### ISSUE TITLE
Trinity 'whiteout' when Firefly is running.

### ISSUE THREAD

**Issue by WillHawkMuc** [iotaledger/firefly#1003]
## Issue description

When trying to start Trinity while Firefly was running, Trinity got stuck on a white screen and had to be killed.
![image](https://user-images.githubusercontent.com/75979295/115689863-c6a5b780-a35c-11eb-92dc-d163a7e49757.png)

## Wallet version

RC

## System specification

Windows 10

## Is it a repeatable issue?

It happened again, when I had TZrinity open during the migration. 
After successful migration in Firefly, Trinity went white again.

## Steps To reproduce the issue

Only one Account - cannot migrate twice to test.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by Tombaaa** [comment]
can you please past your diagnostics (in firefly)
![image](https://user-images.githubusercontent.com/77152394/115854000-130af900-a42a-11eb-8730-8625daa5fd62.png)

**Comment by Tombaaa** [comment]
you seem to have a different issue than me (I suspect mine is because of an ä in the user path. Have you tried to use English as Firefly language?

**Comment by WillHawkMuc** [comment]
Yes, first of all, Trinity has a white screen, not Firefly - not sure how changing language in Firefly will help.
Also I am unable to reproduce this, as it happened during migration and I don't have any more seeds to migrate.

**Comment by antalm** [comment]
This is a Trinity bug, not Firefly. Also Trinity reaches its end of life in 4 days, so I doubt it should be fixed.

**Comment by cvarley100** [comment]
Thanks @WillHawkMuc. We won't fix anything in Trinity going forwards.
