### ISSUE TITLE
Firefly does not finish migration

### ISSUE THREAD

**Issue by isma139** [iotaledger/firefly#1007]
I am following step by step https://blog.iota.org/chrysalis-migration-process/, however when I put the seed 81 characters and firefly accepts, it is loading and the screen is blue and does not continue.

**Comment by isma139** [comment]
I checked that it can be time consuming due to having too many addresses spent on the seed, but I spent a lot of time waiting for the blue screen and nothing. I think it's best to send it to an exchange for now if that's the case.

**Comment by rajivshah3** [comment]
Hi, can you post a screenshot of the blue screen? Are any messages showing?

**Comment by MiKeF05** [comment]
@isma139 Have you already migrated your tokens?
