### ISSUE TITLE
password

### ISSUE THREAD

**Issue by osum8** [iotaledger/firefly#1014]
## Issue description

Briefly describe the issue.

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by osum8** [comment]
I migrated from Trinity to Firefly and created my profile and password, but now the backup requires that password and Firefly says it is incorrect. I try to change my password and that doesn't work either now because my old password is incorrect but it isn't. Now I try to do anything in the app that requires a password and I can't. What do I do?

**Comment by Wondermike2000** [comment]
It may well be that you still activated the Caps Lock key when setting the password. Because you entered the seed just before that. Try out your normal password and press beforehand caps lock

**Comment by Amirmohsenkbit** [comment]
When importing syd81 digits, the wallet will not be displayed please help

**Comment by rajivshah3** [comment]
@osum8 did turning off caps lock fix the issue? We're adding a warning in the next version (#1018)

**Comment by osum8** [comment]
yes it did, and I changed password and new one is working as of now, we'll see by thrusday
