### ISSUE TITLE
Pin Input Error

### ISSUE THREAD

**Issue by hoangkara** [iotaledger/firefly#1024]
Each time user tries to input pin, they cannot seamlessly type their pin.  They have to click each dot to enter a number.  Then there is a message that says wrong pin.  User cannot gain access to their own wallet due to this error.

**Comment by Amirmohsenkbit** [comment]
When importing syd81 digits, the wallet will not be displayed please help

**Comment by MiKeF05** [comment]
@hoangkara Which OS do you use?

**Comment by Amirmohsenkbit** [comment]
W10

**Comment by Amirmohsenkbit** [comment]
In the past, with Trinity with Valan for Firefly with Windows 10

**Comment by cvarley100** [comment]
@hoangkara please can you provide details of your Operating System and if possible, a video of this happening on a new profile?

**Comment by hoangkara** [comment]
I use Windows, but the problem is resolved now thank you.  I restarted the wallet app

Sent from Yahoo Mail on Android 
 
  On Thu, Apr 29, 2021 at 5:50 AM, Charlie ***@***.***> wrote:   


@hoangkara please can you provide details of your Operating System and if possible, a video of this happening on a new profile?

**Comment by Latorlince** [comment]
Buenas tardes. Creo que me he olvidado la contraseña que piden para hacer cualquier cosa en Firefly.
Cómo puedo solucionarlo?

**Comment by MiKeF05** [comment]
@Latorlince You can restore your profile with the 24 words and set a new password.
