### ISSUE TITLE
profil löschen

### ISSUE THREAD

**Issue by cinomat** [iotaledger/firefly#1025]
angelegtes Profil lässt sich nicht löschen
firefly neu installieren brachte auch kein Erfolg

**Comment by cvarley100** [comment]
Hey. Please open issues in English only. The dev team does not speak German unfortunately.

**Comment by MiKeF05** [comment]
The issue is that the created profile in Firefly can´t be deleted. @cinomat Do you only have one profile? Is this issue still present?

**Comment by cinomat** [comment]
yes, is still present, only one profil. i can create another profil and
delete but the first created is not posible....thx

MiKeF05 ***@***.***> schrieb am Mo., 26. Apr. 2021, 20:52:

**Comment by cinomat** [comment]
Tue, 27 Apr 2021 18:11:56 GMT
ClientError: {}

Tue, 27 Apr 2021 18:11:35 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/addresses/iota1qppzgrxdlrd6e5uyj3anwuylkpsuv54x39nu0sekzgjj9yh5zvzzz9mfgjk/outputs): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

**Comment by rajivshah3** [comment]
This sounds like the intended behavior. If you've only created one profile, then you need to reset the wallet instead of deleting the profile
