### ISSUE TITLE
withdraw to firefly 

### ISSUE THREAD

**Issue by mazi313** [iotaledger/firefly#1028]
## Issue description
Cannot withdraw funds from binance to put in firefly, my address to receive does not work. and cannot refresh for a different one.
Briefly describe the issue.

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by Travetown** [comment]
Firefly is available for the new network from April 28th.  until then you can only receive and send with Trinity.  From April 28th  you can only pay out from Biance if Biance has switched to the new network.

**Comment by cvarley100** [comment]
As @Travetown mentioned - exchanges will start supporting Chrysalis and Firefly from the 28th of April.

**Comment by Operateam72** [comment]
No updates on when binance will start supporting Firefly?
