### ISSUE TITLE
Firefly Wallet funktioniert nicht 

### ISSUE THREAD

**Issue by JD-EIC** [iotaledger/firefly#1029]
Ich kann weder mein altes Firefly Wallet über die Recovery Phrase wiederherstellen  (weiße Seite erscheint) noch ein neues wallet einrichten (nach Eingabe eines Passwortes erscheint eine weiße Seite) - dann geht nichts mehr 
Firefly v1.0.0
Plattform: win32
Plattformversion: 10.0.19041
Plattform-Architektur: x64
CPU-Anzahl: 2
Gesamtspeicher: 4006.1 MB
Freier Speicher: 568.2 MB
Benutzerpfad: C:\Users\Jörg\AppData\Roaming\Firefly

**Comment by Travetown** [comment]
Es liegt wahrscheinlich an dem Umlaut im Deinem Namen. Der Fehler ist wohl schon behoben und sollte mit der nächsten Version nicht mehr vorkommen. 
Im Moment kannst Du nur versuchen, Dich mit einen anderen Benutzer an dem Rechner anzumelden, der kein Umlaut hat. Dann sollte es funktionieren.

**Comment by JD-EIC** [comment]
Ich habe aber keinen Umlaut in meinem Benutzernamen.

**Comment by cvarley100** [comment]
Hey. Please open issues in English only. The dev team does not speak German unfortunately.

**Comment by Tombaaa** [comment]
Dear Jörg
I have the same issue, my user directory has a ä in its name, as you have the ö for Jörg
C:\Users\Jörg\AppData\Roaming\Firefly

**Comment by MiKeF05** [comment]
This issue is the same like #1015 and will be fixed with #1017.

**Comment by rajivshah3** [comment]
Closing as duplicate of #1015
