### ISSUE TITLE
Optimize language support (EU/German)

### ISSUE THREAD

**Issue by YokoTheDuke** [iotaledger/firefly#1030]
## Description

In FF 1.0.0, after set language German a GUI part still appears in Anglo-Saxon currency and time.

10,000 Gi VS 10.000 Gi
am 7:30 VS 19:30

<img width="797" alt="Firefly-GUI" src="https://user-images.githubusercontent.com/32335666/116137386-c4808780-a6d3-11eb-9950-9eda1c063982.png">

## Motivation

A nice and professionell GUI like in the Firefly App should be perfect in all little corners. ;)

## Requirements

Should be clear.

## Open questions (optional)

Use this section to ask any questions that are related to the feature.

## Are you planning to do it yourself in a pull request?

No.

Thanks for your support!

**Comment by maxwellmattryan** [comment]
Hey @YokoTheDuke, thanks for the suggestion. I would also prefer it in 24-hour time 😅 
I've moved this issue into a discussion [here](https://github.com/iotaledger/firefly/discussions/1509) 👍
