### ISSUE TITLE
Creating new Receiving address - nothing happens

### ISSUE THREAD

**Issue by ChristopherWalz** [iotaledger/firefly#1034]
## Issue description

Creating new Receiving address - nothing happens

## Wallet version

Which version of wallet are you using?

1.0.0

## System specification

What is your operating system?

Windows

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Click "Receive"
2. Click the arrow icon
3. Check error log

## Expected behaviour

Create and show new receive address

## Actual behaviour

Nothing happens

## Errors

```
Tue, 27 Apr 2021 14:59:43 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/addresses/iota1qq68xnd2h5y523z8k78sl3smt8udewhnlmaccv0axv8hmv4n8akrc8kgsxj/outputs?include-spent=true): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`
```

**Comment by MiKeF05** [comment]
Since the network starts tomorrow (28th april) it is not possible to generate a receive address. This will be available with the start of the network on 28th april.

**Comment by cvarley100** [comment]
You can only generate a new receive address once you have used the previous one. This is to prevent wasting unused addresses and makes it easier for Firefly to find your funds when restoring from a Recovery Phrase.

**Comment by ChristopherWalz** [comment]
> You can only generate a new receive address once you have used the previous one. This is to prevent wasting unused addresses and makes it easier for Firefly to find your funds when restoring from a Recovery Phrase.

Makes sense. But then there should be some notification when this case occurs.
