### ISSUE TITLE
Firefly in Mac OSX sierra 10.12.6 not open

### ISSUE THREAD

**Issue by Hoopeman** [iotaledger/firefly#1051]
In OSX 10.12.6 not open screen goes blank
![FIREFLY](https://user-images.githubusercontent.com/75945051/116461838-0858c580-a869-11eb-86da-09cd609b5911.png)

**Comment by kmueller** [comment]
See also https://github.com/iotaledger/firefly/issues/897

**Comment by cvarley100** [comment]
Duplicate fo #897
