### ISSUE TITLE
Unable to delete profile

### ISSUE THREAD

**Issue by c-armbrust** [iotaledger/firefly#1054]
I go to all settings, delete profile -> delete profile. After entering my password to confirm it, the red button "yes" becomes enabled. But when clicking the "yes" button it becomes disabled / greyed out and nothing happens after some waiting time. I cancelled the deletion after a while. 
![Capture](https://user-images.githubusercontent.com/2544188/116479165-80ca8100-a87f-11eb-966a-edd8f17165b3.PNG)

**Comment by c-armbrust** [comment]
I should probably add that the profile I tried to delete behaves strange in general:
It successfully migrated before april 28th. But after chrysalis was live and I logged in, it showed still 0Mi and the note "your funds will become available shortly". There is a permanent load symbol / indicator in the "Latest transactions" section.
So I created a second profile from stronghold file. All fine with that, it shows my funds etc. and tried to delete the first one.

**Comment by Xantus-78** [comment]
Cannot delete profile - deleting process shows no result. Furthermore profile shows notice "Network disconnected", while other profiles don't display this notice (btw. these profiles are able to be deleted):

That's the log of the error:

App Version: 1.1.0

platform: macOS
platformVersion: 11
platformArchitecture: x64
cpuCount: 4
totalMem: 8192.0 MB
freeMem: 2271.5 MB
userPath: /Users/Library/Application Support/Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'id' of undefined
    at /private/var/folders/g0/nvv7nsp13hn8zgdllz9682x00000gp/T/AppTranslocation/438D50B7-5660-4FFC-8F95-2AF5F238DF8A/d/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:165586
    at /private/var/folders/g0/nvv7nsp13hn8zgdllz9682x00000gp/T/AppTranslocation/438D50B7-5660-4FFC-8F95-2AF5F238DF8A/d/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:197606
    at Array.forEach (<anonymous>)
    at destroy (/private/var/folders/g0/nvv7nsp13hn8zgdllz9682x00000gp/T/AppTranslocation/438D50B7-5660-4FFC-8F95-2AF5F238DF8A/d/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:197594)
    at /private/var/folders/g0/nvv7nsp13hn8zgdllz9682x00000gp/T/AppTranslocation/438D50B7-5660-4FFC-8F95-2AF5F238DF8A/d/Firefly.app/Contents/Resources/app.asar/public/build/preload.js:2:191379

**Comment by Xantus-78** [comment]
In addition, status of account shows "Network disconnected"

**Comment by MiKeF05** [comment]
This should be solved with the latest release. If you have further issues please reopen this issue.
