### ISSUE TITLE
"Broken" Profile in Firefly

### ISSUE THREAD

**Issue by ghost** [iotaledger/firefly#1057]
I have a broken profile in firefly, where my funds are still migrating. I can't unlock my profile and I can't delete ist. Also the balance finder is running forever.
When I restore this account into another profile all my funds are available and everything works fine.

**Comment by vanvuongngo** [comment]
Hi @griffenpete01, what operation system do you use? I run Linux and had the same broken file. I had to delete all profiles and recreate it, see discord https://discord.com/channels/397872799483428865/748265907351978115/837584444751347773
