### ISSUE TITLE
Cannot migrate a Trinity seed

### ISSUE THREAD

**Issue by Latorlince** [iotaledger/firefly#1058]
## Issue description

Briefly describe the issue.

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by cvarley100** [comment]
What happens when you input the seed?

**Comment by sheepdreamofandroids** [comment]
I have the same problem: after entering a 81 character seed, firefly shows a 0 balance, even after several attempts to Check Again.
Does it need a certain period to download enough of the tangle?
This is quite disturbing since Trinity (which did show the balance a month ago) refuses to start up.

**Comment by Latorlince** [comment]
Ese problema ya lo he resuelto, tenía mal apuntada la semilla. Ya he hecho la transición.
Ahora el tema es que en Firefly llevan tres días con el cambio hecho y todavía no puedo disponer de mis fondos. No sé si es normal.

**Comment by MiKeF05** [comment]
I´m going to close this issue. Feel free to open it again if you have further issues.
