### ISSUE TITLE
Autofill send to/recipient address when clicking on IOTA links in HTML

### ISSUE THREAD

**Issue by samgranger** [iotaledger/firefly#1061]
## Description

Currently, if you create a link in HTML like the example below, Firefly is opened, but nothing else happens. It would be nice if the Send Payment screen would automatically open with the address pre-filled automatically in the "send to" field.

Additionally it would also be nice to be able to specify an amount and possibly even a payload in the future.

```
<a href="iota:iota1qzdq9r0np53yx5aygdremah56vfe3e8hgm2qf7tqz900vu5kvsehy6ez6xq">Pay me</a>
```

## Motivation

It would be a nice feature to have if you have a checkout for example on an ecommerce store so you don't have to copy an address and fill in the amounts yourself. This would improve the user experience and also result in less human errors.

## Requirements

Write a list of what you want this feature to do.

1. Open send to box when clicking on an iota:... link
2. Prefill the send to/recipient address
3. If possible, also look at options to prefilling an amount etc. with params, eg: 
```
<a href="iota:iota1qzdq9r0np53yx5aygdremah56vfe3e8hgm2qf7tqz900vu5kvsehy6ez6xq?amount=100&payload=foobar">Pay me</a>
```

## Are you planning to do it yourself in a pull request?

If wanted, yes.

**Comment by cvarley100** [comment]
This is implemented but currently disabled. There's a PR open for it atm.

**Comment by samgranger** [comment]
Thanks Charlie!
