### ISSUE TITLE
Using account switcher to switch wallets disables delete function

### ISSUE THREAD

**Issue by Kajover** [iotaledger/firefly#1063]
## Issue description

When creating multiple wallets that have no funds, switching through them doesn't let you delete them but just hide them. You need to go back to the overview and click on the specific wallet to be able to delete it again.

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch): v1.0.0

## System specification

What is your operating system?

macOS 11.3 (20E232)

## Is it a repeatable issue?

Yes

**Comment by Kajover** [comment]
Bug persists in v1.1.0

**Comment by MiKeF05** [comment]
This should be solved with the latest release. If the issue still persists please reopen the issue.
