### ISSUE TITLE
ich wurde gehackt, alles wurde vor der migration am 20.04.2021 von meinem trinity wallet gestohlen und ist bist jetzt nicht mehr aufgetaucht.

### ISSUE THREAD

**Issue by andred92** [iotaledger/firefly#1064]
## Issue description

Briefly describe the issue.

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by andred92** [comment]
ich wurde gehackt

**Comment by cvarley100** [comment]
Hey @andred92. It's best to ask in the #help channel on our [Discord](https://discord.iota.org/). The community will help investigating this for you.

**Comment by andred92** [comment]
Sehr lustig ...... Ich möchte meinen kontostand wieder haben!!! Ich gehe
bis in die sozialen Netzwerke mit diesem hack, wenn ich meinen kontostand
nicht sofort wiederbekomme!

Charlie Varley ***@***.***> schrieb am Do., 29. Apr. 2021,
14:09:

**Comment by MiKeF05** [comment]
Ich bin mir sicher, dass nichts gehackt wurde. Du kannst gerne deine IOTA Adresse hier teilen, sodass alles geprüft werden kann. Auf Discord unter #help wird dir mit Sicherheit weitergeholfen.

**Comment by andred92** [comment]
NEIN ES WURDE NICHT GEHOLFEN!!!! ICH WERDE ÜBERALL SCHREIBEN DAS BEI IOTA
HACKER ANGESTELLT SIND

Am Do., 29. Apr. 2021 um 19:31 Uhr schrieb MiKeF05 ***@***.***

**Comment by andred92** [comment]
IHR BETRÜGER HABT EINFACH MEINEN GESAMMTEN KONTOSTAND GELÖSCHT UND
NIRGENDWO BEKOMMT MAN SINE MIOTA ODER SEIN GELD WIEDER!!!

Am So., 2. Mai 2021 um 14:34 Uhr schrieb Andre Zaleyski <
***@***.***>:

**Comment by andred92** [comment]
ich habe gemacht was sie geschrieben haben und habe mich bei discord mit
vielen unterhalten. dort geht im allgemeinen rum, dass hacker bei iota
unterwegs sind.

Am So., 2. Mai 2021 um 14:36 Uhr schrieb Andre Zaleyski <
***@***.***>:
