### ISSUE TITLE
ACHTUNG HACKER SIND UNTERWEGS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by andred92** [iotaledger/firefly#1065]
## Issue description

Briefly describe the issue.

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by cvarley100** [comment]
Hey. Please can you join the [Discord](https://discord.iota.org/) so we can discuss this with you.

**Comment by nothingismagick** [comment]
Wir wollen helfen, aber die Issue Board auf Github ist nicht den richtigen Ort dafür. Bitte verbinde Dich mit Charlie auf Discord - oder z.B. Antonio wenn Deutsch gesprochen werden soll.
