### ISSUE TITLE
Migration to Chrysalis wallet.

### ISSUE THREAD

**Issue by Huascarsefard** [iotaledger/firefly#1066]
I can not get my balance from Trinity to Firefly wallet. How to do it?

**Comment by cvarley100** [comment]
Hey. It's best to join the [Discord](https://discord.iota.org/) and ask in the #help channel about these sorts of things.

**Comment by Huascarsefard** [comment]
Sorry but Discord does not accept the invitation. I am really worry about
my balance. Thack you.
