### ISSUE TITLE
Issue with migration

### ISSUE THREAD

**Issue by LV1830** [iotaledger/firefly#1067]
## Issue description

Migrating to the new network, Firefly is stuck transferring my funds on the Migrate Your funds page, I hit the button to begin the migration, but it's not going anywhere, had been already 40 minutes and the Migrating funds icov is just turning constantly but I don't get the message that is completed, it seems stuck and I'm worries funds are lost in limbo...

## Wallet version

Migrating from Trinity 1.6.2 to Firefly

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Windows

## Is it a repeatable issue?

stuck in migrating funds, nothing happens

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Begin migration, stuck at the Migrate your funds page when I hit begin transfer
2.
3.

## Expected behaviour

Migration to be completed in few minutes, but it has been more then 40 mins and it's still  not completed

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by dcts** [comment]
Had the same issue, did you resolve it @LV1830 ? My firefly crashed and I had to close it, after restart the funds show to be migrated on the tangle explorer but no account with the new private key.... 

Are they gone forever? Lost in Limbo? :(
