### ISSUE TITLE
Profile says "Your funds will become available shortly" but funds are available with no transaction history

### ISSUE THREAD

**Issue by jdesopo** [iotaledger/firefly#1068]
## Issue description

When I log into the one particular profile (I have a few) a message appears "Your funds will become available shortly".  I can dismiss the message and unlock the wallet with the passcode, but the send/receive buttons are disabled.  Nevertheless, I can send/receive via the menu drop down (not the buttons) and it works! The funds are available as I've transferred them back and forth to other wallets within that profile, and wallets from another profile.  They are transferring fine.  No transaction history appears under "latest transactions" area for that particular profile/wallet though. 

## Wallet version

Which version of wallet are you using?

Firefly v1.0.0
Language: en
Currency: USD
Node settings: Automatic node selection
Platform: win32
Platform Version: 10.0.19042
Platform Architecture: x64
CPU Count: 8
Total Memory: 16093.7 MB
Free Memory: 5938.6 MB
User Path: C:\Users\[userID]\AppData\Roaming\Firefly

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

I don't know - it seems to be one profile I have.  All the other profiles seem to operate fine - so I cannot reproduce it.  Logout out Login does not fix it. 

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

This profile should act like all the other profiles

## Actual behavior

Describe what actually happens.

As described above

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

![image](https://user-images.githubusercontent.com/51210514/116558083-ecc6dc80-a8b3-11eb-864e-3a763abd4e94.png)

**Comment by t00k** [comment]
You can remove the profile and re-add it using the 24 phrases again. For some users it seemed like it got stuck and thinking your funds werent available yet. So remove the profile (make sure you know which 24 phrases belongs to that profile) and just re-add it, and it should be fixed.

**Comment by jdesopo** [comment]
Thank you!  Worked like a charm...  All good now.  I love this.
