### ISSUE TITLE
Problem with a PIN profile

### ISSUE THREAD

**Issue by Mcjevo** [iotaledger/firefly#1069]
Hi, from this morning i have aproblem with mi wallet. My PIN doesn´t works. Finally I have to create a second profile and recover my wallet with my IOTA´s. But I´m so worried because the PIN of that first profile this morning worked well and now is not working. So I would like to delete that profile becuase I think that is a direct access to my coins and if someone has changed my PIN now he can send my coins to other account.

Sorry for mi english. It´s not my native language

**Comment by etiiiR** [comment]
I have the same problem, my Pin is not working anymore.

**Comment by t00k** [comment]
@Mcjevo In the current version that is an issue with the language and currency when using other languages. Please try changing the language back to English and restart Firefly, and see if you can login to your first profile.

Then please continue to use Firefly in english until new version is released.

And about;  _if someone has changed my PIN now he can send my coins to other account._
This is not possible. You need the stronghold password to send funds. So your funds are safe.

**Comment by Mcjevo** [comment]
> @Mcjevo In the current version that is an issue with the language and currency when using other languages. Please try changing the language back to English and restart Firefly, and see if you can login to your first profile.
> 
> Then please continue to use Firefly in english until new version is released.
> 
> And about; _if someone has changed my PIN now he can send my coins to other account._
> This is not possible. You need the stronghold password to send funds. So your funds are safe.

I changed the languaje and restart the wallet app and I have the same problem, My PIN doesn´t works and I finish with the message of "3 incorrect attemps" and i have to wait.


I suppose that the password cannot be changed from the settings of this profile.

By the way, another user write to me that have the same problem with the PIN today, but here I can´t see the reply. Sotrry is the first time taht y write in Hitub 

Anyway, Thank you very much for you Reply  tOOk and sorry again for my english.

**Comment by t00k** [comment]
Okay, I helped a user earlier today and the language was his issue.

No need to say sorry for your english. Also, there is no risk about your funds with the first profile.

If you have your 24 phrases and the stronghold backed up you can re-install Firefly wallet and setup a new profile with those 24 phrases.

As long as you have your 24 phrases or the stronghold you can always access your IOTA.

Are you using Windows?

**Comment by Mcjevo** [comment]
Yes I´m using Windows 10. Really, instead of re-install the app I opened a new profile and I selected recovere the wallet with the 24 phrases and I could see that all it´s ok. Althouhgt I would like to delete that first profile to avoid risk, but for delete that profile I believe that I can to access fist with the PIN :).

**Comment by t00k** [comment]
Yes, but the only way to remove the first profile is to get access to it first, which you will probably not be able to.

What you can do is to browse into _C:\Users\Username\AppData\Roaming\Firefly_ and remove that Firefly folder. This will remove Firefly from your computer and let you re-install it. Then you just setup with the same 24 words again (as you did with your second profile) and you will see the funds again, and only have one profile.

**Comment by Mcjevo** [comment]
Well, thank you very much T00k. your solution has worked well. 

I was able to delete the profile and everything is fine.

 Thanks a lot.

**Comment by t00k** [comment]
Happy to hear. Can you please mark this issue as solved here on github?

Have a great night!
