### ISSUE TITLE
FireFly 1.0.0 on ubuntu 20.04 only displays a blank white screen 

### ISSUE THREAD

**Issue by alaakaazaam** [iotaledger/firefly#1072]
## Issue description

On linux 'Ubuntu 20.04.2 LTS ', the cmdLine './firefly-desktop-1.0.0.AppImage &' starts the wallet with a blank screen and nothing else happens

## Wallet version

firefly-desktop-1.0.0 from https://firefly.iota.org/ (which points to https://iotaledger-files.s3.eu-central-1.amazonaws.com/4a1ddea1-10c1-4f1d-83f0-e14903931a46/releases/firefly-desktop-1.0.0.AppImage)

## System specification

$ cat /etc/issue
Ubuntu 20.04.2 LTS \n \l
$ uname -a
Linux ste64 5.4.0-47-lowlatency #51-Ubuntu SMP PREEMPT Fri Sep 4 20:46:20 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

## Is it a repeatable issue?

Yes it is

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. give execution right : chmod 775 ./firefly-desktop-1.0.0.AppImage
2. run it with simple cmdline : ./firefly-desktop-1.0.0.AppImage &
3.

## Expected behaviour

One would expect the wallet screen to show a wizard for creating the account (as on windows)

## Actual behaviour

Wallet only displays a blank white screen

## Errors
In my terminal console
20:47:35.506 › Checking for update
20:47:41.014 › Update for version 1.0.0 is not available (latest version: 1.0.0, downgrade is disallowed).

**Comment by eKing021** [comment]
same
Mac 10.13.6
Firefly 1.0.0

**Comment by rajivshah3** [comment]
Hi, can you please try on the latest version to see if any error messages are shown?

**Comment by alaakaazaam** [comment]
At first try, i got this : 
App Version: 1.1.0

platform: linux
platformVersion: 5.4.0-47-lowlatency
platformArchitecture: x64
cpuCount: 2
totalMem: 4808.9 MB
freeMem: 110.8 MB
userPath: /home/stephane/.config/Firefly

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_INTERNET_DISCONNECTED
![erreur_firefly_1 1 0](https://user-images.githubusercontent.com/6622814/116780386-bab4a680-aa7c-11eb-878a-2eacf320a167.png)



Then each launch gets a blank screen, even if i delete .config/Firefly folder to get a clean config

**Comment by rajivshah3** [comment]
Do you have `libsecret` and `gnome-keyring` installed?

**Comment by alaakaazaam** [comment]
Hi, i was missing libsecret-dev & libsecret-tools.
Installed them, rebooted but issue still there..

Here are my installed packages : 

dpkg -l |grep **libsecret**
ii  libsecret-1-0:amd64                                         0.20.3-0ubuntu1                             amd64        Secret store
ii  libsecret-1-dev:amd64                                       0.20.3-0ubuntu1                             amd64        Secret store (development files)
ii  libsecret-common                                            0.20.3-0ubuntu1                             all          Secret store (common files)
ii  libsecret-tools                                             0.20.3-0ubuntu1                             amd64        tool for storing and retrieving GObject passwords


dpkg -l |grep **keyring**
ii  brave-keyring                                               1.9                                         all          Brave Browser keyring and repository files
ii  gnome-keyring                                               3.36.0-1ubuntu1                             amd64        GNOME keyring services (daemon and tools)
ii  gnome-keyring-pkcs11:amd64                                  3.36.0-1ubuntu1                             amd64        GNOME keyring module for the PKCS#11 module loading library
ii  libgnome-keyring-common                                     3.12.0-1build1                              all          GNOME keyring services library - data files
ii  libgnome-keyring0:amd64                                     3.12.0-1build1                              amd64        GNOME keyring services library
rc  libp11-kit-gnome-keyring:i386                               3.10.1-1ubuntu4.2                           i386         GNOME keyring module for the PKCS#11 module loading library
ii  libpam-gnome-keyring:amd64                                  3.36.0-1ubuntu1                             amd64        PAM module to unlock the GNOME keyring upon login
ii  python3-keyring                                             18.0.1-2ubuntu1                             all          store and access your passwords safely - Python 3 version of the package
ii  python3-keyrings.alt                                        3.4.0-1                                     all          alternate backend implementations for python3-keyring
ii  ubuntu-keyring                                              2020.02.11.4                                all          GnuPG keys of the Ubuntu archive

**Comment by hristo-mavrodiev** [comment]
Strange, on Ubuntu 20.04 Desktop Live DVD image, just downloaded and run the app with no issues. Can you share more details of your Ubuntu installation. Is it the server or desktop installation?  Are they any security modifications that you have done? How can we reproduce your environment? Can you run the appimage with ``--no-sandbox`` argument?

**Comment by alaakaazaam** [comment]
Hi, as the --no-sandbox parameter didn't bring any more elements to share, i did same as you and installed firefly on another totally fresh laptop, right now my old ubuntu desktop seems messy as hell, guess i tweaked a little too much my configs by the past (it's a dev machine) : its finally working on the new one.
Thanks for the effort, you can close the issue
