### ISSUE TITLE
Firefly Stuck After Entering Pin

### ISSUE THREAD

**Issue by MauritzBotma** [iotaledger/firefly#1073]
## Issue description

Firefly is stuck after entering pin. Left it and it reverts back to the profile screen without any error message.

## Wallet version

Firefly 1.0.0

## System specification

Windows 19042.928

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.Open Firefly
2. Select profile
3. Enter pin

## Expected behaviour

Open the wallet UI.

## Actual behaviour

Stuck on-screen after pin.
![Snipaste_2021-04-29_20-43-09](https://user-images.githubusercontent.com/69192896/116604724-ca25d980-a92e-11eb-9d37-a17c1b794981.png)

## Errors

No errors or messages are provided

**Comment by Remerk** [comment]
Same thing happens to me!! Just keeps running....

**Comment by Malt1985** [comment]
Yep. Same over here been trying for 2 days now and no result.

**Comment by colinkinn** [comment]
Same thing for a day now.  If you bypass the loading screen by going to settings it states no wallets found and all funds show zero.

**Comment by MauritzBotma** [comment]
I have managed to get a workaround by just creating a new profile but I cannot delete the original profile.

**Comment by JTAOHW** [comment]
Here the same, re-installing will not help either.

**Comment by colinkinn** [comment]
The latest Firefly update seems to have resolved this issue

**Comment by Remerk** [comment]
Yes! New uodate seems to have this sorted!

**Comment by MauritzBotma** [comment]
Thanks
