### ISSUE TITLE
Show complete count of tokens

### ISSUE THREAD

**Issue by tolotos-rgu** [iotaledger/firefly#1076]
Firefly 1.0.0 on Windows shows the amount of tokens like x.uvw Gi. How can I find out the complete number of tokens I own? 
Can you please add a funktion to show the complete count of tokens?

**Comment by Phyloiota** [comment]
Really like that idea.
A work around for now will be like this:
Create a second wallet in your profile, use the send funktion, click on "Max" and set it to show "i"
So you will be able to see all Iotas.
But i think the same switch can be applied to the total balance view 
![image](https://user-images.githubusercontent.com/77154511/116627649-1b11ee00-a980-11eb-9bf5-ff7d0f4f193d.png)

**Comment by antalm** [comment]
Another workaround can be to click on the wallet, the  ... on top right, then View address history.
If you have all your funds on a single address, then you can see it with proper precision.
If you have it on multiple addresses, then unfortunately you need to manually add them or use the send max method as mentioned above.
But I would like to be able to click on the balance to change its precision similar to the way it worked in Trinity.
