### ISSUE TITLE
blank white page

### ISSUE THREAD

**Issue by eKing021** [iotaledger/firefly#1078]
Mac 10.13.6
Firefly 1.0.0
Never installed beta or lower ver.

**Comment by Sor3nt** [comment]
Same here :(

**Comment by Niikklas** [comment]
I have the same problem

**Comment by MrRo-de** [comment]
Same here, but the first beta worked fine.

**Comment by rajivshah3** [comment]
Hi, this should be resolved in the latest version which now supports macOS 10.12 and later
