### ISSUE TITLE
gpg and asc files for code verfcation are missing

### ISSUE THREAD

**Issue by cristi1941** [iotaledger/firefly#1082]
## Issue description

To Verify your Firefly desktop download for LInux the following is mentioned on  https://chrysalis.docs.iota.org/firefly/verify_download.html: 

Download the .asc and .gpg files in the Assets section of the release notes

I cant find any gpg / asc files in the assets section.

## Wallet version

Which version of wallet are you using?

firefly-desktop-1.0.0.AppImage

## System specification

What is your operating system?

Linux

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by rajivshah3** [comment]
Hi, this is now uploaded in the latest release (1.1.0)
