### ISSUE TITLE
"Something Went Wrong" message after introducing Profile Name. White Screen After Importing Seed Vault.

### ISSUE THREAD

**Issue by tomecosta** [iotaledger/firefly#1085]
## Issue description

After Downloading and installing Firefly from https://firefly.iota.org/
Error: "Something Went Wrong" Pop-up after introducing Profile Name. White Screen After Importing Seed Vault.

## Wallet version

Firefly Version 1.0.0 downloaded from https://firefly.iota.org/

## System specification

Windows 10

Win/  10.0.18363 

## Is it a repeatable issue?

Yes, happens all the time I try to create any profile

## Steps To reproduce the issue

Reproduce the issue.

1.Open Firefly
2.Introduce the Profile name (Mine: Tomco) and error appears: "Something went wrong".
3.Import SeedVault .kdbx file and White Screen Appears. After few minutes on the white screen my Firefly closes automatically.

## Expected behaviour

Create Profile and Import SeedVault 

## Actual behaviour

Error, White Screen and SeedVault not imported

## Errors

![image](https://user-images.githubusercontent.com/37813543/116716767-6e178f80-a9d8-11eb-8479-60de3875bf57.png)

![image](https://user-images.githubusercontent.com/37813543/116716865-8c7d8b00-a9d8-11eb-9f59-8ec2488ac4d5.png)

**Comment by rajivshah3** [comment]
Hi, can you please try with the latest version (1.1.0)?

**Comment by tomecosta** [comment]
@rajivshah3 yes, it works perfectly with the new 1.1.0 version

**Comment by rajivshah3** [comment]
Great! I'll close this issue
