### ISSUE TITLE
Blank Window

### ISSUE THREAD

**Issue by Zietez** [iotaledger/firefly#1088]
## Issue description

A blank window.

## Wallet version

- Firefly 1.1.0

## System specification

Linux
openSUSE Leap
Ver. 15.2 de 64 bits
Kernel Linux 5.3.18-lp152.72-default x86_64
MATE 1.24.0
Mem : 7.5 G
CPU: AMD Athlon(tm) II X2 245 Processor × 2 
Graphic : NV4C

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Open the app
2. wait and ...
3. big blank window.

## Expected behaviour

Describe what you expect to happen.

Working it.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.
![screenshot14](https://user-images.githubusercontent.com/83484415/116769112-70d9ab00-a9ff-11eb-8319-bc94d34667e1.png)
![screenshot15](https://user-images.githubusercontent.com/83484415/116769113-71724180-a9ff-11eb-92d2-76f3eb7244ab.png)

**Comment by hristo-mavrodiev** [comment]
Can you try to run it with the argument ```--disable-gpu```?

**Comment by Zietez** [comment]
./firefly-desktop-1.1.0.AppImage --disable-gpu

the same blank window.

**Comment by hristo-mavrodiev** [comment]
Can you try with:
```./firefly-desktop-1.1.0.AppImage --ignore-gpu-blacklist```
Electron have some reported issues with black screen when try to run with hardware acceleration. What is your GPU and do you have installed GPU drivers? 
Can you try to run the this command in Chrome:
```
chrome://gpu/
```

![image](https://user-images.githubusercontent.com/61916767/119043442-b7e50b80-b9c1-11eb-93c3-af4ee1921ef0.png)
Could be a GPU driver issue.

**Comment by Zietez** [comment]
This is the result of the configuration. What can be done. I have six applications with the extension ".AppImage" and they all work correctly, including the "trinity-desktop-1.6.1.AppImage".
![screenshot14](https://user-images.githubusercontent.com/83484415/119158556-f1e2fb80-ba1b-11eb-8cef-f28ea49ef2d3.png)

**Comment by hristo-mavrodiev** [comment]
Could you share report from ```lscpu``` ? Could be because of your cpu doesn't support sse/ssse/avx instructions?

**Comment by Zietez** [comment]
![screenshot14](https://user-images.githubusercontent.com/83484415/122104203-0b8a1f80-cddd-11eb-988d-dc8aabbff0cf.png)

**Comment by hristo-mavrodiev** [comment]
Your CPU doesn't support ssse3 sse4_1 sse4_2 fma avx instructions. The Appimage is compiled  with github actions and the machine have more modern CPU:

Run lscpu >> lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  1
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz
Stepping:            4
CPU MHz:             2095.077
BogoMIPS:            4190.15
Hypervisor vendor:   Microsoft
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            36608K
NUMA node0 CPU(s):   0,1
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt avx512cd avx512bw avx512vl xsaveopt xsavec xsaves md_clear

if you unzip the Appimage files and dissassebly `desktop` file `objdump -d desktop > YOURFILE.asm`, there are ssse3, sse4, avx instructions inside it.
https://stackoverflow.com/questions/47878352/how-to-check-if-compiled-code-uses-sse-and-avx-instructions
Your CPU don't know how to interpret this instructions. So probably developers could try to change the github actions file to compile the build for older CPUs or add checks and messages for unsupported hardware.

You can try to build it from sources - https://github.com/iotaledger/firefly/tree/develop/packages/desktop

**Comment by Zietez** [comment]
firefly-desktop-1.2.0.AppImage. same same ..... 21/04/2022 ... same 21/04/2023 ... same ?

**Comment by rajivshah3** [comment]
Hi @Zietez , we're looking into the issue regarding SSE4 instructions. Just out of curiosity, does any console output appear when you do `./firefly-desktop-1.2.0.AppImage` in the terminal? Also, does it work if you do `./firefly-desktop-1.2.0.AppImage --ignore-gpu-blacklist`?
