### ISSUE TITLE
Invalid certificate error

### ISSUE THREAD

**Issue by hanspetzer** [iotaledger/firefly#1089]
## Issue description

Invalid certificate error when trying to connect to a custom node

## Wallet version

Which version of wallet are you using?

- 1.1.0 Win

## System specification

What is your operating system?

Win

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

add custom public node "https://hanspetzersnode.at" and set as primary

## Expected behaviour

Firefly connects to node

## Actual behaviour

Firefly gives a certificate error

## Errors

![Bild_2021-05-01_095643](https://user-images.githubusercontent.com/31186027/116775490-884a7f80-aa63-11eb-8acc-871bc864832d.png)

**Comment by uwec** [comment]
@hanspetzer  di dyou install your node with Nuriels "playbook"? If so run an update via horc (version 1.0.2) and the issue is fixed. It seem it s a nginx configuration issue and not a bug of Firelfy.

**Comment by hanspetzer** [comment]
> @hanspetzer di dyou install your node with Nuriels "playbook"? If so run an update via horc (version 1.0.2) and the issue is fixed. It seem it s a nginx configuration issue and not a bug of Firelfy.

Thanks for the tip. I don't use palybook but I use nginx as rate limiter. My ssl configuration was a little outdated since I've been using it for a while, the main problem was that I used the cert.pem instead of the fullchain.pem in the config.
Now everything works, thanks!
