### ISSUE TITLE
Two profiles - Locked wallet

### ISSUE THREAD

**Issue by Rowski90** [iotaledger/firefly#1093]
Hey! 
Can someone help me with my issue. 

Firefly Wallet version 1.1.0.

1) So I made the migration from Trinity Mobile to Firefly desktop. 
2) Then I accidently first selected: "Create new wallet" to Firefly. After the process I added "new profile" and then selected the correct "Migrate or Restore a wallet" -option. 
3) I use the seed from Trinity Mobile
4) I took passphrases etc and created passwords like in the first session.
5) It did not let me to select the stronghold like it did in the first session, but I think that is normal?.
6) Migration was all good and I am able to enter with my pincode and see the balance which is correct
7) Problem is that in this profile2 I created, I am not able to open the locked wallet. It says incorrect password. In profile1 that I created I am able to do that...

Hopefully you have experience like this and can help me, thanks!

**Comment by jaskoervin** [comment]
I can not login in to my wallet ,I NEED A PIN THAT I DON'T REMAMBER TO PUT ONE , SO I TRY TO DO EXACTLY WHAT YOU DO AND I HAVE THA SAME PROBLEM WITH THE PASSWORD

**Comment by Phyloiota** [comment]
Rowski - you are fine - the other profile will not be able to access i would say.
Jaskoervin:
Use the "Add Profile" Function, use your saved 24 menoric Phrase or the saved Stronghold backup fiel from the first profile creation and restore the wallaet using one of teose methods. In this process you can create new Passwords and Pin - keep them savely stored

**Comment by Rowski90** [comment]
> Rowski - you are fine - the other profile will not be able to access i would say.
> Jaskoervin:
> Use the "Add Profile" Function, use your saved 24 menoric Phrase or the saved Stronghold backup fiel from the first profile creation and restore the wallaet using one of teose methods. In this process you can create new Passwords and Pin - keep them savely stored

Any idea Phyloiota how to unlock that profile? Or should I first shut the first one?

**Comment by MiKeF05** [comment]
@Rowski90 Were you able to solve your issue?

**Comment by Rowski90** [comment]
> @Rowski90 Were you able to solve your issue?

Hi Mike,

yes it was solved with the help I received from phyloiota. 

"Use the "Add Profile" Function, use your saved 24 menoric Phrase or the saved Stronghold backup fiel from the first profile creation and restore the wallaet using one of teose methods. In this process you can create new Passwords and Pin - keep them savely stored"
