### ISSUE TITLE
pin request

### ISSUE THREAD

**Issue by jaskoervin** [iotaledger/firefly#1094]
## Issue description

Briefly describe the issue.

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.
I download firefly wallet , I put my seed  ,  wait 24 h to start working and after I check my wallet to see if I have access, but he ask me for pin that I do not remember to put one when I create this profile...what can I do to have access to my wallet again?

**Comment by MiKeF05** [comment]
@jaskoervin Were you able to solve your issue? You can always restore your profile with the 24 words. There you are able to set a new PIN
