### ISSUE TITLE
Refresh / create another Receive Address doesn't work

### ISSUE THREAD

**Issue by mgeier63** [iotaledger/firefly#1096]
## Issue description

When clicking the 
![image](https://user-images.githubusercontent.com/5276926/116786324-2f610280-aac8-11eb-9ede-14be13d47d0b.png)
icon in "Receive Funds", it spins for a few seconds but the "My Address" and the QR-Code do not change.

## Wallet version

Which version of wallet are you using?

1.1.0

## System specification

Xubuntu 20.04

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Create a wallet
2. Click on "Receive"
3. Click on ![image](https://user-images.githubusercontent.com/5276926/116786324-2f610280-aac8-11eb-9ede-14be13d47d0b.png)

## Expected behaviour

A new receiving address is generated and displayed

## Actual behaviour

Nothing happens

## Errors

Nothing in the log

**Comment by MiKeF05** [comment]
Did you already use the address that is displayed? Since the addresses are reusable with Chrysalis you don´t have to generate a new address with every time you would like to send.

**Comment by mgeier63** [comment]
No, but having multiple receiving addresses per profile/seed is a valid use case - as you may want to hand out different addresses for different "payment channels" you're expecting.
I guess that's why the "refresh" button is there in the UI in the first place, it's just that it doesn't work.

**Comment by Travetown** [comment]
> No, but having multiple receiving addresses per profile/seed is a valid use case - as you may want to hand out different addresses for different "payment channels" you're expecting.
> 
> I guess that's why the "refresh" button is there in the UI in the first place, it's just that it doesn't work.

maybe in this case it would be even clearer if you created separate accounts within the profile.
