### ISSUE TITLE
After migration 3 days ago from Trinity wallet, I still have the message "your funds will be available soon". Wallet using Firefly V1.1.0

### ISSUE THREAD

**Issue by trinitylight** [iotaledger/firefly#1100]
## Issue description

Briefly describe the issue.

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by WernerderChamp** [comment]
Have you tried scanning for your funds?
You can access this by clicking on your account symbol (bottom left corner), select "All settings" and then "Balance finder".
This should hopefully fix the error. If not, please join the [Official IOTA Discord](https://discord.iota.org/) and ask for help in the #help channel

**Comment by Phyloiota** [comment]
check in your Trinity Wallet if your balance is out of Trinity and sent to an address starting with "TRANSFER..." Copy this transaction into here https://explorer.iota.org/legacy-mainnet - if it shows “confirmed”, your balance is correct and you have a backup of the 24 words and your stronghold file it is okay and safe to close Firefly, the migration was successful and after a restart of Firefly you funds will appear. 
If the Transaction is shown in the explorer as “pending” it will need to be reattached. Use the “reattache” Function in the explorer until you get a “confirmed” status for the transaction.
Now proceed as above and close Firefly.
https://cdn.discordapp.com/attachments/401389663236915200/836613006765981777/unknown.png

**Comment by trinitylight** [comment]
thanks for the info guys, I just fixed the problem in another way, I moved my funds in another firefly profile that doesn't have these issues and in 5 seconds I fixed it. Fortunately I could send and receive also with that bug from that profile to another one using the menu in top to the left. The bug was just in the main page, very strange

**Comment by dcts** [comment]
I can confirm, had the same issue. After migration the Funds show in the balance in the top left, but it is not possible to send them and I see this alert saying "your funds will be available soon": 
![Bildschirmfoto vom 2021-05-24 19-08-43](https://user-images.githubusercontent.com/44790691/119383591-cda94800-bcc3-11eb-8c00-cbe54b268c76.png)

# SOLUTION
For me i could resolve this issue by creating an stronghold backup file and then simply recovering that newly created backup. Maybe thats helpful for somebody.
