### ISSUE TITLE
!!!!!!ACHTUNG BEI IOTA SIND HACKER UNTERWEGS; AUF DISCORT SAGEN DAS AUCH VIELE!!!!!!!!!!!!

### ISSUE THREAD

**Issue by andred92** [iotaledger/firefly#1101]
## Issue description

Briefly describe the issue.

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by obany** [comment]
Github is for reporting issues with the software,  please use discord for help with other issues.

**Comment by andred92** [comment]
Das ist mir doch egal.

Am 02.05.2021 19:54 schrieb "Martyn Janes" ***@***.***>:
