### ISSUE TITLE
Cannot migrate : Seeds are not currently supported

### ISSUE THREAD

**Issue by donaminos** [iotaledger/firefly#1102]
## Issue description

When I enter my Trinity seed I get the following error `Seeds are not currently supporter`.

<img width="439" alt="Screenshot 2021-05-02 at 15 46 19" src="https://user-images.githubusercontent.com/5103153/116815534-418d8000-ab5e-11eb-95a9-cbba6b151b5c.png">

## Wallet version

Which version of wallet are you using?

- wallet version : 0.4.0

## System specification

What is your operating system?

Mac Catalina 10.15.7

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Import existing wallet
2. I have a text backup
3. Enter the seed 

## Expected behaviour

Import wallet

## Actual behaviour

Error message `Seeds are not currently supported`

## Errors

`Seeds are not currently supported`

**Comment by Phyloiota** [comment]
You are using the Beta Version of Firefly.
Please delete this version and use the new Alpha Release that will work on the current Mainnet with real IOTA and your real Seed.
Download it here:
https://github.com/iotaledger/firefly/issues/1105

**Comment by rajivshah3** [comment]
Hi, please download the official version of Firefly from https://firefly.iota.org

**Comment by donaminos** [comment]
> Hi, please download the official version of Firefly from https://firefly.iota.org

It works, thanks for your help @rajivshah3
