### ISSUE TITLE
Better timing on switch to dark mode during on boarding

### ISSUE THREAD

**Issue by cyclux** [iotaledger/firefly#1104]
## Description

During on boarding turn the theme to dark colors once the figure has pulled down the lamp string to the bottom.
Currently it turns dark, then the animation starts. More intuitive is that it turns dark once the lamp string is on the bottom.

## Motivation

Sync between animation is not intuitively synchronized.
I know this is really unimportant, just if there is time it would be cool :D

## Requirements

Just adjust the timing of the switch to dark theme.

## Are you planning to do it yourself in a pull request?

No.

**Comment by cvarley100** [comment]
Haha you are a perfectionist

**Comment by cyclux** [comment]
😅
