### ISSUE TITLE
Digicert code signature is different from what is shown on  https://firefly.iota.org/

### ISSUE THREAD

**Issue by Dago1** [iotaledger/firefly#1105]
## Issue description

Check of SHA256 hash is ok.
-> but code signature is different:
Should be (acc. to website): „DigiCert DigiCert SHA2 Assured Code Signing CA IOTA Stiftung“
but is:                                 „DigiCert SHA2 Assured ID Code Signing CA“

?Is the exe file reliable?

## Wallet version

firefly-desktop-1.1.0.exe

- wallet version (version number, commit, or branch):

## System specification

WIN 10 64 bit

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

--
![grafik](https://user-images.githubusercontent.com/83552178/116823871-49154f00-ab87-11eb-8a81-6df90319b19f.png)

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by rajivshah3** [comment]
Yes, that's fine. There's a formatting issue on the website
