### ISSUE TITLE
Backup Ledger

### ISSUE THREAD

**Issue by andrevicentegoncalves** [iotaledger/firefly#1107]
Hi, I just installed Firefly and want to migrate from Trinity, I use the Ledger Nano X, how can I backup the seed to migrate? I don't know my seed but I have access to my trinity wallet. Please help! 

Thanks

**Comment by Phyloiota** [comment]
Migrating wit a Trinity Ledger account is not yet possible. 
You will need to wait a few weeks until the Ledger support is implemented in the new Firefly Wallet.
No worries, your Seed is absolute safe stored in the Ledger.
Just wait for an upcoming announcement in the next week when the process for Ledger owners can start
