### ISSUE TITLE
Firefly unable to downloadApp Version: 1.1.0  platform: win32 platformVersion: 10.0.19042 platformArchitecture: x64 cpuCount: 4 totalMem: 3999.4 MB freeMem: 393.6 MB userPath: C:\Users\user\AppData\Roaming\Firefly  Error Type: Main Unhandled Promise Rejection  Error: Uncaught Error: net::ERR_NETWORK_IO_SUSPENDED

### ISSUE THREAD

**Issue by ggraham123** [iotaledger/firefly#1112]
## Issue description

Briefly describe the issue.

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by rajivshah3** [comment]
Hi, please fill out the template. We can't figure out what's wrong without that information
