### ISSUE TITLE
The wallet download is very slow. 

### ISSUE THREAD

**Issue by markskayff** [iotaledger/firefly#1113]
## Issue description
I'm on a Linux Mint 20 with a Firefox web browser. The download speed for the IOTA Wallet is about 500kb/s. My internet speed connection is good now. About 50 Mb/s.

## Wallet version

I'm trying to download the wallet.

## System specification

Linux Mint 20.

**Comment by rajivshah3** [comment]
Hi, this should be resolved now on the Firefly website
