### ISSUE TITLE
program only opens a blank screen only when opening flrefly1.1.0 in mac10.13.6

### ISSUE THREAD

**Issue by joeiota** [iotaledger/firefly#1116]
## Issue description

Briefly describe the issue.

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by cvarley100** [comment]
Are you on version 1.1.0? If so, can you share the error displayed?

**Comment by joeiota** [comment]
All I get is a blank window opening....Sent from my Galaxy
-------- Original message --------From: Charlie Varley ***@***.***> Date: 05/05/2021  20:44  (GMT+00:00) To: iotaledger/firefly ***@***.***> Cc: joeiota ***@***.***>, Author ***@***.***> Subject: Re: [iotaledger/firefly] program only opens a blank screen only when opening flrefly1.1.0 in mac10.13.6 (#1116) 
Are you on version 1.1.0? If so, can you share the error displayed?

**Comment by joeiota** [comment]
and yes am using 1.1.0

**Comment by cvarley100** [comment]
You might want to try updating your OS version. High Sierra is quite old and Apple no longer support it with security updates.

**Comment by joeiota** [comment]
Can't.  Laptop is not able to be updated.Sent from my Galaxy
-------- Original message --------From: Charlie Varley ***@***.***> Date: 10/05/2021  14:21  (GMT+00:00) To: iotaledger/firefly ***@***.***> Cc: joeiota ***@***.***>, Author ***@***.***> Subject: Re: [iotaledger/firefly] program only opens a blank screen only when opening flrefly1.1.0 in mac10.13.6 (#1116) 
You might want to try updating your OS version. High Sierra is quite old and Apple no longer support it with security updates.
