### ISSUE TITLE
blank window

### ISSUE THREAD

**Issue by eva-ggg** [iotaledger/firefly#1118]
## Issue description

blank window after login

## Wallet version

Which version of wallet are you using?

- firefly 1.1.0.

## System specification

What is your operating system?

Windows10

## Is it a repeatable issue?

i dont know

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

That i can log in and continue the transfer from trinity to firefly

## Errors

![image](https://user-images.githubusercontent.com/83675817/117075012-6d625e80-ad34-11eb-9afa-023bd64a3fa3.png)
![Unbenannt1](https://user-images.githubusercontent.com/83675817/117075062-810dc500-ad34-11eb-99f7-d50b882b0c2e.PNG)

**Comment by WOETER139** [comment]
Hi Eva-ggg,
I had the same issue, used the seed several times and left me with blank Firefly. After this I decided to remove the 1st install and did fresh install of Firefly. Filled in the seed again and that worked for me. Hope this helps you to get it working.

**Comment by eva-ggg** [comment]
unfortunately it still does not work. i have uninstalled it and reinstalled firefly. my profile is stored but as soon as i enter my pin, the blank window appears again.

**Comment by eva-ggg** [comment]
even when I create a new profile. After typing the password for the backup file, the blank space appears and i cannot continue.

**Comment by WOETER139** [comment]
I've used my 81 seed to recover

**Comment by eva-ggg** [comment]
I did. Multiple times. I have a profile, but as soon I enter my password, the blank window appears. When I try to create a new profile, using my 81 word seed, after the window where I can store the back up file, the blank window appears... after that the new profile is not saved somehow.

**Comment by WOETER139** [comment]
Well, I thought it might help you. But it looks you did the same as I did. If not nice if it doesn't work as supposed to. Hope some solution soon comes your way. Good luck.

**Comment by eva-ggg** [comment]
Thank you so much!

**Comment by cvarley100** [comment]
Are any errors displayed?

**Comment by hristo-mavrodiev** [comment]
Can you try to run it with the argument ``` --disable-gpu```?
