### ISSUE TITLE
Please HELP, Binance is not allowing me to withdraw my IOTA and transfer to Firefly

### ISSUE THREAD

**Issue by bluekingdomfrenchies** [iotaledger/firefly#1119]
I generated a receive IOTA address in my Firefly wallet and used it to withdraw it out of Binance. 
It states the MIOTA network is BUSY
I used he BEP20(BSC) network

"The withdrawal address format is wrong. Please check the withdrawal address length and character content and try again"

What do I do?? I don't have a NanoLedger, where else can I store my IOTA?? They are giving my 14 days (I have 7 left) before they LOCK my account due to me being a US citizen, I applied and got the USBinance account, but I cannot transfer from one Binance to another Binance US account. They won't let me sell,trade,swap. HELP pleaseeeeee. I don't want to loose my 157 IOTA

**Comment by rajivshah3** [comment]
> I used he BEP20(BSC) network

This is for [Binance Smart Chain](https://www.binance.org/en/smartChain), you need a different wallet for that. Binance is not currently allowing withdrawals to the IOTA network, but they should soon. 

As a side note, I didn't have a problem withdrawing after the 14 days, so this may not be an issue

**Comment by Operateam72** [comment]
I'm in the same boat.  From what I read on Binance's announcement, the ability to withdraw since the Chrysalis migration started has yet to be established.. Am I correct on this info?
