### ISSUE TITLE
Send and Receive tabs use issues

### ISSUE THREAD

**Issue by AlexisCav** [iotaledger/firefly#1120]
## Issue description
Perform the migration, everything fine, balance correct, but the send and receive tabs are not active. Also in the lower right corner appears a warning that says: Your funds will be available shortly. I can only access sending and receiving from the menu (hamburger)

Briefly describe the issue.
Perform the migration, everything fine, balance correct, but the send and receive tabs are not active. Also in the lower right corner appears a warning that says: Your funds will be available shortly. I can only access sending and receiving from the menu (hamburger)

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by jojosoup** [comment]
I have the same problem. Balance is correct. But I can not send and receive. Also, in the lower right corner appears a warning that says: Your funds will be available shortly. Shall we wait for a new Firefly version?

**Comment by Travetown** [comment]
https://discord.com/channels/397872799483428865/748265907351978115/839123688770240522
