### ISSUE TITLE
Main Unhandled Promise Rejection

### ISSUE THREAD

**Issue by exentim** [iotaledger/firefly#1127]
After returning to Windows from overnight Standby mode, this showed up: Firefly was still open and operational after typing in PIN.

App Version: 1.1.0

platform: win32
platformVersion: 10.0.19041
platformArchitecture: x64
cpuCount: 4
totalMem: 8092.2 MB
freeMem: 2141.2 MB
userPath: C:\Users\username\AppData\Roaming\Firefly

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NAME_NOT_RESOLVED

**Comment by rajivshah3** [comment]
Hi, this sounds like a connectivity issue. Was it resolved after you used your computer for a bit?

**Comment by perandre** [comment]
I have experienced the same issue with MacOS. There are multiple issues reporting the same thing (with non-descriptive titles); the issues needs some cleanup.

## Details:

App Version: 1.3.0

platform: macOS
platformVersion: 12.0.1
platformArchitecture: x64
cpuCount: 8
totalMem: 16384.0 MB
freeMem: 1269.1 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NETWORK_CHANGED
