### ISSUE TITLE
 trying to recover my wallet from trinity to firefly

### ISSUE THREAD

**Issue by Danilo3369** [iotaledger/firefly#1130]
## Issue description   I am trying to recover my wallet from trinity to firefly without success, I recovered the account with the 24 phrase of my ledger s  but the account appears at 0, what can I do

Briefly describe the issue.

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by r-c-k** [comment]
See [https://blog.iota.org/firefly-token-migration/](https://blog.iota.org/firefly-token-migration/) to learn about the migration. Support for Ledger Nano devices is planned for later this month.
