### ISSUE TITLE
Migrate iota tokens from trinity to firefly

### ISSUE THREAD

**Issue by Topgear2** [iotaledger/firefly#1131]
I cannot open trinity wallet to send tokens to firefly.wallet uses Ledger nano x

**Comment by r-c-k** [comment]
See [https://blog.iota.org/firefly-token-migration/](https://blog.iota.org/firefly-token-migration/) to learn about the migration. Sending your tokens from Trinity to Firefly is **not** how it works. Support for Ledger Nano devices is planned for later this month.
