### ISSUE TITLE
Uncaught Error: net::ERR_NETWORK_CHANGED

### ISSUE THREAD

**Issue by yovendielmundo** [iotaledger/firefly#1134]
## Issue description

Unfortunately, an error has occurred in Firefly

`Error Type: Main Unhandled Promise Rejection`
`Error: Uncaught Error: net::ERR_NETWORK_CHANGED`

## Wallet version
App Version: 1.1.0

## System specification

platform: macOS
platformVersion: 11
platformArchitecture: x64

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

- Open the wallet application
- Close the MacBook, go to sleep mode
- Open the Macbook again
- 
## Expected behaviour

No errors happen

## Actual behaviour

Unfortunately, an error has occurred in Firefly

## Errors
```
App Version: 1.1.0

platform: macOS
platformVersion: 11
platformArchitecture: x64
cpuCount: 12
totalMem: 16384.0 MB
freeMem: 90.7 MB
userPath: /Users/luis/Library/Application Support/Firefly

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NETWORK_CHANGED
```

**Comment by densnet8888** [comment]
App Version: 1.1.0

platform: win32
platformVersion: 10.0.19042
platformArchitecture: x64
cpuCount: 16
totalMem: 16314.6 MB
freeMem: 7338.8 MB
userPath: C:\Users\Win10\AppData\Roaming\Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'id' of undefined
    at C:\Users\Win10\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:165586
    at C:\Users\Win10\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:197606
    at Array.forEach (<anonymous>)
    at destroy (C:\Users\Win10\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:197594)
    at C:\Users\Win10\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:191379

**Comment by cvarley100** [comment]
This might be to do with you VPN?

**Comment by yovendielmundo** [comment]
@cvarley100 thanks for replying. Yes, it could be. Sometimes I use the VPN. I'm gonna close the bug and report only if I get the error again.
