### ISSUE TITLE
Blank white screen on Mac

### ISSUE THREAD

**Issue by lipppi** [iotaledger/firefly#1137]
## Issue description

The program doesn't start, it's just a white screen. In the header menu only the "About Firefly Firefly" (sic) option can be chosen. "Check for updates", "Settings", "Diagnostics" and "Error log" options results in nothing happening.

## Wallet version

Version 1.1.0

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac OS High Sierra on a MacBook Pro mid-2010.

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

For the UI of the program to show up as intended 

## Actual behaviour

White screen

## Errors

Unaccessable

**Comment by cvarley100** [comment]
High Sierra is no longer supported by Apple for security updates. Are you able to update to a newer OS version?
