### ISSUE TITLE
BINANCE WALLET WITHDRAWL ISSUE

### ISSUE THREAD

**Issue by jhrosenb** [iotaledger/firefly#1139]
## Issue description

Briefly describe the issue.
Hello, I am trying to withdraw my IOTA from my binance spot wallet into my Firefly wallet. I've installed firefly on my computer, created a wallet and copied the address to Binance to send it to. when I copy and paste into binance it says: 
"The withdrawal address format is wrong. Please check the withdrawal address length and character content and try again"
every time. Can someone help/advise me on this issue?
## Wallet version**: 1.1.0**

Which version of wallet are you using?

- wallet version (version number, commit, or branch):
HARDWALLET: LEDGER NANO S (but I don't think it's connected to it)
FIREFLY VERSION 1.1.0
## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)
WINDOWS 10
## Is it a repeatable issue?

Y/N
YES
## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.copy my firefly wallet address
2.go to binance IOTA wallet and paste address
3.error message appears

## Expected behaviour

Describe what you expect to happen.
SHOULD BE ACCURATE FIREFLY WALLET ADDRESS. ADDRESS IS CORRECT
![BINANCE ERROR](https://user-images.githubusercontent.com/83886443/117553699-db927400-b007-11eb-95f6-74786f8eb633.JPG)

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by cvarley100** [comment]
Binance are currently in the process of upgrading their IOTA integration. They have disabled withdrawals until it is complete.
