### ISSUE TITLE
There was a network error restoring your wallet.  I typed my seed to commence migration and when i hit continue is error pops up.  Any recommendations?

### ISSUE THREAD

**Issue by Mtennant1313** [iotaledger/firefly#1142]
## Issue description

There was a network error restoring your wallet. I typed my seed to commence migration and when i hit continue is error pops up. Any recommendations?  I also tried downloading the SeedVault file and it and then said:  Something went wrong.

## Wallet version

- Trinity on my Ipad, which it is not discontinued

## System specification

Mac OS Big Sur

## Is it a repeatable issue?

Yes

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by cvarley100** [comment]
A couple of reasons for this can be - incorrect device time, using a VPN, network proxy settings etc.

**Comment by Mtennant1313** [comment]
I'm running a mac and my device time is checked in my preferences to set date and time automatically, I'm not running a VPN, so it seems like it might be a network proxy setting.  I'll do some digging thanks.

**Comment by Mtennant1313** [comment]
Tried loading it on another computer and it worked...thanks
