### ISSUE TITLE
Error when launching for the first time

### ISSUE THREAD

**Issue by JoergEmilio** [iotaledger/firefly#1143]
## Issue description

Thank you for any helpful ideas: I changed from Trinity to Firefly to migrate my MIOTA to Chrysalis.
Downloaded the App from Firefly website but after installation Firefly does start only with a blank page and shows the following error:

App Version: 1.1.0

platform: macOS
platformVersion: 10.10
platformArchitecture: x64
cpuCount: 4
totalMem: 4096.0 MB
freeMem: 52.4 MB
userPath: /Users/Emilio/Library/Application Support/Firefly

Error Type: Preload Error

Error: Uncaught Error: node-loader:
Error: dlopen(/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node, 1): no suitable image found.  Did find:
	/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node: code signature invalid for '/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node'

## Wallet version
1.1.0

## System specification
Mac OS 10.10.
MacBookAir

## Is it a repeatable issue?
Yes

## Steps To reproduce the issue
1. Download Firefl from Firefly website
2. Open program

## Actual behaviour
Installation sems normal. Dragged the Firefly symbol to the Applications. Started the program. It starts, but shows only a blank page and an Error description:

## Errors:

App Version: 1.1.0

platform: macOS
platformVersion: 10.10
platformArchitecture: x64
cpuCount: 4
totalMem: 4096.0 MB
freeMem: 52.4 MB
userPath: /Users/Emilio/Library/Application Support/Firefly

Error Type: Preload Error

Error: Uncaught Error: node-loader:
Error: dlopen(/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node, 1): no suitable image found.  Did find:
	/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node: code signature invalid for '/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node'

**Comment by rajivshah3** [comment]
I can't reproduce the issue. Where did you download Firefly from?

**Comment by rajivshah3** [comment]
On macOS 10.10, the OS looks for code signatures with SHA-1 hashes. I'm not sure what release it was changed in, but code signatures now have SHA-256 hashes. Can you try updating your macOS version? Versions before 10.12 are not supported

**Comment by JoergEmilio** [comment]
Dear Rajiv,

Thank you for your help. I have downloaded Firefly from the official website mentioned on Iota website.
I understand, that my OS version is not suported any more. 
So I will try to update the System. 
Not sure, wether it is poosible on my MacBook Air (Beginning 2014), 1.4 GHz Intel.
Automatic software update does not offer any updates.

Do you think its possible anyways to update?

Thanks again and best wishes.
Emilio
