### ISSUE TITLE
Migration to Firefly - error message: "please try again"

### ISSUE THREAD

**Issue by rictoledo** [iotaledger/firefly#1145]
I tried to migrate my funds from Trinity to Firefly. After a few minutes firefly pulls an error saying "There was an error migrating your funds. Please try again". I have tried multiple times and nothing happens. I also checked the Trinity if I have any pending transactions but nothing. My balance is still the same in Trinity.

**Comment by thoro87** [comment]
I am experiencing the same issue. I didn't touch IOTA for a while so I still had the IOTA Light Wallet 2.5.7.
During FiryFly Setup I used the 81-Char Seed and the balance that came up after the import looked correct.
After setting up PIN and Password however during the "Migrate your funds" process the litte Window with the message "There was an error migrating your funds. Please try again." pops up.

**Comment by MiKeF05** [comment]
@rictoledo @thoro87 Were you able to migrate your token?

**Comment by rictoledo** [comment]
Yes, I was able to transfer the funds in the end. I do not recall exactly what I did, but I remember I had to change the Windows settings turning off the “automatically detect the timezone / adjust time” (something like that). it sounds random, but it worked.
________________________________

**Comment by MiKeF05** [comment]
Glad to hear. Would it be possible to close this issue?

**Comment by thoro87** [comment]
I don't remember what I did 7 months ago, but it all went well a few days later. :)

**Comment by MiKeF05** [comment]
Okay great. Thank you both for the feedback. Issue can be closed
