### ISSUE TITLE
open firefly wallet then occured error

### ISSUE THREAD

**Issue by Mohamadev** [iotaledger/firefly#1148]
<img src="https://cdn3.bbcode0.com/uploads/2021/5/11/9ff4b0e560933ea0d9410b77ea491a8d-full.png"/>

**Comment by BongoBertie2021** [comment]
Hi, the exact same thing has happened to me, the wallet I created has gone. Have you found a solution to this and if so could you share it on here? Or could someone from Iota/Firefly help at all?

**Comment by thiagomen001** [comment]
did you make it?
@Mohamadev @BongoBertie2021

**Comment by BongoBertie2021** [comment]
Hi, yes I managed to retrieve the wallet by setting up a new profile with the 24 word recovery phrase and the Iota holding re-appeared. So all good but I have a mistrust of Firefly and Iota. No help offered whatsoever, my solution was just an educated guess. Am relieved, good luck
