### ISSUE TITLE
Seed Import Issue

### ISSUE THREAD

**Issue by storm5had0w** [iotaledger/firefly#1153]
I am trying to migrate from Trinity to Firefly. Firefly asks for my Trinity seed -- I input my Trinity seed, but Firefly rejects the seed because it has digits in it. My Trinity seed has several digits in it -- I cannot import due to this. How can I resolve? Thank you.

**Comment by Travetown** [comment]
Have you entered an IOTA address and not the seed?  The seed only consists of the letters A to Z and the number 9

**Comment by wonkytonky2** [comment]
it's not a bug. your seed can't have digits except for nr 9.   
get the correct seed.
