### ISSUE TITLE
How to retrieve coins from Trinity + Ledger ?

### ISSUE THREAD

**Issue by MacGregorsk** [iotaledger/firefly#1154]
Hi. 

I have some Iota on Trinity linked to a Ledger. It looks like I can't activate the send button to transfer and sell the cryptos on an exchange.
I tried Firefly as I was suggested to do but I have no seed, password or file I can recopy to retrieve my wallet.
(Trinity says : 'Seed export not available for Ledger account').

How can I retrieve my coins ?

Regards.

**Comment by r-c-k** [comment]
See [https://blog.iota.org/firefly-token-migration/](https://blog.iota.org/firefly-token-migration/) to learn about the migration. Support for Ledger Nano devices is planned for later this month.

**Comment by MacGregorsk** [comment]
Thank you.

**Comment by JAVIER45648** [comment]
Hi,
I have exactly the same problem explained by MacGregorsk on May 14:

I have some Iota on Trinity linked to a Ledger. It looks like I can't activate the send button to transfer and sell the cryptos on an exchange.
I tried Firefly as I was suggested to do but I have no seed, password or file I can recopy to retrieve my wallet.
(Trinity says : 'Seed export not available for Ledger account').

How can I retrieve my coins?

MacGregorsk: did you solve the issue?  Can you please tell me how you did it? 
Many thanks in advance!
Regards,
Javier

**Comment by r-c-k** [comment]
Ledger integration is still work in progress, so a little more patience is needed. Join the official IOTA discord at [discord.iota.org](discord.iota.org) for further questions. 🙂
