### ISSUE TITLE
balance is negative

### ISSUE THREAD

**Issue by ghost** [iotaledger/firefly#1162]
## Wallet version

Which version of wallet are you using?

1.1.0(Testnet with https://api.lb-0.testnet.chrysalis2.com)

## System specification

What is your operating system?

Mac

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. open wallet and send
2. balance is zero,back to main windows
3. balance is negative

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

balance of atoi1qzveqp4p9de6rwu4ej05zqvggucz8j94np8ggqpt6awr79sznl9s5jmlplt is 11Mi not negative

## Errors

![截屏2021-05-21 上午11 19 39](https://user-images.githubusercontent.com/58415594/119077284-9833fe80-ba26-11eb-85f2-1912c4b627a8.png)

**Comment by MiKeF05** [comment]
This should be solved with the latest release. If the issue still persists please reopen the issue.
