### ISSUE TITLE
Miota Address is Incorrect

### ISSUE THREAD

**Issue by Majatosh** [iotaledger/firefly#1164]
## Issue description

I am trying to deposit Miota into firefly wallet and it says that the address format is incorrect.

## Wallet version

Firefly v1.1.0

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac OS High Sierra version 10.13.6

## Is it a repeatable issue?

YES

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

I am expecting to be able to use a valid address for the wallet that is recommended as super secure on IOTA website. 

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by rajivshah3** [comment]
What is saying the address format is incorrect?

**Comment by Majatosh** [comment]
When i scan the code for the address, binance says address format is incorrect and i cannot withdraw.

**Comment by Travetown** [comment]
See

https://github.com/iotaledger/firefly/issues/1139
