### ISSUE TITLE
Hoddle IOTA since 2017

### ISSUE THREAD

**Issue by SchellBribie** [iotaledger/firefly#1165]
Need your help I wanted to migrate my account to Firefly after not having looked into IOTA for several years.
My Seed i have on record is only 78 characters long. 
What can I do?

**Comment by tahmeaollo** [comment]
Just add number 9s to the end until it's 81 characters long

**Comment by SchellBribie** [comment]
HI Petteri - Thank you Sooo much - it worked !
Cheers
Peter

On 24/05/2021 19:24:55, Petteri ***@***.***> wrote:
Just add number 9s to the end until it's 81 characters long
