### ISSUE TITLE
Token Migration Failed - coins seem to be lost.

### ISSUE THREAD

**Issue by dcts** [iotaledger/firefly#1166]
## Description

During Token Migration the app first showed that the migration failed and I should try later, after trying multiple times without success, the app froze, and I had to close it. Then after reopening the old tokenaddress was empty. After checking the tangle explorer it showed that the tokens are migrated but there is no new account in the firefly app. 

I migrated multiple wallets, most of them worked without problems, but this one with 150 IOTA on it did not work. Heres the tangle exporer entry:
https://explorer.iota.org/legacy-mainnet/address/HOCUZXLPXRFKTNJTDYFEVSNEOURHFNKZWECHLAGPHIDDOJGAXFMZTFNXKTEZRLZJOQOOVUT9J9ECAUPHBTRXIMGJPW

My full user flow was as following:
1. click on PLUS icon to create another PROFILE
2. set a naming for the profile
3. select "Wallet migration or recovery"
4. select "I have a 81 character seed"
5. input seed
6. shows balance of 150 IOTA
7. click on "Migrate"
8. ... then it failed with an alert, and prompted to try again later. I tried multiple times, did not work. After several fails the button did not respond at all anymore, and the app seemd frozen. After force restart the newly created account does not show up. When I try to repeat the whole process, after inserting the seed in step 6 the app shows a 0 balancem, indicating that the funds were migrated. But there is no profile... 

After using the firefly wallet for another 30 mins I got this error message, not sure if that is related to this problem but I believe it is:
```
App Version: 1.1.0

platform: linux
platformVersion: 5.8.0-53-generic
platformArchitecture: x64
cpuCount: 12
totalMem: 64067.3 MB
freeMem: 48557.2 MB
userPath: /home/dcts/.config/Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'migratedTransactions' of undefined
    at /tmp/.mount_fireflilOMlT/resources/app.asar/public/build/preload.js:2:165586
    at /tmp/.mount_fireflilOMlT/resources/app.asar/public/build/preload.js:2:197606
    at Array.forEach (<anonymous>)
    at destroy (/tmp/.mount_fireflilOMlT/resources/app.asar/public/build/preload.js:2:197594)
    at /tmp/.mount_fireflilOMlT/resources/app.asar/public/build/preload.js:2:191379
```

## Wallet version
- 1.1.0

## System specification
- Linux
- Ubuntu 20.04

## Is it a repeatable issue?
N

## Expected behaviour
Migration successfully works. Or if the migration fails, then I would expect it to not move the funds.

## Actual behaviour
Migration failed, but the funds seem to be migrated.

**Comment by rajivshah3** [comment]
Can you try deleting the account and then importing your new seed?
