### ISSUE TITLE
Funds don't appear in my wallet

### ISSUE THREAD

**Issue by vladigankov** [iotaledger/firefly#1167]
## Issue description

I've made a purchase transaction SEPA via Omoku on 24/05.
In y Omoku acount it shows correctly. Money are discounted from my acount.
On 25/05 funds don't appera on my wallet.
Is it normal?

## Wallet version

Which version of wallet are you using?

v 1.1.0

## System specification

What is your operating system?

Windows 10

## Is it a repeatable issue?

N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by rajivshah3** [comment]
Hi, please contact Omoku for support
