### ISSUE TITLE
Software freezes while setting up an extra secure password

### ISSUE THREAD

**Issue by EricGend** [iotaledger/firefly#1172]
## Issue description

While setting up my wallet iI decided ti choose an very extra secure password of about 256 characters, managed by a Passwordmanager, the Software instantly freezes and don't respond anymore.

## Wallet version

Firefly v. 1.1.0 - officiall download

## System specification

Win10 64bit

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Open a new wallet copy past a password with 256 characters like this: 
qt\V;;W-hÄP".^bWeWjs`}Uds"^.9eGUa;{lV|E?u3ü)l-7~cmzZ4SfggQsYzi.1^hWZVU!NsLICj0X*`%>epd\ÜmcZPS!eB~LQ P>NKIDh71?Zvb_<Cbgs%yöyoyX4Q8taü${8|'Xf+HJ9{V0"3kREfSAOßÜ@_&1ku3Gßö8;9LPlPIo{BPB<5N 5|(9cHJx3?k.c}%*q7~Z2PKÄö(BAb/t%gv%bFfJ!6zü7e8ä9apqV'574v@''ü}{W_eCN%O7e

## Expected behaviour

dont freeze ;D

## Actual behaviour

freeze 

## Errors

no error log at all

**Comment by kraftjs** [comment]
This issue is still present with user's provided string in Firefly v1.3.3 on Windows 10. I have not tried to replicate on other platforms.

**Comment by jeeanribeiro** [comment]
I've reproduced the error here and this is related to the password strength algorithm, we're using a lib called 'zxcvbn', and one of the performance issues of this lib is that when we have a large password, the function execution takes a lot longer than usual passwords, so according to the docs, is recommended that we only check a limited number of characters in the password, like the first 100 characters or less.

https://github.com/dropbox/zxcvbn#user-content-performance
