### ISSUE TITLE
Cannot assign a Stronghold password

### ISSUE THREAD

**Issue by m75687** [iotaledger/firefly#1175]
## Issue description

I am unable to assign a Stronghold password in Firefly when migrating from my old Trinity Seedvault. The button to save the password for the Stronghold file remains inactive all the time. I have tried many password combinations, shorter, no special characters, no numbers, only certain special characters, etc. but the button is always grayed out and Enter cannot be used to confirm either. 

Which version of wallet are you using?

Firefly v1.1.0
Plattform: win32
Plattformversion: 10.0.19041
Plattform-Architektur: x64
CPU-Anzahl: 8
Gesamtspeicher: 16324.2 MB
Freier Speicher: 10138.9 MB
Benutzerpfad: C:\Users\username\AppData\Roaming\Firefly

What is your operating system?

Windows 10 pro 64bit Version 2004

## Is it a repeatable issue?

Yes 

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Firefly Darkmode, german, setting long profilname with underscore, 
2. Wallet migration to Chrysalis, Selecting Trinity Seedvault, ... 
3. Check 24 Words, trying to set a Stronghold pw for my stronghold file...

## Errors

no error log

**Comment by MiKeF05** [comment]
@m75687 Does this issue still persist?

**Comment by m75687** [comment]
> @m75687 Does this issue still persist?

No, thanks for your question. After a new install the problem no longer existed
