### ISSUE TITLE
Waiting for migration, the transaction is freezed, network doesn't work

### ISSUE THREAD

**Issue by Markburo86** [iotaledger/firefly#1177]
## Issue description

Today I set up my Firefly software and wallet. Everything worked fine. Then I did the migration process charging my seedvault of my Trinity wallet in order to migrate to Firefly wallet. After 50 minutes I find the transaction in the section "Last transactions" but it's freezed I cannot click on it and moreover I don't find any found in my wallet: it seems that the migration is not completed. Then I checked my Firefly software again and in the lower-left corner, there's the status "Network not connected" - Messages per second 0, Referenced rate 0%.  What can I do now? Change the node? To which address? Hope someone can help me with this, thanks!

## Wallet version

Which version of wallet are you using?

Firefly 1.1.0

## System specification

What is your operating system?

Windows 10

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. I enter in the wallet.
2. The network doesn't change its status
3. The transaction cannot complete.

## Expected behaviour

I expect that the transaction will complete and I will see my coins in my wallet.

## Actual behaviour

The migration is stopped by a problem and I don't find my coins in the wallet
![Diagnostics](https://user-images.githubusercontent.com/85054119/120096876-16cb2300-c12e-11eb-8194-c69f78661112.JPG)
![Network disconneted](https://user-images.githubusercontent.com/85054119/120096877-1763b980-c12e-11eb-95ab-f87056537465.JPG)
![Screenshot wallet](https://user-images.githubusercontent.com/85054119/120096878-1763b980-c12e-11eb-8908-773041aa1b1b.JPG)
![Something went wrong when I go in settings](https://user-images.githubusercontent.com/85054119/120096879-17fc5000-c12e-11eb-9e32-cbe3a41b9b31.JPG)

## Errors

Sun, 30 May 2021 07:58:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Sun, 30 May 2021 07:58:42 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Sun, 30 May 2021 07:58:32 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Sun, 30 May 2021 07:58:24 GMT
ClientError: `Response error with status code 503: Service Unavailable`

**Comment by Blu3M00nG1rl** [comment]
Hello. Same Issue. Same message : code 503 - Service unavailable.
![error_log](https://user-images.githubusercontent.com/46823234/120097350-467b2a80-c130-11eb-9015-858f3b8f7ac5.PNG)

**Comment by Apahatschi** [comment]
Hey guys, I'm also Waiting for confirmation. I just have a normal transfer from Bitbanda to my firefly. 
![grafik](https://user-images.githubusercontent.com/85084850/120124769-3574fc80-c1b6-11eb-840b-b685988086df.png)

**Comment by Markburo86** [comment]
The migration has been completed and I have my coins in the wallet. All is ok now.
