### ISSUE TITLE
Firefly had problems waking up from Windows standby (ERR_NETWORK_IO_SUSPENDED)

### ISSUE THREAD

**Issue by r-sweet-codes** [iotaledger/firefly#1181]
## Issue description
Left all my programs (incl. Firefly) open and Windows went into standby. After starting up again, i see two Firefly windows, one of them the Error (see Screenshot below). After closing the error window, the main Firefly window remains open and can be used without problems.

## Wallet version

Which version of wallet are you using?
1.1.0

## System specification
Win32, x64

## Is it a repeatable issue?
Yes

## Steps To reproduce the issue
Go in Standby and wake up again.

## Expected behaviour
No error message after starting up from Standby.

## Actual behaviour
Error message after starting up from Standby.

## Errors

![Screenshot (40)](https://user-images.githubusercontent.com/56869177/120271972-9252de80-c2ac-11eb-9904-01453db252c3.png)

**Comment by connectedSoul** [comment]
#1127 sounds like the same behaviour, just with another error.

**Comment by gjeee** [comment]
i can confirm this behaviour as well:

> App Version: 1.1.0
> 
> platform: win32
> platformVersion: 10.0.19043
> platformArchitecture: x64
> cpuCount: 8
> totalMem: 8066.7 MB
> freeMem: 1981.0 MB
> userPath: C:\Users\gertj\AppData\Roaming\Firefly
> 
> Error Type: Main Unhandled Promise Rejection
> 
> Error: Uncaught Error: net::ERR_NETWORK_IO_SUSPENDED

**Comment by Supersonic56** [comment]
The same behavior has happened to me today. Is there any fix or action that should be taken?
App Version: 1.2.0

platform: win32
platformVersion: 10.0.19043
platformArchitecture: x64
cpuCount: 8
totalMem: 7985.7 MB
freeMem: 962.2 MB
userPath: C:\Users\coach\AppData\Roaming\Firefly

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_CONNECTION_RESET
