### ISSUE TITLE
I lose my wallet 

### ISSUE THREAD

**Issue by Kikocano** [iotaledger/firefly#1185]
Hello.

I had my trinity wallet, and i still having it. But in april i have send my seed vault to firefly, since here everything  its ok. A few days ago i format my PC losing al de files related with seed. Can i sign in on firefly without need to import a seed? I dont know the way to recover my wallet.
I have tried to import a seed vault form trinity again, but it appears like i have no iotas

Can you help me

**Comment by r-c-k** [comment]
Have you backed up your stronghold or 24 words as advised in the setup process? If so, then you can use those to get back access to your funds in firefly but if you have not backed up your 24 words nor the stronghold file after migration then your funds might be lost.

Depending on how you formatted your computer you might have a chance by extracting files from your hard drive via a data recovery tool.

**Comment by Kikocano** [comment]
Hi again.

 

I had a seedvault and a seed but qhen i impot it it appears 0 value. How it is posible?

 

Can you help me?

 

De: Richard K. ***@***.***> 
Enviado el: jueves, 3 de junio de 2021 1:10
Para: iotaledger/firefly ***@***.***>
CC: Kikocano ***@***.***>; Author ***@***.***>
Asunto: Re: [iotaledger/firefly] I lose my wallet (#1185)

 

Have you backed up your stronghold or 24 words as advised in the setup process? If so, then you can use those to get back access to your funds in firefly but if you have not backed up your 24 words nor the stronghold file after migration then your funds might be lost.

Depending on how you formatted your computer you might have a chance by extracting files from your hard drive via a data recovery tool.

**Comment by r-c-k** [comment]
If you migrated your funds via firefly wallet then your tokens are not on the old network anymore and therefore not accessible with your old seed or seed vault file.

Please reach out to the #help channel on [Discord](https://discord.iota.org) for further assistance. **Keep in mind to never share your seed/passphrase/seedvault with anyone.**

**Comment by Kikocano** [comment]
Then? Isn’t there no way to recover it anymore? Really?

 

And how is the process to do this

 

De: Richard K. ***@***.***> 
Enviado el: jueves, 3 de junio de 2021 11:15
Para: iotaledger/firefly ***@***.***>
CC: Kikocano ***@***.***>; Author ***@***.***>
Asunto: Re: [iotaledger/firefly] I lose my wallet (#1185)

 

If you migrated your funds via firefly wallet then your tokens are not on the old network anymore and therefore not accessible with your old seed or seed vault file.

Please reach out to the #help channel on Discord <https://discord.iota.org>  for further assistance. Keep in mind to never share your seed/passphrase/seedvault with anyone.

**Comment by r-c-k** [comment]
If you did not back up your 24-word phrase nor your stronghold file (as was clearly advised in the firefly setup process) then your funds are lost. Again, you might be able to recover your stronghold backup etc. from your hard drive with a data recovery software but that depends on a bunch of variables.

Please reach out to us on Discord ([click here](https://discord.iota.org)) and we'll see if we can help you with that.

**Comment by Kikocano** [comment]
where should be stored? I wich path i mean…  i would like to recover the stronghold file, but i need to kwnow where is it

 

De: Richard K. ***@***.***> 
Enviado el: jueves, 3 de junio de 2021 13:49
Para: iotaledger/firefly ***@***.***>
CC: Kikocano ***@***.***>; Author ***@***.***>
Asunto: Re: [iotaledger/firefly] I lose my wallet (#1185)

 

If you did not back up your 24-word phrase nor your stronghold file (as was clearly advised in the firefly setup process) then your funds are lost. Again, you might be able to recover your stronghold backup etc. from your hard drive with a data recovery software but that depends on a bunch of variables.

Please reach out to us on Discord (click here <https://discord.iota.org> ) and we'll see if we can help you with that.

**Comment by r-c-k** [comment]
Your problem is not the result of a bug with the firefly wallet software which makes GitHub the wrong place to ask for help (despite it being too unintuitive to further assist you in getting back your funds). Once again, please visit the [official IOTA Discord](https://discord.iota.org) and head to the #help channel.
