### ISSUE TITLE
Firefly Error

### ISSUE THREAD

**Issue by michiel505** [iotaledger/firefly#1186]
## Issue description

Started Firefly and got an error message

## Wallet version

1.1.0

## System specification

Win 10

## Is it a repeatable issue?

N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Start Firefly
2.
3.

## Expected behaviour

Start Firefly normally

## Actual behaviour

Got error message, Firefly also pops up to start at the same time

## Errors

App Version: 1.1.0

platform: win32
platformVersion: 10.0.19042
platformArchitecture: x64
cpuCount: 12
totalMem: 16135.3 MB
freeMem: 9146.4 MB
userPath: C:\Users\michi\AppData\Roaming\Firefly

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NAME_NOT_RESOLVED

**Comment by rajivshah3** [comment]
Hi, is this issue still ocurring?

**Comment by michiel505** [comment]
Hi, this has been resolved after getting a new version.
