### ISSUE TITLE
Re-import via recovery phrase: StrongholdError: `the mnemonic was already stored`

### ISSUE THREAD

**Issue by dnalneh** [iotaledger/firefly#1187]
### Briefly describe the issue.

I successfully migrated, send some transactions and then I deleted my profile from firefly. When I added my new seed again via recovery phrase (without closing the app), an error occurs at the last step when setting up the pin. The user cannot go further. Please take a look at the pictures. (btw: Adding via backup-file works fine)

### Which version of wallet are you using?

firefly version 1.1.0

### System specification

Win 10

![grafik](https://user-images.githubusercontent.com/2178069/120632992-e525c500-c469-11eb-9522-de0cf3166efa.png)

![grafik](https://user-images.githubusercontent.com/2178069/120633050-fb338580-c469-11eb-9869-f76b46b83a94.png)

### Workaround
Simply close and open the app again, then everything is working fine

**Comment by maxwellmattryan** [comment]
Hey @dnalneh, whenever this error occurred were you using the same profile name as the one you deleted beforehand? I am trying to replicate the issue but am not able to. From what I've tried however, using the same name results in an `AccountAliasAlreadyExists` error initially occurring then the `mnemonic was already stored` one afterwards - does this happen for you as well?

**Comment by nicole-obrien** [comment]
Fixed in https://github.com/iotaledger/firefly/pull/1209
