### ISSUE TITLE
QR code in dark theme can not be scanned 

### ISSUE THREAD

**Issue by psteffensen** [iotaledger/firefly#1188]
## Issue description

QR code in dark theme can not be scanned . I guess it is because of the dark background with white dots. The scanner may expect white background with black dots.

## Wallet version

v1.1.0

## System specification

Ubuntu 20.04

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. turn on dark theme
2. press receive
3. Try to scan the qr code. I scanned from Binance app (android)

## Expected behaviour

Scan and get address string

## Actual behaviour

Never scans, but scans with light theme in Firefly

## Errors

No errors, just doesn't scan

**Comment by r-c-k** [comment]
I'd assume that the issue lies with the binance app which doesn't know how to interpret the iota:// scheme. Scanning works fine for me with a normal qr code scanner (iOS).

**Comment by kraftjs** [comment]
This issue is stale, but I am now able to copy the receive address with Binance's mobile app. Closing the issue.
