### ISSUE TITLE
Error prompt in my wallet

### ISSUE THREAD

**Issue by ArmandoRosales** [iotaledger/firefly#1189]
App Version: 1.1.0

platform: win32
platformVersion: 6.3.9600
platformArchitecture: x64
cpuCount: 4
totalMem: 3911.3 MB
freeMem: 1156.9 MB
userPath: C:\Users\joser_000\AppData\Roaming\Firefly

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NAME_NOT_RESOLVED

**Comment by maxwellmattryan** [comment]
Hey @ArmandoRosales, would you be able to provide some steps to help us reproduce the issue on our side?

**Comment by MiKeF05** [comment]
Duplicate to #2123
