### ISSUE TITLE
information

### ISSUE THREAD

**Issue by negromusic** [iotaledger/firefly#1191]
Hello I would like to know if it is normal that a withdrawal from Bitfinex to Firefly (small amount "5 Miota) takes more than 20 minutes (at the moment) to be made

**Comment by negromusic** [comment]
Hello I would like to know if it is normal that a withdrawal from Bitfinex to Firefly (small amount "5 Miota) takes more than 20 minutes (at the moment) to be made

**Comment by wonkytonky2** [comment]
ask bitfinex for the transation and who us here

**Comment by rajivshah3** [comment]
Hi, please contact Bitfinex for support
