### ISSUE TITLE
Rename Profile Name

### ISSUE THREAD

**Issue by Kajover** [iotaledger/firefly#1194]
## Description

It would be great if one can rename an already created profile (not wallet). 

## Motivation

Otherwise one needs to create a new profile and needs to delete the old one in order to rename a profile.

**Comment by maxwellmattryan** [comment]
Hey @Kajover, thank you for the suggestion. I have already converted a similar issue into a discussion, so I will close this one and add your description [here](https://github.com/iotaledger/firefly/discussions/1500) 👍

**Comment by Kajover** [comment]
@maxwellmattryan alright, the link just doesn’t work

**Comment by maxwellmattryan** [comment]
> @maxwellmattryan alright, the link just doesn’t work

Hey @Kajover, my bad! I will update the link ~
