### ISSUE TITLE
binance to firefly

### ISSUE THREAD

**Issue by 0808123** [iotaledger/firefly#1195]
## Issue description

Briefly describe the issue....when I copy my firefly address to withdraw Iota on BINANCE ..IT SAYS THE WITHDRAWL FORMAT IS WRONG 

## Wallet version

Which version of wallet are you using? v1.1.0

- wallet version (version number, commit, or branch):

## System specification

What is your operating system? Mac

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by rajivshah3** [comment]
Binance is not supporting withdrawals yet

**Comment by 0808123** [comment]
Ok thank you for your reply

Sent from my iPhone

On Jun 8, 2021, at 7:07 PM, Rajiv Shah ***@***.***> wrote:

﻿

Closed #1195<https://github.com/iotaledger/firefly/issues/1195>.
