### ISSUE TITLE
when I veryfy my pin  it get stacked and do not proceed the screen is freezed and stays like that also I could see the seed words in the document do not apear they are blank space Version is 1.10 linux bes.is a repeatable issue

### ISSUE THREAD

**Issue by ninjaturt** [iotaledger/firefly#1198]
## Issue description

Briefly describe the issue.

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by Col3Trickl3** [comment]
i think i'm having the same issue you are.  do you mean, after entering your pin, nothing happens?  that's what my problem is.  let me know when this shit is fixed

**Comment by Col3Trickl3** [comment]
there's also no errors, the screen just remains the same.  never times out.  just stuck after pin entered correctly

**Comment by ninjaturt** [comment]
Listen I do not know nothing about computing I  open Linux in my crombox
but I make it autoexe my file in file permissions I strongly believe that
probably can be something related when we download the templates in blank
space there would be some issue because is the previous step that freezes
or  better say do not allow us to proceed, supposedly according a tutorial
the next step is the assignment for the seed work, sop probably got stacked
because the file template list si no prepared in some way, I am wander what
could happen with Ubuntu I will try to download Ubuntu, what you think?
Atte Carlos

**Comment by matteo-casiraghi** [comment]
Hi, same problem, .. freeze after correct  pin...
I have installed firefly , do migrations    and logged in correctly until  june 2.
windows 8.1 64bit ...
now how can I do?   ... please help me, I am very worried.
Thank you , 
Matteo

**Comment by matteo-casiraghi** [comment]
Awesome..
solved in this way:

Start with going to Control Panel and Programs, and uninstall Firefly from there.
Then open a folder and browse to %APPDATA% , inside that appdata folder you should have a Firefly folder. Delete it.

Then go into Control Panel -> User accounts -> Credentials Manager -> Manage Windows Credentials. Then delete all the "Firefly/" entries in there.

After that, restart your computer. Download latest Firefly version. And try setting up your seeds again.

in particular ...
In Windows
Open like My documents or similar...
In the address bar Where it says My documents, click on it, write %appdata% and press enter, then delete firefly folder...

wow ... :) thank you @t00k

**Comment by ninjaturt** [comment]
Yes but in my case I had cromo como and Linux once after this command I get
it but I delete Linux to opened when I needed but I could not did it again
even recovery it wit my seed words is like probably a comand or sudo comand
is mises probably
