### ISSUE TITLE
iota transaction process in firefly

### ISSUE THREAD

**Issue by stariota** [iotaledger/firefly#1201]
## Issue description

I migrated my trinity wallet in to firefly. I try to send my iota-tokens from the binance-platform to my new firefly wallet. But the binance platform dosn't accept the created receiving-adress from my firefly wallet. All adresses which are created ba firefly starting with the chapters "iota1-following by a row of numbers (eg: "iota1qprrhxxxxx". These kind of adresses won't accept the binance plattform. By the way- a prooft the download version of firfly with the 'hash-process descriped by the iota foundation and the fiirefly wallet is the originaly one from the iota foundation. Actually i can not send iota-tokens to my firefly wallet from the binance plattform.

## Wallet version

Firefly v1.1.0
Sprache: de
Währung: USD
Node-Einstellungen: Automatische Node-Verwaltung
Plattform: win32
Plattformversion: 10.0.19041
Plattform-Architektur: x64
CPU-Anzahl: 8

- wallet version (version number, commit, or branch): Firefly v1.1.0

## System specification:
Firefly v1.1.0
Plattform: win32
Plattformversion: 10.0.19041
Plattform-Architektur: x64
CPU-Anzahl: 8
Gesamtspeicher: 8077.6 MB
Freier Speicher: 3627.6 MB
Benutzerpfad: C:\Users\Mario Teschke\AppData\Roaming\Firefly

What is your operating system?

Win10

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.create a "receiving adress" in a firefly wallet
2. contact and ask binance about there iota-withdrawal process fpr iotas
3.

## Expected behaviour

the withdrawal process to firefly wallets from extern platforms should work.

## Actual behaviour

see description under question number 1.)
## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by hristo-mavrodiev** [comment]
Binance is still not ready with the migration to the Chrysalis network. You can subscribe for notifications sms/email on their withdraw page and check when is ready or use another exchange.

**Comment by MiKeF05** [comment]
Issue can be closed as it points to the missing support of Binance.
