### ISSUE TITLE
Adding message for unsupported hardware or improve the build to work with older CPUs

### ISSUE THREAD

**Issue by hristo-mavrodiev** [iotaledger/firefly#1205]
## Issue description
When users with CPU that doesn't support ssse3 sse4_1 sse4_2 avx instructions run the wallet they get black screen

## Wallet version
1.1.0

## System specification
 CPU that doesn't support ssse3 sse4_1 sse4_2 avx instructions
Linux

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.find CPU that doesn't support this instructions
2. run the wallet
3.

## Expected behaviour

get message for unsupported hardware or improve the build to work with older CPUs

## Actual behaviour

black screen

## Errors
https://github.com/iotaledger/firefly/issues/1088
https://github.com/iotaledger/firefly/issues/1193

**Comment by Zietez** [comment]
On the same computer, as it did not work on linux, I had to virtualize Windows 10 (VirtualBox) to be able to carry out the migration. I think the problem is not hardware but software.

**Comment by Zietez** [comment]
On the same computer, as it did not work on linux, I had to virtualize Windows 10 (VirtualBox) to be able to carry out the migration. I think the problem is not hardware but software.

**Comment by nicole-obrien** [comment]
@rajivshah3 can this be closed?
