### ISSUE TITLE
Error on profile and wallet name re-use

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#1208]
## Issue description

Users are unable to delete a profile and create a new one with the same profile name so long as they haven't closed Firefly from the time of deletion to the time of creation. Specifically, Firefly throws an error of type `AccountAliasAlreadyExists` with a message `can't create account: account alias already exists`.

It's worth noting that changing the wallet name before deleting the profile will allow a user to create a profile of the same name, however the renamed wallet shows up in addition to the initial "Wallet 1" despite it being empty. This PR's changes make it so that upon deleting a profile, its wallet accounts are also deleted making it so re-creating the same profile would only show a newly initialized "Wallet 1".

## Wallet version

- 1.1.0
- develop

## System specification

- Ubuntu (20.04)
- MacOS (Catalina 10.15.7)
- Windows 10

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

1. Create a new profile of some specific name (e.g. `TheProfile`)
2. Delete `TheProfile`
3. Without closing the application, create another profile with the same name, `TheProfile`

## Expected behaviour

Firefly should create the profile despite having the same name since it should've been deleted beforehand.

## Actual behaviour

Firefly doesn't delete all instance of the profile thus resulting in the inability to create a profile of the same name. It deletes even the profile folder within `~/.config/Firefly/__storage__` (Ubuntu), but there is some other data not being accounted for. It's worth noting that closing the app is a workaround. 

## Errors

The following error is thrown once from the `asyncCreateAccount` method in [wallet.ts](https://github.com/iotaledger/firefly/blob/ad770a532971350800817b4b22d58a3c0ed93289/packages/shared/lib/wallet.ts#L413):
```
{
    type: "AccountAliasAlreadyExists",
    message: "can't create account: account alias already exists",
    time: 1623955679138 (or some other number)
}
```

Every error after is this error below, thrown from the `asyncStoreMnemonic` method also in [wallet.ts](https://github.com/iotaledger/firefly/blob/ad770a532971350800817b4b22d58a3c0ed93289/packages/shared/lib/wallet.ts#L348):
```
{
    type: "StrongholdError",
    message: "the mnemonic was already stored`",
    time: 1623959183578 (or some other number)
}
```

**Comment by nicole-obrien** [comment]
Fixed in: https://github.com/iotaledger/firefly/pull/1209
