### ISSUE TITLE
Changing receive adresses - get a logical approach implemented.

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#1219]
## Issue description
New receive addresses should be created for every fresh receiving transaction in a wallet following privacy standards. Atm this only happens if the user closes the app and logs in again. While the app is open a user gets the same receive address again and again provided by the wallet for evey fresh transaction.

Briefly describe the issue.
A user that attempts to receive a lot of transactions from different sources to his own Firefly wallet (maybe from several exchanges to get his funds into Firefly) would always have to use the same address for all those withdrawal attempts if the Firefly App stays open during this process and he just clicks on "copy address" every time and places the copied address into the exchange withdrawal field. 
On the other hand, if the user would do this same thing, but in between those withdrawals from different exchanges he would close the Firefly app, logs in again and hits "copy address" again, the wallet always generates a fresh receive address. That seems not to follow a consistent logic. 
I think: 
Every time a user has received funds in a wallet and clicks on "copy address" again, he should receive a fresh created empty address. Maybe users don't even recognize that the address has not changed... 
And why should there be a different approach between those two cases (login/ receive/ logout/ login/ receive.... or login/receive/receive/receive....)Either the privacy standards are followed always or not...
## Wallet version

Which version of the wallet are you using?
1.1.0

I would suggest implementing my feature request #725 here - show a field in the wallet with one static receive address that the user can choose to copy as often as he wishes if he does not care about the privacy so much... but always generate also a fresh receive addresses as soon as funds have arrived on an address - independent from the user's login behavior... this would be the more logical approach and users wont be so confused that they sometimes get a fresh address, sometimes not and there is no real plan behind it obviously visible

**Comment by shufps** [comment]
@Thoralf-M is this bug the same what we observed during ledger testings? (not changing receive address)

**Comment by Thoralf-M** [comment]
@shufps no, this version doesn't have this change included, otherwise it would stay the same even after a restart
But I also noticed that the address stays the same while the app is open and gets used and for the ledger we want to display the new address before it gets shown on the ledger, so it should get fixed then

**Comment by MiKeF05** [comment]
I´m going to close this issue as with the upcoming stardust update the approach with the receive address will change.
