### ISSUE TITLE
[ledger] sending from account to account gives "wrong ledger" error message

### ISSUE THREAD

**Issue by shufps** [iotaledger/firefly#1239]
After adding a Ledger Nano S (I deleted all config files), the initial scan showed three used accounts:

![image](https://user-images.githubusercontent.com/3079832/124489580-7235a400-ddb1-11eb-9392-28882c4bd804.png)

When trying to send 2Mi from `Wallet 3`* to `Wallet 1`*, this error message appears:

![image](https://user-images.githubusercontent.com/3079832/124489782-a741f680-ddb1-11eb-80e7-358a2ba33632.png)
 

*: when logging out and logging in again, the text changes from `wallet 2` to `account 2` and `wallet 3` to `account 3` what seems to be the correct term.

**Comment by Thoralf-M** [comment]
Should be fixed with https://github.com/iotaledger/wallet.rs/pull/676/commits/89726134dcd838f7c8839f1ba6c2b79ef8ea0304

**Comment by shufps** [comment]
I can confirm, the issue has been fixed :partying_face:
