### ISSUE TITLE
IOTA implementation in "Mnemonic-Code-Converter"

### ISSUE THREAD

**Issue by dev0pa** [iotaledger/firefly#1252]
https://github.com/iancoleman/bip39/issues/495#issuecomment-833953063

Can someone from the developers or from the IOTA community submit a pull request to also support IOTA-Wallet-Addresses, at https://iancoleman.io/bip39/

**Comment by maxwellmattryan** [comment]
Hey @dev0pa, I've moved this issue into the discussions [here](https://github.com/iotaledger/firefly/discussions/1498).
