### ISSUE TITLE
Allow messages/data attachments on transactions

### ISSUE THREAD

**Issue by F-Node-Karlsruhe** [iotaledger/firefly#1256]
## Description

When sending a transaction there is no way to attach a message or data to it,
neither in the UI nor when using a deep link.

## Motivation

Attaching data to transactions is very useful for linking identifiers or hashes to the transaction which allows a ton of use cases.

## Requirements

1. Pass on the message string of a deep link to the send function
2. Allow useres to attach messages to transaction or at least see the message which will be attached by the deep link

## Are you planning to do it yourself in a pull request?

No, i'm not familiar enough with the firefly implementation.

**Comment by Thoralf-M** [comment]
Related to https://github.com/iotaledger/firefly/issues/471

**Comment by maxwellmattryan** [comment]
Closing this as it is a duplicate (and has been turned into a discussion [here](https://github.com/iotaledger/firefly/discussions/1489)).
