### ISSUE TITLE
Need to close/reopen ledger app during migration

### ISSUE THREAD

**Issue by admljhnsn** [iotaledger/firefly#1264]
## Issue description

During the migration on ledger, when switching between legacy and new ledger apps, Firefly doesn't continue until you close and reopen the app on the ledger.

## Wallet version

1.1.0 ledger test version w/ migration
build #135

## System specification

MacOS BigSur 11.4
MacBook Pro (Retina, 13-inch, Mid 2014)

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Do a standard migration process
2. Choose the index, etc.
3. Begin Migration (the IOTA legacy app is still open from previous steps)
4. A popup says "Open the legacy app to continue" (the app is still open from the previous steps)
5. Have to close the ledger app and reopen to continue the migration

## Expected behaviour

Firefly should check to see if the app is open already

## Actual behaviour

The popup says to open the legacy app, even though it is already open on the ledger

## Errors

![image](https://user-images.githubusercontent.com/33967917/126017529-0760fd5b-2d74-41e8-a1c1-5a402724c5db.png)

**Comment by cvarley100** [comment]
Fixed in #1272
