### ISSUE TITLE
external sender addresses shown as `Null` in tx - detail view

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#1265]
## Issue description

Inside the wallet detail/transaction detail view a received transaction does show the "sender" of the transaction as `Null`

## Wallet version

1.1.0

## System specification

Firefly v1.1.0
Platform: win32
Platform Version: 10.0.19043
Platform Architecture: x64
CPU Count: 4
Total Memory: 6082.5 MB
Free Memory: 1410.5 MB

## Is it a repeatable issue?

yes

## Steps To reproduce the issue

open a wallet detail view and check the detail of a received transaction from an external source

## Expected behavior

 It should show either:

-  exact address of the sender
-  or write "external"

## Actual behavior

The external source will be shown as "null" - that indicates a missing variable i would interpret it.

![image](https://user-images.githubusercontent.com/77154511/126107652-e4b9afa0-80f2-4aa4-ac6a-5172603a5362.png)

**Comment by maxwellmattryan** [comment]
Hey @Phyloiota, looking into this again. There is supposed to be a section in the transaction detail view for "Send Address" right above the "Receive Address", but I'm unable to reproduce this bug myself. Do you remember maybe how you reproduced this bug?

A simple fix is just using the word "Unkown" if for some reason the sender data isn't valid or something.

**Comment by Thoralf-M** [comment]
Should be like this if the message got pruned and we can't get the sender address anymore
