### ISSUE TITLE
[Ledger migration] Firefly is stuck on "Migrating funds" even though the migration tx is confirmed.

### ISSUE THREAD

**Issue by t00k** [iotaledger/firefly#1307]
## Issue description

During the migration of funds Firefly just keeps on "Migrating funds..." and spinning on forever, even though its confirmed on the explorer on the TRANSFER-address.

## Wallet version

Build #142, latest for testers.

## System specification

Win 10, latest FW on Ledger and apps.

## Is it a repeatable issue?

Yes but no. Happened 2 times now, but not sure how to reproduce.

## Expected behaviour

Firefly should notice when the migration tx has been confirmed, and continue.

## Actual behaviour

Keeps on spinning forever on the "Migrating funds..." page.

**Comment by t00k** [comment]
[-1627408583091.log](https://github.com/iotaledger/firefly/files/6887825/-1627408583091.log)
[logfromindex11.log](https://github.com/iotaledger/firefly/files/6887826/logfromindex11.log)

Two logs from Dev Tools and the Console.
"16274" is from first try, some successful some failed, then continous spinning.
"logfromindex11" is from the second try with the same index number.

**Comment by shufps** [comment]
Happend also to me ... perhaps it would be a good idea to show a hint like

`If the migration never stops you can exit firefly and continue with opening the created profile and to choose advanced settings -> migrate ledger funds`

after some minutes :thinking: 

related to: https://github.com/iotaledger/firefly/issues/1332

**Comment by laumair** [comment]
Thanks for the report @t00k. 

https://github.com/iotaledger/firefly/pull/1342 & https://github.com/iotaledger/firefly/pull/1340 should fix this issue.
