### ISSUE TITLE
all Miota disappeared from my wallet

### ISSUE THREAD

**Issue by aramhakobyan66** [iotaledger/firefly#1364]
## Issue description

My wallet was stolen

Briefly describe the issue.

I have checked my wallet (trinity) and saw that  all the MIOTA that I owned was transfered to an unknown wallet  on 14 of June
![IMG_20210804_122902](https://user-images.githubusercontent.com/88408058/128169026-9ab9d816-5f99-4a80-a9a2-f4989f95b234.jpg)

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

Trinity wallet. Version v1.6.2

## System specification

What is your operating system?

windows 10

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Detect the infringement
2. Return all the MIOTA or compensate it.  
3.

## Expected behaviour

Only me can access to my wallet and manage my coins

## Actual behaviour

Someone else could transfer all my coins to an unknow wallet

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by MiKeF05** [comment]
Did you do the migration of your tokens? Because it seems all your tokens have been migrated to the new network.

**Comment by aramhakobyan66** [comment]
ok, you are right. All the tokens were migrated to the new network, that´s why I couldn´t see it. Now I can see all the balance in firefly
