### ISSUE TITLE
[Ledger Migration] - Stuck at finding balance with legacy app

### ISSUE THREAD

**Issue by chrisella** [iotaledger/firefly#1375]
## Issue description

Stuck at finding balance when using new Firefly 1.2.0 to migrate funds on a Ledger Nano S

## Wallet version

0.7.3 - New IOTA App
0.5.8 - Legacy Ledger App

2.0.0 - Ledger Firmware version

1.2.0 - Firefly desktop

## System specification

Windows 10

I just tried this on my Windows 10 Laptop instead and it worked there and I've now migrated successfully, so this seems isolated to my desktop machine, but may be an issue for others.

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

Follow the new Trinity -> Firefly migration guide for Ledger devices.
When you get to checking balance, after swapping to the legacy app it just sits like this (I've currently waited 20 minutes).
Also the app on the ledger has done nothing, it doesn't say generating address. I've tried restarting the ledger and re-installing the legacy app.

![image](https://user-images.githubusercontent.com/1069324/128469292-59c68f3e-57d6-4b60-8961-4aca11cb1e91.png)

## Expected behaviour

Successfully find my balance

## Actual behaviour

It hangs and never finds my balance. The Ledger app doesn't seem to do anything (I.e. no address generation).

## Errors

No errors in the log unfortunately.

![image](https://user-images.githubusercontent.com/1069324/128469905-595dcd78-835d-453a-8711-e2594441669e.png)

This is the state my ledger is in at this point, in the legacy app but it doesn't seem to actually "do" anything.

**Comment by MiKeF05** [comment]
You can try to reinstall both apps (Legacy and new IOTA app). You can also try to run Firefly as admin if your OS is windows. To have further support you can go to the IOTA Discord server and visit the help channel.

**Comment by MiKeF05** [comment]
@chrisella Have you successfully migrated your tokens?

**Comment by chrisella** [comment]
Yes I managed to by using my other computer in the end, I had no luck
whatsoever on my main desktop machine.

**Comment by MiKeF05** [comment]
Okay so I guess this issue can be closed
