### ISSUE TITLE
Connection issue Ledger Nano X

### ISSUE THREAD

**Issue by MiKeF05** [iotaledger/firefly#1379]
## Issue description

When trying to connect the Ledger Nano X with Firefly the connection is rarely possible. When the ledger finally connects, the button for generating an address doesn't work. This was on my PC with Windows 10.

I have tried to

- reinstall Firefly with deleting the appdata folder,
- reinstall the iota app on the ledger,
- disable windows defender.

Also, every other ledger-related app can instantly connect to my ledger. Only firefly fails to do this. I have tried to restart the PC several times and only opening the firefly app.

I have also tried to connect the Ledger Nano X on my old PC with Windows 7. And there it is no problem. Firefly connects without problems.

## Wallet version

Firefly v1.2
IOTA App v0.7.3
Ledger Nano X firmware v1.3.0

## System specification

What is your operating system?

Windows 10

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Open Firefly
2. Login Profile
3. Connect Ledger Nano X
4. Open IOTA app on ledger

**Comment by maxwellmattryan** [comment]
Hey @MiKeF05, some other Windows users have also been experiencing bugginess, mainly in the communication with the Ledger device and Firefly. We suspect that it might have something to do with the wallet.rs library, but are still investigating - thank you for your understanding and patience.
