### ISSUE TITLE
Duration of migration to Firefly? It has been 2hours plus and I still have the 'migrating funds' icon spinning.  How long should it take?  Has migration frozen?

### ISSUE THREAD

**Issue by DJ-Maggan** [iotaledger/firefly#1382]
## Issue description

Briefly describe the issue.

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by MiKeF05** [comment]
@DJ-Maggan Did you try to close and reopen the IOTA legacy App on the ledger? Or have you successfully migrated your tokens?

**Comment by borptpa** [comment]
I have the same issue, it's already 24 hours and still same rotating circle and message : migrating funds: I downloaded latest firefly wallet and went through installation, 24 words, back up files, etc, but something is not working.
What should I do?

**Comment by MiKeF05** [comment]
You can try to close and reopen Firefly. When you open Firefly you should be able to login to your profile. And your tokens should already be available in this profile.

**Comment by borptpa** [comment]
thanks alot


     On Sunday, March 13, 2022, 11:55:04 AM EDT, MiKeF05 ***@***.***> wrote:  
 
 


You can try to close and reopen Firefly. When you open Firefly you should be able to login to your profile. And your tokens should already be available in this profile.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
