### ISSUE TITLE
Migration of balance from Trinity to Firefly will not be performed (Leader Nano S) 

### ISSUE THREAD

**Issue by Javahake** [iotaledger/firefly#1383]
## Issue description

After creating a new adress in the Miota App (Ledger),  I opened the Iota Legacy App (Ledger) for searching the balance on the Trinity Wallet. Firefly find also my balance (so far so good) After that I started the migration....but the migration will not be performed.

## Wallet version
1.2.0

Which version of wallet are you using?
1.2.0

- wallet version (version number, commit, or branch):

1.2.0

What is your operating system?

Win 10

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by Mersi42** [comment]
my problem is also similar to this , but at the end there is an error that something went wrong
error log : Sun, 08 Aug 2021 14:30:53 GMT
LegacyClientError: https://nodes.iota.org/: status code 400

**Comment by wonkytonky2** [comment]
https://en.ryte.com/wiki/Status_Code_400
try clear dns cache @Mersi42

**Comment by Mke91** [comment]
Error code 400 ist mostly time related.
try this.
https://www.groovypost.com/howto/synchronize-clock-windows-10-with-internet-atomic-time/

**Comment by Mersi42** [comment]
thanks , I restore my wallet @Mke91

**Comment by Spartachris79** [comment]
Could somebody help me with this?  I'm really struggling to find ANY help, whatsoever, on transferring my IOTA from the Trinity wallet to the Firefly wallet.  It's set up on my Ledger Nano device, but that is not doing me any good as I cannot send from Trinity to Firely.  It just doesn't allow it to send when I click the send button after putting in my Firefly wallet address.  So, to make a long story short, the seed is on my Ledger device (so it doesn't exist on Trinity settings) and when I put in my Firefly wallet address I'm just flat unable to send it.  I click send but nothing happens.  Therefor my IOTA is just sitting in a discontinued Trinity wallet.  Please help!  I just want to put them on my Ledger device.  Thank you in advance!

**Comment by MiKeF05** [comment]
@Javahake Have you successfully migrated your tokens?

**Comment by Spartachris79** [comment]
Yes, all settled. Thank you.

**Comment by Javahake** [comment]
@MiKeF05 meanwhile yes..I repeated the migration to firefly several times, and at some point it had worked.
But I don‘t know what was the reason why the migration procedure was successful only after several attempts.
Has anybody an idea?

**Comment by MiKeF05** [comment]
The problem is mainly due to connection issues to the ledger. Do you use a Nano S or Nano X? So I guess this issue can be closed.

**Comment by Javahake** [comment]
@MiKeF05 I use a Nano S …
yeah … I also think I can close the issue.
Thx at all

**Comment by Spartachris79** [comment]
Close it.
