### ISSUE TITLE
Firefly is out of view when I open on different monitor setup and the display is not available. 

### ISSUE THREAD

**Issue by MOSDEV82** [iotaledger/firefly#1385]
I found a solution to fix that, maybe it is possible to fix that in Firefly build. To get the view back, I just delete the settings.json. It should not be a problem to check that the stored position is valid during start of firefly... The content of this file is just the window state on exit... {"windowState":{"main":{"x":320,"y":165,"width":1280,"height":720}}}

Please fix that. It is annoying!

**Comment by wonkytonky2** [comment]
got a similar issue
when i switched display 1 with 2 (i got 2 screens) 
firefly was not vissible

**Comment by begonaalvarezd** [comment]
Cant replicate on Linux, looks like a Windows thing 🤔

**Comment by MOSDEV82** [comment]
I think yes, it is a Windows thing. I also have this issue with Ledger Live sometimes. But II found a hotkey to fix that (I am ot Sure ALT+Space).. But its annoying...
