### ISSUE TITLE
No funds on the wallet after migration with ledger nano s

### ISSUE THREAD

**Issue by gregorbonna85** [iotaledger/firefly#1386]
Yesterday I have migrated my tokens to new firefly wallet with my ledger nano s and everything went well. but today I noticed information from firefly on the screen that something went wrong and there was an error and i need to contact iota.org. Then I checked my wallet and balance was zero.

**Comment by MiKeF05** [comment]
Issue can be close see Discord message https://discord.com/channels/397872799483428865/398499876935303186/874351150583930990
