### ISSUE TITLE
All funds disappeared after migration!!!

### ISSUE THREAD

**Issue by gregorbonna85** [iotaledger/firefly#1388]
Yesterday I did token migrations and everything went well i had all my funds on the new firefly wallet but when I saw today on the screen, that there was an issue and I have to contact support. I checked my wallet and there is no funds on it. Did anyone have a similar problem?
Briefly describe the issue.

## Wallet version
1.2.0

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by Tobivaria** [comment]
I would suggest joining the discord and there check out the #help channel.
https://discord.com/invite/uSv4aKDr

**Comment by MiKeF05** [comment]
Issue can be close see Discord message https://discord.com/channels/397872799483428865/398499876935303186/874351150583930990
