### ISSUE TITLE
Backup of the transaction history for ledger wallets

### ISSUE THREAD

**Issue by Travetown** [iotaledger/firefly#1394]
Some exchanges require screenshots of the history of previous transactions when making deposits. Otherwise deposits will not be accepted.
In contrast to the "normal" accounts in Firefly (Stronghold), there is currently no possibility of performing a backup within Firefly and thus ensuring the transaction history in the event of a restore.
I think it is important to also offer a backup solution for the transactions for ledger wallets in Firefly.

## Are you planning to do it yourself in a pull request?

No.

**Comment by maxwellmattryan** [comment]
Hey @Travetown, I've converted this issue into a [discussion](https://github.com/iotaledger/firefly/discussions/1487) 👍 we have been talking about how we would like to approach this one.
