### ISSUE TITLE
Wallet with Tokens disappeared after Migration and Upgrade to 1.2.0

### ISSUE THREAD

**Issue by iotabuddy** [iotaledger/firefly#1398]
## Issue description

I have a few different Trinity wallets that needed to be migrated to Firefly and IOTA 1.5. I migrated 1 successfully yesterday, and then noticed that a new version of Firefly was available. I upgraded to 1.2.0, and soon after, migrated a second Trinity wallet to Firefly successfully. However, when I accessed my first Firefly account today, the interface stated that I had "no wallets" and showed 0 Miota (which is not correct). I tried to "Create a Wallet," which resulted in the error report copied below.

The second account appears to be fine and the wallet and all tokens are accounted for. I have no idea why the wallet / tokens with the first account disappeared. I'm not sure if it's related to the upgrade or not.

## Wallet version

1.2.0 now (1.1.0 recently)

## Error Report

App Version: 1.2.0

platform: macOS
platformVersion: 10.15
platformArchitecture: x64

Error Type: Render Context Error

TypeError: Cannot read property 'signerType' of undefined
    at a (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2911806)
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2912401
    at n (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2843814)
    at m (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2843984)
    at HTMLInputElement.<anonymous> (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2201023)

**Comment by iotabuddy** [comment]
Just FYI - I was easily able to create another profile, enter my 24 word recovery phrase, and the wallet / token amount from the 1st migration (discussed above) appeared again.

**Comment by MiKeF05** [comment]
This issue can be closed as the tokens appeared after creating a new profile
