### ISSUE TITLE
problem finding my Iota

### ISSUE THREAD

**Issue by BlueRay111** [iotaledger/firefly#1400]
Hi, eversince the migration from trinity to firefly I have been unable to find my miotas. I had previously merged trintiy to my nano s. Since the migration to firefly there have been two issues. My balance is missing the checksum is wrong and since I have no balance I cannot make the transfer to my nano s.

**Comment by MiKeF05** [comment]
Do you have your tokens on your Ledger Nano S or do you have a normal seed with length of 81? Have you already done the migration in Firefly?

**Comment by BlueRay111** [comment]
Hi Mike,
My tokens were on my Ledger nano but could only be seen when Trinity was
open. I have my 81 seed from trinity but when I enter it into firefly it
says I have no miota at all  I had 336.36 miota. Thank you for replying.

**Comment by MiKeF05** [comment]
Okay. So if you have all your token on Ledger Nano you do not need the 81 character seed. Because this seed is not connected to your Ledger Nano. All you need to do is the migration process in Firefly with your Ledger Nano. Therefore you can follow this step by step guide to migrate your token to the new network:
https://blog.iota.org/firefly-token-migration-guide-for-ledger-users/

**Comment by MiKeF05** [comment]
@BlueRay111 Have you successfully migrated your tokens to the new network?

**Comment by BlueRay111** [comment]
Mike,
How kind of you to check in. I apologize for not replying to last email. I
find I have to be in the right mindset to prepare myself to learn new
technological apps. I would like to have it done in a few days.  I have the
link you attached and will let you know how it went. Today it is a Blue
Moon so maybe tonight. Take care

**Comment by BlueRay111** [comment]
Hi
I have tried connecting firefly to my nano s and it now has the ledger
symbol but the account still is 0. There is no index number that shows. So
I need help again please. I watched the video link and took the steps but
it seems that  it is not working for me. Thank you

**Comment by MiKeF05** [comment]
Have you done the migration process with the ledger Nano? Seems that you have just created a ledger profile. 
Please try the migration process and use the index number that you have chosen when you set up an account in Trinity.
If you don't know the index number you can disable your internet connection and then open Trinity. Go to your account, account management and view seed to get the correct index number.

**Comment by BlueRay111** [comment]
Phew....this is all new to me. So I went into Trinity like you said I can
see my balance there so now I'm on firefly and migrating ledger and it's
taking more than 20 minutes....is this Normal?
Mike,  thanks for your help so far. Probably will be asking more questions
again. Have a good afternoon

**Comment by MiKeF05** [comment]
Did you see the correct index number under the tab "view seed"? 
I think it would be helpful to join the IOTA Discord server and the help channel. Otherwise it will take too long to get you through the migration process

**Comment by BlueRay111** [comment]
Mike,
I did find my index number it was 0 but that did not make a difference to
when I tried to migrate my wallet. I tried about 14 times and nothing. I am
beyond frustrated. Thanks anyway.

**Comment by MiKeF05** [comment]
Okay. Would it be possible to join the IOTA Discord server and go to the help channel. There we can assist you through the migration. Because there are many things that might to get done. Here is the link: https://discord.iota.org/

**Comment by BlueRay111** [comment]
I am on discord. So I will go on. Thank you and have a nice day

**Comment by MiKeF05** [comment]
Perfect. We will get you through :-) And stay cautious. Do NOT get your seed or your 24 words to anyone.

**Comment by BlueRay111** [comment]
I am on the #help iota discord channel and it seems everyone who is
replying has very bad english. I am not trusting anyone there, can you give
a name of a moderator who can help me. It is hard to distinguish who is
legit or not. Thanks

**Comment by MiKeF05** [comment]
@BlueRay111 Wrote you a DM in Discord

**Comment by BlueRay111** [comment]
Sorry it's taking a while I had to remove discord from my phone and laptop
cause they were not communicating properly. I have to reinstall them and
then reboot my computer
