### ISSUE TITLE
Migration not working when Passphrase in use.

### ISSUE THREAD

**Issue by DexManx** [iotaledger/firefly#1404]
## Issue description

The migration process is not recognizing balances when thoes balances are secured by a passphrase. I have two accounts both secured by different passphrases and the migration process does not recognise neither of them.

It does recognise the base seed, the one not secured by a passphrase.

## Wallet version

Firefly 1.20

Which version of wallet are you using?

the release version: firefly-desktop-1.2.0.exe

## System specification

Windows 10 Pro  10.0.19042 Build 19042

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Have Ledger wallet with legacy address secured by passphrase. 
start migration process, up to point where you specify index (have tried multiple index values), 
funds not found 0 balance!
can not proceed to transfer.

## Expected behaviour

Correct account balance displayed.
mirgation can proceed.

## Actual behaviour

Balance is 0
migration can not proceed

## Errors

none.

**Comment by DexManx** [comment]
was this tested using a passphrase in both the iota app and the iota legacy app?
Has this been confirmed to work?
are there any issues reported on this, with possible workarounds?

**Comment by wonkytonky2** [comment]
i think as work around you can extract seed trough muxxer recovery tool  with passphrase.   

but not sure.

**Comment by DexManx** [comment]
One thing I find strange in the Trinity Wallet

> muxxer

Can

**Comment by DexManx** [comment]
Can someone confirm if this is an issue at the moment ?

**Comment by DexManx** [comment]
> i think as work around you can extract seed trough muxxer recovery tool with passphrase.
> 
> but not sure.

I can go that route, but I really just want to know what's happening, as if it's a common issue or not. If the dev's are working on a solution and it's been recognized as a bug, I am happy to wait and provide information if needed.?

**Comment by DexManx** [comment]
How can this be closed, without an explanation?
Can someone provide some concrete information about this issue?

**Comment by DexManx** [comment]
IOTA Reddit forum has confirmed that migration with passphrase is working.
