### ISSUE TITLE
Conflicting transaction when sending iota from my ledger firefly wallet

### ISSUE THREAD

**Issue by ImYmir** [iotaledger/firefly#1405]
## Issue description

When I try to send iota from my ledger wallet in firefly, I keep getting conflicted transactions on the tangle explorer. The addresses match on my ledger and on firefly when I press send/accept. 
https://explorer.iota.org/mainnet/message/2926bc2e83f8685dab96c0afd3da955c695d03ab24eed93994df794e26156fa5

## Wallet version

Version 1.2.0 and Ledger version 0.7.3

## System specification

Windows 10 version 21H1

## Is it a repeatable issue?

Yes, every time I do it. 

## Steps To reproduce the issue

1. Make wallet with passphrase ledger, deposit some iota only to find out it doesn't work to use with passphrase
2. Make a second ledger wallet that you're 100% confident is your passphrase wallet,
3. Send some iota to that second wallet and then also successfully withdraw without a passphrase. 
4. Try to do the same with the first ledger wallet without a passphrase, but now you only get conflicted transactions.

## Expected behaviour

I expect to get my iota out of my wallet when all addresses match on both the pc and the ledger itself.

## Actual behaviour

Conflicted transactions on the tangle

**Comment by ImYmir** [comment]
https://explorer.iota.org/mainnet/message/28b50d911a00bdbf4d9424e5eb1a5a0d87934aa7b058d2396261094d2cf9dd85

**Comment by ImYmir** [comment]
Just to clear this up, The second wallet I made that I was 100% sure I did with my passphrase, actually was made without the passphrase (because of some bug?), so something weird is going on with each profile. It thinks I keep logging in without passphrase. Which is why I have issues with wrong mnemonic when I try to send from my first wallet.

**Comment by MiKeF05** [comment]
@ImYmir Were you able to solve your issue?

**Comment by ImYmir** [comment]
Yes
________________________________
