### ISSUE TITLE
Wrong conversion to fiat right after migration

### ISSUE THREAD

**Issue by agus-xyz** [iotaledger/firefly#1406]
## Issue description

Right after a succesful migration, the new funds are correct, but the fiat value shown is 0usd.

## Wallet version

v1.2.0

## System specification

Ubuntu 20.04

## Is it a repeatable issue?

I cannot tell actually

## Steps To reproduce the issue

1. Create new profile in wallet
2. Import 81chars seed 
3. Locate and migrate funds 

## Expected behaviour

After migration, the migrated funds value is shown correctly in both iota and fiat (usd)

## Actual behaviour

After migration, the migrated funds value in fiat shows 0usd

## Errors

![Untitled](https://user-images.githubusercontent.com/3696240/129477304-e057282e-aaf9-46b6-b818-32beb499f501.jpg)

**Comment by teunvw14** [comment]
I've had the same issue migrating today actually. Funds migrated fine (and rather quickly too - was very impressed with how smooth it was), yet it showed $0.00 as the value post-migration. The amount shown before starting the migration was fine though.

![Untitled](https://user-images.githubusercontent.com/25725612/129799852-908c2186-67b1-45f7-943c-45ca25412644.png)

**Comment by maxwellmattryan** [comment]
Hey @agus-xyz and @teunvw14, I'm guessing these were migrations for a Ledger device?

**Comment by agus-xyz** [comment]
Hi @maxwellmattryan, nope, standard migration. With no ledger.

**Comment by teunvw14** [comment]
@maxwellmattryan for me the migration was with Ledger (Nano S)
