### ISSUE TITLE
TRINITY WON'T ALLOW TO SEND TO FIREFLY

### ISSUE THREAD

**Issue by Spartachris79** [iotaledger/firefly#1407]
## Issue description I'm unable to send IOTA from Trinity to Firefly.  It just won't allow the SEND button to be clicked.  I no longer have a SEED for Trinity as it's on my Ledger Nano device.  I'm using all the latest versions of everything. I'm using WINDOWS. I sign in to Trinity and there's a red bar at the top where it reads ''TRINITY DISCONTINUED. PLEASE GO TO firefly.iota.org to download the new wallet'' which I've done, but I'm still not being allowed to send from Trinity to Firefly wallet.  Any positive assistance is extremely welcomed.  
Briefly describe the issue.

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by MiKeF05** [comment]
Issue can be closed as the migration was successful. https://discord.com/channels/397872799483428865/398499876935303186/876541947995635712
