### ISSUE TITLE
Ledger passphrase issue

### ISSUE THREAD

**Issue by IncorrigiblePedant** [iotaledger/firefly#1409]
## Issue descript

Can access passphrase protected profile utilising standard/default Ledger Pin. Can generate addresses within the profile - though these do not match between Firefly and Ledger.

## Wallet version

- wallet version (version number, commit, or branch):

1.2.0

## System specification

Windows 10

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

Your Ledger Pin is 1111. You set up a passphrase on Ledger tied to a the Pin 11112222.

You then make a Profile in the Firefly wallet utilising the Ledger Pin 11112222 (nothing to do with the Firefly Pin - this is the Ledger Pin, that allows access to the Send & Receive and address generation. To subtract/add to the confusion lets say that we have made the Firefly Pin 567890).

Now, if I log into this profile (utilising my Firefly Pin 567890), I cannot Sent or Receive or generate addresses until I plug in my Ledger. I therefore plug in my Ledger and I should put in the Ledger Pin 11112222 - this is the only one I have set up in the above step. I however accidentally just put in Ledger Pin 1111 - this is the incorrect Pin, but it still allows me to nominally activate Send & Receive and generate addresses - albeit the addresses it generates do not match with what Firefly displays as the address, and the address displayed on the Ledger. I am not sure what happens past this point if you approve the address on the Ledger, because I don't want to risk finding out :)

This seems to be a case of Firefly allowing access to functionality of the device when it shouldn't be allowing this in this instance.

## Expected behaviour

When I input the incorrect Ledger Pin I expect it to say something along the lines of "Incorrect Ledger Pin", and not allow me (albeit probably nominal) access to the generation of addresses.

## Actual behaviour

It changes the red "Hardware Device Not Detected" to a green "Hardware Device Detected", and allows nominal access to address generation.

I am not overly keen to discover if sending is actually possible...

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by shufps** [comment]
Entering the wrong 2nd pin into the ledger gives you a completely different seed.

Although, you could create a signature, it would be rejected by the nodes because the pub-keys doesn't fit to the input addresses.

**Comment by maxwellmattryan** [comment]
Hey @IncorrigiblePedant this is (mostly) normal behavior. If you confirm the address or try to sign the transaction, it's rejected by Firefly with an error about a mismatching mnemonic. However there's another thing worth fixing, which is that it's possible to create another wallet using a different passphrase within the __same__ Firefly profile.
