### ISSUE TITLE
Where did my miota go?

### ISSUE THREAD

**Issue by Spartachris79** [iotaledger/firefly#1416]
## Issue description I recently migrated everything to Firefly, but now it just shows a zero balance in the wallet.

Briefly describe the issue. The issue is that my wallet is now showing a zero balance.

## Wallet version latest version.

Which version of wallet are you using? Latest version
- wallet version (version number, commit, or branch):

## System specification

What is your operating system? Windows

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by MiKeF05** [comment]
Did you migrate your tokens on a ledger or do you have a normal Firefly profile? Do you see the funds migration transaction in your profile?

**Comment by Mke91** [comment]
this issue is solved helped him in Discord

**Comment by rajivshah3** [comment]
Thanks @Mke91 !
