### ISSUE TITLE
transport error

### ISSUE THREAD

**Issue by babble-ai** [iotaledger/firefly#1420]
## Issue description  In the error log I keep getting "ledger misc error: ledger transport error"

Briefly describe the issue.I downloaded firefly before it could be used with which meant I had to create a 24 word seed, I now want to control firefly with my ledger, it will not do it.
 

## Wallet version1.2.0

Which version of wallet are you using? 1.2.0

- wallet version (version number, commit, or branch):

## System specification 

What is your operating system?  64bit operating system *64 based processor

Mac/Win/Linux (+Version and or Distro if possible)  windows 10 home  os build 19042.1110

## Is it a repeatable issue? 

Yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.download firefly ,  create profile create 24 word seed
2.create second profile to be controlled by ledger, it will not continue beyond create wallet button
3.

## Expected behaviour

Describe what you expect to happen.  it will not go beyond create wallet button

## Actual behaviour

Describe what actually happens. nothing happens

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.
 Ledger misc error: ledger transport error

**Comment by maxwellmattryan** [comment]
Hey @babble-ai, so the problem is that you're unable to create a Ledger profile after creating a software profile? There should be no problem creating an arbitrary amount of different profiles.

**Comment by babble-ai** [comment]
Thank you for repllying, yes that is the problem, what do I do.

**Comment by MiKeF05** [comment]
@babble-ai You could try to uninstall Firefly and delete the folder in C:\Users\[username]\AppData\Roaming\Firefly. Then you can reinstall Firefly. But before you uninstall Firefly make sure to have the 24 words of your normal software wallet.

After you Firefly is installed you can try to restore the software wallet and then create a hardware wallet.

**Comment by babble-ai** [comment]
Thanks for the reply, yes i did as you wrote, no luck the ledger does connect and tries to make a new wallet, eventually the ledger times out with no new wallet there is also no ledger "help" page.

**Comment by MiKeF05** [comment]
Have you checked for the latest firmware update of your Ledger? This would be 2.0 for Ledger Nano S and 1.3 for Ledger Nano X

**Comment by babble-ai** [comment]
In my ledger live it says that at the top it is synchronized and further down it says the ledger nano s is genuine and that the version is up to date 1.6.1. no mention of a 2.0 there.

**Comment by babble-ai** [comment]
Thank you very much, went to the ledger website and downloaded the latest version, proceeded to firefly and was successful in creating a wallet controlled by ledger.

**Comment by MiKeF05** [comment]
Great! I guess this issue can be closed
