### ISSUE TITLE
trinity to firefly migration - paper wallet no longer works

### ISSUE THREAD

**Issue by chazzer66** [iotaledger/firefly#1424]
## Issue description

I launched Firefly and used my 81 ch paper wallet. It is showing zero balance. Checksum is correct.

## Wallet version

Version 1.2.0

## System specification

What is your operating system?

Mac 11.5.1

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Just reenter the 81 chs and repeat
2.
3.

## Expected behaviour

Should be a balance

## Actual behaviour

Zero balance and requested to try again

## Errors

Error log is empty

**Comment by Mke91** [comment]
And you are sure there are funds on this seed? 
To check install trinity wallet type in that seed and have a look if you see your funds.

**Comment by chazzer66** [comment]
Thanks!

Ok. I still have the old Trinity wallet on iOS. I can see that the seed is the same as my paper seed. I can also see a zero balance. I thought I transferred the Iota to the desktop wallet a while back ahead of the migration and I can see a transaction to do that on 21st April. 

Now I am wondering where it went since the desktop Trinity wallet on my Mac no longer opens even if I load the latest version. 

Any ideas please?

**Comment by Mke91** [comment]
Maybe you already migrated? cause first migration phase was possible 21st of april.
So you would need your 24 word recovery phrase to recover your iotas if you have no access to them

**Comment by chazzer66** [comment]
Ok that seems plausible given the date of the transaction. Can I enter the recovery phrase in Firefly? Is that how I do it?

**Comment by Mke91** [comment]
yes you can enter the recovery phrase in firefly choose the option -> migrate or restore a wallet -> then select i have an firefly recovery phrase

**Comment by chazzer66** [comment]
Thanks again - I’ll give it a try!

**Comment by chazzer66** [comment]
Hello again

I’ve checked and I cannot find a 24 word recovery phrase. I don’t recall getting one at all actually. I originally purchase MIOTA on Bittrex on 10/2/20 and then set up the Trinity wallet on mobile. I transferred the MIOTA to the wallet on 13/2/2. I think it was at that time that I got the paper wallet with the 81 ch seed. 

Do you have any other ideas? How was the transfer made on 21st April if I did not initiate it?

Thanks again

**Comment by zarrillojr** [comment]
Hi guys,, I think I have similar issues  like everyone,,? Trinity wallet doesn't show up  Firefly wallet doesn't   admit any iota tokens from my others wallet to activated the wallet I think I lost my 781 iota I bought 2020 much appreciated help to recover them thanks.

**Comment by MiKeF05** [comment]
@zarrillojr Have you done the migration steps to migrate your tokens to the new network?

**Comment by chazzer66** [comment]
Hi @zarrillojr - what are these migration steps please?

**Comment by MiKeF05** [comment]
@chazzer66 No one could do the transaction without the seed. So you said that you have done a transaction to your Trinity desktop wallet? You can try to disable your internet connection and login to Trinity. Then you can check the seed and migrate it with the correct balance

**Comment by maxwellmattryan** [comment]
@zarrillojr @chazzer66 Migration steps are [here](https://blog.iota.org/firefly-token-migration-guide-for-ledger-users/). Please let us know how things go ~

**Comment by chazzer66** [comment]
Thanks for the migration steps but I don’t use Ledger for MIOTA so is this applicable?

Also I tried the earlier suggestion to use Trinity desktop wallet while disconnected from the internet and it does not login. It returns “Node Error”. Suggests changing node or disabling system proxy. I tried disabling system proxy but does not work. 

Any other suggestions please?

**Comment by chazzer66** [comment]
Thanks for the migration steps but I don’t use Ledger for IOTA so is this applicable?

Also I tried the earlier suggestion to use Trinity desktop wallet while disconnected from the internet and it does not login. It returns “Node Error”. Suggests changing node or disabling system proxy. I tried disabling system proxy but does not work. 

Then I reconnected to the internet and tried the Trinity desktop login again and this time it worked for some reason. Now I can see my IOTA again in that wallet. So how do I get these into Firefly?

**Comment by MiKeF05** [comment]
@chazzer66 Okay. So you can go in Trinity to your account with the tokens -> account management -> view seed. There you should see the 81 char seed you need for the migration. Don´t share this seed with anyone.
After that you can follow the steps in the blog article to migrate your seed (https://blog.iota.org/firefly-token-migration/).

**Comment by chazzer66** [comment]
Apologies! I had forgotten that I did indeed use the legacy app on Ledger. I have been able to complete the migration successfully now and expected balances are in Firefly. Thanks again for your help and sorry for confusion!

**Comment by MiKeF05** [comment]
No worries! 😉 Glad to hear that you successfully completed the migration. I guess this issue can be closed.

**Comment by chazzer66** [comment]
Confirmed :)

**Comment by jojo-9** [comment]
hello,

Can somebody help me please. I tried to do the migration from trinity to firefly with ledger wallet, but I seen no iota in the account to migrate. Is it possible it doesn't show because I connect through a hub with my computer??

**Comment by MiKeF05** [comment]
Hello,

there are several things that might influence your balance. Did you use the correct index number? You have to use the index number that you selected when you created the Trinity profile. Also make sure to connect the ledger directly to an USB port. Also does your ledger display "Generating Adresses" when you hit search balance?

**Comment by jojo-9** [comment]
hello,

normally I use the default index number. I tried the first 12 and none of them contain my coins. I connected the ledger with the apple cable to my labtop and that didn't work then I read I should use the original ledger cable but since I don't have usb connection on my labtop I connected it with a small hub. the ledger does show "Generating Adress" but my balance doesn't show up.

**Comment by MiKeF05** [comment]
Are you sure that your tokens are on your ledger? Are you sure that you use the correct index number? You can also login to Trinity to see which index you used.

**Comment by jojo-9** [comment]
Hello,

I found my iotas and was doing the migration but during the process my internet went down. The migration was made in two transfers the first transfer was migrated but during the second internet went down. No when I got my internet back and checked the firefly application I got a ledger account but I have 0 iotas.

Can you please help me out here?

Kind regards,
Mijanou

**Comment by jojo-9** [comment]
Hello,

I panicked when I didn’t see my iotas, but simply forgot to connect my hardware wallet. The migration was succesfully. I want to thank you very much for the help you have given me. I now have all my funds in the firefly application.

Kind regards,
Mijanou
