### ISSUE TITLE
Miotas desapeared from my wallet when I changed my pin

### ISSUE THREAD

**Issue by MikelTeemo** [iotaledger/firefly#1425]
## Issue description

Miotas desapeared from my wallet when I changed my pin

## Wallet version

Firefly 1.1.0

## System specification

Windows 10

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Enter in your wallet with you pin
2. Change the pin in settings and close the wallet
3. Entre with the new pin

## Expected behaviour

I expected to see my coins like before.

## Actual behaviour

The coins desapeared

## Errors

App Version: 1.1.0

platform: win32
platformVersion: 10.0.19042
platformArchitecture: x64
cpuCount: 12
totalMem: 16332.5 MB
freeMem: 12501.3 MB
userPath: C:\Users\Mike\AppData\Roaming\Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'id' of undefined
    at C:\Users\Mike\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:165586
    at C:\Users\Mike\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:197606
    at Array.forEach (<anonymous>)
    at destroy (C:\Users\Mike\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:197594)
    at C:\Users\Mike\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:191379

**Comment by MiKeF05** [comment]
Make sure to have the latest version of Firefly. Just update it and make a new fresh profile with restoring your wallet. Therefore you need the 24 words, your stronghold + password or your hardware ledger.

**Comment by maxwellmattryan** [comment]
Hey @MikelTeemo, did your wallet's disappear entirely or did the balance simply go to 0 Mi? If you go on the dashboard it should either have at least one wallet or a message saying something like "You do not have any wallets".
