### ISSUE TITLE
BSC into Firefly

### ISSUE THREAD

**Issue by MPKGITHUB** [iotaledger/firefly#1430]
### Issue description

I set up a Firefly account because I thought Firefly would accept transfer on the BSC (Binance Smart Chain) network so I can withdraw my IOTA coins from Binance.com into Firefly. However, after I set up the Firefly account and got an address for an IOTA wallet, it will not work on the Binance.com to withdraw via BSC.

Did I misunderstand something?

Is it possible to use BSC to transfer coins to Firefly?

### Firefly version

1.2.0

### OS details

Mac OS 11.5.2

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Make a wallet in Firefly
2. Try to withdraw IOTA coins from Binance.com to Firefly
3.
...

### Expected behaviour

Coins transfer from Binance.com to Firefly

### Actual behaviour

Error message:  BSC in umatched to the address copied from Firefly/

### Errors

<img width="498" alt="Screen Shot 2021-08-27 at 6 27 56 PM" src="https://user-images.githubusercontent.com/89636179/131105788-30d275d3-6d3d-4cd8-9862-c894ad465fcf.png">

**Comment by cvarley100** [comment]
BEP20 tokens are not currently supported in Firefly. Only the IOTA token is.
