### ISSUE TITLE
ClientError: {}

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/firefly#1433]
### Issue description

When logging out of a profile this error is added to the error log, the

It starts from here https://github.com/iotaledger/firefly/blob/e83c3415deab0b5e25c457a652ef7fd428a158a6/packages/backend/bindings/node/native/src/lib.rs#L62  and the error message is `receiving on a closed channel`
Here https://github.com/iotaledger/firefly/blob/e83c3415deab0b5e25c457a652ef7fd428a158a6/packages/shared/lib/shell/walletApi.ts#L139 it gets converted to this `ClientError` and since the message is only a string, JSON.stringify() removes it

### Firefly version

dev

### OS details

Windows

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Log into a profile
2. Logout
3. Open Error log

### Expected behaviour

There should be no error, the polling should probably stop before or maybe we just ignore this particular error?
Apart from that the error message should be visible

### Actual behaviour

Error is visible in the log, but doesn't really help

**Comment by Thoralf-M** [comment]
To show at least the error message one could use 
```JS
        let messageData = JSON.stringify(message);
        if (messageData == "{}") {
            messageData = message.toString();
        }
        const newError = { type: ErrorType.ClientError, message: messageData, time: Date.now() }
```
here https://github.com/iotaledger/firefly/blob/e83c3415deab0b5e25c457a652ef7fd428a158a6/packages/shared/lib/shell/walletApi.ts#L139

**Comment by nicole-obrien** [comment]
Thanks for the suggestion, I will create a PR for this change. Any chance you know where this polling is happening after logout, might be able to stop that too. 😕

**Comment by Thoralf-M** [comment]
No sorry, don't know from where this is called
