### ISSUE TITLE
Account Setup issue

### ISSUE THREAD

**Issue by RobynKismine** [iotaledger/firefly#1435]
### Issue description

I moved my Iota from Trinity to Chrysalis.  The process took overnight and the next morning I noticed the transfer was still in process.  I went in to Firefly to create an account.  After I created the account I was having sign in problems and it asked me to create an account (again).  I created another account.  I cannot log in to my first account, and my second account is showing a 0 balance.  Please help me recover my original account or get my Iota transferred from it to my 2nd account.

### Firefly version

1.2.0

### OS details

Windows 10

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

I expected the transfer and my account set up to work properly

### Actual behaviour

I cannot log in to the account where I believe my Iota's are.

**Comment by MiKeF05** [comment]
Do you have access to Trinity? You can check if the migration was successful. Therefore disable your internet connection and log into Trinity. If the balance is still there the migration was not successful and you have to do the migration again. Do you use a ledger?

**Comment by RobynKismine** [comment]
Hello, I attempted to migrate my Iota from Trinity to Firefly via Chrysalis.  In the process I created User Name Dragonfly9. I woke the next morning to find the migration was still in process.  Thinking that something went wrong as it had been many hours later, I created a new User in Firefly: Saturn5Kite.  I can get in the Saturn5Kite User account, (which shows a 0 Balance), however, I'm quite certain the Iota transferred into the original account I created: Dragonfly9.  Is there any way that I can get into this account as I cannot find any information regarding the PIN#, etc..? I have the PIN and Firefly recovery phrase for the Saturn5Kite User account in Firefly, and I have the recovery phrase for Chrysalis, but I do not have the PIN or the recovery phrase for my Dragonfly9 User account in Firefly, where I believe my Iota is located. There must be some kind of verification that I can use such as my email address to recover the Dragonfly9 account.  Please help me. Thank you. Ronald MacBaen 
    

-----Original Message-----

From: MiKeF05 ***@***.***>
To: iotaledger ***@***.***>
Cc: RobynKismine ***@***.***>; Author ***@***.***>
Date: Friday, 3 September 2021 1:15 PM -08
Subject: Re: [iotaledger/firefly] Account Setup issue (#1435)

 

  

Do you have access to Trinity? You can check if the migration was successful. Therefore disable your internet connection and log into Trinity. If the balance is still there the migration was not successful and you have to do the migration again. Do you use a ledger? —
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MiKeF05** [comment]
Did you migrate with a ledger device or normal 81 char seed?

**Comment by RobynKismine** [comment]
Hi Mike, Not a ledger, I have an 81 character seed 
    

-----Original Message-----

From: MiKeF05 ***@***.***>
To: iotaledger ***@***.***>
Cc: RobynKismine ***@***.***>; Author ***@***.***>
Date: Saturday, 4 September 2021 1:50 AM -08
Subject: Re: [iotaledger/firefly] Account Setup issue (#1435)

 

  

Did you migrate with a ledger device or normal 81 char seed? —
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MiKeF05** [comment]
So you have followed the steps described in this article in the first migration? https://blog.iota.org/firefly-token-migration/
Normally you should have set a PIN and password for the account in the first migration. I guess with recovery phrase for Chrysalis you mean the 24 words of your first migration.

Please try the following steps: Open Firefly -> Create new profile -> Restore wallet -> I have a Firefly backup phrase. There you can set a PIN and a password. And try to use the 24 words for Chrysalis.

**Comment by MiKeF05** [comment]
@RobynKismine Were you able to migrate your tokens and login into your profile in Firefly?

**Comment by RobynKismine** [comment]
Thanks Mike. Problem solved. I appreciate your help and follow up. Have a great day.  
    

-----Original Message-----

From: MiKeF05 ***@***.***>
To: iotaledger ***@***.***>
Cc: RobynKismine ***@***.***>; Mention ***@***.***>
Date: Tuesday, 7 September 2021 1:51 PM EDT
Subject: Re: [iotaledger/firefly] Account Setup issue (#1435)

 

  

@RobynKismine Were you able to migrate your tokens and login into your profile in Firefly? —
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MiKeF05** [comment]
Perfect. I guess this issue can be closed....

**Comment by RobynKismine** [comment]
Yes, thanks 
    

-----Original Message-----

From: MiKeF05 ***@***.***>
To: iotaledger ***@***.***>
Cc: RobynKismine ***@***.***>; Mention ***@***.***>
Date: Tuesday, 7 September 2021 11:18 AM -08
Subject: Re: [iotaledger/firefly] Account Setup issue (#1435)

 

  

Perfect. I guess this issue can be closed.... —
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
