### ISSUE TITLE
Firefly wallet on Ledger Nano X disappeared

### ISSUE THREAD

**Issue by davwag** [iotaledger/firefly#1436]
### Issue description

1) Created a profile + wallet via Firefly on Ledger Nano X yesterday, transfered IOTA to it.
2) Today not accessable anymore. "Status: Network disconnected" and no wallet is in there anymore (=disappeared completely).
3) The hardware appears to be recognized ("Hardware device connected") but does not recognize a wallet on it.
3) When I try to create a new wallet, error appears (error log below)

### Firefly version

1.2.0

### OS details

Linux Kubuntu 20.04 LTS

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

Maybe only in my case (I don't want to test more as there are tokens on):
1) Start Ledger Nano X
2) Open IOTA app on Ledger Nano X
3) Open Firefly
4) Create profile for Ledger Nano X on Firefly (Kubuntu 20.04 LTS)
5) Create Wallet within this profile + transfer IOTA tokens into it
6) Exit Firefly, disconnect Ledger Nano
7) Reconnect Ledger Nano
8) open Firefly
9) Login to Ledger Nano profile

### Expected behaviour

1) To be able to access my IOTA token
2) To be able to create a wallet

### Actual behaviour

1) Wallet is not appearing
2) Wallet cannot be created

### Errors

App Version: 1.2.0

platform: linux
platformVersion: 5.4.0-81-generic
platformArchitecture: x64
cpuCount: 4
totalMem: 19721.5 MB
freeMem: 15746.1 MB
userPath: /home/user/.config/Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'id' of undefined
    at /tmp/.mount_fireflUUQggu/resources/app.asar/public/build/preload.js:2:548226
    at /tmp/.mount_fireflUUQggu/resources/app.asar/public/build/preload.js:2:590514
    at Array.forEach (<anonymous>)
    at destroy (/tmp/.mount_fireflUUQggu/resources/app.asar/public/build/preload.js:2:590502)
    at /tmp/.mount_fireflUUQggu/resources/app.asar/public/build/preload.js:2:582572

**Comment by MiKeF05** [comment]
Do you only have the profile with the ledger? And you have several wallets in this profile or just one?

**Comment by elsersinn** [comment]
I have the same issue with MacOS 11.5.1 and Ledger Nano S. I have 2 profiles, one works correctly but the one with Ledger shows Network disconnected. 1 wallet per profile.

**Comment by MiKeF05** [comment]
Please try to create a new profile for the ledger and then choose the option restore hardware wallet -> Firefly ledger backup. I guess you should then be able to connect to the network. And can then delete the older ledger profile.

**Comment by elsersinn** [comment]
Hi, I followed those steps and everything is working now. Thanks!!

**Comment by davwag** [comment]
> Please try to create a new profile for the ledger and then choose the option restore hardware wallet -> Firefly ledger backup. I guess you should then be able to connect to the network. And you are able to delete the older ledger profile. @elsersinn

That worked for me, too. Thanks!

**Comment by MiKeF05** [comment]
Issue can be closed
