### ISSUE TITLE
Signing/Verifying messages in firefly.

### ISSUE THREAD

**Issue by Skerberus** [iotaledger/firefly#1437]
## Description

With the new EdDSA signatures it should be possible to sign a given message and verify that is was signed by a given address. This would be a very nice feature within firefly.

## Motivation

To show that I have control of a given address e.g. tax reasons.

## Requirements

Write a list of what you want this feature to do.

1. Sign a message with a given address.
2. Verify that a given message was signed by the private key belonging to that address.

## Are you planning to do it yourself in a pull request?

No.

**Comment by maxwellmattryan** [comment]
Hey @Skerberus, I've moved this issue to a [discussion](https://github.com/iotaledger/firefly/discussions/1488) so that this can be closed 👍
