### ISSUE TITLE
App no longer enables PIN entry 

### ISSUE THREAD

**Issue by GHolden68** [iotaledger/firefly#1438]
### Issue description

I enter my PIN but nothing happens. It worked when I set it up a while ago.  I have updated to the latest v1.2.0 but after I enter the code, nothing happens.  There is no button to click to enter it - it just sits there.  I have tried to find a config file but cannot find it as saw that referenced in one issue.  I am not hugely technical so just need the software to work as it should.  
![Firefly hanging](https://user-images.githubusercontent.com/90053429/132024591-09022fe5-0772-40a7-9968-2d98d04ea971.PNG)

Is this a common issue /bug?

### Firefly version

1.2.0

### OS details

Windows 10 Pro

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Open Firefly
2. Select my profile icon
3. Enter correct PIN
4. Nothing happens
...
![Firefly hanging](https://user-images.githubusercontent.com/90053429/132025716-07ac252f-9074-4ac4-aed5-1ab54523f766.PNG)

### Expected behaviour

Presume the PIN either works or there is an option to hit "enter"

### Actual behaviour

Nothing happens and no option appears to enter the PIN

### Errors

No errors on screen

Diagnostics report: 
Firefly v1.2.0
Language: en
Currency: USD
Node settings: Automatic node selection
Platform: win32
Platform Version: 10.0.19043
Platform Architecture: x64
CPU Count: 4
Total Memory: 16301.3 MB
Free Memory: 9190.4 MB
User Path: C:\Users\holde\AppData\Roaming\Firefly

Error log is empty

**Comment by MiKeF05** [comment]
Did you try to restart your computer?

If the restart doesn´t help you can do the following. Uninstall Firefly and delete the folder Firefly in C:\Users\holde\AppData\Roaming. Then reinstall Firefly and create a new profile. There you can choose the option to restore your profile. Before you uninstall make sure to have your 24 words for the backup.

**Comment by GHolden68** [comment]
Many thanks – that fixed it!
