### ISSUE TITLE
Network not connect

### ISSUE THREAD

**Issue by gasserf97** [iotaledger/firefly#1439]
### Issue description

Network does not connect on profil 1, i add a second profil and it worked. On the first one it does still not connect.

Maybe it happend because i canceld before a profile. I´m using Ledger Nano S.

Error Log is empty

### Firefly version

1.2.0

### OS details

Windows 10 Pro_ 19043.1165

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...
.

### Expected behaviour

.

### Actual behaviour

.

**Comment by MiKeF05** [comment]
You can try to restore the profil with a freshly new created profile. To restore the profile just connect your ledger and choose the option restore hardware wallet and then Firefly ledger backup.

**Comment by gasserf97** [comment]
Yes i have done it. I wrote it just that you know that the problem does exist

**Comment by diegom1298** [comment]
I had the same issue. I solve it by creating a new profile, but i didnt create it from start. I create the new profile by restoring my previous wallet by the backup (stronghold, seed,etc). It worked and connected to the network correctly.

**Comment by nicole-obrien** [comment]
Hi @gasserf97, sorry for the delay. Can you remember if you changed your profiles pin before this occurred?

**Comment by Shobba** [comment]
I've got the same problem. Every time I add a new profile for my Ledger Nano, the next time I open Firefly and check that profile it says "Network not connected", the wallet is gone ("Du hast keine Wallets. Bitte erstelle eine.") and I basically have to remove that profile and re-add it. But next time I open Firefly, the exact same problem occurs :(
I'm on macOS.

**Comment by gasserf97** [comment]
Hi @nicole-obrien  i´m not 100 % sure but i don´t think that i have changed my password

**Comment by nicole-obrien** [comment]
Do you currently have access to your accounts?

**Comment by gasserf97** [comment]
Yes i do
