### ISSUE TITLE
Network Disconnected

### ISSUE THREAD

**Issue by rajadixon** [iotaledger/firefly#1442]
### Issue description

Since the installation of the wallet it show "Network Disconnected" and always shows notification as "Something went wrong". Everything is fine in Firewall and anti-virus. When i checked for error log it shows like this - tcp open error: An invalid argument was supplied (os error 10022). What i have to do now?

### Firefly version

Firefly v1.2.0

### OS details

Windows 7

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

Want to connect my wallet to network

### Actual behaviour

Unable to connect the wallet to network i.e unable to bring my tokens from exchange.

### Errors

![IMG_4093](https://user-images.githubusercontent.com/90019645/132119610-e3f59ca2-cb20-4b5d-98df-b11eb46a1861.jpeg)
![IMG_4094](https://user-images.githubusercontent.com/90019645/132119621-9aff1569-e103-4145-8852-638045c89d0a.jpeg)
![IMG_4095](https://user-images.githubusercontent.com/90019645/132119628-d37381e5-2d9c-40e2-8dad-69df906e8ee6.jpeg)

**Comment by MiKeF05** [comment]
Have you tried to temporarily disable your firewall? Looks like something blocks the connection. Is this your privat computer?

**Comment by rajadixon** [comment]
> Have you tried to temporarily disable your firewall? Looks like something blocks the connection. Is this your privat computer?

Yes, i tried but it still shows the same thing. Yes, it's my private computer.

**Comment by MiKeF05** [comment]
Maybe you have another computer to try it? Would be worth to try...

**Comment by rajadixon** [comment]
> Maybe you have another computer to try it? Would be worth to try...

Yes, it worked fine on another computer running on windows 10 OS, Thank you..!!! I think the problem was associate with windows 7 because i tried with two computer running on windows 7 and it shows the same result so, i request development team to look after it. My problem has been solved. Thank you.

**Comment by diegom1298** [comment]
I had the same issue. I solve it by creating a new profile, but i didnt create it from start. I create the new profile by restoring my previous wallet by the backup (stronghold, seed,etc). It worked and connected to the network correctly.

**Comment by eBinder2** [comment]
Hi, i've got the same status and network message.., Network disconnected and Something went wrong.

In my case it is not a personal laptop, and the log says..  
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): error trying to connect: invalid certificate: UnknownIssuer`

My data:
Firefly v1.2.0
Language: en
Currency: EUR
Node settings: Automatic node selection
Platform: win32
Platform Version: 10.0.19042
Platform Architecture: x64
CPU Count: 4
Total Memory: 8031.9 MB
Free Memory: 2735.8 MB

So..unable to see the coins a sent from an exchange to Firefly.

Thank you so much!

**Comment by diegom1298** [comment]
Hi men,
I solve this problem by restoring the profile than wasnt working with a new one on the same firefly wallet.
You can restore it by your seed or the steonghold archive.
Good luck
--
Enviado desde myMail para Android miércoles, 24 noviembre 2021, 00:56p. m. -05:00 de eBinder2  ***@***.*** :
