### ISSUE TITLE
Migration of 1.00 Mi never completes

### ISSUE THREAD

**Issue by janzilka** [iotaledger/firefly#1443]
### Issue description

Folllowed funds migration guide from Legacy IOTA to IOTA on Chrisalis. All steps seemed to finish properly but the last one. Transfer funds never finished (writing this issue after more than 60 minutes seeing "Migrating funds" message in Firefly)

The amount to migrate was exact minimum limit recommended 1.00 MIOTA

### Firefly version

1.2.0

### OS details

Windows 10 Enterprise version 1909 (OS build 18363.1734)

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Connected Ledger Nano X using USB cable
2. Generated address
3. Switched Ledger app
4. Initiated "Transfer funds" 

... transfer never finishes 

### Expected behaviour

Migration should get finished in 30 minutes I expect

### Actual behaviour

Never finishes the "Transfer funds"

### Errors

no errors generated

**Comment by MiKeF05** [comment]
Try to do the migration steps from the beginning again. In the step transfer funds close and reopen the legacy app on ledger. A popup to confirm the transaction should appear.
