### ISSUE TITLE
Migrating Trinity Wallet failed

### ISSUE THREAD

**Issue by ston2** [iotaledger/firefly#1447]
### Issue description

I installed a new Firefly on my notebook to transfer my Trinity Wallet.

After entering my Trinity seed, the new Firefly Security Phrase was displayed. However, before I could save or copy the phrase, my notebook went into standby mode because it had no power.

After I plugged in the power cable and restarted the notebook, the Firefly wallet only showed a blank white window (maybe just background), the phrase was no longer displayed. It was not possible for me to restore the phrase. After that I cancelled the process and restarted Firefly.

But now Firefly does not accept the Trinity seed anymore. Therefore, I cannot complete the transfer of my wallet and thus cannot reproduce the error.

In the old Trinity wallet the correct amount is shown, I hope the transfer did not start, is that correct? If not, where are my IOTA's? 
How can I complete the transfer?

### Firefly version

1.2.0

### OS details

Windows 10 home

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1. See description

### Expected behaviour

Completed Wallet transfer 

### Actual behaviour

See description

**Comment by MiKeF05** [comment]
If the balance is still shown in Trinity the process of the migration didn't finish. Try the following:
Uninstall Firefly and delete the folder Firefly in "C:\Users[username]\AppData\Roaming\"
After that install Firefly again and start the migration again.

**Comment by ston2** [comment]
Thank you for your advice. 
Now it works and the wallet is transfered.
