### ISSUE TITLE
Cannot find balance during migration

### ISSUE THREAD

**Issue by Estiven23** [iotaledger/firefly#1459]
### Issue description

Ingreso la semilla para emigrar mis tokens a la nueva billetera de IOTA, FIREFLY, me brinda el código de verificación, el cual es correcto y aun así no me reconoce mi saldo y no me deja continuar con el proceso de emigrar mi cuenta de TRINITY a FIREFLY.
Se queda en verifique su saldo o si ha ingresado correctamente su semilla de 81 palabras.
Al crear la nueva wallet tenía en TRINITY saldo.
¿Cómo hago para rescatar mis tokens?

Comunicarse por favor a mi email:

estiven23@gmail.com

gracias.

### Firefly version

FIREFLY 1.2.0

### OS details

WINDOWS 10 Home Single Language 64 BITS

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Ingrese la semilla de 81 palabras
2. Darle continuar y se genera el problema
3.
...

### Expected behaviour

Que me asigne mis tokens tenidos en TRINITY - IOTA

### Actual behaviour

No me deja importar o emigrar mis tokens a FIREFLY de TRINITY antigua versión de IOTA

### Errors

![ERROR MIGRACIÓN TOKENS IOTA](https://user-images.githubusercontent.com/90590055/133021726-dfa2a9ec-2a38-45db-aaa2-eea8c409089e.jpg)

**Comment by cvarley100** [comment]
How many addresses do you have in Trinity? You might need to press "Check Again" several times.
