### ISSUE TITLE
Preload Content Error Firefly IOTA

### ISSUE THREAD

**Issue by mpfanni610** [iotaledger/firefly#1465]
### Issue description

Hi, 
i want to migrate my trinity wallet to firefly wallet. But during the migration it stops and the following error was show.
Trininty  value = 0
Firefly value = 0

NEED help!

App Version: 1.2.0

platform: win32
platformVersion: 10.0.19041
platformArchitecture: x64
cpuCount: 4
totalMem: 16239.7 MB
freeMem: 13068.3 MB
userPath: C:\Users\12345\AppData\Roaming\Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'forEach' of null
    at C:\Users\12345\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:548089
    at C:\Users\12345\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:590377
    at Array.forEach (<anonymous>)
    at destroy (C:\Users\12345\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:590365)
    at C:\Users\12345\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:582435

### Firefly version

1.2.0

### OS details

Windows 10 

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1. Doin the migration step by step.
2.Migration start after 5 minutes -> error
3.
...

### Expected behaviour

Only the error text and both wallets = 0

### Actual behaviour

Need help quick please

### Errors

App Version: 1.2.0

platform: win32
platformVersion: 10.0.19041
platformArchitecture: x64
cpuCount: 4
totalMem: 16239.7 MB
freeMem: 13068.3 MB
userPath: C:\Users\12345\AppData\Roaming\Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'forEach' of null
    at C:\Users\12345\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:548089
    at C:\Users\12345\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:590377
    at Array.forEach (<anonymous>)
    at destroy (C:\Users\12345\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:590365)
    at C:\Users\12345\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:582435

**Comment by MiKeF05** [comment]
Is the balance in the Trinity wallet now 0? Try the following: Create a new profile and then choose the option restore profile with Firefly backup phrase.

**Comment by mpfanni610** [comment]
Thank you for your answer.

Yes it’s 0.

In the history can I see, that my amount was -149 Miota. So it means transfered, right ?

Von meinem iPhone gesendet

**Comment by mpfanni610** [comment]
Ok, I made a new account. But nothing does change

**Comment by MiKeF05** [comment]
Is your balance in Trinity 0?

**Comment by mpfanni610** [comment]
Yes, also in firefly

**Comment by MiKeF05** [comment]
Did you migrate with a ledger?

**Comment by mpfanni610** [comment]
Yes. The migration stop with the ledger connected. And then the error is show.

**Comment by MiKeF05** [comment]
I would suggest to uninstall Firefly and delete the folder Firefly in C:\Users\12345\AppData\Roaming. After that install Firefly again, choose restore wallet-> Hardware wallet -> Firefly Ledger backup. If your balance should not appear I would suggest to join the IOTA Discord server and go to the help channel.

**Comment by mpfanni610** [comment]
Ok, thank you very much. I will try it tomorrow evening. If it fix my problem, I would let you know. Thank you

**Comment by mpfanni610** [comment]
It doesnt work :/

**Comment by MiKeF05** [comment]
The best way will be to join the IOTA discord server to get quick help.
