### ISSUE TITLE
Preload context error

### ISSUE THREAD

**Issue by ecbusta123** [iotaledger/firefly#1469]
### Issue description

I cannot see my balance in firefly. I have connected the Ledger Nano S.

Status is 'Network Disconnected'.

When I try to create a test wallet, I get an error.

### Firefly version

v1.2.0

### OS details

Windows 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

Access balance when connecting ledger nano S

### Actual behaviour

Unable to see Iota balance.

Firefly status is 'Network Disconnected'

Error when trying to create test wallet.

### Errors

App Version: 1.2.0

platform: win32
platformVersion: 10.0.10586
platformArchitecture: x64
cpuCount: 4
totalMem: 3954.6 MB
freeMem: 638.0 MB
userPath: C:\Users\1234\AppData\Roaming\Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'signerType' of undefined
    at C:\Users\1234\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:548089
    at C:\Users\1234\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:590377
    at Array.forEach (<anonymous>)
    at destroy (C:\Users\1234\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:590365)
    at C:\Users\1234\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:582435

**Comment by MiKeF05** [comment]
You already have migrated your tokens to the new network?

**Comment by ecbusta123** [comment]
I set up my ledger and bought iota recently. I believe it's already on the new network.

**Comment by MiKeF05** [comment]
I would suggest to uninstall Firefly and delete the folder Firefly in C:\Users\1234\AppData\Roaming\. After that install Firefly again, choose restore wallet-> Hardware wallet -> Firefly Ledger backup. If your balance doesn´t appear I would suggest to join the IOTA Discord server and go to the help channel.

**Comment by ecbusta123** [comment]
Thank you, that worked.
