### ISSUE TITLE
PIN für Anmeldung falsch

### ISSUE THREAD

**Issue by Safde2406** [iotaledger/firefly#1474]
### Issue description

Beim Versuch mich bei der Firefly-Wallet anzumelden und den PIN eingeben, heißt es, dass der PIN falsch sei. Ich bin mir jedoch sicher dass der PIN zu 100% korrekt ist.
Habe auch schon ein neues Profil angelegt. Bei der ersten Anmeldung funktioniert es einwandfrei. Melde ich mich jedoch ab und will mich wieder anmelden, tritt das gleiche Problem wieder auf.

### Firefly version

1.2.0

### OS details

Windows 7

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Firefly öffnen
2. Profil auswählen
3. PIN eingeben
4. Fehlermeldung: "1 falscher Versuch"
...

### Expected behaviour

Anmeldung erfolgt

### Actual behaviour

Keine Anmeldung möglich

**Comment by ratiodep** [comment]
Firefly does not support Windows 7

**Comment by Safde2406** [comment]
Ok schade. Vielen Dank für die schnelle Hilfe

**Comment by Yanev1** [comment]
I have the same issue on a Mac. My PIN code is 100% correct, but for some reason doesn't recognize it, and it tells me I'm entering an incorrect pin code. Can anyone help to resolve this?
