### ISSUE TITLE
Stuck at "Verify your Pin Code"

### ISSUE THREAD

**Issue by Neshura87** [iotaledger/firefly#1476]
### Issue description

Stuck at "Verify your Pin Code" when recovering from a stronghold file, clicking the button does nothing

### Firefly version

1.2.0

### OS details

Manjaro 15.13.13-1

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Recover Stronghold file
2. Enter Pin Code
3. Stuck on the confirm screen
...

### Expected behaviour

Pin Code either rejected or accepted upon clicking "Confirm Pin Code"

### Actual behaviour

"Confirm Pin Code" button does nothing

**Comment by MiKeF05** [comment]
I guess this has something to do with this issue: 
https://github.com/iotaledger/firefly/issues/243

Can you try the steps described there?

**Comment by Neshura87** [comment]
Installing gnome-keyring worked
