### ISSUE TITLE
seems some wallet is  "hidden" and not showing my balance

### ISSUE THREAD

**Issue by bazakida** [iotaledger/firefly#1477]
### Issue description

after sending iota internaly  wallets looked messed up : double entries  with 0 value

![image](https://user-images.githubusercontent.com/89320402/133842111-75c1d0cc-127c-48e3-b6eb-7dee447a3a58.png)

the value  graph was also negative. 

seems the money is somehow still there but it doesn't show to correct "wallet"  whith the correct address where i internally send the money.

i did unhide wallets. but it's not showing up
i did find balance button many times .. nothing shows up

i had this before i think.   i fixed it with entering 24 words  from scratch. but this time i only have the backup file not the words .

some resest button to move all addresses  in 1 wallet would be nice;  probalby not having this issue

### Firefly version

1.2.0

### OS details

win 10 or lubuntu  latest versions

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.  start adding  iota and adding wallets until the wallets start to do wierd things like double names  and leaving out some wallets. 
it might be triggerd by naming a wallet exactly the same as an existing one. just a guess.

### Expected behaviour

show all wallets , especially the' one with   some iota in it.

### Actual behaviour

leaves out the wallet with the iota vallue and wierd value graph.

**Comment by nicole-obrien** [comment]
Thank you for reporting this issue. Some questions that might help with troubleshooting:

- Do you have the checkbox with hidden wallets currently ticked in advanced settings?
- Is one or more of the wallets you created not being displayed under my wallets?
- Was one of these wallets named the same as a wallet showing up?
- Do you have any notable messages under error log in advanced settings?
- If you restore from a stronghold back up does the issue persist?
- Does the negative amount roughly equate to what you sent to a hidden wallet?

**Comment by bazakida** [comment]
Do you have the checkbox with hidden wallets currently ticked in advanced settings?
yes
Is one or more of the wallets you created not being displayed under my wallets?
yes

Was one of these wallets named the same as a wallet showing up?

i dont remember but it might be very possible since i use  "wallet 1" , "wallet 2" often as names.

Do you have any notable messages under error log in advanced settings?

"clienterror:{}"



If you restore from a stronghold back up does the issue persist?

yes, 

Does the negative amount roughly equate to what you sent to a hidden wallet?

yes

**Comment by bazakida** [comment]
i'm no rust dev but 
![image](https://user-images.githubusercontent.com/89320402/133851442-0705c50e-effb-4c83-b5a4-9eaf9962f4c7.png)
woudn't it be possible you won't get all acounts if you used same name?

**Comment by nicole-obrien** [comment]
Thanks for the information, we will take a look and try and replicate the issue first. Will keep you updated.

**Comment by bazakida** [comment]
thanks,  appreciate the fast response on a weekend

**Comment by bazakida** [comment]
added a wallet xxx and this happens 2 time same wallet is added
 both same addresses behind it.
![image](https://user-images.githubusercontent.com/89320402/133889001-c62770e5-2412-49fb-9774-371dfe32a5b5.png)

**Comment by bingodonky** [comment]
issue still there at  1.3.0 version

![image](https://user-images.githubusercontent.com/96496153/147014842-1b947355-f8bd-4880-aa09-60736a919c43.png)

**Comment by bingodonky** [comment]
![image](https://user-images.githubusercontent.com/96496153/151181586-fb6fec19-6ec5-492e-b41a-6543069f00f7.png)
tried in version 1.3.3

not fixed yet

**Comment by bingodonky** [comment]
tried version  1.4.1 beta  on mainnet.


![image](https://user-images.githubusercontent.com/96496153/161823489-20140918-d6fc-4d28-9ece-b02e90ac00a6.png)

![image](https://user-images.githubusercontent.com/96496153/161823568-52ebe498-49f3-4cc9-a929-3faaa134d1c8.png)

![image](https://user-images.githubusercontent.com/96496153/161823615-0d8750b8-de9e-4428-814a-5f507b2a6ebb.png)

the iota are there at : iota1qz4uvvrhv6n52vawl9kenm8wj43cqx5npjn3q79u3fa7lkjgguwku4hkjvg

https://thetangle.org/address/iota1qz4uvvrhv6n52vawl9kenm8wj43cqx5npjn3q79u3fa7lkjgguwku4hkjvg

but they don't show up in wallet. i did a few times "balance finder"


![image](https://user-images.githubusercontent.com/96496153/161823852-895af68f-6b5d-4f4b-8538-3c781008a288.png)

**Comment by bingodonky** [comment]
![image](https://user-images.githubusercontent.com/96496153/164073217-04e48662-54bd-4f9c-8fe8-0c4e5247dd7b.png)


this took some time :) but the issues is fixed  with 1.5.1 wallet .. i remember creating lots of wallets testing out a lot of internal transactions 

now that i see how balance finder works it was obvious i had to click it a lot of times..


another issues closed  :)

**Comment by jeeanribeiro** [comment]
> ![image](https://user-images.githubusercontent.com/96496153/164073217-04e48662-54bd-4f9c-8fe8-0c4e5247dd7b.png)
> 
> this took some time :) but the issues is fixed with 1.5.1 wallet .. i remember creating lots of wallets testing out a lot of internal transactions
> 
> now that i see how balance finder works it was obvious i had to click it a lot of times..
> 
> another issues closed :)

\o/
