### ISSUE TITLE
Migration from Trinity to FireFly with Seed < 81

### ISSUE THREAD

**Issue by Juliamd** [iotaledger/firefly#1478]
### Issue description

Hi everyone, 
I send and receive IOTA Tokens with seed < 81 with Trinity wallet light 2.5.7. Meanwhile, I tried to migrate into Firefly without success because Seed = 81 digit required. Are may Tokens in Trinity at risk?

### Firefly version

1

### OS details

Apple MacBook

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.dfdsf
2.dsfsdf
sfsdf3.
...

### Expected behaviour

ddsdfsd

### Actual behaviour

fdsfs

### Errors

dfsfds

**Comment by admljhnsn** [comment]
you need to add 9's until it = 81 characters

**Comment by Juliamd** [comment]
THX. It worked.

**Comment by maxwellmattryan** [comment]
Closing b/c issue was resolved (thanks @admljhnsn !)
