### ISSUE TITLE
problem bei der ledger migration

### ISSUE THREAD

**Issue by Cueneyit** [iotaledger/firefly#1515]
### Issue description

hallo

Als ich das erstemal die migrations Anleitung abgeschlossen hatte, erschien ein weißer Bild und es passierte nichts mehr und ich musste dann das Fenster von Firefly schließen.

Als ich erneut Firefly öffnete stellte ich fest das die migration meiner Token nicht abgeschlossen wurde und es wurde auch kein Konto angelegt.

diesen Prozess habe ich mehrfach wiederholt und es trat immer wieder das gleiche Problem auf.

Als ich heute es erneut versuchte öffnete sich eine Warnung im Fenster.

kurz beschrieben....    Du hast Guthaben auf wiederverwendeten adressen, aber die für die Absicherung erforderlichen informationen wurden nicht gefunden. Dies kann passieren, wenn Transaktionen vor langer Zeit durchgeführt wurden. Du kannst fortfahren, aber dei XXXXtoken sind während der migration gefährdet.

was soll ich machen?!

kann mir jemand helfen?

### Firefly version

1.2.0

### OS details

win 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.befolge die migrations Anleitung
2.nach der generation der Adressen wird eine Warnung ausgeprochen
3. verlust der token möglich
...

### Expected behaviour

ich erwarte das dieses problem gelöst wird.

ich will n icht meine token verlieren

### Actual behaviour

ich bin frustriert.

kein bock das es ständig probleme mit der migration meiner token gibt.

habe angst mein geld zu verlieren

### Errors

Wed, 29 Sep 2021 15:04:44 GMT
LedgerMiscError: ledger transport error

Wed, 01 Sep 2021 18:44:55 GMT
LegacyClientError: https://chronicle.iota.org/api: Connection Failed: invalid certificate: CertNotValidYet

Wed, 01 Sep 2021 18:44:12 GMT
LegacyClientError: https://chronicle.iota.org/api: Connection Failed: invalid certificate: CertNotValidYet

Wed, 01 Sep 2021 18:42:49 GMT
LegacyClientError: https://chronicle.iota.org/api: Connection Failed: invalid certificate: CertNotValidYet

Wed, 01 Sep 2021 18:41:10 GMT
LegacyClientError: https://chronicle.iota.org/api: Connection Failed: invalid certificate: CertNotValidYet

Wed, 01 Sep 2021 18:37:30 GMT
LegacyClientError: https://chronicle.iota.org/api: Connection Failed: invalid certificate: CertNotValidYet

Wed, 01 Sep 2021 18:36:29 GMT
LegacyClientError: https://chronicle.iota.org/api: Connection Failed: invalid certificate: CertNotValidYet

Wed, 01 Sep 2021 18:35:27 GMT
LegacyClientError: https://chronicle.iota.org/api: Connection Failed: invalid certificate: CertNotValidYet

Wed, 01 Sep 2021 18:34:31 GMT
LegacyClientError: https://chronicle.iota.org/api: Connection Failed: invalid certificate: CertNotValidYet

Wed, 01 Sep 2021 18:01:39 GMT
LedgerMiscError: ledger transport error

**Comment by r-c-k** [comment]
Melde dich ggf. mal im #german oder #help Channel auf [Discord](https://discord.iota.org), dort wird in der Regel schnell geholfen. Mit einer in Deutsch verfassen Fehlerbeschreibung werden die Entwickler der Wallet nicht viel Anfangen können.

**Comment by Goki8** [comment]
Hi ich habe ein Problem mit dem Status: Netzwerk nicht verbunden

**Comment by Mke91** [comment]
@Goki8 Wenn deine Funds nach der Migration mit ledger oder seed nicht auftauchen. Erstelle ein neues Profil und wähle die Option aus Restore or Migrate a wallet und dann die entsprechende Option. Dann sollten deine Funds erscheinen.
Bei weiteren Fragen melde dich im Discord https://discord.iota.org/

**Comment by MiKeF05** [comment]
@Cueneyit Hast du mittlerweile auf Discord Hilfe gefunden und hat die Migration geklappt?
