### ISSUE TITLE
stronghold file

### ISSUE THREAD

**Issue by rotcodnelg** [iotaledger/firefly#1516]
### Issue description

I backed up and in doing so a .stronghold file was created. How do I open it to retrieve the data?

### Firefly version

1.2.0

### OS details

10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

open file

### Actual behaviour

can't open file

**Comment by admljhnsn** [comment]
@rotcodnelg you create a new profile in firefly and choose the option to use a firefly backup

**Comment by maxwellmattryan** [comment]
Hey @rotcodnelg, I'm going to close this issue as this is more of a question asking for help on how to use Stronghold. As @admljhnsn mentioned, you create a new profile in Firefly and restore it from the `.stronghold` file you just made.
