### ISSUE TITLE
Inconsistency in refreshing transactions

### ISSUE THREAD

**Issue by gjeee** [iotaledger/firefly#1519]
### Issue description

In the main window it prompts to enter your password when clicking the refresh icon in "Latest transactions" panel.
In the account view it doesn't ask you.

From a user point of view this is a bit weird and does not make sense.

### Firefly version

v1.2.0

### OS details

Windows 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

...

### Expected behaviour

...

### Actual behaviour

...

**Comment by nicole-obrien** [comment]
Thank you, you are right. I will raise this issue to find out the correct version and add the fix to our backlog.
