### ISSUE TITLE
Preload Context Error

### ISSUE THREAD

**Issue by WvHDev** [iotaledger/firefly#1520]
### Issue description

After opening the firefly application on windows it automatically crashes and I get the following error message:

App Version: 1.2.0

platform: win32
platformVersion: 10.0.19042
platformArchitecture: x64
cpuCount: 12
totalMem: 16315.2 MB
freeMem: 10830.3 MB
userPath: C:\Users\an\AppData\Roaming\Firefly

Error Type: Preload Context Error

TypeError: Cannot read property 'isValid' of undefined
    at x.performValidation (C:\Users\an\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:541269)
    at C:\Users\an\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:547924
    at C:\Users\an\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:590377
    at Array.forEach (<anonymous>)
    at destroy (C:\Users\an\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:590365)
    at C:\Users\an\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:582435

I'm using the app now since the start and I never had any problems with it. I'm connecting through my ledger. Also I can't make a receiving address.

How can I fix this?

### Firefly version

1.2.0

### OS details

Windows 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Start firefly
2. Wait 30 seconds
3. Crash

### Expected behaviour

Working application

### Actual behaviour

The app is starting up and I can see my balance and earlier transactions. The CPU is going to 100% and after 30 seconds it crashes. I can click the error message away and everything works except for creating an address.

### Errors

App Version: 1.2.0

platform: win32
platformVersion: 10.0.19042
platformArchitecture: x64
cpuCount: 12
totalMem: 16315.2 MB
freeMem: 10830.3 MB
userPath: C:\Users\an\AppData\Roaming\Firefly

Error Type: Preload Context Error

TypeError: Cannot read property 'isValid' of undefined
    at x.performValidation (C:\Users\an\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:541269)
    at C:\Users\an\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:547924
    at C:\Users\an\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:590377
    at Array.forEach (<anonymous>)
    at destroy (C:\Users\an\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:590365)
    at C:\Users\an\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:582435

**Comment by Mke91** [comment]
try to delete the folder that you mentioned C:\Users\an\AppData\Roaming\Firefly and start firefly after that again.
make sure you have your seed or ledger available before deleting.

**Comment by WvHDev** [comment]
It's working now

Deleted the folder and restarted firefly


Thanks

> try to delete the folder that you mentioned C:\Users\an\AppData\Roaming\Firefly and start firefly after that again. make sure you have your seed or ledger available before deleting.
