### ISSUE TITLE
Error installing Firefly on Linux Mint

### ISSUE THREAD

**Issue by bokkearebest** [iotaledger/firefly#1593]
### Issue description

Hi,
I tried to install the firefly wallet on my linux mint desktop. Got the following error:

App Version: 1.2.0

platform: linux
platformVersion: 4.15.0-99-generic
platformArchitecture: x64
cpuCount: 4
totalMem: 15961.7 MB
freeMem: 10096.4 MB
userPath: /home/ant/.config/Firefly

Error Type: Preload Error

Error: Uncaught Error: node-loader:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /tmp/.org.chromium.Chromium.SI45e4)

Anyone know how to help?

Thanks
AntMan

### Firefly version

1.2.0

### OS details

Linux Mint

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Download the linux app from firefly.iota.org
2. Run it to install
3. Error occurs
...

### Expected behaviour

I expected to install the wallet and then set it up for use

### Actual behaviour

Error generated on install

### Errors

App Version: 1.2.0

platform: linux
platformVersion: 4.15.0-99-generic
platformArchitecture: x64
cpuCount: 4
totalMem: 15961.7 MB
freeMem: 10096.4 MB
userPath: /home/ant/.config/Firefly

Error Type: Preload Error

Error: Uncaught Error: node-loader:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /tmp/.org.chromium.Chromium.SI45e4)

**Comment by MiKeF05** [comment]
Hello,

like the error says libstdc++.so.6 was not found. Try to install it.

**Comment by nicole-obrien** [comment]
Hi, is this issue resolved?

**Comment by bokkearebest** [comment]
Yes, thanks. Upgraded my desktop to the latest distro and then the wallet installed ok.Thanks Anton On 15/10/2021 3:26 am, nicole-obrien ***@***.***> wrote:
Hi, is this issue resolved?
