### ISSUE TITLE
[Task]: Use respective script for languages in profile settings

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#1598]
### Issue description

It would be easier to read for native speakers if the languages in the profile settings dropdown were written in their corresponding scripts. 

### Firefly version

1.2.0

### OS details

MacOS (Catalina 10.15.7)

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Navigate to settings page
2. Navigate to general settings
3. Click dropdown for language

### Expected behaviour

Should display each language in its respective writing system / script.

### Actual behaviour

Each language is represented with Roman letters.

### Errors

N/a

**Comment by Chaitanya12123** [comment]
I'd like to work on this
