### ISSUE TITLE
Accounts are not fully deleted

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#1607]
### Issue description
Firefly isn't fully deleting accounts when a tries to do so; only the app-side data is being removed.

In the [code](https://github.com/iotaledger/firefly/blob/561f847abdc013435ce6469c6ea0c1bb4b13a5d7/packages/shared/components/modals/AccountActions.svelte#L61), there's no call for removing the accounts being made.

### Firefly version
1.2.0 and `develop`

### OS details
MacOS (Catalina 10.15.7)

### Can the issue be reliably reproduced?
Yes

### Steps to reproduce the issue
1. Create a new account within a profile
2. Delete the newly created account
3. Try to create another new account with the same name / alias

You should see an error for an already existing alias even though it was removed just before.

### Expected behaviour
Users should be able to delete and create accounts without any bugs.

### Actual behaviour
Users cannot delete and create accounts freely as the bug of not deleting the account `wallet.rs`-side introduces unwanted behavior.

**Comment by nicole-obrien** [comment]
Fixed in https://github.com/iotaledger/firefly/pull/1209
