### ISSUE TITLE
Infinite spinner on cancelling Stronghold password while creating an account

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#1608]
### Issue description

While creating an account (for software profiles), if you "Cancel" the Stronghold popup asking for your password, Firefly will be slightly stuck with the infinite spinner.

### Firefly version

1.2.0 and `developer`

### OS details

MacOS (Catalina 10.15.7)

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Create an account within a software profile with Stronghold locked
2. Click "Cancel" instead of entering your password 

You should see the spinner still spinning towards the bottom left of the screen.

### Expected behaviour

The state should resume normally if the user cancels the Stronghold password.

### Actual behaviour

Firefly gets stuck, infinitely spinning for that button.

**Comment by nicole-obrien** [comment]
Fixed in: https://github.com/iotaledger/firefly/pull/1209
