### ISSUE TITLE
Wallet takes long to load and will not input numbers properly

### ISSUE THREAD

**Issue by hoangkara** [iotaledger/firefly#1611]
### Issue description

The wallet takes longer to load as in there is a 30 sec delay before it loads up.  Then when I try to input my pin, I can only input one number.  then I have to click each time, but I am denied access because it indicates I have the wrong pin.

### Firefly version

1.2.0

### OS details

Windows 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.Opening the wallet
2. Trying to input pin to login
3.
...

### Expected behaviour

Loads immediately and should allow login with the correct pin.  Should allow user to input pin number

### Actual behaviour

The wallet has a white screen for about 30 seconds before loading up.  Once the wallet loads up, I choose my account.  However, when I input my pin, I can only input the first number.  After that I cannot input any other numbers with my keyboard unless I click the next space.  After inputting the entire pin the wallet still does not grant access indicating the pin is wrong.

### Errors

Sun, 26 Sep 2021 21:28:03 GMT
ClientError: {}

Sun, 26 Sep 2021 21:17:02 GMT
ClientError: {}

Sat, 25 Sep 2021 19:10:56 GMT
StrongholdError: `failed to perform action: `Snapshot Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sat, 25 Sep 2021 19:10:50 GMT
StrongholdError: `failed to perform action: `Snapshot Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sat, 25 Sep 2021 19:10:37 GMT
StrongholdError: `failed to perform action: `Snapshot Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sat, 25 Sep 2021 19:10:25 GMT
StrongholdError: `failed to perform action: `Snapshot Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sat, 25 Sep 2021 17:47:17 GMT
ClientError: {}

Sat, 25 Sep 2021 17:38:36 GMT
ClientError: {}

Thu, 29 Apr 2021 22:50:11 GMT
ClientError: {}

Sat, 24 Apr 2021 19:01:52 GMT
ClientError: {}

Sat, 24 Apr 2021 18:56:43 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/addresses/iota1qzvd84r6ew6jn3yf07s885fdfxkaagph5cxxvy0we000cx60cdm3xkv2ql6/outputs?include-spent=true): error trying to connect: dns error: No such host is known. (os error 11001)`

Sat, 24 Apr 2021 15:18:38 GMT
ClientError: {}

Sat, 24 Apr 2021 15:13:28 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/addresses/iota1qzvd84r6ew6jn3yf07s885fdfxkaagph5cxxvy0we000cx60cdm3xkv2ql6/outputs?include-spent=true): error trying to connect: dns error: No such host is known. (os error 11001)`

Sat, 24 Apr 2021 15:08:06 GMT
ClientError: {}

Sat, 24 Apr 2021 15:02:55 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/addresses/iota1qzvd84r6ew6jn3yf07s885fdfxkaagph5cxxvy0we000cx60cdm3xkv2ql6/outputs?include-spent=true): error trying to connect: dns error: No such host is known. (os error 11001)`

Sat, 24 Apr 2021 14:54:15 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/addresses/iota1qzvd84r6ew6jn3yf07s885fdfxkaagph5cxxvy0we000cx60cdm3xkv2ql6/outputs?include-spent=true): error trying to connect: dns error: No such host is known. (os error 11001)`

Sat, 24 Apr 2021 14:54:10 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/addresses/iota1qzvd84r6ew6jn3yf07s885fdfxkaagph5cxxvy0we000cx60cdm3xkv2ql6/outputs?include-spent=true): error trying to connect: dns error: No such host is known. (os error 11001)`

Sat, 24 Apr 2021 14:53:57 GMT
StrongholdError: `failed to perform action: `Snapshot Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sat, 24 Apr 2021 14:53:26 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/addresses/iota1qzvd84r6ew6jn3yf07s885fdfxkaagph5cxxvy0we000cx60cdm3xkv2ql6/outputs?include-spent=true): error trying to connect: dns error: No such host is known. (os error 11001)`

Sat, 24 Apr 2021 14:46:40 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/addresses/iota1qzvd84r6ew6jn3yf07s885fdfxkaagph5cxxvy0we000cx60cdm3xkv2ql6/outputs?include-spent=true): error trying to connect: dns error: No such host is known. (os error 11001)`

Sat, 24 Apr 2021 14:46:39 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/addresses/iota1qzvd84r6ew6jn3yf07s885fdfxkaagph5cxxvy0we000cx60cdm3xkv2ql6/outputs?include-spent=true): error trying to connect: dns error: No such host is known. (os error 11001)`

Sat, 24 Apr 2021 14:46:36 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/addresses/iota1qzvd84r6ew6jn3yf07s885fdfxkaagph5cxxvy0we000cx60cdm3xkv2ql6/outputs?include-spent=true): error trying to connect: dns error: No such host is known. (os error 11001)`

Sat, 24 Apr 2021 14:44:16 GMT
StrongholdError: `failed to perform action: `Snapshot Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sat, 24 Apr 2021 14:44:08 GMT
StrongholdError: `failed to perform action: `Snapshot Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sat, 24 Apr 2021 14:43:56 GMT
StrongholdError: `failed to perform action: `Snapshot Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sat, 24 Apr 2021 14:43:41 GMT
StrongholdError: `failed to perform action: `Snapshot Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sat, 24 Apr 2021 14:42:02 GMT
StrongholdError: `failed to perform action: `Snapshot Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sat, 24 Apr 2021 14:41:55 GMT
StrongholdError: `failed to perform action: `Snapshot Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sat, 24 Apr 2021 14:41:27 GMT
StrongholdError: `failed to perform action: `Snapshot Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sat, 24 Apr 2021 14:41:16 GMT
StrongholdError: `failed to perform action: `Snapshot Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sat, 24 Apr 2021 14:40:45 GMT
StrongholdError: `failed to perform action: `Snapshot Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sat, 24 Apr 2021 14:40:41 GMT
StrongholdError: `failed to perform action: `Snapshot Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sat, 24 Apr 2021 14:40:28 GMT
StrongholdError: `failed to perform action: `Snapshot Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sat, 24 Apr 2021 14:39:46 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/addresses/iota1qzvd84r6ew6jn3yf07s885fdfxkaagph5cxxvy0we000cx60cdm3xkv2ql6/outputs?include-spent=true): error trying to connect: dns error: No such host is known. (os error 11001)`

Sat, 24 Apr 2021 14:37:03 GMT
ClientError: {}

Sat, 24 Apr 2021 14:29:09 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/addresses/iota1qzvd84r6ew6jn3yf07s885fdfxkaagph5cxxvy0we000cx60cdm3xkv2ql6/outputs?include-spent=true): error trying to connect: dns error: No such host is known. (os error 11001)`

**Comment by rajivshah3** [comment]
Hi, has this always happened or did this only start when you opened the issue? I saw that you posted error messages from April

**Comment by hoangkara** [comment]
This issue has resolved, I apologize, I didn't realize I forgot to close the case.  I believe it may have been because I was not using the English keyboard.
