### ISSUE TITLE
Tôi không nhận được tiền khi chuyển vào ví mới. HELP ME !!!

### ISSUE THREAD

**Issue by manhtuanads** [iotaledger/firefly#1617]
### Issue description

Tôi chuyển tiền từ ví cũ vào ví mới, và có thông báo như sau: (tiền của bạn có sẵn trong thời gian ngắn). Và chưa về được ví mới. Trạng thái kết nối của ví báo(Network disconnected). thank

### Firefly version

Firefly phiên bản 1.2.0

### OS details

WINDOWS 7- 64 BIT

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

HELP ME !!!

### Actual behaviour

![z2888026438405_ecc82d684cd8ab783c9cd1cf5eb39aa1](https://user-images.githubusercontent.com/48626558/139417358-0450472a-0cb4-425f-83aa-800951856394.jpg)

### Errors

![z2888026438405_ecc82d684cd8ab783c9cd1cf5eb39aa1](https://user-images.githubusercontent.com/48626558/139417092-cbdecaae-9403-4601-8eb1-657d6802054f.jpg)

**Comment by MiKeF05** [comment]
Hello,

could you try the following. Create a new profile in Firefly and choose restore profile. Enter your 24 words OR your use the stronghold backup file to restore your profile. If your funds are available you can then delete the old profile.

**Comment by manhtuanads** [comment]
vâng xin cảm ơn đẵ trợ giúp, tôi làm thử xem có được không

**Comment by manhtuanads** [comment]
tôi đã làm như bạn hướng dẫn nhưng khi tạo ví thì lại không có tiền trong đó. Điều chắc chắn là tôi đã nhập đúng cụm từ khôi phục ví. Khi mở ra thì không có một đồng tiền nào trong ví. Ví tôi backup chước đó thì còn nhìn thấy tiền bên trong nhưng có thông báo như sau: (tiền của bạn có sẵn trong thời gian ngắn).  Xin nhận được sự trợ giúp sớm nhất từ các bạn. cảm ơn!!!

**Comment by manhtuanads** [comment]
![image](https://user-images.githubusercontent.com/48626558/139521930-06873fff-4fe2-4553-8271-3e79f5c57fa2.png)
đây là ví tôi lập lần 1

**Comment by manhtuanads** [comment]
![image](https://user-images.githubusercontent.com/48626558/139521946-c3d89781-230b-4679-92e4-e06573eeaf48.png)

đây là ví tôi lập lần (2), cụm từ khôi phục ví như nhau

**Comment by manhtuanads** [comment]
xin được trợ giúp sớm

**Comment by MiKeF05** [comment]
Is there something in the error log? Click on the upper left symbol and then Firefly -> error log to get there. If yes can you paste it here?

**Comment by MiKeF05** [comment]
@manhtuanads Have you solved your issue?

**Comment by Tuditi** [comment]
I'm closing this down, since the issue is outdated. If it is still present in the current Firefly version (1.6.5), please reopen it!
