### ISSUE TITLE
Cannot send Miota

### ISSUE THREAD

**Issue by eisteeatze** [iotaledger/firefly#1620]
### Issue description

When sending MIOTA Coins, I get an error message after entering the password.

### Firefly version

1.2.0

### OS details

Windows

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.Send credit
2.enter address
3.confirm
4. enter password

### Expected behaviour

error message

### Actual behaviour

error message

### Errors

Error log:
Mo, 01 Nov 2021 15:02:19 GMT
LeavingDustError: Fehler beim Verlassen des Staubs: Transaktion würde Staub hinterlassen (662468i)

**Comment by MiKeF05** [comment]
The problem here is that you can't have less then 1Mi on an address. So I think when you send it all then it should be good.

**Comment by nicole-obrien** [comment]
Hi @eisteeatze, was this an issue with sending less than or leaving less than 1Mi on an address?
