### ISSUE TITLE
One Computer Shows Correct Amount, the Other Says Zero Balance

### ISSUE THREAD

**Issue by B1GT3X45** [iotaledger/firefly#1621]
### Issue description

Recently bought a new WIndows Surface Pro 8 (WIndows 11), and I wanted to have my Firefly wallet on my new device. I was able to access my wallet via .kdbx file and password. The balance says 0 and I keep clicking "Check Again" to no avail.

The old laptop shows everything perfectly, new device shows 0 balance.

Firefly v1.2.0
Language: en
Currency: USD
Node settings: Automatic node selection
Platform: win32
Platform Version: 10.0.22000
Platform Architecture: x64
CPU Count: 8
Total Memory: 16218.0 MB
Free Memory: 9422.7 MB
User Path: C:\Users\bentr\AppData\Roaming\Firefly

### Firefly version

1.2.0

### OS details

Windows 11

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1. Have current/old device open with Firefly showing correct balance
2. Download Firefly on new device (Windows 11)
3. Run a back up via .kdbx
4. Balance shows zero, with old device showing current amount side by side
...

### Expected behaviour

Both wallets open showing the same information/amounts.

### Actual behaviour

One computer shows current amount, the other shows zero.

### Errors

"Try checking again. If you still can't find your balance you might have entered your seed incorrectly."

**Comment by MiKeF05** [comment]
Hello,

if you have already migrated your tokens to the new network you cannot migrate again with the .kdbx file. This file was only available for the Trinity wallet. Since you have migrated your token to the new network you can only restore your wallet on the new computer with a stronghold file + password OR with the 24 words you got when you set up the profile in Firefly.

**Comment by B1GT3X45** [comment]
Used the stronghold file and it worked, thank you!
