### ISSUE TITLE
Iota missing from one address

### ISSUE THREAD

**Issue by sporat** [iotaledger/firefly#1623]
Hi,

I am using the current version (1.2.0) of IOTA Firefly.
I migrated my tokens on 18th of May 2021. I didn't look into Firefly since then. But when I checked directly after the migration, all of my tokens were there.

Right now, on transaction of one specifiy address is missing.
Are there any options to get the miota back

Thanks for your help,
Sebastian

**Comment by MiKeF05** [comment]
Hello,
what do you mean with one transaction is missing? The migrated balance was correct?

**Comment by Tuditi** [comment]
I'm closing this down, since the balance finder has been updated. Please reopen if the issue still persists.
