### ISSUE TITLE
moving token from trinity wallet to firefly wallet.

### ISSUE THREAD

**Issue by Thaitran1234** [iotaledger/firefly#1626]
### Issue description

Need help in moving token from trinity wallet to firefly wallet.

### Firefly version

kkk

### OS details

lll

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.
2.
3.
...
N/A.

### Expected behaviour

N/A.

### Actual behaviour

N/A.

### Errors

N/A

**Comment by MiKeF05** [comment]
Hello, 

it would be great to visit the IOTA Discord server to get help for the migration. There is a help channel you can visit. Could you then please close this issue as it is no bug in Firefly?
