### ISSUE TITLE
Firefly nur weißer Bildschirm

### ISSUE THREAD

**Issue by xscheckix** [iotaledger/firefly#1633]
### Issue description

Hallo zusammen, 

ich habe die Firefly wallet Installiert, leider kommt immer nur der weiße Bildschirm beim starten und mehr passiert nicht. 

Firefly Wallet: 1.2.0 
Mac OS Catalina Macbook Pro 2010 

habe schon den Ordner
username/Library/Application Support/Firefly 
gelöscht danach neu installiert und gestartet, aber Firefly startet zwar aber der Bildschirm ist nur weiß. 

Die Spache kann ich net ändern, oder was anderes auswählen in dem Reiter der Wallet. 

Hat jemand das gleiche Problem?! 

wäre super wenn mir da jemand hilft! 

Grüße Micha

### Firefly version

1.2.0

### OS details

Mac OS Catalina Macbook Pro 2010 

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.Deinstaliert und neu Installiert aber das hat nichts gebracht
...

### Expected behaviour

![Bildschirmfoto 2021-11-16 um 21 33 30](https://user-images.githubusercontent.com/94522376/142225310-c4f5c2a8-fb7a-43a9-be25-1ee2640aa131.png)
der Bildschirm bleibt nur weiß, mehr passiert nicht

### Actual behaviour

Bildschirm weiß^^

**Comment by Narrenkappe** [comment]
Gab es eine Lösung für dieses Problem?
