### ISSUE TITLE
Coins suddenly dissapeared 

### ISSUE THREAD

**Issue by Marco2388** [iotaledger/firefly#1634]
Hi,
I opened my Wallet today and it showed 0 Balance, no transactions are shown, just the migration from may this year. I made other transactions in the meantime and last week the wallet worked normal. Now it shows no transactions in history and all my coins are not showing or gone. When i check the adress in explorer it whows me 0 Balance an no transactions too.
What happened here and what can i do?

Thanks in advance
Marco

**Comment by MiKeF05** [comment]
Hello,

which version of Firefly do you use? Anything in the error log?

**Comment by Marco2388** [comment]
> 
> 
> Hello,
> 
> which version of Firefly do you use? Anything in the error log?

Hi Mike, i use the latest version 1.2.0
error log shows this : 
Thu, 18 Nov 2021 09:51:34 GMT
ClientError: {}

Thu, 18 Nov 2021 09:17:32 GMT
ClientError: {}

Thu, 18 Nov 2021 09:11:22 GMT
ClientError: {}

Thu, 18 Nov 2021 09:03:03 GMT
ClientError: {}

**Comment by MiKeF05** [comment]
Can you try the following. Create a new profile in Firefly and restore your profile either with your 24 words or your stronghold file. If you use a ledger then restore the profile with your ledger.

**Comment by Marco2388** [comment]
> 
> 
> Can you try the following. Create a new profile in Firefly and restore your profile either with your 24 words or your stronghold file. If you use a ledger then restore the profile with your ledger.

i already did that, even on a different laptop and one time with stronghold file and one time with rec phrase. but it shows 0 balance and no transactions unfortunately

**Comment by MiKeF05** [comment]
Can you go to the official iota Discord server and to the help channel. There you will get support.
