### ISSUE TITLE
Trust Wallet can't connect to Firefly Wallet

### ISSUE THREAD

**Issue by Neverlast777** [iotaledger/firefly#1637]
Dears,
Please advice - scanning the code in Firefly to receive MIOTA from my Trust Wallet but no way to connect - it opens Firefox browser with some arabic letters.....
Or if I scan the Firefly address to receive MIOTA - message pops up in Trust Wallet "Invalid Address"....

**Comment by Neverlast777** [comment]
Or if I scan the Firefly address - message pop up in Trust Wallet "Invalid Address"....

**Comment by svenger87** [comment]
Your Trust Wallet handles your BSC wrapped IOTA´s right?
You can´t send wrapped IOTA to Firefly.

Move your wrapped IOTA´s to Binance and Exchange them to the "real deal" and transfer those to your Firefly wallet.

**Comment by nicole-obrien** [comment]
@Neverlast777 svenger is right, Firefly only supports the IOTA token sent over the IOTA network. Please join our discord if you continue having issues.

**Comment by Neverlast777** [comment]
Check the screenshot below - it's not wrapped:

**Comment by nicole-obrien** [comment]
I can't see any screenshot, but IOTA is not included in https://trustwallet.com/assets, and Firefly is the only wallet that I know that currently supports native IOTA tokens.

**Comment by Neverlast777** [comment]
So - your advice is to move iota to Binance and to connect Firefly from it?
Attached is the screenshot again - you should see as attached file.

**Comment by Neverlast777** [comment]
![Screenshot_20211119_191919_com wallet crypto trustapp](https://user-images.githubusercontent.com/94674778/142661830-77c783c4-3070-4d2d-9262-2a8ab1d4c337.jpg)

**Comment by nicole-obrien** [comment]
Yeah, BEP20 is the token standard for Binance Smart Chain. Essentially they hold your IOTA and let you withdraw either wrapped IOTA a BEP20 token via BSC or you can withdraw the native IOTA token via the IOTA network to an IOTA address. Bare in mind Binance like to pause their withdrawals via IOTA network from time to time.

Download official firefly application from here: https://firefly.iota.org/ and create a profile, then generate an address, once pasted into binance, they will only let you withdraw via IOTA network using this address.

**Comment by Neverlast777** [comment]
> Yeah, BEP20 is the token standard for Binance Smart Chain. Essentially they hold your IOTA and let you withdraw either wrapped IOTA a BEP20 token via BSC or you can withdraw the native IOTA token via the IOTA network to an IOTA address. Bare in mind Binance like to pause their withdrawals via IOTA network from time to time.
> 
> Download official firefly application from here: https://firefly.iota.org/ and create a profile, then generate an address, once pasted into binance, they will only let you withdraw via IOTA network using this address.

Thanks for the reply!
I will do it later - the transfer to binance but the question still stays why Trust Wallet can't connect to Firefly... I used the official firefly link - exactly like the one you sent.... Hope there will be no surprises with binance...

**Comment by Neverlast777** [comment]
Everything worked well with binance!
So - what's next now - just wait for the announcement of staking?

**Comment by MiKeF05** [comment]
Yes just wait for the announcement of staking. I guess this issue can be closed

**Comment by Neverlast777** [comment]
Yes. Close it. Thanks again!!!

**Comment by nicole-obrien** [comment]
Thanks for the update, yeah as long as you can see the tokens in firefly, when staking is released you will be able to do so through firefly.
