### ISSUE TITLE
Estado de red degradada

### ISSUE THREAD

**Issue by Patxiii** [iotaledger/firefly#1639]
### Issue description

Al entrar a mi perfil en FireFly el estado de la Red pone degradada (color naranja). Esta en modo automatico el nodo. he cambiado en manual al segundo y tampoco se soluciona.

### Firefly version

Firefly v1.2.0 

### OS details

Windows 8.1

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

Firefly v1.2.0
Idioma: es-ES
Divisa: EUR
Ajustes del nodo: Selección automática de nodo
Plataforma: win32
Versión de la plataforma: 6.3.9600
Arquitectura de la plataforma: x64
Número de CPU: 4
Memoria Total: 2018.4 MB
Memoria Libre: 492.0 MB
Ruta de Usuario: C:\Users\txurtys\AppData\Roaming\Firefly

### Expected behaviour

.

### Actual behaviour

.

### Errors

Sat, 20 Nov 2021 14:45:06 GMT
ClientError: {}

**Comment by MiKeF05** [comment]
Hello,

so your network status is disconnected? One question that could be related to this is have you changed your PIN before this issue?

A quick workaround would be to create a new profile and restore your wallet with your 24 words or your stronghold backup file. If you use a ledger that you can restore it with your ledger.

**Comment by MiKeF05** [comment]
@Patxiii Were you able to resolve your issue?
