### ISSUE TITLE
Impossible to set PIN while creating wallet

### ISSUE THREAD

**Issue by 666RandomGuy** [iotaledger/firefly#1640]
### Issue description

Impossible to set PIN while creating SOFTWARE wallet. After clicking confirm pin nothing happens.

### Firefly version

1.2.0

### OS details

Ubuntu 20.04.3 LTS

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Run appimage
2. Create SOFTWARE wallet, set name, password and pin
3. Confirm pin and nothing happens

### Expected behaviour

After confirming PIN number, there should be next window or something....

### Actual behaviour

After confirming PIN number nothing happens

**Comment by MiKeF05** [comment]
Hello, please make sure to install gnome-keyring.

**Comment by 666RandomGuy** [comment]
It works now, thanks.

**Comment by MiKeF05** [comment]
I guess the issue can now be closed
