### ISSUE TITLE
Setting up a software wallet the PIN confirmation blocks the process

### ISSUE THREAD

**Issue by javidnia** [iotaledger/firefly#1641]
### Issue description

Setting up my first software wallet, the PIN confirmation screen does not proceed to the next step. No error is shown and the error log is empty.

### Firefly version

1.2.0

### OS details

Kubuntu release 20.04.3

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.Run the Linux Installer
2.Choose Create Software Wallet
3.Create a password
4.Setup a PIN code
5.Reenter the PIN code
...

### Expected behaviour

After confirming the PIN code the next page shall be shown

### Actual behaviour

After confirming the PIN code nothing happens

**Comment by MiKeF05** [comment]
Hello make sure to install gnome-keyring

**Comment by MiKeF05** [comment]
@javidnia Could you resolve your issue with installing gnome-keyring?

**Comment by javidnia** [comment]
Yes. Thank you for your support
