### ISSUE TITLE
blank sceen

### ISSUE THREAD

**Issue by 7Oxiq** [iotaledger/firefly#1643]
### Issue description

Hello,
After installing Firefly, I have a blank screen and no interaction just the version window showing. What can I do please? I am running Ubuntu.

### Firefly version

1.2.0

### OS details

UBUNTU 20.04 LTS / AMD PALM (DRM 2.50.0 / 5.4.0-90-generic, LLVM 12.0.0) / 64 bits

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

Simple start of the application with right click then launch on the appi image file 

### Expected behaviour

I should not have a white screen

### Actual behaviour

I have a white sceen

**Comment by StefanoD** [comment]
I'm not a maintainer, but on my issue I have been asked to attach the output of `chrome://gpu/` in Chrome, if you have it installed.

**Comment by rajivshah3** [comment]
Yep, please try attaching a screenshot from `chrome://gpu` if you can

**Comment by rajivshah3** [comment]
Hi @7Oxiq , can you please attach a screenshot from `chrome://gpu`?

**Comment by Tuditi** [comment]
Closed due to duplicate issue (https://github.com/iotaledger/firefly/issues/1643).

**Comment by StefanoD** [comment]
> Closed due to duplicate issue (#1643).

What duplicated issue? You are referring with the link to this actual ticket.
