### ISSUE TITLE
No actualiza la billetera error

### ISSUE THREAD

**Issue by psanrui** [iotaledger/firefly#1645]
### Issue description

Realice la transacción desde binance mediante código QR y no ha llegado la transacción.
Debido a otro error tuve que hacer un nuevo perfil y recuperar con las 24 palabras pero sigue sin aparecer la transacción
![Capturafirefly](https://user-images.githubusercontent.com/94890514/142981785-049118d8-c4f9-481b-b4e7-35c23cb46d3e.PNG)

### Firefly version

versión 1.2.0

### OS details

windows 10 v 2009

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.  a la espera
2.
3.
...

### Expected behaviour

recibir mi transacción completa

### Actual behaviour

a la espera

### Errors

App Version: 1.2.0

platform: win32
platformVersion: 10.0.19042
platformArchitecture: x64
cpuCount: 6
totalMem: 16163.3 MB
freeMem: 8297.8 MB
userPath: C:\Users\psanrui\AppData\Roaming\Firefly

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_ABORTED

**Comment by MiKeF05** [comment]
You can check the address with the explorer (https://explorer.iota.org/mainnet). If the balance is not on the address yet then you should contact Binance.

**Comment by MiKeF05** [comment]
@psanrui Were you able to solve your issue?

**Comment by MiKeF05** [comment]
This should be fixed in the latest release.

**Comment by bodom066** [comment]
HOW CAN I GET OUT MY IOTAS FROM FIREFLY TO METAMASK? IT WRITES ME DOWN THAT THE THE ADRESS MUST START WITH THE WORLD IOTA ¿?¿

**Comment by begonaalvarezd** [comment]
> HOW CAN I GET OUT MY IOTAS FROM FIREFLY TO METAMASK? IT WRITES ME DOWN THAT THE THE ADRESS MUST START WITH THE WORLD IOTA ¿?¿

There is no EVM yet in IOTA so at the moment there is no way from firefly to send tokens from layer 1 to evm (eg metamask). All transactions in firefly iota at the moment are layer 1 only, so the only allowed addresses indeed must start with the `iota` prefix

**Comment by bodom066** [comment]
So I will have my iotas blocked for years and I can not trade with them during this time?
________________________________
De: Begoña Álvarez de la Cruz ***@***.***>
Enviado: domingo, 10 de diciembre de 2023 16:42
Para: iotaledger/firefly ***@***.***>
Cc: bodom066 ***@***.***>; Comment ***@***.***>
Asunto: Re: [iotaledger/firefly] No actualiza la billetera error (Issue #1645)


HOW CAN I GET OUT MY IOTAS FROM FIREFLY TO METAMASK? IT WRITES ME DOWN THAT THE THE ADRESS MUST START WITH THE WORLD IOTA ¿?¿

There is no EVM yet in IOTA so at the moment there is no way from firefly to send tokens from layer 1 to evm (eg metamask). All transactions in firefly iota at the moment are layer 1 only, so the only allowed addresses indeed must start with the iota prefix

**Comment by bodom066** [comment]
So may you tell me some bridge or way to trade my Iotas please? I need it for personal reasons ...
________________________________
De: Begoña Álvarez de la Cruz ***@***.***>
Enviado: lunes, 11 de diciembre de 2023 10:29
Para: iotaledger/firefly ***@***.***>
Cc: bodom066 ***@***.***>; Comment ***@***.***>
Asunto: Re: [iotaledger/firefly] No actualiza la billetera error (Issue #1645)


So I will have my iotas blocked for years and I can not trade with them during this time?

Not having an EVM is not what this means, your funds are not blocked and you can trade using other options, they are just not provided my the protocol but you need to use a third party service like a bridge or an exchange

**Comment by begonaalvarezd** [comment]
Github is not the place for this conversation, this is a technical platform to report bugs to the developers. You can join the official discord https://discord.iota.org/
