### ISSUE TITLE
Transfer wird nicht vollendet.

### ISSUE THREAD

**Issue by Ralli-S** [iotaledger/firefly#1649]
Guten Tag,
wollte meine Miota auf Fire Fly 1.2.0 von einer Börse transferieren. Jetzt hängt der Auftrag seit 2 Tagen im Status Bearbeitung.
In meiner Wallett tut sich aber nichts, auch bekomme ich keine Fehlermeldung.
Was kann ich tun?
MfG Ralf

**Comment by MiKeF05** [comment]
Hallo, 

in diesem Fall denke ich ist es besser direkt den Support der Börse zu kontaktieren. 

Im Explorer (https://explorer.iota.org/mainnet) kannst du deine Adresse prüfen. Sollte noch keine Balance vorhanden sein, hat die Börse die Auszahlung noch nicht durchgeführt.

**Comment by MiKeF05** [comment]
Das liegt leider an der Exchange. Ohne Bestätigung kann die Transaktion auch nicht durchgeführt werden.
