### ISSUE TITLE
 Funds have not been received to the Firefly wallet

### ISSUE THREAD

**Issue by Soulparaxis** [iotaledger/firefly#1650]
### Issue description

I made an iota transfer from a Binance wallet almost a day ago. Funds have not been received to the Firefly wallet

### Firefly version

1.2.0

### OS details

Windows 7

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

Cancellation of a transaction or transfer of funds to a wallet

### Expected behaviour

Cancellation of a transaction or transfer of funds to a wallet

### Actual behaviour

Cancellation of a transaction or transfer of funds to a wallet

### Errors

1

**Comment by MiKeF05** [comment]
Hello, 
I think it is no issue with the Firefly wallet. You should contact the Binance support to get this done. You can check your address with the explorer (https://explorer.iota.org/mainnet). When the balance is not on the address then the exchange hasn´t done the transfer yet.

**Comment by eBinder2** [comment]
> Hello, I think it is no issue with the Firefly wallet. You should contact the Binance support to get this done. You can check your address with the explorer (https://explorer.iota.org/mainnet). When the balance is not on the address then the exchange hasn´t done the transfer yet.

I dont think so, i hve the same problem even the exchnge did it, and even restoring my wallet with the seed phrase. The only thing that coulb be interfering is the firewall, because the wallet is always disconnected, not sure...let's check it..

**Comment by MiKeF05** [comment]
@Soulparaxis Have you received the tokens from Binance in your Firefly wallet? If not what's the status of the network? Is your wallet connected to the network?

**Comment by shudai79** [comment]
I have the same issue. The network is disconnected and I get the following error message: errornodechrysalisNodeInactive

**Comment by MiKeF05** [comment]
@Soulparaxis Have you received your tokens?

**Comment by eBinder2** [comment]
Yes i did, thank you so much for your follow-up!

**Comment by demian78** [comment]
Same with me!!! I sent from bitpanda on 12/22/21 and I didn't receive anything in my wallet?!
See picture below for details:
![Iota-Zahlung](https://user-images.githubusercontent.com/96737717/147488218-3f62930d-57fd-4f01-92d2-888deadc8ca4.jpg)

**Comment by MiKeF05** [comment]
Your address starts with atoi... This is an address for the testnet. You have created a developer profile which is connected to the testnet. You need to create a new profile and restore your profile without checking the developer profile.
