### ISSUE TITLE
Balance 0, no wallet

### ISSUE THREAD

**Issue by onetime91** [iotaledger/firefly#1651]
### Issue description

The balance is 0 and there is no wallets.
There isn't also connection.
Thanks for the help.

### Firefly version

firefly 1.2.0

### OS details

windows 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Open the wallet
2. Create new wallet
3. Error of firefly
...

### Expected behaviour

I think it's gonna work good like before.

### Actual behaviour

I have problems with firefly, it's the second time i have problems with balance

### Errors

App Version: 1.2.0

platform: win32
platformVersion: 10.0.22000
platformArchitecture: x64
cpuCount: 8
totalMem: 7987.2 MB
freeMem: 2666.3 MB
userPath: C:\Users\Utente\AppData\Roaming\Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'signerType' of undefined
    at C:\Users\Utente\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:548089
    at C:\Users\Utente\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:590377
    at Array.forEach (<anonymous>)
    at destroy (C:\Users\Utente\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:590365)
    at C:\Users\Utente\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:582435

**Comment by MiKeF05** [comment]
Hello,

have you updated Firefly to v1.2 before? Maybe try the following. Create a new profile and restore your wallet with either your stronghold backup file or your 24 words.

**Comment by eBinder2** [comment]
> Hello,
> 
> have you updated Firefly to v1.2 before? Maybe try the following. Create a new profile and restore your wallet with either your stronghold backup file or your 24 words.

Doesn't work, same problem with no result after restoring + seed phrase, etc,..

**Comment by MiKeF05** [comment]
Then you can do the following. Uninstall Firefly and delete the folder Firefly in C:\Users\Utente\AppData\Roaming. After that you can install Firefly and restore your profile again.

**Comment by onetime91** [comment]
Now it's ok.
I created a new profil and then imported with the 24 words.
Now the balance is correct.
thank you very much
