### ISSUE TITLE
Firefly frizzes when creating a wallet for the first time 

### ISSUE THREAD

**Issue by Riddle1988** [iotaledger/firefly#1653]
### Issue description

Firefly frizzes when creating a wallet for the first time after you go back to the previous step

Issue was reproduced on two different Windows 10 PC's.

### Firefly version

firefly-desktop-1.2.0

### OS details

Windows 10 (10.0.18363)

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Start Firefly
2. Choose language -> (English) and press Continue
3. Accept Privacy Policy and press Continue
3. Use Dark Theme and press Continue
4.  Set Profile name on "Create a profile" page and press Continue
5. On "Set up wallet" page press back arrow to go back to "Create a profile" page
6. On "Create a profile" page press back arrow again
6. BUG: Back button did not work application is still on  "Create a profile" page and you cannot press any new button it looks frozen.

### Expected behaviour

After pressing back button when we return to the "Create a profile" page application should still work.

### Actual behaviour

Application is not responding to any inputs/outputs

**Comment by maxwellmattryan** [comment]
This is fixed in the `develop` branch. There was a lock on the storage for `wallet.rs` and we added an API call that removes it for us "unlocking" the actual file to delete.
