### ISSUE TITLE
Cuenta a 0 y Wallet Desconectada

### ISSUE THREAD

**Issue by Ismasun** [iotaledger/firefly#1657]
### Issue description

CUENTA A 0 Y WALLET DESCONECTADA!!!!!

### Firefly version

1.2.0

### OS details

WINDOWS 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

Hola, veo que es un problema comun......
He creado la Wallet y todo iva bien, traspase mis IOTAS desde Binance, vi mi saldo y hice un cambio de mi contraseña numerica de acceso, a partir de ese momento mi saldo es 0 y en estado de Red pone Desconectada. He intentado varios pasos pero no me reconoce mi contraseña, que al final incomprensiblemente he podido cambiar con una que no era la correcta, por otro lado he intentado añadir otro perfil con las 24 palabras que copie y repase tres veces y no entiendo porque esta encallada en una palabra que no reconoce que pondria la mano en el fuego que las 24 estan bien. 

### Expected behaviour

Que la Wallet no se desconecte cuando haces algun cambio de contraseña.
Somos dos amigos, hemos creado las Wallets a la vez, el no ha hecho ninguna modificacion de contraseñas y le va bien, yo si la he cambiado y no me va. Los dos lo hemos hecho con Windows.......

### Actual behaviour

Frustracion y Preocupacion

### Errors

Client Error ()

**Comment by Ismasun** [comment]
Tampoco hay Historial ni Carteras claro ...........

**Comment by nicole-obrien** [comment]
Duplicate of https://github.com/iotaledger/firefly/issues/1656 please track issue there.
