### ISSUE TITLE
Cuenta a 0 y wallet desconectada

### ISSUE THREAD

**Issue by Ribtar** [iotaledger/firefly#1659]
### Issue description

Ayer realicé mi primer ingreso de MIOTAs a la cartera y funcionó perfectamente. Decidí cambiar mi contraseña, y hoy No aparece mi wallet (y por tanto con saldo 0). En historial de operaciones me aparece vacío.
Aparece un mensaje de red desconectada.
¿Cómo puedo acceder de nuevo a mi wallet y a mis MIOTAs?

### Firefly version

Firefly v.1.2.0.

### OS details

Windows 11

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1. Envío mis MIOTAs a mi wallet de Firefly. Envío exitoso, aparecen en mi balance.
2. Decido cambiar mi PIN de acceso
3. Al día siguiente, abro la aplicación y mi wallet ha desaparecido (saldo 0), no existe historial de transacciones, y aparece un mensaje de red desconectada.
...

### Expected behaviour

Espero que se informe del error y se restablezca el servicio con los saldos correspondientes

### Actual behaviour

El hecho de que mi cartera con mis MIOTAs no aparezca, evidentemente mi causa temor de perder mi inversión.

**Comment by MiKeF05** [comment]
This is a known bug and will hopefully be fixed with the new version. In the meantime you can try to create a new profile and restore your wallet with the 24 words or the stronghold file.

**Comment by Ribtar** [comment]
Thank you MikeF05.
I created a new profile and everything is OK
Thanks again
