### ISSUE TITLE
GATE.io not allowing transfers of IOTA to Firefly

### ISSUE THREAD

**Issue by coincowboy** [iotaledger/firefly#1662]
### Issue description

Not exactly a firefly issue, but it really is a problem for firefly and IOTA because it will be missing out on a ton of liquidity if GATE.io users cant transfer.  Users of Gate.io are not able to move their IOTA to a FIREFLY address.  It wont allow you to pick a chain either.  Folks are complaining about it on stackexchange [https://iota.stackexchange.com/questions/2799/how-to-get-firefly-out-of-an-exchange-that-has-suspended-withdrawals/2802#2802](url)   Here is a screenshot of the message they see. 
![GateIOscreenshot](https://user-images.githubusercontent.com/95137869/143768791-871cdd9c-9fce-4fb9-9646-9f3230961dd9.jpg)

### Firefly version

1.2.0

### OS details

Windows 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.Gate.io will not allow transfers of IOTA
2.
3.
...

### Expected behaviour

Gate.io should have the new chain to allow transfers, but they have not updated their chain information.  from stackexchange, "that they did not update their withdrawal logic for the changes in the Chrysalis update in April 2021."

### Actual behaviour

Says the blockchain is under maintenance

**Comment by nicole-obrien** [comment]
Sorry we are unable to help with this request, as it is not an issue with Firefly.
