### ISSUE TITLE
Firefly won't accept my PIN

### ISSUE THREAD

**Issue by Freyabelle** [iotaledger/firefly#1663]
### Issue description

I have tried to log into my Firefly account to check my IOTA which I normally do most days but it won't accept my PIN. I have tried it several times but no joy. I will try again tomorrow.

### Firefly version

1.2.0 IOTA Foundation

### OS details

Windows10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Clicked onto my profile
2. Entered my PIN
3. Keeps saying incorrect PIN
...

### Expected behaviour

I expect to be logged into my IOTA account

### Actual behaviour

Not being allowed to log in

**Comment by nicole-obrien** [comment]
@Freyabelle have you recently changed your pincode or password?

**Comment by nicole-obrien** [comment]
Thanks, think this is possibly related to another issue. But as you are all sorted I will close this one.
