### ISSUE TITLE
Wallet a 0 Red Desconectada 2ª consulta

### ISSUE THREAD

**Issue by Ismasun** [iotaledger/firefly#1668]
### Issue description

Error de la Wallet Fondos: 0 y desconectada Vuelvo ha hacer la consulta.

### Firefly version

1.2.0

### OS details

WINDOWS 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

Hola, no se porque se ha retirado mi consulta, la solucion la habeis puesto en otra consulta de otro usuario !!!!!!!!!
No entiendo nada, esa solucion a mi no me funciona........ 
Os vuelvo a realizar la consulta:
He creado la Wallet y todo iva bien, traspase mis IOTAS desde Binance, vi mi saldo y hice un cambio de mi contraseña numerica de acceso, a partir de ese momento mi saldo es 0 y en estado de Red pone Desconectada. He intentado varios pasos pero no me reconoce mi contraseña, que al final incomprensiblemente he podido cambiar con una que no era la correcta, por otro lado he intentado añadir otro perfil con las 24 palabras que copie y repase tres veces y no entiendo porque hay una palabra que no reconoce, esta palabra la copie correctament, pondria la mano en el fuego que las 24 estan bien. 
Que solucion me dais?????
No entiendo porque habeis quitado la consulta sin haberme dado una solucion.........

### Expected behaviour

Que me deis una solucion para poder operar con mis IOTAS, es un problema de funcionamiento de Firefly, yo he hecho los pasos correctos!!!!!!!

### Actual behaviour

Estoy muy molesto, no he podido operar con la Wallet..........

### Errors

Client Error: ()

**Comment by Ismasun** [comment]
Ahora me doy cuenta que habeis puesto que mi consulta esta duplicada, no lo entiendo.......
Llevo 6 dias esperando

**Comment by nicole-obrien** [comment]
We only need to track an issue once and in a single place. If you need support to access your funds until this is fixed, you will find very helpful people in our discord server to help you. https://discord.iota.org/

**Comment by Ismasun** [comment]
OK... lo intento.
