### ISSUE TITLE
IOTA Transferred to Firefly wallet. Not recieved

### ISSUE THREAD

**Issue by daljeet0679** [iotaledger/firefly#1669]
### Issue description

Hello! 

I have transferred IOTA tokens from Binance to Firefly wallet, i see transaction is cleared on IOTA ledger but tokens have not received in my wallet.

My transaction ID is 27ae0ac6eadeaaab6e289ea9267aad57508cc317a53276f196ddb0c58cdb3cac

My wallet Address  iota1qr8gcvsjtvpxtetjamr2xnwj49catd5jd8h082n7h9axcgt6svam62cv6ur

Please help! 

### Firefly version

1.2.0

### OS details

Windows 10 Enterprise Version 1709 16299.2166

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.
2.
3.
...
Login to Firefly and under wallet i see no tokens

### Expected behaviour

Tokens should appear

### Actual behaviour

No tokens are appearing in the wallet even after transaction is confirmed hours back.

**Comment by MiKeF05** [comment]
Hello,

what is the status of the network in your Firefly? Are you connected to the network?

**Comment by nicole-obrien** [comment]
@daljeet0679 did you by any chance change your pin recently?

**Comment by daljeet0679** [comment]
Mike, thanks! i did create a new wallet and restore with my 24 words
recovery key and in the new wallet too i see status as not connected. I
suspect something to do with the firewall which could be blocking certain
traffic.

Can i install this wallet on iphone? I dont find it on app store.

Please advise

**Comment by daljeet0679** [comment]
> @daljeet0679 did you by any chance change your pin recently?

Nope! I am using it for the first time.

**Comment by MiKeF05** [comment]
@daljeet0679 The mobile wallet for Firefly is currently being developed. Do you use a work PC or a private computer? You can try to actively allow Firefly in your Firewall. Also you can try to temporarily disable your Firewall.

Are there any errors in the error log in Firefly?

**Comment by daljeet0679** [comment]
Mike! its actually a work laptop and we cannot disable the firewall :-) Let me install it on my kids laptop

**Comment by MiKeF05** [comment]
Ah okay. This could be the issue that some process is being blocked. Try it on another computer as you said and I think it should be good

**Comment by daljeet0679** [comment]
Thanks Mike! its working on my alternate laptop.

**Comment by nicole-obrien** [comment]
Thanks Mike for providing support.
