### ISSUE TITLE
Refreshing of transactions possible without unlocking the Wallet

### ISSUE THREAD

**Issue by RusssaQ** [iotaledger/firefly#1672]
### Issue description

I had my wallet locked, clicked on one of the latest transactions. 
![Screenshot 2021-11-30 203555](https://user-images.githubusercontent.com/64601209/144116082-a5e04e12-7e1e-4f26-8333-b4d86d65e082.png)

New window opened where I clicked the back arrow 
![Screenshot 2021-11-30 203607](https://user-images.githubusercontent.com/64601209/144116137-c94b0807-eada-4329-ab3a-ef4f59faf68f.png)

and was able to press the refresh button without the need of unlocking my Wallet with the password.
![Screenshot 2021-11-30 203621](https://user-images.githubusercontent.com/64601209/144116172-361928a3-2215-44a8-adfe-cddf82b3dfb1.png)

### Firefly version

1.2.0

### OS details

Windows 10 Home 20H2 19042.1348

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Open Firefly wallet and access profile
2. Click on one of the latest transactions shown.
3. In the new window click back arrow on the left of "Transactions"
4. Click on the refresh button on the top right of the "Transactions" window
5. No Password needed to refresh
...

### Expected behaviour

The request for the wallet password is expected to open after clicking the refresh button when the wallet is not unlocked.
Since it is also needed when opening the wallet main window

### Actual behaviour

Wallet password is not needed when pressing refresh button.

**Comment by nicole-obrien** [comment]
Thanks for the find, although it has already been reported here:: https://github.com/iotaledger/firefly/issues/1519
