### ISSUE TITLE
Creating new wallet with Ledger Nano X won't continue

### ISSUE THREAD

**Issue by AedenII** [iotaledger/firefly#1680]
### Issue description

in firefly the process wont continue after the ledger nano x is recognized and the iota app is opend. firefly confirms the connection to the hardware wallet, but won't do anything after i click "continue".
the firefly application and the iota app (v. 0.5.5) on the nano ledger x are both new installed and reinstalled after some tries. everything is up-to-date. all applications were closed on the last try. computer was rebooted before.
it should create a new firefly wallet with the nano ledger x stick.

### Firefly version

1.2.0

### OS details

Windows 10 Home 21H2 19044.1387

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. open firefly
2. continue (language dialog)
3. accept policy & terms of service
4. use dark theme
5. set profilename
6. "create new wallet"
7. "i want a hardware wallet"
8. set pin-code
9. connect hardware wallet
10. unlock hardware wallet
11. open iota app on hardware wallet
12. click continue
13. -

### Expected behaviour

the application should go forward in the dialog

### Actual behaviour

the continue button shortly shows a message about connecting or processing (not sure) and then back to "continue"
no error message dialog or change on the hardware wallet

### Errors

LedgerMiscError: ledger transport error

**Comment by MiKeF05** [comment]
Hello,

it seems that you use an outdatet firmware version of your ledger device. For ledger nano x the firmware version should at least be 1.3. If there is no hint in Ledger Live to update the firmware version you need to manually download it from the Ledger Live website and install it again. After you updated the firmware version and the IOTA app it should be good.

**Comment by AedenII** [comment]
I'll check it and try it again and let you know. thank you so far.

**Comment by AedenII** [comment]
it worked. ledger had a problem with the automatic update function of ledger live. this also prevented the newest update of the ledger nano x software. although it said its updated to the newest, there was a even newer version available after the manual update of ledger live via their support website. thanks for the help.
