### ISSUE TITLE
Firefly not working after profile deletion

### ISSUE THREAD

**Issue by WvHDev** [iotaledger/firefly#1687]
### Issue description

After deleting a profile the firefly app is not responding. I have to go to task manager and close the application to restart it.

### Firefly version

1.2.0

### OS details

Windows 11

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Open Firefly 1.2.0
2. Go to settings
3. Delete current profile
4. Firefly is not working anymore
...

### Expected behaviour

I expect to continue with Firefly and create a new profile after that

### Actual behaviour

The app is not responding and I have to manually close the app through task manager (ctrl alt del)

### Errors

No error

**Comment by MiKeF05** [comment]
Hello,

there will be some fixes in the new release where this bug should be resolved. So you can try this with the new version of Firefly.
