### ISSUE TITLE
Problem: network disconnected status and my wallet is not showing!

### ISSUE THREAD

**Issue by Mellacyrpto** [iotaledger/firefly#1696]
**Issue description**
Firefly in network disconnected status and my wallet is not showing!

**Firefly version**
firefly-desktop-1.2.0

**OS details**
Windows 8.1 64x

**Can the issue be reliably reproduced?**
Yes

**Steps to reproduce the issue**
every time i start the program i could not connect the firefly wallet and my balance is not shown

**Actual behaviour**
Application is not connecting 

**Errors**
App Version: 1.2.0

platform: win32
platformVersion: 6.3.9600
platformArchitecture: x64
cpuCount: 4
totalMem: 7969.1 MB
freeMem: 6222.9 MB
userPath: C:\Users\Admin\AppData\Roaming\Firefly

Error Type: Preload Context Error

Error: Uncaught TypeError: Cannot read property 'signerType' of undefined
    at C:\Users\Admin\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:548089
    at C:\Users\Admin\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:590377
    at Array.forEach (<anonymous>)
    at destroy (C:\Users\Admin\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:590365)
    at C:\Users\Admin\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:2:582435

**Comment by MiKeF05** [comment]
Hello,

I think this is most likely a bug in Firefly. This will be fixed with the new release. In the meantime you can try to create a new profile and restore your profile with your 24 words. If you use a ledger then use the ledger to restore your profile.

**Comment by acenolaza** [comment]
@MiKeF05 I'm having the same issue in v1.3.0

Firefly v1.3.0
Language: en
Currency: USD
Node selection: Automatic
Platform: linux
Platform Version: 5.10.0-0.bpo.9-amd64
Platform Architecture: x64
CPU Count: 4
Total Memory: 11864.3 MB
Free Memory: 445.1 MB

Tue, 21 Dec 2021 14:54:57 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:54:47 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:54:37 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:54:27 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:54:17 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:54:07 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:53:57 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:53:47 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:53:45 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:53:27 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:53:21 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/addresses/iota1qzwq798ym47gc3sa872k2uf3tgxxzzgx7m7jllaayr8jsn62gq7qgjh6xze/outputs): connection closed before message completed`

Tue, 21 Dec 2021 14:53:16 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:53:16 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qzwq798ym47gc3sa872k2uf3tgxxzzgx7m7jllaayr8jsn62gq7qgjh6xze): connection closed before message completed

Tue, 21 Dec 2021 14:53:15 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/events): connection closed before message completed

Tue, 21 Dec 2021 14:52:46 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Tue, 21 Dec 2021 14:51:23 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/addresses/iota1qzwq798ym47gc3sa872k2uf3tgxxzzgx7m7jllaayr8jsn62gq7qgjh6xze/outputs?include-spent=true): connection closed before message completed`

Tue, 21 Dec 2021 14:51:23 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qzwq798ym47gc3sa872k2uf3tgxxzzgx7m7jllaayr8jsn62gq7qgjh6xze): connection closed before message completed

Tue, 21 Dec 2021 14:51:22 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:51:19 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/events): connection closed before message completed

Tue, 21 Dec 2021 14:49:02 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/events): connection closed before message completed

Tue, 21 Dec 2021 14:49:01 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:48:51 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection error: Connection reset by peer (os error 104)`

Tue, 21 Dec 2021 14:48:41 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:48:31 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:48:11 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): error trying to connect: tls handshake eof`

Tue, 21 Dec 2021 14:48:03 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:47:51 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:47:41 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:47:31 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:47:21 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:47:11 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:46:51 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:46:41 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:46:37 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/events): connection closed before message completed

Tue, 21 Dec 2021 14:46:31 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:46:21 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:46:11 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:46:01 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:45:51 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:45:41 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:45:31 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:45:21 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:45:11 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:45:04 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:45:02 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): error trying to connect: tls handshake eof`

Tue, 21 Dec 2021 14:45:01 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:44:51 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:44:41 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:44:31 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:44:21 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:44:11 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:43:52 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:43:51 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:43:41 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:43:39 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Tue, 21 Dec 2021 14:43:38 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Tue, 21 Dec 2021 14:43:32 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Tue, 21 Dec 2021 14:43:31 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:43:22 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qzwq798ym47gc3sa872k2uf3tgxxzzgx7m7jllaayr8jsn62gq7qgjh6xze): channel closed

Tue, 21 Dec 2021 14:43:20 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:43:16 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/events/57607d9f8cefc366c3ead71f5b1d76cef1b36a07eb775158c541107951d4aecb): connection closed before message completed

Tue, 21 Dec 2021 14:42:41 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:42:31 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:42:11 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:42:01 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:41:51 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:41:41 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:41:32 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:41:25 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/events): connection error: Connection reset by peer (os error 104)

Tue, 21 Dec 2021 14:41:21 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection error: Connection reset by peer (os error 104)`

Tue, 21 Dec 2021 14:41:11 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:41:01 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:40:51 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:40:41 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:40:31 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:40:21 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:40:11 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:40:01 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:39:51 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:39:41 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:39:31 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:39:21 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:39:11 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:38:51 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:38:41 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:38:31 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:38:21 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:38:11 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:37:56 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:37:42 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:37:33 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:37:23 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:37:22 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/events): connection closed before message completed

Tue, 21 Dec 2021 14:37:11 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:36:59 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/events/57607d9f8cefc366c3ead71f5b1d76cef1b36a07eb775158c541107951d4aecb/status): connection closed before message completed

Tue, 21 Dec 2021 14:36:51 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:36:41 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:36:31 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qqcnn6k6dmerfpclyp8jtv464a3jlnq3t63lf8yrqndhdtmv8le3jhf6emt): connection closed before message completed

Tue, 21 Dec 2021 14:36:31 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/addresses/iota1qzwq798ym47gc3sa872k2uf3tgxxzzgx7m7jllaayr8jsn62gq7qgjh6xze/outputs?include-spent=true): connection closed before message completed`

Tue, 21 Dec 2021 14:36:30 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:36:27 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/events): connection closed before message completed

Tue, 21 Dec 2021 14:35:49 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:35:38 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:35:29 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:35:18 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:35:08 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:34:58 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:34:48 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:34:44 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:34:28 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:34:08 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:33:48 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:33:42 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:33:28 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:33:18 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:33:08 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:32:48 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:32:39 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:32:28 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): channel closed`

Tue, 21 Dec 2021 14:32:17 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:32:07 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection closed before message completed`

Tue, 21 Dec 2021 14:31:58 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/addresses/iota1qzwq798ym47gc3sa872k2uf3tgxxzzgx7m7jllaayr8jsn62gq7qgjh6xze/outputs?include-spent=true): connection closed before message completed`

**Comment by MiKeF05** [comment]
Can you try to change the node to 
https://mainnet-node.tanglebay.com

**Comment by acenolaza** [comment]
Thanks. It automagically started working and I think it has something to do with this: https://discord.com/channels/397872799483428865/800810467928309790/922868580339572786

**Comment by MiKeF05** [comment]
Yes the node API of this node is quite busy. But should work now with the other node.

**Comment by MiKeF05** [comment]
@Mellacyrpto Were you able to solve your issue?
