### ISSUE TITLE
FireFly: network disconnected, no IOTA showing in the wallet 

### ISSUE THREAD

**Issue by abloccato** [iotaledger/firefly#1703]
### Issue description

I transferred my IOTA last week, and I correctly received them on my wallet on FireFly. 
After a couple of days, when I accessed again my wallet there were no more IOTA showing, in the left bottom corner there are three red bars signing "Network Disconnected", and even going on "Advance Settings" and clicking on "Find balances" it doesn't change. 
It's like my app is not connected to internet.. 
![Capture](https://user-images.githubusercontent.com/95850624/145370726-2cf72a33-1b39-40d8-8ca9-41cfed029e25.PNG)
![image](https://user-images.githubusercontent.com/95850624/145370900-78c10ed2-8127-4840-82e8-d0c13fbecbed.png)

### Firefly version

Firefly v1.2.0

### OS details

Windows 10 Pro, version 1909

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

To bring back my network connection and recover my IOTA

### Actual behaviour

Wallet not connected, IOTA not showing, I cannot even see my past transaction history!

### Errors

Wed, 08 Dec 2021 11:35:14 GMT
ClientError: {}

Wed, 08 Dec 2021 10:53:51 GMT
ClientError: {}

Tue, 07 Dec 2021 09:00:37 GMT
ClientError: {}

Mon, 06 Dec 2021 16:46:49 GMT
ClientError: {}

Fri, 03 Dec 2021 16:13:50 GMT
ClientError: {}

Fri, 03 Dec 2021 15:55:25 GMT
ClientError: {}

Fri, 03 Dec 2021 14:57:41 GMT
ClientError: {}

**Comment by MiKeF05** [comment]
Hello,

this is a known issue in the current version of Firefly and will be fixed with the next release. In the meantime you can try to create a new profile and restore your wallet either with the stronghold backup file or your 24 words. 

Hopefully the new version will be released soon.

**Comment by abloccato** [comment]
Thank you very much!! 
It worked :) 


Andre
