### ISSUE TITLE
Typing a . (Period) on the amount, freezes wallet functionality

### ISSUE THREAD

**Issue by cometax** [iotaledger/firefly#1706]
### Issue description

When transferring funds from a wallet to another (I believe also when sending), if you type .1 for example, the wallet stops functioning and requires a sw restart to recover. Note: if you type a number prior to the period, it works fine, as soon as the first digit is a period, it does not behave correctly. 

### Firefly version

1.2.0

### OS details

Windows 10 pro

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Open a profile
2. Go to a wallet
3. Go to internal transfer
4. type a .3 on the amount to send
5. Try to send anything or switch screens, it will not work.
...

### Expected behaviour

It should be able to send .5 Giotas or not freeze functionality if a period is entered at the beginning 

### Actual behaviour

If the first digit happens to be a period, even if you correct the error right away, firefly is no longer functional

### Errors

I will update the ticket with any log I find.

**Comment by rajivshah3** [comment]
This issue seems to be fixed (not sure which commit it was fixed in)
