### ISSUE TITLE
WRONG PASSWORD

### ISSUE THREAD

**Issue by DAGQ** [iotaledger/firefly#1714]
### Issue description

Firefly don´t recognize my password , it say´s  wrong password

### Firefly version

v1.2.0

### OS details

Windows 10

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

accept my account password

### Actual behaviour

don´t recognize my account password

### Errors

Sun, 12 Dec 2021 13:41:58 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sun, 12 Dec 2021 13:41:49 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sun, 12 Dec 2021 13:21:38 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sun, 12 Dec 2021 13:21:02 GMT
ClientError: {}

Sun, 12 Dec 2021 13:20:30 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sun, 12 Dec 2021 13:09:46 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sun, 12 Dec 2021 13:09:32 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sun, 12 Dec 2021 13:09:16 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sun, 12 Dec 2021 13:01:43 GMT
ClientError: {}

Sun, 12 Dec 2021 12:56:22 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sun, 12 Dec 2021 12:54:58 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sun, 12 Dec 2021 12:32:23 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sun, 12 Dec 2021 12:26:35 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sun, 12 Dec 2021 12:26:09 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sun, 12 Dec 2021 12:25:45 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sun, 12 Dec 2021 12:25:23 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

**Comment by MiKeF05** [comment]
This issue is known and will be solved with the next version. PR: https://github.com/iotaledger/wallet.rs/pull/822
In the meantime you can create a new profile and restore it either with your 24 words or your stronghold backup file. If you use a ledger device then you can restore it with the ledger.

**Comment by MiKeF05** [comment]
@DAGQ Were you able to resolve your issue?
