### ISSUE TITLE
App Version: 1.2.0  platform: win32 platformVersion: 10.0.19042 platformArchitecture: x64 cpuCount: 4 totalMem: 8191.2 MB freeMem: 2919.4 MB userPath: C:\Users\PC\AppData\Roaming\Firefly  Error Type: Main Unhandled Promise Rejection  Error: Uncaught Error: net::ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by TheGreeenMan** [iotaledger/firefly#1722]
### Issue description

I get an Error when I open the program and I send 5 MIOTA to my wallet address and nothing showed up.  Thanks.

### Firefly version

1.2.0.

### OS details

Windows 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Just reopen Firefly.
2.
3.
...

### Expected behaviour

I expected the wallet to open without errors.

### Actual behaviour

The error pops up when I open the program.

### Errors

App Version: 1.2.0

platform: win32
platformVersion: 10.0.19042
platformArchitecture: x64
cpuCount: 4
totalMem: 8191.2 MB
freeMem: 2919.4 MB
userPath: C:\Users\PC\AppData\Roaming\Firefly

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_CONNECTION_RESET

**Comment by MiKeF05** [comment]
Hello,

do you use a special firewall or a proxy?

**Comment by TheGreeenMan** [comment]
No I do not.

**Comment by MiKeF05** [comment]
Do you maybe use a VPN?

**Comment by TheGreeenMan** [comment]
It didn't work with or without a VPN, same message.

**Comment by Matthu23** [comment]
Hi, I´m facing the same problem. I´ve opend the App and received the followong message:

App Version: 1.2.0

platform: win32
platformVersion: 10.0.19041
platformArchitecture: x64
cpuCount: 4
totalMem: 16239.6 MB
freeMem: 10843.0 MB
userPath: C:\Users\Admin\AppData\Roaming\Firefly

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NETWORK_CHANGED

**Comment by Matthu23** [comment]
The prblem was shown only once. By re-opening the App, it worked out as it should.

**Comment by TheGreeenMan** [comment]
Glad it worked for ya.  Im still having same issue.

**Comment by MiKeF05** [comment]
@TheGreeenMan Could you solve your issue?

**Comment by TheGreeenMan** [comment]
As far as I know it still doesnt work and my 5 MIOTA I sent still havent
appeared in the wallet.

**Comment by jmgomezpoveda** [comment]
Same issue with 1.3.0 on Linux:

```
App Version: 1.3.0

platform: linux
platformVersion: 5.13.0-22-generic
platformArchitecture: x64
cpuCount: 8
totalMem: 15905.9 MB
freeMem: 3789.6 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NAME_NOT_RESOLVED
```

I was not doing anything; just had the app open in the background.

**Comment by MiKeF05** [comment]
@TheGreeenMan What have you tried so far? Disable VPN? Disable antivir? Maybe this can help you. It relates to google chrome but should be the same error. https://www.webnots.com/how-to-fix-err_connection_reset-error-in-google-chrome/

**Comment by TheGreeenMan** [comment]
I tried the ideas on Webnots...  It is saying I cannot connect to https://mainnet-node.tanglebay.com/.  I have no idea why yet.

**Comment by TheGreeenMan** [comment]
How do I switch to the mainnet-node>?

**Comment by MiKeF05** [comment]
You just need to go to settings in Firefly then node settings and choose manual. Then you can add this node.

**Comment by TheGreeenMan** [comment]
I tried, it says something went wrong and wont allow it.

**Comment by MiKeF05** [comment]
What error is in the error log?

**Comment by rajivshah3** [comment]
Did this issue occur after your computer was locked/went to sleep?

**Comment by TheGreeenMan** [comment]
No, it just happens whenever.  I got the wallet to work on my laptop so I
am not too concerned.  It was saying I could not connect to the mainnet for
some reason.  I tried everything.  Took all firewalls down, anything that
could have blocked it. Nothing.

**Comment by MiKeF05** [comment]
This should be fixed in the latest release.
