### ISSUE TITLE
start error

### ISSUE THREAD

**Issue by goodluck518** [iotaledger/firefly#1741]
### Issue description

1.open firefly
2.a error window 
3. it cant input only one  PIN ,cusor can't auto move to next position 
4. I  move cusor in mouse one by one
5. input correct PIN, but report password error

### Firefly version

1.2

### OS details

windows

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.open firefly
2.a error window 
3. it cant input only one  PIN ,cusor can't auto move to next position 
4. I  move cusor in mouse one by one
5. input correct PIN, but report password error
...

### Expected behaviour

login success

### Actual behaviour

I can‘t login firefly

### Errors

App Version: 1.2.0

platform: win32
platformVersion: 10.0.17134
platformArchitecture: x64
cpuCount: 4
totalMem: 3979.2 MB
freeMem: 1403.2 MB
userPath: C:\Users\GoodLuck\AppData\Roaming\Firefly

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_CONNECTION_TIMED_OUT

**Comment by MiKeF05** [comment]
Do you use a VPN or work PC?

**Comment by goodluck518** [comment]
I don't use vpn ,it pop error.when i use vpn，it doesn't pop error.
but i can only input the first PIN，i must move to the next one with mouse. (pic 1)
i input sex correct PIN, it still tell me password is wrong.(pic 2)





------------------ Original ------------------
From: MiKeF05 ***@***.***>
Date: Sun,Dec 19,2021 9:45 PM
To: iotaledger/firefly ***@***.***>
Cc: goodluck518 ***@***.***>, Author ***@***.***>
Subject: Re: [iotaledger/firefly] start error (Issue #1741)



Do you use a VPN or work PC?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MiKeF05** [comment]
@goodluck518 What do you mean with you can only input first PIN? When you login to your profile you need the PIN. Once you are in the profile you need the password to unlock your wallet if you use a normal software profile.

**Comment by goodluck518** [comment]
I figure it out.
It's weird.
Firstly, iput a arbitrary char,then delete it. After that,input six arbitrary chars.The six chars won't be diplayed.Finally, input my password.
I can login my accout ,but i don't know why it like this.
Anyway,it really works. 
Thank you very much！
















在 2021-12-24 19:16:45，"MiKeF05" ***@***.***> 写道：

@goodluck518 What do you mean with you can only input first PIN? When you login to your profile you need the PIN. Once you are in the profile you need the password to unlock your wallet if you use a normal software profile.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MiKeF05** [comment]
Okay great. Would be good if you close this issue.

**Comment by goodluck518** [comment]
Everything goes well!
