### ISSUE TITLE
After importing the profile with multiple wallets, only first is in translated form

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/firefly#1742]
### Issue description

**### PLEASE SEE UPDATE ON THIS IN THE COMMENT**

I understand that wallet names are saved nowhere and resets themselves to default when we're importing profiles but first is translated properly (in PL it's Portfel 1) but later accounts are in english (Account 2, Account 3, Account 4...). Later should be translated too (Portfel 2, Portfel 3, Portfel 4).
![M4GcKnU](https://user-images.githubusercontent.com/35224101/146148677-c0c2f310-e81e-4f6d-8a60-e21fd18a1814.png)

### Firefly version

1.3.0 beta 186

### OS details

Windows 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

0. Set lang other than English
1. Have a profile with multiple wallets
2. reset Firefly and reimport profile / or try to import the stronghold or mnemonic on second machine
3. The imported profile will have first wallet translated but later in English form

![M4GcKnU](https://user-images.githubusercontent.com/35224101/146149128-13cf47de-5d99-40f3-b497-95baa2930ff0.png)

### Expected behaviour

Having all imported wallets to be in translated form

### Actual behaviour

First wallet is translated and later english

**Comment by UmbahaSpodPaha** [comment]
Update on this bug i discovered:
- when you clean-install Firefly and import the profile, the bug doesn't exist:
![ok](https://user-images.githubusercontent.com/35224101/146563394-1da2a240-abfb-4683-9ebc-7e0026f91682.png)

- but when you close the wallet, open it again and login, every other wallet than first one changes name to english one:
![notok](https://user-images.githubusercontent.com/35224101/146563538-4fa71107-c8c9-4656-b54f-ec6f75c305d0.png)

**Comment by astede** [comment]
I have a similar problem in that I had two accounts in my Trinity wallet but after migration to Firefly using my original seed, only one account had been transferred. I would appreciate any comments as to how to resolve.
