### ISSUE TITLE
Minor UI cut on this particular screen on minimum window size

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/firefly#1770]
### Issue description

![CUT on minimum](https://user-images.githubusercontent.com/35224101/146446545-a2cb5cc3-92fb-48c3-9379-23ae38c04d3f.png)

### Firefly version

1.3.0 beta #188

### OS details

Windows 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

Add some padding/space there

### Actual behaviour

When she Firefly window has minimum size set, this exact part getting cut a little.

**Comment by MiKeF05** [comment]
This should be fixed in the latest release.
