### ISSUE TITLE
ClientError: {}

### ISSUE THREAD

**Issue by clareiota** [iotaledger/firefly#1772]
### Issue description

Above error occurs when transferring IOTA to Firefly from an exchange.
The transfer has worked previously with different addresses.

### Firefly version

v1.2.0

### OS details

macOS Monterey v12.0.1

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1. Did not reproduce the error as previous IOTA transferred are still unaccounted for.
2.
3.
...

### Expected behaviour

That the IOTA transfer from the exchange to Firefly is successful and auditable, like the 5-6 previous transfers. 

### Actual behaviour

The message from the exchange is:

Error Message: Withdrawals are currently disabled for this address due to wallet maintenance.

### Errors

[IOTA Firefly Error file - 17Dec21.docx](https://github.com/iotaledger/firefly/files/7732273/IOTA.Firefly.Error.file.-.17Dec21.docx)

The transfer failed on the following address:
iota1qzfy3cmlh5umjej2xstffu0mfl6ntvmgn22hhgavxkuwts9p65veuw4g8qk

**Comment by r-c-k** [comment]
If the exchange disabled withdrawals then this has nothing to do with Firefly. The funds were not yet transferred to your address (probably due to maintenance on their own wallet) as you can see [here](https://explorer.iota.org/mainnet/addr/iota1qzfy3cmlh5umjej2xstffu0mfl6ntvmgn22hhgavxkuwts9p65veuw4g8qk).

**Comment by Thoralf-M** [comment]
The empty ClientError will be fixed in the next release https://github.com/iotaledger/firefly/issues/1433, but as @r-c-k wrote your problem is only on exchange side
