### ISSUE TITLE
Invalid Address

### ISSUE THREAD

**Issue by Curtflix** [iotaledger/firefly#1773]
### Issue description

I recently installed the Firefly wallet and when I attempt to send IOTA from my Binance Wallet, the address copied from Firefly shows as invalid.  I am very new to crypto.  What am I doing wrong?

### Firefly version

1.2.0

### OS details

Windows 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. copy the receive wallet address from firefly
2. paste into the send address in the IOTA asset send 
3. address shows a invalid address
...

### Expected behaviour

send IOTA to firefly wallet

### Actual behaviour

can't send IOTA to invalid address

### Errors

invalid address

**Comment by svenger87** [comment]
Do you have any screenshot?
My guess is you selected the Binance Chain (BEP-20) to withdraw your funds.

Binance chain is incompatible with IOTAs mainnet.

**Comment by Curtflix** [comment]
No screen shots but I did select miotac iota.

**Comment by svenger87** [comment]
Oh yeah, Thats wrapped IOTA on Binance Chain. You can´t transfer those to firefly.

**Comment by Curtflix** [comment]
Any way around it?

**Comment by antonionardella** [comment]
To get tokens to Firefly one needs IOTA tokens that reside on IOTA's network (called the Tangle). To achieve this, send the tokens back to Binance and withdraw them to the Tangle network.
Should Binance have issues with withdrawals, get in touch with Binance's support.

**Comment by maxwellmattryan** [comment]
I'm going to close this as it is a non-Firefly issue. Best of luck with withdrawals!

**Comment by MakingStuffs** [comment]
I am also having this issue on Bitfinex. Add the Firefly wallet address and it is triggering the invalid address error.
