### ISSUE TITLE
new wallets in a profile dont appear on 2nd device

### ISSUE THREAD

**Issue by clbargain** [iotaledger/firefly#1781]
Description: when importing the same seed on 2 devices and add new wallets on one of the two, the new wallets dont show on the 2nd device.

Steps to reproduce:
1) install firefly on Device A (Windows) and import seed 'X'
2) install firefly on Device B (Windows) and import same seed 'X'
3) on Device A and under a single profile add new multiple wallets and send funds from the original wallet to the new ones by doing internal transfer.
4) restart firefly on Device B 
5) observe: the newly created wallets dont show up on device B eventhough the balance of the original wallet is updated.

**Comment by MiKeF05** [comment]
Have you tried the balance finder in the settings? You can also try to import the seed again on Device B if you created and sent funds to a wallet on Device A. But I guess this will be solved with the new version of Firefly which will be released soon.

**Comment by clbargain** [comment]
I tried the Balance finder several times but it did not solve the issue.

Deleting the Account from Firefly and re-importing the Seed worked - I still considered it as a bug as the process should have been seemless :)

**Comment by MiKeF05** [comment]
Yes this bug is already solved with a PR and will be included in the next version of Firefly.
