### ISSUE TITLE
IOTA kommt ins Firefly nicht an

### ISSUE THREAD

**Issue by fbsln-firefly** [iotaledger/firefly#1787]
Habe vor 24h MIOTA von Binance an die Firefly Wallet gesendet.

Bis jetzt sind Sie noch nicht da. Wie lange dauert es ???

Viele Grüße Lutz

**Comment by Travetown** [comment]
Binance lässt doch momentan keine Auszahlungen ins IOTA-Netz zu. 
Ist die Transaktion bei Binance abgeschlossen?

**Comment by r-c-k** [comment]
Gib mal die Adresse, an welche du die Token gesendet hast, auf [https://explorer.iota.org/mainnet](explorer.iota.org/mainnet) ein. Sollte die balance dort 0 sein, dann liegt das an Binance selbst. Die setzen Withdrawals leider häufig aus.

**Comment by svenger87** [comment]
Wahrscheinlich waren es auch MIOTAC auf der Binance chain.

**Comment by fbsln-firefly** [comment]
Was sind MIOTAC ???Auf Binance steht "ausgesetzt "Gibt es noch einen Weg Euro in IOTA zu wandeln und dann auf FireFly Wallet zu übertragen ???VG LutzVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: svenger87 ***@***.***> Datum: 18.12.21  13:44  (GMT+01:00) An: iotaledger/firefly ***@***.***> Cc: fbsln-firefly ***@***.***>, Author ***@***.***> Betreff: Re: [iotaledger/firefly] IOTA kommt ins Firefly nicht an (Issue
  #1787) 
Wahrscheinlich waren es auch MIOTAC auf der Binance chain.

**Comment by svenger87** [comment]
Ich persönlich nutze Bitpanda und Anycoin.

**Comment by fbsln-firefly** [comment]
IOTA Coins waren gestern bis heute Mittag weg und tauchten heute Nachmittag bei Binace wieder auf.Wollte neuen Versuch starten,  jetzt sagt Binance IOTA Netzwerk ausgesetzt.Gibt es Alternativen Coins auf FireFly zu bekommen???Viele Grüße LutzVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Travetown ***@***.***> Datum: 18.12.21  13:41  (GMT+01:00) An: iotaledger/firefly ***@***.***> Cc: fbsln-firefly ***@***.***>, Author ***@***.***> Betreff: Re: [iotaledger/firefly] IOTA kommt ins Firefly nicht an (Issue
  #1787) 

Binance lässt doch momentan keine Auszahlungen ins IOTA-Netz zu.

Ist die Transaktion bei Binance abgeschlossen?

**Comment by MiKeF05** [comment]
Wie oben schon erwähnt bietet sich Bitpanda für den Kauf und die Auszahlung von IOTA an.

**Comment by Nick-Picker** [comment]
BEP20 Iota sind durch "Echte" #IOTA besichert. Der "Echte" iota ist also beliehen und kann, wenn nicht genügend freie, unbeliehene Iota vorhanden sind, nicht in eine Wallet transferiert werden.

**Comment by fbsln-firefly** [comment]
Super Danke an AlleBitpanda hat super funktioniert. Die ersten IOTA sind auf der Firefly  Wallet angekommen. Jetzt kann Shimmer startenVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: svenger87 ***@***.***> Datum: 18.12.21  20:39  (GMT+01:00) An: iotaledger/firefly ***@***.***> Cc: fbsln-firefly ***@***.***>, Author ***@***.***> Betreff: Re: [iotaledger/firefly] IOTA kommt ins Firefly nicht an (Issue
  #1787) 

Ich persönlich nutze Bitpanda und Anycoin.

**Comment by Felix131195** [comment]
Ich habe leider das gleiche Problem, aber mit Bitpanda.

erfolgreich Iota ausgezahlt, aber nichts kam an in meiner Firefly-wallet.

Hat jemand Tipps für mich ?

**Comment by OBI1983** [comment]
Ich habe gestern auch meine IOTA vonBitpanda an die Firefly Wallet gesendet aber bis jetzt ist es dort noch nicht angekommen.
Bei Bitpanda wird der Transaktionsstatus immer noch als Ausstehend angezeigt.
Kann mir jemand weiterhelfen?

**Comment by Felix131195** [comment]
Ich habe den Support kontaktiert... der meinte es müsste geklappt haben, wenn nicht sollte ich mich nochmal melden.
Hat natürlich nicht geklappt.. warte nun auf Antwort vom Support.

**Comment by OBI1983** [comment]
Ok. Könnten sie mich dann mal auf dem laufenden halten?Gesendet mit der WEB.DE iPhone AppAm 22.12.21 um 19:21 schrieb Felix131195
                
            
            
                
                    Von: "Felix131195" ***@***.***>Datum: 22. Dezember 2021An: "iotaledger/firefly" ***@***.***>Cc: "OBI1983" ***@***.***>,"Comment" ***@***.***>Betreff: Re: [iotaledger/firefly] IOTA kommt ins Firefly nicht an (Issue #1787)
                
                

Ich habe den Support kontaktiert... der meinte es müsste geklappt haben, wenn nicht sollte ich mich nochmal melden.

Hat natürlich nicht geklappt.. warte nun auf Antwort vom Support.

**Comment by Felix131195** [comment]
Natürlich, mich nervt das grad nur.. ich hoffe meine Coins sind nicht weg.
Aber die Wallet Adresse ist korrekt.

**Comment by Stefan000020** [comment]
Hey,

ich habe mir einen Entwickler Account angelegt, kann man darauf nichts schicken?
Es ist bei mir nichts angekommen, hat jemand einen Tipp was ich nun unternehmen kann ?

Danke

**Comment by OBI1983** [comment]
Ja ich habe auch extra noch mal alles kontrolliert. Bei mir ist auch alles soweit korrekt.

**Comment by MiKeF05** [comment]
Die Transaktionen können alle unter explorer.iota.org überprüft werden. Einfach dort die Adresse eintragen und überprüfen, ob diese bestätigt wurde.

**Comment by MiKeF05** [comment]
@Stefan000020 Wieso hast du dir einen Entwickleraccount angelegt? Ein solcher Account ist, wie es der Name schon sagt, für Entwickler und mit eine Testnetzwerk verbunden. Du musst dir also einen neuen Account erstellen, um IOTA Tokens zu empfangen und zu senden.

**Comment by Stefan000020** [comment]
Okay sind die Tokens dann weg ?

**Comment by MiKeF05** [comment]
Hast du eine Adresse mit atoi am Anfang?

**Comment by Stefan000020** [comment]
Ja

**Comment by Stefan000020** [comment]
Habe jetzt 2 Wallets, auf dem einen hat es geklappt aber auf dem Entwickler eben nicht.

**Comment by OBI1983** [comment]
Ich habe meine Adresse mal da eingegeben da steht dann das die Balance 0 ist. Was hat das jetzt zu bedeuten?Gesendet mit der WEB.DE iPhone AppAm 22.12.21 um 19:35 schrieb MiKeF05
                
            
            
                
                    Von: "MiKeF05" ***@***.***>Datum: 22. Dezember 2021An: "iotaledger/firefly" ***@***.***>Cc: "OBI1983" ***@***.***>,"Comment" ***@***.***>Betreff: Re: [iotaledger/firefly] IOTA kommt ins Firefly nicht an (Issue #1787)
                
                

Die Transaktionen können alle unter explorer.iota.org überprüft werden. Einfach dort die Adresse eintragen und überprüfen, ob diese bestätigt wurde.

**Comment by MiKeF05** [comment]
@Stefan000020 Normal kannst du keine Tokens des Mainnets auf eine atoi Adresse senden. Da bekommst du eine Fehlermeldung auf der Exchange

**Comment by MiKeF05** [comment]
@OBI1983 Wenn die Balance noch 0 ist, dann hat die exchange die Token noch nicht versendet. Dann solltest du warten oder den Support der Exchange kontaktieren.

**Comment by Felix131195** [comment]
Ich habe anscheinend den gleichen Fehler gemacht, bezüglich des Entwickler-Acc..
gleiche Frage sind meine Coins nun weg oder gelangen sie zurück zu Bitpanda.(wegen Fehlermeldung) `?

**Comment by Stefan000020** [comment]
Habe von Bitpanda aus die Entwickler atio Adresse eingegeben und auf Bitpanda stand das alles hat funktioniert.

**Comment by OBI1983** [comment]
Ok dann werde ich das mal versuchen.Meine Adresse fängt mit iota… an ist das dann richtig? Vielen Dank schon mal. Gesendet mit der WEB.DE iPhone AppAm 22.12.21 um 19:47 schrieb MiKeF05
                
            
            
                
                    Von: "MiKeF05" ***@***.***>Datum: 22. Dezember 2021An: "iotaledger/firefly" ***@***.***>Cc: "OBI1983" ***@***.***>,"Mention" ***@***.***>Betreff: Re: [iotaledger/firefly] IOTA kommt ins Firefly nicht an (Issue #1787)
                
                
@OBI1983 Wenn die Balance noch 0 ist, dann hat die exchange die Token noch nicht versendet. Dann solltest du warten oder den Support der Exchange kontaktieren.

**Comment by MiKeF05** [comment]
Alle Adressen auf dem Mainnet beginnen mit iota. Das ist richtig.

Normal ist das nicht möglich von einer Exchange auf atoi zu senden, da diese die Adresse überprüfen. Sobald eine Fehlermeldung kommt, sind die Tokens weiterhin auf der Exchange.

**Comment by MiKeF05** [comment]
@Stefan000020 Du solltest den Support der Exchange kontaktieren, dass sie nachsehen.

**Comment by Stefan000020** [comment]
@MiKeF05 mit Exchange meinst du Bitpanda?

**Comment by MiKeF05** [comment]
Jup genau, wenn du von dort aus deine Token versendet hast.

**Comment by Felix131195** [comment]
Und was wäre, wenn die die Coins doch versendet hätten ?

**Comment by MiKeF05** [comment]
Wie gesagt, die Exchange prüft normalerweise die Adresse. Kontaktiert bitte die Exchange über den Support. Nur die kann euch in diesem Fall weiterhelfen.

**Comment by Stefan000020** [comment]
Alles klar habe ich gemacht.

Danke für die Hilfe

**Comment by Felix131195** [comment]
ja habe ich gemacht, danke für die kompetente Hilfe. 

den ganzen stress nur wegen eines kleinen Fehlers

**Comment by Felix131195** [comment]
Bitpanda sagt die Walletauszahlung war erfolgreich.

Aber keine Coins.

Hab jetzt zum 2ten mal geschrieben, dass es doch nicht möglich sei und es eine Fehlermeldung geben müsste, bevor es überwiesen wird.

**Comment by Stefan000020** [comment]
Hey
das gleiche habe sie bei mir auch geschrieben, ich soll mich an Firefly wenden sozusagen.

**Comment by Stefan000020** [comment]
@Felix131195  was machst du nun und um wieviel Geld handelt es sich bei dir?

**Comment by r-c-k** [comment]
Kommt doch bitte mal auf den [IOTA Discord](https://discord.iota.org) @Stefan000020 & @Felix131195, dort kann man euch wesentlich effizienter helfen als hier. Kontaktiert mich dort auch gerne per Direktnachricht (rck#3810).

**Comment by r-c-k** [comment]
Issue kann geschlossen werden @fbsln-firefly
