### ISSUE TITLE
I have a similar problem in that I had two accounts in my Trinity wallet but after migration to Firefly using my original seed, only one account had been transferred. I would appreciate any comments as to how to resolve.

### ISSUE THREAD

**Issue by astede** [iotaledger/firefly#1793]
I have a similar problem in that I had two accounts in my Trinity wallet but after migration to Firefly using my original seed, only one account had been transferred. I would appreciate any comments as to how to resolve.

_Originally posted by @astede in https://github.com/iotaledger/firefly/issues/1742#issuecomment-997276620_

**Comment by MiKeF05** [comment]
I think you should also have 2 seeds no?

**Comment by astede** [comment]
Thank you for your reply, but I only had the one which I kept all the time when I created my 2 accounts within Trinity

**Comment by MiKeF05** [comment]
Do you have Trinity installed? You can login and search for the second seed. Before you open Trinity disable your internet connection. After this you should be able to login.

Click on the account and go to "View seed".

**Comment by astede** [comment]
I have resolved the problem. Used earlier version of Firefly and followed instructions with using a Ledger. Both of my accounts migrated successfully. Feel free to ask further questions for clarification. Cheers
