### ISSUE TITLE
miota withdrawal disabled on binance

### ISSUE THREAD

**Issue by Gert1978** [iotaledger/firefly#1795]
### Issue description

miota withdrawal disabled on binance

### Firefly version

v1.2.0

### OS details

windows 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.miota withdrawal disabled on binance
2.
3.

### Expected behaviour

miota withdrawal disabled on binance

### Actual behaviour

miota withdrawal disabled on binance

### Errors

miota withdrawal disabled on binance

**Comment by Travetown** [comment]
It's unrelated to Firefly.

**Comment by Gert1978** [comment]
according to binance its unrelated to Binance. where is the problem?

**Comment by Travetown** [comment]
![image](https://user-images.githubusercontent.com/66588710/146669694-c8338077-b1ca-4207-a9cf-3be0a03ba99c.jpeg)

**Comment by teunvw14** [comment]
Yeah this is Binance's fault, has nothing to do with firefly.

**Comment by nicole-obrien** [comment]
Not an issue with firefly
