### ISSUE TITLE
Mutiple issue: Recovery phase & password unrecognized 

### ISSUE THREAD

**Issue by Lawwuji** [iotaledger/firefly#1797]
I migrated my wallet from trinity to firefly, later when I try to do an transaction, it's telling me my password is wrong.
Then I try to restore the wallet using recovery phrase, it reports there is unrecognize word, right now I can only check the wallet balance using pin code, I wrote down both my password and recovery phrase on paper, but they both somehow don't work, please help.

**Comment by MiKeF05** [comment]
If Firefly tells you there is a unrecognized word then you might have a typo in one of the words. You can check the words you have written down if they all are in this list: https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

Maybe you have also a typo or caps lock when you set the password or when you type it in to do a transaction.

**Comment by Lawwuji** [comment]
Thank you so much, you nailed it, both.

**Comment by MiKeF05** [comment]
Great. So I guess this issue can be closed.

**Comment by BrendanV21** [comment]
How do i reset my password if my password is not correct

**Comment by MiKeF05** [comment]
@BrendanV21 You need to create a new profile with your 24 words. If you use a ledger device you need the device to create a new profile.
