### ISSUE TITLE
My staking buttons are not live yet on Firefly wallet 

### ISSUE THREAD

**Issue by Littlebit1212** [iotaledger/firefly#1829]
### Issue description

I saw on YouTube that Pre-staking has begun yet my staking buttons are not live or visible yet??  Please help.

### Firefly version

iota1qpscgm24r0zru55yrz5ckmj9trrtd424txlrmr2p4lnc2vfu0reuu6yln6u

### OS details

Windows 11

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.Sign in
2.No staking button
3. No staking button
...

### Expected behaviour

There should be pre-staking and I have no staking button

### Actual behaviour

No staking button

### Errors

No errors appear  forget it I figured it out.  I had to update.

**Comment by MiKeF05** [comment]
Please download the latest version of Firefly https://firefly.iota.org/

**Comment by AjayanN** [comment]
it could take sometime.

**Comment by MiKeF05** [comment]
Issue can be closed
