### ISSUE TITLE
Stuck in Pin Confirmation

### ISSUE THREAD

**Issue by ematiasm** [iotaledger/firefly#1833]
### Issue description

Stuck in Pin confirmation

### Firefly version

1.3

### OS details

ManjaroKDE updated 20211221

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.  Launch AppImage
2. Recover wallet with FireFlySeed
3. Set new password
4. Set Pin
5. Confirm Pin
6. Nothing appens
...

### Expected behaviour

open dashboard

### Actual behaviour

stuck in pin confirmation

**Comment by MiKeF05** [comment]
Make sure to install gnome-keyring
