### ISSUE TITLE
Two typo in French translation

### ISSUE THREAD

**Issue by Yann39** [iotaledger/firefly#1837]
# Issue description

I simply noticed 2 typo in French translated version of the Firefly app.

# Errors

In the upper right tooltip :
![iota1](https://user-images.githubusercontent.com/1263086/146979687-515f264c-a8d6-483f-9de2-3805ab062e67.JPG)
"Ouvrez la onfiguration ..." should be "Ouvrez la configuration ..."

In the staking confirmation step :
![iota2](https://user-images.githubusercontent.com/1263086/146979693-b73d5931-128d-4aeb-9c25-f2528395184d.JPG)
"En mettons vos fonds ..." should be "En mettant vos fonds ..."

# Wallet version

1.3.0

**Comment by t00k** [comment]
Updated on Crowdin. Will be updated next time Firefly devs pull the translation strings and import them into Firefly.
Thanks for finding them!
