### ISSUE TITLE
I have 2 profiles and in each profile is my main account

### ISSUE THREAD

**Issue by PANDoGGA** [iotaledger/firefly#1838]
### Issue description

I have a ledger nano x which I used with my Trinity wallet. When migration was possible I tried to migrate my account. No I have profile 1 with my main account and 2 additional accounts. And i have profile 2, which appeared somehow after migration, which has also my main account included. Can I delete profile 2 without deleting my main account?

### Firefly version

1.3.0

### OS details

Windows 10

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

When I migrated my account from Trinity to Firefly for some reason the second profile appeard.

### Actual behaviour

I just have 2 profiles with my main acccount. I can receive and send iota from both profiles.

**Comment by MiKeF05** [comment]
The profile 2 is more or less the exact same copy of the profile 1. You can delete the profile in C:\Users\[User]\AppData\Roaming\Firefly\__storage__. But be careful to not delete the wrong profile. Maybe first create a backup of the folder before deleting it.
