### ISSUE TITLE
Profile with staked wallets shows blank UI

### ISSUE THREAD

**Issue by cashbrudi** [iotaledger/firefly#1843]
### Issue description

I've updated from Firefly version 1.2.0 to latest 1.3.0 and activated staking on all wallets in Profile 1. Then I exited Firefly via menu "Firefly / Quit". After reopening the app and logging in into Profile 1 I see a blank window. ~~When I reopen Firefly and log in to Profile 2 which has two wallets without staking the UI is displayed correctly.~~

![firefly-blank-window](https://user-images.githubusercontent.com/37546170/147006601-3be18aba-07e5-49a2-9f60-0e6a36acc031.png)

### Firefly version

1.3.0

### OS details

macOS Platform Version: 10.11.6 Platform Architecture: x64

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. open firefly
2. login to Profile which has staked wallets
3. starre at blank window with all wallets gone and try not to get a heart attack

### Expected behaviour

UI displays all wallets correctly

### Actual behaviour

blank window

### Errors

no error, nothing in error log

**Comment by MiKeF05** [comment]
@cashbrudi Does your issue persist?

**Comment by cashbrudi** [comment]
The issue may be related to incompatibility with old MacOS version (macOS Platform Version: 10.11.6 Platform Architecture: x64). Issue persists even after upgrading to v1.4.1 - though I've have to admin that I simply installed the new version over the old one without doing any cleanup in between. So may be the updated version would work if I did a proper cleanup - but I'm not aware of which folders and where to remove to do a clean install.

Other than that my personal issue is resolved since I was able to restore my wallet on  another machine with a more up-to-date MacOS version.

If you care about compatibility with MacOS 10.11.6 please provide instructions on how to conduct a clean installation (which old folders have to be removed, etc.?), I'd be happy to retest the installation then. Otherwise feel free to close this issue.
