### ISSUE TITLE
Delete Profile Not Working After New Profile Created

### ISSUE THREAD

**Issue by carpenterdev** [iotaledger/firefly#1845]
### Issue description

Migrated Ledger based funds from Trinity to Firefly 1.2 in Sep2021. This created Profile with 3 wallets, correctly. Amounts are correct. Got warning "Your funds will become available shortly". Still got warning after 1.3 update. In 1.3 added new Profile, using "Migrate or restore a wallet" | "I have a Ledger backup" | "I have a Firefly Ledger backup". The new profile was created, with same three wallets, and same amounts. Restarted Firefly, opened old Profile, it is still there with same warning. Under Settings clicked "Delete profile", got error  "You must transfer all balances before you can delete your profile". Got out of settings, opened one of wallets in old profile, clicked "Send funds" | "Internal Transfer". Expected dropdown to allow selection of new profile and one of it's wallets, but it only allows selection of one of the other wallets in the old profile.

### Firefly version

1.3.0

### OS details

Windows 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Create new profile.
2. Click "Migrate or restore a wallet"
3. Click "I have a Ledger backup"
4. Click ""I have a Firefly Ledger backup"
5. New profile is created, and has same three wallets as old profile, and wallets have same (correct) amounts.
6. Exit Firefly.
7. Open Firefly.
8. Click on the old profile and see that it still has same wallets, and amounts, that the new profile has. Plus the "unavailable funds warning"
9. Go to Settings, under Security, click "Delete profile". See error "You must transfer all balances before you can delete your profile".
 

### Expected behaviour

When new profile was created I expected that the balances in the old profile wallets would be zero, and that I could delete the old, empty, profile.

### Actual behaviour

Old profile wallets have same amounts as new profile wallets, and old profile cannot be deleted.

### Errors

![firefly_130_delete_profile_bug](https://user-images.githubusercontent.com/8070204/147017293-829be2f0-39c1-4e86-af85-99885036a31c.jpg)

**Comment by MiKeF05** [comment]
@carpenterdev  An internal transfer is only to send funds between the wallets inside a profile. Does this warning still appear? Did you connect your ledger and sync your wallet once again?
The reason why you can´t delete a profile is because you have a balance in this profile. But I guess this will change in the next version of Firefly.

**Comment by carpenterdev** [comment]
@MiKeF05 OK, I now understand use of "internal transfer".

Yes, warning still appears in the old profile. Yes, I have synced my wallet and restarted everything several times, except Win10, and still cannot delete old profile. The wallets in that old profile should be empty, since I created a new one, which now, is a duplicate of the old one.

I'll wait for next Firefly update. If it's still a problem I will reopen this issue.
Thanks.

**Comment by carpenterdev** [comment]
This problem still exists in v1.3.2 - two Identical profiles, each with three wallets, each matching wallet has same values in both profiles. Can't delete the old profile because its wallets aren't empty. Can't figure out how to make the old profile wallets empty.

**Comment by MiKeF05** [comment]
This was not fixed in the latest release. You can read the changelog. If you need to delete one profile immediately go to C:\users\ [user]\AppData\Roaming\Firefly\__storage__. In this folder should be your profiles and you can delete the one you don't use anymore.

**Comment by carpenterdev** [comment]
> This was not fixed in the latest release. You can read the changelog. If you need to delete one profile immediately go to C:\users\ [user]\AppData\Roaming\Firefly\storage. In this folder should be your profiles and you can delete the one you don't use anymore.

Thanks Mike. This worked. If this is published anywhere you might want to let people know that changing a profile folder name in the storage folder causes Firefly to delete it.

**Comment by MiKeF05** [comment]
Yes this is is normal because the storage folder should not be modified. But probably in the next version you are able to delete and change the profile name within Firefly.
