### ISSUE TITLE
password not correct

### ISSUE THREAD

**Issue by kuduthero** [iotaledger/firefly#1846]
### Issue description

i forgot my password... but i do have the phrase. how can i change my password using the phrase?

### Firefly version

1.3.0

### OS details

windows

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.password not correct
2.
3.
...

### Expected behaviour

password not correct. how to change password

### Actual behaviour

password not correct

**Comment by r-c-k** [comment]
You cannot change your password by using your passphrase but you can set up a new profile from the passphrase and chose a new password for that profile.

If you need further assistance contact me [@discord](https://discord.iota.org) (rck#3810).

**Comment by kuduthero** [comment]
i have created a new profile. but new and old profile didnot synced together... my iota is still in the old profile... should i transfer them to the new profile?

**Comment by r-c-k** [comment]
I can't answer your dm on discord, you need to accept my friend request or join the [IOTA Discord](https://discord.iota,org) first. Let's solve your issue there. :)

**Comment by kuduthero** [comment]
issue solved . Thanks to r-c-k.... now waiting to try staking since now having an issue with the staking nodes... will try again later
