### ISSUE TITLE
IOTA does not appear in firefly wallet

### ISSUE THREAD

**Issue by superzman1** [iotaledger/firefly#1850]
### Issue description

I did a transfer of IOTA to my wallet,

This transaction does not appear in firefly but does appear on Tangle Explorer. I've re-installed to 1.3 with a clean install, i've created a brand new profile with backup phrase, i've tried using balance finder, i've tried connecting to the Tangle Bay node https://mainnet-node.tanglebay.com, the funds still do not appear and were sent many days ago, thankyou for help. My total balance showing is NOT Correct.

Transaction ID:
42c85c174736f47211c32d661b47a68eca84a4e89f7cf9b579223618d2543159

### Firefly version

1.3

### OS details

Windows 10 Home 64-bit (10.0, Build 19043) (19041.vb_release.191206-1406)

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.	Login
2.	All settings
3.	Balance finder
4.	Find balance
5.	Search balance

### Expected behaviour

All transaction histories should show.

### Actual behaviour

Every other transaction log i've sent to the same address is there, just not this latest one

### Errors

Wed, 22 Dec 2021 10:15:47 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Mon, 13 Dec 2021 06:24:43 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Mon, 13 Dec 2021 06:24:42 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Mon, 13 Dec 2021 06:24:25 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Mon, 13 Dec 2021 06:24:24 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sat, 04 Dec 2021 06:44:21 GMT
ClientError: {}

Thu, 18 Nov 2021 08:48:22 GMT
ClientError: {}

Sat, 26 Jun 2021 09:12:35 GMT
ClientError: {}

Fri, 11 Jun 2021 12:04:02 GMT
ClientError: {}

**Comment by MiKeF05** [comment]
Hello,

can you try to uninstall your current Firefly installation and also delete the folder Firefly from C:\Users\[user]\AppData\Roaming\. After that please install Firefly 1.3.2 and try to restore your profile with your backup phrase.

**Comment by superzman1** [comment]
Thankyou, I've done this, my balance didnt change. It's possible the moneys there but the actual transaction history in firefly never updated. I'm happy to let it go, every other transaction ive sent to the exact same wallet adress has landed. Is there anything else I could possibly try?

**Comment by MiKeF05** [comment]
And the total balance of your profile is not correct?

**Comment by superzman1** [comment]
Apologies, ive tallied all the transactions and yes the total balance is correct, the transaction history in firefly just didnt record that 1 transaction, thankyou
