### ISSUE TITLE
LatestAccountIsEmpty on wallet creation

### ISSUE THREAD

**Issue by rbachlec** [iotaledger/firefly#1855]
### Issue description

I already have 2 wallets under my profile (Ledger). Both wallets have balance > 0 and at least two history entries.
If I try to create a third wallet I just get this message:

LatestAccountIsEmpty: can't create accounts when the latest account doesn't have message history and balance

### Firefly version

1.3.0

### OS details

Windows 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Open Profile
2. Click 'Plus' (create wallet)
3. Enter wallet name
4. Click button 'Create'

### Expected behaviour

A new wallet should be created

### Actual behaviour

Getting error message that last wallet has to be used first

### Errors

LatestAccountIsEmpty: can't create accounts when the latest account doesn't have message history and balance

**Comment by MiKeF05** [comment]
Which node are you connected to?

**Comment by rbachlec** [comment]
https://chrysalis-nodes.iota.cafe

But it does not seem to make any difference which node I'm connected to.

**Comment by MiKeF05** [comment]
Have you tried to change the node to 
https://mainnet-node.tanglebay.com

**Comment by rbachlec** [comment]
Ok I recreated the profile and now it works. Thank you.

**Comment by MiKeF05** [comment]
Okay great. Issue can be closed
