### ISSUE TITLE
my stakes are invisible in my wallet

### ISSUE THREAD

**Issue by ercankuruz** [iotaledger/firefly#1856]
### Issue description

my stakes are invisible in my wallet. I've started the staking, but now it is saying that " 0 mi staked"

### Firefly version

1.3.0

### OS details

mac

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

wallet is nor working properly

### Actual behaviour

wallet is not working properly

**Comment by r-c-k** [comment]
Probably just a network error. You can try temporarily changing your node to `https://mainnet-node.tanglebay.com/`.

**Comment by Rafa1981** [comment]
Thanks, I have the same problem, can you explain who to change the node?

**Comment by r-c-k** [comment]
Settings - Advanced Settings - Network configuration - Set Node selection to manual - Add node.
Make sure to set it as primary.

**Comment by Rafa1981** [comment]
Thanks a lot r-c-k

**Comment by ercankuruz** [comment]
> Settings - Advanced Settings - Network configuration - Set Node selection to manual - Add node. Make sure to set it as primary.

thanks, now I can see the stakes.

**Comment by r-c-k** [comment]
Glad it helped. 👍 Issue can be closed then @ercankuruz.

**Comment by ercankuruz** [comment]
Hi,  

Again I’ve same problem, Please find attached screen shot.



Best Regards,
 
Huseyin Ercan KURUZ | Certifying Engineer
m. +971 (0)58 891 1633
***@***.*** | flydubai.com

**Comment by ercankuruz** [comment]
Again I've same problem

![Screen Shot 2021-12-26 at 11 16 21 PM](https://user-images.githubusercontent.com/94834098/147418005-78e636be-a4ca-4788-b8c7-833b00608095.png)
![Screen Shot 2021-12-26 at 11 16 05 PM](https://user-images.githubusercontent.com/94834098/147418015-501620f3-e648-4eeb-8859-174ef3b85b8d.png)
