### ISSUE TITLE
Duplicate iota staking funds transaction

### ISSUE THREAD

**Issue by cryp-to-dev** [iotaledger/firefly#1858]
### Issue description

I tried the new pre-staking functionality and it let me transfer 2 times the amoun of IOTA I had in this moment I had 1Gi and Firefly let me 2 transaction of 1Gi each one.
![image](https://user-images.githubusercontent.com/21373478/147171448-888801c8-a632-4c02-9e0e-032fea9ef4b0.png)

### Firefly version

1.3.0

### OS details

Windows 10 Pro

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Open the staking tab
2. Accept the info and conditions of the staking
3. Send funds to staking
4. Close the confirmation screen fast.
5. And request to sed funds to staking again.
...

### Expected behaviour

The second transaction should be rejected because you don't have enough funds.

### Actual behaviour

It will put two transactions in the in your transaction history, the amount of staked funds will be correct just the available funds as max, but in the history it will looks like 2 transactions.

**Comment by MiKeF05** [comment]
If you logout and login to the profile and sync your wallet does the issue persist?

**Comment by dlt-green** [comment]
yes, i also can reproduce it, when you start firefly and if you are fast enough to push the staking button bevor the wallet recognize the staking, you can make it more then once

https://user-images.githubusercontent.com/89119285/147379882-32ff3ebb-445e-40ee-af20-f08e05bf5046.mp4

.

**Comment by netraptor86** [comment]
> If you logout and login to the profile and sync your wallet does the issue persist?

Yes, I have the 2 transactions even I not have the enough Miotas to complete the 2 transactions.
