### ISSUE TITLE
Iota Migration - Error at last step

### ISSUE THREAD

**Issue by bruno0102** [iotaledger/firefly#1859]
### Issue description

The Migration of Iota from Ledger is not working at the last step: it finds the Iota on the Ledger, after clicking on the Button to start Migration a error massage appears.
Every Update is done

### Firefly version

1.3.0

### OS details

Windows 10.0.22000 Build 22000

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Follow the steps to Migrate Iota from the Ledger into the new network at Firefly.
2.
3.
...

### Expected behaviour

To solve the Problem, that Iota can be transferred into the new network.

### Actual behaviour

It is not possible to react on the error message.

**Comment by r-c-k** [comment]
Please try installing Firefly 1.2 [https://github.com/iotaledger/firefly/releases/tag/desktop-1.2.0](https://github.com/iotaledger/firefly/releases/tag/desktop-1.2.0) to do the migration. Afterwards you can upgrade to 1.3 again.

**Comment by Ralf121212** [comment]
Thank you very much,

i had exactly the problem! With firefly version 1.3.0 it was not possible to migrate my funds from my trinty wallet to the new firefly wallet. After deinstalling firefly version 1.3.0 and installing 1.2.0. The entire migration process worked without a problem.

I have been tring for 2 days and it almost drove me cracy.

Thany you so much for your help!

**Comment by CodeLarkin** [comment]
> Please try installing Firefly 1.2 https://github.com/iotaledger/firefly/releases/tag/desktop-1.2.0 to do the migration. Afterwards you can upgrade to 1.3 again.

This was a huge help. Thank you! Temporarily reverting to Firefly 1.2 for the migration did the trick.

**Comment by bruno0102** [comment]
Thanks for the help!!! =)

Richard K. ***@***.***> schrieb am Do., 23. Dez. 2021, 07:28:

**Comment by r-c-k** [comment]
Issue can be closed then @bruno0102

**Comment by Fredi009sg** [comment]
I haven't done anything since 2 years with my iota. Now I tried to migrate to the new network structure but I won't pass the migration step. Always shown that the migration failed. 

Have another of the experts any suggestions?
