### ISSUE TITLE
password not correct

### ISSUE THREAD

**Issue by RafaelEscudero** [iotaledger/firefly#1863]
### Issue description

I forgot my password but I have the PIN and the seed. I need to backup the wallet but I need the password for everything, also to delate the profile, because I have MIOTA and, to delate the profile, your wallet has to be empty, and you need the password to send money.

Please, anyone know how to recover the profile with the seed? 

I was waiting for the staking much time  :)

### Firefly version

1.3.0

### OS details

windows

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. password not correct
2.
3.
...

### Expected behaviour

Recover the password to stake my IOTA

### Actual behaviour

password not correct

### Errors

I need the password to backup the wallet? I need to backup the wallet by using the seed because I lost my password....

**Comment by r-c-k** [comment]
Please contact me at the [IOTA Discord](https://discord.iota.org) (rck#3810), we'll resolve your issue there. Github is not the right place for this.

**Comment by RafaelEscudero** [comment]
Thanks for your time, I've already sent a friend request there.

**Comment by RafaelEscudero** [comment]
Thanks to rck the issue is resolved. Thanks!!
