### ISSUE TITLE
Keine coins in der Wallet

### ISSUE THREAD

**Issue by JempM** [iotaledger/firefly#1865]
Hallo, ich habe gestern meine coins von Bitpanda auf die Firefly gesendet, und dort kamen sie nie an?
Ich habe bei Bitpanda nachgefragt, und die bestätigten mir dass die coins versendet wurden.

Mfg

Jemp

**Comment by r-c-k** [comment]
Fängt deine Adresse mit "iota" oder "atoi" an? Hast du schon im auf [https://explorer.iota.org](https://explorer.iota.org) nachgeschaut, ob die Token auf der Adresse angekommen sind (confirmed)?

**Comment by JempM** [comment]
atoi

**Comment by r-c-k** [comment]
Dann hast du beim erstellen des Profils "Entwicklerprofil" ausgewählt. "atoi"-Adressen sind Testnet-Adressen. Bitpanda hätte das erkennen müssen, da Token über das Mainnet nicht an Testnetadressen gesendet werden können. Wende dich dort bitte mal an den Support, gerne auch mit verweis auf diesen Thread hier.

**Comment by JempM** [comment]
ich weiss auch nicht wie ich das auf explorer.iota nachschauensoll? Habe jetzt mal dort die Adresse meiner Wallet eingegeben?
Und dann kommt folgendes: We could not find any messages, addresses, outputs, milestones or indexes for the query.

**Comment by r-c-k** [comment]
Ja weil es diese Adresse im Mainnet nicht gibt. Du kannst diese Wallet nicht benutzen wenn du deine Token in Firefly haben möchtest. Kontaktieren mich bitte mal auf [Discord](https://discord.iota.org) (rck#3810).

**Comment by JempM** [comment]
Die sagten mir versendete coins sind weg, und die bekommt man nicht zurÜck. Wo sind die denn jetzt hin?

**Comment by r-c-k** [comment]
Die können nicht versendet sein weil die Adresse im Mainnet nicht gültig ist. Bitte ab jetzt Discord.

**Comment by r-c-k** [comment]
@JempM Ich habe grade gesehen dass Bitpanda den hrp von "atoi" auf "iota" ändert und die Token dann versendet. Du kannst demnach einfach ein neues Profil mit deiner Passphrase/Ledger/Stringhold Backup erstellen (wiederherstellen), lässt den Haken bei "Entwicklerprofil" weg, und solltest dann deine Token sehen.

**Comment by JempM** [comment]
@r-c-k  Vielen Dank. Das wäre super. Aber wie erstelle ich ein neues Profil? Das alte löschen, dann ein neues?

**Comment by JempM** [comment]
Ich brauche ja danach wieder dieselbe Walletadresse?

**Comment by r-c-k** [comment]
Du musst das alte erstmal nicht löschen. Logge dich aus, dann "Profil hinzufügen" - Entwicklerprofil NICHT auswählen - Wallet migrieren oder wiederherstellen - dann dein Backup wählen.

**Comment by JempM** [comment]
@r-c-k Es hat geklappt. Alle coins sind da. Vielen vielen DANK für ihre Hilfe.

**Comment by r-c-k** [comment]
Gerne. Issue kann dann geschlossen werden :)
