### ISSUE TITLE
Firefly doubled my funds ;) [visual bug]

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/firefly#1866]
### Issue description

I somehow made firefly double my funds. 

### Firefly version

1.3.0

### OS details

macOS Monterey 12.0.1

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

Only seems to be reproducable with a specific node from a community member. I can DM you the url if needed.

1. Add specific Node url to firefly
2. Reload balance
3. Doubled your funds
4. Enjoy

### Expected behaviour

Firefly shouldn't double my funds (sadly 😞  )

### Actual behaviour

But it does :trollface:

**Comment by MiKeF05** [comment]
This should be fixed.
