### ISSUE TITLE
Can't connect to network

### ISSUE THREAD

**Issue by SebLane** [iotaledger/firefly#1868]
No network connection.

**Comment by SebLane** [comment]
![image](https://user-images.githubusercontent.com/96590037/147272810-e4e4fa7f-6d47-4656-95e8-1d818f509bf3.png)

**Comment by MiKeF05** [comment]
Do you use a work computer or a VPN?

**Comment by SebLane** [comment]
yes work pc with vpn

**Comment by MiKeF05** [comment]
Then that´s the problem. Something on your work PC doesn´t allow a connection to the node. So I think you need to change the computer

**Comment by Aenimaniac** [comment]
Can anybody tell me how to connect my Hornet node to Firefly? Something goes wrong if I add https://"my ipadress"

**Comment by MiKeF05** [comment]
What´s the exact error message?

**Comment by Aenimaniac** [comment]
> What´s the exact error message?

"Something went wrong".

I enter https://myipadress

**Comment by MiKeF05** [comment]
Do you use a SSL certificate for your node? I think you also may need a public domain to connect your node with Firefly.
