### ISSUE TITLE
Error when trying to stake

### ISSUE THREAD

**Issue by DPF64** [iotaledger/firefly#1869]
### Issue description

App Version: 1.3.0

platform: win32
platformVersion: 10.0.19041
platformArchitecture: x64
cpuCount: 6
totalMem: 15742.2 MB
freeMem: 8155.5 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NAME_NOT_RESOLVED

### Firefly version

1.3.0

### OS details

Windows 10 Pro

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1. I want to be able to stake but I have a message saying staking not detected
2.
3.
...

### Expected behaviour

I want to be able to stake

### Actual behaviour

Staking not detected

### Errors

App Version: 1.3.0

platform: win32
platformVersion: 10.0.19041
platformArchitecture: x64
cpuCount: 6
totalMem: 15742.2 MB
freeMem: 8155.5 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NAME_NOT_RESOLVED

**Comment by MiKeF05** [comment]
Can you try to temporarily turn off your firewall? Would also be worth to try to run Firefly as admin

**Comment by MiKeF05** [comment]
@DPF64 Were you able to solve your issue?

**Comment by DPF64** [comment]
Yes.  Thank you very much.
It was our firewall that was causing the problem.

Donald P Flanagan
Partner
HFK McRae & Wilson
630 Riverbend Drive, Suite 100
Kitchener, Ontario  N2K 3S2
Phone 519-886-0084 x215
Fax 519-886-8095

[hfkmw6]
