### ISSUE TITLE
software stop at second pin during profile setup

### ISSUE THREAD

**Issue by jacopotolja** [iotaledger/firefly#1871]
### Issue description

Download the appimage, controlled the sha and positive match.
setup the profile but at the second screen when I place the confirmation pin (only numeric) the software does not advance.

### Firefly version

1.3.0

### OS details

Operating System: MXLinux Debian GNU/Linux 11 KDE Plasma Version: 5.20.5 KDE Frameworks Version: 5.78.0 Qt Version: 5.15.2 Kernel Version: 5.10.0-9-amd64 OS Type: 64-bit Processors: 4 × Intel® Core™ i7-6560U CPU @ 2.20GHz Memory: 15.2 GiB of RAM Graphics Processor: Mesa Intel® Iris® Graphics 540

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. I follow the step
2. as i get to the second screen of the pin number
3. after I write the 6 pin for the second time
4. the button on the lower left side activate but as it pressed does not forward the program to the next step (I don't know what to expect)
5. 
![image](https://user-images.githubusercontent.com/5058359/147284824-4c73e63f-bbd2-40fc-9745-9f42221f4e42.png)

...

### Expected behaviour

To see the next step in the profile creation

### Actual behaviour

Nothing happens

### Errors

No error reported

**Comment by MiKeF05** [comment]
Make sure to install gnome keyring

**Comment by jacopotolja** [comment]
it worked
