### ISSUE TITLE
Migration error when in STEP 4 (Transfering Funds)

### ISSUE THREAD

**Issue by Equol29** [iotaledger/firefly#1874]
Hey... 

I am doing the migration to Chrisalys from my Ledger (Trinity) - The process goes smoothly till step 4 when it always tells me that something went wrong but no idea what might be the problem. I see my funds (IOTA Legacy App) but when it gets to transfer to the new Wallet (in ledger) then it breaks. 

Someone´s help much appreciated

**Comment by MiKeF05** [comment]
Please use Firefly 1.2 for the migration. After the migration you can update again to 1.3.

**Comment by Equol29** [comment]
> Please use Firefly 1.2 for the migration. After the migration you can update again to 1.3. Here is the link for 1.2: https://github.com/iotaledger/firefly/releases/tag/desktop-1.2.0

Thanks MiKe

**Comment by MiKeF05** [comment]
@Equol29 Quick question did you select the "Developer Profile" when you set up your profile?

**Comment by Equol29** [comment]
Hey Mike...

No I didn´t... why?... should I have done that?... It worked for me as you suggested.

**Comment by MiKeF05** [comment]
@Equol29 No everything is okay. You may not use the developer profile for the mainnet 😉 All good
