### ISSUE TITLE
Can't create a second wallet in Firefly 1.3

### ISSUE THREAD

**Issue by mownarch** [iotaledger/firefly#1876]
### Issue description

It says:
Fri, 24 Dec 2021 07:17:54 GMT
LatestAccountIsEmpty: can't create accounts when the latest account doesn't have message history and balance

I did create once a second wallet, which I then deleted again without using it. It seems as this wallet is still somewhat known within the app (but not displayed) which is forbidding me to create a new wallet.

The option "Show hidden wallets" is checked.

### Firefly version

1.3

### OS details

Win 10 Pro

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

My guess:
1. Create 2nd Wallet in Firefly
2. Delete 2nd Wallet
3. Create 2nd Wallet
...

### Expected behaviour

New wallet shall be created and accessible

### Actual behaviour

LatestAccountIsEmpty: can't create accounts when the latest account doesn't have message history and balance

### Errors

LatestAccountIsEmpty: can't create accounts when the latest account doesn't have message history and balance

**Comment by MiKeF05** [comment]
Can you try to uncheck and check "Show hidden wallets" again?

**Comment by mownarch** [comment]
Hi.
I also tried that.

**Comment by MiKeF05** [comment]
Did you also have this profile with Firefly 1.2?

**Comment by mownarch** [comment]
Yes, I am using this profile for a while now and updated to 1.3 when it got released.

**Comment by MiKeF05** [comment]
Was resolved with the latest version 1.3.2 and by restoring with the stronghold backup. Issue can be closed.
