### ISSUE TITLE
Staking issue

### ISSUE THREAD

**Issue by AjayanN** [iotaledger/firefly#1877]
### Issue description

I staked all my iota once on 21st, Now today I am still receiving the button for stake funds and I tried to stake it again, The result is this. I literally am able to stake it again. I fear that, in future dates, would it automatically again close my staked message and ask again to restake, which would cause an issue in a reduction in the percentage of rewards received
![image](https://user-images.githubusercontent.com/52562205/147348067-70fb8f83-747d-4b5f-ad5b-528167859b1c.png)

### Firefly version

1.3.0

### OS details

Windows 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Open firefly
2. The stake button is not enabled at the time, then it suddenly turns blue and shows that you have not staked in shimmer and assembly card
3. asks to stake again,

### Expected behaviour

staked and loaded. Atleast there should not be the stake funds button still in blue if once the message is already transferred

### Actual behaviour

Described in the description

### Errors

The message ids on both are different so, It's like the previous staking transaction was not even done.

**Comment by MiKeF05** [comment]
Have you sent funds while the staking was active?

**Comment by AjayanN** [comment]
Nope, I have not.

**Comment by MiKeF05** [comment]
Hm that's strange. Once it is staked it should be staked. Maybe this was due to a very high API load of the nodes.

**Comment by AjayanN** [comment]
Is there a roundabout on this issue other than to just wait until the node gets connected perfectly and the already staked message transaction is caught? I am now using the node from tanglebay solely due to this issue was caused on the already provided nodes.

**Comment by MiKeF05** [comment]
I think with the next release there will be more nodes in the automatic node selection. With this fix the connection management to a node should be more reliable.

**Comment by AjayanN** [comment]
Thanks for the response.

**Comment by r-c-k** [comment]
Sounds like a network/node issue. Have you already tried adding the tanglebay node? You should be fine in any case though…
