### ISSUE TITLE
password not accepted

### ISSUE THREAD

**Issue by waterloochris** [iotaledger/firefly#1878]
### Issue description

firefly will not accept my password. every letter has been checked and rechecked. 

### Firefly version

1.3.0

### OS details

windows 

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.enter password
2.enter password
3.enter password
...

### Expected behaviour

accept password

### Actual behaviour

incorrect password entered

**Comment by r-c-k** [comment]
Please join the [IOTA Discord](https://discord.iota.org) if you need assistance with this issue (visit the #help channel). You can also contact me via direct message if you want (rck#3810).

Please never share your seed, passphrase or any kind of sensitive information with **anyone**.

**Comment by MiKeF05** [comment]
@waterloochris Were you able to solve your issue?

**Comment by waterloochris** [comment]
Hello thanks for reaching out. no the problem is still there. when i try to stake my coins my password is not accepted. im sure its the correct password. so then i tried to create a new profile in firefly but one of my recovery phrases is not accepted. thats where im at

**Comment by MiKeF05** [comment]
You mean one of the words in your recovery phrase is not accepted?

**Comment by waterloochris** [comment]
thank you
