### ISSUE TITLE
wallet not open

### ISSUE THREAD

**Issue by Shabby007** [iotaledger/firefly#1879]
### Issue description

i install wallet but it not opening showing some error.

### Firefly version

1.3.0

### OS details

window 7 i5, 64 bit lenova

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...
wyddie duh

### Expected behaviour

its need work

### Actual behaviour

pl

### Errors

App Version: 1.3.0

platform: win32
platformVersion: 6.1.7601
platformArchitecture: x64
cpuCount: 4
totalMem: 4016.2 MB
freeMem: 1106.7 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_TIMED_OUT

**Comment by r-c-k** [comment]
Windows 7 is not supported since it officially reached its end-of-life in January 14, 2020.
