### ISSUE TITLE
unfortunately an error occured

### ISSUE THREAD

**Issue by Tunchie522** [iotaledger/firefly#1880]
App Version: 1.3.0

platform: win32
platformVersion: 6.3.9600
platformArchitecture: x64
cpuCount: 4
totalMem: 4016.7 MB
freeMem: 959.6 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_CONNECTION_RESET

**Comment by perandre** [comment]
This bug is a duplicate of https://github.com/iotaledger/firefly/issues/1127
