### ISSUE TITLE
transaktion history for staking in firefly

### ISSUE THREAD

**Issue by dlt-green** [iotaledger/firefly#1881]
### Issue description

When you stake, you find after that a info in the transaktion history with "für Wallet 1 gestaked", when you unstake, there should be a info with "für Wallet 1 nicht mehr gestaked", but it is only shown as a "Gesendet von Wallet 1".

### Firefly version

1.3.0

### OS details

Windows 11

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. stake
2. unstake

### Expected behaviour

when you unstakte, there should be a info with "für Wallet 1 nicht mehr gestaked"

### Actual behaviour

when you unstakte, there is only shown "Gesendet von Wallet 1"

### Errors

[](url
![Unbenannt](https://user-images.githubusercontent.com/89119285/147379540-4bf4261d-babd-40eb-abde-1b874166f45f.png)
)

**Comment by cvarley100** [comment]
The unstaking transaction is no different to a regular send. We don't currently plan on fixing this.
