### ISSUE TITLE
Iota Staking Verwaltung - Button inaktiv

### ISSUE THREAD

**Issue by Schnait** [iotaledger/firefly#1883]
### Issue description

Staking Verwaltung kann nicht synchronisiert werden - der Button ist nicht aktiv.
Guthaben wird gezeigt - aber kein Staking start ist möglich. 

### Firefly version

V1.3.0

### OS details

Win 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

eine Löschung meines Problems

### Actual behaviour

schon öfters versucht -

**Comment by r-c-k** [comment]
Erstelle mal ein neues Profil indem du aus deinem Backup (Ledger oder Passphrase) wiederherstellst.
Ansonsten für Fragen und Probleme am besten dem IOTA Discord ([https://discord.iota.org](https://discord.iota.org)) beitreten. GitHub ist für sowas weniger geeignet.

**Comment by MiKeF05** [comment]
@Schnait Konntest du das Problem lösen?

**Comment by cvarley100** [comment]
Fixed in 1.3.1
