### ISSUE TITLE
Firefly doesnt recognize the address for my wallet

### ISSUE THREAD

**Issue by hatmaserat** [iotaledger/firefly#1884]
### Issue description

i tried to send a small amount of MIOTA to nano x to test firefly. the first transaction arrived and firefly shows me that but for the second transaction it says i received nothing. although in explorer i can see the amount is there. 

![image](https://user-images.githubusercontent.com/96664500/147392175-ba4ec1ab-71cb-476c-96ff-271f5ff70953.png)

![image](https://user-images.githubusercontent.com/96664500/147392184-b2edd487-404b-4e48-b53a-eed8d6a84179.png)

![image](https://user-images.githubusercontent.com/96664500/147392189-01c91da5-4982-4160-a8f0-851890dde937.png)

I already disconnected my ledger and connected it again and synched it and it still says i received 0.
i also turned off VPN and still the same issue.
I´ve also changed the node to https://mainnet-node.tanglebay.com and set it as primary node and still the same issue.

In my error log it says:

Sat, 25 Dec 2021 19:22:34 GMT
ReqwestError: error sending request for url (https://mainnet-node.tanglebay.com/api/plugins/participation/addresses/iota1qz5reedzkezru03v6gwnvt4l05ju4wtszpr4g57htyysyqk6ewwpgek7wng): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 19:18:29 GMT
LedgerDongleLocked: ledger locked

Sat, 25 Dec 2021 19:03:35 GMT
ReqwestError: error sending request for url (https://mainnet-node.tanglebay.com/api/plugins/participation/addresses/iota1qrjhs639fynryytkxuggmq4gx9p3crgcv7ht5eqqjy0cgcygrqk8g62sxcr): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 19:03:05 GMT
ReqwestError: error sending request for url (https://mainnet-node.tanglebay.com/api/plugins/participation/addresses/iota1qrjhs639fynryytkxuggmq4gx9p3crgcv7ht5eqqjy0cgcygrqk8g62sxcr): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 18:57:01 GMT
ReqwestError: error sending request for url (https://mainnet-node.tanglebay.com/api/plugins/participation/addresses/iota1qrjhs639fynryytkxuggmq4gx9p3crgcv7ht5eqqjy0cgcygrqk8g62sxcr): error trying to connect: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. (os error 10054)

Sat, 25 Dec 2021 18:54:38 GMT
ReqwestError: error sending request for url (https://mainnet-node.tanglebay.com/api/plugins/participation/addresses/iota1qqhk2z35dvwmxxk99ytkx8tlumgjnhamt72dvf245zaux8xf629kc9dj8k5): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 18:23:48 GMT
LedgerMiscError: ledger transport error

Sat, 25 Dec 2021 18:15:25 GMT
LedgerDongleLocked: ledger locked

Sat, 25 Dec 2021 18:05:09 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqhk2z35dvwmxxk99ytkx8tlumgjnhamt72dvf245zaux8xf629kc9dj8k5): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 17:54:12 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqhk2z35dvwmxxk99ytkx8tlumgjnhamt72dvf245zaux8xf629kc9dj8k5): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 17:53:10 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qz5reedzkezru03v6gwnvt4l05ju4wtszpr4g57htyysyqk6ewwpgek7wng): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 17:44:19 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqhk2z35dvwmxxk99ytkx8tlumgjnhamt72dvf245zaux8xf629kc9dj8k5): error trying to connect: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. (os error 10054)

Sat, 25 Dec 2021 17:39:49 GMT
LedgerDongleLocked: ledger locked

Sat, 25 Dec 2021 17:38:19 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qzn5wx9xjy7ulpgfvz7368ushu5vgc693w7t3hp7c2l8dx8sfu9dzufll0w): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 17:37:50 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qz5reedzkezru03v6gwnvt4l05ju4wtszpr4g57htyysyqk6ewwpgek7wng): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 17:36:49 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qzn5wx9xjy7ulpgfvz7368ushu5vgc693w7t3hp7c2l8dx8sfu9dzufll0w): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 17:26:08 GMT
LedgerDeviceNotFound: ledger device not found

Sat, 25 Dec 2021 17:24:52 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqhk2z35dvwmxxk99ytkx8tlumgjnhamt72dvf245zaux8xf629kc9dj8k5): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 17:23:04 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qz5reedzkezru03v6gwnvt4l05ju4wtszpr4g57htyysyqk6ewwpgek7wng): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 17:23:04 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqhk2z35dvwmxxk99ytkx8tlumgjnhamt72dvf245zaux8xf629kc9dj8k5): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 17:22:03 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qz5reedzkezru03v6gwnvt4l05ju4wtszpr4g57htyysyqk6ewwpgek7wng): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 17:21:02 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qrjhs639fynryytkxuggmq4gx9p3crgcv7ht5eqqjy0cgcygrqk8g62sxcr): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 17:14:56 GMT
LedgerDeviceNotFound: ledger device not found

Sat, 25 Dec 2021 17:14:42 GMT
LedgerDeviceNotFound: ledger device not found

Fri, 24 Dec 2021 17:13:59 GMT
LedgerMnemonicMismatch: ledger mnemonic is mismatched

Fri, 24 Dec 2021 17:13:39 GMT
LedgerMnemonicMismatch: ledger mnemonic is mismatched

Fri, 24 Dec 2021 17:05:57 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qzn5wx9xjy7ulpgfvz7368ushu5vgc693w7t3hp7c2l8dx8sfu9dzufll0w): error trying to connect: tls handshake eof

Fri, 24 Dec 2021 16:58:47 GMT
LedgerDeviceNotFound: ledger device not found

Fri, 24 Dec 2021 12:54:24 GMT
LedgerDeviceNotFound: ledger device not found

Fri, 24 Dec 2021 05:25:01 GMT
LedgerMiscError: ledger transport error

Fri, 24 Dec 2021 05:25:01 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/events): error trying to connect: tls handshake eof

Fri, 24 Dec 2021 05:18:29 GMT
LedgerDongleLocked: ledger locked

Fri, 24 Dec 2021 05:16:20 GMT
LedgerDongleLocked: ledger locked

Thu, 23 Dec 2021 21:38:49 GMT
LedgerMiscError: ledger transport error

What am I doing wrong?

### Firefly version

1.3.0

### OS details

Microsoft Windows 11 Home

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

see issue description

### Actual behaviour

see issue description

### Errors

Sat, 25 Dec 2021 19:22:34 GMT
ReqwestError: error sending request for url (https://mainnet-node.tanglebay.com/api/plugins/participation/addresses/iota1qz5reedzkezru03v6gwnvt4l05ju4wtszpr4g57htyysyqk6ewwpgek7wng): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 19:18:29 GMT
LedgerDongleLocked: ledger locked

Sat, 25 Dec 2021 19:03:35 GMT
ReqwestError: error sending request for url (https://mainnet-node.tanglebay.com/api/plugins/participation/addresses/iota1qrjhs639fynryytkxuggmq4gx9p3crgcv7ht5eqqjy0cgcygrqk8g62sxcr): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 19:03:05 GMT
ReqwestError: error sending request for url (https://mainnet-node.tanglebay.com/api/plugins/participation/addresses/iota1qrjhs639fynryytkxuggmq4gx9p3crgcv7ht5eqqjy0cgcygrqk8g62sxcr): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 18:57:01 GMT
ReqwestError: error sending request for url (https://mainnet-node.tanglebay.com/api/plugins/participation/addresses/iota1qrjhs639fynryytkxuggmq4gx9p3crgcv7ht5eqqjy0cgcygrqk8g62sxcr): error trying to connect: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. (os error 10054)

Sat, 25 Dec 2021 18:54:38 GMT
ReqwestError: error sending request for url (https://mainnet-node.tanglebay.com/api/plugins/participation/addresses/iota1qqhk2z35dvwmxxk99ytkx8tlumgjnhamt72dvf245zaux8xf629kc9dj8k5): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 18:23:48 GMT
LedgerMiscError: ledger transport error

Sat, 25 Dec 2021 18:15:25 GMT
LedgerDongleLocked: ledger locked

Sat, 25 Dec 2021 18:05:09 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqhk2z35dvwmxxk99ytkx8tlumgjnhamt72dvf245zaux8xf629kc9dj8k5): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 17:54:12 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqhk2z35dvwmxxk99ytkx8tlumgjnhamt72dvf245zaux8xf629kc9dj8k5): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 17:53:10 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qz5reedzkezru03v6gwnvt4l05ju4wtszpr4g57htyysyqk6ewwpgek7wng): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 17:44:19 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqhk2z35dvwmxxk99ytkx8tlumgjnhamt72dvf245zaux8xf629kc9dj8k5): error trying to connect: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. (os error 10054)

Sat, 25 Dec 2021 17:39:49 GMT
LedgerDongleLocked: ledger locked

Sat, 25 Dec 2021 17:38:19 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qzn5wx9xjy7ulpgfvz7368ushu5vgc693w7t3hp7c2l8dx8sfu9dzufll0w): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 17:37:50 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qz5reedzkezru03v6gwnvt4l05ju4wtszpr4g57htyysyqk6ewwpgek7wng): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 17:36:49 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qzn5wx9xjy7ulpgfvz7368ushu5vgc693w7t3hp7c2l8dx8sfu9dzufll0w): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 17:26:08 GMT
LedgerDeviceNotFound: ledger device not found

Sat, 25 Dec 2021 17:24:52 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqhk2z35dvwmxxk99ytkx8tlumgjnhamt72dvf245zaux8xf629kc9dj8k5): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 17:23:04 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qz5reedzkezru03v6gwnvt4l05ju4wtszpr4g57htyysyqk6ewwpgek7wng): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 17:23:04 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qqhk2z35dvwmxxk99ytkx8tlumgjnhamt72dvf245zaux8xf629kc9dj8k5): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 17:22:03 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qz5reedzkezru03v6gwnvt4l05ju4wtszpr4g57htyysyqk6ewwpgek7wng): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 17:21:02 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qrjhs639fynryytkxuggmq4gx9p3crgcv7ht5eqqjy0cgcygrqk8g62sxcr): error trying to connect: tls handshake eof

Sat, 25 Dec 2021 17:14:56 GMT
LedgerDeviceNotFound: ledger device not found

Sat, 25 Dec 2021 17:14:42 GMT
LedgerDeviceNotFound: ledger device not found

Fri, 24 Dec 2021 17:13:59 GMT
LedgerMnemonicMismatch: ledger mnemonic is mismatched

Fri, 24 Dec 2021 17:13:39 GMT
LedgerMnemonicMismatch: ledger mnemonic is mismatched

Fri, 24 Dec 2021 17:05:57 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qzn5wx9xjy7ulpgfvz7368ushu5vgc693w7t3hp7c2l8dx8sfu9dzufll0w): error trying to connect: tls handshake eof

Fri, 24 Dec 2021 16:58:47 GMT
LedgerDeviceNotFound: ledger device not found

Fri, 24 Dec 2021 12:54:24 GMT
LedgerDeviceNotFound: ledger device not found

Fri, 24 Dec 2021 05:25:01 GMT
LedgerMiscError: ledger transport error

Fri, 24 Dec 2021 05:25:01 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/events): error trying to connect: tls handshake eof

Fri, 24 Dec 2021 05:18:29 GMT
LedgerDongleLocked: ledger locked

Fri, 24 Dec 2021 05:16:20 GMT
LedgerDongleLocked: ledger locked

Thu, 23 Dec 2021 21:38:49 GMT
LedgerMiscError: ledger transport error

**Comment by MiKeF05** [comment]
Hello,

I think this problem is due to firewall restrictions or something else on your computer. As you see there are request errors and TLS handshake issues. You can try to temporarily disable your firewall or use another network.

**Comment by hatmaserat** [comment]
but why there were no issues with the transaction before? (which i made with the same device and with VPN)
![image](https://user-images.githubusercontent.com/96664500/147394981-ab19364c-2a13-4779-b577-6838b91684ea.png)
i did that transaction one day before and it went through without any problems.

**Comment by hatmaserat** [comment]
i tried it without VPN and the transaction still says 0 and doenst recognize it for Wallet 1

**Comment by hatmaserat** [comment]
thank you MikeF05 (problem solved)
