### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by Mist972** [iotaledger/firefly#1885]
### Issue description

Hello, after entering my code, I have a white screen and I do not have access to my wallet. I connect with a ledger. It has already worked very well.
Thank you for your help.

### Firefly version

1.3.0

### OS details

Mac 10.11.6

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

- 

### Actual behaviour

-

**Comment by r-c-k** [comment]
Delete the Firefly folder from ~/Library/Application Support/Firefly and then start Firefly again. You‘ll need to recover from your Ledger in the profile setup process.

**Comment by Mist972** [comment]
Ok Thx ! I'll try



Le sam. 25 déc. 2021 à 21:29, Richard K. ***@***.***> a
écrit :

**Comment by MiKeF05** [comment]
@Mist972 Were you able to resolve your issue?

**Comment by cvarley100** [comment]
You need to update your Mac OS.
