### ISSUE TITLE
Firefly migration funds does not work

### ISSUE THREAD

**Issue by dsx5000** [iotaledger/firefly#1886]
### Issue description

On latest Firefly to migrate iota from ledger old trinity to new network is working until showing the right balance.
Then it does not ask to create new password as written in discription. Is directly ask to migrate fund. Then it shows: an error has occured. Tried on different computers and systems, many times, deinstalling and installing iota legacy and new iota via ledger life. Thanks for any help!

### Firefly version

1.3.0

### OS details

Mac OS 12.0.1

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

migrate iota from old to new network

### Actual behaviour

an error occured after hitting button: start migration

### Errors

es ist ein fehler aufgetreten
an error occured 
- no further discriptions

**Comment by r-c-k** [comment]
Hey there, please install v1.2.0 for the migration [https://github.com/iotaledger/firefly/releases/tag/desktop-1.2.0](https://github.com/iotaledger/firefly/releases/tag/desktop-1.2.0). Afterwards you can upgrade to 1.3.0 again and start staking.

If you need further assistance, please join the IOTA Discord at [https://discord.iota.org](https://discord.iota.org).

**Comment by MiKeF05** [comment]
@dsx5000 Were you able to solve your issue?

**Comment by dsx5000** [comment]
Thank you!
yes with firefly 1.2.0 it was possible to do!
