### ISSUE TITLE
Pre staking "something went wrong?"

### ISSUE THREAD

**Issue by iotabug** [iotaledger/firefly#1890]
### Issue description

Hi!

I tried to add my iota to the pre staking via the firefly wallet. I checked everything, forexample the firmware from the ledger and everything is uptodate. When I press confirm after stake, then in the right bottom a pop up shows up and says something went wrong. What is the issue? Everything should work?

### Firefly version

1.3.0

### OS details

windows 10

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

so that i can stake them as all other do

### Actual behaviour

bug

**Comment by r-c-k** [comment]
Does your error log say anything?

**Comment by MiKeF05** [comment]
I guess the tokens are spread about too many addresses. If this is the case you need to manually consolidate the tokens.

**Comment by iotabug** [comment]
how?

**Comment by r-c-k** [comment]
Create a new address (or wallet) and send all funds to that address/wallet.

**Comment by rajivshah3** [comment]
Does anything appear in the error log?
