### ISSUE TITLE
genarate adresse

### ISSUE THREAD

**Issue by Guenter6724** [iotaledger/firefly#1892]
### Issue description

Adresse is not possible to generate
ledger is correct connected
status network is online
Also wallet (staking is not syncronising)
1 hour ago, everything was working and fine
i have closed the wallet and the ledger several times, started the PC again, but the problem is still there
![staking](https://user-images.githubusercontent.com/96687943/147409164-f173297b-4193-471e-8f70-a11caffa2891.PNG)
![synchro wallet](https://user-images.githubusercontent.com/96687943/147409178-b018c1f0-863b-4cae-ad0c-e8ab0ca348c8.PNG)

### Firefly version

v1.3.0

### OS details

Windows 10 pro

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

hope that it works again soon

### Actual behaviour

several times startet new the ledger and the wallet

### Errors

no errors in the protokoll

**Comment by r-c-k** [comment]
You can try to either create a new wallet and send your funds there (via internal transfer for instance) or create an entirely new profile by restoring from your ledger. Adding `https://mainnet-node.tanglebay.com/` to your node list might also be a good idea (set as primary).

Also please make sure that you're not behind a strict firewall or VPN.

For further assistance please visit the IOTA Discord at [https://discord.iota.org](https://discord.iota.org).

**Comment by MiKeF05** [comment]
@Guenter6724 Were you able to solve your issue?

**Comment by Guenter6724** [comment]
Yes, thanks a lot, but now I have the problem, that sometimes the firefly wallet is only a white screen after a while. If I start firefly again, it works and after some minutes it's going to be white again. Thank you. Guenter 

Gesendet von Yahoo Mail auf Android 
 
  Am Di., Dez. 28, 2021 at 21:01 schrieb ***@***.***>:   


@Guenter6724 Were you able to solve your issue?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MiKeF05** [comment]
@Guenter6724 Does your computer enter the sleep mode? After the sleep mode Firefly has a white screen?

**Comment by Guenter6724** [comment]
No, the computer is not in the sleep mode. It's a windows surface with win 10 After a wile not using the firefly it's turning to white screen. So I have to quit firefly and start new

Gesendet von Yahoo Mail auf Android 
 
  Am Do., Dez. 30, 2021 at 16:35 schrieb ***@***.***>:   


@Guenter6724 Does your computer enter the sleep mode? After the sleep mode Firefly has a white screen?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
