### ISSUE TITLE
firefly Pre-staking disappears

### ISSUE THREAD

**Issue by perezosito** [iotaledger/firefly#1893]
### Issue description

I pre-staked some IOTA on december 22, I have the transaction confirmed, on december 22 i was able to see my funds in staking, now I open firefly again and it tolds me "dont detected staking funds, try changing node"

I have a notification (top right of the window) telling me to go to advanced settings, network, and "see details" to verify if staking is allowed but it dosn't sow me nothing about staking.

### Firefly version

1.3.0

### OS details

windows 10

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1. pre-staking on december 22 and wait 4 days
2.
3.
...

### Expected behaviour

no staking detected

### Actual behaviour

i dont see my funds in staking.

**Comment by bingodonky** [comment]
try to change node  to tanglebay  and put in in primary

**Comment by r-c-k** [comment]
Add `https://mainnet-node.tanglebay.com/` to your nodes list. The default load balances are having issues currently.

**Comment by xstriker01x** [comment]
This worked! Thank You

**Comment by perezosito** [comment]
Yes, Perfect! thanks you so much!

**Comment by MiKeF05** [comment]
Duplicate to https://github.com/iotaledger/firefly/issues/1894

**Comment by bazchap** [comment]
> Add `https://mainnet-node.tanglebay.com/` to your nodes list and set it as primary. The default load balances are having issues currently.

this worked for me too, thanks

**Comment by Olatuyitony347** [comment]
am unable to add this node https://mainnet-node.tanglebay.com/ to my firefly account it keeps telling me something went wrong

**Comment by rajivshah3** [comment]
@Olatuyitony347 does anything appear in the error log?

**Comment by rajivshah3** [comment]
Closing issue as the original issue was resolved
