### ISSUE TITLE
Staking Not Detected

### ISSUE THREAD

**Issue by subhanmangi** [iotaledger/firefly#1894]
### Issue description

Same issue happening with all my wallets on Mac FireFly Version 1.3.

Tried all official nodes

### Firefly version

1.3.0

### OS details

Mac OS

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Sign in Firefly
2. Go to Staking
3. Click the Stake

### Expected behaviour

Staking not detected

### Actual behaviour

Staking

**Comment by r-c-k** [comment]
Add `https://mainnet-node.tanglebay.com/` to your nodes list and set it as primary. The default load balances are having issues currently.

**Comment by dkdwien** [comment]
Same issue.
ClientError: 'Response error with satus code 503: Service Unavailable'

https://mainnet-node.tanglebay.com/ - doesn't work for me.

**Comment by hackneycrypto** [comment]
Also having same issue. Trying to add https://mainnet-node.tanglebay.com/ within Advanced Settings - Node Configuration and get error "Something went wrong" and the node is not added to the the list.

**Comment by justjooshing** [comment]
To add to the above, seemingly any request is getting 503 for me including 'find balances' or 'view info' on the two official nodes (chrysalis-nodes.iota.org and .iota.cafe) as well as trying to add new nodes

**Comment by rajivshah3** [comment]
Hi, the coordinator is currently down. Please see https://status.iota.org for updates

**Comment by r-c-k** [comment]
Official statement:

_We have some issues with the COO Node atm, the devs are working already on it, please be patient, you can't do anything at the moment. 
Your Firefly will show "network disconnected" and you don't see your staking rewards. This is just temporary.
At the moment, no new staking rewards are generated during this downtime and no transactions can be issued. Your currently already gained rewards will NOT be lost, the minutes of this downtime will automatically be added to the staking period, so the exact 90 days staking will be achieved._
