### ISSUE TITLE
Again same problem

### ISSUE THREAD

**Issue by ercankuruz** [iotaledger/firefly#1895]
### Issue description

Again I've got the same problem.  my stakes are invisible in my wallet. I've started the staking, but now it is saying that " 0 mi staked
![Screen Shot 2021-12-26 at 11 16 21 PM](https://user-images.githubusercontent.com/94834098/147418072-cd0f70f8-7634-42b9-a9ce-d8feacbe92de.png)
![Screen Shot 2021-12-26 at 11 16 05 PM](https://user-images.githubusercontent.com/94834098/147418074-fa8579f1-0df8-4a7f-bba3-877571a607b2.png)
"I've got

### Firefly version

Fireflyy v1.3.0

### OS details

mac

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

Again I've got the same problem.  my stakes are invisible in my wallet. I've started the staking, but now it is saying that " 0 mi staked

### Actual behaviour

Again I've got the same problem.  my stakes are invisible in my wallet. I've started the staking, but now it is saying that " 0 mi staked

**Comment by MiKeF05** [comment]
Please read https://github.com/iotaledger/firefly/issues/1894

**Comment by MiKeF05** [comment]
Issue can be closed

**Comment by ercankuruz** [comment]
thanks



Best Regards,
 
Huseyin Ercan KURUZ | Certifying Engineer
m. +971 (0)58 891 1633
***@***.*** | flydubai.com
