### ISSUE TITLE
Transaction from Bitpanda to Firefly-Wallet

### ISSUE THREAD

**Issue by iamalazar** [iotaledger/firefly#1898]
### Issue description

Hello all, 

on 12/21/2021 at 17:59 I sent a transaction via an crypto exchange named Bitpand 999.988555 MIOTA to my Firefly wallet (address: atoi1qpkq5a95awvxfggzhxvhe9w0s6h5dkv5l6tzvsg66p233f4fl7s0gprzg9x). The transaction was executed by Bitpanda on the same day.  Unfortunately, I have not yet received the MIOTA that I've sent. 
The message ID for the transaction is: 80c33362f5b23cd42543df905a7887a281d4f4f624772fd1cd578f07ffc2e344

Could you help me further regarding this? 

Thank you very much for your support.

With kind regards 
Alazar

Translated with www.DeepL.com/Translator (free version)

### Firefly version

1.3.0

### OS details

Mac

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Sent 999,988555 MIOTA from Bitpand to my Firefly-Wallet (Adrres:atoi1qpkq5a95awvxfggzhxvhe9w0s6h5dkv5l6tzvsg66p233f4fl7s0gprzg9x)
2.Transaction was executed by the exchange at the same day, under the following Message ID 80c33362f5b23cd42543df905a7887a281d4f4f624772fd1cd578f07ffc2e344
3. till now I've not received the sent MIOTA yet   

### Expected behaviour

My expectation is that you can tell me where the MIOTA sent went and credit it to my wallet (which I specified in the description).

### Actual behaviour

My expectation is that you can tell me where the MIOTA sent went and credit it to my wallet (which I specified in the description).

### Errors

n/a

**Comment by r-c-k** [comment]
You created a developer profile and therefore generated a testnet address. Unfortunately Bitpanda wasn't properly checking the addresses at this point and send your funds to the same address on mainnet instead.
Please create a new profile by restoring from your ledger/passphrase **without** selecting the "Developer profile" checkbox. Your funds will appear then.

If you need further assistance please join the IOTA Discord server at [https://discord.iota.org](https://discord.iota.org).

**Comment by iamalazar** [comment]
thank you very much for your your support. I received my everything
