### ISSUE TITLE
Funds have not been received to the Firefly wallet. Don't know what to do. Network is clear. Transaction was from Bitpanda to Firefly.

### ISSUE THREAD

**Issue by Lukkullus** [iotaledger/firefly#1899]

**Comment by r-c-k** [comment]
It's hard to help you without you providing any issue description, but anyway...
Please see if the following answer solves your issue: [https://github.com/iotaledger/firefly/issues/1898#issuecomment-1001511512](https://github.com/iotaledger/firefly/issues/1898#issuecomment-1001511512)

**Comment by Lukkullus** [comment]
Sorry, my english is not that good. I ve sent about 81 IOTA to the Firefly Wallet (iota1qrnu47hjk7xj547rf2lqx894927t2lm4jg96mcz2p47nl88eek7mkmvfs5p) and it was confirmed by BitPanda via Mail. But there is no IOTA to see in my wallet.

**Comment by Lukkullus** [comment]
Forget it......the token arrived. Thank you.

**Comment by r-c-k** [comment]
Issue can be closed then @Lukkullus
