### ISSUE TITLE
Firefly wallet retrieval

### ISSUE THREAD

**Issue by mazanyah** [iotaledger/firefly#1904]
### Issue description

after providing correct stronghold backup file and password to restore Firefly wallet, I'm getting a whitescreen and so cannot access my wallet.
Important Note: The wallet had not yet been updated from previous version as it was originally opened on a Windows 10 PC, which would not permit the update. Upon trying to restore that wallet on my MacBook Pro is when the above problem occurred.

### Firefly version

1.1.0

### OS details

10.13.6

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. download Firely wallet from firefly.iota.org on to MacBook Pro, version Mac OS High Sierra 10.13.6
2. open Firefly wallet using download .dmg file
3. select add profile, create a profile name, then hit continue
4. select migrate or restore a wallet
5. select I have a file backup 
6. in the drag/drop dialog window select choose file, select original stronghold backup file and hit continue
7. supply original password, hit continue
8. whitescreen appears
Please Note: in the Firefly menu bar, under the Firefly dropdown tab, when About Firefly is selected it shows as the 1.3 version (other categories, eg: Check for Updates, Diagnostics, Error Log are inoperable).

### Expected behaviour

After providing correct stronghold backup file and password I expected access to my restored Firefly wallet.

### Actual behaviour

The Firefly wallet window opens as a blank whitescreen, therefore not permitting any access to the wallet.

**Comment by r-c-k** [comment]
Please update to the most recent Firefly version (1.3.0). If you have your backup (passphrase or ledger), then try deleting the Firefly folder at `~/Library/Application Support/Firefly` and then create a new profile by restoring from that backup.

**Comment by MiKeF05** [comment]
@mazanyah Were you able to solve your issue?

**Comment by mazanyah** [comment]
No. At present the issue remains unresolved. Because I cannot yet access the Firefly wallet (i.e., getting only a whitescreen, as specified in my initial laying out of the issue, above) I cannot update to the most recent version (1.3.0), thus what r-c-k's solution proposes is impossible at the outset. 
I am still in need of assistance. Thanks.

**Comment by r-c-k** [comment]
Have you already deleted the Firefly folder as advised? @mazanyah

**Comment by mazanyah** [comment]
I installed Firefly on a different computer (iMac OS 10.11.6 - because I did not have success trying to delete the Firefly folder on my MacBook Pro, as I currently have a different Firefly wallet running on that computer and am presently staking my IOTA tokens from that wallet).
However, I ran into the exact same issue: whitescreen, as previously described; and so cannot even access the Firefly wallet to update it to the current version 1.3.0

**Comment by r-c-k** [comment]
You can update to 1.3.0 without opening the wallet: [https://firefly.iota.org](https://firefly.iota.org).
Please also remove your Firefly folder on your iMac and try again. I'm not sure if you macOS version is supported by Firefly though. @mazanyah

**Comment by mazanyah** [comment]
Can you please provide specific instructions or supply that particular body of information specific to updating the Firefly without being able to access the wallet itself. 
Thanks Much.

**Comment by r-c-k** [comment]
1. Click the link I provided ([https://firefly.iota.org](https://firefly.iota.org)).
2. Click the download button for your operating system.
3. Let it download.
4. Execute the file you just downloaded.
5. Don't forget to brush your teeth before going to bed.

**Comment by mazanyah** [comment]
All of these steps have been taken multiple times and DO NOT at all resolve the issue, which is why I provided very specific/detailed information as to the nature of the problem that is occurring.
I am not in need of general solutions but rather assistance that directly addresses the problem encountered, as initially presented. 
But thanks.

**Comment by r-c-k** [comment]
If you've taken those steps multiple times before then you are on 1.3.0 already. You can now delete your Firefly folder from `~/Library/Application Support/Firefly` and set up a new profile by restoring from your backup. From my experience, this resolves the white screen issue for users with an outdated macOS version.

**Comment by mazanyah** [comment]
pardon my lack of knowledge, as I am not tech savvy but can easily follow clear step-by-step instructions, specifically: where on my MacBook and/or iMac do I go to delete the above identified folder? ie, how is the process that you provide undertaken. Thanks kindly.

**Comment by r-c-k** [comment]
Open the Finder and press `Shift+CMD+G`. Then just copy paste the path and press enter.

**Comment by mazanyah** [comment]
Followed your instructions precisely. Unfortunately, same result. 
Uncertain of other options but will continue various other approaches until successfull, as the wallet holds a significant amount of IOTA.
Thanks for your assistance.

**Comment by r-c-k** [comment]
Please visit the IOTA Discord ([https://discord.iota.org](https://discord.iota.org)) for further (and more efficient) assistance.

**Comment by cvarley100** [comment]
You might need to update Mac OS.

**Comment by mazanyah** [comment]
I’ll try it. 🙏🏾
