### ISSUE TITLE
PIN碼無法連續輸入.....

### ISSUE THREAD

**Issue by dinosaur55555** [iotaledger/firefly#1905]
### Issue description

進入錢包前的PIN碼無法連續輸入，需要一個一個用滑鼠點選才能輸入，輸入完後說密碼錯誤....
所以我用助記詞再復原一個錢包地址，結果還是一樣，需要一個一個用滑鼠點選才能輸入，輸入完後說密碼錯誤

我確定我PIN碼沒有記錯，因為有一次我重裝軟體，是可以直接輸入PIN碼而且密碼正確，但也僅只有一次成功
後來我重下載軟體，重新安裝軟體都無法進入，說是PIN碼錯誤

### Firefly version

1.3.0

### OS details

WIN 10 Professional 

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.進入錢包前的PIN碼無法連續輸入
2.需要一個一個用滑鼠點選才能輸入
3.輸入完後說密碼錯誤....
...

### Expected behaviour

我要成為IOTA家人

### Actual behaviour

無法登入錢包

**Comment by r-c-k** [comment]
Try changing the language in Firefly to English.
试着将萤火虫的语言改为英语。

**Comment by dinosaur55555** [comment]
成功了，謝謝

**Comment by r-c-k** [comment]
那么问题就可以结束了 @dinosaur55555

**Comment by MiKeF05** [comment]
Issue can be closed
