### ISSUE TITLE
Didn't receive token from Bitpanda

### ISSUE THREAD

**Issue by demian78** [iotaledger/firefly#1906]
### Issue description

I sent 100€ IOTA from Bitpanda to firefly on 12/22/21 and didn't receive any token yet?!
Where are my toke???
I have developer status with firefly.
For details see picture below:
![Iota-Zahlung](https://user-images.githubusercontent.com/96737717/147488951-394f2a80-78c4-435d-a858-87d92bd6d8e0.jpg)

### Firefly version

1.3.0

### OS details

Windows 10 pro

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1. I did not wanted to try because otherweise all my tokens are gone
2.
3.
...

### Expected behaviour

Get my tokens!

### Actual behaviour

I don't know

**Comment by MiKeF05** [comment]
Your address starts with atoi... This is an address for the testnet. You have created a developer profile which is connected to the testnet. You need to create a new profile and restore your profile without checking the developer profile.

**Comment by MyMonk089** [comment]
You sent the token to a test net address. atoi... That was wrong. Mainnet has iota... addresses. 😉 Think they are gone.

**Comment by r-c-k** [comment]
They're not gone @MyMonk089 
Do what MiKeF05 told you @demian78. Just create a new profile by restoring from the passphrase/ledger that you used for your current dev profile **without** checking the "Developer profile" checkbox and all will be good.

**Comment by demian78** [comment]
Ok thanks I will try. Should I delete the old profile?

**Comment by demian78** [comment]
It worked! Thank YOU @MyMonk089 and @r-c-k !!!

**Comment by r-c-k** [comment]
Issue can be closed then @demian78
