### ISSUE TITLE
Die Auswahl für welchen Token gestackt werden soll ist nicht gekommen . 

### ISSUE THREAD

**Issue by HyKoTo** [iotaledger/firefly#1909]
### Issue description

Ich habe vor einigen Tagen das erste mal in meiner Wallet Iota gestackt. Dabei habe ich beide Token ausgewählt. 
Jetzt habe ich noch einmal Iota gestackt . Allerdings ist keine Auswahl mehr gekommen für welchen Token ich stacken möchte. 

### Firefly version

1.3.0

### OS details

Win 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Iota stacken auswählen 
2.iota werden gestacked
3.insg gestackter Betrag ist ok
...

### Expected behaviour

Auswahlmenü kommt . Ob ich Shimmer oder Assembly stacken möchte .

Das hat vor einigen Tagen noch funktioniert.

### Actual behaviour

die MIOTA wurden gestackt ohne Auswahlmöglichkeit.

**Comment by MiKeF05** [comment]
Die Tokens, die du erneut manuell zum Staking hinzugefügt hast, wurden automatisch mit der vorherigen Auswahl gestaked. Wenn du also beim ersten Staken beide Airdrops ausgewählt hast und später nochmal Token manuell zum Staken hinzugefügt hast, werden die Token auch für beide Airdrops gestaked.

Wenn du die Auswahl ändern möchtest, musst du einmal unstaken und kannst bei erneutem Staken wieder eine Auswahl treffen.

**Comment by HyKoTo** [comment]
Ok danke für die Information .
