### ISSUE TITLE
Problem migrating Iota from Trinity to Firefly using a Nano S

### ISSUE THREAD

**Issue by AndreMarselous** [iotaledger/firefly#1913]
Hi. 
I'm trying to migrate my Iota from Trinity to Firefly using my Nano S. Everything went fine, I even saw my balance. But when I tried to migrate the Iota, I got the notification "Something went wrong" with no other explanation. Has anyone else had this problem, and if so, how did you solve it?
Any advice would be greatly appreciated.
Thank you!

**Comment by MAITREIOTA** [comment]
Salut jai exactemment le meme probleme que toi , tu as trouvé une solution ?

**Comment by MiKeF05** [comment]
Unfortunately migrating tokens from the old network using a Ledger Nano in combination with the newest Firefly version 1.3 has some issues atm. If it fails to migrate with the "something went wrong message" do the following:

- Downgrade your Firefly version to Version 1.2.
To do this, delete the current Firefly version from your PC, and download version 1.2 from here: https://github.com/iotaledger/firefly/releases/tag/desktop-1.2.0 (scroll down to "assets"), install this Firefly version, and then migrate your tokens with the Nano ledger as described here: 
https://blog.iota.org/firefly-token-migration-guide-for-ledger-users/

After this has succeeded, you can update to Firefly version 1.3 which will make staking your IOTA tokens possible. 
Do not install Firefly as a "Developer Profile"!

**Comment by Marzo2121** [comment]
Hi
I have exactly the same problem here:
I installed Firefly 1.3, all fine, it even showed my balance.
Then I installed Firefly 1.2 as you described.
Now I don't even get the balance. It shows "Das dauert ein bisschen. Generiert dein Ledger Adressen?"
I've reinstalled Iota Legacy, doesn't work. Same message.
![ledger iota legacy](https://user-images.githubusercontent.com/96747076/147502994-988dd0e1-f601-4e4e-939b-f306aa131f02.png)

**Comment by MiKeF05** [comment]
Can you try to close and reopen the IOTA legacy app on the ledger device? Your ledger needs to display "Generating Address" in this process. If this issue persists please join the IOTA Discord server (https://discord.iota.org/) to get immidiate help.

**Comment by MiKeF05** [comment]
@AndreMarselous @MAITREIOTA @Marzo2121 Were you able to solve your issue?

**Comment by Marzo2121** [comment]
Yes, sorry for not replying!
I got help on discord.

Solution:
- deactivate firewall
- run firefly as admin
