### ISSUE TITLE
firefly cannot be installed on my PC

### ISSUE THREAD

**Issue by Leandro19786** [iotaledger/firefly#1914]
I am worried because I have already installed and reinstalled the firefly application twice on my PC, and when I have done the whole process (24 sentences, profile, stronghold file, etc.) the program tells me that something went wrong and I cannot install it Finally.

I refuse you to inform us what to do, or if it is necessary to install it in another language ....... I repeat that the application installs well, but something happens at the end of the process.

Please, I ask you to resolve it, as we do not want to be left out of the IOTA staking period, which begins on December 28.

**Comment by MiKeF05** [comment]
Is there a problem with installing Firefly or restoring your profile? Are you able to open Firefly?

**Comment by Leandro19786** [comment]
> Is there a problem with installing Firefly or restoring your profile? Are you able to open Firefly?

I can download firefly on my PC, I can do the whole registration process (phrases, language, profile;) but in the end it says something went wrong

**Comment by MiKeF05** [comment]
Can you share the error log in Firefly?

**Comment by Leandro19786** [comment]
> Can you share the error log in Firefly?

I send you a photo

[Doc1.docx](https://github.com/iotaledger/firefly/files/7781671/Doc1.docx)

**Comment by MiKeF05** [comment]
Can you click on the menu in the upper left? Navigate to Firefly and error log

**Comment by Leandro19786** [comment]
Mon, 27 Dec 2021 19:59:19 GMT
StrongholdError: `the mnemonic was already stored`

Mon, 27 Dec 2021 19:16:18 GMT
StrongholdError: `the mnemonic was already stored`

Mon, 27 Dec 2021 18:48:43 GMT
StrongholdError: `the mnemonic was already stored`

Mon, 27 Dec 2021 18:48:29 GMT
StrongholdError: `the mnemonic was already stored`

Mon, 27 Dec 2021 18:28:56 GMT
StrongholdError: `the mnemonic was already stored`

Mon, 27 Dec 2021 18:27:27 GMT
ClientError: `error sending request for url (https://api.lb-1.h.chrysalis-devnet.iota.cafe/api/v1/info): error trying to connect: tcp open error: Se ha proporcionado un argumento no válido. (os error 10022)`

Mon, 27 Dec 2021 18:15:04 GMT
StrongholdError: `the mnemonic was already stored`

Mon, 27 Dec 2021 18:14:49 GMT
ClientError: `error sending request for url (https://api.lb-0.h.chrysalis-devnet.iota.cafe/api/v1/info): error trying to connect: tcp open error: Se ha proporcionado un argumento no válido. (os error 10022)`

Fri, 24 Dec 2021 19:26:05 GMT
StrongholdError: `the mnemonic was already stored`

Fri, 24 Dec 2021 19:18:08 GMT
StrongholdError: `the mnemonic was already stored`

Fri, 24 Dec 2021 19:08:03 GMT
StrongholdError: `the mnemonic was already stored`

Fri, 24 Dec 2021 19:07:53 GMT
ClientError: `error sending request for url (https://api.lb-1.h.chrysalis-devnet.iota.cafe/api/v1/info): error trying to connect: tcp open error: Se ha proporcionado un argumento no válido. (os error 10022)`

Fri, 24 Dec 2021 19:03:49 GMT
StrongholdError: `the mnemonic was already stored`

Fri, 24 Dec 2021 19:03:01 GMT
StrongholdError: `the mnemonic was already stored`

Fri, 24 Dec 2021 19:02:49 GMT
StrongholdError: `the mnemonic was already stored`

Fri, 24 Dec 2021 19:00:15 GMT
StrongholdError: `the mnemonic was already stored`

Fri, 24 Dec 2021 19:00:09 GMT
StrongholdError: `the mnemonic was already stored`

Fri, 24 Dec 2021 19:00:06 GMT
StrongholdError: `the mnemonic was already stored`

Fri, 24 Dec 2021 18:57:51 GMT
ClientError: `error sending request for url (https://api.lb-1.h.chrysalis-devnet.iota.cafe/api/v1/info): error trying to connect: tcp open error: Se ha proporcionado un argumento no válido. (os error 10022)`

**Comment by MiKeF05** [comment]
And you want to restore your profile?

**Comment by Leandro19786** [comment]
windows 2008

**Comment by MiKeF05** [comment]
And you want to restore your profile?

**Comment by Leandro19786** [comment]
yes, i need firefly

**Comment by MiKeF05** [comment]
Try the following:

- Unintall Firefly
- Delete the folder Firefly in C:\Users\[User]\AppData\Roaming\
- Install Firefly again
- Create new profile and restore your profile

But please DO NOT USE the developer profile when you set up a profile.

**Comment by Leandro19786** [comment]
> Try the following:
> 
> * Unintall Firefly
> * Delete the folder Firefly in C:\Users[User]\AppData\Roaming\
> * Install Firefly again
> * Create new profile and restore your profile
> 
> But please DO NOT USE the developer profile when you set up a profile.

thank you very very much.
i will do it that way

I think the error was that when starting it filled the developer profile option, and I shouldn't have done it.

thanks again.

**Comment by JanOonk** [comment]
Btw general security advice: upgrade your OS. Windows (Server) 2008 is really really old and not supported anymore by Microsoft and will not receive any updates incl. security updates anymore since 14 January 2020. Source https://en.m.wikipedia.org/wiki/Microsoft_Windows

**Comment by Leandro19786** [comment]
> Btw general security advice: upgrade your OS. Windows (Server) 2008 is really really old and not supported anymore by Microsoft and will not receive any updates incl. security updates anymore since 14 January 2020. Source https://en.m.wikipedia.org/wiki/Microsoft_Windows

Thanks. it is already installed on my PC
