### ISSUE TITLE
No se migran mis iotas desde Trinity a Firefly

### ISSUE THREAD

**Issue by Cojomantecas** [iotaledger/firefly#1915]
Llevo varias días intentando obtener las iotas que tenía en mi billetera de Trinity pero es imposible. He descargado Firefly en dos ordenadores diferentes para volver a hacer elprocso desde el principio pero en ningún momento accedo al saldo que tenía en Trinity. La nueva billetera la abro gracias a la frase de seguridad.
Podrían ayudarme?

**Comment by MiKeF05** [comment]
What is the exact issue? You are not able to migrate?

**Comment by Cojomantecas** [comment]
El problema exacto es que se crea la nueva billetera vinculada a la antigua gracias a la frase de recuperación, pero el saldo es 0 y no puedo migrar las iotas que tenia acumuladas en la antigua. Donde están esas iotas ahora? Como puedo recuperarlas?
Gracias

Enviado desde ProtonMail móvil

-------- Mensaje original --------

**Comment by MiKeF05** [comment]
Please join the official IOTA discord server (https://discord.iota.org/) to get immediate help with this.

**Comment by MiKeF05** [comment]
@Cojomantecas Were you able to solve your issue?

**Comment by Cojomantecas** [comment]
No, no se ha solucionado el problema. Nadie sabe decirnos como recuperar las iotas.

Enviado desde ProtonMail móvil

-------- Mensaje original --------

**Comment by BTCuba1** [comment]
Hola a todos, tengo mis iotas en la versión antigua de Firefly y no puedo ponerlos en staking ya que la nueva actualización cuando trato de bajarla me da un error, si alguien ya pudo resolver eso por favor déjenmelo saber, gracias

**Comment by MiKeF05** [comment]
@BTCuba1 Please download the latest version directly from here: https://firefly.iota.org/
You can install it again and should then have the latest version.

**Comment by MiKeF05** [comment]
@Cojomantecas It is difficult to solve this issue on Github. Please join the official IOTA discord server (https://discord.iota.org/) to get immediate help with this.

**Comment by Cojomantecas** [comment]
Buenas noches.
He perdido tiempo y dinero.
Si los 81 caracteres por algún motivo están mal apuntados, tu contraseña no sirve de nada ya que la billetera Trinity ha caducado.
Es una curiosa forma de perder inversores.
Gracias por intentar ayudarme.
Saludos cordiales.

Enviado desde ProtonMail móvil

-------- Mensaje original --------

**Comment by Cojomantecas** [comment]
Hola de nuevo.
Sigo intentando recupera las Iotas de trinity y se nos ha ocurrido entrar en Thangle y copiar tanto la dirección de la billetera como el id de la transacción, las dos obtenidas de Binance.
Tangle no reconoce ninguna de las dos informaciones. ¿Quiere esto decir que nos han jaqueado la billetera?
¿Qué más podemos hace?
¿Nos puedes dar alguna idea?
Muchas gracias de ante mano y disculpa las molestias.
Saludos cordiales.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by MiKeF05** [comment]
I don´t get your exact issue. Have you already migrated your 81 char seed?

**Comment by Cojomantecas** [comment]
No, me dice que no son correctos mis 81 caracteres, pero tampoco me dejaba entrar en mi billetera de trinity.

Enviado desde ProtonMail móvil

-------- Mensaje original --------

**Comment by MiKeF05** [comment]
After you have done the steps described above you can go to your account and view the seed of your account.

**Comment by Cojomantecas** [comment]
En firefly metimos tanto la semilla como las 24 palabras. La siemilla no fue reconocida y las palabras hizo que se abriera una billetera vacía. Para comprobar que hicimos bien la transacción en su momento introdujimos en thetangle tanto la dirección de la billetera como la id de la transacción (que es lo que le contábamos en el anterior mail) y ninguna de las dos cosas fue reconocida por el escaner de iotas. Quiere eso decir que nos pudieron Hackear la billetera?
Se le ocurre alguna idea más para ver que ha podido pasar con la billetera?
Gracias

Enviado desde ProtonMail móvil

-------- Mensaje original --------

**Comment by MiKeF05** [comment]
Again you have not migrated your 81 char seed haven't you? If you have NOT migrated then your funds can not be in Firefly. You need to migrate your correct 81 char seed.
Have you logged in to Trinity to check 81 char seed? Where did you get the 24 words that you entered in Firefly?
