### ISSUE TITLE
IOTA not arrived in Firefly

### ISSUE THREAD

**Issue by Octo77** [iotaledger/firefly#1917]
### Issue description

Using Ledger address in Firefly.
Send from Bitvavo , not arrived (3 hours now)

### Firefly version

1.3

### OS details

windows 10

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...
?

### Expected behaviour

?

### Actual behaviour

?

**Comment by r-c-k** [comment]
Do you have a message ID/transaction ID? You can also check your withdrawal address on [https://explorer.iota.org](https://explorer.iota.org) to see if your exchange actually processed your withdrawal order.

Bitvavo also just suspended withdrawals so they might have canceled your withdrawal request.

**Comment by Octo77** [comment]
the address is empty. Bitvavo supported te withdrawel and the transaction is marked as approved

**Comment by Octo77** [comment]
The address
iota1qzkzeh385d607wkq0e78f992s3069upw0jq955cfxhz2wpvqnvgw6x8gaer

**Comment by MiKeF05** [comment]
The balance is 0 yes. Then you should get in contact with their support as the withdrawal seems to be not completed.

**Comment by kanggarya** [comment]
i have the same issue, I have sent from indodax exchange and the transaction was success, but 4 hours ago, i havent received it in my firefly wallet
TX id : 9e6feaa5fe14df86f4f186a442d76c822fef15e36d834381c8463b56ad1e4ba5
wallet address: atoi1qre9jzfjffpnrq6tfm8wdvkvtrvfh0mhv2jeruh79u4cf20xgfe4qver78p

Looks like there's a problem with the wallet

**Comment by Octo77** [comment]
> The address
> iota1qzkzeh385d607wkq0e78f992s3069upw0jq955cfxhz2wpvqnvgw6x8gaer

I received it today, 16 hours after the transaction. Nerverecking but resolved

**Comment by begonaalvarezd** [comment]
> i have the same issue, I have sent from indodax exchange and the transaction was success, but 4 hours ago, i havent received it in my firefly wallet TX id : 9e6feaa5fe14df86f4f186a442d76c822fef15e36d834381c8463b56ad1e4ba5 wallet address: atoi1qre9jzfjffpnrq6tfm8wdvkvtrvfh0mhv2jeruh79u4cf20xgfe4qver78p
> 
> Looks like there's a problem with the wallet

@kanggarya `atoi1qre9jzfjffpnrq6tfm8wdvkvtrvfh0mhv2jeruh79u4cf20xgfe4qver78p` is a devnet address not a mainnet one. Looks like you have a created a "developer profile" which connects to devnet by default. When you create a profile, please avoid ticking "developer profile", we are improving the UX around this for the next version. 

Is the transaction in Indodax really confirmed?
