### ISSUE TITLE
Error Occured

### ISSUE THREAD

**Issue by Tunchie522** [iotaledger/firefly#1919]
### Issue description

App Version: 1.3.0

platform: win32
platformVersion: 6.3.9600
platformArchitecture: x64
cpuCount: 4
totalMem: 4016.7 MB
freeMem: 1156.9 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_INTERNET_DISCONNECTED

### Firefly version

1,3,0

### OS details

wondows 8.1

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

Repeated App Failure 

### Actual behaviour

App Sudden failure with an warning
 

### Errors

App Version: 1.3.0

platform: win32
platformVersion: 6.3.9600
platformArchitecture: x64
cpuCount: 4
totalMem: 4016.7 MB
freeMem: 1156.9 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_INTERNET_DISCONNECTED

**Comment by MiKeF05** [comment]
I think you do not have a internet connection as the error says ERR_INTERNET_DISCONNECTED. Please make sure that you have a stable internet connection.

**Comment by cvarley100** [comment]
Duplicate issue.
