### ISSUE TITLE
Pin lockout

### ISSUE THREAD

**Issue by Jadashi** [iotaledger/firefly#1920]
### Issue description

Not sure why this happened but I got a pin lockout after a Windows security update... I note that it has happened in older versions of Firefly (mostly Mac) while investigating the problem on the net.

I'd used the pin hundreds of times to login in to a regularly used wallet, (the only one I've ever used) but today after staking a considerable amount of MIOTA it locked me out with incorrect pin errors...

After fretting a bit, app closing, reboots, FAQ study i was able to restore it with a new wallet profile and the stronghold backup system.

I don't plan on trying to replicate the error either.

Just thought I'd mention it and see if anyone else has had it happen.

### Firefly version

1.3

### OS details

Windows 7

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.Enter Pin
2.Enter Pin
3.Enter Pin
...

### Expected behavior
 
Regularly used pin to log into Flyfly Wallet

### Actual behavior

Incorrect Pin error
Incorrect Pin error

**Comment by nicole-obrien** [comment]
Duplicate of #1683
