### ISSUE TITLE
Issue to connect Firefly wallet from the network due to invalid peer cert

### ISSUE THREAD

**Issue by mudlum** [iotaledger/firefly#1921]
### Issue description

I have sent some IOTA to the wallet via Binance & Bitfinex but unable to view it from the Fireflyt wallet. 
Following is the error msg I got.

Tue, 28 Dec 2021 09:02:54 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer`

### Firefly version

Firefly v1.3.0

### OS details

Windows 

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

The error msg is reoccuring, seems been happening since wallet setup today

### Actual behaviour

Unable to view the relevant balance for staking

### Errors

Tue, 28 Dec 2021 09:02:54 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer`

**Comment by r-c-k** [comment]
When you're sure, that your withdrawals were processed by Binance & Bitfinex then please make also sure that you're not behind a strict firewall or vpn. Alternatively try connecting to one of the default nodes in the settings.

**Comment by SVAR76** [comment]
Hi I am facing exactly the same issue
MIOTAS successfully sent from Binance but unable to see them on my wallet because of Network appears as "Disconnected" in the App

**Comment by SVAR76** [comment]
Wed, 29 Dec 2021 13:09:32 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer`
![Issue2](https://user-images.githubusercontent.com/96828214/147667347-717643f1-fa8b-4535-9e0c-c5ff664ad10d.jpg)
![Issue1](https://user-images.githubusercontent.com/96828214/147667358-00e37b09-71f1-4f41-9df4-3c63042cf4dd.jpg)

**Comment by r-c-k** [comment]
Are you behind a strict firewall or a VPN?

**Comment by rajivshah3** [comment]
@mudlum @SVAR76 Can you provide your OS details including version?

**Comment by mudlum** [comment]
My issue is resolved after lifting the firewall. Thanks!
