### ISSUE TITLE
my firefly wallet address is wrong

### ISSUE THREAD

**Issue by Ricoo28** [iotaledger/firefly#1923]
### Issue description

My Firefly wallet address is wrong and I cannot send iota from the exchange, how can I change my wallet address?

### Firefly version

1.3.0

### OS details

windows10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

My Firefly wallet address is wrong and I cannot send iota from the exchange, how can I change my wallet address?

### Actual behaviour

My Firefly wallet address is wrong and I cannot send iota from the exchange, how can I change my wallet address?

### Errors

My Firefly wallet address is wrong and I cannot send iota from the exchange, how can I change my wallet address?

**Comment by MiKeF05** [comment]
Does your address start with atoi...? If your address starts with atoi... then you need to create a new profile without checking the developer profile.

**Comment by Ricoo28** [comment]
> Adresin atoi... ile mi başlıyor? Adresiniz atoi... ile başlıyorsa, geliştirici profilini kontrol etmeden yeni bir profil oluşturmanız gerekir.

yes it starts with atoi. Do I need to delete and reopen my profile?

**Comment by r-c-k** [comment]
You need to create a new profile but let the "Developer profile" checkbox unselected. @Ricoo28

**Comment by kanggarya** [comment]
@r-c-k  thx u sir, my problems solve, hope help the same issue with me
