### ISSUE TITLE
error on Firefly

### ISSUE THREAD

**Issue by hector100499** [iotaledger/firefly#1924]
### Issue description

error tope: main unhandled premies rejected
error: uncaught error: net: :ERR_INTERNET_DISCONECTED

### Firefly version

1.3.0

### OS details

Mac OS 12.1

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. 2. 3. ... Mar, 28 Dic 2021 13:15:17 GMT ClientError: `error enviando una solicitud de url (https://chrysalis-nodes.iota.cafe/api/v1/info): error al intentar conectarse: error dns: no se pudo buscar información de la dirección: nombre de nodo ni nombre serv proporcionado, o desconocido`  Mar, 28 Dic 2021 13:15:17 GMT ClientError: `error enviando una solicitud de url (https://chrysalis-nodes.iota.org/api/v1/info): error al intentar conectarse: error dns: no se pudo buscar información de la dirección: nombre de nodo ni serv proporcionado, o no conocido`  Mar, 28 Dic 2021 13:15:08 GMT ClientError: `error enviando una solicitud de url (https://chrysalis-nodes.iota.cafe/api/v1/info): error al intentar conectarse: error dns: no se pudo buscar información de la dirección: nombre de nodo ni nombre serv proporcionado, o desconocido`  7 GMT ClientError: `error enviando una solicitud de url (https://chrysalis-nodes.iota.cafe/api/v1/info): error al intentar conectarse: error dns: no se pudo buscar información de la dirección: nombre de nodo ni nombre serv proporcionado, o desconocido`  Mar, 28 de diciembre de 2021 13:14:29 GMT ClientError: `error enviando una solicitud de url (https://chrysalis-nodes.iota.cafe/api/v1/info): error al intentar conectarse: error dns: no se pudo buscar información de la dirección: nombre de nodo ni nombre serv proporcionado, o desconocido`  

### Expected behaviour

i dont know

### Actual behaviour

cantidad receiv mi iotas on Firefly from bitfinex

**Comment by MiKeF05** [comment]
Looks like you have issues with your internet connection. Can you close and reopen Firefly? 

You can also try to change the node to https://mainnet-node.tanglebay.com/ in the node settings. Just switch to manual, add the node to the list and set it as primary node.

**Comment by hector100499** [comment]
so i have to be conected to internet to receiv mi iotas in Firefly?

**Comment by MiKeF05** [comment]
Yes

**Comment by hector100499** [comment]
gracias
im already staking, but if mi internet go Down or if mi pc disconnects from the internet, the staking stop? the tokens stop joining? thanks¡

**Comment by MiKeF05** [comment]
No, Firefly connects to a node and retrieves all the necessary data. So you can disconnect your internet again and the staking remains. But if you want to see your rewards and have access to Firefy you need an internet connection again. Because Firefly needs to fetch this info from a node.

**Comment by hector100499** [comment]
entendido muchas gracias¡

**Comment by MiKeF05** [comment]
Issue can be closed
