### ISSUE TITLE
Uncaught Error: net::ERR_TIMED_OUT

### ISSUE THREAD

**Issue by jjmiranda** [iotaledger/firefly#1925]
### Issue description

App Version: 1.3.0

platform: macOS
platformVersion: 11.6.1
platformArchitecture: x64
cpuCount: 8
totalMem: 16384.0 MB
freeMem: 72.7 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_TIMED_OUT

### Firefly version

1.3.0

### OS details

macOS

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Open Firefly
2. Wait to get the error
3. End

### Expected behaviour

Handle promise rejection

### Actual behaviour

Firefly show a error window

### Errors

App Version: 1.3.0

platform: macOS
platformVersion: 11.6.1
platformArchitecture: x64
cpuCount: 8
totalMem: 16384.0 MB
freeMem: 72.7 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_TIMED_OUT

**Comment by MiKeF05** [comment]
Do you use a VPN or strict firewall?

**Comment by jjmiranda** [comment]
Nothing, plain internet conecction :)

**Comment by MiKeF05** [comment]
Hm can you try to restart your computer?

**Comment by MiKeF05** [comment]
@jjmiranda Were you able to solve your issue?
