### ISSUE TITLE
The Wallet is rejecting my password

### ISSUE THREAD

**Issue by KeksVanTlou** [iotaledger/firefly#1926]
### Issue description

I know for sure that the password is correct, i have just updated the wallet and transfered some IOTA to the wallet and when i want to preStake my IOTA the wallet is refusing my password.

### Firefly version

currect versoin: 1.3.0

### OS details

windows 7

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.
2.
3.
...
![Capture](https://user-images.githubusercontent.com/36669863/147574284-4e13bd7f-eab9-4a1d-9168-3c6df5446ed7.JPG)

### Expected behaviour

For the Log on to succed

### Actual behaviour

The Log on fails

### Errors

Wrong password

**Comment by MiKeF05** [comment]
Can you please join the IOTA Discord server (https://discord.iota.org/) to get immidiate help?

**Comment by KeksVanTlou** [comment]
> Can you please join the IOTA Discord server (https://discord.iota.org/) to get immidiate help?

I have joined the Discord

**Comment by MiKeF05** [comment]
@KeksVanTlou Were you able to solve your issue on Discord?
