### ISSUE TITLE
Completed Binance IOTA transfer not reflected to Firefly wallet for 45 mins. TX ID: 1dc8e3e473cf7892b90a60f1a2c63eabeaceee7a136151a5ce42a8daf8e0085a

### ISSUE THREAD

**Issue by Oflezer** [iotaledger/firefly#1927]
TX ID : 1dc8e3e473cf7892b90a60f1a2c63eabeaceee7a136151a5ce42a8daf8e0085a
WAllet address : iota1qryg79ly5duhr4qp52x9edf73ej9hlx8m3xcxe6su5nawzgzf75p6ng7uun

**Comment by MiKeF05** [comment]
Have you already synced your wallet? Do you use a ledger device?

**Comment by Oflezer** [comment]
![image](https://user-images.githubusercontent.com/96782155/147576066-23149e02-cc82-4997-a042-c474d21f9050.png)

**Comment by Oflezer** [comment]
ı dont know how to syncronize and no I didnt use a ledger device. just downloaded firefly for windows and did the setup

**Comment by kanggarya** [comment]
I have the same issue, i have sent iota from indodax exchange to firefly wallet, and about 3 hours ago, i didnt receive to my firefly wallet, i did it twice to make sure the trx but it isnt not received yet.
TX id 9e6feaa5fe14df86f4f186a442d76c822fef15e36d834381c8463b56ad1e4ba5
wallet address: atoi1qre9jzfjffpnrq6tfm8wdvkvtrvfh0mhv2jeruh79u4cf20xgfe4qver78p

Please help how to solve this issue?

**Comment by kanggarya** [comment]
@Oflezer sir, is your problem solved? Please share thx

**Comment by MiKeF05** [comment]
@kanggarya You have used a developer profile. Therefore your address starts with atoi... The mainnet addresses all start with iota...

If the withdrawal was completed by your exchange try to create a new profile in Firelfy and DO NOT use developer profile. Then restore your profile with the recovery phrase

**Comment by kanggarya** [comment]
@MiKeF05 thx sir, my problems solve, i unchecked developer and update my profile

**Comment by rajivshah3** [comment]
@Oflezer

**Comment by rajivshah3** [comment]
@Oflezer can you please join our [Discord](https://discord.iota.org) and ask for support in the #help channel?
