### ISSUE TITLE
i can't create new programm wallet

### ISSUE THREAD

**Issue by ovzzvo** [iotaledger/firefly#1928]
### Issue description

I want to create a wallet. At the stage of creating a password, I enter a password, click continue. After that, it writes, a new password is set, but I can not continue registration, since I am not transferred to a new stage.

### Firefly version

firefly-desktop-1.3.0

### OS details

windows 10 pro

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.try to register from my pc)))
2.
3.
...

### Expected behaviour

I want to create a wallet.

### Actual behaviour

 At the stage of creating a password, I enter a password, click continue. After that, it writes, a new password is set, but I can not continue registration, since I am not transferred to a new stage.

### Errors

Firefly v1.3.0
Язык: ru
Валюта: USD
Выбор узла: Автоматически
Платформа: win32
Версия платформы: 10.0.18362
Архитектура платформы: x64
Количество CPU: 8
Всего памяти: 16315.8 MB
Свободная память: 11231.6 MB

-Error log is empty- i chek it

**Comment by MiKeF05** [comment]
Can you please join the IOTA Discord server (https://discord.iota.org/) to get immidiate help?

**Comment by ovzzvo** [comment]
ok

**Comment by ovzzvo** [comment]
the problem was still not resolved

**Comment by ovzzvo** [comment]
i have 2 computer on windows 10 and none of them keep me from creating a wallet, is that ok?

**Comment by MiKeF05** [comment]
So you try to create a profile and stuck at creating a password?

**Comment by ovzzvo** [comment]
Yes, I write my password, click continue, the system approves my password, but there is no next step.
