### ISSUE TITLE
problem to open  firefly 

### ISSUE THREAD

**Issue by GraceCB13B** [iotaledger/firefly#1929]
### Issue description

i just recive some iotas from binance 
and then i just wait to the transaction
Sudenly,  firefly was shut down  and i opened again but when i finished the put corectly my pasword, appeared a little message saying " something went  wrong"

### Firefly version

1.0.0

### OS details

 Windows 10 Version 21H1

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.open firefly
2.send iota from binance  to my wallet 
3.wait the transacction
4. firefly suddenly shut down 
5. opened again the firefly
6. put the correct pasword
7. appeared red  message " something went wrong " 
8. try to put again the pasword
9. firefly is not right 
![image](https://user-images.githubusercontent.com/96783688/147580882-9e39b85e-9000-45b6-9a00-b86cf3582a6f.png)

...

### Expected behaviour

Somebody tells me what is the problem

### Actual behaviour

somebody who tells me how can i fix the issue 

### Errors

![image](https://user-images.githubusercontent.com/96783688/147581116-32615a08-ed57-44df-98dc-4b81f27aa38d.png)

**Comment by MiKeF05** [comment]
Do you use Firefly 1.0?

**Comment by Olatuyitony347** [comment]
Am having the same issue when I want to see 
https://mainnet-node.tanglebay.com/ to firefly it tells me "SOMETHING WENT WRONG"

**Comment by Olatuyitony347** [comment]
Admin help us fix this bug 89 days left to stake

**Comment by MiKeF05** [comment]
@Olatuyitony347 You have trouble with your PIN?

**Comment by GraceCB13B** [comment]
@MiKeF05 MikeF05  ,yes 1.0
like @Olatuyitony347  I have the same problem..

**Comment by GraceCB13B** [comment]
Telegrma group of iota says that we can try to download again the wallet and recovery the profile

**Comment by MiKeF05** [comment]
@GraceCB13B You need to use the latest version 1.3. You can download it here: https://firefly.iota.org/

Please make sure to have your recovery phrase (24 words) and follow the steps:

- Uninstall Firefly 
- Delete the folder in Firefly in C:\Users\[User]\AppData\Roaming. You may need to hide the folder AppData
- Install Firefly 1.3
- Create a new profile and choose the option restore profile with Firefly backup phrase
- Follow the steps in Firefly

**Comment by GraceCB13B** [comment]
@MiKeF05  Thank you so much.
I am going to try right now 
i will keep you inform about the problem team

**Comment by Olatuyitony347** [comment]
@MiKeF05  I don't have problem with my pin,I mean I received that same error"something went wrong" when I want to add the node

**Comment by MiKeF05** [comment]
@Olatuyitony347  I already answered you in https://github.com/iotaledger/firefly/issues/1922

**Comment by GraceCB13B** [comment]
people @MiKeF05 @Olatuyitony347  
Mike is right , we have to download the new version.
I just enter  in the website that shared Mike in the coment , i dowloaded the new version and i could get in my wallet again.
Thank you so much to help me

**Comment by Olatuyitony347** [comment]
@GraceCB13B am using the new version already and the node network adding error still there

**Comment by GraceCB13B** [comment]
@Olatuyitony347 i don't have idea about node ...  create a new tag explaning this problem , maybe somebody knows how can you do

**Comment by rajivshah3** [comment]
Closing the issue as the original issue was resolved
