### ISSUE TITLE
`Response error with status code 503: Service Unavailable`  

### ISSUE THREAD

**Issue by BigGius** [iotaledger/firefly#1935]
### Issue description

cant see my staking

### Firefly version

1.3.0

### OS details

os catalina

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

a

### Actual behaviour

a

**Comment by Hasun07** [comment]
me too

**Comment by Schrankmonster** [comment]
Same here! No Connection to Tangle,Cafe, or Iota. Org Node possible!?!?!?

**Comment by JulienMB23** [comment]
I have the same issue when I want to log in in my firefly wallet

**Comment by Schrankmonster** [comment]
seems its a network problem..................

**Comment by Oceanrhythm** [comment]
same here! 
error type Main unhandled promise rejection
clientError 'error sending request for url (https//chrysalis-nodes.iota.org/api/v1/info

**Comment by Schrankmonster** [comment]
i also cant re-add the Tangle node its thrown away by firefly.. "an error occured " -window occurs when i want to add the tangle node.

**Comment by Doni3240** [comment]
I'm also having the same problem to connect the firefly wallet...

**Comment by MarekR-cpu** [comment]
is the staking still active even though I have this problem as well?

**Comment by nicole-obrien** [comment]
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476126255506501632?s=20
