### ISSUE TITLE
network disconnected

### ISSUE THREAD

**Issue by DerKranke** [iotaledger/firefly#1937]
### Issue description

When I open the Firefly wallet, I receive directly an error message "Netzwerk nicht verbunden" (it is in german), and I see that the network is disconnected.

### Firefly version

1.3.0

### OS details

Windows 10 Pro

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.Start the Software
2.
3.
...

### Expected behaviour

Solve this issue, I need help

### Actual behaviour

Solve this issue, I need help

### Errors

Firefly v1.3.0
Sprache: de
Währung: EUR
Node-Auswahl: Manuell
Plattform: win32
Plattformversion: 10.0.19044
Plattform-Architektur: x64
CPU-Anzahl: 16
Gesamtspeicher: 16304.8 MB
Freier Speicher: 9900.7 MB

**Comment by nicole-obrien** [comment]
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476126255506501632?s=20
