### ISSUE TITLE
Error:network disconnected

### ISSUE THREAD

**Issue by anarbalshirini** [iotaledger/firefly#1938]
### Issue description

Response error with status code 503: Service Unavailable

### Firefly version

1.3.0

### OS details

Windows 10 Pro

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

Can't get my miota

### Actual behaviour

disappointment

**Comment by craigbosward** [comment]
Same problem for me, been checking for over 30 min same error.  was working 8 hours ok.

**Comment by Rcko86** [comment]
I have the same problem, it was working yesterday.

**Comment by nicole-obrien** [comment]
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476126255506501632?s=20
