### ISSUE TITLE
I do not receive the tokens

### ISSUE THREAD

**Issue by witopowa** [iotaledger/firefly#1939]
### Issue description

Yesterday I made a transfer of my iota from binance. In binance it was already confirmed, I have checked several times that the address of my portfolio in Firefly is correct but they do not arrive. It gets me when I log in "Something went wrong"

### Firefly version

Firefly 1.3

### OS details

Windows 10 Enterprise

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

.

### Actual behaviour

.

**Comment by nicole-obrien** [comment]
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476126255506501632?s=20
