### ISSUE TITLE
No network, no staking.

### ISSUE THREAD

**Issue by HRD303** [iotaledger/firefly#1940]
### Issue description

Network doesn't work, staking doesnt work. Pls held

### Firefly version

v1.3.0

### OS details

Win 64 

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

I have 109 mi on a balance. Wanted to stake that in firefly wallet. Did that yesturday. But today no network and no staking.

### Expected behaviour

Staking started yesterday

### Actual behaviour

No network, no staking.

### Errors

0

**Comment by nicole-obrien** [comment]
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476126255506501632?s=20

**Comment by HRD303** [comment]
Hey! I staked that yesterday! And it was OK! I have a screenshot with it. But today there is no staking! I can show.

**Comment by HRD303** [comment]
Here it is
