### ISSUE TITLE
Hi have this error

### ISSUE THREAD

**Issue by a-akin** [iotaledger/firefly#1941]
App Version: 1.3.0

platform: win32
platformVersion: 10.0.19044
platformArchitecture: x64
cpuCount: 4
totalMem: 16329.2 MB
freeMem: 12429.7 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NETWORK_CHANGED

**Comment by nicole-obrien** [comment]
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476126255506501632?s=20
