### ISSUE TITLE
Netzwerk nicht verbunden. Staking nicht erkannt

### ISSUE THREAD

**Issue by gianndavid** [iotaledger/firefly#1942]
### Issue description

Netzwerk kann seit 8:30 Uhr nicht verbunden werden. Staking wurde abgebrochen. Gestaktes Guthaben wird nicht mehr angezeigt. 

Network can't connect. Staking stopped. Staked Token aren't shown anymore.

### Firefly version

1.3.0

### OS details

Windows 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. 
2.
3.
...
.

### Expected behaviour

continue Staking

### Actual behaviour

disapointed

### Errors

ClientError:"Response error with status code 503:Service Unavailable"

**Comment by toerne-moers** [comment]
Same here

**Comment by nicole-obrien** [comment]
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476126255506501632?s=20

**Comment by toerne-moers** [comment]
Sorry, but it is. If I click on the Network-Configuration as suggested, choose the network and click "Info anzeigen". It says "Ein Fehler ist aufgetreten".

**Comment by toerne-moers** [comment]
And the link you posted doesnt work

**Comment by r-c-k** [comment]
Not a bug @toerne-moers  [https://twitter.com/iota/status/1476130331812106244?s=20](https://twitter.com/iota/status/1476130331812106244?s=20)
