### ISSUE TITLE
Error of network on firefly

### ISSUE THREAD

**Issue by Miukolop** [iotaledger/firefly#1943]
### Issue description

Tengo los tres nodos configurados en firefly pero la red aparece en rojo sin conexiones

### Firefly version

1.0.3

### OS details

Windows 10 pro versión 21H1 19043.1415

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

No puedo ver la situación del staking y quiero ver la situación del staking

### Actual behaviour

No tengo red dentro de firefly red desconectada

**Comment by nicole-obrien** [comment]
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476126255506501632?s=20
