### ISSUE TITLE
Firefly Network disconnected

### ISSUE THREAD

**Issue by eruialf** [iotaledger/firefly#1946]
The IOTA staking on Firefly is not detected because the wallet is not connected to the network anymore.

Regards,

Wed, 29 Dec 2021 08:30:30 GMT
ClientError: `Response error with status code 503: Service Unavailable`

**Comment by Miukolop** [comment]
Dame here

**Comment by nicole-obrien** [comment]
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476126255506501632?s=20
