### ISSUE TITLE
IOTA not arrived in Firefly

### ISSUE THREAD

**Issue by tllillong** [iotaledger/firefly#1947]
### Issue description

Using Ledger address in Firefly.
Send from Binance , not arrived (13ours now)

### Firefly version

1.3

### OS details

windows 10

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...
。

### Expected behaviour

？

### Actual behaviour

You can see it on the chain, but it hasn’t arrived in the wallet yet

**Comment by nicole-obrien** [comment]
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476126255506501632?s=20
