### ISSUE TITLE
Staking issue_Network/Node not detected in Firefly

### ISSUE THREAD

**Issue by Lupodanaro** [iotaledger/firefly#1949]
### Issue description

Goodmorning,
 I started yesterday staking and all went well. This morning I see an issue, pls advice:
1. Starting Firefly I get the following message (see attachment, although in Dutch):
A. Network connection lost.
B. Staking not detected.
C. Pls try to change Node (in my settings the Node selection is set at automatic).
D. Balance staking: 0 Mi

Regards and thanks for an advice.

Lupo

### Firefly version

1.3.0

### OS details

mac 12.1

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1. X
2.
3.
...

### Expected behaviour

X

### Actual behaviour

X

**Comment by nicole-obrien** [comment]
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476126255506501632?s=20
