### ISSUE TITLE
Network Disconnected

### ISSUE THREAD

**Issue by Nobody500-89** [iotaledger/firefly#1951]
### Issue description

Network Disconnected, no staking visible

### Firefly version

v1.3.0

### OS details

Windows 10 Home

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

n.i.

### Actual behaviour

n.i.

**Comment by demian78** [comment]
Same with me?!

Wed, 29 Dec 2021 08:59:08 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:59:08 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:58:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:58:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:58:48 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:58:48 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:58:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:58:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:58:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:58:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:58:37 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:58:27 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:58:27 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:58:17 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:58:17 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:58:07 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:58:07 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:57:57 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:57:57 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:57:57 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:57:57 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:57:57 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:57:42 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:57:42 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:57:32 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:57:32 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:57:23 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:57:22 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:57:21 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:57:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:57:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:57:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:57:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:57:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:52:24 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:52:24 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:52:14 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:52:14 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:52:13 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:52:13 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:52:13 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:44:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:44:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:44:25 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:44:25 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:44:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:44:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:44:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:44:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:43:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:43:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:43:45 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:43:45 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:43:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:43:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:43:25 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:43:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:43:20 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:43:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:43:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:43:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:43:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:42:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:42:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:42:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:42:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:42:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:42:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:42:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:42:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:42:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:42:04 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:42:04 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:41:54 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:41:54 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:41:44 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:41:44 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:41:44 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:41:44 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:41:44 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:41:20 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:41:20 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:41:10 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:41:10 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:41:00 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:41:00 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:41:00 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:41:00 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 08:41:00 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Mon, 27 Dec 2021 16:49:46 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Mon, 27 Dec 2021 16:49:26 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Mon, 27 Dec 2021 16:47:52 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Mon, 27 Dec 2021 16:46:26 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Mon, 27 Dec 2021 16:42:46 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Mon, 27 Dec 2021 16:38:59 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Mon, 27 Dec 2021 16:36:10 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Mon, 27 Dec 2021 16:35:10 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Mon, 27 Dec 2021 16:34:08 GMT
ClientError: `Response error with status code 404: 404 page not found
`

**Comment by Hangman2021** [comment]
I have the same problem

**Comment by timooobck** [comment]
same for me. I have the following specs:

`Firefly v1.3.0
Sprache: de
Währung: USD
Node-Auswahl: Automatisch
Plattform: macOS
Plattformversion: 10.15.7
Plattform-Architektur: x64
CPU-Anzahl: 4
Gesamtspeicher: 8192.0 MB
Freier Speicher: 2726.7 MB`

**Comment by Cavale1ro** [comment]
I have the same problem, first entry in the error log at Wed, 29 Dec 2021 06:52:48 GMT.
I tried switching node selection to manual in Advanced Settings and changing the primary node but I'm getting "network disconnected" status / ClientError: `Response error with status code 503: Service Unavailable on both listed nodes shown below.
https://chrysalis-nodes.iota.org
https://chrysalis-nodes.iota.cafe

diag info:

Firefly v1.3.0
Language: en
Node selection: Automatic
Platform: win32
Platform Version: 10.0.22000
Platform Architecture: x64
CPU Count: 12
Total Memory: 16181.9 MB
Free Memory: 9489.4 MB

**Comment by nicole-obrien** [comment]
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476126255506501632?s=20
