### ISSUE TITLE
Staking not detected

### ISSUE THREAD

**Issue by dkdwien** [iotaledger/firefly#1952]
### Issue description

ClientError: 'Response error with satus code 503: Service Unavailable'
Is there a way to fix it?

### Firefly version

1.3.0

### OS details

macOS 12.1

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. open firefly
2. no stake button enabled
3. an error message pops up as "something went wrong"

### Expected behaviour

staking button needs to be enabled

### Actual behaviour

Staking not detected and not enabled

Message: No staking events detected: Open network configuration in Advanced Settings and make sure the current node has the "Participation" feature by clicking "View Info".

### Errors

ClientError: 'Response error with satus code 503: Service Unavailable'

**Comment by nicole-obrien** [comment]
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476126255506501632?s=20
