### ISSUE TITLE
Staking not detected 

### ISSUE THREAD

**Issue by ttfit007** [iotaledger/firefly#1953]
### Issue description

When I logon to my wallet I can see my balance but I am not able to do anything. The wallet shows that I have added iotas for staking (see picture) but it does not show anything. The following issue is detected:

Wed, 29 Dec 2021 09:04:12 GMT
ClientError: `Response error with status code 503: Service Unavailable

<img width="308" alt="staking" src="https://user-images.githubusercontent.com/96818244/147646372-c1dee537-ee42-4a89-b620-ca5849e4c8b5.PNG">

### Firefly version

1.3.0

### OS details

Windows 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. logon to the wallet 
2.nothing happens 
3.message appears that a mistake has occured
4.staking is not showing anything 

### Expected behaviour

Would like to be able to logon to the wallet and see my balance and also see the progress of staking.

### Actual behaviour

I can logon to my wallet but I am not able to do anything else. 

### Errors

<img width="339" alt="Error_2021" src="https://user-images.githubusercontent.com/96818244/147646132-e8164c2f-8b1e-4db3-8b5f-0d4deb48330a.PNG">

**Comment by nicole-obrien** [comment]
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476126255506501632?s=20
