### ISSUE TITLE
Keinstaking

### ISSUE THREAD

**Issue by kjklj** [iotaledger/firefly#1954]
### Issue description

Keine Verbindung, somit kein Staking. Node wechsel wird vorgeschlagen, hilft nicht

### Firefly version

1.3.0

### OS details

Win 10 Pro

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Einloggen
2. Fehlermeldung
3. Node wechsel hilft nicht
...

### Expected behaviour

Bitte beheben

### Actual behaviour

Bitte beheben

**Comment by fscha64** [comment]
Same issue !!

**Comment by nicole-obrien** [comment]
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476126255506501632?s=20
