### ISSUE TITLE
ERROR CODE 503

### ISSUE THREAD

**Issue by Benji134** [iotaledger/firefly#1955]
### Issue description

Wed, 29 Dec 2021 09:21:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:17 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:17 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:50 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:47 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:45 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:30 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:30 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:25 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:45 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:15 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Wed, 29 Dec 2021 09:14:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:52 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:52 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:45 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:25 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:24 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Mon, 27 Dec 2021 23:55:51 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Started staking yesterday, but now the wallet is disconnected and my asmb and smr Tokens are no longer displayed.

### Firefly version

1.3

### OS details

Windows 10 Home

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.Its reproduceing by itself
2.
3.
...

### Expected behaviour

Seems to be an network issue

### Actual behaviour

no connection and tokens are gone

### Errors

Wed, 29 Dec 2021 09:21:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:17 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:17 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:50 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:47 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:45 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:30 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:30 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:25 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:45 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:15 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Wed, 29 Dec 2021 09:14:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:52 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:52 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:45 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:25 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:24 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Mon, 27 Dec 2021 23:55:51 GMT
ClientError: `Response error with status code 404: 404 page not found
`

**Comment by nicole-obrien** [comment]
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476126255506501632?s=20
