### ISSUE TITLE
Response error with status code 503: Service Unavailable

### ISSUE THREAD

**Issue by timooobck** [iotaledger/firefly#1956]
### Issue description

since this morning no more staking possible:
"Response error with status code 503: Service Unavailable" 

staking counter is at 0. 
yesterday staking was possible without problems. 

### Firefly version

1.3.0

### OS details

MacOS 10.15.7

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

-

### Actual behaviour

-

### Errors

Wed, 29 Dec 2021 09:20:43 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:43 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:25 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:25 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:14 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:04 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:04 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:44 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:44 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:24 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:24 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:14 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:04 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:04 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:54 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:54 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:43 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:43 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:23 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:23 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:13 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:13 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:54 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:54 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:44 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:44 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:25 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:25 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:14 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:14 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:04 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:17:04 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:54 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:43 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:43 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:23 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:23 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:13 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:13 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:03 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:16:03 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:53 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:53 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:44 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:44 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:34 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:25 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:25 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:04 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:15:04 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:44 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:44 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:25 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:24 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:03 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:14:03 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:53 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:53 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:43 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:43 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:23 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:23 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:13 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:13 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:03 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:13:03 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:12:53 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:12:53 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:12:43 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:12:43 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:12:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:12:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:12:23 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:12:23 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:12:22 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:12:22 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:12:13 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:12:13 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:12:03 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:12:03 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:11:53 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:11:53 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:11:51 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:11:43 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:11:43 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:11:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:11:33 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Wed, 29 Dec 2021 09:11:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:11:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:11:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:11:17 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:11:17 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:11:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:11:07 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:11:07 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:11:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:10:57 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:10:57 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:10:57 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:10:57 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:10:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

**Comment by nicole-obrien** [comment]
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476126255506501632?s=20
