### ISSUE TITLE
Network Disconnected

### ISSUE THREAD

**Issue by iamalazar** [iotaledger/firefly#1957]
### Issue description

Network Disconnected

Wed, 29 Dec 2021 09:25:32 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:25:32 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:25:31 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:25:31 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:25:22 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:25:22 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:25:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:25:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:25:02 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:25:02 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:24:52 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:24:52 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:24:42 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:24:42 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:24:32 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:24:32 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:24:22 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:24:22 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:24:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:24:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:24:02 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:24:02 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:23:52 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:23:52 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:23:42 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:23:42 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:23:32 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:23:32 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:23:22 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:23:22 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:23:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:23:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:23:02 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:23:02 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:22:52 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:22:52 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:22:42 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:22:42 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:22:32 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:22:32 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:22:22 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:22:22 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:22:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:22:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:22:02 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:22:02 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:52 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:52 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:42 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:42 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:32 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:32 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:22 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:22 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:02 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:02 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:21:02 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:52 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:52 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:42 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:42 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:32 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:32 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:22 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:22 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:02 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:20:02 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:52 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:52 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:52 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:52 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:19:52 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:41 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:41 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:31 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:31 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:31 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:31 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:31 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:13 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:13 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:03 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:03 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:03 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:03 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:18:02 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Mon, 27 Dec 2021 11:19:43 GMT
LatestAccountIsEmpty: can't create accounts when the latest account doesn't have message history and balance

### Firefly version

1.3.0

### OS details

Mac

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

n.i.

### Actual behaviour

n.i 

### Errors

no response

**Comment by nicole-obrien** [comment]
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476126255506501632?s=20
