### ISSUE TITLE
Staking

### ISSUE THREAD

**Issue by Hartke1984** [iotaledger/firefly#1960]
### Issue description

Wed, 29 Dec 2021 09:39:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:39:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:39:30 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:39:30 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:39:22 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:39:22 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:39:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:39:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:39:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:39:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:39:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:35:18 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:35:18 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:35:08 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:35:08 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:48 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:48 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:28 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:28 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:18 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:18 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:08 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:08 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:48 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:48 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:28 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:28 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:18 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:18 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:08 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:08 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:48 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:48 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:28 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:28 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:18 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:18 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:08 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:08 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:48 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:48 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:28 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:28 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:18 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:18 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:08 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:08 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:48 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:48 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:28 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:28 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:17 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:17 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:07 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:07 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:29:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:29:57 GMT
ClientError: `Response error with status code 503: Service Unavailable`

### Firefly version

1.3.0

### OS details

windows 10

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

Weis nicht

### Actual behaviour

Staking anzeige Of gestern ging es noch

### Errors

Wed, 29 Dec 2021 09:39:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:39:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:39:30 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:39:30 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:39:22 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:39:22 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:39:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:39:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:39:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:39:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:39:12 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:35:18 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:35:18 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:35:08 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:35:08 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:48 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:48 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:28 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:28 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:18 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:18 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:08 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:08 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:48 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:48 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:28 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:28 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:18 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:18 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:08 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:08 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:48 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:48 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:28 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:28 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:18 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:18 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:08 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:08 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:48 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:48 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:28 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:28 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:18 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:18 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:08 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:08 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:48 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:48 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:38 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:28 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:28 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:17 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:17 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:07 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:07 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:29:58 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:29:57 GMT
ClientError: `Response error with status code 503: Service Unavailable`

**Comment by nicole-obrien** [comment]
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476126255506501632?s=20
