### ISSUE TITLE
Staking not detected

### ISSUE THREAD

**Issue by dzudohonor** [iotaledger/firefly#1961]
### Issue description

Staking not detected. Both nodes doesn't work - Service unavaible

### Firefly version

1.3.0

### OS details

Windows 7

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

I want again stack my IOTA

### Actual behaviour

I couldn't staking iota

### Errors

Wed, 29 Dec 2021 10:09:14 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:09:14 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:09:04 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:09:04 GMT
ClientError: `Response error with status code 503: Service Unavailable`

**Comment by nicole-obrien** [comment]
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476126255506501632?s=20
