### ISSUE TITLE
Nodo Firefly

### ISSUE THREAD

**Issue by Rafa1981** [iotaledger/firefly#1964]
### Issue description

Hi, in order to continue staking when problems will be fixed, is better to have the node of firefly in automatic or ww have to set it in manual and as primary: https://mainnet-node.tanglebay.com/ ?

### Firefly version

1.3

### OS details

Windows 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Staking stops
2. Which node we have to use now

### Expected behaviour

Start staking as soon as the problem is fixed

### Actual behaviour

....

**Comment by r-c-k** [comment]
Both will work. Adding another node like tanglebay is optional.

**Comment by r-c-k** [comment]
Issue can be closed.
