### ISSUE TITLE
ClientError: `Response error with status code 503: Service Unavailable`

### ISSUE THREAD

**Issue by UgoGard** [iotaledger/firefly#1965]
### Issue description

Wed, 29 Dec 2021 10:16:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:16:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:16:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:16:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:16:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:16:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

### Firefly version

Firefly v1.3.0

### OS details

Mac Os X 10.13.6

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Open Firefly wallet
2. Go to "Staking"
3. Check network status 
4. Check error log 

### Expected behaviour

Network status should be "connected" and Wed, 29 Dec 2021 10:16:26 GMT
ClientError: `Response error with status code 503: Service Unavailable` should NOT happen.

### Actual behaviour

Network status is "Disconnected" 

### Errors

Wed, 29 Dec 2021 10:16:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

**Comment by playwincrypto** [comment]
I have the same issue.

![image](https://user-images.githubusercontent.com/88676194/147653604-7be9b237-0126-46e4-a28e-56a4832f36c8.png)

**Comment by nicole-obrien** [comment]
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476130331812106244?s=20

**Comment by mullos1** [comment]
i am the same
