### ISSUE TITLE
Network not connected

### ISSUE THREAD

**Issue by Stressfrei** [iotaledger/firefly#1968]
### Issue description

When i open the program, the failure come up: ClientError: `Response error with status code 404: 404 page not found. I can't switch the node and i can't see my staking.

### Firefly version

1.3.0

### OS details

Windows 11 Pro Version 21H2 Build 22000.376

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.  Open Firefly

### Expected behaviour

opne firefly and look my stakings

### Actual behaviour

its not possible the view my stakings

### Errors

Wed, 29 Dec 2021 10:27:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:27:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:27:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:27:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:26:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:26:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:26:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:26:45 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:26:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:26:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:26:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:26:25 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:26:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:26:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:26:06 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:26:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:25:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:25:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:25:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:25:45 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:25:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:25:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:25:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:25:25 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:25:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:25:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:25:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:25:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:24:56 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:24:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:24:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:24:45 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:24:36 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:24:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:24:26 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:24:25 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:24:16 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:24:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:24:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:24:05 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): connection error: connection reset`

Wed, 29 Dec 2021 10:23:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:23:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:23:45 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:23:45 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:23:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:23:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:23:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:23:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:23:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:21:41 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:21:41 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:21:39 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:21:34 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:21:31 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:21:31 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:21:21 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:21:21 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:21:12 GMT
ClientError: `Response error with status code 503: <html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

`

Wed, 29 Dec 2021 10:21:11 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:21:11 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:21:08 GMT
ClientError: `Response error with status code 503: <html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

`

Wed, 29 Dec 2021 10:21:05 GMT
ClientError: `Response error with status code 503: <html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

`

Wed, 29 Dec 2021 10:21:01 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:21:01 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:20:51 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:20:51 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:20:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:20:46 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:20:41 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:20:41 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:20:40 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:20:40 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:20:31 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:20:31 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:20:21 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:20:21 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:20:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:20:11 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:20:11 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:20:01 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:20:01 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:20:00 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:20:00 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 10:20:00 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:35:54 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:35:53 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:35:44 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:35:43 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:35:34 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:35:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:35:24 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:35:23 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:35:13 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:35:13 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:35:04 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:35:03 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:54 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:53 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:44 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:43 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:34 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:24 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:23 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:14 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:13 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:04 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:34:03 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:54 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:53 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:44 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:43 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:34 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:24 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:23 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:14 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:13 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:04 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:33:03 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:54 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:53 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:44 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:43 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:34 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:24 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:23 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:14 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:13 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:04 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:32:03 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:54 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:53 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:44 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:43 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:34 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:24 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:23 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:14 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:14 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:04 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:31:03 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:54 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:53 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:44 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:43 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:34 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:23 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:23 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:14 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:13 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:03 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:30:03 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:29:53 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:29:53 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:29:43 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:29:43 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:29:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:29:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:29:29 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:29:23 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:29:23 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:29:13 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:29:13 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:29:04 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:29:03 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:28:53 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:28:53 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:28:53 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:28:53 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:28:53 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:28:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:28:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:28:33 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:28:25 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:28:25 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:28:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:28:15 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:28:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:28:05 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:27:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:27:55 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:27:54 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:27:45 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:27:45 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:27:42 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:27:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:27:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:27:35 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:27:34 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Wed, 29 Dec 2021 09:27:34 GMT
ClientError: `Response error with status code 503: Service Unavailable`

Tue, 28 Dec 2021 18:41:24 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qqghz6quxsrsr5mef6ne8yfzxhl2ry0h97vjgs4qesfn9utlftdd5dmsgng): error trying to connect: tls handshake eof

Tue, 28 Dec 2021 18:40:20 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Tue, 28 Dec 2021 18:40:19 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): operation timed out`

Tue, 28 Dec 2021 17:04:16 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qqghz6quxsrsr5mef6ne8yfzxhl2ry0h97vjgs4qesfn9utlftdd5dmsgng): error trying to connect: tls handshake eof

Tue, 28 Dec 2021 14:02:17 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Tue, 28 Dec 2021 14:02:16 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): operation timed out`

Tue, 28 Dec 2021 13:36:46 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qqghz6quxsrsr5mef6ne8yfzxhl2ry0h97vjgs4qesfn9utlftdd5dmsgng): error trying to connect: tls handshake eof

Tue, 28 Dec 2021 08:12:18 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Tue, 28 Dec 2021 06:09:47 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qqghz6quxsrsr5mef6ne8yfzxhl2ry0h97vjgs4qesfn9utlftdd5dmsgng): error trying to connect: tls handshake eof

Tue, 28 Dec 2021 06:09:22 GMT
ClientError: `Response error with status code 404: 404 page not found

**Comment by nicole-obrien** [comment]
This is not a bug with firefly, the network is currently not issues new milestones. Please follow official IOTA channels to be notified when this issue is resolved. https://twitter.com/iota/status/1476130331812106244?s=20
