### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by a-akin** [iotaledger/firefly#1970]
### Issue description

Wont pop up to my wallet dashboard after entring my pin to login.

Please help

### Firefly version

1.3.0

### OS details

platformVersion: 10.0.19044

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

I expected to login to my dashboard

### Actual behaviour

Not redirecting to my dashboard

### Errors

Not redirecting to my dashboard

**Comment by MiKeF05** [comment]
Please join the official IOTA discord server (https://discord.iota.org/) and go to the help channel to get immediate help with this.
