### ISSUE TITLE
Can't Stacking

### ISSUE THREAD

**Issue by Baial5** [iotaledger/firefly#1971]
### Issue description

I have my IOTA in Firefly since 28th afternoon, and when I press the stacking button, a window appears with my IOTA amount and next to, it a button that says: **synchronizing**. And it doesn't advance, it doesn't give me the opcion of the next step.

### Firefly version

1.3.0

### OS details

Windows 10 Pro version 20H2

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.Open and unlock the wallet
2.Press Stacking button
3.
...

### Expected behaviour

1. Press stacking button
2. Choose Crypto for reward
3. Stacked

### Actual behaviour

1. press stacking button
2. synchronizing
3. NO MORE........

### Errors

No errors

**Comment by MiKeF05** [comment]
Do you have a pending transaction? Do you use a ledger?

**Comment by Baial5** [comment]
I don't have pending transaction, and I don't use a ledger.
Thanks.

**Comment by Baial5** [comment]
Oh!! excuse me! In transactions figure an old transaction pending. Could that be the cause of the problem? How can I solve that?
Thanks!!

**Comment by Baial5** [comment]
But this pending transaction was done correctly. in the exchange it appears as completed

**Comment by Baial5** [comment]
Solved!! I have created a second wallet.
