### ISSUE TITLE
Wallet is stuck in syncing status

### ISSUE THREAD

**Issue by galeamat** [iotaledger/firefly#1973]
### Issue description

I wanted to unstake tokens due to new tokens received in same wallet. Once I pressed unstake, the wallet remained stuck in syncing status. 

### Firefly version

1.3.0

### OS details

Windows

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Stake tokens
2.Send tokens to same wallet
3. Unstake tokens
...
![iotafirefly-sync](https://user-images.githubusercontent.com/96837465/147686193-da455fbd-ecb5-496b-b3ea-280d651a6a51.PNG)

### Expected behaviour

once unstaked, wallet would be free to stake again

### Actual behaviour

wallet stuck in syncing mode and tokens cannot be unstaked or staked

**Comment by MiKeF05** [comment]
Please join the official IOTA discord server (https://discord.iota.org/) and go to the help channel to get immediate help with this.

**Comment by galeamat** [comment]
I found a workaround, by transferring the tokens to another wallet. Then one received I staked them.

**Comment by cvarley100** [comment]
Fixed in 1.3.1.
