### ISSUE TITLE
IOTA not arrived to my Firefly

### ISSUE THREAD

**Issue by Leandro19786** [iotaledger/firefly#1974]
I have the problem that my IOTA have not arrived at Firefly, I sent it from Binance and the transaction was successful in minutes in binance, but it will already be 24 hours, and I have not received it in my firefly wallet
TX ID:
235afdabcfb57278aa4eedace7d7574853e3b0d5709e3e5f0662523c1b310153

It seems like there is a problem with the wallet.

**Comment by r-c-k** [comment]
Please visit the IOTA Discord ([https://discord.iota.org](https://discord.iota.org)). Resolving your issue there will be much more efficient.
Visit the `#help` channel or contact me via direct message @rck#3810 if you want.

**Comment by Leandro19786** [comment]
> Please visit the IOTA Discord (https://discord.iota.org). Resolving your issue there will be much more efficient. Visit the `#help` channel or contact me via direct message @rck#3810 if you want.

is already solved. I thank r-c-k very much, who helped me too much to solve it, thanks to him I solved it.
