### ISSUE TITLE
incorrect balance

### ISSUE THREAD

**Issue by ERM91** [iotaledger/firefly#1976]
### Issue description

firefly shows balance = zero, but I see only one transaction: transferred x Mi to this account.

have someone the same issue?

### Firefly version

1.3

### OS details

Windows 10 home

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

.

### Actual behaviour

.

### Errors

no error

**Comment by r-c-k** [comment]
Please join the IOTA Discord ([https://discord.iota.org](https://discord.iota.org)) and visit the **#help** channel so we can effectively assist you with this issue.
Please keep in mind to never share your seed, passphrase or any kind of sensitive information with anyone.
