### ISSUE TITLE
Firefly disconnected, node plugin not found

### ISSUE THREAD

**Issue by CHK888** [iotaledger/firefly#1979]
### Issue description

Hi, my firefly is disconnected and it says node plugin not found.
It was fine yesterday, but today is disconnected and staking is not available. As of yesterday i successfully staked. 

Please help. Thank you.

### Firefly version

1.3.0

### OS details

Windows 10 Home

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

It should be connected

### Actual behaviour

Firefly disconnected.

**Comment by CHK888** [comment]
i tried changing the node to  https://mainnet-node.tanglebay.com/ , however it dosen't allow the change with the same error message that node plugin error not found.

**Comment by cryptomate01** [comment]
Hi IOTA team, I am getting the same error message and Firefly is not connected. Please suggest a solution. 
Thank you!

**Comment by MiKeF05** [comment]
Issue has been resolved on Discord https://discord.com/channels/397872799483428865/398499876935303186/926132612488118342
