### ISSUE TITLE
Main Unhandled Promise Rejection

### ISSUE THREAD

**Issue by TomasMoskala** [iotaledger/firefly#1981]
### Issue description

App Version: 1.3.0

platform: win32
platformVersion: 10.0.19043
platformArchitecture: x64
cpuCount: 4
totalMem: 8104.1 MB
freeMem: 822.7 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NAME_NOT_RESOLVED

### Firefly version

1.3.0

### OS details

win32 platformVersion: 10.0.19043

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

Runtime error

### Expected behaviour

App running

### Actual behaviour

Runtime error without interaction

### Errors

App Version: 1.3.0

platform: win32
platformVersion: 10.0.19043
platformArchitecture: x64
cpuCount: 4
totalMem: 8104.1 MB
freeMem: 822.7 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NAME_NOT_RESOLVED

**Comment by MiKeF05** [comment]
Looks like a DNS issue. Do you use a VPN or some strict firewall?

**Comment by masoud1108** [comment]
I have the same issue

App Version: 1.3.0

platform: win32
platformVersion: 6.1.7601
platformArchitecture: x64
cpuCount: 4
totalMem: 3994.4 MB
freeMem: 1673.4 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NETWORK_IO_SUSPENDED

**Comment by MiKeF05** [comment]
Same for you. Do you have a VPN or strict firewall? Are you connected to the internet?

**Comment by masoud1108** [comment]
I connected to the internet. I connected without VPN 
Fund migration is completed and i receive this message " your funds will become available shortly" but after around 12 hour my balance is 0 Mi

**Comment by MiKeF05** [comment]
@masoud1108 Please create a new profile and restore your wallet with the 24 words. Your funds should become available in the new profile.

**Comment by cvarley100** [comment]
Duplicate issue.
