### ISSUE TITLE
Wallet Address Is Not Correct

### ISSUE THREAD

**Issue by mucahithy** [iotaledger/firefly#1989]
### Issue description

My Wallet address begins with "atoi1....6gm" instead of "iota1...6gm".

I tried to deleting account and create a new one but again address was not correct. 

So that I cant send token this address and dont allowed create new wallet. 

![image](https://user-images.githubusercontent.com/45150935/147785638-9c2fe511-67d8-4078-ae5b-f0a180748d51.png)
 

### Firefly version

1.3.0

### OS details

windows 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.aa
2.
3.
...aa

### Expected behaviour

a

### Actual behaviour

aa

**Comment by r-c-k** [comment]
You created a developer profile. Please create a new profile without ticking the "Developer profile" checkbox.

**Comment by mucahithy** [comment]
thank you
