### ISSUE TITLE
Delay between latest transactions and wallet overview [1.3.1-beta]

### ISSUE THREAD

**Issue by t00k** [iotaledger/firefly#1991]
### Issue description

As in older versions there is a delay between the "Latest transactions" and the "Wallet overview".

Split up funds between two or more wallets. Send internal transfer from Wallet 1 to Wallet 2. Both sent tx and received tx gets solid inside "Latest transactions" but nothing happens in the wallet overview, until you either click the spinning button to refresh latest tx (which then also updates wallet overview), or change from staking tab and back to wallet.

### Firefly version

1.3.1-beta

### OS details

Windows 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Create 2 or more wallets
2. Send internal transfer
3. Watch latest tx get updated, but wallet overview be stuck
...

Isn't like this every single time but enough for it to be an issue.

### Expected behaviour

Both Wallet overview and Latest transactions should update when the transactions get confirmed.

### Actual behaviour

One of the views lag behind.

**Comment by r-c-k** [comment]
Can confirm on macOS 12.1
<img width="1392" alt="Bildschirmfoto 2021-12-31 um 20 53 53" src="https://user-images.githubusercontent.com/17240275/147837648-7885115f-5e70-4a8a-8e0f-1df38e8fff3e.png">

**Comment by nicole-obrien** [comment]
@t00k @cvarley100 was this fixed in 1.3.1 or 1.3.2?

**Comment by MiKeF05** [comment]
With the change to a single wallet view this issue doesn´t exist anymore.
