### ISSUE TITLE
Miota nicht auf Bitpanda Wallet angekommen

### ISSUE THREAD

**Issue by tackar66** [iotaledger/firefly#1993]
Hallo, ich habe von der Firefly Wallet Miota an Bitpanda gesendet gegen 19:34 Uhr und sie sind noch nicht angekommen, was kann ich tun?

**Comment by MiKeF05** [comment]
Bitte bei der Exchange auf Bestätigung warten. Exchanges benötigen meist etwas länger, um die Token gutzuschreiben.

**Comment by MiKeF05** [comment]
Issue can be closed as it is not related to Firefly

**Comment by tackar66** [comment]
Ok,
hatte kurz vorher eine kleine Menge Iota an Bitpanda gesendet, das ging recht schnell.
