### ISSUE TITLE
Whitescreen when opening Firefly Wallet

### ISSUE THREAD

**Issue by Jamiemack14** [iotaledger/firefly#1994]
### Issue description

This is the second time this has happened, and to neutralise it last time I made a new wallet. But now that my money is being staked earning the airdrop tokens, I wanted to add some more funds. However, I can't access my wallet.

When starting up firefly wallet, everything loads properly. It then shows my accounts and I am able to click on it. I then am allowed to input my 6 digit passcode, and after I input it, the screen goes completely white. 

This is where the issue occurs. My account worked yesterday but it does not work now. I would like some help please.

Thanks

### Firefly version

version 1.3.0

### OS details

mac OS X El Capitan version 10.11.6

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Open firefly
2. Select wallet
3. Enter Passcode
4. Screen becomes white and unusable.
...

### Expected behaviour

I was suppose to access my wallet and see my holdings

### Actual behaviour

The screen is white

### Errors

![Screen Shot 2021-12-30 at 4 01 14 PM](https://user-images.githubusercontent.com/96892656/147793243-3716689b-3274-4a91-8e9d-a88b92ee1588.png)

**Comment by t00k** [comment]
mac OS X El Capitan version 10.11.6 is not supported by Firefly.
El Capitan got the latest update in 2016. Please update to a newer version, especially since you are using this computer for crypto.

El Capitan seems to be end of life and do not receive any security updates anymore.

**Comment by MikeRogero** [comment]
This same behavior is occurring on Windows 10 version 19042.1466 currently.   Should this be reopened?
