### ISSUE TITLE
Why the recived address is changed ?

### ISSUE THREAD

**Issue by jasonpakio** [iotaledger/firefly#1995]
My wallet recived addreess has changed in a day ,so what happed?

**Comment by jasonpakio** [comment]
Hello?

**Comment by MiKeF05** [comment]
You need to be a little bit patient when dropping an issue.
Firefly generates a new receive address when the one before was used. But addresses are reusable and you also are able to use the one before over and over again. This is due to privacy reasons.

**Comment by begonaalvarezd** [comment]
Additionally, if you click on your wallet > the three dots next to the balance > view address history, you can see your full list of addresses with its balances.

![image](https://user-images.githubusercontent.com/3624944/147818631-af26d562-740f-4e57-a6ea-305af8da607b.png)

Closing the issue, feel free to reopen if needed 🙏🏼
