### ISSUE TITLE
i newbie

### ISSUE THREAD

**Issue by pezhman47** [iotaledger/firefly#1996]
### Issue description

App Version: 1.3.0

platform: win32
platformVersion: 6.1.7601
platformArchitecture: x64
cpuCount: 2
totalMem: 4093.0 MB
freeMem: 338.4 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NAME_NOT_RESOLVED

### Firefly version

1.3.0

### OS details

windows 7

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.i newbie
2.
3.
...

### Expected behaviour

i newbie

### Actual behaviour

i newbie

### Errors

App Version: 1.3.0

platform: win32
platformVersion: 6.1.7601
platformArchitecture: x64
cpuCount: 2
totalMem: 4093.0 MB
freeMem: 338.4 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NAME_NOT_RESOLVED

**Comment by cvarley100** [comment]
Closing as this is a duplicate issue. Please ask for help in the #help channel on https://discord.iota.org.
