### ISSUE TITLE
My IOTA FF Wallet has disappeared with my staked tokens even after I  reinstalled with 24 word phrase 

### ISSUE THREAD

**Issue by ef4ort** [iotaledger/firefly#1997]
Hello there 
I need some help with getting my staked tokens reinstalled following a wallet crash on my Win 64 Bit PC about  12 hours ago  
I tried to reinstall the wallet from the application using existing details to import a new wallet with my 24 word phrase as copied down 
However i was surprised that this step only brought back the Wallet without the contents as staked .  . All i have now was a screenshot i took earlier to show a friend on what The Wallet looks like while trying to install it on the mobile phone    
This screenshot is attached to this email below   
 Please advise on how to reclaim the  140 Miota  token staked since  28 December 2021 together with all the acrued Assembly and Shimmer Tokens 
 Thank you 
 Kind regards 
 Adekunle 
 
![image](https://user-images.githubusercontent.com/42033270/147855855-b7f6f870-c2fb-491e-9d6e-cfdddd7bb83b.png)

**Comment by MiKeF05** [comment]
Hello,
so you actually have restored your wallet with the correct balance? But the rewards are not displayed and the staking overview says "Staking not detected"?

**Comment by ef4ort** [comment]
i have restored the application from the original Firefly . 1.30  download that meant installing the application again on my PC without a problem and i had chosen the 24 word mnemonic phrase option When my wallet was back up however it was just like another clean wallet without evidence of any transaction including the staked tokens but from what i sent earlier  you would see that the original wallet  had two deposits of  80 and then 60 Miota deposits bought from 2 different exchanges . allowing me to stake the total of  140 Mi , Then i had been able to see the rewards coming in as staking commenced.  There was a momentary ceasure in activitiy  then the rewards  resumed . I know i had  more than   1 millions Shimmers and going to 7 Assenbkues tokens .  In essence  what i am saying was that i was able to get the Wallet up using the same info i had used earlier  before the staking  but when the wallet came up it had no content to it .     Staking was not detected .  and my originial  Transaction including Deposits was not found in the restored wallet

**Comment by ef4ort** [comment]
Niethere the balance nor the staking status is displayed in the restored
wallet .  i was also surprised that it still accepted the same name i used
for the wallet that disappeared while trying to restore it with exactly the
same details and passwords that i had used earlier on so as to keep the
details intact to help retract my funds   If my previous details were
intact on the server then I would expect it to say that the Name ef4ort is
no longer available for the wallet .
This morning on attempting to access the wallet again another error came up
attached below"

[image: image.png]

**Comment by t00k** [comment]
Make sure you did not check the box for developer profile when setting up your account.

Do not use developer profiles in the Firefly Wallet if you are not a Developer. A developer Profile will connect you to the Testnet and generate addresses that do not work on IOTA Mainnet. These testnet addresses start with "atoi1" instead of the mainnet addresses "iota1".
You need an address from a normal profile to withdraw IOTA tokens from exchanges. These addresses start with "iota1........".
Log out of the developer profile and create a new profile without the developer modus activated.

If you have accidentally created a developer profile and did send funds to an "atoi1" address you have not lost your funds. 
To make these funds accessible you need to use the "recover a wallet" function in Firefly while creating a new profile. 
Create a "non-developer" profile and use the 24 words that you have saved from your "developer profile" to restore this new profile (non-developer).
Your funds will show up in this new profile.

**Comment by ef4ort** [comment]
Thank you for the suggestions here is the address that came up with the new installation after the first one with staked tokens crashed "iota1qqez7xtsy7v6enw7pa58w5lta602t3hwed4vw0ve90pn76dmx0wpqcajffr"  It is however not the same wallet address that contained my staked tokens  and to which initial iOta funds that was later staked was sent .  
That address on the same computer and the same wallet  was :iota1qr24cgygmh5g4scvuxx9gaf4uar0q59gpfkkzmgel3dhnxx8t9exww7u8pa

What i am not about is what is responsible for the disparity in the two different addresses that came up before and after the crash   If i use the same  recovery phrase for my Wallet  i expect to have essentially the same receiver code for the same IOTA Firefly wallet address in the same  Environment .  
i did not choose the Developer profile as you can see the wallet address is not starting   with istor .  and the contents of the wallet is pasted below  
![image](https://user-images.githubusercontent.com/42033270/147892954-be207709-4c5a-4017-a9b1-5587b2ac14c8.png)

**Comment by ef4ort** [comment]
This is all just too confusing to me

**Comment by ef4ort** [comment]
i did not create a developer profite because the new wallet that came up
with my  stored 24 word passphrase  have a receiver code starting with iota
but it came with a completelely different address than the one i sent the
funds to  for staking earlier and same one with which the funds were
staked.
its very confusing to me .  right now because i dont know if i should
delete the new emply wallet then reinstall it again with the hope of
getting something comparable to my previous wallet and its content before
the application crashed out of my pC
[image: image.png]

**Comment by MiKeF05** [comment]
It is okay that the receiver address is another one. Firefly automatically generates a new receiver address after you have used the one before. It is for privacy reasons. But you also can use the address before. 
You can also have a look at all generated addresses in the wallet by clicking on the wallet -> click on the three dots -> view address history.

**Comment by t00k** [comment]
Please update to 1.3.2, then add a new profile, using the same 24 words/stronhold again.

**Comment by ef4ort** [comment]
Thank you for the headsup .
Do i need to uninstall my existing app on the PC before i do the upgrade ?
or just follow he promp to upgrade download the upgrade then  add a  new
profile as advised
Thank you

**Comment by ef4ort** [comment]
The wallet has now been successfully recovered following the upgrade and
additional profile creation as attached below in screenshot
Thank you for the support

[image: image.png]

**Comment by MiKeF05** [comment]
I guess this issue can be closed

**Comment by ef4ort** [comment]
Yes  i checked again this morning and the app is still stable with the contents intact .  
Will resolve the job thnks  again for positive directives.

**Comment by ef4ort** [comment]
successfully resolved
