### ISSUE TITLE
Ledger Migrations Fehler

### ISSUE THREAD

**Issue by Andree909** [iotaledger/firefly#1998]
### Issue description

Ledger Migrations Fehler

![Fehlermeldung-Firefly-Screenshot_20220101_174130](https://user-images.githubusercontent.com/96953090/147857393-2bccc710-474c-4972-9b3b-608d8cc77b41.png)

### Firefly version

1.3.0

### OS details

Arch Linux - Kernel Version: 5.15.12-arch1-1 (64-bit) , Windows 11 Pro - 22000.376

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

Firefly version
1.3.0
Operating System: 	
	
	Arch Linux
			KDE Plasma Version: 5.23.4
			KDE Frameworks Version: 5.89.0
			Qt Version: 5.15.2
			Kernel Version: 5.15.12-arch1-1 (64-bit)
			Graphics Platform: X11
			Processors: 4 × Intel® Core™ i5-4690K CPU @ 3.50GHz
			Memory: 7.7 GiB of RAM
			Graphics Processor: NVIDIA GeForce GTX 750 Ti/PCIe/SSE2

	Windows 11
			Processors: Intel® Core™ i7-1165G7 CPU @ 2.80GHz

Ledger Nano X

Firmware 	v2.0

App:

IOTA		v0.7.3
IOTALegacy	v0.5.8

1.	Wallet migrieren

2.	von Ledger Backup
3.		Ledger Trinity Backup

4.	PIN-Code	******
	
5.	APP Installiert
		IOTA		v0.7.3
		IOTALegacy	v0.5.8

6. 	Connect Ledger

7.		start IOTA v0.7.3

8.			Create Adress

9.		exit IOTA v0.7.3

10.		start IOTALegacy v0.5.8

11.           Index 0

12.			konto 7,981	OK

13.			Start Migration

Fehler , Error

13.			Start Migration

Fehler , Error

13.			Start Migration

Fehler , Error

### Expected behaviour

Migration OK

### Actual behaviour

Error

**Comment by MiKeF05** [comment]
Leider gibt es aktuell mit Firefly 1.3 Probleme bei der Ledger Migration. Um das zu umgehen, bitte Firefly 1.2 installieren (https://github.com/iotaledger/firefly/releases/tag/desktop-1.2.0) und die Migration erneut durchführen. Anschließend kann wieder auf Firefly 1.3 geupdatet werden.

**Comment by Andree909** [comment]
Hallo, und vielen Dank für die schnelle Info.
Mit der Version 1.2 von Firefly hat die Migration ohne Fehler funktioniert

Gruß, Andree909
