### ISSUE TITLE
My wallet network is not connected and my transferred tokens are not received from Binance, but its been sent from Binance... and i can't able to add this network address manually, https://mainnet-node.tanglebay.com/. How can i solve thsi issue. pls help me

### ISSUE THREAD

**Issue by farouk1976omar** [iotaledger/firefly#2000]

**Comment by MiKeF05** [comment]
Do you use a VPN or a strict firewall? Can you share the error log in Firefly? Click on the menu on the upper left, then Firefly and error log.

**Comment by cvarley100** [comment]
Please ask for support help in the #help channel on https://discord.iota.org.

**Comment by farouk1976omar** [comment]
i used strict firewall not used vpn vpn

**Comment by farouk1976omar** [comment]
> Please ask for support in the #help channel on https://discord.iota.org.



> Do you use a VPN or a strict firewall? Can you share the error log in Firefly? Click on the menu on the upper left, then Firefly and error log.

i use strict firewall not vpn

**Comment by farouk1976omar** [comment]
error log 
Mon, 03 Jan 2022 12:41:54 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): error trying to connect: tcp open error: Un argument non valide a été fourni. (os error 10022)`

Mon, 03 Jan 2022 12:41:54 GMT
NodesNotSynced: nodes https://mainnet-node.tanglebay.com/ not synced

Mon, 03 Jan 2022 12:41:44 GMT
NodesNotSynced: nodes https://mainnet-node.tanglebay.com/ not synced

Mon, 03 Jan 2022 12:41:44 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): error trying to connect: tcp open error: Un argument non valide a été fourni. (os error 10022)`

Mon, 03 Jan 2022 12:41:34 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): error trying to connect: tcp open error: Un argument non valide a été fourni. (os error 10022)`

Mon, 03 Jan 2022 12:41:34 GMT
NodesNotSynced: nodes https://mainnet-node.tanglebay.com/ not synced

Mon, 03 Jan 2022 12:41:24 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): error trying to connect: tcp open error: Un argument non valide a été fourni. (os error 10022)`

Mon, 03 Jan 2022 12:41:24 GMT
NodesNotSynced: nodes https://mainnet-node.tanglebay.com/ not synced

Mon, 03 Jan 2022 12:41:19 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): error trying to connect: tcp open error: Un argument non valide a été fourni. (os error 10022)`

Mon, 03 Jan 2022 12:41:19 GMT
NodesNotSynced: nodes https://mainnet-node.tanglebay.com/ not synced
