### ISSUE TITLE
Firefly Error message: ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by d0ms0n** [iotaledger/firefly#2002]
### Issue description

App Version: 1.3.0

platform: win32
platformVersion: 10.0.19043
platformArchitecture: x64
cpuCount: 16
totalMem: 15734.8 MB
freeMem: 5430.6 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NAME_NOT_RESOLVED

### Firefly version

1.3.0

### OS details

Microsoft Windows 10 Pro Version	10.0.19043 Build 19043

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. The PC was in "Save energy" mode with firefly open
2. The Network was then unavailable due to power blackout on fibreglass router
3. Network available again
4. Wake up PC and Login
5. Error message was shown

### Expected behaviour

No error message is shown

### Actual behaviour

Error message shown as described above.

### Errors

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NAME_NOT_RESOLVED

**Comment by cvarley100** [comment]
Try disable Firewall and antivirus. 

Your best place for help if the above does not work is https://discord.iota.org #1858 help channel.

Closing as this is a duplicate issue.
