### ISSUE TITLE
Mon, 03 Jan 2022 13:05:37 GMT ClientError: `error sending request for url (https://mainnet-node.tanglebay.com/api/v1/info): error trying to connect: tcp open error: An invalid argument was supplied. (os error 10022)`  Mon, 03 Jan 2022 13:05:37 GMT NodesNotSynced: nodes https://mainnet-node.tanglebay.com/ not synced

### ISSUE THREAD

**Issue by Kumar240892** [iotaledger/firefly#2006]
### Issue description

Mon, 03 Jan 2022 13:05:37 GMT
ClientError: `error sending request for url (https://mainnet-node.tanglebay.com/api/v1/info): error trying to connect: tcp open error: An invalid argument was supplied. (os error 10022)`

Mon, 03 Jan 2022 13:05:37 GMT
NodesNotSynced: nodes https://mainnet-node.tanglebay.com/ not synced

### Firefly version

v1.3.2

### OS details

window 7 ultimate 2009

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.
2.
3.
...
Mon, 03 Jan 2022 13:05:37 GMT
ClientError: `error sending request for url (https://mainnet-node.tanglebay.com/api/v1/info): error trying to connect: tcp open error: An invalid argument was supplied. (os error 10022)`

Mon, 03 Jan 2022 13:05:37 GMT
NodesNotSynced: nodes https://mainnet-node.tanglebay.com/ not synced

### Expected behaviour

de signal bar should show green ... and currently i m receving something went wrong
de coin that i send from binance i dint receive 
every time its show like tis
Mon, 03 Jan 2022 13:05:37 GMT
ClientError: `error sending request for url (https://mainnet-node.tanglebay.com/api/v1/info): error trying to connect: tcp open error: An invalid argument was supplied. (os error 10022)`

Mon, 03 Jan 2022 13:05:37 GMT
NodesNotSynced: nodes https://mainnet-node.tanglebay.com/ not synced

 but i did as per guide here... still same not connect to wallet

### Actual behaviour

should be connect and able to se my cointhat i transfer from binance.. and should be stacking it

### Errors

Mon, 03 Jan 2022 13:05:37 GMT
ClientError: `error sending request for url (https://mainnet-node.tanglebay.com/api/v1/info): error trying to connect: tcp open error: An invalid argument was supplied. (os error 10022)`

Mon, 03 Jan 2022 13:05:37 GMT
NodesNotSynced: nodes https://mainnet-node.tanglebay.com/ not synced

**Comment by Kumar240892** [comment]
iota1qpw2caw3mlpc4wa93sytzy3u0yh6j2sdquyf3usasxg8cuqjedf3xu5ya25 tis is my addrest

**Comment by MiKeF05** [comment]
It looks like that your computer blocks the request to the node. So you can try to temporarily disable your firewall or allowing Firefly to connect to the node.

**Comment by MiKeF05** [comment]
And it is highly recommend to not use an outdated windows version. Windows 7 doesn´t get updates anymore.

**Comment by Kumar240892** [comment]
> It looks like that your computer blocks the request to the node. So you can try to temporarily disable your firewall or allowing Firefly to connect to the node.

my fire wall is off...its always been off from ealier

**Comment by Kumar240892** [comment]
> And it is highly recommended to not use an outdated windows version. Windows 7 doesn´t get updates anymore.

ok but tis issue not regarding de windows rite...

**Comment by rajivshah3** [comment]
It looks like the node you're connected to is not synced. You can switch your node in the settings under "Network config". You can change "Node selection" to "Manual" and then set a node as your primary node

**Comment by Kumar240892** [comment]
> It looks like the node you're connected to is not synced. You can switch your node in the settings under "Network config". You can change "Node selection" to "Manual" and then set a node as your primary node

still de problem sustain ... can i log out fire fly in tis pc .. and login firefly in other pc f .. 
is that can be done ... /??? should i able to login de wallet from other pc ...????
