### ISSUE TITLE
Error occured while App was running unattended

### ISSUE THREAD

**Issue by CoinTroll666** [iotaledger/firefly#2012]
### Issue description

When FireFly was running unattended, i saw an error occured when i got back to my computer. Following error code was shown

App Version: 1.3.2

platform: win32
platformVersion: 10.0.19043
platformArchitecture: x64
cpuCount: 4
totalMem: 8181.9 MB
freeMem: 2907.6 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NAME_NOT_RESOLVED 

### Firefly version

1.3.2

### OS details

Windows 10.0.19043 win32 x64

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1. No way to reproduce, cause it was not a user action causing the issue
2.
3.
...

### Expected behaviour

At Version 1.3.0 Firefly was running over night for several days in past, never showing such issues the next morning

### Actual behaviour

Error occuring while app was unattended

### Errors

App Version: 1.3.2

platform: win32
platformVersion: 10.0.19043
platformArchitecture: x64
cpuCount: 4
totalMem: 8181.9 MB
freeMem: 2907.6 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NAME_NOT_RESOLVED

**Comment by MiKeF05** [comment]
Did your computer went to sleep mode?

**Comment by CoinTroll666** [comment]
> Did your computer went to sleep mode?

No it didn't. Was online and awake the whole night.

**Comment by rajivshah3** [comment]
> net::ERR_NAME_NOT_RESOLVED

I think this error comes from not being able to resolve a domain to its IP address. @CoinTroll666 did Firefly operate normally after this showed up?

**Comment by CoinTroll666** [comment]
> > net::ERR_NAME_NOT_RESOLVED
> 
> I think this error comes from not being able to resolve a domain to its IP address. @CoinTroll666 did Firefly operate normally after this showed up?

When I dismissed the error-popup FireFly was doing it's job as expected again without having to restart the program. It just went back to the profile selection Screen.
In that case maybe this is not a bug which makes the program unusable but maybe this error is able to occur at some other point so o decided to report it.

**Comment by rajivshah3** [comment]
Thanks. We can probably ignore this error as it just means the DNS resolution service was temporarily unavailable and likely isn't an error in Firefly itself

**Comment by CoinTroll666** [comment]
Maybe that's the reason, yeah. I couldn't rule out that it was a temporary and very short disruption of my internet connection which was happening over night. So yes, please close this issue.
