### ISSUE TITLE
unstaked iota, no rewards received

### ISSUE THREAD

**Issue by sybTt** [iotaledger/firefly#2015]
Hello,

On 28.12 I made a transfer and staked 14840 iota, all was ok, rewards were coming. 
On 29.12 I made another transfer of 187.5 iota and staked them over the old amount, total 15030 iota staked, I was asked the password for staking, all ok.

Today I logged on again and I saw that I have not received  rewards  since 29.12 and all my coins are available, nothing is staked. 

How is it possible to have the funds unstaked as I haven't made any other operation?

**Comment by MiKeF05** [comment]
Please visit the official IOTA discord to get immediate help with this issue (https://discord.iota.org/)

**Comment by MiKeF05** [comment]
There was a manual send transaction from the user and this unstaked the funds. Otherwise the funds can´t be sent. But this is a normal process and Firefly also warns the user that the funds need to be staked again. Issue can be closed.
