### ISSUE TITLE
i cant see my iota balance on firefly wallet

### ISSUE THREAD

**Issue by malgebesus** [iotaledger/firefly#2017]
### Issue description

Hi IOTA team,

i have sent 55 IOTA from Binance to my own firefly wallet on 31 December 2021. 

im checking my wallet for 4 days but i cant see my IOTA balance on my wallet. i checked my balance on https://explorer.iota.org/mainnet , here i can see my IOTA balance. because of this im sure i sent my IOTA tokens succesfully.

i tried some methods to solve this issue, you can see below;

1- i reinstalled wallet with recovery phrase 
2-  i reinstalled wallet with public words
3- i deleted windows cahce and deleted all items of firefly wallet, redownloaded wallet and installed
4- and my last trying is, from firefly wallet settings/advanced settings/find my balance

all methods i tried failed, still i cant see my IOTA balance on my wallet.

my wallet adress: iota1qq9q2ntds69rd3ye4l08ty35fdvkx9geqqg088q8cn3u60dn52k3gde9w3q

please help me, i want to stake my IOTA tokens. 

### Firefly version

1.3.2

### OS details

windows

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

i want to see my IOTA tokens on my wallet and stake it

### Actual behaviour

i cant see my iota balance on firefly wallet

**Comment by MiKeF05** [comment]
Can you please share the error log of Firefly? Do you use a VPN?

**Comment by malgebesus** [comment]
hi again, after your warning , checked my vpn setting, and i saw that im using (using a corporate connection). after that i connected with my phone's internet and now i can see my IOTA balance, i staked all of it. Thanks :)
