### ISSUE TITLE
allegedly wrong password

### ISSUE THREAD

**Issue by Eric0G** [iotaledger/firefly#2018]
### Issue description

Hello supposedly my password is wrong to stake my iotas can't make a new password

### Firefly version

1.3

### OS details

Windows 10

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1.
2.
3.
...
i dont now

### Expected behaviour

i dont now

### Actual behaviour

i dont now

**Comment by MiKeF05** [comment]
Create a new profile in Firefly and restore your profile with your 24 words. In this process you can set a new password and a new PIN.

**Comment by Eric0G** [comment]
Thx 🙏🏽 


Gesendet von Yahoo Mail für iPhone


Am Dienstag, Januar 4, 2022, 10:13 PM schrieb MiKeF05 ***@***.***>:




Create a new profile in Firefly and restore your profile with your 24 words. In this process you can set a new password and a new PIN.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MiKeF05** [comment]
Issue can be closed
