### ISSUE TITLE
Callback Error syncAccounts - typeError: Cannot read property 'migratedTransactions' of undefined

### ISSUE THREAD

**Issue by cryptocommit** [iotaledger/firefly#2021]
### Issue description

App Version: 1.3.2

platform: macOS
platformVersion: 11.6.2
platformArchitecture: x64
cpuCount: 4
totalMem: 8192.0 MB
freeMem: 95.6 MB

Error Type: Callback Error syncAccounts

TypeError: Cannot read property 'migratedTransactions' of undefined
    at Ws (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2115031)
    at file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2110216
    at Array.forEach (<anonymous>)
    at onSuccess (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2110203)
    at Function.t.<computed>.<computed> (file:///Applications/Firefly.app/Contents/Resources/app.asar/public/build/index.js:2:2108132)

### Firefly version

1.3.2

### OS details

platform: macOS platformVersion: 11.6.2 platformArchitecture: x64 cpuCount: 4 totalMem: 8192.0 MB freeMem: 95.6 MB

### Can the issue be reliably reproduced?

No

### Steps to reproduce the issue

1.
2.
3.
...

### Expected behaviour

staking available

### Actual behaviour

staking not available

### Errors

sync wallets do not work

**Comment by MiKeF05** [comment]
Hello, can you try to create a new profile and restore it with your stronghold backup or your 24 words?

**Comment by Tuditi** [comment]
This might be due to not using the optional chaining in `processMigratedTransactions` in wallet.ts (see link).
Let us know if MiKeF05's suggestion help, since this api will change in the future.

https://github.com/iotaledger/firefly/blob/e66be3b316a14d4c626e537b6c164537261b0248/packages/shared/lib/wallet.ts#L1030

**Comment by jeeanribeiro** [comment]
6 months old issue and no replies from the author yet, I will close it
