### ISSUE TITLE
[Bug]: Dark blue Screen when starting firefly

### ISSUE THREAD

**Issue by Glisaink** [iotaledger/firefly#2025]
### Issue description

When I start the firefly application it opens only with a dark blue window. 

### Expected behaviour

The applications should open with the field for my PIN Code. It worked one single time.

### Actual behaviour

When I start the firefly application it opens only with a dark blue window. I reinstalled firefly several times. It doesn´t help. The very first time it worked but after I closed the application and opened it only 5 minutes later, it didn´t work anymore.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Everytime I open the application the dark blue screen appears. Reinstalled it several times.

### Diagnostics

```shell
The button doesn´t work
```

### Errors

```shell
The button doesn´t work
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Which OS do you use? Do you use the latest version of Firefly? (1.3.2)

**Comment by Glisaink** [comment]
Windows 10 x64 and yes firefly 1.3.2

**Comment by MiKeF05** [comment]
Can you please share the error log of Firefly?

**Comment by Glisaink** [comment]
No the button doesn´t work. I only see this screen and buttons like "Firefly" or "Help" don´t work
![1](https://user-images.githubusercontent.com/97201626/148309350-6c6cd1ea-b7c9-4b43-b465-1458c5df1187.JPG)

**Comment by MiKeF05** [comment]
Could you try the following. Uninstall Firefly and also delete the folder Firefly in C:\Users\ [user]\AppData\Roaming\. If you had profiles in Firefly before make sure to have a backup or your 24 words to be able to restore your profile.

**Comment by Glisaink** [comment]
Nice, thanks a lot! This worked!

**Comment by MiKeF05** [comment]
Great to hear! I guess this issue can be closed
