### ISSUE TITLE
[Bug]: Staked funds reported by Firefly as unstaked (after sending funds from staked account)

### ISSUE THREAD

**Issue by mrstormlars** [iotaledger/firefly#2030]
### Issue description

I sent some funds out of my staked wallet. The remainder was then transferred to a new address (as per default in Firefly). Then I staked the remaining funds again (funds "sent" to the same new address), and the transaction went through with no error. I can see on thetangle.org that the funds are staked, and Firefly shows how the amount of rewarded tokens are increasing each 10s. Firefly correctly sums rewarded tokens from the old and new address.
BUT: Firefly (v. 1.3.2) still reports 0 Mi staked funds, and "Not staked" on both Assembly and Shimmer. Only a visual bug, but still confusing...
![bilde](https://user-images.githubusercontent.com/21202092/148584560-c9f41505-7b22-4ed0-8881-e6f49952d296.png)
![bilde](https://user-images.githubusercontent.com/21202092/148584633-fddb4931-7565-4b0f-9498-2fe494c68364.png)

### Expected behaviour

Firefly should show amount of staked funds (same as total funds in account), as it does when the first account is staked.

### Actual behaviour

After sending funds out of a staked address, re-staking in the new address causes Firefly to not display staking status correctly (see Issue description).

### Can the issue reliably be reproduced?

No

### Steps to reproduce the issue

Not shure if the issue can be reliably reproduced, but here is how I would do it:
1. Send a fraction of account balance from a staked account. 
2. Re-stake the remaining funds (in the new address).

### Diagnostics

```shell
Firefly v1.3.2
Language: en
Currency: USD
Node selection: Manual
Platform: win32
Platform Version: 10.0.19044
Platform Architecture: x64
CPU Count: 16
Total Memory: 32678.9 MB
Free Memory: 24124.1 MB
```

### Errors

```shell
N/A
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Travetown** [comment]
Perhaps for a similar reason. 

For example, I am currently staking at an address A 10Gi.  Then I send 2 Gi to this address.  These are then correctly shown to me as not in staking.  Now I select staking and the transaction will also be carried out correctly with the entire balance of 12 Gi.  However, Firefly then indicates that 10Gi - the old credit - are not in staking.  Only when I do the staking again will the display be correct.

**Comment by ytiruces** [comment]
Have the same issue

**Comment by ytiruces** [comment]
After sing out\sign in, it's ok now
