### ISSUE TITLE
[Bug]: Balance display error when an Internal Transfer complete

### ISSUE THREAD

**Issue by guang384** [iotaledger/firefly#2031]
### Issue description

Make an Internal Transfer （Whether you directly select internal transfer or transfer to an internal wallet address ）
When the transfer is completed, the wallet balance used to send iota does not change, but the wallet balance receiving iota increases, and the total balance display is also wrong

### Expected behaviour

The balance of the wallet that has been transferred out will be reduced

### Actual behaviour

There was no decrease, and the total balance was also wrong due to the increase of the balance of another sub wallet

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1.Make an Internal Transfer （Whether you directly select internal transfer or transfer to an internal wallet address ）
2.Wait transfer complete
3.Check each balance

### Diagnostics

```shell
UI is not updated in time
```

### Errors

```shell
no
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guang384** [comment]
V1.3.2

**Comment by MiKeF05** [comment]
This should be fixed in the latest release.
