### ISSUE TITLE
[Task]: Add Firefly (desktop) to MacOS app store

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2038]
### Task description

We would like to add firefly to the MacOS app store, so that we can improve the security of the downloads.

### Requirements

// TODO

### Acceptance criteria

App is added to the app store and setup for future releases.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jeeanribeiro** [comment]
**Electron docs: Mac App Store submission guide**
https://www.electronjs.org/docs/latest/tutorial/mac-app-store-submission-guide
