### ISSUE TITLE
[Task]: Add Firefly (desktop) to Microsoft store

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2039]
### Task description

We would like to add firefly to the Microsoft app store, so that we can improve the security of the downloads.

### Requirements

// TODO

### Acceptance criteria

Desktop app is downloadable from the app store, and we can easily manage future releases.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jeeanribeiro** [comment]
**Electron docs: Windows Store Guide**
https://www.electronjs.org/docs/latest/tutorial/windows-store-guide

**Microsoft Docs: Publish Windows apps and games**
https://docs.microsoft.com/en-us/windows/uwp/publish/
