### ISSUE TITLE
[Bug]: Stake appears disabled the merge button to add new funds to the stake

### ISSUE THREAD

**Issue by rantontxe** [iotaledger/firefly#2041]
### Issue description

![Sin título](https://user-images.githubusercontent.com/97513988/148918768-c47decf6-e390-4955-94ea-325f7091551c.jpg)

### Expected behaviour

be able to stake with new funds

### Actual behaviour

I can't add anything to the stake

### Can the issue reliably be reproduced?

No

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Hello, can you please try to create a new profile and restore your wallet with your stronghold backup file + password?

**Comment by MiKeF05** [comment]
Hello, can you please try to send all your funds to a new wallet inside your profile? After this you can stake with the new wallet. But make sure to create a wallet INSIDE your profile.

**Comment by MiKeF05** [comment]
This should be fixed in the latest release
