### ISSUE TITLE
[Task]: Mobile recover profile using file backup

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2078]
### Task description

TBD

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by amadeu2** [comment]
Closes since the task is inside https://github.com/iotaledger/firefly/issues/2080
