### ISSUE TITLE
[Bug]: MacOS M1 Bug - Main Unhandled Promise Rejection

### ISSUE THREAD

**Issue by Mielej18** [iotaledger/firefly#2123]
### Issue description

Continually getting the following error on my M1 Mac Mini:

App Version: 1.3.2

platform: macOS
platformVersion: 12.1
platformArchitecture: x64
cpuCount: 8
totalMem: 8192.0 MB
freeMem: 71.1 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NAME_NOT_RESOLVED

### Expected behaviour

I don't expect this pop-up every day.

### Actual behaviour

Application running in background (not actively being used) and pop up appears. App continues to work but error happens every day.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Leave the application running and the error will popup on a daily basis

### Diagnostics

```shell
App Version: 1.3.2

platform: macOS
platformVersion: 12.1
platformArchitecture: x64
cpuCount: 8
totalMem: 8192.0 MB
freeMem: 71.1 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NAME_NOT_RESOLVED
```

### Errors

```shell
App Version: 1.3.2

platform: macOS
platformVersion: 12.1
platformArchitecture: x64
cpuCount: 8
totalMem: 8192.0 MB
freeMem: 71.1 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_NAME_NOT_RESOLVED
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Thank you for reporting this. This error should not affect the operability of the Firefly wallet. The net:: errors will not be shown anymore in one of the future releases.
