### ISSUE TITLE
[Task]: Allow users to edit profile name

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#2127]
### Task description

Add a setting to edit the profile name. This may require changes in wallet-rs so first check the spec if it's possible and if not, contact Thorald Mueller about required changes.

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [x] I have assigned this task to the correct people
- [x] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by rajivshah3** [comment]
I was thinking about this a little while ago. Is it worth migrating the profiles to paths with random identifiers as names? That would also allow users to use whatever characters they want, as we currently don't allow certain characters:

https://github.com/iotaledger/firefly/blob/d62300a7fe307e6f158774c43cfada8bc5a6b307/packages/shared/lib/helpers.ts#L52-L74

**Comment by Tuditi** [comment]
@rajivshah3 , I had the same idea! The issue here is that we need to migrate all already existing profiles. Not sure how that would work.
