### ISSUE TITLE
[Bug]: Hangs on load screen after entering pin

### ISSUE THREAD

**Issue by onetimewonder** [iotaledger/firefly#2131]
### Issue description

After pin entry at startup/login, screen hangs indefinitely on logo loader.
Restarts of app and laptop, as well as reinstall of firefly and updated mac OS have not resolved the issue.
Only setup today, app worked a couple times and now doesn't.
I see historic versions of this issue that were fixed with updates at the time and have since closed.

### Expected behaviour

After pin entry should load dashboard

### Actual behaviour

stays stuck on logo loader screen

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

open app, enter pin, hang

### Diagnostics

```shell
Firefly v1.3.2
Platform: macOS
Platform Version: 12.1
Platform Architecture: x64
CPU Count: 8
Total Memory: 16384.0 MB
Free Memory: 771.8 MB
```

### Errors

```shell
Empty
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chemicallymark** [comment]
Same error here. Open app, enter pin, hangs on splash screen. Please fix this bug.

**Comment by MiKeF05** [comment]
Can you try it with a fresh installation of Firefly? Before you do that make sure to have your 24 words or a stronghold backup + password. 

For a fresh installation uninstall Firefly and also delete the folder Firefly in `username/Library/Application Support/` (macOS). With this folder all your data like your previous profiles will be deleted. Install Firefly again and restore your wallet with your 24 words or your stronghold file + password.

**Comment by chemicallymark** [comment]
I can try but this WAS a fresh install.

FYI...I'm using Win10

**Comment by chemicallymark** [comment]
It's working for now. Will test again later after some time has passed and report back if the error still exists

**Comment by onetimewonder** [comment]
Thanks that sorted it!

**Comment by chemicallymark** [comment]
Seems to be working ok now. Thanks!

**Comment by gimletJP** [comment]
Hi all,
got the some issue with Mac OS 12.1 and Firefly 1.3.2. After entering the PIN the loader is stucked for ever and two firefly process (renderer and helper) go crazy. Background, might be helpful

1) Stacked IOTA
2) Created an address to receive IOTS
3) Send IOTA from exchange to address created under 2)
4) Notification in FIreFly come "receiving IOTA" but then it was stucked
5) Closed FireFly
6) Started FireFly again and got the issue

Is reinstalling and creating a new wallet really a solution? in other issues here it seems people lose the stacking and will I still get my transmitted IOTA?

**Comment by MiKeF05** [comment]
@gimletJP This address under point 2 was a completely new address wasn't it?

No you can't loose the staking as all the data are on the nodes. Firefly only connects to a node to receive these information. Users had problems that Firefly unstaked because they did an outgoing transfer from the staked wallet. But this is pretty normal. Otherwise the funds can't be sent.

When you do the steps described above you restore your wallet. All staked funds will be staked and the incoming transaction should be credited. The funds are already on the new address. You can check this in the explorer which is the actual data from a node. But before you delete the folder with the profile data make sure to have your 24 words or your stronghold backup file + password

**Comment by gimletJP** [comment]
@MiKeF05 Yes it was a new address in my eyes. I clicked "receive" in Firefly and it created an address which I used just for the transaction in 2). Checking the address with the tangle explorer also only shows this one transaction I did in step 2).

Does it make a difference from which time point the stronghold backup file is? I have two as I just did a backup prior to stacking.

**Comment by MiKeF05** [comment]
Okay. But just to make this clear. You are always able to use existing addresses to receive tokens. Firefly generates a new address only for privacy reasons. So you can use a new or an exisiting address to receive tokens.

It would be good to use the latest backup you have created.

**Comment by gimletJP** [comment]
@MiKeF05  Thanks! Will try it later and provide an update then.

However, what is the root for this behavior? Isn't it strange that a clean install shall be the fix. How do I prevent that the next transmission crashes it again

**Comment by MiKeF05** [comment]
@gimletJP The devs are already investigating this issue. Hopefully this will be fixed with the next release.

**Comment by gimletJP** [comment]
@MiKeF05  Thanks for your support. Clean install and restore from stronghold file worked well

**Comment by alexandre1985** [comment]
I am on a ArchLinux system using the AppImage version 1.3.2 and I cannot enter with my PIN.
I have tried creating a new account using the seed words and it gets stuck on the "confirme the PIN" part.

This is a major bug! Fix it!

**Comment by MiKeF05** [comment]
@alexandre1985 The Firefly wallet was tested before the release. Please make sure to have installed gnome-keyring.

I recommend to join the official IOTA discord server and go to the help channel to solve this issue.

P.S. Please don't comment on random issues when you face another issue than the current issue is about.

**Comment by peto75** [comment]
![Снимок экрана 2022-01-22 020951](https://user-images.githubusercontent.com/98058783/150620877-ba50ce31-5968-4514-ae1a-507c7aa4fcbe.png)
Здравствуйте.уже перепробовал всё что возможно никаких улучшений.
Спасибо за понимание

**Comment by MiKeF05** [comment]
This should be fixed with the latest release.
