### ISSUE TITLE
Firefly on Mac doesnt open after Password !!! [Bug]: 

### ISSUE THREAD

**Issue by PaulBo123** [iotaledger/firefly#2134]
### Issue description

I have problems to get access to my account/Staking. after receiving iota it doesnt work 
I have put in the password but the window doesnt start.

Sat, 15 Jan 2022 16:55:50 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qpjrqk84tu564k4kjqqllatajuee4uwxnphpg83dsta5877tycysgedeenp): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known

Sat, 15 Jan 2022 16:55:50 GMT
ClientError: `error sending request for url (https://mainnet-node.tanglebay.com/api/v1/info): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known`

### Expected behaviour

Access to my account on firefly app / platform

### Actual behaviour

after password, it is in a constant loading process ....

### Can the issue reliably be reproduced?

Yes

### Errors

```shell
Sat, 15 Jan 2022 16:55:50 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.cafe/api/plugins/participation/addresses/iota1qpjrqk84tu564k4kjqqllatajuee4uwxnphpg83dsta5877tycysgedeenp): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known

Sat, 15 Jan 2022 16:55:50 GMT
ClientError: `error sending request for url (https://mainnet-node.tanglebay.com/api/v1/info): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known`
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
This is a duplicate to #2131. Therefore I´m going to close this issue. Please see the solution described below. If this doesn´t solve your issue please use issue #2131.

Here is the solution described in the reported issue:

Can you try it with a fresh installation of Firefly? Before you do that make sure to have your 24 words or a stronghold backup + password.
For a fresh installation uninstall Firefly and also delete the folder Firefly in username/Library/Application Support/ (macOS). With this folder all your data like your previous profiles will be deleted. Install Firefly again and restore your wallet with your 24 words or your stronghold file + password.
