### ISSUE TITLE
[Bug]: Stake/Staking pending

### ISSUE THREAD

**Issue by mikemassaro** [iotaledger/firefly#2148]
### Issue description

The send transaction to confirm staking a wallet will not move from pending status.

### Expected behaviour

If an incorrect private key was used to confirm a transaction, I expect the transaction to show as invalid or denied, not pending.

### Actual behaviour

When I went to confirm the staking transaction on my Ledger, I had opened it from the screen saver which wiped the temporary pass phrase from the private key resulting in the transaction to attempt confirmation with the wrong private key.  I assume this is why the staking transaction is stuck in pending status.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Request to stake transaction from Fire Fly wallet.
Confirm transaction with Ledger, using the incorrect private key.
Transaction shows as pending and will not change.
Staking unconfirmed as well as air drop participation unconfirmed.

### Diagnostics

```shell
Firefly v1.3.2
Language: en
Currency: USD
Node selection: Automatic
Platform: win32
Platform Version: 10.0.22000
Platform Architecture: x64
CPU Count: 8
Total Memory: 32665.5 MB
Free Memory: 26228.7 MB
```

### Errors

```shell
Mon, 17 Jan 2022 16:21:13 GMT
LedgerMnemonicMismatch: ledger mnemonic is mismatched
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
Staking events have finished
