### ISSUE TITLE
[Task]: (Staking Tab) Update staking flows to single wallet

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2159]
### Task description

TBD

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
continue work on branch `feat/single-wallet-staking`
