### ISSUE TITLE
[Bug]: Linux Firefly does not accept mine or any PIN

### ISSUE THREAD

**Issue by alexandre1985** [iotaledger/firefly#2189]
### Issue description

I am on a ArchLinux OS with Firefly AppImage version 1.3.2 .

I am trying to enter my Firefly account. It is not accepting my PIN.

I have tried creating a new account using my seed words and it get's stuck on the "confirm the PIN number" part.

### Expected behaviour

accept correct PIN

### Actual behaviour

not accepting correct PIN

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

on the case of login just try to enter your account and enter the correct PIN number

on the case of creating a new account:
1. Create a new account
2. Choose to recover from words
3. enter the correct words
4. enter a password
5. enter the pin
6. confirm the pin (it get's stuck)

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexandre1985** [comment]
I did this new bug issue because @MiKeF05 suggested me in here https://github.com/iotaledger/firefly/issues/2131 to do so

**Comment by rajivshah3** [comment]
Can you confirm that `gnome-keyring` and `libsecret` are installed? https://github.com/iotaledger/firefly/issues/1149

**Comment by alexandre1985** [comment]
Hi have both `gnome-keyring` and `libsecret` installed

**Comment by alexandre1985** [comment]
Any answers. I am getting anxious because I have a lot o money in this coin and Firefly (the official IOTA wallet) is not functioning.
I am unable to access my funds!

**Comment by alexandre1985** [comment]
```
Firefly v1.3.3
Language: en
Currency: USD
Node selection: Automatic
Platform: linux
Platform Version: 5.15.16-1-lts
Platform Architecture: x64
CPU Count: 2
Total Memory: 1862.1 MB
Free Memory: 68.5 MB
```

**Comment by alexandre1985** [comment]
Is this even a serious coin?

What kind of developers are behind this wallet that do not even respond to this urgent issue?

**Comment by MiKeF05** [comment]
@alexandre1985 I´m a community member and found this issue from someone before. Maybe this can help you in the meantime. https://github.com/iotaledger/firefly/issues/850 The devs will come back to you to resolve this issue asap.

**Comment by alexandre1985** [comment]
I have updated Firefly to the last version and this is the error message that I get:
```
13:34:32.631 › Checking for update
13:34:33.261 › Update for version 1.3.3 is not available (latest version: 1.3.3, downgrade is disallowed).
(node:10609) Electron: Loading non-context-aware native module in renderer: '/tmp/.org.chromium.Chromium.saHZZA'. This is deprecated, see https://github.com/electron/electron/issues/18397.
Error occurred in handler for 'keychain-set': [Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached]
```

**Comment by MiKeF05** [comment]
@rajivshah3 Any thoughts in this topic?

**Comment by rajivshah3** [comment]
I don't have any experience with Arch Linux so I don't think I'll be of much help, but Google suggested that it's related to `gnome-keyring`. These might help:

https://github.com/github/feedback/discussions/7115
https://www.reddit.com/r/archlinux/comments/q5s0s5/vscode_git_keychain_error/
https://github.com/microsoft/vscode/issues/120392#issuecomment-814210643

Nonetheless, we may be removing use of the keychain altogether in a future release since we realized it's not entirely necessary

**Comment by nrdsp** [comment]
Same issue here, on NixOS. Installed gnome-keyring and libsecret to no avail. Agree that the pin seems totally unecessary IMHO.

**Comment by Slaol121** [comment]
Same issue.  Manjaro Linux.  Program freezes at confirm PIN screen.
