### ISSUE TITLE
[Bug]: my wallet is keeping screen white

### ISSUE THREAD

**Issue by Abahusau** [iotaledger/firefly#2194]
### Issue description

whenever i try to enter my account after entering my passcode, the screen goes white

### Expected behaviour

whenever i try to enter my account after entering my passcode, the screen goes white

### Actual behaviour

whenever i try to enter my account after entering my passcode, the screen goes white

### Can the issue reliably be reproduced?

Yes

### Errors

```shell
whenever i try to enter my account after entering my passcode, the screen goes white
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by t00k** [comment]
Are you by any chance using Windows 7 or a really old version of macOS?

**Comment by Abahusau** [comment]
i'm having the latest version on my macbook .. also, as i have two account in the wallets, the first one is working fine but the other one whenever i entered the password the screen goes white forever.

**Comment by t00k** [comment]
MacOS Monterey or do you know which version?
Can you try adding a new profile, using the same 24 words/stronghold backup/ledger as the wallet that is going white?

**Comment by Abahusau** [comment]
thank you for your help. its working now after adding a new profile with the 24 words

**Comment by MiKeF05** [comment]
@Abahusau I´m going to close this issue as it seems to be resolved.
