### ISSUE TITLE
[Bug]: Transferred and received Mi don't increase the wallet balance 

### ISSUE THREAD

**Issue by ftprivate** [iotaledger/firefly#2196]
### Issue description

I've transferred Mi from Bitpanda to my Firefly wallet (one profile ; two wallets -> main for staking, 2nd for NFT sale).
Bitpanda shows the transfer as "completed" and my Firefly wallet (NFT sale) shows the received amount of Mi.
Unfortunately the balance of the wallet doesn't increase! 
More than strange - when I close and reopen Firefly, sometimes the correct balance is show for ~15 sec. and then disappears again. I've already switched the network settings from auto to manual with no success....
Any ideas?

Regards  -   

### Expected behaviour

An increased balance after receiving the amount of Mi

### Actual behaviour

the old (incorrect) balance is shown.
from time to time, after restarting Firely, the correct balance is shown, but only for some seconds...

### Can the issue reliably be reproduced?

No

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by t00k** [comment]
Did you already download the artifact with the bug fixed, if you were the same person asking for help on Discord?
The one at https://github.com/iotaledger/firefly/actions/runs/1728758362 .

If not, please download the artifact for your operating system at the link above and install it.

**Comment by MiKeF05** [comment]
Duplicate to #2110. Please try the version in the link above. If the issue persists please use issue #2110 for further assistance.

**Comment by ftprivate** [comment]
Hi and thx for your quick response.
I'm not the guy from discord...
When I follow the link above, I get to the "build (macos-10.15)" which is the one for me...
Unfortunately I'm not a dev :( and so I've no idea what to do with all the files shown there. Sorry...

thx for your help -
Frank

**Comment by ftprivate** [comment]
Hi and thx for your quick response.
I'm not the guy from discord...
When I follow the link above, I get to the "build (macos-10.15)" which is the one for me...
Unfortunately I'm not a dev :( and so I've no idea what to do with all the files shown there. Sorry...

thx for your help -
Frank


 
 

Gesendet: Samstag, 22. Januar 2022 um 12:39 Uhr
Von: "t00k" ***@***.***>
An: "iotaledger/firefly" ***@***.***>
Cc: "ftprivate" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [iotaledger/firefly] [Bug]: Transferred and received Mi don't increase the wallet balance (Issue #2196)


 

Did you already download the artifact with the bug fixed, if you were the same person asking for help on Discord?
The one at https://github.com/iotaledger/firefly/actions/runs/1728758362 .

If not, please download the artifact for your operating system at the link above and install it.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by t00k** [comment]
> 

Click on the MacOS one to download the .dmg file to your computer. When downloaded just run as usual to update Firefly.
Then start Firefly, and see if your issue is solved.
