### ISSUE TITLE
[Bug]: in firefly new version

### ISSUE THREAD

**Issue by nununanaa** [iotaledger/firefly#2197]
### Issue description

 The balance in my wallet keeps changing 0 to actual MIOTA count. 

### Expected behaviour

![error](https://user-images.githubusercontent.com/98216185/150637921-197cc027-5600-41c0-a4d9-ff234cf38a54.jpg)

### Actual behaviour

I'd like to transfer MIOTA. 
but The balance in my wallet keeps changing 0 to actual MIOTA count. and also staking changing 0 to variable numbers.

Both staking and transfer are not possible.

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by t00k** [comment]
Download the version for your operating system under "Artifacts" from this link;
https://github.com/iotaledger/firefly/suites/5015347723/artifacts/147510664
then run it to update Firefly.

Also, NEVER share your seed with ANYONE. Scammers might be trying to contact you. Never share or put your seed on any website.

**Comment by MiKeF05** [comment]
Duplicate to #2110. Please try the version in the link above. If the issue persists please use issue #2110 for further assistance.
