### ISSUE TITLE
[Bug]: Airdrop names missing in the description when merging funds.

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/firefly#2200]
### Issue description

When merging the funds on staking panel we're getting broken description on confirmation window (airdrop names not showing):
![Bez tytułu](https://user-images.githubusercontent.com/35224101/150660725-18b9c044-6dbc-4f4b-b1fb-a45c71122e0f.png)

### Expected behaviour

airdrop name/s to be parsed correctly

### Actual behaviour

airdrop name/s missing in the description

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. trigger merging in the staking panel
2. when confirmation banner pops up there is description which isn't parsing {airdrop} variable.

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gjeee** [comment]
i can confirm this bug as well

**Comment by rajivshah3** [comment]
Is this still an issue in 1.3.3? I can't seem to reproduce it
