### ISSUE TITLE
[Bug]: Main Unhandled Promise Rejection

### ISSUE THREAD

**Issue by PackPro21** [iotaledger/firefly#2201]
### Issue description

App Version: 1.3.0

platform: win32
platformVersion: 10.0.19043
platformArchitecture: x64
cpuCount: 8
totalMem: 16061.6 MB
freeMem: 3145.0 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_INTERNET_DISCONNECTED

### Expected behaviour

The issue looks to be due to my internet connection dropping.
I would think the system should retry to connect after a period of time.

### Actual behaviour

I shut the window. System looks to have reconnected.

### Can the issue reliably be reproduced?

No

### Diagnostics

```shell
App Version: 1.3.0

platform: win32
platformVersion: 10.0.19043
platformArchitecture: x64
cpuCount: 8
totalMem: 16061.6 MB
freeMem: 3145.0 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_INTERNET_DISCONNECTED
```

### Errors

```shell
Sat, 22 Jan 2022 11:22:57 GMT
ClientError: `Response error with status code 404: {"error":{"code":"404","message":"Not Found, error: event not found: f6dbdad416e0470042d3fe429eb0e91683ba171279bce01be6d1d35a9909a981: code=404, message=Not Found"}}
`

Thu, 30 Dec 2021 11:41:43 GMT
LedgerMiscError: ledger transport error

Thu, 30 Dec 2021 11:30:46 GMT
LedgerMiscError: ledger transport error

Sat, 18 Dec 2021 04:11:26 GMT
ClientError: {}
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
@PackPro21 After you have closed this notification and had a stable Internet connection Firefly was operational again?

**Comment by PackPro21** [comment]
@MiKeF05 Yes, it looks like the internet connection was lost and the application failed to reconnect. 
I'm sure it isn't a big issue, however being a programmer myself, I like to know all the things that prevent the application working seamlessly.

**Comment by nicole-obrien** [comment]
Was mentioned that we should just swallow these errors here: https://discord.com/channels/397872799483428865/930249834248691743/931295244878745710
