### ISSUE TITLE
[Bug]: The message is not yet referenced by a milestone.

### ISSUE THREAD

**Issue by gmsongxi** [iotaledger/firefly#2203]
### Issue description

I transferred IOTA from OKEX exchange to Binance exchange, but the status of the transfer is always pending, the error is "The message is not yet referenced by a milestone". What should I do? 
This is my deal：https://explorer.iota.org/mainnet/message/fa717b88d1d28b25ab5ad95a14aef76a303ad45491b080e1d17dbc2d840515d4

### Expected behaviour

I want my deal confirmed

### Actual behaviour

The message is not yet referenced by a milestone

### Can the issue reliably be reproduced?

No

### Diagnostics

```shell
The message is not yet referenced by a milestone
```

### Errors

```shell
The message is not yet referenced by a milestone
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Thoralf-M** [comment]
It's confirmed now here https://explorer.iota.org/mainnet/message/8e26a5ade9583750cd62154cc0f866af6adcc815f7a10f0d377da4e22e5cc4c3
