### ISSUE TITLE
[Task]: Document process for adding a new setting

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/firefly#2215]
### Task description

It is currently not documented how to add an additional item to the settings. Adding this to the wiki will allow other people to contribute more easily.

### Requirements

- Update the wiki

### Acceptance criteria

- Wiki has been updated

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
I added the description here: https://github.com/iotaledger/firefly/blob/chore/create-firefly-handbook/docs/handbook/guides/developer-tips.md#adding-a-setting
