### ISSUE TITLE
[Task]: Define SOP - Security vulnerability management 

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#2238]
### Task description

TBD

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by maxwellmattryan** [comment]
Have added a handbook section for this [here](https://iotaledger.github.io/firefly/standard-operating-procedures/vulnerabilities/) :+1:
