### ISSUE TITLE
Can tripple my amount of Iotas for staking without having the real asset

### ISSUE THREAD

**Issue by roborache** [iotaledger/firefly#2317]
### Issue description

I've created 3 seperate wallets in one Firefly Account, so I can have an overview of my investment. Because I did invest in 3 seperate times, I did split it up to see the price value rising up or down

After creating my 3rd side wallet, I saw the value changing up and down. This effect the staking rewards to me, because the bug let me get more stake rewards than I should get originally.

![bug4](https://user-images.githubusercontent.com/16886710/153515871-30e61700-17e4-4113-b668-f3307044299e.png)
![bug3](https://user-images.githubusercontent.com/16886710/153515873-0e5cd598-19ee-40d9-a214-023f5b0a28a6.png)
![bug1](https://user-images.githubusercontent.com/16886710/153515874-eaab45b8-2717-492f-a34e-4683a3a9db34.png)
![bug2](https://user-images.githubusercontent.com/16886710/153515878-23c1831a-9de0-48cb-859d-b0e80224d840.png)

### Expected behaviour

If you deposit IOTAS to your Iota wallet,  you should be able to only stake that amount

If you even created another sub wallet in that one account, you should be able to stake the amount that you only have in there.

### Actual behaviour

When I withdraw my Iotas from binance to the side wallet in the firefly account, I was able to stake the double amount of IOTA tokens , and sometimes after 5-10 minutes, my amount was trippled so I could stake again. It was over the original amount
![bug4](https://user-images.githubusercontent.com/16886710/153516073-597b5d95-b3e8-4118-8636-e5ffc5d61141.png)
![bug3](https://user-images.githubusercontent.com/16886710/153516075-52927d7f-4a70-4ff4-8876-8e1efc674eb6.png)
![bug1](https://user-images.githubusercontent.com/16886710/153516079-4d88161e-1abb-4e79-9e77-866f2b0e3d24.png)
![bug2](https://user-images.githubusercontent.com/16886710/153516080-b58d6a31-12dd-49ef-af23-84778c7c4199.png)

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Start Firefly
Create more than 2 side Wallets in the same account
Start staking in all of the 2 or more wallets

### Diagnostics

```shell
Firefly v1.3.3
Sprache: de
Währung: EUR
Node-Auswahl: Manuell
Plattform: win32
Plattformversion: 10.0.18363
Plattform-Architektur: x64
CPU-Anzahl: 12
Gesamtspeicher: 16319.4 MB
Freier Speicher: 3474.2 MB
```

### Errors

```shell
In the staking tab, you see an error saying "you have left .... Iotas not staked" while the original amount is already staked, but you suddenly get more Iotas in your wallet. The phantom amount can get staked too now and you earn the double or even tripple amount of staking rewards
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Can you try to create a new profile and restore your wallet with your 24 words or the stronghold backup + password?

**Comment by nicole-obrien** [comment]
Should be fixed now
