### ISSUE TITLE
[Bug]: IOTA Balance glitch - Balance doubles

### ISSUE THREAD

**Issue by Jaleeoo** [iotaledger/firefly#2319]
### Issue description

I'm experiencing a glitch on Firefly where my balance doubles for a brief moment, it then goes away and comes back, when I try to stake it, it obviously does not work however every time I tried try to stake it, the amount that would bounce in and out of my account would add more and more each time. 

This glitch continued to happen while the wallet status was locked and also unlocked, the application never recognised this "unstaked amount" as a legitimate figure as when I tried to send the "unstaked amount" to a test wallet it recognised that this exceeded what my actual funds were.

Lastly I wanted to see how the wallet would react when sending an amount that I did have in my balance back and forth to a test wallet, this as a result crashed my application and my wallet, based from the error response tells me I have an "undefined" balance amount. As of right now I'm still unable to get access to my wallet as every time I enter my PIN the following error pop-up appears.

App Version: 1.3.3

platform: win32
platformVersion: 10.0.19043
platformArchitecture: x64
cpuCount: 4
totalMem: 8071.7 MB
freeMem: 2547.9 MB

Error Type: Callback Error latestAddress

TypeError: Cannot read property 'balance' of undefined
    at file:///C:/Users/Jack/AppData/Local/Programs/Firefly/resources/app.asar/public/build/index.js:2:3060474
    at Array.map (<anonymous>)
    at file:///C:/Users/Jack/AppData/Local/Programs/Firefly/resources/app.asar/public/build/index.js:2:3060411
    at Array.forEach (<anonymous>)
    at file:///C:/Users/Jack/AppData/Local/Programs/Firefly/resources/app.asar/public/build/index.js:2:3060370
    at Array.forEach (<anonymous>)
    at file:///C:/Users/Jack/AppData/Local/Programs/Firefly/resources/app.asar/public/build/index.js:2:3060339
    at file:///C:/Users/Jack/AppData/Local/Programs/Firefly/resources/app.asar/public/build/index.js:2:3060502
    at m (file:///C:/Users/Jack/AppData/Local/Programs/Firefly/resources/app.asar/public/build/index.js:2:2027894)
    at Array.<anonymous> (file:///C:/Users/Jack/AppData/Local/Programs/Firefly/resources/app.asar/public/build/index.js:2:2027973)
    at i (file:///C:/Users/Jack/AppData/Local/Programs/Firefly/resources/app.asar/public/build/index.js:2:2027509)
    at Object.update (file:///C:/Users/Jack/AppData/Local/Programs/Firefly/resources/app.asar/public/build/index.js:2:2027565)
    at file:///C:/Users/Jack/AppData/Local/Programs/Firefly/resources/app.asar/public/build/index.js:2:3065577
    at onSuccess (file:///C:/Users/Jack/AppData/Local/Programs/Firefly/resources/app.asar/public/build/index.js:2:2114063)
    at Function.t.<computed>.<computed> (file:///C:/Users/Jack/AppData/Local/Programs/Firefly/resources/app.asar/public/build/index.js:2:2108132)

Is the error log I received. Initially this just seemed like a UI issue however this may be something more. Anyone who's able to look into this would be greatly appreciated.
<img width="960" alt="wut 5" src="https://user-images.githubusercontent.com/99555263/153722878-c0a7ec43-23bc-4afc-8b50-20324ca8ce43.png">
<img width="960" alt="wut 6" src="https://user-images.githubusercontent.com/99555263/153722879-4ecbd415-3c56-41ad-937f-2c88e35b2ce4.png">
<img width="960" alt="wut 7" src="https://user-images.githubusercontent.com/99555263/153722880-6accbe00-f1ed-47cc-a499-8410ceca5b54.png">
<img width="960" alt="wut 8" src="https://user-images.githubusercontent.com/99555263/153722881-647cd6c3-e3f0-46ba-8995-b64076ecf8c5.png">

Above shows what I was able to screenshot - When staking these false funds, additional IOTA are staked onto the false amount and this process can be repeated over and over again.

### Expected behaviour

The initial expectation is for the false amount to not appear in the wallet in the first place.

### Actual behaviour

However this did happen, and after trying to send an amount from one wallet to another, it has crashed the software.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Glitched amount goes to into wallet
2. Send amount less than true value to test wallet
3. Re-send the same funds from the test wallet back to main while the false value still remains in the wallet
4. App appears to crash and wallet is irretrievable. 

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Can you try to create a new profile and restore your wallet either with your 24 words or your stronghold backup + password? If you use a ledger then you need to restore it with your ledger device.

**Comment by Jaleeoo** [comment]
> Can you try to create a new profile and restore your wallet either with your 24 words or your stronghold backup + password? If you use a ledger then you need to restore it with your ledger device.

Hi, yes I've tried that now and I've regained access to my account, however the same issue of the balance doubling appears to still be there on the new profile

**Comment by MiKeF05** [comment]
Hello, I´m going to close this issue because it is a duplicate to #2198. Please feel free to comment at issue #2198.
