### ISSUE TITLE
[Bug]: Account not opening after clicking on Windows message for received transaction

### ISSUE THREAD

**Issue by nicoh123** [iotaledger/firefly#2324]
### Issue description

Hey guys, I sent a transaction to my wallet and got some notification from Windows/ Firefly. After I clicked the message, my Firefly went in "I'm not able to click anything in the app" mode. I restarted it, and now I can't get over the loading Firefly symbol after entering my PIN. Its loading forever.

### Expected behaviour

Logging in to my wallet.

### Actual behaviour

Infinite loading screen without anything happening.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Starting the firefly application.
Entering the PIN code for my profile.
Nothing happens except the Firefly loading symbol.

### Diagnostics

```shell
Firefly v1.3.3
Plattform: win32
Plattformversion: 10.0.19043
Plattform-Architektur: x64
CPU-Anzahl: 8
Gesamtspeicher: 8026.2 MB
Freier Speicher: 2749.9 MB
```

### Errors

```shell
Mon, 14 Feb 2022 13:26:40 GMT
ReqwestError: error sending request for url (https://mainnet-node.tanglebay.com/api/plugins/participation/addresses/iota1qpegl8wh2m52g3wtsdef589qvvsjae4866kyfhu5yyc5zqtktq5kg5hrmzn): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)

Mon, 14 Feb 2022 13:26:40 GMT
ClientError: `error sending request for url (https://mainnet-node.tanglebay.com/api/v1/addresses/iota1qrjtfxnd6qlcyecpuwmvd4s39jcdrvzvs4ydzdc03zggwh5cd3upwvuk4hf/outputs?include-spent=true): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Mon, 14 Feb 2022 13:26:40 GMT
ClientError: `error sending request for url (https://mainnet-node.tanglebay.com/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Mon, 14 Feb 2022 13:26:40 GMT
ClientError: `error sending request for url (https://mainnet-node.tanglebay.com/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Mon, 14 Feb 2022 13:26:40 GMT
ReqwestError: error sending request for url (https://mainnet-node.tanglebay.com/api/plugins/participation/events): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tr547** [comment]
Hi I had the same problem.

I was able to fix it.

**1. uninstall the Firefly app.
2. go to the following folder: %appdata% > Roaming > Firefly
3. delete the Firefly folder
4. install Firefly again
5. log in with your account** 

Voilà !

**Comment by nicoh123** [comment]
> Hi I had the same problem.
> 
> I was able to fix it.
> 
> **1. uninstall the Firefly app. 2. go to the following folder: %appdata% > Roaming > Firefly 3. delete the Firefly folder 4. install Firefly again 5. log in with your account**
> 
> Voilà !

Thanks man, you saved my day! That perfectly helped :)
