### ISSUE TITLE
Firefly don´t recognize my password , it say´s wrong password and ledger backup don't work

### ISSUE THREAD

**Issue by fedjaf** [iotaledger/firefly#2325]
### Issue description

Firefly don´t recognize my password , it say´s wrong password.

### Expected behaviour

accept my account password

### Actual behaviour

don´t recognize my account password

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Firefly don´t recognize my password , it say´s wrong password 
2. Ledger Backup don't work
3. 

### Diagnostics

```shell
Sat, 12 Feb 2022 09:02:05 GMT
LegacyClientError: https://nodes.iota.cafe/: Connection Failed: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat. (os error 10060)

Fri, 11 Feb 2022 13:30:41 GMT
LedgerMiscError: ledger transport error

Fri, 11 Feb 2022 07:48:50 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:48:50 GMT
ClientError: `error sending request for url (https://mainnet-node.tanglebay.com/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:48:40 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:48:40 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:48:34 GMT
ClientError: `error sending request for url (https://mainnet-node.tanglebay.com/api/v1/addresses/iota1qzjthl2u56s24p7f2gdux5yhs3enfqj37g2dyjymvnjuu6tcgxcwxldt2wz/outputs?include-spent=true): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:48:33 GMT
ClientError: `error sending request for url (https://mainnet-node.tanglebay.com/api/v1/addresses/iota1qzjthl2u56s24p7f2gdux5yhs3enfqj37g2dyjymvnjuu6tcgxcwxldt2wz/outputs?include-spent=true): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:48:30 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:48:30 GMT
ClientError: `error sending request for url (https://mainnet-node.tanglebay.com/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:48:22 GMT
ClientError: `error sending request for url (https://mainnet-node.tanglebay.com/api/v1/addresses/iota1qzjthl2u56s24p7f2gdux5yhs3enfqj37g2dyjymvnjuu6tcgxcwxldt2wz/outputs?include-spent=true): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:48:20 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:48:20 GMT
ClientError: `error sending request for url (https://mainnet-node.tanglebay.com/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:48:11 GMT
LatestAccountIsEmpty: can't create accounts when the latest account doesn't have message history and balance

Fri, 11 Feb 2022 07:48:10 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:48:10 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:48:08 GMT
LatestAccountIsEmpty: can't create accounts when the latest account doesn't have message history and balance

Fri, 11 Feb 2022 07:48:02 GMT
LatestAccountIsEmpty: can't create accounts when the latest account doesn't have message history and balance

Fri, 11 Feb 2022 07:48:00 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:48:00 GMT
ClientError: `error sending request for url (https://mainnet-node.tanglebay.com/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:47:59 GMT
LatestAccountIsEmpty: can't create accounts when the latest account doesn't have message history and balance

Fri, 11 Feb 2022 07:47:50 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:47:50 GMT
ClientError: `error sending request for url (https://mainnet-node.tanglebay.com/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:47:40 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:47:40 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:47:30 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:47:30 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:47:20 GMT
ReqwestError: error sending request for url (https://mainnet-node.tanglebay.com/api/plugins/participation/addresses/iota1qzjthl2u56s24p7f2gdux5yhs3enfqj37g2dyjymvnjuu6tcgxcwxldt2wz): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)

Fri, 11 Feb 2022 07:47:20 GMT
ClientError: `error sending request for url (https://mainnet-node.tanglebay.com/api/v1/addresses/iota1qzjthl2u56s24p7f2gdux5yhs3enfqj37g2dyjymvnjuu6tcgxcwxldt2wz/outputs?include-spent=true): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:47:20 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:47:20 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.cafe/api/v1/info): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

Fri, 11 Feb 2022 07:47:20 GMT
ReqwestError: error sending request for url (https://mainnet-node.tanglebay.com/api/plugins/participation/events): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fedjaf** [comment]
V1.3.3 Firefly

**Comment by fedjaf** [comment]
Windows 10 Version 21H2 (Build 19044.1526)
Ledger HW: IOTA Version 0.7.3

**Comment by MiKeF05** [comment]
Do you mean the password or the PIN? What exactly do you mean with "Ledger Backup"?

**Comment by fedjaf** [comment]
I mean the password when i open firefly. 
I have a Ledger ( Hardware Wallet).

**Comment by MiKeF05** [comment]
When you use a ledger then you don´t have a password. You only have a PIN. There is a difference between a PIN and a password. Can you try to create a new profile and restore your profile with the ledger device?

**Comment by fedjaf** [comment]
Youre right its the PIN. Sorry. 

![62384947-513A-4E66-89A7-B6310B17E0B2](https://user-images.githubusercontent.com/99492259/154005728-29dd4bd5-01f1-4d57-992e-b9e0ed5238c3.jpeg)

**Comment by fedjaf** [comment]
![71B5B25D-F845-44B9-8401-BCBAACDF194A](https://user-images.githubusercontent.com/99492259/154006215-046e1c18-625e-4f78-a4d2-0326031d074f.jpeg)
![D5871F04-8BE7-466C-A3A2-57881D363370](https://user-images.githubusercontent.com/99492259/154006226-8484cea8-b40f-449c-874b-16d89e822135.jpeg)
![DC989958-4FA7-41B9-A1EA-6928C46280C5](https://user-images.githubusercontent.com/99492259/154006241-ad70b390-f6d3-4342-83b8-882ea2ac5f2f.jpeg)
![8C76B10D-C9AA-41A4-853D-C092CA16933E](https://user-images.githubusercontent.com/99492259/154006250-3b2a539a-7142-4443-a5d2-043ee928f9e9.jpeg)
![18216D66-DF4B-4960-86A2-F6ED5DCC62C6](https://user-images.githubusercontent.com/99492259/154006256-3fcfd4bf-0cdc-440c-a393-2dbcd2c5747e.jpeg)
![69BC7D45-C8F8-4339-9FC7-FF3F33951421](https://user-images.githubusercontent.com/99492259/154006262-b15c0aff-5005-450c-84dc-fc97dc8680ef.jpeg)
![F1B060A1-5B09-4B05-B1A4-377861DEB765](https://user-images.githubusercontent.com/99492259/154006267-30c68d78-046f-482e-ad00-6dfbeaca7a5e.jpeg)
![41B74B6D-34F6-4B5F-A0BC-52952C289882](https://user-images.githubusercontent.com/99492259/154006275-e70643ab-363c-449d-9c08-e5934b68ff13.jpeg)
![72D36073-5E81-4E84-9AC8-07CB12D361DA](https://user-images.githubusercontent.com/99492259/154006282-4d21dc68-f803-4476-ad13-2e061fbc4263.jpeg)
![819C8A7F-794B-474E-AB62-DE3F40C922C0](https://user-images.githubusercontent.com/99492259/154006290-fcf662b1-ac00-49f2-9188-a434ec357222.jpeg)
![6B456C02-3CA9-4A2E-925C-E61BEFDEE93C](https://user-images.githubusercontent.com/99492259/154006299-ae374743-cfdf-48d6-b087-014631783bae.jpeg)
![0843070D-5005-46EA-BA49-1B4E5E05372A](https://user-images.githubusercontent.com/99492259/154006302-8ac4bde6-6123-4b8d-b86a-7ec63cb23834.jpeg)
![48AEF23E-93CB-435A-BA7B-92F25AA4BF6C](https://user-images.githubusercontent.com/99492259/154006309-765f621c-c33c-4515-b87c-5ee61aec36dd.jpeg)
![D632ADD7-FECE-45B1-B8F6-FFD55FD7C295](https://user-images.githubusercontent.com/99492259/154006316-aaeb1a72-2c95-4a9c-b673-a7fd2148fde4.jpeg)
![5BBAE2CE-C617-4330-911D-5C1D55BD832B](https://user-images.githubusercontent.com/99492259/154006322-034681fd-98ad-433a-8b6e-c8e372c1d81c.jpeg)
![48EC67CE-90E6-470A-8CAC-7E13FB911541](https://user-images.githubusercontent.com/99492259/154006327-a873b247-e8ab-4b7a-b820-74e51a9eea05.jpeg)

**Comment by fedjaf** [comment]
I try to Restore Firefly wallet but its not work. I send some pictures. Regards

**Comment by trimat1** [comment]
Did you maybe use Wallet 2 or Wallet 3?
I had the same problem, my funds where on wallet 3 and don´t show up on wallet 1 ofc but also not with the find funds function.
The Problem is you can´t add a second wallet (with + symbol) as long as you don´t used wallet 1 (see my Issue Report).
My solution was to send 1 IOTA from somewhere else to wallet 1 and the add wallet 2 and so the funds got shown again.
Best.

**Comment by fedjaf** [comment]
I think you are right i try this. Cause i have 2 Wallets. I give Feedback soon.

**Comment by fedjaf** [comment]
this fix the prolem, thank you sooooooo much!

**Comment by MiKeF05** [comment]
This will become a lot easier and smoother with one of the next updates of Firefly.
