### ISSUE TITLE
[Bug]: Profile freezes after entering PIN on macOS

### ISSUE THREAD

**Issue by ianboyd22** [iotaledger/firefly#2370]
### Issue description

Cannot get into wallet on macOS. When I enter my passcode all I see is the loading screen for the firefly application. 

### Expected behaviour

Once I enter my passcode into the firefly app I expect to see my wallet and the balance of all my coins and tokens I have in there.

### Actual behaviour

The firefly application is just showing the loading screen with the logo. 

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Open the app and then enter the passcode for your wallet and then this problem happens. 

### Diagnostics

```shell
Firefly v1.3.3
Platform: macOS
Platform Version: 12.2
Platform Architecture: x64
CPU Count: 8
Total Memory: 8192.0 MB
Free Memory: 26.5 MB
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ianboyd22** [comment]
No I am not using a Ledger. I am using the firefly app on the macOS and for some reason I can see what in my wallet.

**Comment by kraftjs** [comment]
Can you try adding a new profile with "Add Profile" --> "Migrate or restore wallet" --> "I have a Firefly recovery phrase".
This has solved the issue for some users. Your funds are still there, the Firefly wallet acts as just a GUI to the tangle.

If that works, then you can delete the profile causing the freeze by navigating to `~/Library/Application\ Support/Firefly/__storage__/<profile>` and deleting the profile.

**Comment by rajivshah3** [comment]
@ianboyd22 out of curiosity, would you be able to try [these steps](https://github.com/iotaledger/trinity-wallet/issues/2348#issuecomment-555204649) before adding a profile or resetting the wallet? This has sometimes fixed keychain-related issues on macOS

**Comment by ianboyd22** [comment]
@rajivshah3 I am not able to lock my keychain on my Mac.

**Comment by rajivshah3** [comment]
Ah yikes, I should have double-checked that. It seems like Apple removed the ability to lock and unlock the default keychain after that message was written. I think you'll need to try what @kraftjs recommended in that case

**Comment by ianboyd22** [comment]
I have tried what @kraftjs recommended and it seems to have worked. Thank you both for your help on this issue.

**Comment by Peterthanas** [comment]
> Can you try adding a new profile with "Add Profile" --> "Migrate or restore wallet" --> "I have a Firefly recovery phrase". This has solved the issue for some users. Your funds are still there, the Firefly wallet acts as just a GUI to the tangle.
> 
> If that works, then you can delete the profile suffering from the freeze by navigating to `~/Library/Application\ Support/Firefly/__storage__/<profile>` on your system and deleting the profile.

If I migrate to a new wallet profile in Firefly will I lose the staked amounts I have collected so far?

**Comment by rajivshah3** [comment]
Nope, your funds will still be staked
