### ISSUE TITLE
[Subtask]: Add loading spinner until voting tx is confirmed

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#2411]
### Task description

The voting flow popups miss a loading spinner until the tx is confirmed. After confirmation we show the success 
like in staking.

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jeeanribeiro** [comment]
#2412 merged

**Comment by Tuditi** [comment]
Reopening due to some reactivity issues on the spinner message:

![image](https://user-images.githubusercontent.com/45079109/155549729-6d600867-9f8a-459f-9a6f-c8466b8b4de7.png)
