### ISSUE TITLE
[Bug]: Dashboard route empty after using deep links when not enabled

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#2433]
### Issue description

There is an issue surrounding the usage of deep links when they're not enabled and the dashboard route state.

### Expected behaviour

The route state should never be empty, even if having never navigated to the dashboard in the first place. 

### Actual behaviour

When clicking on a deep link while not enabled, Firefly is taken to the settings page. When I click the exit button on the top right, the settings page closes but no other route is loaded.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Make sure IOTA deep links are NOT enabled in Firefly
2. Click on a deep link, like [this one](iota://wallet/send/atoi1qrh820g2p2ekx37005lq6jf56rhmtqu987qq07adqta0y5n6cz2sczgz6f5?amount=10&unit=Mi) (you should be brought to the settings with a notification saying "IOTA deep links are not enabled."
3. Exit the settings page by clicking the "x" button in the top right

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tuditi** [comment]
This should not be an issue with the new router implementation anymore.
