### ISSUE TITLE
[Task]: Reclicking on modal icon when modal opened, makes it disappear

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#2434]
### Task description

Modals use a custom action so they close when you click outside them. However if you click on the same icon that opened the modal, the modal automatically reopens. Example: network status or profile at the bottom.

### Requirements

TBD

### Acceptance criteria

Clicking on an icon that opens a modal, let's the modal disappear when the modal is already opened and the user clicks on the icon again.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
Closing as this was fixed in [#2809](https://github.com/iotaledger/firefly/pull/2763)
