### ISSUE TITLE
[Bug]: Ledger doesn't connect on Ubuntu (Linux)

### ISSUE THREAD

**Issue by lukastanisic99** [iotaledger/firefly#2437]
### Issue description

OS: Ubuntu 20.04

Firefly version v1.3.3

Problem:
Firefly doesn't register a connected Ledger device with the IOTA app open. It registers the ledger when it's connected without opening the IOTA app. Once the IOTA app is opened it thinks the ledger disconnected. 

sha256sum matches the one in the release notes. 

Favicon is also missing, but that's just visual (still a bug). 

### Expected behaviour

Connect ledger, open IOTA app -> continue (same as on Windows)

### Actual behaviour

Nothing

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Try to setup Firefly v1.3.3 with Ledger on Ubuntu 20.04

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by t00k** [comment]
Similar reported in #firefly-help channel by user Schurick#5589.

> "Hi, I'm running firefly 1.3.3 on Manjaro Linux. I try to create a new wallet on firefly, but only come to the screen, where firefly waits for connecting the ledger. Ledger is connected, unlocked and iota app is open. But the connection screen of firefly does not continue. Does anybody have an idea what the problem could be."

Ledger Live updated, latest firmware version and latest IOTA apps. Tried different USB ports and restart of computer etc. A non-ledger profile works without issues. Manjaro Linux, using KDE.

**Comment by rajivshah3** [comment]
> It registers the ledger when it's connected without opening the IOTA app

@lukastanisic99 This is odd 🤔  I assume the Ledger Live app recognizes the Ledger too?

@t00k did Ledger Live recognize the device? If not, it could be the `udev` rules (see solution 1 in the Linux tab [here](https://support.ledger.com/hc/en-us/articles/115005165269-Fix-USB-connection-issues-with-Ledger-Live?support=true))

**Comment by lukastanisic99** [comment]
Yes Ledger Live recognizes the Ledger + FireFly also recognizes it until the IOTA app is open. Once open it thinks I've disconnected the Ledger. The exact same setup works on Windows.

**Comment by lukastanisic99** [comment]
Strangely even though Ledger Live worked, running the above command resolved the problem for Firefly

**Comment by maxwellmattryan** [comment]
Going to close this issue as it's resolved :slightly_smiling_face: Will look into adding this information for users and devs using a Ledger-based profile.
