### ISSUE TITLE
Problem with Firefly wallet 

### ISSUE THREAD

**Issue by Expected372** [iotaledger/firefly#2439]
### Task description

All my iota is gone. 

One month ago i send 1,2 Giota to my Firefly wallet and safed it with a ledger nano s. 

Now i want to buy more but as i opened my Firefly wallet i saw that`s empty. 

I can´t find it anymore. In my wallet are no activities. I can´t even saw my last disposit.

If i search with the Iota explorer i can saw it but it´s not in wallet.

### Requirements

I wanne speak to someone how knows the solution.

### Acceptance criteria

If someone can help my to find my iota.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by t00k** [comment]
First, make sure you are on version 1.3.3.

Then, log out, and try adding a new profile, using the SAME ledger as your first profile.

Lastly, do you have the withdrawal address you sent 1.2 Gi from? So we can try and see where the money went or if they are still on the correct address.

Please stay cautious of scammers, NEVER share your 24 words or connect them to any site.

**Comment by Expected372** [comment]
Thank you for your help.

My Problem is solved. 

Idk why but I can see all my Iota now.
