### ISSUE TITLE
[Task]: re-fetch events after node change

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#2453]
### Task description

when you are connected to a node that doesnt have the voting events, after adding a node with them, the event still doesnt show on firefly. I think we should fetch again so the events can appear right away

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
I don't have this issue anymore. Can you still reproduce it?
