### ISSUE TITLE
[Task]: Fix sending after voting

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#2454]
### Task description

I encountered a crash when trying to send after having voted. Steps to reproduce:

1) Vote
2) Go back to dashboard
3) Send Transaction
4) FF crashes with message TypeError: cannot read property of 'length' undefined

### Requirements

TBD

### Acceptance criteria

It's possible to send partial AND max amount of funds after having voted.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
I think this is the same as #2444
