### ISSUE TITLE
Firefly unable to open from firefox [Bug]: 

### ISSUE THREAD

**Issue by Cool-Dr-T** [iotaledger/firefly#2457]
### Issue description

Firefox is unable to open Firefly on Ubuntu 21.10 - When navigating to a Soonaverse site pop up that should open Firefly, it does not open as expected. Firefly has to be manually opened.

### Expected behaviour

Firefly should open when selected from the Firefox prompt

### Actual behaviour

Firefly does not open.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

In latest firefly
Latest version of firefox
navigate to Soonaverse web page and purchase NFT (or something that will prompt to open Firefly)
Select the FIrefly option to open Firefly
Then allow the pop up that is attempting to open Firefly...
Firefly will not open.

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Hello, thanks for reporting this issue. But you should better report this on Soonaverse Discord.
