### ISSUE TITLE
[Task]: Consider adding default parameters to execute Electron as native Wayland

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#2477]
### Task description

The users using a different distro than a Debian-based Linux, using AppImage file will need enable Ozone Platform to enable Wayland adding this parameters:
```bash
$ firefly-desktop-1.3.3.AppImage --enable-features=UseOzonePlatform --ozone-platform=wayland
```
this could be defined as default in some way?

VSCode is adding in my distro two [desktop entries](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html), one called `VSCode Wayland` and the other just `VSCode`

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by rajivshah3** [comment]
[`executableArgs`](https://www.electron.build/configuration/appimage) is probably what we want to define for this
