### ISSUE TITLE
Firefly UI won't display after opening.[Bug]: 

### ISSUE THREAD

**Issue by bigtankjr** [iotaledger/firefly#2501]
### Issue description

Firefly opens but won't display the UI. The thumbnail for the application is visible in the taskbar, shows a tooltip of the UI when hovering over the thumbnail in the taskbar, but will not fully display when clicking on the thumbnail in the taskbar or during the launch of the application. 

### Expected behaviour

When launching the application, the UI should open and allow the user to access the UI. Once the application is launched and visible in the taskbar, the UI should be accessible by the user
![full_screen_ui_tooltip_won't_open_to_allow_access](https://user-images.githubusercontent.com/18479183/156934725-97949ed5-8953-4564-92bb-5f5370b6b2a8.png)
.

### Actual behaviour

The application launches, but the UI is not visible and cannot be accessed.

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Most likely the window has been opened outside of the displayed area. There are shortcuts to bring the app back to the area. Depending on your OS the shortcut is different.

**Comment by bigtankjr** [comment]
Thanks for the feedback. After trying several techniques for correcting the issue, selecting the application in the taskbar and pressing Window +D worked for me.
