### ISSUE TITLE
cannot send transaction from new wallet[Bug]: 

### ISSUE THREAD

**Issue by Cool-Dr-T** [iotaledger/firefly#2513]
### Issue description

Recently setup a new wallet on Firefly, have 3 current wallets on my laptop no problem with these.

There was an error message when creating but it went away and all seemed fine. Intra-wallet transfers worked and managed to recieve some IOTA into the wallet. However cannot send any IOTA from that wallet, just get a message saying "something went wrong" - nothing else I can see to point to an error.

### Expected behaviour

Should be able to send a transaction without error

### Actual behaviour

Error saying "something went wrong"

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
@Cool-Dr-T I´m going to close this issue. Feel free to open it again if you have further issues.
