### ISSUE TITLE
[Task]: Fix: sending a tx from account A disables actions for all other accounts until tx sent

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#2518]
### Task description

> if I send a tx with wallet 1, I'm unable to do anything with my other wallets in the meantime

### Requirements

-

### Acceptance criteria

-

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
This is inhibited UI wise by disabling switching an account until the syncing/transactions are finished/confirmed.
See: https://github.com/iotaledger/firefly/pull/2703
