### ISSUE TITLE
[Bug]: JWT authentication not working

### ISSUE THREAD

**Issue by F-Node-Karlsruhe** [iotaledger/firefly#2533]
### Issue description

When adding or altering a node in firefly with JWT authentication on all API endpoints the following error is thrown:
`
ClientError: Response error with status code 400: {"error":{"code":"400","message":"missing or malformed jwt, error: code=400, message=missing or malformed jwt"}}
`

### Expected behaviour

Add a node with JWT auth and Firefly applies the JWT correctly, allowing to use the node as normal.

### Actual behaviour

When adding or altering a node in firefly with JWT the following error is thrown:

`ClientError: Response error with status code 400: {"error":{"code":"400","message":"missing or malformed jwt, error: code=400, message=missing or malformed jwt"}}`

This only happens when all API endpoints are restricted. In the case that the default API endpoints (requesting messages etc) are authentication free, the node can be added without issues.  

-> Firefly does not check the token, but in case it is used on an restricted API endpoint the latter described error occurs

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Restrict entire API of node
2. create JWT
3. Add node in firefly and with JWT in token field in the form `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c`

### Diagnostics

```shell
ClientError: Response error with status code 400: {"error":{"code":"400","message":"missing or malformed jwt, error: code=400, message=missing or malformed jwt"}}
```

### Errors

```shell
Es ist ein Fehler aufgetreten.

ClientError: Response error with status code 400: {"error":{"code":"400","message":"missing or malformed jwt, error: code=400, message=missing or malformed jwt"}}
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Have you set up your reverse proxy correctly? I had also a misconfiguration with the reverse proxy and had the same issue. You can also ask in the hornet channel on discord.

**Comment by F-Node-Karlsruhe** [comment]
I think so. It works fine in with the particular node and the python library with the exact same token.

**Comment by MiKeF05** [comment]
Have you explicitly configured the path `/api` in the reverse proxy config?

**Comment by F-Node-Karlsruhe** [comment]
Reverse proxy for the api subdomain:
`
ServerTokens ProductOnly
ServerSignature Off
<VirtualHost *:80>
    ServerName my.domain
    RewriteEngine On
    RewriteCond %{HTTPS} !=on
    RewriteRule ^/?(.*) https://%{HTTP_HOST}/$1 [L,R,NE]
</VirtualHost>
<IfModule mod_ssl.c>
        # Display only Apache as server signature
        ServerTokens Prod
        ServerSignature Off
        <VirtualHost *:443>
                ServerName my.domain
                ProxyPreserveHost On
                # Setup the proxy
                <Proxy *>
                        SetEnvIf Host "^(.*)$" THE_HOST=$1
                        RequestHeader setifempty X-Forwarded-Proto https
                        RequestHeader setifempty X-Forwarded-Host %{THE_HOST}e
                        ProxyAddHeaders Off
                        Order deny,allow
                        Require all granted
                        AllowOverride All
                </Proxy>
                ProxyPassMatch (.*)(\/websocket)$ ws://127.0.0.1:14265/$1$2
                ProxyPass / http://127.0.0.1:14265/
                ProxyPassReverse / http://127:0.0.1:14265/
                SSLEngine on
                Include /etc/letsencrypt/options-ssl-apache.conf
                SSLCertificateFile /etc/letsencrypt/live/my.domain/fullchain.pem
                SSLCertificateKeyFile /etc/letsencrypt/live/my.domain/privkey.pem
        </VirtualHost>
</IfModule>
`

No, why is that necessary? the api listening on 14265 and i have a subdomain for each, the API on 14265 and the dashboard on 8081. This should work in my mind (as it does when using the library with jwt) or am i missing something?

**Comment by maxwellmattryan** [comment]
@MiKeF05 Is the JWT authentication working for you with the current 1.3.3 version? Trying to figure out if it's something to do with the way we're passing the auth stuff to `wallet.rs`.

**Comment by MiKeF05** [comment]
@maxwellmattryan Yes I needed to pass the `/api` path for the node in the reverse proxy configuration. Then it worked for me. There were also some users with the same problem in the hornet channel. But I think it is not related to Firefly.

**Comment by maxwellmattryan** [comment]
@MiKeF05 Yeah it doesn't seem to be related to Firefly :thinking:

**Comment by F-Node-Karlsruhe** [comment]
So you mean that adding an extra proxy for the location like below should resolve the issue?
```
ProxyPass                  /api/     http://localhost:14265/
ProxyPassReverse    /api/     http://localhost:14265/
```
Even though this shouldn't change anything?
