### ISSUE TITLE
Set a default profile / Track last logged in profile

### ISSUE THREAD

**Issue by antonionardella** [iotaledger/firefly#254]
## Description

An option to set the default profile for the wallet.

## Motivation

- Should the user have only one profile in his wallet, there should be an option to set a default profile, to directly ask for the PIN, instead of having an additional click to select _the only available profile_
- Should I have one _daily_ account and a _savings_ account, I might want to open the daily account directly and log out to switch to the savings account, only when needed.

## Requirements

Write a list of what you want this feature to do.

1. Settings under profile to select the default profile
2. When default profile is set, Firefly should ask straight for the PIN when it is opened

## Open questions (optional)

Use this section to ask any questions that are related to the feature.

## Are you planning to do it yourself in a pull request?

No.

**Comment by maxwellmattryan** [comment]
Hey again @antonionardella, also moved this over to a [discussion](https://github.com/iotaledger/firefly/discussions/1482) 👍
