### ISSUE TITLE
[Task]: Consider syncing only the currently selected wallet and not all

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#2548]
### Task description

TBD

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
Is there a decision on this? Or should we either close it or move it to a low priority milestone?

**Comment by nicole-obrien** [comment]
Moving this to the continuously improve UX backlog so that we can revisit it.

**Comment by nicole-obrien** [comment]
Closing because we have a duplicate task https://github.com/iotaledger/firefly/issues/2548 which contains more info
