### ISSUE TITLE
[Task]: Mobile prepare Application ID for alpha

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#2555]
### Task description

Change the current app-id `org.iota.firefly.mobile` by `org.iota.firefly.mobile.alpha`

### Requirements

- Change needed Capacitor and project files.
- Make a script to replace all needed strings on every file needed.

### Acceptance criteria

Application ID must be changed on XCode and Android Studio.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by rajivshah3** [comment]
> Make a script to replace all needed strings on every file needed.

[Fastlane](https://fastlane.tools/) is great for these types of tasks. I'm happy to work on this script if you'd like

**Comment by amadeu2** [comment]
awesome thanks!
