### ISSUE TITLE
[Task]: Mobile verify on Android Chromium/Chrome version and force update

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#2557]
### Task description

There are older Chromium / Chrome browser versions on Android 8, 7, 6, 5 emulators and some old real phones.
We built the app with Webpack targeting the last 2 browser versions to reduce js file size and avoid including old polyfills.
If we allow the app to run in an older browser version it's simply not running because the browser does not support new JS features.

We need to check the browser version before running the webview, avoid keeping running the app and offer a link to update their respective browser.

There is also an option for advanced users to replace the webview by example from Chrome to Samsung Internet browser, enabling Developer options and change by there. We could catch this case too.

### Requirements

- Implement in Java a way to check the currently installed browser version or better yet what is the browser linked to webview.
- Use an Android Intent to open the Play Store and link to the Chrome app to be updated.
- Run the webview once the browser has updated the version.

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by paul-boegelsack** [comment]
@amadeu2 I'm not sure about the priority. You told me that the wrong webview could cause some of the problems on trello, right? So maybe we should set this higher? I think it would be good to get user feedback about this approach during beta.

**Comment by amadeu2** [comment]
investigate if it's possible to force update before install

**Comment by amadeu2** [comment]
👀 related: https://github.com/ionic-team/capacitor/issues/4884
