### ISSUE TITLE
[Task]: Reset wallet by itself after 2 days since created.

### ISSUE THREAD

**Issue by scratcrypto** [iotaledger/firefly#2571]
### Task description

I created Firefly wallet 2 days ago.  Wrote 24 exact words for recovery seeds. Set up two different type of passwords.  One for login and one for passcode to open wallet.  Backed up a file. Transferred funds within 10 mins from CEX to Firefly wallet.  I like the Firefly UI. a Bit of oversize wallet but its okay.  So neat with staking included. I thought why not  stake as well.  First day.  Great without any incident. 

Today after 2nd day. I clicked Firefly wallet app. To my dismayed it took a longer to open and reset itself asking me to create new log in, new wallet or recover or migate. That  was so weird.  I clicked recover. To my surprise that one word out of 24 words is error denied me access. Lucky I  was able to save with 81 backup file with correct password. but in Firefly U.I.  I  have no way to access recover 24 words to double check what are the correct recovery words. 

That is very concerning how did 24 recover words become an issue.  Not the first time it happened to me with itself wrong recovery words on 2 different non-custodial wallet apps in past. but this is the first time with Firefly. 

### Requirements

Need to fix the bug with 24 recovery words and Stop the Firefly suddenly reset itself. 

### Acceptance criteria

Is there a way for me to double check my recovery words. Just like any other apps or web 3 wallets that allow user to double check recovery words from time to time.  

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by MiKeF05** [comment]
Unfortunatly there is no way to reveal the words again. You have 2 options. If only one word is not recognized you can check it with the BIP39 wordlist. Sometimes there are similar words. Try another word which sounds similar.

The second option is to create a complete new profile and send all your funds to the new profile after the staking period. But remember that your staking rewards are connected to the 24 words you staked with. But I would recommend the first option.

**Comment by scratcrypto** [comment]
What bugs me was why did the wallet reset itself on 2nd day?  Does the reset ever happened to anyone ? 
That is good idea can look up those words for similar words.  Does it ever happen that the word during the reveal process that gave out wasnt matched as in the 24 words seeds after the 24 words reveal closed?  Really thank god for the back up file. That will save the funds after the staking ends and yes definitely will transfer funds just in case.  I will still keep using the Firefly and create wallet to see if the problem still continue. Hopefully this will be one off incident. 
Thanks for replying back. Cheers

**Comment by scratcrypto** [comment]
Found the word in the Bip 39. Might be my fault :D  I will test after the staking ended. Just to be sure.  Thanks Cheers.

**Comment by MiKeF05** [comment]
Perfect. I will close this issue. Normally the wallet should not reset itself.

**Comment by scratcrypto** [comment]
Yep close this issue. I'll get back to you if reset wallet still persistent.  Cheers
