### ISSUE TITLE
[Bug]: missing Funds in Firefly after transfer from wallet A to Wallet B

### ISSUE THREAD

**Issue by CryptoFutta** [iotaledger/firefly#2588]
### Issue description

This issue raised up yesterday morning (Sun 20 March at 9:52 CET), never seen this before.

On wallet B there were 2Mi befor this transfer.

I´ve send 1Gi from Wallet A to Wallet B.

After receiving 1Gi in Wallet B i want to pay some Mi for NFTs. While doing so Firefly responded "InsufficientFunds" and at this point of time my funds in Wallet B felt back to 2 Mi.

Looking into the IOTA explorer everything looks as it should. Firefly instead shows this phenomen.

I can reproduce this issue. After re-login to the wallet, Firefly shows 1.002 Gi as expected. Unlocking Wallet and/or trying to stake these funds result in the described status.

On top  ... when Firdefly shows 2 Mi it is possible for me to stake them ... assembly and shimmer ... 2Mi on shimmer ...  !!! ... something strange is going on.

To get behind what´s going on ... i did a second transfer from Wallet A to Wallet B with 40 Mi. I´ve used these 40 Mi for getting a NFT on soonaverse ... everything went well. So in general ... for this it worked as expected.

Can please somebody help me with this ... thanks in advance.

### Expected behaviour

Funds after transaction should be available for transactions.

### Actual behaviour

i can not use transfered funds

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. firefly logout
2. firefly login

### Diagnostics

```shell
Firefly v1.3.3
Sprache: de
Währung: USD
Node-Auswahl: Automatisch
Plattform: win32
Plattformversion: 10.0.19043
Plattform-Architektur: x64
CPU-Anzahl: 8
Gesamtspeicher: 32587.5 MB
Freier Speicher: 17308.6 MB
```

### Errors

```shell
Mon, 21 Mar 2022 17:26:29 GMT
ClientError: `Response error with status code 503: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
`

Mon, 21 Mar 2022 17:21:19 GMT
ClientError: `Response error with status code 503: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
`

Mon, 21 Mar 2022 17:20:49 GMT
ClientError: `Response error with status code 503: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
`

Mon, 21 Mar 2022 17:19:19 GMT
ClientError: `Response error with status code 503: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
`

Mon, 21 Mar 2022 17:18:39 GMT
ClientError: `Response error with status code 503: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
`

Mon, 21 Mar 2022 17:16:59 GMT
ClientError: `Response error with status code 503: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
`

Sun, 20 Mar 2022 10:28:24 GMT
InsufficientFunds: insufficient funds 2000000/40000000 available or input address used as output

Sun, 20 Mar 2022 10:27:50 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sun, 20 Mar 2022 10:14:38 GMT
InsufficientFunds: insufficient funds 2000000/500000000 available or input address used as output

Sun, 20 Mar 2022 09:54:48 GMT
InsufficientFunds: insufficient funds 2000000/40000000 available or input address used as output

Sun, 20 Mar 2022 09:23:35 GMT
InsufficientFunds: insufficient funds 2000000/40000000 available or input address used as output

Sun, 20 Mar 2022 09:18:24 GMT
InsufficientFunds: insufficient funds 2000000/40000000 available or input address used as output

Sun, 20 Mar 2022 09:17:48 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Sun, 20 Mar 2022 09:11:06 GMT
InsufficientFunds: insufficient funds 2000000/40000000 available or input address used as output

Sun, 20 Mar 2022 09:06:12 GMT
InsufficientFunds: insufficient funds 2000000/40000000 available or input address used as output

Sun, 20 Mar 2022 09:01:00 GMT
InsufficientFunds: insufficient funds 2000000/40000000 available or input address used as output

Thu, 17 Mar 2022 17:17:09 GMT
ClientError: `error sending request for url (https://mainnet-node.tanglebay.com/api/v1/info): operation timed out`
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Thoralf-M** [comment]
Try this: 
1. Send 2 Mi to wallet with the 1 Gi
2. Send 1 Mi from the same wallet away
Then it should generate a new remainder address and this should hopefully fix the problem so the whole balance gets available again

**Comment by CryptoFutta** [comment]
Hi, thank you for your reply ... i am not clear how to proceed ...

Outgoing Point
Wallet B. 2 MI
Wallet A: Wallet from which i´ve send 1Gi to wallet B
Wallet B: 1.002 Gi

so at the moment there is no Wallet with 1GI ... do you mean Wallet A or Wallet B? or in other words, do you mean that i have to send 2Mi from Wallet B to Wallet A and afterwards 1 Mi from Wallet A back to Wallet B?

thanks in advance

**Comment by CryptoFutta** [comment]
Hello again, what i did

1 -> send 1 Mi from Wallet B to Wallet C
2 -> send 1 Mi from Wallet B to Wallet A
3 -> staking of 1 Gi on Wallet B

this worked now ... so the final Questions are:

- if staking is now possible with 1 Gi it should be fine now, or?
- with small technical background, what is the root caus for this?

again, thanks in advance

**Comment by JA-FAR** [comment]
Adding a comment here that I also experienced the exact same issue as @CryptoFutta: An internal transfer between two Firefly wallets caused the funds to deduct from the sending wallet but not appear on the receiving wallet. Re-opening the app would show the correct balance for about 30 seconds, then the balance would revert back as if the funds disappeared. I suspected it was some kind of state issue in Firefly itself. I was able to correct the issue with @Thoralf-M 's suggestion, by sending 1Mi from the affected wallet back to the original sending wallet. Thanks!

**Comment by CryptoFutta** [comment]
Hello ... sorry i missed two things ...

@JA-FAR ... the funny thing was, that i have already sent some additional MIOTAs to Wallet B and after this i have send exactly these MIOTASs away to buy some NFTs. So at the end ... for a short time ... i had already a different count of MIOTAs on this Wallet but after i have used them and i felt back to the origin count af MIOTAs ... even i had send one Mi away the propblem was gone ... for me it looked like that it was neccessary to do a transaction which forced a diiferen t count of funds

@Thoralf-M  ... many thanks for your support

In my eyes thre issue could be closed
