### ISSUE TITLE
[Bug]: App icon missing in Firefly 1.4.0-alpha-1

### ISSUE THREAD

**Issue by JannemanDev** [iotaledger/firefly#2623]
### Issue description

App icon missing in Firefly alpha 1.4

### Expected behaviour

Should see an icon I guess

### Actual behaviour

No icon
![bug](https://user-images.githubusercontent.com/13236774/159925563-de82eefb-b410-426a-bf20-19178c5253ee.png)

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Top left menu > Firefly Alpha > About Firefly Alpha

### Diagnostics

```shell
.
```

### Errors

```shell
.
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicole-obrien** [comment]
Thank you, I will get this fixed 😄

**Comment by JannemanDev** [comment]
Hotfix? :)
