### ISSUE TITLE
[Task]: Handle back button / action on Android

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#2638]
### Task description

Android back button or swipe action are closing the app, where it should go back in the router history.

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by paul-boegelsack** [comment]
Should be fixed before the beta starts. On my device, it not only closes the app: opening it again kicks me out a second time after entering the PIN code. Some testers have also complained about this.

**Comment by amadeu2** [comment]
Yes you right we can implement it before beta release, the issue with the second login it's related to a problem with the bindings plugin, I will add the respective task.
