### ISSUE TITLE
[Bug report]: After renaming profile network status disconnected

### ISSUE THREAD

**Issue by MiKeF05** [iotaledger/firefly#2644]
### Platform

Desktop

### Version

1.4.0-beta-1

### Description

After renaming the profile I tried to log out and log back in to the renamed profile. The network is now disconnected. After renaming the profile back to the previous name everything is working fine again.

### Expected behaviour

Network shall not be disconnected after the profile is renamed

### Actual behaviour

Network is disconnected after login in to the renamed profile

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Rename profile
2. Log out
3. Log in to the renamed profile
4. Network is disconnected

### Operating System

Windows

### Diagnostics

```shell
Firefly v1.4.0-beta-1
Sprache: de
Währung: USD
Node-Auswahl: Automatisch
Plattform: win32
Plattformversion: 10.0.19044
Plattform-Architektur: x64
CPU-Anzahl: 8
Gesamtspeicher: 8072.2 MB
Freier Speicher: 3060.9 MB
```

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Staking

Never staked

### Crash Status

None of the above

### Error Messages

No error messages shown

### Error Logs

```shell
No error messages in the error log
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicole-obrien** [comment]
Investigating: 
Might need some more info on this as I can not reproduce.
- Does this happen every-time?
- Did you logout from settings screen or navigate to wallet first?

**Comment by UmbahaSpodPaha** [comment]
Can confirm the problem.

- changed the profile name
- logged out
- logged in again
- network status disconnected (RED) and all wallets gone
- after changing the profile name to the old name everything works again ;)

**Comment by MiKeF05** [comment]
> Investigating: Might need some more info on this as I can not reproduce.
> 
> * Does this happen every-time?
> * Did you logout from settings screen or navigate to wallet first?

This happens every time I do the steps mentioned above. I only logged out directly from the settings screen.

**Comment by nicole-obrien** [comment]
Interesting, because there is a current issue which is preventing logout directly from settings page which I can reproduce https://github.com/iotaledger/firefly/issues/2643, probably both related.

**Comment by MiKeF05** [comment]
Yes I think it depends on the OS. I use windows and in the other ticket macOS is used.
