### ISSUE TITLE
[Bug report]: Error when trying to create a profile with a once used name

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/firefly#2645]
### Platform

Desktop

### Version

1.4.0-beta-1

### Description

After creating a profile, renaming it from `P2` to `P1` and then logging out to create a new profile (only possible after logging out once after creation of `P2`, see #2643), when attempting to create a new profile `P2`, in the end of the setup process the Error "A wallet with this name already exists." is shown. 

(Also should say "profile" instead of "wallet")

<img width="555" alt="Bildschirmfoto 2022-03-28 um 19 01 41" src="https://user-images.githubusercontent.com/17240275/160451011-626c7271-b01d-46b6-8d2b-2ee973dff2d6.png">

### Expected behaviour

Creation of `P2` should be possible because existing `P2` was renamed to `P1` before.

### Actual behaviour

Error message

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Create a new profile `P2`
2. Log out (necessary because of #2643)
3. Log into `P2` again  
4. Rename `P2` to `P1`
5. Log out 
6. Create a new profile P2 and go trough the setup process

### Operating System

Mac

### Diagnostics

```shell
Firefly v1.4.0-beta-1
Platform: macOS
Platform Version: 12.3
Platform Architecture: x64
CPU Count: 12
Total Memory: 32768.0 MB
Free Memory: 3446.1 MB
```

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicole-obrien** [comment]
Investigating: seems that this is the case until you restart FF, and the error doesn't appear until the end screen and not on the profile name screen. we should fix this.
