### ISSUE TITLE
[Task]: FORGET PASSWORD

### ISSUE THREAD

**Issue by HCHESTER12** [iotaledger/firefly#2651]
### Task description

Hello team, 

I just forget my password since the opening of my fircly wallet, i have a seed and stronghold file but i can't recover my wallet,

Can you help me please ? 

### Requirements

?password

### Acceptance criteria

NA

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by rajivshah3** [comment]
Hi, if you have your Stronghold file you can reset the app by deleting the application data, which is located in a different place depending on your OS:

macOS: `~/Library/Application Support/Firefly` (the Library folder is hidden by default, see [here](https://www.macrumors.com/how-to/reveal-library-folder-in-macos/))
Windows: `%APPDATA%/Firefly`
Linux: `~/.config/Firefly`

Then, you can restore your account with your Stronghold file
