### ISSUE TITLE
[Bug report]: DARK MODE - Setting the wallet color to white #FFFFFF causes text blending with background

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/firefly#2652]
### Platform

Desktop

### Version

1.4.0-beta1

### Description

Setting the wallet color to white on DARK MODE causes some issues like this:
[
![mQoe92G](https://user-images.githubusercontent.com/35224101/160486667-8f9a0fc2-717e-475b-8015-a31cbf0b966f.gif)
](url)

### Expected behaviour

Texts visible on all circumstances

### Actual behaviour

Texts not visible on all circumstances :D

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. set firefly to dark mode
2. choose manual color of wallet to #FFFFFF
3. hover the mouse over the white wallet

### Operating System

Windows

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Staking

Never staked

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicole-obrien** [comment]
Soon to be obsolete component so won't fix.
