### ISSUE TITLE
[Bug report]: Firefly leaves background processes

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/firefly#2672]
### Platform

Desktop

### Version

1.3.3

### Description

When running firefly and making multiple payments (20+) over a period of 30 minutes Firefly was observed to leave behind background processes that are consuming 5% of CPU. These processes were one time individual processes and at another time within the chrome process (see attached images

Case 1 after exiting
![image](https://user-images.githubusercontent.com/44786846/160711447-a7916162-8940-46b2-95bc-3649892c7d60.png)

Case 2 after exiting
![image](https://user-images.githubusercontent.com/44786846/160711476-ad05fe31-76fa-40dc-a68f-0c09e9ef9fcf.png)

For Case 2 I have a mini-dump of one of the processes and will provide if requested

### Expected behaviour

When FF shuts down it closes completely any background tasks

### Actual behaviour

Background tasks remain

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Make multiple FF payments over 30 min

### Operating System

Windows

### Diagnostics

```shell
Windows 11
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Error Messages

None

### Error Logs

```shell
Have mini-dump if requested
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwellmattryan** [comment]
Hey @centercirclesolutions, would you mind sharing the mini dump file, perhaps via Discord DM?

**Comment by rajivshah3** [comment]
@centercirclesolutions I haven't had time to look into this issue yet — does this still happen in 1.4.2?

**Comment by centercirclesolutions** [comment]
I've not seen it happen on FF 141 or 142. I have seen errors come up when resuming from Hibernation but those get a popup and I hop are reported to you guys

**Comment by rajivshah3** [comment]
Great, I think we can close this then. It may have been fixed in the Electron update we did in 1.4.0

>  I have seen errors come up when resuming from Hibernation but those get a popup and I hop are reported to you guys

This should be "fixed" in #2865. This type of error can be ignored and probably relates to your computer not being able to connect shortly after waking up from hibernation, so it doesn't really need to be reported to the user.
