### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by Agpfxdani** [iotaledger/firefly#2685]
### Platform

Desktop

### Version

1.3.3

### Description

On March 28 I made a transfer from firefly to binance and to date I still have not received the funds. They were deducted from my wallet and another receiving and shipping address appears. I am very worried about my funds

Message ID 5c4dd8926e08a6c265788433dd83db35249a2db74db3058ee8bb5cafe180a712

![image](https://user-images.githubusercontent.com/102695664/160919874-fa8f7676-2d49-484a-9e69-8ad9875ec184.png)

### Expected behaviour

Receive my money on Binance

### Actual behaviour

I have not received the funds transferred from the firefly platform

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Receive the money back to my wallet
2. Receive the money on Binance

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
The transaction is already confirmed on the IOTA network.  So you need to contact Binance support that you get the transaction credited.

**Comment by Agpfxdani** [comment]
It's not even my binance address that says there, everything was changed,
the delivery address doesn't say it's mine either, binance doesn't have any
proof that the transfer is for the address, you don't see that there is an
error in the process

**Comment by MiKeF05** [comment]
But you sent the tokens to this address 'iota1qq489gvxrs0nphj2w3a6cl7fupg7pkhh2va9hsfhuaxfhxggh5z76gj8htf' that you used in Firefly. And the tokens were sent to this address

**Comment by Agpfxdani** [comment]
brother I put my binance address with miota they did not reach my address
because that is not my address the shipment had a bug in the application I
do not even know whose address it is

**Comment by Agpfxdani** [comment]
even firefly shipping address is not my wallet either

**Comment by MiKeF05** [comment]
What do you mean with Firefly shipping address is not your wallet?

**Comment by Agpfxdani** [comment]
correct brother, it clearly says another shipping and receiving address

**Comment by Agpfxdani** [comment]
I was sending to my address and they deducted it, but the shipping and
receiving addresses are not the same and I did not receive my iota

**Comment by MiKeF05** [comment]
Like I said Firefly generates a new receive address after you used the one before. The new receive address is on the screenshot on the left side. For the transaction the address before was used. So everything is correct. If you click on the 3 dots in your screenshot and go to address history you see all your adresses of the wallet.

**Comment by MiKeF05** [comment]
And the address with ...8htf at the end is where the tokens were sent that you have entered in the transaction process.

**Comment by Agpfxdani** [comment]
![image](https://user-images.githubusercontent.com/102695664/161283348-2c0bf590-ec0d-4622-9908-048d8308f88a.png)
 

Hello, I was checking and the address is the same as the one I currently receive, apparently it is my same network.


I will attach proof of a previous operation.
![image](https://user-images.githubusercontent.com/102695664/161283798-42749106-f503-461f-97af-bfc6803f8765.png)

**Comment by MiKeF05** [comment]
Okay. And where did you get the following address? Did you copy it from Binance? `iota1qq489gvxrs0nphj2w3a6cl7fupg7pkhh2va9hsfhuaxfhxggh5z76gj8htf`

**Comment by Agpfxdani** [comment]
no brother, do not send to that address and yet it says that it is my
receipt address, my binance address ends in 7 was the one that I copied and
put, the error is that it was sent to a network that I do not know but it
says that it is mine

**Comment by Agpfxdani** [comment]
My address binance is
iota1qzk4gphcvc57g254u29z8v8xnhypfrdrsu8kvjwdx094c2sps98s5tgwuf7

**Comment by MiKeF05** [comment]
From the screenshots and the network there was a transaction from the address `iota1qqu5c4psau5hlcfu0jay2wane6gl4eraxzvm4q4rs0c4a8xjtvl8ul36u0e` to the address `iota1qq489gvxrs0nphj2w3a6cl7fupg7pkhh2va9hsfhuaxfhxggh5z76gj8htf`. This transaction was made within Firefly.

And before you received from Binance on the address `iota1qqu5c4psau5hlcfu0jay2wane6gl4eraxzvm4q4rs0c4a8xjtvl8ul36u0e`.

**Comment by Agpfxdani** [comment]
Yes, the transaction was made to an IOTA network, reviewing previous transactions, note that the same address appears as a recipient in past transactions, that is, the network that was sent is mine but I do not know how to access it and the money is not in any wallet either

**Comment by MiKeF05** [comment]
This address does not belong to your wallet. Binance made severall transfers within one transaction when you received the funds. So when you transfered to `iota1qq489gvxrs0nphj2w3a6cl7fupg7pkhh2va9hsfhuaxfhxggh5z76gj8htf` you do not have any longer access to your funds. Only who has access to this address can transfer the funds now.
