### ISSUE TITLE
ich gebe den Pin ein und firefly öffnet sich nicht mehr, was ist zu tun ? Bitte um hilfe..[Bug report]: 

### ISSUE THREAD

**Issue by donald494** [iotaledger/firefly#2696]
### Platform

Desktop

### Version

1.3.3

### Description

nach meinem Staking lässt sich meine Wallet nicht mehr öffnen....ich habe mal den Pin verkehrt eingegeben und er zeigt mir an falscher Pin .......also mein Pin ist korrekt, aber die Wallet öffnet sich nicht....was kann ich tun ?

### Expected behaviour

Firefly müsste sich öffnen

### Actual behaviour

Öffnet sich nicht mehr

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Diagnostics

```shell
zeigt mir nichts an
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Crash Status

Non-responsive

### Error Messages

nein

### Error Logs

```shell
nein
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Issue was resolved in discussions
