### ISSUE TITLE
[Bug report]: Leaving the IOTA app on ledger device leads to a white screen

### ISSUE THREAD

**Issue by MiKeF05** [iotaledger/firefly#2717]
### Platform

Desktop

### Version

v1.4.0-beta-2

### Description

While being logged in and leaving the IOTA app on a ledger device leads to a white screen.

### Expected behaviour

Closing IOTA app and not getting a white screen

### Actual behaviour

Closing IOTA app and getting a white screen

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Log in to a profile
2. Open IOTA app on ledger device
3. Close IOTA app on ledger device

### Operating System

Windows

### Diagnostics

```shell
Firefly v1.4.0-beta-2
Sprache: de
Währung: USD
Node-Auswahl: Automatisch
Plattform: win32
Plattformversion: 10.0.19044
Plattform-Architektur: x64
CPU-Anzahl: 8
Gesamtspeicher: 8072.2 MB
Freier Speicher: 2553.7 MB
```

### Developer Profile

Yes

### Profile Type

Hardware (Ledger)

### Staking

Never staked

### Crash Status

White screen

### Error Messages

No error message

### Error Logs

```shell
No error logs
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rajivshah3** [comment]
Potentially also related to [FIREFLY-BACKEND-7](https://sentry.io/organizations/iota-foundation-h4/issues/3137258990/?referrer=github_integration). The error on desktop is from `HidD_FreePreparsedData` and the backend error includes `hid_write` in the stacktrace. The error could be coming from interacting with the Ledger device in the Rust backend

**Comment by MiKeF05** [comment]
@rajivshah3 I tried another USB port and with this one everything works fine. So I guess this is probably due to my hardware. I also found out that transactions with the USB port which results in a white screen are very slow. So I don´t think this is Firefly related.
