### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by jpodeschva** [iotaledger/firefly#2723]
### Platform

Desktop

### Version

1.3.3

### Description

I was trying to make an internal transaction with my Ledger and when I tried to make the transfer, the amount that should remain in the main wallet was much lower.

### Expected behaviour

Example, 240mi transaction from a wallet that had 1,240Gi to one that had 190Mi

### Actual behaviour

Before making the 240mi transaction from a wallet that had 1,240Gi to one that had 190Mi, the result should be 1Gi in the main one and the FireFly announced that there were 940mi left

### Can the issue reliably be reproduced?

No

### Operating System

Windows

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Previously staked

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
I think you need to pay attention that this is UTXO based. So the remainder don´t need to be the rest of the whole wallet. If you have more addresses in one wallet then the remainder can also be from one address

**Comment by jpodeschva** [comment]
> I think you need to pay attention that this is UTXO based. So the remainder don´t need to be the rest of the whole wallet. If you have more addresses in one wallet then the remainder can also be from one address

Thanks but in my case I have only 2 adress

**Comment by jpodeschva** [comment]
> I think you need to pay attention that this is UTXO based. So the remainder don´t need to be the rest of the whole wallet. If you have more addresses in one wallet then the remainder can also be from one address

OK. I check then. Thanks

**Comment by jpodeschva** [comment]
> I think you need to pay attention that this is UTXO based. So the remainder don´t need to be the rest of the whole wallet. If you have more addresses in one wallet then the remainder can also be from one address

OK. I check it and is this case. Thanks!!
