### ISSUE TITLE
[Sub Task] Light mode has different colours for each of the navigation bars, dark mode should follow something similar

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#2735]

**Comment by nicole-obrien** [comment]
Was there a decision on this? Or should we close it?

**Comment by begonaalvarezd** [comment]
> Was there a decision on this? Or should we close it?

I havent closed it because nothing was implemented yet. Should we include a `gray-1000`?

**Comment by nicole-obrien** [comment]
What are your thoughts on this? `#15233B`
<img width="1348" alt="Screenshot 2022-04-11 at 21 58 23" src="https://user-images.githubusercontent.com/89913787/162831039-4db50f85-f3fc-4ffe-90d4-53149886ae10.png">
