### ISSUE TITLE
[Bug report]: Unable to update Firefly app on Desktop

### ISSUE THREAD

**Issue by BrotherSnare** [iotaledger/firefly#2750]
### Platform

Desktop

### Version

1.3.3

### Description

App Version: 1.3.3

platform: macOS
platformVersion: 11.6.1
platformArchitecture: x64
cpuCount: 16
totalMem: 16384.0 MB
freeMem: 154.6 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: Cannot download "https://dl.firefly.iota.org/firefly-desktop-1.4.0.zip", status 403: 

### Expected behaviour

Able to update the Firefly wallet with no incident

### Actual behaviour

Getting the error message seen in the Description.  Also seen below:

App Version: 1.3.3

platform: macOS
platformVersion: 11.6.1
platformArchitecture: x64
cpuCount: 16
totalMem: 16384.0 MB
freeMem: 154.6 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: Cannot download "https://dl.firefly.iota.org/firefly-desktop-1.4.0.zip", status 403: 

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Log into Firefly app on Mac
2. Attempt to update the app from version 1.3.3 to the latest version
3. This is where the error message appeared

### Operating System

Mac

### Diagnostics

```shell
Firefly v1.3.3
Language: en
Currency: GBP
Node selection: Automatic
Platform: macOS
Platform Version: 11.6.1
Platform Architecture: x64
CPU Count: 16
Total Memory: 16384.0 MB
Free Memory: 209.6 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Error Messages

Pls refer to the above error message

### Error Logs

```shell
Mon, 28 Mar 2022 20:22:01 GMT
ClientError: `error sending request for url (https://chrysalis-nodes.iota.org/api/v1/info): operation timed out`

Mon, 28 Mar 2022 17:15:55 GMT
ReqwestError: error sending request for url (https://chrysalis-nodes.iota.org/api/plugins/participation/addresses/iota1qrl34ewlj5ulw6ge3yzk07n0j22rppg3pg03jp00xek047g796lhz99ayke): error trying to connect: tcp connect error: Operation timed out (os error 60)

`
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by beare84** [comment]
Also occurs on Linux:
App Version: 1.3.3

platform: linux
platformVersion: 5.4.0-107-generic
platformArchitecture: x64
cpuCount: 4
totalMem: 7916.1 MB
freeMem: 2242.9 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: Cannot download "https://dl.firefly.iota.org/firefly-desktop-1.4.0.AppImage", status 403:

**Comment by ScaNicky** [comment]
The new version 1.4.0 of firefly contains a bug, the download has been disabled pending a fix.

**Comment by iamochuko** [comment]
> The new version 1.4.0 of firefly contains a bug, the download has been disabled pending a fix.

Noted...

**Comment by MiKeF05** [comment]
https://github.com/iotaledger/firefly/discussions/2748
