### ISSUE TITLE
[Bug report]: Update Error 1.3.3 - 1.4

### ISSUE THREAD

**Issue by RupertDunmil** [iotaledger/firefly#2751]
### Platform

Desktop

### Version

1.3.3

### Description

Clicking "Upgrade" from 1.3.3 to the 1.4 it throws an uncaught error.

### Expected behaviour

Upgrade would work

### Actual behaviour

Threw following error

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. open app in 1.3.3
2. click upgrade
3. Error

### Operating System

Mac

### Diagnostics

```shell
Firefly v1.3.3
Language: en
Currency: USD
Node selection: Manual
Platform: macOS
Platform Version: 12.3.1
Platform Architecture: x64
CPU Count: 8
Total Memory: 32768.0 MB
Free Memory: 4879.4 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Error Messages

App Version: 1.3.3

platform: macOS
platformVersion: 12.3.1
platformArchitecture: x64
cpuCount: 8
totalMem: 32768.0 MB
freeMem: 5411.2 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: Cannot download "https://dl.firefly.iota.org/firefly-desktop-1.4.0.zip", status 403: 

### Error Logs

```shell
Mon, 04 Apr 2022 22:42:10 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Mon, 04 Apr 2022 22:42:08 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Mon, 04 Apr 2022 22:41:36 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Mon, 04 Apr 2022 22:41:30 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rajivshah3** [comment]
We've currently removed 1.4.0 due to a bug. We'll also fix the update alert so that it does not prompt you to update

**Comment by stereoIII6** [comment]
alright thnx...
i was just about to report the issue ...
because of digital same same !
