### ISSUE TITLE
[Bug report]: Error: net::ERR_NETWORK_CHANGED

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/firefly#2782]
### Platform

Desktop

### Version

1.4.1

### Description

Error on resume from Hibernation

### Expected behaviour

Resumes

### Actual behaviour

Error

App Version: 1.4.1

platform: win32
platformVersion: 10.0.22563
platformArchitecture: x64
cpuCount: 32
totalMem: 32680.4 MB
freeMem: 12048.5 MB

Error Type: [Main Context] Unhandled Rejection

Error: net::ERR_NETWORK_CHANGED

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Launch FF
Hibernate
Resume

### Operating System

Windows

### Diagnostics

```shell
App Version: 1.4.1

platform: win32
platformVersion: 10.0.22563
platformArchitecture: x64
cpuCount: 32
totalMem: 32680.4 MB
freeMem: 12048.5 MB

Error Type: [Main Context] Unhandled Rejection

Error: net::ERR_NETWORK_CHANGED
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

Non-responsive

### Error Messages

Popup

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicole-obrien** [comment]
Hi, I don't think this error really means anything. And we should just swallow it when it occurs.

**Comment by centercirclesolutions** [comment]
I get the same when hibernating on 1.4.2

App Version: 1.4.2

platform: win32
platformVersion: 10.0.22563
platformArchitecture: x64
cpuCount: 32
totalMem: 32680.4 MB
freeMem: 7938.2 MB

Error Type: [Main Context] Unhandled Rejection

Error: net::ERR_NETWORK_IO_SUSPENDED
