### ISSUE TITLE
[Bug Report] After click payment link no UI reaction

### ISSUE THREAD

**Issue by lein1013** [iotaledger/firefly#2832]
### Platform

Desktop

### Version

1.4.2

### Description

After clicking the payment link the Firefly Desktop app opens and the payment is prefilled. But since I want to send from another wallet (same profile) I click on the wallet symbol. Then the wallets are shown (left button stil the "Payment details added from IOTA link" active), but the UI does not responds
Close app - restart 

### Expected behaviour

as in the previous version 1.3.3 (? at least I think so), I could change the wallet and proced with the payment

### Actual behaviour

UI freezes

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. click IOTA payment link
2. click on wallet symbol (left toolbar) (profile needs to have multiple wallets)
3. click on another wallet -> wallet will not change (restart needed)

### Operating System

Windows

### Diagnostics

```shell
Firefly v1.4.2
Language: en
Currency: EUR
Node selection: Automatic
Platform: win32
Platform Version: 10.0.22593
Platform Architecture: x64
CPU Count: 12
Total Memory: 32519.3 MB
Free Memory: 13903.9 MB
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Previously staked

### Crash Status

Non-responsive

### Error Messages

Diagnosis was after restart

### Error Logs

```shell
not available
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicole-obrien** [comment]
Thank you! This will be fixed with UI changes in 1.5.0, therefor I will close this.
