### ISSUE TITLE
[Bug report]: Balance finder doesn't find anything

### ISSUE THREAD

**Issue by skippic** [iotaledger/firefly#2914]
### Platform

Desktop

### Version

1.4.2

### Description

Firefly Balance finder combined with Ledger probably only searches a limited amount of addresses and even clicking on it for one hour doesn't find anything. It is true, that my account has a long history with a lot of wallets and addresses, but one would expect to find something. 

Wallets up to 100, transfers and therefore addresses more than 100, less than 1000.

Tried with different Ledgers on different PCs. Balance finder searches for 1s, 25s, 1s, 25s, 25s, 1s, 25s, 25s, 1s, 25s, 25s, 1s, 25s, 25s, 1s, 25s, 25s, 1s, 25s, 25s...

Ledger works fine with MM for example and also on old PC and Firefly with TX history.

All PCs are Intel based, Win10 and Win11. I use good USB cables, no hub. Brave tends to give me notifications, that Ledger was connected, so that might interrupt some kind of process.

Consulted with Antonio and was told to paste the issue here.

### Expected behaviour

Recover Firefly wallet balances.

### Actual behaviour

Keeps searching balances forever without any luck.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Reinstall Firefly deleting \AppData\Roaming\Firefly
2. Create a profile
3. Migrate wallet
4. I have Ledger backup
5. Firefly Ledger backup
6. Pin 2x
7. Continue, Restore, Finish
8. Wait for sync
9. Settings, Balance finder
10. Find balances
11. Search, Search, Search, Search......

### Operating System

Windows

### Diagnostics

```shell
Firefly v1.4.2
Language: en
Currency: USD
Node selection: Automatic
Platform: win32
Platform Version: 10.0.22000
Platform Architecture: x64
CPU Count: 16
Total Memory: 32617.6 MB
Free Memory: 17420.1 MB
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Previously staked

### Crash Status

None of the above

### Error Messages

-

### Error Logs

```shell
Empty
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Does your ledger display "Generating Address" when you use the balance finder to search for balance?

**Comment by skippic** [comment]
Yes, it changes between "Generating Address" and the iota symbol once in a while

**Comment by MiKeF05** [comment]
Each time you search for a balance 10 addresses will be searched. So if you have many addresses I think you need to search a few times without closing the pop-up. When you close the balance finder pop-up the search begins from the first address again.

**Comment by nicole-obrien** [comment]
I think the balance finder definitely needs improving, at least in the next update we will show you what number of wallets and addresses per wallet have been searched. But we should improve the search algorithm.

**Comment by skippic** [comment]
It could just search addresses until interrupted and show progress.

**Comment by MiKeF05** [comment]
Can you try to transfer 1Mi to your wallet and then snyc again with the balance finder?

**Comment by skippic** [comment]
I kind of worked it out. Made 100 wallets adding 1Mi each time and then used the Balance finder to discover more. Let's hope it works better in Shimmer, because this is horrible user experience!
