### ISSUE TITLE
[Bug report]: i can't log in with my pin

### ISSUE THREAD

**Issue by stanimir-id** [iotaledger/firefly#2922]
### Platform

Desktop

### Version

1.4.2

### Description

i can't log in with my pin only i have access to the computer and only i have all the information is happening to me for the second time

### Expected behaviour

lol

### Actual behaviour

lol

### Can the issue reliably be reproduced?

No

### Steps to reproduce the issue

 lol

### Operating System

Windows

### Diagnostics

```shell
no
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

Non-responsive

### Error Messages

no

### Error Logs

```shell
no
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rajivshah3** [comment]
Can you please try the new version, 1.5.0?

**Comment by MiKeF05** [comment]
@stanimir-id I´m going to close this issue. Feel free to open it again if you have further issues.
