### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by yintolerance** [iotaledger/firefly#2925]
### Platform

Desktop

### Version

1.4.2

### Description

ping code input problem

### Expected behaviour

Unable to enter ping codes continuously

### Actual behaviour

Unable to enter ping codes continuously

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Unable to enter ping codes continuously
The ping code error is displayed after intermittently entering the ping code

### Operating System

Windows

### Diagnostics

```shell
Unable to enter ping codes continuously
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rajivshah3** [comment]
Can you please elaborate on the exact steps you're following? Please also try in the new version, 1.5.0

**Comment by MiKeF05** [comment]
@yintolerance I´m going to close this issue. Feel free to open it again if you have further issues.
