### ISSUE TITLE
[Bug report]: Error: Uncaught Error: node-loader

### ISSUE THREAD

**Issue by richirich32** [iotaledger/firefly#2956]
### Platform

Desktop

### Version

1.5.0

### Description

App Version: 1.5.0

platform: win32
platformVersion: 10.0.19044
platformArchitecture: x64
cpuCount: 8
totalMem: 16317.5 MB
freeMem: 9033.0 MB

Error Type: [Preload Context] Error

Error: Uncaught Error: node-loader:
Error: The module 'C:\Users\XXX\AppData\Local\Temp\d0ad441e-f867-4f29-97d6-b93ddd3ae579.tmp.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 87. This version of Node.js requires
NODE_MODULE_VERSION 85. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

### Expected behaviour

open Firefly App

### Actual behaviour

crash with a white screen

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. doubleclick Firefly-App
2. crash with a white screen
3. error popup shows up

### Operating System

Windows

### Diagnostics

```shell
- not accessible
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Previously staked

### Crash Status

White screen

### Error Messages

App Version: 1.5.0

platform: win32
platformVersion: 10.0.19044
platformArchitecture: x64
cpuCount: 8
totalMem: 16317.5 MB
freeMem: 8445.5 MB

Error Type: [Preload Context] Error

Error: Uncaught Error: node-loader:
Error: The module 'C:\Users\XXX\AppData\Local\Temp\4c11b3a1-c71e-49a1-aa79-114a3eddd373.tmp.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 87. This version of Node.js requires
NODE_MODULE_VERSION 85. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

### Error Logs

```shell
- not accessible
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rajivshah3** [comment]
Was this version compiled locally or are you using an official version of Firefly?
