### ISSUE TITLE
Whitespace as account name leads to app freeze

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/firefly#296]
## Issue description

Firefly lets me create a new account with whitespace as account name (" "). When trying to switch to this newly created account, firefly is showing a white page and seems to freeze. UI interaction isn't working anymore.

## Wallet version

https://github.com/iotaledger/firefly/suites/2207785779/artifacts/45651262

## System specification

macOS BigSur 11.3 Public Beta

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

1. Create a new account with one whitespace as account name
2. Select the new account

## Expected behaviour

Prevent me from using only whitespace as account name

## Actual behaviour

Application freezes after selecting the account

## Errors

<img width="1392" alt="Bildschirmfoto 2021-03-08 um 23 22 12" src="https://user-images.githubusercontent.com/17240275/110390252-fb3c0900-8065-11eb-9071-84d5725a9e6a.png">
<img width="552" alt="Bildschirmfoto 2021-03-08 um 23 25 27" src="https://user-images.githubusercontent.com/17240275/110390268-01ca8080-8066-11eb-9ba9-0965551062f1.png">

**Comment by obany** [comment]
This is fixes in the next release please re-open if you still have issues.
