### ISSUE TITLE
[Bug report]: Password not set and unable to proceed for staking

### ISSUE THREAD

**Issue by vikky4446** [iotaledger/firefly#2962]
### Platform

Desktop

### Version

1.5.0

### Description

I haven't set my password for Firefly. I'm trying to stake my Miota for Assembly. I am prompted to enter password. I haven't set any password previously and I don't see any other option to proceed for staking
![Firefly error](https://user-images.githubusercontent.com/104023549/164059119-ef01bf9d-7516-4a3b-870f-72303464be7a.JPG)
.

### Expected behaviour

1. I should have an option to use my recovery phrase since I haven't set my password
2. There should be an option to set my password using my recovery phrase

### Actual behaviour

1. I am unable to proceed for staking as it is asking for password
2. Not able to set passwor
![Firefly error](https://user-images.githubusercontent.com/104023549/164059409-6e2bc87d-0d01-47e6-acdf-a74d70df95b1.JPG)
d

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Install Firefly 1.4.0 version
2. Do not set the password and just set the Pin
3. Upgrade to 1.5.0 version
4. Try to stake the Iota for Assembly
5. You will be prompted for password with no other option

### Operating System

Windows

### Diagnostics

```shell
views.dashboard.security.version.title
Language: en
Currency: USD
Node selection: Automatic
Platform: win32
Platform Version: 10.0.17134
Platform Architecture: x64
CPU Count: 8
Total Memory: 8039.2 MB
Free Memory: 2312.3 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Answered in discussion https://github.com/iotaledger/firefly/discussions/2960
