### ISSUE TITLE
macOS 11 app icon - meet design guidelines

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/firefly#297]
![firefly](https://user-images.githubusercontent.com/17240275/110391032-325eea00-8067-11eb-9936-31a7b2761d11.png)
symbolic^

## Description

The app icon should match the design guidelines for macOS 11 (rounded rectangle).

[https://developer.apple.com/design/human-interface-guidelines/macos/overview/whats-new-in-macos/](https://developer.apple.com/design/human-interface-guidelines/macos/overview/whats-new-in-macos/)

## Motivation

Aesthetics, I guess 🙂

**Comment by rajivshah3** [comment]
@r-c-k this should be fixed in the 0.3.0 release

**Comment by r-c-k** [comment]
@rajivshah3 yep looks good. I’ll just add the beta label concept here in case it is considered.

<img width="1306" alt="C7AB709A-83B1-47AA-8467-D2C5FDDAFDEC" src="https://user-images.githubusercontent.com/17240275/112065209-8c31da80-8b64-11eb-9b3d-735959b9ea06.png">
