### ISSUE TITLE
[Bug report]: The balance of shimmer and assembly in firefly is no longer displayed

### ISSUE THREAD

**Issue by kaosoul** [iotaledger/firefly#2988]
### Platform

Desktop

### Version

1.5.1

### Description

The balance of shimmer and assembly in firefly is no longer displayed since the update to 1.5.1

Problem on ledger ans stronghold

### Expected behaviour

The balance of shimmer and assembly in firefly is no longer displayed since the update to 1.5.1

Problem on ledger ans stronghold

### Actual behaviour

The balance of shimmer and assembly in firefly is no longer displayed since the update to 1.5.1

Problem on ledger ans stronghold

### Can the issue reliably be reproduced?

Yes

### Operating System

Linux

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Actively staking

### Crash Status

Non-responsive

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kaosoul** [comment]
I dont use VPN. I do what I always do. With version 1.5.1, the shimmer and assembly balance is not displayed

**Comment by kaosoul** [comment]
I live in Reunion Island. The submarine cable seems to be damaged. Maybe the problem is with the cable.

**Comment by MiKeF05** [comment]
Have you already tried to use the balance finder in the settings a few times in a row? I´m going to close this issue as it is a duplicate to https://github.com/iotaledger/firefly/issues/4016. Feel free to open the issue again if you have further problems.
