### ISSUE TITLE
Receive & Send buttons become unreachable with too many accounts

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/firefly#302]
## Issue description

When creating multiple accounts (7 in my case), the Receive and Send buttons in the Account panel become unreachable without resizing the window. 

## Wallet version

https://github.com/iotaledger/firefly/suites/2207785779/artifacts/45651262

## System specification

macOS 11.3 Beta

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

1. Create multiple accounts

## Expected behaviour

A scrollbar should appear to reach the  Receive & Send buttons

## Actual behaviour

Buttons become unreachable

## Errors

<img width="391" alt="Bildschirmfoto 2021-03-08 um 23 49 18" src="https://user-images.githubusercontent.com/17240275/110392737-b2864f00-8069-11eb-8e52-ba9941e78555.png">

**Comment by obany** [comment]
This should be fixed, please reopen if still an issue
