### ISSUE TITLE
[Bug report]: An error "Something went wrong"

### ISSUE THREAD

**Issue by 19812003** [iotaledger/firefly#3021]
### Platform

Desktop

### Version

1.5.1

### Description

When I try to do any transcation I get an error "something went wrong". It happends when i try to send my tokens or to stake them. Can't do anything.

### Expected behaviour

I expect that everything will work

### Actual behaviour

After any action i get an error "something went wrong"

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Diagnostics

```shell
views.dashboard.security.version.title
Language: en
Currency: USD
Node selection: Manual
Platform: win32
Platform Version: 10.0.19044
Platform Architecture: x64
CPU Count: 12
Total Memory: 15741.3 MB
Free Memory: 8425.4 MB
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Previously staked

### Crash Status

None of the above

### Error Messages

Что-то пошло не так. Something went wrong.

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 19812003** [comment]
![image](https://user-images.githubusercontent.com/100508447/164764554-f47fda0c-7291-403f-8891-5d60fbfe5245.png)

**Comment by MiKeF05** [comment]
Please check in the error log in the menu. Maybe you use a wrong ledger?

**Comment by 19812003** [comment]
thanks )it helped ) the ledger was different
