### ISSUE TITLE
[Bug report]: Error when trying to migrate funds

### ISSUE THREAD

**Issue by PickledPigeon** [iotaledger/firefly#3026]
### Platform

Desktop

### Version

1.5.1

### Description

Problems migrating funds from old Trinity to new Firefly. Keeps asking me to try again

### Expected behaviour

Migration of funds

### Actual behaviour

Pop up "There was an error migrating your finds, please try again"

### Can the issue reliably be reproduced?

No

### Operating System

Windows

### Diagnostics

```shell
"There was an error migrating your finds, please try again"
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Error Messages

"There was an error migrating your finds, please try again"

### Error Logs

```shell
"There was an error migrating your finds, please try again"
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwellmattryan** [comment]
Hey @PickledPigeon, is there any extra information in the "Error log" whenever you try this?

**Comment by MiKeF05** [comment]
@PickledPigeon I´m going to close this issue. Feel free to open it again if you have further issues.
