### ISSUE TITLE
Multiple accounts breaks account selector

### ISSUE THREAD

**Issue by NemesisFLX** [iotaledger/firefly#303]
## Issue description

Several issues when the amout of accounts reach a certain limit
![image](https://user-images.githubusercontent.com/9351775/110392721-ad290480-8069-11eb-8b8b-72bcb5a36280.png)
![image](https://user-images.githubusercontent.com/9351775/110392739-b4501280-8069-11eb-8b6c-65a3944ec343.png)

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch): v0.0.1

## System specification

What is your operating system?

Windows 10

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Create many accounts

## Expected behaviour

Limit the number of accounts

## Actual behaviour

It seems to be unlimited but after 18 accounts i cant even reach them anymore

**Comment by obany** [comment]
This should be fixed in the next release, please re-open if the problem persists.
