### ISSUE TITLE
[Bug report]: Cannot find balance of wallet with high index

### ISSUE THREAD

**Issue by Marcima** [iotaledger/firefly#3038]
### Platform

Desktop

### Version

1.5.1

### Description

My balance is 0 and my wallets aren't shown. I've tried to press the button " searching for balance" so often, but it can't be found. I have a very high Ledger Index number (****) .... I wonder if that could be the problem. 

### Expected behaviour

I actualized Firefly, thought my former balance, with my 6 wallets would be shown.... latest after pressing the button to find the funds.

### Actual behaviour

The balance is 0, the former wallets and history aren't there, not at all after pressing the button for several times.

### Can the issue reliably be reproduced?

No

### Operating System

Windows

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwellmattryan** [comment]
Hey @Marcima, is it both your wallets and addresses that have the high index, or just the wallets? One potential improvement for the balance finder could be an advanced option to start the search on a specific wallet and address index :thinking:

**Comment by Marcima** [comment]
Hi maxwellmattryan, I don't know the adress index but the wallet index, which was also necessary for the migration from Trinity to Firefly is very high, over thousand. Another point is, that I had 3 wallets and while staking assembly and shimmer there was a bug, so I had to create 3 new wallets in Firefly and had to send the money from the original 3 wallets to the new ones. So my first 3 wallets were empty and the whole balance is on the 3 new ones. I don't know if that affects anything. Thank you!
