### ISSUE TITLE
[Bug report]: something went wrong notification after typing in correct pw

### ISSUE THREAD

**Issue by lukestara** [iotaledger/firefly#3092]
### Platform

Desktop

### Version

1.0.0

### Description

I want to enter my firefly wallet. After typing in the correct pw a notification popped up which tells me that "something went wrong". I am wondering what that could be.. still I could not enter my wallet and still cannot.

### Expected behaviour

wallet should be open after typing in correct pw.

### Actual behaviour

nothing happens except for that pop-up notification mentioned in the description section.

### Can the issue reliably be reproduced?

No

### Operating System

Mac

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

Non-responsive

### Error Messages

something went wrong

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Do you really use Firefly v1.0.0? If yes you should update to the latest version. And with pw do you mean the password or the PIN?

**Comment by lukestara** [comment]
Yes I meant the PIN. additionally it is not possible to update to the latest version out of the wallet itself as it always tells me that something went wrong
