### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by marzgithub858** [iotaledger/firefly#3175]
### Platform

Desktop

### Version

1.5.1

### Description

Updated my firefly wallet (desktop windows) to the latest version 1.5.1 and after a successfull update, the SHIMMER $SMR token which I earned as rewards (from staking IOTA) didn't appear in my holdings.  Only the ASSEMBLY $ASMB token appeared. 

### Expected behaviour

Was expecting ASSEMBLY $ASMB token and SHIMMER $SMR token , both of which were earned as rewards from STAKING IOTA, would still appear and be reflected in my holdings after the successful update of FIREFLY Desktop (windows) version 1.5.1 wallet. 

### Actual behaviour

Only the Assembly $ASMB token was reflected in my token holdings after the update.

### Can the issue reliably be reproduced?

No

### Operating System

Windows

### Diagnostics

```shell
na
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Error Messages

na

### Error Logs

```shell
na
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Have you already tried to use the balance finder in the settings a few times in a row? I´m going to close this issue as it is a duplicate to https://github.com/iotaledger/firefly/issues/4016. Feel free to open the issue again if you have further problems.
