### ISSUE TITLE
[Bug report]: 0 Mi have positive USD value 

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/firefly#3190]
### Platform

Desktop

### Version

1.5.1

### Description

<img width="392" alt="Bildschirmfoto 2022-05-13 um 10 11 27" src="https://user-images.githubusercontent.com/17240275/168231515-5584a3aa-aea8-4986-8a77-fc4a27ed1ad2.png">

Firefly currently shows a value of 0.35 USD for 0 Mi, after creating a new profile.

### Expected behaviour

0 Mi should equal 0 USD.

### Actual behaviour

0 Mi are equal to some positive USD value.

### Can the issue reliably be reproduced?

Yes

### Operating System

Mac

### Diagnostics

```shell
views.dashboard.security.version.title (???)
Language: en
Currency: USD
Node selection: Automatic
Platform: macOS
Platform Version: 12.3.1
Platform Architecture: x64
CPU Count: 12
Total Memory: 32768.0 MB
Free Memory: 11128.1 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Never staked

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by r-c-k** [comment]
Nevermind 😅

**Comment by MiKeF05** [comment]
This is the actual price of 1 MIOTA. So should be okay

**Comment by r-c-k** [comment]
Just noticed, sorry 😅
