### ISSUE TITLE
[Bug report]: Staking Firefly

### ISSUE THREAD

**Issue by Bundeslade** [iotaledger/firefly#3238]
### Platform

Desktop

### Version

1.5.1

### Description

Hallo, habe meine Iota zum staking freigegeben - offensichtlich funktioniert es. Nun, vielleicht lächerlich: das Männchen auf der linken seite; normalerweise müsste die Animation laufen. linkes objekt nach rechts in die Hand. das macht er nicht. Hat dies Auswirkungen auf das Staking oder die Sicherheit?

Danke
<img width="1440" alt="Bildschirmfoto 2022-05-17 um 14 46 09" src="https://user-images.githubusercontent.com/60068781/168816395-b72de429-ffaf-42f2-bac7-70c485d69a2e.png">

### Expected behaviour

Die Animation läuft, wie beim ersten Staking

### Actual behaviour

Die Animation stockt - aus der linken Hand will ein Gegenstand (Blub?) die Hand verlassen - macht es aber nicht

### Can the issue reliably be reproduced?

No

### Operating System

Mac

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tuditi** [comment]
Do you have this issue still in 1.6?

**Comment by Bundeslade** [comment]
Thx for reaction; yesterday suddenly it works. JörgGesendet mit der GMX Mail AppAm 01.06.22 um 09:09 schrieb Tuditi
                
            
            
                
                    Von: "Tuditi" ***@***.***>Datum: 1. Juni 2022An: "iotaledger/firefly" ***@***.***>Cc: "Bundeslade" ***@***.***>,"Author" ***@***.***>Betreff: Re: [iotaledger/firefly] [Bug report]: Staking Firefly (Issue #3238)
                
                
Do you have this issue still in 1.6.0?

**Comment by Tuditi** [comment]
Then I'll close this issue! :rocket:

**Comment by Bundeslade** [comment]
Ah - okGesendet mit der GMX Mail AppAm 01.06.22 um 11:10 schrieb Tuditi
                
            
            
                
                    Von: "Tuditi" ***@***.***>Datum: 1. Juni 2022An: "iotaledger/firefly" ***@***.***>Cc: "Bundeslade" ***@***.***>,"Author" ***@***.***>Betreff: Re: [iotaledger/firefly] [Bug report]: Staking Firefly (Issue #3238)
                
                

Then I'll close this issue! 🚀
