### ISSUE TITLE
[Bug report]: Firefly logo in App-Icon not aligned (macOS)

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/firefly#3251]
### Platform

Desktop

### Version

1.5.1

### Description

<img width="512" alt="ff" src="https://user-images.githubusercontent.com/17240275/169029451-3cb8d8a5-af78-4721-9f5b-9db86955dd28.png">

The Firefly logo in the App-Icon is not properly aligned.
Visual/Optical alignment might be considered over pixel alignment.

![align](https://user-images.githubusercontent.com/17240275/169032681-8ed181c3-528b-4fea-8459-884dd903c9af.png)

### Expected behaviour

Aligned properly

### Actual behaviour

Not aligned

### Can the issue reliably be reproduced?

Yes

### Operating System

Mac

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicole-obrien** [comment]
Hey thats some serious eye for detail, will pass on to UX/UI team.
