### ISSUE TITLE
(UX Feature Request) PIN auto-submit & PIN length suggestion

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/firefly#332]
## Description
PIN should auto-submit itself after entering the last character (common for example in Windows PIN login screen or binance when putting in 2FA code. After typing last character (when correct of course) it does log in automatically without pressing enter

Also! Pretty standard for the PINs are 4 or 8, won't be better to choose some of these instead of 6?

## Motivation
Better User Experience

## Requirements
1. Changing pin lenght (or be able to choose) from 6 to 4 or 8 number lenght
2. Auto logging after entering last number from the PIN

## Are you planning to do it yourself in a pull request?
No

**Comment by obany** [comment]
Auto submit of the PIN is included in the next version.
