### ISSUE TITLE
[Task]: Define Mobile minimum versions

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/firefly#3342]
### Task description

Define the minimum versions for mobile on iOS and Android.

### Requirements

* Ensure OS version is still receiving security updates
* Ensure support in Capacitor (https://capacitorjs.com/docs/android#android-support, https://capacitorjs.com/docs/ios#ios-support)

### Acceptance criteria

* Minimum version agreed by the team
* Security audit approval

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by amadeu2** [comment]
# Minimum versions - evaluation criteria

## Android
https://developer.android.com/topic/security/best-practices
https://developer.android.com/training/articles/security-tips#WebView

### Android 7.0:
ref: https://developer.android.com/about/versions/nougat/android-7.1

ref: https://blog.ostorlab.co/webviews-security-android-ios.html
- the geolocation API will only be allowed on secure origins (over HTTPS.)
- WebView runs web content in a separate sandboxed process (🔴 I could not find on Android docs this, it's on android 8 link bellow)
- Safe Browsing API added to notify when WebView attempts to navigate to a URL that Google has classified as a known threat. 

ref: https://en.wikipedia.org/wiki/Android_Nougat
Android Nougat went unsupported with no more security updates after October 2019.

### Android 8
ref: https://developer.android.com/about/versions/oreo/android-8.0-changes#security-all
- Your app's WebView objects now run in multiprocess mode. Web content is handled in a separate, isolated process from the containing app's process for enhanced security.
- For information about security enhancements related to use of native libraries, see Native Libraries.(https://developer.android.com/about/versions/oreo/android-8.0-changes#nl)

## Android 9
ref: https://developer.android.com/about/versions/pie/android-9.0#security
- Unified biometric authentication dialog
- APK signature scheme with key rotation

## Android 10
ref: https://developer.android.com/about/versions/10/features#security
- Improved biometric authentication dialogs

## Android 11
ref: https://developer.android.com/about/versions/11/features#security
- Biometric authentication updates

## Android 12
ref: https://developer.android.com/about/versions/12/features#security-privacy
- Hide application overlay windows
- Bluetooth permissions 

## iOS
WIP
