### ISSUE TITLE
No explanation of recovery phrase form + Missing seed checksum

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/firefly#335]
## Issue description
No explanation of how recovery phrase should be entered on the account recovery screen

## Wallet version
0.0.1

## Steps To reproduce the issue
1. Try to recover an account from existing recovery phrases
2. It's not obvious how you should enter the phrases. It should be like every work in another row? Every word after space or after comma? Or maybe with numbers like 1.word1 2.word2 etc?

## Expected behaviour
It should be explained or Firefly should recognize after first word what we're typing in (seed or phrases) and let us know how to correctly put the words in the field.

**+ Also it would be good to have the checksum on the bottom after typing in normal seed.**

![cUlAcTE](https://user-images.githubusercontent.com/35224101/110468913-3c213580-80d9-11eb-8d0f-c565804b1abd.png)

**Comment by maxhq** [comment]
Also: it lets me painfully enter my seed (only all uppercase works) and only then it says: "Seeds are currently not supported."

**Comment by ArshaParsa** [comment]
> This is planned for a later version. We currently have basic validation where if you hit space it considers it a recovery phrase.

hi. I did not understand

**Comment by ArshaParsa** [comment]
> ## Issue description
> No explanation of how recovery phrase should be entered on the account recovery screen
> 
> ## Wallet version
> 0.0.1
> 
> ## Steps To reproduce the issue
> 1. Try to recover an account from existing recovery phrases
> 2. It's not obvious how you should enter the phrases. It should be like every work in another row? Every word after space or after comma? Or maybe with numbers like 1.word1 2.word2 etc?
> 
> ## Expected behaviour
> It should be explained or Firefly should recognize after first word what we're typing in (seed or phrases) and let us know how to correctly put the words in the field.
> 

........... I Copied and pasted all 81 words like attached pic. ( this is 63 words of 81) 



> **+ Also it would be good to have the checksum on the bottom after typing in normal seed.**
> 
> ![cUlAcTE](https://user-images.githubusercontent.com/35224101/110468913-3c213580-80d9-11eb-8d0f-c565804b1abd.png)

![image_2021-08-03_183943](https://user-images.githubusercontent.com/39510122/128030073-75e91220-a88a-4000-91ca-bf6acc944c9c.png)

**Comment by cvarley100** [comment]
Seed checksum is now there. It also tells you to add spaces for the recovery phrase.
