### ISSUE TITLE
Fund search on existing seed entry

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/firefly#337]
## Issue description
Too many tokens on the account after entering Trinity seed

## Wallet version
0.0.1

## System specification
Latest Windows 10 build

## Is it a repeatable issue?
Y

## Steps To reproduce the issue
1. Try to recover an account from the normal Trinity seed
2. Firefly will immediately see it as 45000 USD account **when there it is 1Mi on it**
![VzPhMnz](https://user-images.githubusercontent.com/35224101/110470279-f1082200-80da-11eb-83fc-e50f356353e7.png)
3. Clicking on "No, check again" will give you short "foo" in the console.
![aYUI8mc](https://user-images.githubusercontent.com/35224101/110470463-290f6500-80db-11eb-9c58-f940fbbffabf.png)

## Expected behaviour
I should see 1Mi on this account, not 45kUSD :)

**Comment by cvarley100** [comment]
Closing this as it will be available in the migration build.
