### ISSUE TITLE
[Subtask]: Handle TransactionProgress

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#3371]
### Task description

TBD

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
Lets leave this open and blocked until we plan exactly how to use this, as the current implementation is a copy of what we used to do and this might not be what we want to do.
