### ISSUE TITLE
[Bug report]: Calulation of votes seems to be wrong

### ISSUE THREAD

**Issue by Karuma303** [iotaledger/firefly#3383]
### Platform

Desktop

### Version

1.6.1

### Description

There seem to be some issues with the numbers that are shown in the voting view

### Expected behaviour

- The number of my counted votes should show a fraction of the number of my maximum votes regarding the time that I already locked them for voting.
- The number of my counted votes should show a fraction of the number of total votes that are shown via tooltip over the bars of the graph

### Actual behaviour

After one hour of voting

- the number of my counted votes is already at roughly 1/3 of the number of maximum votes 
- the number of my counted votes is roughly at 2.5% of the number of total votes 

Both of these number should be wrong, regarding that the vote counting phase is only open for one hour and also regarding that I'm not a whale and I'm not owning a mentionable high number of tokens

### Can the issue reliably be reproduced?

No

### Operating System

Windows

### Diagnostics

```shell
Version 1.6.1
Language: en
Currency: EUR
Node selection: Manual
Platform: win32
Platform Version: 10.0.22000
Platform Architecture: x64
CPU Count: 12
Total Memory: 16111.2 MB
Free Memory: 6050.4 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rajivshah3** [comment]
Thanks for the report! This was fixed in #3384 and released in v1.6.2
