### ISSUE TITLE
[Task]: E12.M3 - Collectibles gallery view with media

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#3436]
### Task description

Initalize the technical collectibles module

### Requirements

- [ ] #3438
- [ ] #3439

### Acceptance criteria

Meets the above requirements.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by kraftjs** [comment]
Closing issue as stale
