### ISSUE TITLE
[Bug report]: shimmer is not showing in my iota wallet?

### ISSUE THREAD

**Issue by asifibnayyub** [iotaledger/firefly#3461]
### Platform

Desktop

### Version

1.6.2

### Description

after update my shimmer is not visible in iota wallet...
IOTA FIREFLY WALLET ADDRESSS: iota1qp8qjel9dwe3f9epe4fvcnjjxsmmr7n9ytynjxwe7ehl9myaalwmvjj9rwn

[thetangle.org](https://thetangle.org/)EXPLORER:

IOTA WALLET2:iota1qrl86q0cn0ev8cduq6h2350md6mp99xcwfudr4ju3rtkqghnqfvy7rps44w

### Expected behaviour

WALLET 2 DISAPPEAR AFTER UPDATE

### Actual behaviour

WALLET 2 DISAPPEAR AFTER UPDATE

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Error Messages

BALANCE FINDER UNABLE TO FIND MY 2ND WALLET

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Have you already tried to use the balance finder in the settings a few times in a row? You can also try to create a second wallet and use the balance finder. I´m going to close this issue as it is a duplicate to https://github.com/iotaledger/firefly/issues/4016. Feel free to open the issue again if you have further problems.
