### ISSUE TITLE
[Task]: Correctly handle errors in restore account

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#3492]
### Task description

Currently, we don't show a notification/error upon restoration of an acount if:

- a wrong password is supplied to the import
- a wrong file is uploaded (we limit file types, but e.g. .txt files can be uploaded)

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jeeanribeiro** [comment]
Tried to reproduce the issues described, but it was probably solved in another PRs
