### ISSUE TITLE
General UX Ideas / Food for thought

### ISSUE THREAD

**Issue by Metz-2** [iotaledger/firefly#353]
**Issue description**
General Ideas for the User Interface and workflow

**Wallet version**
0.0.1

* "Back up your wallet" window needs a "Yes, i have read and understood this" checkbox.
* Entering PIN should instantly unlock the Acccount (no need to click the button). e.g. bitfinex does that with the 2FA and i like it a lot.
* Design is not consistent between send and receive windows. "Receive funds" has a **X** top right to close the window. "send payment" has a **back** button.
* Simplified transition between functions (remove the X / "back" to close window). For example, if I want to switch from the receive to the send window, the process is: click x, click send. it would prefer to always be able to quickly switch. maybe with tabs?
* multiple "send" windows are confusing. you have the send button on the main screen which leads to a window with account selection drop-down menu. and the other way of first select account > send funds. which then looks a bit different. that could lead to confusion. this should be unified.
* the "incoming" / "outgoing" counter are counterintuitive and confusing. it reads like they are incoming or outgoing _right now_ instead of what the overall volume was. it also does not seem to seperate between accounts. and in general i don't see much sense to have that kind of statistic on the front page. better add a dedicated statistic page with e.g. volume per day, etc.
* The whole window is much too wide. it should be possible to remove or at least collapse/minimize the Portfolio Overview. plus the "Security Box" could be as well just 4 smaller icons on the top of the window or in the menu bar on the left. a wallet that takes 80% of my screen is just too big. 
* settings window needs a "back" button. e.g. going All Settings > Profile i have no way going back to the Settings overview except clicking again on the accounts >  all settings button bottom left.

**Comment by antalm** [comment]
> Adding on top of your send/receive comments, I think IF can do better with the graphics for the send and receive. I feel that the receive button reminds me of the share button on my iphone (which is counter intuitive because we use this to SEND on iPhone). I also feel that the receive graphic looks too much like a refresh icon.

I think iPhone share has an upward arrow, like this:
![iphone_share](https://user-images.githubusercontent.com/29548853/112521440-cb4a7080-8d9c-11eb-823f-86ab8933ad0d.png)

I am completely OK with the current one, but I understand it may confuse others. Probably the arrow should point to a stylized open wallet consisting of only a very few lines. But that could also be confusing.

**Comment by cvarley100** [comment]
@UmbahaSpodPaha some good suggestions here. Please can you break down your suggestions into individual issues - it is easier to maintain.
