### ISSUE TITLE
[Task]: Fix UI layout on smaller devices

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3539]
### Task description

Some of the UI elements like input fields, buttons, texts and labels are not always fitting into the screen space which often causes overflows or overlapping on smaller device screens.  

### Requirements

Adjust the responsiveness of the mobile UI for smaller Screen sizes.

### Acceptance criteria

Can be closed when the requirements are complete.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by amadeu2** [comment]
Closed as tested with Iphone SE and working nice now.
