### ISSUE TITLE
[Task]: Fix PIN code input detection on mobile

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3544]
### Task description

When the PIN code is entered quickly, inputs are sometimes not detected.

### Requirements

Entering the pin code doesn't miss user inputs

### Acceptance criteria

The requirements have to be completed.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by kweelulaay** [comment]
Passcode is correct but can't login to account in my PC how ?

**Comment by amadeu2** [comment]
With the new changes on https://github.com/iotaledger/firefly/pull/4041 seems i'ts solved 🙂 I've just tested on my phones and ca't reproduceit anymore.
Please @paul-boegelsack test it on your phones to confirm, thanks!

**Comment by paul-boegelsack** [comment]
Hey @amadeu2 sorry I missed that. Checked it with your pull request and it works like intended 👍
