### ISSUE TITLE
[Task]: Check locales everywhere once 1.6 is merged

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#3630]

**Comment by amadeu2** [comment]
Language issues are still there then of 1.5 merge.

**Comment by paul-boegelsack** [comment]
Seems there is an issue with the reactivity on main view: When changing the language, buttons and texts are not translated. @begonaalvarezd Maybe a similar issue like here: https://github.com/iotaledger/firefly/issues/3669
