### ISSUE TITLE
[Task]: Make auto-select language at `Welcome`

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#3652]
### Description

Could be implemented with [navigator.language](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language) or the Capacitor [getLanguageCode()](https://capacitorjs.com/docs/v2/apis/device#getlanguagecode)

### Requirements

- [ ] Works on Android
- [ ] Works on iOS

**Comment by paul-boegelsack** [comment]
@amadeu2 Seems this has been working since the mergers?
