### ISSUE TITLE
[Task]: Add ActionSheet to change profile name

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#3655]
### Description

Use the ActionSheet native plugin to allow change the profile name from the profile menu as designed on Figma.

### Requirements

- [ ] Works on Android
- [ ] Works on iOS

**Comment by paul-boegelsack** [comment]
@amadeu2 I guess this should appear when you click on the profile name? Maybe it's better to jump right into the edit view when you do that?

**Comment by amadeu2** [comment]
hmm not sure, we could ask Valerie for details on Discord UX channel
