### ISSUE TITLE
Updated to FireFly 1.6.2 and not showing iota ion wallet or that iota is staked.... [Bug report]: 

### ISSUE THREAD

**Issue by Mikey888888** [iotaledger/firefly#3658]
### Platform

Desktop

### Version

1.6.2

### Description

Updated to FireFly 1.6.2 and not showing iota in iota wallet or that iota is staked. 

Was staking iota for Assembly with Firefly 1.6.1 but after update it isnt showing anything either in iota wallet or that the Iota is being staked for Assembly...

Help!!!

### Expected behaviour

Developers to help fix the issue so it shows the correct balance in Iota wallet and the Staked Assembly option.

### Actual behaviour

Upgraded from Firefly 1.6.1 to Firefly 1.6.2 and afterwards shows 0 iota and that iota is not being staked for Assembly....

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Upgrade from firefly 1.6.1 to firefly 1.6.2 

### Operating System

Windows

### Diagnostics

```shell
Version 1.6.2
Language: en
Currency: USD
Node selection: Automatic
Platform: win32
Platform Version: 10.0.19043
Platform Architecture: x64
CPU Count: 8
Total Memory: 8134.5 MB
Free Memory: 2776.4 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Have you already tried to use the balance finder in the settings a few times in a row? I´m going to close this issue as it is a duplicate to https://github.com/iotaledger/firefly/issues/4016. Feel free to open the issue again if you have further problems.
