### ISSUE TITLE
[Task]: Keyboard shouldn't move up any content

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3702]
### Task description

TBD

### Requirements

App content stays where it is when the keyboard is shown.

### Acceptance criteria

Can be closed when the requirement is complet.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
Closing this task because implementing this will lead to inputs not being visible anymore. We should make a UI study beforehand
