### ISSUE TITLE
[Task]: Fix success message at onboarding

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#3720]
### Description

Currently the message on the Success screen at confirming the recovery phrase in not centered.
Center the message as Figma design.

### Requirements

- [x] Works on Android
- [ ] Works on iOS

**Comment by paul-boegelsack** [comment]
@amadeu2 Just to get things right, you mean the success screen of the recovery phrase or the screen that comes after, when the profile setup is complete? Seems in the figma design is just one screen left (Profile complete).

**Comment by amadeu2** [comment]
You right, I will do this task since I modified it before. There was some limitations to fulfill that specific changes, I'll walk around it and let you know.
