### ISSUE TITLE
Firefly Iota abheben 

### ISSUE THREAD

**Issue by Maddin00711** [iotaledger/firefly#3742]
### Task description

Ich kann meine iota von Firefly nicht abheben ich werde nach meinem password gefragt was ich dann eingeben und es geht nicht ? es ist doch mein firefly password oder ? 

### Requirements

.

### Acceptance criteria

.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by MiKeF05** [comment]
Es gibt eine PIN und ein Passwort. Zum Versenden von Token benötigst du das Passwort.

**Comment by Maddin00711** [comment]
kann ich das passwort noch änder ? oder ein neues machen ?

**Comment by paul-boegelsack** [comment]
Du kannst dein Password in den Einstellungen ändern, allerdings brauchst du dafür das alte Passwort. Wenn das nicht funktioniert, kannst du mit deiner recovery phrase ein neues Profil anlegen und das alte danach löschen.

**Comment by Maddin00711** [comment]
Vielen Dank :)

**Comment by paul-boegelsack** [comment]
Gerne :)

**Comment by Maddin00711** [comment]
wenn ich ein neues Profil mache und das alte lösche sind deann meine Iota weg ?

**Comment by paul-boegelsack** [comment]
Nein, deine Iota hängen im übertragenen Sinne an deiner recovery phrase. Solange du die hast, kannst du deine Wallet jederzeit reproduzieren. Ich würde dir allerdings empfehlen erst das neue Profil anzulegen, bevor du das alte löschst. Wenn du nur ein Profil hast, geht es sowieso nicht anders.

**Comment by Maddin00711** [comment]
okay vielen dank für deine wissen :)
