### ISSUE TITLE
[Task]: Update Electron

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#3743]
### Task description

Update Electron to a major version (>=14) now that we're not using the Proxy object anymore.

See for more info: https://github.com/iotaledger/firefly/issues/2213

### Requirements

Electron version at least 14. 16 would be even better.

### Acceptance criteria

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by MiKeF05** [comment]
The update should also fix this issue https://github.com/iotaledger/firefly/issues/1628. @rajivshah3 mentioned something that this was solved with Electron 13.5 or later.

**Comment by Tuditi** [comment]
Bumping into a similar issue: https://github.com/TryGhost/node-sqlite3/issues/1504

**Comment by Tuditi** [comment]
I think the problem is related to the deprecation of `allowRendererProcessReuse`

If I understand it correctly the renderer process crashes, because it fails to initialize the native modules (I tried building N-API modules in wallet.rs), upon a reload. Possibly `neon` is not the right tool to generate the bindings. We could have a look into napi-rs to build new bindings, but this requires some work of wallet.rs.

https://github.com/electron/electron/issues/18397

**Comment by Tuditi** [comment]
Here is a repository that contains only the relevant code for the crash for Electron v14 and higher: https://github.com/Tuditi/native-module-issue
