### ISSUE TITLE
[Task]: Adapt entire app to overlay keyboard

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#3748]
### Description

Then of https://github.com/iotaledger/firefly/issues/3735 was merged, we need to adapt the on boarding flow, send flow and everywhere there is an input.

### Requirements

- [ ] Works on Android
- [ ] Works on iOS

**Comment by paul-boegelsack** [comment]
@amadeu2 @begonaalvarezd Should be all in one drawer regarding the feedback, right? The UX feedback also mentions that the password drawer is the only one that should be full sized. Maybe two additional drawer components (SendConfirm, SendPassword)?

**Comment by amadeu2** [comment]
> @amadeu2 @begonaalvarezd Should be all in one drawer regarding the feedback, right? The UX feedback also mentions that the password drawer is the only one that should be full sized. Maybe two additional drawer components (SendConfirm, SendPassword)?

IMO the proposed changes on send flow at Trello needs to be discussed together with the keyboard changes to avoid scrolls. I'm currently looking a way to implement the changes with the less modifications as possible, some direction should be decided before implement it to avoid double work. Have you soem proposal in your mind?
