### ISSUE TITLE
[Task]: Fix titles at wallet actions drawers

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#3749]
### Description

Currently the wallet actions drawers has their title as previous design. We need to center each one as  Figma design.

### Requirements

- [ ] Works on Android
- [ ] Works on iOS

**Comment by paul-boegelsack** [comment]
@amadeu2 We had some feedback about the wallet actions on trello:

_"View address history" and "export transaction history" should be removed from the action sheet and moved to the settings "advanced" section._

Don't know if we should address this with this task, what do you think?
