### ISSUE TITLE
[Subtask]: Fix custom date picker selecting wrong date

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#3751]
The custom date picker is selecting the wrong date whenever we select the custom date picker. i.e. If we use the picker to select the date 12th of august, if we change are mind and reselect it then it shows the currently selected date as the 8th of December. Looks like we are putting the month and day the wrong way round maybe?

**Comment by Tuditi** [comment]
@nicole-obrien , I don't seem to have this issue
