### ISSUE TITLE
[Bug report]: Add custom node info field does not accept '/'

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#3754]
### Platform

Desktop

### Version

stardust-developt

### Description

There is a bug in the onboarding flow, on the `Connect to a custom network` page. It looks like manually inputting the `/` character in the Node Address field is impossible. Copying works fine

### Expected behaviour

I should be able to type the node address in manually

### Actual behaviour

Typing `/` doesn't work in the node address field

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Create a Profile
2. Choose Shimmer protocol
3. Choose 'Custom Network`
4. Try typing in the node URI in Node Address field

### Operating System

Linux

### Diagnostics

```shell
TBD
```

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Crash Status

Non-responsive

### Error Messages

TBD

### Error Logs

```shell
TBD
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MarkNerdi** [comment]
Resolved with:
https://github.com/iotaledger/firefly/pull/3866/files
