### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by m-garcia1998** [iotaledger/firefly#3767]
### Platform

Desktop

### Version

1.6.2

### Description

In one of my wallets I don't get what I had accumulated in shimmer

### Expected behaviour

i want to see that i dont lose my stake

### Actual behaviour

i cant see my reward on shimmer when i stake on the first step

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Actively staking

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Can you try to use the balance finder? I´m going to close this issue as it is a duplicate to https://github.com/iotaledger/firefly/issues/4016. Feel free to open this issue if you have further issues.
