### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by cedricdonigarten** [iotaledger/firefly#3775]
### Platform

Desktop

### Version

1.6.2

### Description

Previous assembly staking rewards not visible (previous shimmer rewards are visible).
Cannot participate in the current staking period which should remain 18 more days.

### Expected behaviour

Assembly staking rewards should be visible

### Actual behaviour

no rewards visible. protokoll:
Mon, 04 Jul 2022 11:28:27 GMT
Network: Failed to fetch staking result for 'shimmer.json'

Mon, 04 Jul 2022 11:28:27 GMT
Network: Failed to fetch staking result for 'assembly_01.json'

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/97615319/177146950-15902d08-7ae6-440c-b1d3-2546ed32ff9f.png">

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Just start Firefly

### Operating System

Windows

### Diagnostics

```shell
Version 1.6.2
Sprache: de
Währung: USD
Node-Auswahl: Automatisch
Plattform: win32
Plattformversion: 10.0.19043
Plattform-Architektur: x64
CPU-Anzahl: 16
Gesamtspeicher: 16056.5 MB
Freier Speicher: 6583.3 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Error Messages

Mon, 04 Jul 2022 11:28:27 GMT
Network: Failed to fetch staking result for 'shimmer.json'

Mon, 04 Jul 2022 11:28:27 GMT
Network: Failed to fetch staking result for 'assembly_01.json'

### Error Logs

```shell
Mon, 04 Jul 2022 11:28:27 GMT
Network: Failed to fetch staking result for 'shimmer.json'

Mon, 04 Jul 2022 11:28:27 GMT
Network: Failed to fetch staking result for 'assembly_01.json'
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
It seems that the request gets blocked. Do you have any special firewall or a VPN? I´m going to close this issue as it is a duplicate to https://github.com/iotaledger/firefly/issues/4016. Feel free to open this issue again if you have further problems.
