### ISSUE TITLE
[Bug report]: Cannot create a new software wallet. It get stucked after re-enter pin code

### ISSUE THREAD

**Issue by urko-b** [iotaledger/firefly#3777]
### Platform

Desktop

### Version

1.6.2

### Description

Cannot create a new software wallet. It get stucked after re-enter pin code

### Expected behaviour

To create a new wallet

### Actual behaviour

It get stucked

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Create a new software wallet
2. Set password
3. Set numeric PIN Code
4. Re-Enter PIN CODE
5. Then it get stucked

### Operating System

Linux

### Diagnostics

```shell
Version 1.6.2
Language: en
Currency: USD
Node selection: Automatic
Platform: linux
Platform Version: 5.14.21-2-MANJARO
Platform Architecture: x64
CPU Count: 8
Total Memory: 13868.6 MB
Free Memory: 953.6 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Crash Status

Infinite loading symbol

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Can you try to install gnome-keyring? I´m going to close this issue as it is a duplicate to https://github.com/iotaledger/firefly/issues/3847

**Comment by urko-b** [comment]
@MiKeF05 thx so much, now is working fine. Please could you add this package to installation file?

**Comment by MiKeF05** [comment]
@rajivshah3 @nicole-obrien @cvarley100 Maybe this could be done in a next release?
