### ISSUE TITLE
[Task]: Fix crash at open ActionSheet

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#3782]
### Description

To reproduce the issue, we need to double tap the 3-dots button at account switcher drawer, before the ActionSheet plugin is opened. The app crashes with the next error:
![Image](https://user-images.githubusercontent.com/7059509/177231904-30c6a968-0b21-455e-a393-7c588e8eea53.jpg)

This could be better reproduced the first time the ActionSheet plugin is called. This cold-run in some cases is taking almost 1 second on my Samsung A22, that long time led me to tap more than one time. On iOS there is less time at the cold-run, but still notable on my Iphone 7 iOS 14.

### Requirements

- [ ] Works on Android
- [ ] Works on iOS

**Comment by paul-boegelsack** [comment]
@amadeu2 Yeah, thats annoying. Don't know if we can make it faster. Maybe it would be a workaround to disable the button or the click event while the sheet is called?
