### ISSUE TITLE
[Task]: Modify release cloud yaml to track latest mobile version

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#3799]
### Task description

TBD

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by cvarley100** [comment]
This is not needed for the website. We can just link to the respective app stores where the version is listed.
