### ISSUE TITLE
[Windows10] Firefly dont work in Windows 10 Sandbox

### ISSUE THREAD

**Issue by Donk119** [iotaledger/firefly#386]
## Issue description

When trying to open Firefly in the Windows Sandbox, the following error message appears.

![Sandbox](https://user-images.githubusercontent.com/34712382/110748739-73f6bd00-8240-11eb-9e2e-4f51739d8467.png)

Apparently, the Sandbox Windows cannot open app.asar.

The Windows 10 Sandbox is only available to Windows 10 Pro / Business users. The sandbox must be enabled separately and the bug should only affect a minimal number of users. 

https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview

## Wallet version

Alpha 0.0.1

## System specification

Windows 10 Pro Build 21327

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Start Firefly in a Windows Sandbox

## Expected behaviour

That Firefly opens.

## Actual behaviour

Firefly does not open

## Errors

Screenshot is above.

**Comment by obany** [comment]
Could you try installing the VC++ runtime and see if this fixes the issue https://www.microsoft.com/en-us/download/details.aspx?id=53840

**Comment by Donk119** [comment]
These versions are installed on my system. 

![image](https://user-images.githubusercontent.com/34712382/112815783-f4ab1b00-9080-11eb-8714-839ccf65d2a9.png)

**Comment by obany** [comment]
are they installed in the sandbox ?

**Comment by Donk119** [comment]
good point :-D
Now it works.

![image](https://user-images.githubusercontent.com/34712382/112817027-499b6100-9082-11eb-8576-a16669228929.png)
