### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by bazchap** [iotaledger/firefly#3868]
### Platform

Desktop

### Version

1.6.3

### Description

have just updated new version of firefly wallet & my Miota were all gone, balance was zero for my Miota. After doing a balance finder the Miota arrived
when i updated my firefly it made me go through the whole setup again including 24 word phrase. Not all of my shimmer & assembly tokens are there now still because i had a 2nd wallet that just had Assembly & shimmer from staking even though there are no iota in this wallet now as this 2nd wallet was used for buying NFT's. This wallet has now disappeared in the new update to 1.6.3 & so the assembly & shimmer from this 2nd wallet are not showing in my overall balances. WHAT HAVE I TO DO?

### Expected behaviour

I expected to just sign in to the older version, then update to the newer version without having to go through the whole setup again. I also expected both the wallets to be there & the full amount of my shimmer assembly & Miota tokens to be showing

### Actual behaviour

When i tried to sign in it made me start the setup. I went to the three bars at top left, checked for updates then it took me to Iota website as usual & i downloaded the update 1.6.3. It made me go through the whole setup once i had the new update ready. As soon as i opened it at first all of my Miota shimmer & assembly were missing. Some of my shimmer & assembly are still missing. After looking in the balance finder my Iota returned but a 2nd wallet i had (which only had shimmer & assembkly in from staking over the 2 periods of staking) has not shown up in this new update. The wallet no longer has any Iota in it as it was used for buying NFT's but it had an accumulation of shimmer & assembly in it. Now because the 2nd wallet is missing the tokens from staking that were in this wallet are missing from the main shimmer & assembly balances. I've tried signing out & back in again but to no avail. HELP !! 

### Can the issue reliably be reproduced?

No

### Operating System

Windows

### Diagnostics

```shell
Version 1.6.3
Language: en
Currency: GBP
Node selection: Automatic
Platform: win32
Platform Version: 10.0.19043
Platform Architecture: x64
CPU Count: 4
Total Memory: 3981.7 MB
Free Memory: 1051.3 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Have you tried to use the balance finder many times in a row? Also try to create the second wallet and use the balance finder again.

**Comment by bazchap** [comment]
Hi there thanks for the contact. Yes i tried this straight away & the 2nd
wallet was there but with nothing in it. No matter what i tried at first
nothing was showing. The ASMB & SMR only appeared after about a week & are
now in the 2nd wallet. The only thing i've noticed is the account
transaction history is no longer there for account 2, just the recent ones.
But at least the tokens are now back. Kind regards, Barry

**Comment by MiKeF05** [comment]
If you restore your profile with the stronghold file the transaction should be restored. When you restore your profile with the 24 words and the message has already been pruned on the node then the history can´t be restored. So better save a stronghold backup file and the whole transaction history will be restored.
