### ISSUE TITLE
[Bug report]: Recovery phrase restores not all but only single wallet

### ISSUE THREAD

**Issue by westbounce** [iotaledger/firefly#3879]
### Platform

Desktop

### Version

1.6.3

### Description

Due to a laptop crash i have to recovery my firefly wallet. I succeded by providing the recovery phrase from the firefly wallet recovery kit. However the restore only restored a single wallet. However over the course of firefly upgrades, i ended up having 2 wallets, one for ASMB staking and the other, now missing wallet, for SMR staking. Please help to recover my second wallet. 

### Expected behaviour

secondary wallet must also be recovered

### Actual behaviour

secondary wallet did not recover

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

install wallet
enter recovery phrase

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

None of the above

### Error Messages

none

### Error Logs

```shell
none
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
You can try to use the balance finder in the settings. After this everything should appear again. Feel free to open this issue again if you have further issues.

**Comment by westbounce** [comment]
I have run balance finder against all available iota notes each time hitting search more than 30 times. The second wallet and it's iota balance came back but i am still missing the SMR balance. Firefly has been updated to v1.6.4. How can i recover the SMR balance?

**Comment by MiKeF05** [comment]
Do you use a special firewall or a VPN? You can also try to recover your wallet once again and run the balance finder.

**Comment by westbounce** [comment]
no special firewall or vpn. standard windows 10 (no company issued device), so no special security in place. I have recovered the wallet already twice on 2 different device. same result.

**Comment by MiKeF05** [comment]
Have you already checked the staking address on thetangle.org?

**Comment by westbounce** [comment]
update to firefly 1.6.5 has resolved the issue
