### ISSUE TITLE
[Bug report]:  Fix language unknown error

### ISSUE THREAD

**Issue by annie101101046** [iotaledger/firefly#3888]
### Platform

Desktop

### Version

desktop-2.0.0-beta-1.0.1

### Description

 When using the Shimmer Firefly wallet, if change the language will show an unknown error.

### Expected behaviour

If the language setting has an issue, needs to show up an error message.

### Actual behaviour

Here are the steps:

1. Choose Simplified Chinese
2. Then set the Pin Code
3. Click Next
4. Then there is no response and no error message

And if switch back to EN, it can work. 

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Choose Simplified Chinese
2. Then set the Pin Code
3. Click Next
4. Then there is no response and no error message

### Operating System

Linux

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

Non-responsive

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MarkNerdi** [comment]
It looks like the problem are non-latin alphabets. 
I tested it with: greek, russian, chinese for i got stuck after entering the pin, and english, german, italian, spanish for which it works

**Comment by maxwellmattryan** [comment]
Hmm I've tested Japanese and Chinese both in the dev instance and the Beta build - didn't have any problems with this :thinking: @annie101101046 would you mind providing more info about your system / OS?

**Comment by kraftjs** [comment]
I've also just tested with simplified Chinese, recovering a profile and logging into an already created profile, and I cannot reproduce this issue.

**Comment by MarkNerdi** [comment]
Also cannot reproduce it.
