### ISSUE TITLE
[Bug report]: Fix Metadata UI textarea with a scrollbar to display metadata

### ISSUE THREAD

**Issue by annie101101046** [iotaledger/firefly#3898]
### Platform

Desktop

### Version

desktop-2.0.0-beta-1.0.1

### Description

The Metadata fee's UI section needs to fix with a scrollbar if the metadata text area is too long.

### Expected behaviour

There should be a textarea with a scrollbar to display the metadata.

### Actual behaviour

The Metadata fee's UI section needs to fix with a scrollbar if the metadata text area is too long.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Click the metadata fee section
2. Click and check the metadata text area
3. Metadata text area was too long
4. The UI was out of control

### Operating System

Linux

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MarkNerdi** [comment]
Fixed in newer version
