### ISSUE TITLE
RTL Languages: Spacing & alignment issues

### ISSUE THREAD

**Issue by karimkozman** [iotaledger/firefly#391]
## Issue description

1. spacing issues/overlapp (Amount number)

![Screen Shot 2021-03-10 at 3 51 45 PM copy3](https://user-images.githubusercontent.com/25418520/110771752-26d41480-825b-11eb-9ab2-ad8742fd1390.jpg)

2. close button overlapping current version text in update popup

![Firefly copy](https://user-images.githubusercontent.com/25418520/110771671-0dcb6380-825b-11eb-9c37-c8d5fe3568a3.jpg)

## Wallet version

Which version of wallet are you using?

develop branch

## System specification

What is your operating system?

Mac version 11.2

**Comment by cvarley100** [comment]
RTL is disabled for now. Will be reenabled with proper integration later on.
