### ISSUE TITLE
[Bug report]: Storage Deposit Return Unfullilled

### ISSUE THREAD

**Issue by sdellava** [iotaledger/firefly#3910]
### Platform

Desktop

### Version

Stardust - Alpha

### Description

I've sent some SMR to an address with 1 hour expiration. The recipent (me) did not claim the funds.

This is the tx: [0xa734cb8f1651509eb68e8d29a579796100d483782e28b313f62cdd755aae7750](https://explorer.alphanet.iotaledger.net/alphanet/transaction/0xa734cb8f1651509eb68e8d29a579796100d483782e28b313f62cdd755aae7750)

Now I can't use my balance. Firefly report the error StorageDepositReturnUnfullilled

### Expected behaviour

The balance is correct but I'm not expecting the error.

### Actual behaviour

Impossible to use balance to make a new tx.

### Can the issue reliably be reproduced?

No

### Operating System

Windows

### Diagnostics

```shell
I can't make a diagnosis
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Error Messages

StorageDepositReturnUnfullilled

### Error Logs

```shell
no error log
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MarkNerdi** [comment]
Resolved with:
https://github.com/iotaledger/firefly/pull/4018
