### ISSUE TITLE
[Bug report]: Special character supported in password on desktop is not supported on mobile

### ISSUE THREAD

**Issue by Zenlight** [iotaledger/firefly#3914]
### Platform

Mobile

### Version

0.1.0

### Description

One is currently unable to import or create a wallets with a single quotation mark (") anywhere in the password when using the iOS Firefly Beta, however it is supported on desktop (Mac).
I assume that the same issue is present on Android, but I dont have any device to verify this.

### Expected behaviour

The same special characters supported when creating/importing passwords on desktop should exist on mobile

### Actual behaviour

The continue button is disabled (as expected), but nothing happens after this. 
One can also not go back to the previous steps, but the background animations keep working so its difficult for a user to know if its just slow or if there is an error.
No error message is presented to the user.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Input two identical randomly generated passwords consisting on no special characters in both fields.
2. Add one " anywhere in the same place of both fields.
3. Click on "Continue"

### Operating System

iOS

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Crash Status

Non-responsive

### Error Messages

None

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zenlight** [comment]
This issue is also present in the Firefly Stardust Beta it seems. Any update on this issue?

**Comment by Tuditi** [comment]
We can confirm that it's present on the latest mobile beta as well. We're going to move it into our next sprint.
