### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by Ace2308** [iotaledger/firefly#3935]
### Platform

Desktop

### Version

1.6.3

### Description

My Assembly Staking has completely disappeared.  I don't see my coins staking or showing up in the wallet.

### Expected behaviour

I expected to login and see my coins staking...they are all gone!

### Actual behaviour

Says - MI for staked funds...

### Can the issue reliably be reproduced?

Yes

### Operating System

Mac

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
There will be a fix in 1.6.5. In the meantime can you try to run the balance finder in the settings?

**Comment by MiKeF05** [comment]
I´m going to close this issue as it is a duplicate to https://github.com/iotaledger/firefly/issues/4016
