### ISSUE TITLE
[Task]: fix receive screen for small devices 

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3940]
### Task description

![image](https://user-images.githubusercontent.com/6748220/179948560-a9eec990-a110-49b0-8f0f-f54cccdb08dc.png)

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by amadeu2** [comment]
itś fixed now
