### ISSUE TITLE
[Task]: Balance is not updated after the stronghold import 

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3951]
### Task description

https://trello.com/c/2hE2WTO9/104-no-balance-and-transaction-history-is-shown-if-you-imported-the-wallet-with-a-phrase-on-google-pixel-6

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by amadeu2** [comment]
Yesterday I've been testing with 1.6.5 on Android / iOS and it's solved now 💪
