### ISSUE TITLE
[Bug report]: gpu_data_manager_impl_private.cc(415)] GPU process isn't usable

### ISSUE THREAD

**Issue by arne-fuchs** [iotaledger/firefly#3987]
### Platform

Desktop

### Version

1.6.3

### Description

Ubuntu 22.04 LTS with Gnome X11
NVIDIA GTX 1080 Ti 
Driver Version: 510.73.05

### Expected behaviour

Expected the program to start

### Actual behaviour

Window opens and crashes after a second.
Terminal output:

`Update for version 1.6.3 is not available (latest version: 1.6.3, downgrade is disallowed).
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[27144:0722/175135.296364:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)`

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1.Running Ubuntu 22.04 with Gnome X11 and a GTX 1080 Ti with driver 510.73.05
2.Download AppImage of Firefly
3.chmod +x firefly-desktop....
4.Execute

### Operating System

Linux

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Crash Status

Application closed

### Error Logs

```shell
Update for version 1.6.3 is not available (latest version: 1.6.3, downgrade is disallowed).
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[27144:0722/175135.296364:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arne-fuchs** [comment]
Same problem in version 1.6.4

**Comment by MiKeF05** [comment]
I guess this is a duplicate to https://github.com/iotaledger/firefly/issues/1628. Can you try the workaround described there

**Comment by arne-fuchs** [comment]
The problem still persists even with the --disable-gpu or --ignore-gpu-blacklist flag.
I can't access my funds right now and I cant stake.

**Comment by katian** [comment]
@arne-fuchs try : 

https://github.com/iotaledger/firefly/issues/4215#issuecomment-1214174116

**Comment by arne-fuchs** [comment]
The workaround did work
