### ISSUE TITLE
[Task]: The delete action is still displayed for an account when it has received transactions

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#3998]
### Task description

The delete action for an account is displayed even if it has already received funds. The action changes only after a restart to hide wallet.

<img width="384" alt="image" src="https://user-images.githubusercontent.com/6748220/180749016-46dec106-4650-416e-86f0-093048a07245.png">

<img width="302" alt="image" src="https://user-images.githubusercontent.com/6748220/180749181-e130dada-9136-4cc3-a819-5d9671fdf2c3.png">

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by amadeu2** [comment]
Also there is an issue with hide wallet action
