### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by JoeRadd** [iotaledger/firefly#4028]
### Platform

Desktop

### Version

1.6.4

### Description

Staking shows new event for assebly but wont let me stake

### Expected behaviour

firefly will let me stake for assembly

### Actual behaviour

firefly shows no option to stake for assembly

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

open firefly - confirm balance
go to staking tab see assembly says new event
staking click box is greyed out

### Operating System

Windows

### Diagnostics

```shell
Version 1.6.4
Language: en
Currency: USD
Node selection: Automatic
Platform: win32
Platform Version: 10.0.19044
Platform Architecture: x64
CPU Count: 12
Total Memory: 65462.6 MB
Free Memory: 58473.2 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Try to sync your account with the balance finder in the settings. You can also try to change the node in the network settings.

**Comment by MiKeF05** [comment]
You can also try to use version 1.6.5. I´m going to close this issue as it is a duplicate to https://github.com/iotaledger/firefly/issues/4133
