### ISSUE TITLE
[Bug report]: I had 750,588.618 update and now I have 750.588618

### ISSUE THREAD

**Issue by cucattigaston** [iotaledger/firefly#4044]
### Platform

Desktop

### Version

1.6.4

### Description

I did a wallet update on July 26, 2022 and the place of the comma (,) in the wallet was changed. Before I had 750,588.618 and now I have 750.588618.

### Expected behaviour

expected that when updating the wallet, the same values that it had would be preserved and that the amount would not change.

### Actual behaviour

I did a wallet update on July 26, 2022 and the place of the comma (,) in the wallet was changed. Before I had 750,588.618 and now I have 750.588618.

### Can the issue reliably be reproduced?

No

### Steps to reproduce the issue

MacBook Air.

### Operating System

Mac

### Diagnostics

```shell
I do not have
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

None of the above

### Error Messages

Ninguno

### Error Logs

```shell
Ninguno
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
This is correct. The unit of Shimmer has been changed. But you have the same amount of tokens like before. See also https://twitter.com/fireflywallet/status/1552319343412842496?t=4Ff-VDehCih8NsJdwtm_jw&s=19
