### ISSUE TITLE
[Bug report]: Assemblys have disappeared from the wallet and I can't do staking either.

### ISSUE THREAD

**Issue by JaviCrypto** [iotaledger/firefly#4053]
### Platform

Desktop

### Version

1.6.4

### Description

In my Firefly wallet, I don't see the accumulated Assemblies and it is not allowing me to start the third phase of IOTA staking per Assembly either.

### Expected behaviour

In the portfolio I should be able to see my IOTAS as well as the Shimmer and Assemblys.

It should also be possible to start the new phase of staking of IOTAs per Assemblys.

### Actual behaviour

When I log in to Firefly, I get an alert, which says "Something went wrong", but it doesn't let me log in, it doesn't look like my usual wallet information and the accumulated Assemblys don't appear either. 
On the other hand, when I go to the Staking option, it does not allow me to do the new phase of staking the Iotas for Assemblys.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Access to Firefly
2. "Something went wrong" alert
3. No portfolio information, only IOTAS and Shimmer appear, but no information on transactions or portfolio activity.

### Operating System

Windows

### Diagnostics

```shell
Versión 1.6.4
Idioma: es-ES
Divisa: USD
Selección de nodo: Automática
Plataforma: win32
Versión de la plataforma: 10.0.19044
Arquitectura de la plataforma: x64
Número de CPU: 8
Memoria Total: 15761.4 MB
Memoria Libre: 9078.2 MB
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Previously staked

### Crash Status

None of the above

### Error Messages

"Something went wrong"

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Have you connected your ledger device? Please connect your ledger device and run the balance finder in the settings. I´m going to close this issue as it is a duplicate to https://github.com/iotaledger/firefly/issues/4016. Feel free to continue there if you have further problems.

**Comment by JaviCrypto** [comment]
Hi Mike, 
Thanks for your response
Sorry I didn't explain correctly, I don't have the wallet in a ledger, I have it directly in the web version of Firefly.

Could it be a problem with the node?

Regards

**Comment by MiKeF05** [comment]
Have you already tried to change the node? It seems that Firefly can't connect to a node. Do you have a special firewall or a VPN or something like that?

**Comment by JaviCrypto** [comment]
Yes I have switched to manual node and put the node https://iotanode.eu:444, but it doesn´t work either.
And I am not connected to any VPN or special firewall.

**Comment by MiKeF05** [comment]
Can you try to change the node and restart Firefly? Do you use a home WIFI or a public one like a hotel?

**Comment by JaviCrypto** [comment]
I just tried changing nodes and restarted Firefly, but it still doesn't work.
The curious thing is that if I try to see the node information I get an error message and it won't let me see it.

I'm with the WIfi at home

**Comment by MiKeF05** [comment]
Can you open the error log of Firefly? You find it in the upper left menu

**Comment by JaviCrypto** [comment]
yes, but the message that appears is "The error log is empty".

Although every time I log into Firefly, I get the message "Something went wrong".

**Comment by MiKeF05** [comment]
Can you try to open the address `https://chrysalis-nodes.iota.org/api/v1/info` in your browser? This is a info endpoint of the node. Let´s see if you can connect to the node.

**Comment by JaviCrypto** [comment]
I can see the node info, in the bowser, And I can select the node as priority node, but it seems that doesn´t work, and if I try to see the node info in Firefly I get the error message

**Comment by MiKeF05** [comment]
Okay. Then let´s try to recover your profile. Do you have a stronghold backup? Try to create a new profile and use the option "migrate or restore wallet". In this process you can restore your wallet.

**Comment by JaviCrypto** [comment]
OK, I don´t have a stronghold backup, but I will try to restore the wallet

**Comment by MiKeF05** [comment]
Ok. The advantage of the stronghold backup is that your whole transaction history will be restored. With the 24 words only the transactions which have not yet been pruned by the node can be restored.

**Comment by JaviCrypto** [comment]
Understood, 
I have just restored the wallet, and the Assemblies now appear in my assets. But I still don't see the staking option.

**Comment by JaviCrypto** [comment]
The message on Staking option is "No staking events detected"

**Comment by MiKeF05** [comment]
Then maybe the node doesn´t support it. Can you try to use an official iota node by choosing manual?

**Comment by JaviCrypto** [comment]
yes I am using the official node https://chrysalis-nodes.iota.org, (selecting manually) but the staking doesn´t work

**Comment by MiKeF05** [comment]
With the tanglebay node it is the same? Then something blocks the requests on your side.

**Comment by JaviCrypto** [comment]
I just tried again with the node https://iotanode.eu:444 and it works!! I can start the new staking!

Thanks a lot for your help
