### ISSUE TITLE
[Bug report]: SMR and ASMB amounts are wrong

### ISSUE THREAD

**Issue by kaosoul** [iotaledger/firefly#4068]
### Platform

Desktop

### Version

1.6.4

### Description

The SMR and ASMB amounts are wrong in firefly with ledger nano and also in a single wallet

The ASMB amount posted on 28 July 2022 is much lower than the ASMB amount posted on 17 May 2022. However, I have staked out the asmb. Logically I should have more.

The SMR amount displayed on 28 July 2022 is 1,000,000 times lower than the one displayed on 17 May 2022.

### Expected behaviour

I would like to see correct amounts displayed

### Actual behaviour

The SMR and ASMB amounts are wrong in firefly with ledger nano and also in a single wallet

### Can the issue reliably be reproduced?

Yes

### Operating System

Linux

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Actively staking

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
The unit of Shimmer has been changed. But you have the same amount of tokens like before. See also https://twitter.com/fireflywallet/status/1552319343412842496?t=4Ff-VDehCih8NsJdwtm_jw&s=19

And for the ASMB token you can try to run the balance finder in the settings. But there will be a v1.6.5 which should fix this. I'm going to close this issue as it is a duplicate to https://github.com/iotaledger/firefly/issues/4016
