### ISSUE TITLE
[Bug report]: I can't see the Assemblys and Firefly doesn't allow me to staking.

### ISSUE THREAD

**Issue by JaviCrypto** [iotaledger/firefly#4070]
### Platform

Desktop

### Version

1.6.4

### Description

In my Firefly wallet, I don't see the accumulated Assemblies and it is not allowing me to start the third phase of IOTA staking per Assembly either.

### Expected behaviour

In the portfolio I should be able to see my IOTAS as well as the Shimmer and Assemblys.

It should also be possible to start the new phase of staking of IOTAs per Assemblys.

### Actual behaviour

When I log in to Firefly, I get an alert, which says "Something went wrong", but it doesn't let me log in, it doesn't look like my usual wallet information and the accumulated Assemblys don't appear either.
On the other hand, when I go to the Staking option, it does not allow me to do the new phase of staking the Iotas for Assemblys.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Access to Firefly
"Something went wrong" alert
No portfolio information, only IOTAS and Shimmer appear, but no information on transactions or portfolio activity.

### Operating System

Windows

### Diagnostics

```shell
Versión 1.6.4
Idioma: es-ES
Divisa: USD
Selección de nodo: Automática
Plataforma: win32
Versión de la plataforma: 10.0.19044
Arquitectura de la plataforma: x64
Número de CPU: 8
Memoria Total: 15761.4 MB
Memoria Libre: 9078.2 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Error Messages

"Something went wrong"

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
This was solved with https://github.com/iotaledger/firefly/issues/4053
