### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by AXMAS64** [iotaledger/firefly#4079]
### Platform

Desktop

### Version

1.6.4

### Description

My Shimmer token balance is wrong after last update on Firefly platform.
I have gone from having five thousand seven hundred ninety-six million, forty-nine thousand six hundred eighty-two Shimmer tokens 5.796.049.682 To having or as I interpret it: Five thousand seven hundred ninety-six Shimmer Tokens with forty-nine thousand six hundred eighty-two hundred thousandths 5.796,049682
5.796.049.682 = 5.796,049682 ????
I upload the documents that I have in my possession!
Thanks for your help and greetings
![Capture pantallazo de monedas](https://user-images.githubusercontent.com/110170288/181529727-75c2a596-c0e9-45b1-ac4f-4597a19d2118.PNG)
![Fondos iota actuales](https://user-images.githubusercontent.com/110170288/181532727-cfb77440-b02d-4861-9f79-ce6c96ab8e70.PNG)
![Fondos iota actuales 2](https://user-images.githubusercontent.com/110170288/181533249-c2cc00aa-28dc-4b44-9b3f-41a3060a1e7f.PNG)
.

### Expected behaviour

I would like it to be well differentiated between the tokens that are integers and the decimal part so that there are no errors. Ex:
5,796,049,682 = 5,796.049682 ???

### Actual behaviour

5,796,049,682 = 5,796.049682 ???

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1 Analyze my Shimmer backgrounds in the previous version
2 Check my Shimmer backgrounds after the update.
3 Check how many Iotas I had in staking 10,013 GI
4 Check how many Shimmer I received from staking
5 Compare all the data to see if they match

### Operating System

Windows

### Diagnostics

```shell
Versión 1.6.4
Idioma: es-ES
Divisa: EUR
Selección de nodo: Automática
Plataforma: win32
Versión de la plataforma: 10.0.19044
Arquitectura de la plataforma: x64
Número de CPU: 4
Memoria Total: 8127.5 MB
Memoria Libre: 3035.5 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
The unit of Shimmer has been changed. But you have the same amount of tokens like before. See also https://twitter.com/fireflywallet/status/1552319343412842496?t=4Ff-VDehCih8NsJdwtm_jw&s=19
