### ISSUE TITLE
[Task]: Finish status bar mobile issues - Android

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#4082]
Android:
The status bar overlay mode has not safe-are reserved value. We need to fix safe-area from java code. Seems there is an issue with Chromium not fixed yet: https://bugs.chromium.org/p/chromium/issues/detail?id=1094366
Try with RootWindowInsets:
https://developer.android.com/reference/android/view/View#getRootWindowInsets()

Also try with DisplayCutout:
https://developer.android.com/reference/android/view/WindowInsets#getDisplayCutout()

Investigate a way to expand background to Navigation bar at bottom (where is the back arrow, circle and square icons / swipe mark)
https://developer.android.com/reference/android/view/View#setFitsSystemWindows(boolean)

**Comment by cvarley100** [comment]
Status Bar is generally now good enough. Splash screen white artifacts need fixing however.
