### ISSUE TITLE
[Bug report]: Unable to claim a token

### ISSUE THREAD

**Issue by mbarrueto** [iotaledger/firefly#4084]
### Platform

Desktop

### Version

Stardust Beta 2.0.3

### Description

Unable to claim a token. Wallet does not allow me to claim this token as received, even after multiple attempts (click on claim button)
![image](https://user-images.githubusercontent.com/24359082/181602477-bff4b143-f2b8-4356-8566-2faba6f6cc18.png)

### Expected behaviour

Should process same way as other tokens claimed

### Actual behaviour

Unable to claim a token. Wallet does not allow me to claim this token as received, even after multiple attempts (click on claim button)

### Can the issue reliably be reproduced?

No

### Operating System

Windows

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Basha0** [comment]
Yeah happened to me after closing and reopening FF. Seems like the state is not being saved?

**Comment by MarkNerdi** [comment]
Resolved with:
https://github.com/iotaledger/firefly/pull/4106
