### ISSUE TITLE
[Bug report]: Sending x GLOW units of SMR resets it back to SMR

### ISSUE THREAD

**Issue by JannemanDev** [iotaledger/firefly#4086]
### Platform

Desktop

### Version

Firefly Desktop 2.0.0-beta-2.0.3

### Description

For example sending 100 GLOW of SMR, then Firefly turns it into 100 SMR
![image](https://user-images.githubusercontent.com/13236774/181606525-d1ca73a7-d560-4ed6-a796-eee092e2de2e.png)

Press SEND

![image](https://user-images.githubusercontent.com/13236774/181606557-fa583108-73e3-4ffa-8fbc-5a76f0ee4e79.png)

The tx can be found in explorer: https://explorer.shimmer.network/testnet/transaction/0x1598bbe3591aeb43c21d8eebab8b935a2019f9d768d2baa13accbc618f26ebd3

### Expected behaviour

It should sent 100 GLOW units of SMR, which is 0,00001 SMR.

### Actual behaviour

It sends 100 SMR

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

See Description

### Operating System

Windows

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
See also https://github.com/iotaledger/firefly/issues/4102

**Comment by MarkNerdi** [comment]
Resolved with:
https://github.com/iotaledger/firefly/pull/4103
