### ISSUE TITLE
[Bug report]: All buttons in Firefly is totally unresponsive when you mint a token with a lot of decimals

### ISSUE THREAD

**Issue by erlingfjelstad** [iotaledger/firefly#4087]
### Platform

Desktop

### Version

2.0.0-beta3

### Description

Steps to reproduce:
Mint a new token as per screenshot 
<img width="482" alt="Skjermbilde 2022-07-28 kl  20 36 19" src="https://user-images.githubusercontent.com/4091353/181613336-06294b04-90bc-4f4e-acbb-73dfacc63c6a.png">

**Account is non recoverable with seed phrase after this bug**

### Expected behaviour

Firefly should show an error message that it cannot mint a token with so many decimals.
Firefly should also be able to recover the profile

### Actual behaviour

Firefly is totally broken and any buttons (such as those in the side menu) are not clickable
Profile is also not recoverable from seed phrase as Firefly is forever loading.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

See attached screenshot in description

### Operating System

Mac

### Diagnostics

```shell
Diagnostics button is broken and is impossible to get logs
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Crash Status

Non-responsive

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MarkNerdi** [comment]
Tracked in https://github.com/iotaledger/firefly/issues/4104
