### ISSUE TITLE
[Bug report]: Claim button of native tokens reappears after logout/login

### ISSUE THREAD

**Issue by HolgerKoether** [iotaledger/firefly#4097]
### Platform

Desktop

### Version

2.0.3

### Description

already claimed tokens are shown to be claimable 
![2022-07-28 19_28_59-Window](https://user-images.githubusercontent.com/48596312/181722921-307309c7-1f1c-4227-b504-a773326037ef.png)
n

### Expected behaviour

tokens should be shown as claimed

### Actual behaviour

already claimed tokens are shown to be claimable 

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
See also https://github.com/iotaledger/firefly/issues/4098
