### ISSUE TITLE
[Bug report]: [Preload Context] Error when starting firefly 

### ISSUE THREAD

**Issue by corbo** [iotaledger/firefly#4111]
### Platform

Desktop

### Version

1.6.5

### Description

This error appears when loading Firefly:

App Version: 1.6.5

platform: linux
platformVersion: 5.10.131-1-MANJARO
platformArchitecture: x64
cpuCount: 4
totalMem: 3812.3 MB
freeMem: 748.0 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: ENOENT, public/build/index.node not found in /tmp/.mount_fireflKwXpyi/resources/app.asar

### Expected behaviour

Showing user profile selection choices

### Actual behaviour

Above mentioned error

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Start Firefly

### Operating System

Linux

### Diagnostics

```shell
Settings, Diagnostics and Error Log menu choices do not work. "About Firefly firefly" menu option shows a popup with version 1.6.5
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

White screen

### Error Messages

App Version: 1.6.5

platform: linux
platformVersion: 5.10.131-1-MANJARO
platformArchitecture: x64
cpuCount: 4
totalMem: 3812.3 MB
freeMem: 747.7 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: ENOENT, public/build/index.node not found in /tmp/.mount_firefltWIvGU/resources/app.asar

### Error Logs

```shell
men options not responsive
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kraftjs** [comment]
Looks related to #4113, but the operating system and error message are somewhat different. I'm guessing they are affected by the same issue.

**Comment by kraftjs** [comment]
@corbo I know that the version says 1.6.5, but did you receive this error while using the Firefly Stardust - Beta version and it just reported the version inaccurately, or was this while using the production 1.6.5 Firefly?

**Comment by corbo** [comment]
@kraftjs It is the production version, 1.6.5 updatet via the update menu option from production version 1.6.4

**Comment by corbo** [comment]
Updating from production version 1.6.4 to 1.7.0 just now fortunately resulted in a working current version.
