### ISSUE TITLE
[Bug report]: No reaction after PIN 

### ISSUE THREAD

**Issue by DanEvers** [iotaledger/firefly#4112]
### Platform

Desktop

### Version

firefly-desktop-2.0.0-beta-2.0.3

### Description

Hi there, 
in Firefly Stardust Beta after PIN entry for the wallet nothing happens. Wallet is unusable. 

### Expected behaviour

PIN entry then main wallet dashboard

### Actual behaviour

Nothing happens after PIN entry. 

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

reenter PIN, uninstall and reinstall wallet, but issue persisist. 

### Operating System

Mac

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Firefly12335** [comment]
Habe genau das gleiche Problem ....Neu Installation 1 Anmeldung funktioniert dann keine Reaktion bei der PIN eingabe.
