### ISSUE TITLE
[Bug report]: Firefly Stardust - Beta crashes on startup

### ISSUE THREAD

**Issue by Raivr-dev** [iotaledger/firefly#4113]
### Platform

Desktop

### Version

2.0.0-beta-2.0.3

### Description

Starting _Firefly Stardust - Beta_ crashes immediately, mentioning it can't find a file, which actually does exist when I look in the Local\Temp folder. The "aa4dbe24-d87a-42c9-b47a-b0e26c8dbca5.tmp.node" file contains 18,606,592 bytes.

App Version: 2.0.0-beta-2.0.3

platform: win32
platformVersion: 6.1.7601
platformArchitecture: x64
cpuCount: 8
totalMem: 16366.0 MB
freeMem: 2492.8 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: The specified module could not be found.
C:\Users\MyName\AppData\Local\Temp\aa4dbe24-d87a-42c9-b47a-b0e26c8dbca5.tmp.node

### Expected behaviour

To start and run fine.

### Actual behaviour

It crashes.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Start Firefly Stardust - Beta. It does not matter whether it is installed for all users or just for me. Both installs crash.

### Operating System

Windows

### Diagnostics

```shell
App Version: 2.0.0-beta-2.0.3

platform: win32
platformVersion: 6.1.7601
platformArchitecture: x64
cpuCount: 8
totalMem: 16366.0 MB
freeMem: 2492.8 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: The specified module could not be found.
C:\Users\MyName\AppData\Local\Temp\aa4dbe24-d87a-42c9-b47a-b0e26c8dbca5.tmp.node
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

White screen

### Error Messages

App Version: 2.0.0-beta-2.0.3

platform: win32
platformVersion: 6.1.7601
platformArchitecture: x64
cpuCount: 8
totalMem: 16366.0 MB
freeMem: 2492.8 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: The specified module could not be found.
C:\Users\MyName\AppData\Local\Temp\aa4dbe24-d87a-42c9-b47a-b0e26c8dbca5.tmp.node

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kraftjs** [comment]
![image](https://user-images.githubusercontent.com/72045705/182525748-dd143b5f-e359-4e57-b5ca-85801217fb8d.png)
![image](https://user-images.githubusercontent.com/72045705/182526066-338021ff-b873-4e65-9d8a-9f6cfca12f79.png)
![image](https://user-images.githubusercontent.com/72045705/182526394-4696aeb1-ca81-481f-95b7-10138f9254c3.png)
![image](https://user-images.githubusercontent.com/72045705/182525979-d10bfbe5-1a81-4285-af5c-e24f36614dd0.png)
![image](https://user-images.githubusercontent.com/72045705/182525898-1b9941f0-e3e1-41b4-9079-545a511b13c3.png)

**Comment by kraftjs** [comment]
Also the error from Linux has the same `Error: node-loader`, but this one is from 1.6.5 FF.
![image](https://user-images.githubusercontent.com/72045705/182526698-07a9da34-69ef-4137-b19e-99167d19718a.png)
Worth checking what has changed there too

**Comment by kraftjs** [comment]
From what I've seen in other related issues, I thought it might be related to missing local dependencies so I created a fresh Windows profile and installed the Firefly Beta. Didn't have any issues, so that's not it.

**Comment by kraftjs** [comment]
Extra info.
When moving to the %TEMP% directory and running `node [hash].tmp.node` on the specified file that could not be found from the error message, t00k gets the following error:

```
C:\Users\t00k\AppData\Local\Temp>node 31fa5aef-d377-4a8b-9522-58b94eaa6a6e.tmp.node
node:internal/modules/cjs/loader:1189
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\t00k\AppData\Local\Temp\31fa5aef-d377-4a8b-9522-58b94eaa6a6e.tmp.node
←[90m    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:981:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m {
  code: ←[32m'ERR_DLOPEN_FAILED'←[39m
}

C:\Users\t00k\AppData\Local\Temp>
```

This error that is being caught by the `node-loader` package then throws `Error: node-loader:` via the following code:
```javascript
  return `
try {
  process.dlopen(module, __dirname + "/" + __webpack_public_path__ + ${JSON.stringify(name)}${typeof options.flags !== 'undefined' ? `, ${JSON.stringify(options.flags)}` : ''});
} catch (error) {
  throw new Error('node-loader:\\n' + error);
}
`;
```

**Comment by kraftjs** [comment]
Changed to blocked, awaiting next beta release to see if pull #4091 fixes this issue

**Comment by Tuditi** [comment]
Rust native modules apparently require Windows Visual C++ packages. We need to check if the latest version is present on the user's machine and download it if not.

More information about a script can be found here: https://github.com/electron-userland/electron-builder/issues/4679

**Comment by Tuditi** [comment]
Task has been created for this bug: https://github.com/iotaledger/firefly/issues/4250. I'll close this for now.
