### ISSUE TITLE
[Task]: Improve loading screen ux

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#4122]
### Task description

Add information or progress bar to the loading screen when logging in or restoring.

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by MarkNerdi** [comment]
Closed with https://github.com/iotaledger/firefly/pull/4242/
