### ISSUE TITLE
[Task]:Staking doest work

### ISSUE THREAD

**Issue by 123Roland** [iotaledger/firefly#4132]
### Task description

Cant participate with the newest Staking even when i installed the latest software 

### Requirements

Cant participate with the newest Staking even when i installed the latest software 

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by MiKeF05** [comment]
Duplicate to https://github.com/iotaledger/firefly/issues/4133
