### ISSUE TITLE
the Staking doest show up 

### ISSUE THREAD

**Issue by 123Roland** [iotaledger/firefly#4133]
### Platform

Desktop

### Version

1.6.5

### Description

Cant participate with the newest Staking even when i installed the latest software 

### Expected behaviour

none 

### Actual behaviour

none

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Diagnostics

```shell
none
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Error Messages

none

### Error Logs

```shell
none
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by klaviculos** [comment]
I also have this error. I have the latest version (1.6.5), and I have the ledger (and iota app) up to date, but, when I press the stake button, apparently, nothing happens.

**Comment by MiKeF05** [comment]
You can try to change the node in the settings. Change the node, logout and login.

**Comment by hadze** [comment]
I encountered the same issues after updating firefly to 1.6.5 and the initial start of the app. After logout and restarting firefly the staking worked
