### ISSUE TITLE
[Task]: Disable auto backup on both platforms

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#4147]
From a security standpoint, uploading user data to an external services is always worse than just leaving it local. If we deal with very sensitive data, we shouldn't upload it.
We need to disable auto-backup on Android and iOS.

refs:
- https://developer.android.com/guide/topics/data/backup
```java
android:allowBackup="true"
android:fullBackupContent="true"
```
- https://developer.apple.com/documentation/foundation/optimizing_your_app_s_data_for_icloud_backup

**Comment by jeeanribeiro** [comment]
Maybe it should be disabled as well:

> Device-to-device (D2D) transfers: User data is sent directly to the user's new device from their older device, such as by using a cable.
