### ISSUE TITLE
[Task]: Fix migration sometimes leads to corrupted profiles

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#4188]
### Task description

After doing migration in mobile, sometimes the profiles get corrupted and you cant use firefly anymore unless I wipe all profiles and firefly data and do a fresh start, like a new installation. 
There are couple of issues we should fix before that could be affecting this behavior:
- #3802
- #2473
- #4184
When those are fixed, we should revisit this issue and see if it still happens. 

### Requirements

Migration doesnt corrupt the app

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
Blocked by 
- #3802
- #2473
- #4184

**Comment by begonaalvarezd** [comment]
Cant repro this issue anymore, moving to backlog just in case

**Comment by cvarley100** [comment]
Closing for now. We can reopen if it occurs again.
