### ISSUE TITLE
[Task]: Fix tx pane doesnt cant be shrinked & last tx cut

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#4207]
### Task description

If I have a lot of txs so I need to scroll in the tx history, the last tx is cut for me and I cannot make the pane smaller, like the original size

![image](https://user-images.githubusercontent.com/3624944/184143729-71f41ed2-0185-4e85-bfe9-084cb124dfc3.png)

smaller (I have to go to tokens, reduce it, and then back to activity)

![image](https://user-images.githubusercontent.com/3624944/184143888-00b1b67e-8106-4e1b-b765-43cd9f232653.png)

### Requirements

TVD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by paul-boegelsack** [comment]
I created a separate task for the shrinking issue: https://github.com/iotaledger/firefly/issues/4483
