### ISSUE TITLE
[Bug report]: Fiat rates from the API are wrong

### ISSUE THREAD

**Issue by MiKeF05** [iotaledger/firefly#4216]
### Platform

Desktop

### Version

1.6.5

### Description

The calculation of each fiat value is correctly implemented in Firefly. However there is a big difference for some fiat values compared to exchanges.

I have checked the IOTA market API and there seems to be a big difference in the fiat rates. In the example below all rates received from the IOTA market API are listed. The fiat rate EUR for example is at 0.8528784648 to the base USD but it should be more like 0.97 at the time of the request.

"rates":{"CAD":1.2607249467,"HKD":7.7742430704,"ISK":126.3113006397,"PHP":48.5296375267,"DKK":6.3431130064,"HUF":309.8251599147,"CZK":22.2968017058,"GBP":0.7267292111,"RON":4.1981236674,"SEK":8.7320255864,"IDR":14524.9978678038,"INR":73.1880597015,"BRL":5.7491684435,"RUB":75.3240938166,"HRK":6.4567164179,"JPY":110.7974413646,"THB":31.2648187633,"CHF":0.9441364606,"EUR":0.8528784648,"MYR":4.1465245203,"BGN":1.6680597015,"TRY":8.2942430704,"CNY":6.551130064,"NOK":8.5249466951,"NZD":1.4301918977,"ZAR":14.7960767591,"USD":1,"MXN":20.512238806,"SGD":1.3448187633,"AUD":1.31445629,"ILS":3.3414072495,"KRW":1129.3731343284,"PLN":3.9665671642}}

### Expected behaviour

Fiat rates should be correctly fetched.

### Actual behaviour

For some fiat rates there is a big difference.

### Can the issue reliably be reproduced?

No

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
new version will be released soon with improved fiat
