### ISSUE TITLE
[Bug report]: Infinite loading after PIN entry

### ISSUE THREAD

**Issue by NordishByNature82** [iotaledger/firefly#4238]
### Platform

Desktop

### Version

2.0.0-beta-1.0.1

### Description

The application gets stuck in an infinite loading loop showing nothing but the animated firefly-loading indicator after entering the correct PIN number. The error log is not reachable during this application state and shows "empty" after a restart.

### Expected behaviour

The application is expected to load the UI.

### Actual behaviour

Gets stuck in infinite loading loop.
<img width="1392" alt="Bildschirmfoto 2022-08-16 um 19 20 45" src="https://user-images.githubusercontent.com/82079463/184940524-bbc6ddf4-a454-452a-85ba-bcd7351c2aba.png">

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Create new profile. Try to start application by entering correct PIN.

### Operating System

Mac

### Diagnostics

```shell
Version 
Language: en
Platform: macOS
Platform Version: 12.1
Platform Architecture: x64
CPU Count: 8
Total Memory: 8192.0 MB
Free Memory: 864.5 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Crash Status

Infinite loading symbol

### Error Messages

None

### Error Logs

```shell
None
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicole-obrien** [comment]
Please use the latest beta release, there was a breaking change on the node api that was release tuesday so you will not be able to use older versions. You should also create a new profile now as that one will be corrupt.
