### ISSUE TITLE
Allow user to skip recovery phrase backup and entry to dashboard, but force backup before generating an address

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#427]
## Description

The finalising of profile creation should only be possible if: 1.) pw and pin created and 2.) 24 words have been noted and checked by the software that they are remembered correctly and 3.) backup of the stronghold has been downloaded
- only then profile creation should process and open firefly
-
## Motivation
security

without backup of the file users may loose access to funds

## Requirements

check routine that all 3 conditions are fullfilled

## Open questions (optional)

Use this section to ask any questions that are related to the feature.

## Are you planning to do it yourself in a pull request?

no

**Comment by cvarley100** [comment]
Definitely more important on mobile, but we will consider it.
