### ISSUE TITLE
[Task]: Fix popup couldnt be closed

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#4275]
### Task description

Reported by `bartholomaeus#3186` (iOS): https://discord.com/channels/397872799483428865/996835547484004454/1010478498181296178
> Actually it popped up at first when I confimed my password for the sh export. Thought smth went wrong so I hit three times in total and ended up with 3 backup files
Then also when trying to delete my profile it popped up again.

![image](https://user-images.githubusercontent.com/3624944/185739143-d04d76b0-ad34-4dcb-9376-0193279dc7ba.png)

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
> When trying to cancel the export process I get stuck at the dialogue window forever with this message:
![image](https://user-images.githubusercontent.com/3624944/185739509-ff93df1a-d0a6-4ce7-9229-a55553c15923.png)

**Comment by JannemanDev** [comment]
Just updated the Firefly app using TestFlight on iOS.
Reading above comments I can confirm this bug and reproduce it using these steps:
-goto profile > backup your wallets > A Last backup dialog is shown > Export >Press cancel when password required dialog is shown
A popup message at the top is shown: This popup is unable to be closed

When you retry the steps above you immediately get the same popup message and you wont see both the Last backup and  password required dialogs with password entry.

You have to quit the app to see the dialogs again.
