### ISSUE TITLE
[Bug report]: Firefly doesnt start

### ISSUE THREAD

**Issue by AFB-LDSM** [iotaledger/firefly#4278]
### Platform

Desktop

### Version

2.0.0

### Description

Hi guys,

I have updated to the latest version 2.0.0. However, when startin the app, the app gets stuck after typing in the 6 digit password. This has happened with the last version as well.

Keep up the work

### Expected behaviour

The app should open after typing the 6 digit password

### Actual behaviour

the app gets stuck
![firefly_stardust_stuck](https://user-images.githubusercontent.com/31903395/185787748-cacd09b9-886a-44e0-9036-9db82e7e893f.png)

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Crash Status

Infinite loading symbol

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicole-obrien** [comment]
Please can you check in the console log, you can open this by clicking on the three line menu and opening the dev tools

**Comment by AFB-LDSM** [comment]
Here is a snapshot of the error message


[image: image.png]

Am Mo., 22. Aug. 2022 um 09:59 Uhr schrieb nicole-obrien <
***@***.***>:

**Comment by AFB-LDSM** [comment]
this might also be relevant
[image: image.png]

Am Mo., 22. Aug. 2022 um 10:05 Uhr schrieb Alexander Brause <
***@***.***>:

**Comment by AFB-LDSM** [comment]
here is a new error:

[image: image.png]

Am Mo., 22. Aug. 2022 um 10:07 Uhr schrieb Alexander Brause <
***@***.***>:

**Comment by nakkimusic** [comment]
I also have the same error, it doesn't start after the pin, and if it starts I can't do anything else, the links are stopped, etc....My system is linux.

**Comment by nicole-obrien** [comment]
Should all be fixed with latest error handling during login
