### ISSUE TITLE
[Task]: Mobile Polishing

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/firefly#4313]
### Task description

List of mobile polishing tasks. Assign yourself by adding your name and check off when merged. 

- [x] #4312 (@paul-boegelsack)
- [x] #4371 (@jeeanribeiro)
- [x] #4321 (@cvarley100)
- [x] #4316 (@jeeanribeiro)
- [x] #4327  (@jeeanribeiro)
- [x] #4324 (@jeeanribeiro)
- [x] #4315 (@paul-boegelsack)
- [x] #4361 (@amadeu2)
- [x] #4364 (@amadeu2)
- [x] #4368 (@paul-boegelsack)
- [x] #4351 (@jeeanribeiro)
- [x] #4360 (@jeeanribeiro)
- [x] Verify pin component not filling the full width (@paul-boegelsack)
- [x] #4358 (@jeeanribeiro)
- [x] #4373 (@amadeu2)
- [x] #4353 (@begonaalvarezd )
- [x] #4355 (@begonaalvarezd )
- [x] #4373 (@amadeu2 )
- [x] #4374 (@jeeanribeiro)
- [x] #4376 (@amadeu2 )
- [x] #4379 (@paul-boegelsack)
- [x] #4386 (@paul-boegelsack)
- [x] #4394 (@paul-boegelsack)
- [x] #4388 (@jeeanribeiro)
- [x] #4389 (@jeeanribeiro)
- [x] #3980 (@jeeanribeiro)
- [x] #4391 (@begonaalvarezd)
- [x] #4393 (@paul-boegelsack)
- [x] #4405 (@amadeu2)

**Comment by amadeu2** [comment]
new discoverings
- remove horiz scroll on settings android, viewed at transition btw sub menus

- change password settings:
 + hide title as with change pin for smaller screens. 
 + export stronghpold check is not working
 + when passwords does not match the form is sent the same, and force logout without leave finish process

- password popup auto seelect? on export backup it is and could be nice to implement everywhere with password popup?
- checke scroll on transaction view, add scroll padding bottom

- when ams tokens lodas, we should use the spinning loader on both places, not only on transactions, the user needs an indicator that the app is working before the asm/smr tokens are showed
- notification flood on tanglebay node, remove it just for this release?

- remove continue buttons on onboarding autofoucs? or remove autofocus?
- remove autofocus enter seed onboarding?
- verify pin componet pin and repeat pin opnboarding seems an old one?, on big scren is not filling full with
- recovery phrase onboarding, add padding to top content, too closer to top title
- icon ios installed on black mode remains as light with black background
