### ISSUE TITLE
[Bug report]: firefly wallet access problem 

### ISSUE THREAD

**Issue by engnpkr** [iotaledger/firefly#4350]
### Platform

Desktop

### Version

1.6.5

### Description

I can not access to firefly wallet although I am sure that my pin is correct 100%. It is up to date.

### Expected behaviour

I want to access my wallet

### Actual behaviour

1 incorrect attempt then next time
2 incorrect attempts

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

incorrect attemp
2 incorrect attempts
3 incorrect attempts
wait 30 seconds

### Operating System

Windows

### Diagnostics

```shell
Sürüm 1.6.5
Dil: tr
Para Birimi: USD
Düğüm Seçimi: Otomatik
Platform: win32
Platform Sürümü: 10.0.19044
Platform Mimarisi: x64
CPU Sayısı: 8
Toplam Hafıza: 16245.5 MB
Boş Hafıza: 7561.3 MB
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Actively staking

### Crash Status

None of the above

### Error Messages

incorrect attemp
2 incorrect attempts
3 incorrect attempts
wait 30 seconds

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvarley100** [comment]
On rare occasion Firefly Desktop loses the link with the OS keychain. What you can do in this scenario is create a new profile with your recovery phrase/Stronghold. If you want to remove the old profile you will first need to delete your Firefly folder (`AppData\Roaming\Firefly`).

This will stop happening with a future version of Firefly when we change how pin unlock works.
