### ISSUE TITLE
[Bug report]: "Wallet Activity" chart is not accurate

### ISSUE THREAD

**Issue by cbries** [iotaledger/firefly#4369]
### Platform

Desktop

### Version

1.6.5

### Description

The wallet activity of the year is not totally provided in the Firefly' chart:
![image](https://user-images.githubusercontent.com/5418062/187396305-7a5e4cbc-6af5-4d38-96ff-c42245e8d788.png)

For example the income of 1.5 Gi is no shown.

### Expected behaviour

A full list of all income/outcome of MIOTAs.

### Actual behaviour

Missing bar chart for June, see previous screenshot.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

I just have to open my Firefly wallet.

### Operating System

Windows

### Diagnostics

```shell
Version 1.6.5
Sprache: de
Währung: USD
Node-Auswahl: Automatisch
Plattform: win32
Plattformversion: 10.0.19043
Plattform-Architektur: x64
CPU-Anzahl: 12
Gesamtspeicher: 15985.9 MB
Freier Speicher: 2725.4 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

None of the above

### Error Messages

Wed, 02 Mar 2022 11:45:29 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Fri, 25 Feb 2022 04:47:20 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Thu, 17 Feb 2022 06:51:59 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Thu, 17 Feb 2022 06:51:49 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Thu, 17 Feb 2022 06:51:19 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Thu, 10 Feb 2022 11:35:50 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Thu, 10 Feb 2022 11:33:59 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Thu, 10 Feb 2022 11:33:50 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Thu, 10 Feb 2022 11:33:39 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Thu, 10 Feb 2022 11:32:43 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Thu, 10 Feb 2022 11:32:30 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Thu, 10 Feb 2022 11:30:59 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Thu, 10 Feb 2022 11:30:39 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Thu, 10 Feb 2022 11:30:20 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Thu, 10 Feb 2022 11:30:09 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Thu, 10 Feb 2022 11:29:39 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Thu, 10 Feb 2022 11:29:09 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Tue, 08 Feb 2022 05:33:32 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Mon, 24 Jan 2022 09:49:42 GMT
ClientError: `Response error with status code 404: {"error":{"code":"404","message":"Not Found, error: event not found: 57607d9f8cefc366c3ead71f5b1d76cef1b36a07eb775158c541107951d4aecb: code=404, message=Not Found"}}
`

Sat, 22 Jan 2022 14:58:53 GMT
ClientError: `Response error with status code 404: {"error":{"code":"404","message":"Not Found, error: event not found: 57607d9f8cefc366c3ead71f5b1d76cef1b36a07eb775158c541107951d4aecb: code=404, message=Not Found"}}
`

Tue, 11 Jan 2022 11:15:16 GMT
ClientError: `Response error with status code 404: 404 page not found
`

Wed, 29 Dec 2021 14:29:58 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Wed, 29 Dec 2021 14:29:53 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Fri, 10 Dec 2021 06:37:44 GMT
ClientError: {}

Tue, 07 Dec 2021 12:22:07 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Tue, 07 Dec 2021 12:22:06 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Tue, 07 Dec 2021 09:40:18 GMT
ClientError: {}

Sat, 04 Dec 2021 14:26:16 GMT
StrongholdError: `failed to perform action: `Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.``

Mon, 11 Oct 2021 09:52:07 GMT
ClientError: {}

Mon, 06 Sep 2021 09:14:24 GMT
ClientError: {}

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvarley100** [comment]
The charts are not always accurate and will be removed in the upcoming Firefly Stardust version. We will revisit them in the future.
