### ISSUE TITLE
[Task]: Fix switch to private network crash

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#4375]
### Task description

It was reported in discord that swith to private network crashes the app

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jeeanribeiro** [comment]
Do we have more information about this bug?

**Comment by begonaalvarezd** [comment]
It was reported in discord that trying to switch to a private network caused crash, but I just tested it and it works for me, It took a bit for firefly to process the action but it switched well

**Comment by begonaalvarezd** [comment]
Tested on Android, perhaps worth testing on iOS. If works, i would close the issue

**Comment by amadeu2** [comment]
Tested on iOS is not happening to me
