### ISSUE TITLE
[Task]: Add native token minting support for Ledger profiles

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#4384]
### Task description

We need to add / adjust logic to support native token minting for Ledger profiles.

### Requirements

_TBD_

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
Blocked, since the latest wallet.rs update broke the minting support.
