### ISSUE TITLE
[Task]: No Ed25519 address matched the input address

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#4413]
### Task description

Using ledger we sometimes encounter the `no ed25519  matched the input address` error upon sending a transaction. This error should be investigated further.

### Requirements

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by MarkNerdi** [comment]
https://github.com/iotaledger/wallet.rs/issues/1404

**Comment by MarkNerdi** [comment]
fixed with:
https://github.com/iotaledger/wallet.rs/pull/1406
