### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by cam33000** [iotaledger/firefly#4440]
### Platform

Desktop

### Version

1.6.5

### Description

Hello I noticed that when stacking the shimmer between April and June, my firefly account stacked asmb or instead of shimmer.
It's the 3rd time I stacked asmb and I stacked shimmer only 1 time. This is when we could stack smr and asmb together. 
Is it possible to correct this? 
What happened? 

Thanks

### Expected behaviour

I hope to get the amount I should have gotten in smr

### Actual behaviour

J'ai quasiment pas de smr car je n'ai pas beaucoup stcker lors du tout premier jalonnement. Et le deuxieme jalonnement ma fournit du asmb et non du smr

### Can the issue reliably be reproduced?

No

### Steps to reproduce the issue

i think this is not my mistake

### Operating System

Windows

### Diagnostics

```shell
no diagnostic popup
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

None of the above

### Error Messages

no error message

### Error Logs

```shell
nothing
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
There was only 1 event to stake your Iota tokens to get shimmer. So everything is correct. You were only able to stake IOTA for assembly. And there was also no event to stake shimmer tokens.

**Comment by cam33000** [comment]
Okay so maybe m'y friends made a mistake.
They said to me they have stack smr on april until june.
And twitter on june said smr stacking was finished

**Comment by MiKeF05** [comment]
No problem. It was only possible to stake IOTA tokens to get shimmer and assembly. 

Event 1 -> Rewards SMR and ASMB
Event 2 -> Rewards ASMB
Event 3 -> Rewards ASMB
