### ISSUE TITLE
[Task]: Fix bottom safe area & padding on every drawer

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#4470]
There is needed to verify and fix every drawer on the app checking safe area spaces and padding. 
There is also some drawer with wrong top padding.

**Comment by paul-boegelsack** [comment]
Hey @amadeu2 we had some recent changes to the drawer paddings especially in relation to the confirmation. Is this a screenshot of the current develop branch? I tested with iPhone SE, 8, 11, 12 and 13 and definitely have different paddings than in the image 🤔

**Comment by amadeu2** [comment]
I've checked and I got the same as you, so I've removed the pic. There is only the top margins at asm and smr token drawers
