### ISSUE TITLE
[Bug report]: Beta 6 - Ledger profile is broken if Shimmer app is not available right after setup

### ISSUE THREAD

**Issue by antonionardella** [iotaledger/firefly#4509]
### Platform

Desktop

### Version

beta 6

### Description

The profile associated to my Ledger does not open.
After showing the `Checking node health` screen it goes back to show the list of profiles

### Expected behaviour

Open the Profile 

### Actual behaviour

I inset the PIN, after showing the `Checking node health` screen it goes back to show the list of profiles
The error: `Something went wrong.` is shown

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

**Option 1**

1. Set up a new profile
2. Select `Shimmer`
3. Select `Testnet`
4. Select `Restore Shimmer profile`
5. Select `Use Ledger device`
6. Set profile name
7. Set PIN
8. Confirm `Yes, I've installed these apps`
9. Open the Shimmer app on the Ledger Nano and click continue
![image](https://user-images.githubusercontent.com/7383572/189360785-5ed9cd7f-5fca-427e-8971-7c70e9e38cc1.png)
10. After clicking `Continue`, **close** the Shimmer app on the Ledger
11. Click on `Finish setup`
![image](https://user-images.githubusercontent.com/7383572/189361098-c9dfbff5-6a06-4ea2-920b-56803283d9ee.png)
12. `Checking node health` and `Generating accounts` is shown, right after that Firefly goes back to the profile screen.
13. Error message `Something went wrong.` is shown
14. When you click on the profile `Something went wrong.` is shown
No further action is possible with that profile

### Operating System

Linux

### Diagnostics

```shell
Version 
Language: en
Platform: linux
Platform Version: 5.15.60-1-MANJARO
Platform Architecture: x64
CPU Count: 24
Total Memory: 64231.6 MB
Free Memory: 45295.7 MB
```

### Developer Profile

Yes

### Profile Type

Hardware (Ledger)

### Crash Status

None of the above

### Error Messages

Something went wrong.
![image](https://cdn.discordapp.com/attachments/998627792717627443/1017784834606768128/unknown.png)

### Error Logs

![image](https://user-images.githubusercontent.com/7383572/189358981-758d9dc4-0fa7-4b79-b314-1539a2c1a2f5.png)

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tuditi** [comment]
We added a message that the user should **NOT** close/disconnect their ledger app while creating their new profiles, since we have to interact with the ledger device during profile creation.
