### ISSUE TITLE
[Bug report]: Unable to login to Ledger profile after receiving funds

### ISSUE THREAD

**Issue by t00k** [iotaledger/firefly#4513]
### Platform

Desktop

### Version

Stardust 2.0-beta6

### Description

Created a Ledger profile. Sent funds (SMR and T00KEN) from my "normal profile" to this newly created profile. When I logged out and tried logging into the normal profile I got to the first step of login "Initialising profile manager" and got "Something went wrong" in the lower right corner.

Error logs shows the following;
![shimmerledger](https://user-images.githubusercontent.com/49842330/189418792-1d0a757d-8159-4665-b577-96e0c31795a0.PNG)
The last line says "Unable to reach the file since it is being used by another process".

Opening DevTools and console shows the following;
![shimmerledgerdevtools](https://user-images.githubusercontent.com/49842330/189419093-1c5e8519-2766-47e8-99e9-10e807604f5b.PNG)

After restarting Firefly Stardust I was able to login to the Ledger profile, with my funds showing.

### Expected behaviour

I expected to be able to login to the profile.

### Actual behaviour

It stopped at the first step of logging in, threw "Something went wrong" and didnt work until restart of Firefly.

### Can the issue reliably be reproduced?

No

### Steps to reproduce the issue

1. Create a hardware profile.
2. Send funds from normal profile to newly created hw profile.
3. Log out of normal profile and try logging into hw profile.

### Operating System

Windows

### Diagnostics

```shell
Version 
Language: en
Currency: USD
Node list: https://api.testnet.shimmer.network
Platform: win32
Platform Version: 10.0.19044
Platform Architecture: x64
CPU Count: 4
Total Memory: 8060.2 MB
Free Memory: 3565.2 MB
```

### Developer Profile

Yes

### Profile Type

Hardware (Ledger)

### Staking

Never staked

### Crash Status

Non-responsive

### Error Messages

"Something went wrong" in lower right corner.

### Error Logs

```shell
Invalid Date
undefined: Error: internal error in Neon module: error initializing account manager: Storage("IO error: Failed to create lock file: C:\\Users\\t00k\\AppData\\Roaming\\Firefly Stardust - Beta/__storage__/0aff772c92cb56240bf00b0bf28d7cfc/LOCK: Det g�r inte att komma �t filen eftersom den\r\nanv�nds av en annan process.\r\n")

Last line: "Unable to reach the file since it is being used by another process"
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
If you open the Shimmer app on the ledger and login everything works as expected. If you logout and **don´t close** the Shimmer app on the ledger device and want to login a second time without closing the shimmer app the error appears.

**Following steps to repro:**
1. Open Shimmer app before login
2. Login to profile
3. Don´t close Shimmer app
4. Logout of profile
5. Login to the same profile
=> error appears

OR

1. Open Shimmer app after login
2. Don´t close Shimmer app
3. Logout of profile
4. Login to the same profile
=> error appears


**The error doesn´t appear if the following steps are used:**
1. Open Shimmer app before login
2. Login to profile
3. Close Shimmer app
4. Logout of profile
5. Login to the same profile without opening the Shimmer app
6. Logout of profile
7. Login to the same profile with Shimmer app opened
8. Logout of profile
9. Login to the same profile without opening the Shimmer app
10. Logout of profile
11. ...

**Comment by nicole-obrien** [comment]
Can not reproduce @MiKeF05 @t00k can you reproduce on the latest beta?

**Comment by MiKeF05** [comment]
Yes error is still present on the latest beta. I´m using windows 10 @nicole-obrien

**Comment by jeeanribeiro** [comment]
Fixed in newer versions
