### ISSUE TITLE
[Bug report]: Hidden wallet option not saved

### ISSUE THREAD

**Issue by MiKeF05** [iotaledger/firefly#4515]
### Platform

Desktop

### Version

2.0.0-beta-6

### Description

When I hide a wallet and use the "Show hidden wallet" in the options the wallet is shown. But when I log out and log in to the profile I always need to activate the "Show hidden wallet" in the option. It is not saved after log out.

### Expected behaviour

Save the "Show hidden wallet" option

### Actual behaviour

"Show hidden wallet" is not saved with log out.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Hide wallet
2. Select "Show hidden wallet" in the options
3. Log out
4. Log in to the profile
=> Wallet is hidden and the option "Show hidden wallet" need to be activated again

### Operating System

Windows

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
Closing the issue as the current behavior is the intended behavior 🙏🏼

**Comment by nicole-obrien** [comment]
Otherwise there would be no point in hiding the wallets in the first place. I think in the future moving the show hide button to the wallet switcher will improve ux.
