### ISSUE TITLE
[Bug report]: 24 words recovery only restores incoming transactions in the activity history

### ISSUE THREAD

**Issue by MiKeF05** [iotaledger/firefly#4517]
### Platform

Desktop

### Version

2.0.0-beta-6

### Description

I restored a profile with the 24 word phrase. The balance is correct in all wallets. However in the activity history only incoming transactions are listed with unknown address. This occurs on all wallets which are connected to the 24 word phrase. The outgoing transactions were not pruned in the meantime and should appear.

Restoring the profile with the stronghold also shows the outgoing transactions.

### Expected behaviour

Outgoing transactions should appear in the activity history after restoring with 24 word phrase if they are not pruned

### Actual behaviour

Outgoing transactions don´t appear in the activity history after restoring with 24 word phrase

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Send and receive on a wallet
2. Restore with 24 words
=> Only incoming transactions are restored in the activity history with unknown address

### Operating System

Windows

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeeanribeiro** [comment]
This is fixed in newer versions
