### ISSUE TITLE
[Bug report]: Ledger doesn´t generate an address

### ISSUE THREAD

**Issue by MiKeF05** [iotaledger/firefly#4519]
### Platform

Desktop

### Version

2.0.0-beta-6

### Description

I wanted to create a new hardware profile but in the process of creating the profile it stays on Generating Accounts. The ledger also doesn´t generate an address. On the second attempt this worked. But when I try to create a new wallet inside the profile the same issue appears. It stays forever on "Creating wallet".

![image](https://user-images.githubusercontent.com/71659397/189447111-059d2654-2e1b-4e45-8244-213f4b62d956.png)

![image](https://user-images.githubusercontent.com/71659397/189447305-e2c2aa4c-6e6b-4f96-81aa-83b397f1e3b8.png)

### Expected behaviour

The ledger should immediately generate an address and the wallet should be created.

### Actual behaviour

Firefly stays forever in the process of "Creating a wallet".

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Create a hardware profile
2. Create a new wallet inside the profile
=> Firefly stays forever on "Creating a wallet"

### Operating System

Windows

### Developer Profile

Yes

### Profile Type

Hardware (Ledger), Latest firmware version ledger (2.1.0), Shimmer app version 0.8.0

### Crash Status

Infinite loading symbol

### Error Messages

No error messages

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeeanribeiro** [comment]
No other users have reported this bug so probably fixed in the newer versions
