### ISSUE TITLE
[Task]: Multiple Stronghold import does not work on Android

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/firefly#4533]
### Task description

It is only possible to import one Stronghold per app on Android. The first import works fine. If you try to restore a second profile with a Stronghold you will get an "incorrect password" error.

### Requirements

Ensure multiple stronghold imports work.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
Im testing this and it doesnt happen to me in devmode, testing on `develop` branch hash:  `b90df6b78f0e735d0f58604c8322066ae1dc00ed`.
I tried with production v1.0.0 and I can repro, looks like there is a discrepancy between devmode and production, or the fix has already been merged, not sure. Might be worth uploading to the store some alphas or something and test it again
