### ISSUE TITLE
Make address in receive window "click to copy"

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/firefly#457]
## Description

It would be handy if we could "click to copy" the address in the receive window just like in the transaction detail window.

## Motivation

Ease of use and it would align to the users expectation that addresses etc. are "click to copy". 

## Are you planning to do it yourself in a pull request?

No.

<img width="318" alt="Bildschirmfoto 2021-03-13 um 22 08 11" src="https://user-images.githubusercontent.com/17240275/111044612-db338d80-8449-11eb-91a8-873b5042ea81.png">

**Comment by cvarley100** [comment]
We have copy address button so the current solution is fine for now. If we need to use that space for something later we'll readjust to click address to copy.
