### ISSUE TITLE
Wrong position for "Your current PIN is incorrect." alert

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/firefly#458]
## Issue description

When trying to change the PIN with an incorrect current PIN the alert message is placed under the second input field instead of the first one.

## Wallet version

v0.1.0

## System specification

macOS 11.3 Beta

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

1. Go to Settings - Security - Change PIN code
2. Try changing the PIN with an incorrect current PIN

## Expected behaviour

The alert "Your current PIN is incorrect." should appear under the input field for the current PIN.

## Actual behaviour

The alert "Your current PIN is incorrect." appears under the first input field for the new PIN.

## Errors

<img width="434" alt="Bildschirmfoto 2021-03-13 um 22 24 18" src="https://user-images.githubusercontent.com/17240275/111044978-f8695b80-844b-11eb-8a5c-05c3922b8f5f.png">

**Comment by obany** [comment]
This should be fixed in the next release, please re-open if the problem persists.
