### ISSUE TITLE
[Bug report]: Recovery Kit

### ISSUE THREAD

**Issue by jcbm123143** [iotaledger/firefly#4586]
### Platform

Desktop

### Version

1.6.5

### Description

![image](https://user-images.githubusercontent.com/22148449/190887388-39c4b4d5-bbad-4f8e-a2da-548bb1972995.png)

Recovery Kit 
Recovery Phrase do not have data 

### Expected behaviour

The recovery phrase should have something 24 data display 

### Actual behaviour

The 24 recovery phrase no data display 

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1) Go to Recovery Phrase
2) Save Recovery Kit Template 

-  Recovery Phrase do not have data 

### Operating System

Windows

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
This is only a template where you need to manually write down your phrase.
