### ISSUE TITLE
[Bug report]: FAQ - Page Not Found

### ISSUE THREAD

**Issue by jcbm123143** [iotaledger/firefly#4588]
### Platform

Desktop

### Version

1.6.5

### Description

FAQ page not found 
![image](https://user-images.githubusercontent.com/22148449/190888827-dfaf4384-3f31-454e-8ccb-3b8ef8e5ec1a.png)
![image](https://user-images.githubusercontent.com/22148449/190888837-e81a0307-03ff-466a-942a-ed7fa21b0157.png)

### Expected behaviour

There is information or guide in the FAQ

### Actual behaviour

Page Not Found
We could not find what you were looking for.

Please contact the owner of the site that linked you to the original URL and let them know their link is broken.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1 Go to Help
2 Click FAQ

Error Message Show - Page not found

### Operating System

Windows

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Error Messages

Error Message Show - Page not found

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
This issue was already solved with https://github.com/iotaledger/firefly/pull/4562 and will be included in the next version.
