### ISSUE TITLE
"Something went wrong" when creating account, then "account with that name already exists"

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#459]
## Issue description

After creating the first profile i received funds from the Faucet. Triying to create second account, put in account name, put in password. click "create" -  Error "something is wrong" apperars.
Click "create" again - Error "an account under that name already exists"
Go back to account overview - only one account is visible. Triying to create new account again (same name as before) - error again "account under that name already exists)...

Log out and relogging in - Now both created accounts show up.

## Wallet version

0.1.1

## System specification

Platform: win32
Platform Version: 10.0.19041
Platform Architecture: x64
CPU Count: 4
Total Memory: 6082.5 GB
Free Memory: 1471.7 GB
User Path: C:\Users\Amedw\AppData\Roaming\Firefly

## Is it a repeatable issue?

yes

## Expected behaviour

account creation

## Actual behaviour

error - app seems to not update the sates untill logout and relogg in

No errors in error log 

console errors atached

[account2 error console.txt](https://github.com/iotaledger/firefly/files/6135782/account2.error.console.txt)

## Errors

<img width="698" alt="account2 error 2" src="https://user-images.githubusercontent.com/77154511/111052452-d85e8a00-8495-11eb-9070-ed665ff1f57b.png">
<img width="878" alt="account2 error 3" src="https://user-images.githubusercontent.com/77154511/111052454-dac0e400-8495-11eb-8737-5a93c76d7c28.png">
<img width="937" alt="account2 error 4" src="https://user-images.githubusercontent.com/77154511/111052455-dc8aa780-8495-11eb-9f52-f7c93df9fbb8.png">
<img width="788" alt="account2 error" src="https://user-images.githubusercontent.com/77154511/111052457-ddbbd480-8495-11eb-8370-698c19a406b9.png">

**Comment by cvarley100** [comment]
Fixed in 0.3.0.
