### ISSUE TITLE
Firefly permanently in a syncing state

### ISSUE THREAD

**Issue by no8ody** [iotaledger/firefly#463]
## Issue description

After I have entered the PIN for Firefly and go to the overview page, the update (Acc sync) for the latest transaction continues permanently, which then subsequently leads to a freeze of the wallet when entering the settings, for example, and you can only restart it.

## Wallet version

0.1.0

## System specification

Windows 10

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Add a custom node with basic auth
2. Restart firefly
3. Acc sync starts and Wallet freezed

## Expected behaviour

Should not happen...

## Errors

- Currently no error logs

**Comment by cvarley100** [comment]
Fixed in 0.3.0.
