### ISSUE TITLE
[Bug report]: Unlocking profile button does not work on mouse click

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#4640]
### Platform

Desktop

### Version

2.0.0.Beta 7

### Description

Once you are in a profile and you try to perform an action, entering a password is required.
Enter the password and click on the "unlock" button does not unlock the profile (the Button color changes from light blue to a darker blue)
Unlocking the profile by hitting "enter" on the keyboard works>

Tested in a Developer profile

### Expected behaviour

button click unlocks profile

### Actual behaviour

profile stays locked button color changes

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

create profile

perform any action that requires unlocking

enter stronghold password

click "unlock" button

### Operating System

Windows

### Diagnostics

```shell
Version 
Language: en
Platform: win32
Platform Version: 10.0.19044
Platform Architecture: x64
CPU Count: 16
Total Memory: 16236.1 MB
Free Memory: 8083.1 MB
```

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Error Messages

-

### Error Logs

```shell
-
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicole-obrien** [comment]
Thanks added to the todo list
