### ISSUE TITLE
[Bug report]: Claiming Shimmer with Ledger. Firefly is stuck if no more tokens are to be found.

### ISSUE THREAD

**Issue by antonionardella** [iotaledger/firefly#4643]
### Platform

Desktop

### Version

2.0.0-beta-7

### Description

During the Shimmer claiming process with a Ledger wallet, Firefly is stuck if there are NOT more tokens are to be claimed when using the `Search for rewards` button.

Video available here:
https://cdn.discordapp.com/attachments/998627792717627443/1022419336595525672/claim_stuck.mp4

### Expected behaviour

A message that no more tokens have been found or to continue searching if the whole amount is not shown.
Being able to continue set up my profile.

### Actual behaviour

Firefly is stuck forever

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Add profile
2. Select Shimmer
3. Select Testnet
4. Select Claim Shimmer staking rewards
5. Select Use Ledger device
6. Insert profile name
7. Set up PIN
8. Unlock Ledger and open Shimmer app
9. Click Continue
10. Wait for Firefly to find the Shimmer staking rewards
11. Even though the sum of rewards is displayed click on the `Search for rewards` button
12. Firefly is stuck

### Operating System

Linux

### Diagnostics

```shell
Version 
Language: en
Platform: linux
Platform Version: 5.15.65-1-MANJARO
Platform Architecture: x64
CPU Count: 24
Total Memory: 64231.6 MB
Free Memory: 46406.3 MB
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Crash Status

Infinite loading symbol

### Error Messages

N/A

### Error Logs

```shell
Empty
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwellmattryan** [comment]
Have been working on this, seems to come from this error:
```
"`error sending request for url (https://api.testnet.shimmer.network/api/indexer/v1/outputs/basic?address=rms1qr63gvjjp8eeqju3sdkdpfkgdn7pr9frkuplxxmwr4w2s9c8qn9rjzqcsmu): connection error: broken pipe`"
```

Will continue investigating tomorrow with the wallet-rs team to see if they maybe know exactly why it's occurring during longer searches.

**Comment by maxwellmattryan** [comment]
Also seem to randomly get the `Ledger device not found` error when re-trying the search button, but this seems inconsistent :thinking:

**Comment by maxwellmattryan** [comment]
I think this task may help in fixing this issue - https://github.com/iotaledger/firefly/issues/4672

**Comment by maxwellmattryan** [comment]
Seeing some more errors:

```
{type: 'ClientError', error: '`error sending request for url (https://api.testne…qn9rjzqcsmu): connection error: connection reset`'}
```

```
{type: 'ClientError', error: "`error sending request for url (https://api.testnet.shimmer.network/api/indexer/v1/outputs/basic?address=rms1qr63gvjjp8eeqju3sdkdpfkgdn7pr9frkuplxxmwr4w2s9c8qn9rjzqcsmu): http2 error: connection error received: unspecific protocol error detected`"}
```

**Comment by freeleux** [comment]
also have a bug  time is not matching

Fri, 23 Sep 2022 21:23:59 GMT
ClientError: `Local time 1663968239 doesn't match the time of the latest milestone timestamp: 1663967758`

**Comment by maxwellmattryan** [comment]
Just got another one:
```
{type: 'ClientError', error: "`error sending request for url (https://ledgertest.hornet.zone/api/indexer/v1/outputs/basic?address=smr1qznapnwms6v9ajg2qg7nmhcs9x5p32zk2g7yrgqzauutvv4lxtc2y2wqsjm): http2 error: stream error received: refused stream before processing any application logic`"}
```

**Comment by maxwellmattryan** [comment]
After some changes to `wallet.rs` and the algorithm we wrote to find Shimmer rewards, these issues should no longer be a problem.

**Comment by Stcetjo** [comment]
Seems I am still having this problem. Version 2.0.1
Using Ledger Nano X. 
After the initial search for to claim tokens and it doesn't find any, clicking the search again gives an error "ledger not found" when it is connected just fine.
