### ISSUE TITLE
Firefly opens only with a blank screen

### ISSUE THREAD

**Issue by svenger87** [iotaledger/firefly#465]
## Issue description

After launching the application it only opens into a white blank screen with the menubar at the top.
Error log or Diagnostics cant´t be opened.

## Wallet version
0.10

## System specification

Xiaomi MiPad 2 Windows 10 Home with insider build 21332

## Is it a repeatable issue?

Y

## Expected behaviour

Describe what you expect to happen.

## Errors

![unknown](https://user-images.githubusercontent.com/35897839/111067573-3a82b380-84c5-11eb-8219-46722024724b.png)

**Comment by Tayotakid** [comment]
Same problem, opens on a white screen only. Windows build and console's errors on screenshot
![image](https://user-images.githubusercontent.com/81187221/112042781-35b6a300-8b48-11eb-8f72-fb3ff3688e0c.png)

**Comment by obany** [comment]
This doesn't appear to be a windows version specific problem, I also have 19042.867 and it works, so we can eliminate that as a cause.

**Comment by svenger87** [comment]
@obany check #641

**Comment by obany** [comment]
Could you try installing the VC++ runtime and see if this fixes the issue https://www.microsoft.com/en-us/download/details.aspx?id=53840

**Comment by Tayotakid** [comment]
It worked ! thanks !
