### ISSUE TITLE
[Bug report]: Unknown address in the activity history after deleting wallet

### ISSUE THREAD

**Issue by MiKeF05** [iotaledger/firefly#4680]
### Platform

Desktop

### Version

2.0.0-beta-8

### Description

I created 3 different wallets and deleted the third wallet. With the wallet finder it was possible to get back the third wallet. So far so good. The only thing missing is the address or wallet name in the activity history. In the image below it was a transaction from wallet 1 and a transaction from wallet 2. At least the address should be displayed.

![image](https://user-images.githubusercontent.com/71659397/192098599-bf52fdd2-7e25-40d5-8a67-99fe8fe4cedf.png)

### Expected behaviour

After using the wallet finder the wallet name or at least the sender/receiver address should be displayed in the activity history.

### Actual behaviour

Unknown address is displayed.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Create 2 wallets
2. Transfer some funds from wallet 1 to wallet 2
3. Delete wallet 2
4. Use the wallet finder
5. Sender address in the activity history is "Unknown address"

### Operating System

Windows

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicole-obrien** [comment]
If you deleted the wallet, then you will have deleted all of the history and cached data for the wallet. So when we recover the wallet, it may not be possible to get all of the pruned data for your previous transactions, only the unspent outputs. The outputs only include the sender if it is an async transaction (has a storage deposit return unlock, or a expiration time).
