### ISSUE TITLE
[Bug report]: Price of IOTA stays at 0.37AUD

### ISSUE THREAD

**Issue by sturtIOTA** [iotaledger/firefly#4682]
### Platform

Desktop

### Version

1.6.5

### Description

Hi there,
No matter what the actual price of 1 IOTA is, (currently at 0.42 AUD, it is always at 0.37 AUD in my Firefly account which then means the amount I am holding in AUD is always incorrect!

### Expected behaviour

The price of each IOTA should reflect the real, live price of an IOTA

### Actual behaviour

The price stays at 0.37 AUD

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Start Firefly

### Operating System

Windows

### Diagnostics

```shell
Version 1.6.5
Language: en
Currency: AUD
Node selection: Automatic
Platform: win32
Platform Version: 10.0.22000
Platform Architecture: x64
CPU Count: 6
Total Memory: 16222.3 MB
Free Memory: 10386.6 MB
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Actively staking

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
See also https://github.com/iotaledger/firefly/issues/4216

**Comment by begonaalvarezd** [comment]
New version with improved fiat management will be out soon
