### ISSUE TITLE
App Freezes: Back button on Create your Shimmer Profile

### ISSUE THREAD

**Issue by HyperMindz** [iotaledger/firefly#4709]
### Platform

Desktop

### Version

Firefly Desktop 2.0.0 Beta 8

### Description

When selecting Ledger during enrollment process and getting to the Create your Shimmer Profile, pressing the back button freezes the app completely. Eventually you need to force quit to get app to close.

### Expected behaviour

Expect to go back to the previous screen.

### Actual behaviour

App Freezes and can't close, minimize, input text or do anything.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Launch App
Select Shimmer protocol
Select Testnet
Select Claim Shimmer staking rewards
Select Use Ledger Device
Press back arrow

Note: this happens when with or without the Ledger device connected.

### Operating System

Windows

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Actively staking

### Crash Status

Non-responsive

### Error Messages

NA

### Error Logs

```shell
NA
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeeanribeiro** [comment]
Tried to reproduce it with the same steps but is fixed in newer versions
