### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by tyronefrance** [iotaledger/firefly#4743]
### Platform

Desktop

### Version

2.0.0

### Description

I had both the normal FIREFLY wallet open and the shimmer firefly wallet open... I then closed the normal firefly wallet and proceeded to close the shimmer fly wallet but when closing it I was presented with the following error.

`Wed, 28 Sep 2022 12:34:19 GMT
undefined: internal error in Neon module: error initializing account manager: Storage("IO error: Failed to create lock file: C:\AppData\Roaming\Firefly Shimmer/storage/3730717f6a674acd7befcd1521611049/LOCK: The process cannot access the file because it is being used by another process.\r\n") 
`

![1](https://user-images.githubusercontent.com/35028534/192782257-7b5b06ea-d889-4d24-9f55-3fc3d5888187.jpg)

### Expected behaviour

I was expecting the wallet to close and it did not. Instead it presented the error listed above

### Actual behaviour

It just errored and didn't close

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1.)Open Shimmer-Firefly wallet 
2.)Open Firefly wallet

3.)Close Firefly wallet
4.)Close Shimmer-Firefly wallet 

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Hello, thanks for the report. I´m going to close this issue as it seems to be a duplicate to https://github.com/iotaledger/firefly/issues/4513
