### ISSUE TITLE
[Bug report]: white screen at init

### ISSUE THREAD

**Issue by darkblade60** [iotaledger/firefly#4750]
### Platform

Desktop

### Version

2.0.0

### Description

White screen when I try to initiate the wallet.

### Expected behaviour

Normal first initation

### Actual behaviour

White screen since the beginning

### Can the issue reliably be reproduced?

No

### Operating System

Windows

### Diagnostics

```shell
default
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Crash Status

White screen

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Make sure to install the latest VS C++ Redistributables

**Comment by Araknai** [comment]
I am experiencing this issue.  Completely white window not resolving, every launch.  I installed the latest VS C++ Redistributables package from microsoft to no effect.

![image](https://user-images.githubusercontent.com/33713759/193426807-2fa681ca-6e87-42be-a5bb-c6bbd3a39eb6.png)

**Comment by wayne900** [comment]
> I am experiencing this issue. Completely white window not resolving, every launch. I installed the latest VS C++ Redistributables package from microsoft to no effect.
> 
> ![image](https://user-images.githubusercontent.com/33713759/193426807-2fa681ca-6e87-42be-a5bb-c6bbd3a39eb6.png)

Same probleme here
W10 all updates etc

**Comment by darkblade60** [comment]
I reinstalled graphics drivers and changed my resolution and it works!!!
