### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by roblessju** [iotaledger/firefly#4754]
### Platform

Desktop

### Version

2.0.0

### Description

migre mis token shimmer por medo de una copia de mi billetera firefly de iota y cunca me salio las claves semillas, y se cerro la billetera y no puedo volver a ver mis tokens, hay alguna posibilidad de solucionarlo?tngo cuants habia ganado en steaking.

### Expected behaviour

que parezcan las semillas para poder guardarlas 

### Actual behaviour

perdi mis tokens shimmer

### Can the issue reliably be reproduced?

No

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
@roblessju Por razones de seguridad, Firefly no muestra nunca la clave semilla (seed) excepto cuando creas el perfil por primera vez. Si quieres recuperar tus fondos staked, tienes que crear una copia de seguridad de tu perfil en Firefly IOTA (desde el cual hiciste staking) y usar esa copia en Firefly Shimmer para recuperar tus fondos usando el "claiming flow". Ten en cuenta que para crear copias de seguridad necesitas conocer la contraseña de tu perfil de IOTA donde hiciste Shimmer staking.

En Firefly IOTA:
![Image](https://github.com/iotaledger/firefly/assets/3624944/7b0c36d3-45c9-4474-b5fc-7e7fe61b004e)

![Image](https://github.com/iotaledger/firefly/assets/3624944/83e4ee55-d8a6-4f3c-9edd-ac4a4b0774e3)

![Image](https://github.com/iotaledger/firefly/assets/3624944/a19bf815-d0da-4e24-a9ed-5bb9b15d0e31)

En Firefly Shimmer:
![Image](https://github.com/iotaledger/firefly/assets/3624944/d1b33628-b48c-4c18-ac3a-9561542ce278)

**Comment by mcgregort** [comment]
Tengo el mismo problema, solo que no puedo acceder a Firefly ya que me dice que al estar actualizado ya no funciona esa billetera que va a funcionar en Chrome y entonces he perdido totalmente mi acceso a la billetera y no sé cómo recuperarla. Cuando hice la billetera, no tengo conocimiento de ningún momento a haber quedado ninguna semilla.

**Comment by mcgregort** [comment]
Si alguien me puede echar una mano, lo agradezco profundamente, ya que estoy perdido

**Comment by begonaalvarezd** [comment]
@mcgregort Firefly IOTA is deprecated and it no longer works for the new (IOTA) Mainnet network. You should switch to the new IOTA Wallet [IOTA Wallet - Chrome Web Store](https://chromewebstore.google.com/detail/iota-wallet/iidjkmdceolghepehaaddojmnjnkkija) . You can import your mnemonic or connect your ledger device to it.

If you still experience issues, please join our official Discord community at https://discord.iota.org and open a support ticket in the #raise-support-ticket channel. Our team is ready to assist you and get things running smoothly.
