### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by HaraldErtl** [iotaledger/firefly#4755]
### Platform

Desktop

### Version

2.0.0

### Description

Beim einrichten von Firefly Shimmer Wallet, beim beanspruchen der Rewards.

Wenn man die Rewards beansprucht und dann auf zurück klickt, dann kommt man bei der Einrichtung der Wallet nicht mehr weiter. Mann kann nur von vorne Beginnen und bleibt bei diesem Schritt immer hängen. Heißt man kommt nicht bis zur fertig gestellten Wallet durch.
<img width="1261" alt="Bildschirmfoto 2022-09-29 um 10 56 44" src="https://user-images.githubusercontent.com/87481382/192989284-bf7d9566-b1d2-4158-a9f8-3aef6514b14b.png">

### Expected behaviour

Ein WEITER Button

### Actual behaviour

nur ZURÜCK und BEANSPRUCHEN möglich

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Bis zur beanspruchung geht alles normal.

### Operating System

Mac

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tuditi** [comment]
We fixed this issue. If you still experience problems, please reopen the issue.
