### ISSUE TITLE
[Bug report]: Firefly sturdust doesn`t detect my shimmer reward

### ISSUE THREAD

**Issue by Baial5** [iotaledger/firefly#4756]
### Platform

Desktop

### Version

2.0.0 beta 6

### Description

when I try to claim my shimmer rewards through the firefly stardust wallet, through the stronghold  file, I get a notice that says there is an error. And when I try through the 24 words, it's detect the firefly iota, and when I try to look for the shimmer it doesn't find them.

### Expected behaviour

I expected to be able to pass my shimmer tokens from firefly iota to firefly sturdust

### Actual behaviour

Nothing happened! My tokens are still in the firefly IOTA wallet waiting to be able to claim them

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

None of the above

### Error Messages

something went wrong

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Do you use version 2.0.0 beta 6?

**Comment by Baial5** [comment]
yes!

**Comment by MiKeF05** [comment]
But why the beta version? You need to use the released 2.0.0 version

**Comment by Baial5** [comment]
You are right, I am sorry. I just installed the wallet correctly version 2.0.0, I was able to use the stronghold file, but when it searches for rewards I still get the following message: AN ERROR OCURRED WHILE SEARCHING FOR REWARDS

**Comment by Baial5** [comment]
I don't know why, but by creating a second wallet it has detected them. thanks for everything.
