### ISSUE TITLE
[Bug report]: Expired TX locked on reciever address (Conditionally Locked Balance)

### ISSUE THREAD

**Issue by bartholomaeu5** [iotaledger/firefly#4760]
### Platform

Desktop

### Version

2.0.0

### Description

As described in detail on discord (link below):
1.) claimed drop = 388,04
2.) sent some small tx with expiration option to soonaverse for verification, but all were unclaimed and therefore returned to me.
3.) assets showing smr 386,55 i.e. 1,49 less than claimed
4.) "Balance" showing smr 385,06 i.e. again 1,49 less than in assets.

[https://discord.com/channels/397872799483428865/748265907351978115/1024947956866093117](url)

![](https://cdn.discordapp.com/attachments/748265907351978115/1024947956538945596/unknown.png)

![](https://cdn.discordapp.com/attachments/748265907351978115/1024948121488330772/unknown.png)

### Expected behaviour

There shouldn´t be any funds locked/unspendable anymore as the tx expired

### Actual behaviour

funds locked/unspendable despite tx expired

### Can the issue reliably be reproduced?

No

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeeanribeiro** [comment]
This is fixed in newer versions
