### ISSUE TITLE
[Bug report]: nessun nodo sincronizzato

### ISSUE THREAD

**Issue by squib83** [iotaledger/firefly#4780]
### Platform

Desktop

### Version

2.0.0

### Description

non riesco più ad entrare nel profilo.
viene visualizzato un errore di sincronizzazione.
su impostazioni non si riesce a cambiare tranne se non si entra nel profilo ma visto che non si riesce non so come procedere

### Expected behaviour

riuscire dalle impostazioni andare in configurazione di rete

### Actual behaviour

da un momento all'altro non sono più riuscito ad entrate nel mio portafoglio

### Can the issue reliably be reproduced?

No

### Operating System

Windows

### Diagnostics

```shell
Versione 
Lingua: it
Piattaforma: win32
Versione della piattaforma: 10.0.19044
Architettura della Piattaforma: x64
Conteggio CPU: 12
Memoria Totale: 16205.7 MB
Memoria libera: 11345.0 MB
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Crash Status

None of the above

### Error Messages

Sat, 01 Oct 2022 10:10:52 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 10:10:04 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 10:09:47 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 08:40:25 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 08:40:17 GMT
undefined: undefined

Sat, 01 Oct 2022 08:35:50 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 08:35:44 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 08:35:42 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 08:35:35 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 08:23:54 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 08:15:44 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 08:12:27 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 08:04:53 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 07:52:36 GMT
ClientError: `No synced node available`

Fri, 30 Sep 2022 21:54:16 GMT
ClientError: `No synced node available`

Fri, 30 Sep 2022 21:48:07 GMT
ClientError: `No synced node available`

Fri, 30 Sep 2022 21:47:33 GMT
ClientError: `No synced node available`

Fri, 30 Sep 2022 16:50:57 GMT
ClientError: `No synced node available`

Fri, 30 Sep 2022 16:50:45 GMT
ClientError: `No synced node available`

Fri, 30 Sep 2022 16:49:49 GMT
ClientError: `No synced node available`

### Error Logs

```shell
Sat, 01 Oct 2022 10:10:52 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 10:10:04 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 10:09:47 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 08:40:25 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 08:40:17 GMT
undefined: undefined

Sat, 01 Oct 2022 08:35:50 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 08:35:44 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 08:35:42 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 08:35:35 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 08:23:54 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 08:15:44 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 08:12:27 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 08:04:53 GMT
ClientError: `No synced node available`

Sat, 01 Oct 2022 07:52:36 GMT
ClientError: `No synced node available`

Fri, 30 Sep 2022 21:54:16 GMT
ClientError: `No synced node available`

Fri, 30 Sep 2022 21:48:07 GMT
ClientError: `No synced node available`

Fri, 30 Sep 2022 21:47:33 GMT
ClientError: `No synced node available`

Fri, 30 Sep 2022 16:50:57 GMT
ClientError: `No synced node available`

Fri, 30 Sep 2022 16:50:45 GMT
ClientError: `No synced node available`

Fri, 30 Sep 2022 16:49:49 GMT
ClientError: `No synced node available`
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MarkNerdi** [comment]
Cannot reproduce and didn't occur for quite some time
