### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by kruver** [iotaledger/firefly#4782]
### Platform

Desktop

### Version

1.6.5 iota  end 2.0.0 shimmer

### Description

I type in the password and it won't let me in.

### Expected behaviour

Let Firefly remember the password and let me in without any problems

### Actual behaviour

I type in the password and it doesn't recognize it, but I know for sure it's correct.

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Duplicate to https://github.com/iotaledger/firefly/issues/4781
