### ISSUE TITLE
[Bug report]: Sonnaverse NFTs and Token not visible in my shimmer firefly wallet

### ISSUE THREAD

**Issue by Captain8885** [iotaledger/firefly#4783]
### Platform

Desktop

### Version

Last version of shimmer firefly

### Description

I swaped on iotabee IOTAs to Shimmer and this worked and arrived on my shimmer firefly. I did the same on soonaverse, I bought 2 NFTs and Shimmer, both I have transfereed to my shimmer firefly, but they are not showed in my wallet. I checked it on the explorer and they are visible.

### Expected behaviour

It should be visible in my shimmer firefly wallet

### Actual behaviour

not visible

### Can the issue reliably be reproduced?

Yes

### Operating System

Mac

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Actively staking

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicole-obrien** [comment]
Native NFTs are not yet supported by Shimmer Firefly and the collectibles tab is on our roadmap for Q4 this year.
