### ISSUE TITLE
[Task]: Fix occassional blank screen on selectedAccountStore is undefined

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#4792]
### Task description

If you send MIOTA from fantom testnet to IOTA Devnet, if you receive the tx while you have firefly open in the right wallet, firefly will show a blank screen. 
Use this url to send MIOTA from FTM to Devnet --> https://test.multichain.org/#/router

### Requirements

Receive tx from multichain doesnt crash anymore

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
It's not only a problem with multichain, here are the following things we noticed while debugging.
`selectedAccountStore` is undefined for a split second when receiving the transaction notification, which results in the Dashboard showing white.

The error might be around this area of code:


![Image](https://user-images.githubusercontent.com/45079109/199689789-ba1f682a-5426-4705-b82b-83e00d58cb57.png)



![Image](https://user-images.githubusercontent.com/45079109/199689816-e7749d7b-bfaa-49ea-9832-64fd21138b6c.png)

**Comment by begonaalvarezd** [comment]
Cant reproduce anymore, please reopen if needed
