### ISSUE TITLE
[Bug report]: `TypeError: Cannot read property 'usd' of null`

### ISSUE THREAD

**Issue by Strydom** [iotaledger/firefly#4803]
### Platform

Desktop

### Version

1.6.5

### Description

When opening the app I get the error message "TypeError: Cannot read property 'usd' of null".

### Expected behaviour

The app should open correctly.

### Actual behaviour

The app opens, shows the error and a blank wallet screen.

<img width="1270" alt="Screenshot 2022-10-04 at 12 12 21" src="https://user-images.githubusercontent.com/2946828/193811098-5fa99240-e2bf-4d8f-be7f-25884b33fb52.png">

### Can the issue reliably be reproduced?

No

### Steps to reproduce the issue

Unknown, the app was working and now it is not.

### Operating System

Mac

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Actively staking

### Crash Status

None of the above

### Error Messages

TypeError: Cannot read property 'usd' of null

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Strydom** [comment]
And now it is working again 🤷‍♂️

**Comment by kitodann** [comment]
Just had the same issue, was migrating seed, on windows 11 though, right after I reentered my pin it crashed and showed me the: “cannot read property of ‘usd’ null” with some more info below that.
