### ISSUE TITLE
[Bug report]: Unable to find SMR rewards

### ISSUE THREAD

**Issue by behemot86** [iotaledger/firefly#4804]
### Platform

Desktop

### Version

Firefly Shimmer V2.0.0

### Description

I download shimmer wallet and recovered by 24 -words seed phrase, and when it seaching my rewards it shows an error: https://i.imgur.com/2RHGIMW.png. But I have SMR in IOTA FireFly wallet. Can you help me please?

### Expected behaviour

it should find my rewards

### Actual behaviour

Tue, 04 Oct 2022 13:53:38 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:53:36 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:53:30 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:50:55 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:50:38 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:47:46 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:47:46 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:47:45 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:47:43 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:39:58 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:39:26 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:34:49 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:34:41 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:24:52 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:24:42 GMT
BaseError: An error occurred while searching for rewards

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Restore by 24-words seed frase
2. Claim reward

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Error Messages

An error occurred while searching for rewards

### Error Logs

```shell
Tue, 04 Oct 2022 13:53:38 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:53:36 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:53:30 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:50:55 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:50:38 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:47:46 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:47:46 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:47:45 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:47:43 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:39:58 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:39:26 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:34:49 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:34:41 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:24:52 GMT
BaseError: An error occurred while searching for rewards

Tue, 04 Oct 2022 13:24:42 GMT
BaseError: An error occurred while searching for rewards
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MarkNerdi** [comment]
@behemot86 Were you able to claim your SMR in a newer version of Firefly?

**Comment by kristofvdj88** [comment]
I'm experiencing the exact same issue and am using the latest version of Firefly Shimmer. I staked my IOTA during the very first staking period and only tried claiming the SMR rewards recently. 

**My diagnostics:**
Version 2.1.3
Language: en
Platform: win32
Platform Version: 10.0.19045
Platform Architecture: x64
CPU Count: 8
Total Memory: 32610.2 MB
Free Memory: 18021.2 MB

**Error log:**
Wed, 05 Jul 2023 04:45:37 GMT
BaseError: An error occurred while searching for rewards

Wed, 05 Jul 2023 04:45:11 GMT
BaseError: An error occurred while searching for rewards

Wed, 05 Jul 2023 04:45:09 GMT
BaseError: An error occurred while searching for rewards

Wed, 05 Jul 2023 04:45:06 GMT
BaseError: An error occurred while searching for rewards

**Device specifications:**
Processor	11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz   3.00 GHz
Installed RAM	32,0 GB (31,8 GB usable)
System type	64-bit operating system, x64-based processor

**Windows specifications:**
Edition	Windows 10 Enterprise
Version	22H2
Installed on	19/10/2022
OS build	19045.3086
Experience	Windows Feature Experience Pack 1000.19041.1000.0

I'm also using a GlobalProtect VPN

**Comment by begonaalvarezd** [comment]
The issue should be fixed in the latest version, please reopen if the problem persists 🌷
