### ISSUE TITLE
[Bug report]: Tried to create a developer profile

### ISSUE THREAD

**Issue by GodotInv** [iotaledger/firefly#4852]
### Platform

Desktop

### Version

2.0.0

### Description

App Version: 2.0.0

platform: win32
platformVersion: 10.0.22621
platformArchitecture: x64
cpuCount: 8
totalMem: 16301.0 MB
freeMem: 7276.8 MB

Error Type: [Preload Context] Error

Error: The profile manager was already initialized.
    at C:\Program Files\Firefly Shimmer\resources\app.asar\public\build\preload.js:2:307346
    at Array.forEach (<anonymous>)
    at EventEmitter.<anonymous> (C:\Program Files\Firefly Shimmer\resources\app.asar\public\build\preload.js:2:307333)
    at EventEmitter.emit (node:events:526:28)
    at Object.onMessage (node:electron/js2c/renderer_init:69:746)

### Expected behaviour

I wanted to create a developer profile. When I hit the button, I expected a page that would allow me to create a token on Shimmer. 

### Actual behaviour

I wanted to create a developer profile. When I hit the button, this error message appeared.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Click on the 3 dashes in the top left. 
Scroll down the menu to create a developer profile
Error

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

Non-responsive

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MarkNerdi** [comment]
Fixed in 2.1
