### ISSUE TITLE
[Task]: Check ledger support for L1 -> L2

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#4855]
### Task description

TBD

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jeeanribeiro** [comment]
Transaction done with ledger:
https://explorer.shimmer.network/testnet/transaction/0x325283aa2d0033ecaa63b231620dce87204f0dc5b47e99534a254f483778b8ac

**Comment by jeeanribeiro** [comment]
Only the metadata is showing weird text

![Image](https://user-images.githubusercontent.com/42754063/203343734-f36f142a-733d-4dc2-aca4-cd4658be4b6f.png)

**Comment by jeeanribeiro** [comment]
Test 2:

Sent a new transaction

https://explorer.shimmer.network/testnet/transaction/0x29300e67cf5f5b47bed9b38741223a92317163cf5c69e45b2078a5a62a756dce

![Image](https://user-images.githubusercontent.com/42754063/203349013-ad4a1f91-a585-41c5-82cf-8d85615344c9.png)


![Image](https://user-images.githubusercontent.com/42754063/203349137-6b26d89c-0302-42a2-b203-65d26acd01f1.png)
