### ISSUE TITLE
[Task]: Preselect current date and time when selecting expiry options

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#4893]
### Task description

At the moment, the user has to input the date and time when selecting expiration options.

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by MarkNerdi** [comment]
Closed with https://github.com/iotaledger/firefly/pull/5140
