### ISSUE TITLE
[Bug report]: Insufficient native tokens error when sending multiple times

### ISSUE THREAD

**Issue by Digidus** [iotaledger/firefly#4896]
### Platform

Desktop

### Version

2.0.0

### Description

When sending minted tokens this error occured multiple times (Image Attached)
![FireShot Capture 013 - Untitled document - Google Docs - docs google com](https://user-images.githubusercontent.com/115964784/196080765-d01d325d-9eef-424b-890b-64884571b5cf.png)

### Expected behaviour

sending the tokens without any issue was expected

### Actual behaviour

I recieved this error multiple times on 3 different attempted sends.  I re-entered...reattached? - the transaction immediately on the first two instances and the transaction went through.  on the 3rd attempt I recieved the error message 3 times before the transaction went through.  I sent a total of 17 transactions within 10 minutes and only 3 errored.

### Can the issue reliably be reproduced?

No

### Operating System

Windows

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

None of the above

### Error Messages

please see image above
![FireShot Capture 013 - Untitled document - Google Docs - docs google com](https://user-images.githubusercontent.com/115964784/196081241-15ce0802-c507-461a-a9d6-0f111a5c8288.png)

### Error Logs

```shell
Error log:
Sun, 16 Oct 2022 19:37:38 GMT
InsufficientFunds: insufficient funds 0/49600 available

Sun, 16 Oct 2022 19:34:42 GMT
InsufficientFunds: insufficient funds 0/49600 available

Sun, 16 Oct 2022 19:34:33 GMT
InsufficientFunds: insufficient funds 0/49600 available
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeeanribeiro** [comment]
@Digidus does it still happen in the latest version?

**Comment by begonaalvarezd** [comment]
Hi, is this still an issue in the latest version?

**Comment by marc2332** [comment]
Closing due inactivity.
