### ISSUE TITLE
[Bug report]: Something went wrong - Claim tokens with low storage deposit

### ISSUE THREAD

**Issue by lein1013** [iotaledger/firefly#4911]
### Platform

Desktop

### Version

2.0.1

### Description

precondition:
Wallet got some gift glow with some token (no need to claim). 
Further some other tokens were sent to this wallet with a time window to be claimed
When trying to claim the other token the error "Something went wrong" raised.

After adding 1 SMR to the wallet the tokens could be claimed.

### Expected behaviour

meaningful error message: "too low SMR storage deposit to claim tokens"

### Actual behaviour

error "Something went wrong" 

### Can the issue reliably be reproduced?

No

### Steps to reproduce the issue

Was not tried:
But maybe due to following steps:
1. create a wallet A
2. from a wallet B send a token to wallet A including gift tokens
3. wallet A will receive the token and some gift glow
4. send some other token from wallet B to wallet A with claim count down
5. if now the glow in wallet A are too low I would expect the error "Something went wrong"

### Operating System

Windows

### Diagnostics

```shell
Version 
Language: en
Platform: win32
Platform Version: 10.0.25217
Platform Architecture: x64
CPU Count: 12
Total Memory: 32519.3 MB
Free Memory: 13656.7 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Error Logs

```shell
Mon, 17 Oct 2022 19:55:26 GMT
insufficientFunds: 0,49600

Mon, 17 Oct 2022 19:31:02 GMT
undefined: undefined

Mon, 17 Oct 2022 19:27:17 GMT
undefined: undefined

Mon, 17 Oct 2022 19:26:50 GMT
undefined: undefined

Mon, 17 Oct 2022 19:23:18 GMT
undefined: undefined
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MarkNerdi** [comment]
Fixed in 2.1.0
