### ISSUE TITLE
Portfolio value not in sync with Chart

### ISSUE THREAD

**Issue by jkl2e** [iotaledger/firefly#492]
## Issue description

The Portfolio Value is display in 2 Ways:
Top left as a number.
Top right as a chart.
Those should show the same value.

## Wallet version

0.1.0 & 0.2.1

## System specification

macOS 11.2.2

## Is it a repeatable issue?

> Yes

## Steps To reproduce the issue

1. Receive new tokens
2. wait until transaction is confirmed

## Expected behaviour

Chart Updates after Transaction is confirmed

## Actual behaviour

Chart Updates later

<img width="1278" alt="Bildschirmfoto 2021-03-16 um 15 50 40" src="https://user-images.githubusercontent.com/71429780/111329954-d0f2d880-866f-11eb-8268-b0a2f586ae39.png">

**Comment by cvarley100** [comment]
Fixed in 0.3.0.
