### ISSUE TITLE
[Bug report]: Firefly Shimmer: 'View on Explorer' does not show the correct page

### ISSUE THREAD

**Issue by antonionardella** [iotaledger/firefly#5023]
### Platform

Desktop

### Version

2.0.1

### Description

Clicking on **View on Explorer** does not show the expected information
![image](https://user-images.githubusercontent.com/7383572/198033750-f92e3f3f-3b74-46d9-93d7-04dfd2ace2b4.png)

The _link_ adds _/block/_ to the URL instead of _/output/_ and therefore the Explorer shows **Not found**

![image](https://user-images.githubusercontent.com/7383572/198033807-a457eabf-acf6-4b09-833a-32e3294457f2.png)

### Expected behaviour

This URL should be opened in the browser to show the correct content

https://explorer.shimmer.network/shimmer/output/0x2304f6f6efc68856a8a6ac6107854d4f521bf1937ec60b0591d15d481de8e6690000

### Actual behaviour

This URL is opened in the browser, giving an error in the Explorer

https://explorer.shimmer.network/shimmer/block/0xcbb05450a2e8e10c4e68c08d4c6969b3b4ffd12ce17be6252b3c1fcf4818096b

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Click a transaction in the Activity pane
Clicking on _View on Explorer_
Wait for the Browser to show the wrong page with the **Not found** error

### Operating System

Linux

### Diagnostics

```shell
Version 
Language: en
Currency: USD
Node list: https://api.shimmer.network
Platform: linux
Platform Version: 5.15.74-3-MANJARO
Platform Architecture: x64
CPU Count: 24
Total Memory: 64231.6 MB
Free Memory: 48582.5 MB
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lucagiorgino** [comment]
@jeeanribeiro in file `firefly/packages/shared/components/ActivityDetail.svelte` line **224**. I think it should be changed from _${explorerLink}/**message**/${id}_ to _${explorerLink}/**transaction**/${id}_

**Comment by Dr-Electron** [comment]
@antonionardella I think you meant it should be replaced with the transaction link, no?
https://explorer.shimmer.network/shimmer/transaction/0xcbb05450a2e8e10c4e68c08d4c6969b3b4ffd12ce17be6252b3c1fcf4818096b

**Comment by Dr-Electron** [comment]
> @jeeanribeiro in file `firefly/packages/shared/components/ActivityDetail.svelte` line **224**. I think it should be changed from _${explorerLink}/**message**/${id}_ to _${explorerLink}/**transaction**/${id}_

@lucagiorgino that should be fine as in the IOTA mainnet that is the correct path:
https://github.com/iotaledger/firefly/blob/c5ab60af3ec587bb26c0865d0557448ccd37e08d/packages/shared/components/ActivityDetail.svelte#L188

**Comment by Dr-Electron** [comment]
Also this was solved in
https://github.com/iotaledger/firefly/commit/81a11552e0783f7db4ca3518b3058dd3b41443d6

So can be closed @jeeanribeiro

**Comment by jeeanribeiro** [comment]
Solved in https://github.com/iotaledger/firefly/commit/81a11552e0783f7db4ca3518b3058dd3b41443d6

Thanks @Dr-Electron @MarkNerdi @nicole-obrien @antonionardella @lucagiorgino
