### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by Micert** [iotaledger/firefly#5048]
### Platform

Desktop

### Version

1.6.5

### Description

I have sent Shimmer from Firefly Shimmer (v 2.0.0) from one wallet to an other, and the transaction was displayed as expected, but when I compare the values in the Firefly Wallets (v 1.6.5) there is still the values before the transaction.

### Expected behaviour

Same asset value in Firefly and Firefly Shimmer

### Actual behaviour

The values are not the same

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1.Send Shimmer token in the Firefly Shimmer Wallet from on to an other
2.compare values in Firefly and Firefly Shimmer

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
These are 2 separate wallets right now. The assets in Firefly Shimmer will not be displayed in Firefly.
