### ISSUE TITLE
[Bug report]: SRM: The entire balance cannot be sent

### ISSUE THREAD

**Issue by Travetown** [iotaledger/firefly#5069]
### Platform

Desktop

### Version

2.0.1

### Description

From my wallet I wanted to send the entire balance. This was rejected. I could only send the balance minus 1375 Glow. 

### Expected behaviour

It should be possible for a wallet to be emptied completely. It reminds me of XRP. 

### Actual behaviour

<img width="480" alt="main" src="https://user-images.githubusercontent.com/66588710/198995060-42ec84b0-4eca-4d59-a7d9-9d04ff5a835a.png">

### Can the issue reliably be reproduced?

No

### Steps to reproduce the issue

I can't say if this is reproducible. There were over 100 transactions with different tokens on the wallet. 

### Operating System

Mac

### Diagnostics

```shell
-
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Never staked

### Crash Status

None of the above

### Error Messages

no crash

### Error Logs

```shell
no error
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MarkNerdi** [comment]
You cannot send all of it, because some is locked as storage deposit for your native tokens.
