### ISSUE TITLE
[Bug report]: Native tokens should not be merged when creating remainder output

### ISSUE THREAD

**Issue by tanglepay-dev** [iotaledger/firefly#5073]
### Platform

Desktop

### Version

latest

### Description

Consider a user with 3 unspent UTXO, 1 with 1000$SMR, 1 with 100$FOO, the other with 10$BAR.

If user sent 5 $SMR out with Firefly, there is a single remainder created for native tokens which has 100 $FOO and 10 $BAR sitting on the single UTXO.

This brings about a few problems.
1. The native tokens are managed in a de-facto account based model, i.e. the single UTXO has all token balances, which has same scalability problem as ETH.
2. Wallet and other software are more error prone. When both $FOO and $BAR sit on the same UTXO, if the users would like to spend $FOO, software has to deal with $BAR carefully and also moving $BAR from spent UTXO to the newly created remainder. 
3. As we keep exploring the potential of multi-asset ledgers, consolidation of different tokens may also affect the use of UTXO features, e.g. Sender constraint.
4. Additional challenges and overhead on solving the Back-To-Genesis problem because of irrelevant information on the UTXOs.

Sample transaction
https://explorer.shimmer.network/shimmer/transaction/0xde8df16a89edce097ca90fa4e0fb73a4e90be52876b40f9961e6c82d9d463b86

### Expected behaviour

1. Consolidation of unspent outputs should be performed per native token.
2. There should be options in advance settings for different output management strategy.

### Actual behaviour

All native tokens were merged when user claims or transfers assets, either basic coins or native tokens.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

mentioned above.

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeeanribeiro** [comment]
This is not planned as our policy is to minimize storage deposit for the user
