### ISSUE TITLE
better explain the seed word input process @ import 24 words

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#509]
## Description

Add text after "Enter your seed or recovery phrase" (maybe smaller font or grey)
"Every word of your 24 words recovery phrase must be seperated from the next word with an empty space"

Second way would be: 
have the spaces for the words numbered out as 
1.)
2.)
.
.
.
24.) 
so users know exactly where and how to put the words in

third option - have 24 fixed blank fields to fill in the words 

## Motivation

i first didnt know if i should use an empty space or an comma or write them all in line.

## Requirements

Write a list of what you want this feature to do.

1.
2.
3.

## Open questions (optional)

Use this section to ask any questions that are related to the feature.

## Are you planning to do it yourself in a pull request?

no
<img width="329" alt="seedimport" src="https://user-images.githubusercontent.com/77154511/111737233-30dcbf80-88ba-11eb-849e-b5433c45374b.png">

**Comment by cvarley100** [comment]
Fixed in 0.3.0.
