### ISSUE TITLE
[Windows] button for system notifications has a reverse logic - active switches notifications off

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#510]
## Issue description

after using firefly on ubuntu i realized that windows does never show any notification popups like ubuntu does.

## Wallet version

0.1.0

system notifications are enabled 

## System specification

Platform: win32
Platform Version: 10.0.19041
Platform Architecture: x64
CPU Count: 4

## Is it a repeatable issue?

yes

## Steps To reproduce the issue

issue a transaction

## Expected behaviour

would expect the little popup notification popup "transfered 5 Mi from ... to ... succesfull"

## Actual behaviour

No notifications pop up

## Errors

none

**Comment by obany** [comment]
@Phyloiota If you disable "system" notifications it uses the inbuilt application ones instead, so the logic is not reversed

**Comment by Phyloiota** [comment]
> @Phyloiota If you disable "system" notifications it uses the inbuilt application ones instead, so the logic is not reversed

ah okay - sorry for the wrong declaration - anyway it is still an issue - i only get popup notifications from transactions in windows when i turn off the notifications in "settings"

**Comment by cvarley100** [comment]
@Phyloiota does this happen in 0.3.1 after deleting your Firefly folder?

**Comment by Phyloiota** [comment]
yess charly - still active. I did install 3.1 from scratch with deleted firefly folder. Still same behavior. Popups for tx show only up if notification checkmark is removed, see screencast:

https://user-images.githubusercontent.com/77154511/112702879-f1246200-8ecf-11eb-8b1e-a0915bffdccf.mp4

**Comment by Phyloiota** [comment]
and still same behaviour in 0.4.0

**Comment by cvarley100** [comment]
This is working as intended. System notifications mean OS ones. If you disable system notifications, an in app popup shows. If you enable system notifications, the notification displays at OS level.
