### ISSUE TITLE
[Ubuntu] creating additional account from 24 seed words fails and freezes account creation

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#512]
## Issue description
tried to import the seed words from my first profile (still active) to create a second profile. After putting in the words, set pw and pin the proccess stucks. Only closing the wallet lets me start again.
similar to issue #500 on windows

## Wallet version

Platform: linux
Platform Version: 5.8.0-45-generic
Platform Architecture: x64
CPU Count: 4
Total Memory: 5941.5 GB
Free Memory: 3187.9 GB
User Path: /home/phylo/.config/Firefly

## Is it a repeatable issue?

yes

## Steps To reproduce the issue
use 24 seed words of an active profile to create a second profile

1.
2.
3.

## Expected behaviour

abort proccess with expalining error, or allow process

## Actual behaviour

app is stuck 

## Errors

[-1616171455220.log](https://github.com/iotaledger/firefly/files/6169743/-1616171455220.log)

![Screenshot from 2021-03-20 00-30-14](https://user-images.githubusercontent.com/77154511/111753454-d8192100-88d1-11eb-9144-e840b78604c1.png)

**Comment by obany** [comment]
This looks like the same problem with ff being unable to sync the account as connection failed, syncing errors are now ignored during the creation process

**Comment by cvarley100** [comment]
Please reopen if you face this again.
