### ISSUE TITLE
[Bug report]: Ledger Nano S (NOT PLUS) and Firefly 1.7 = Cannot Stake or Send Transactions

### ISSUE THREAD

**Issue by CrashOverride-lab** [iotaledger/firefly#5147]
### Platform

Desktop

### Version

1.7.0

### Description

Since the Upgrade to Firefly 1.7.0 i cannot send or Stake a Wallet with 300 Transactions.

I was able to Stake 2 Wallets with a few Transactions after multiple trys. 

Was Firefly 1.7 tested with Ledger Nano S Accounts? Or were only Ledger Nano S **plus** Part of the Tests?

Soon the Staking begins and multiple Guys cannot Stake their funds, so this should be a prioritized Topic.

### Expected behaviour

That Firefly would let me send and Receive Transactions ;-) like in the previous versions.

### Actual behaviour

Problem persists.

also restarts, another Computers etc. are helping. Some friends with the same Hardwareconfiguration (Ledger Nano S) are facing the same Problems.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Upgrade Firefly 1.6X (all working) to Firefly 1.7
2. Try to Stake or Send a Transaction with a Wallet with 300 Transactions in Combination with a Ledger Nano S.

### Operating System

Windows

### Diagnostics

```shell
Version 1.7.0
Language: en
Currency: USD
Node selection: Automatic
Platform: win32
Platform Version: 10.0.22621
Platform Architecture: x64
CPU Count: 24
Total Memory: 32488.7 MB
Free Memory: 17727.9 MB
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Previously staked

### Crash Status

None of the above

### Error Messages

"Something went wrong" are sometimes displayed. But the Error Logs are empty.

### Error Logs

```shell
Error Log:

The Error Log is empty.
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CrashOverride-lab** [comment]
We developed after many Testings a Workaround:

1. Downgrade to Firefly 1.6.5
2. Reconfigure Firefly to use a Private Node (a whole Part of the Problem seems Timeouts on Wallets with >100 Adresses). A good Private Node is way faster then the default Public IF Nodes.
2. Send MIOTA to another Account
3. If a error occured (after multiple Trys), Send the Coin per Receive-Address each individually until all Coins transfered.
4. Upgrade to Firefly 1.7 and stake the Amount from the new Wallet.

**Comment by Nixgeht** [comment]
Hey,
do you know if the problem will be fixed in the long run? Because I have exactly the same problem. And even despite the fact that I only have 11 transactions. What I also noticed is that it's very difficult to connect my Ledger to Firefly - you could almost say it connects kind off randomly after waiting for quite a while. Was or is this also the case for you?
