### ISSUE TITLE
[Task]: Fix deeplinks on linux not working unless logged in

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#5151]
### Task description

For some reason on the linux platform the deep link does not persist and get handled if clicked before the user logs into the app. On mac and windows it correctly works in that you can click a deep link when the app is closed and when logged in it will be handled.

### Requirements

Fix deep links on linux.

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
Duplicate https://github.com/iotaledger/firefly/issues/5006
