### ISSUE TITLE
[Task]: Investigate differing balance across app

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#5156]
### Task description

A few people reported that they can not send because the available balance is showing as 0, but if they restore the profile then the available balance is correct. Because it fixes on restore profile but not on restart, it appears to be a wallet.rs issue.

### Requirements

Investigate cause of issue and rule out firefly.

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by marzgithub858** [comment]
My case is that I can't even see or retrieve my $SMR rewards despite several times refreshing the firefly shimmer desktop v2.0.1.. And I have been trying to do this for weeks already.

**Comment by MiKeF05** [comment]
@marzgithub858  Have you already claimed your rewards in the firefly shimmer app?
