### ISSUE TITLE
[Task]: Update the NFT placeholder icons 

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#5172]
### Task description

Currently we used temporary icons in the NFT placeholder component, we should get the UI team to generate some specific icons in our styling to be used here and then replace the temporary.

### Requirements

New designs for icons:
- Image
- Video
- Audio
- Text
- Application
- Font
- Model
Replace old icons with new

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by kraftjs** [comment]
Blocked until we receive the updated icons for MimeTypes from design.
