### ISSUE TITLE
[Task]: Add network Icon to the Network selector 

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#5192]
### Task description

We should add the network icon to the network selector drop down

### Requirements

Add network icon to the network selector dropdown

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
Waiting for designs for the icon
