### ISSUE TITLE
[Task]: Add burning native token activity and burning direction

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#5194]
### Task description

We should add a burning native token activity now that we can burn native tokens. This should also adapting the direction of activities to include a burn option.

### Requirements

Add burn to direction of activities.
Add burn activity generation based on comparing inputs and outputs
Add burn activity generation directly from the burn transaction
Add burn to basic activity tile and popup

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
Blocked until wallet.rs returns transactions with inputs AND outputs.
