### ISSUE TITLE
[Task]: Prevent user from entering onboarding while logging in

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5196]
### Task description

It is possible to enter the onboarding flows from the top menu bar while the loading screen to login is displayed. This causes an error to occur that the profile manager was already initialized:

It is also possible that you can click the menu to make it disappear, wait for the login to finish, then enter the onboarding flow from a logged in state (which results in a leaked account manager).

```
App Version: 2.0.0

platform: linux
platformVersion: 5.15.0-52-generic
platformArchitecture: x64
cpuCount: 8
totalMem: 31890.0 MB
freeMem: 9192.3 MB

Error Type: [Preload Context] Error

Error: The profile manager was already initialized.
    at /tmp/.mount_fireflgtH5jX/resources/app.asar/public/build/preload.js:2:307346
    at Array.forEach (<anonymous>)
    at EventEmitter.<anonymous> (/tmp/.mount_fireflgtH5jX/resources/app.asar/public/build/preload.js:2:307333)
    at EventEmitter.emit (node:events:526:28)
    at Object.onMessage (node:electron/js2c/renderer_init:69:746)
```

### Requirements

_TBD_

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
https://github.com/iotaledger/firefly/issues/4852
