### ISSUE TITLE
[Task]: Implement flow to change votes for a proposal

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5268]
### Task description

The user may want to change a specific answer for a proposal (during the middle of counting).

### Requirements

_TBD_

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
Blocked until https://github.com/iotaledger/firefly/issues/5495 is closed

**Comment by Tuditi** [comment]
Works out of the box.
