### ISSUE TITLE
[Task]: Add tooltip for additional answer info

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5271]
### Task description

A specific answer for a question may include additional information, which should be displayed in a tooltip.

### Requirements

_TBD_

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jeeanribeiro** [comment]
It has already been added, ProposalAnswer.svelte:39
