### ISSUE TITLE
[Task]: Mock crypto nodejs module for testing of BaseError

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5290]
### Task description

To be able to test code that relies on the crypto module [(e.g. `generateRandomId`)](https://github.com/iotaledger/firefly/blob/d870405e735caa1992f88b78d95e62d097f751d9/packages/shared/lib/core/utils/random.ts#L1). We should create a mock for `getRandomValues()`.

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by maxwellmattryan** [comment]
Closing this issue since this already exists [here](https://github.com/iotaledger/firefly/blob/develop/packages/shared/lib/tests/__mocks__/crypto.mock.ts) :+1:
