### ISSUE TITLE
Status of activity can not be filtered in status for locked transactions

### ISSUE THREAD

**Issue by Tombaaa** [iotaledger/firefly#5338]
### Platform

Desktop

### Version

2.0.1

### Description

Transactions shown in the Activity Section of Firefly Shimmer can not be filtered for locked in the status field.

![image](https://user-images.githubusercontent.com/77152394/205439895-287f4963-0814-4612-a047-28ce06bf2e21.png)

the option to select "locked" is missing

![image](https://user-images.githubusercontent.com/77152394/205439917-2da6ee7b-0cf8-4e30-a7ef-d12d349cbe55.png)

### Expected behaviour

all possible status should be possible to select, e.g. add locked to the possible selection

### Actual behaviour

does not show status "locked" as an option to select

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

 1. select filter
 2. select status
 3. option to select "locked" is not shown

### Operating System

Windows

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Never staked

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeeanribeiro** [comment]
Tracked in #6430
