### ISSUE TITLE
wallet internal "error log" only shows fresh errors after closing the app and opening again

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#537]
## Issue description

experienced this issue in all version until now. The internal "error log" shows nothing when you get error messages.
Errors are already vissible in the developer console
After closing the app and logging in again those errors are now in the error log.

## Wallet version

0.2.0

## System specification

win 10

## Is it a repeatable issue?

yes

## Steps To reproduce the issue

wait for an error and open error log - it will not be there. close the app, open again, now error shows up in the log
## Expected behaviour
direct showing of errors in the log

## Actual behaviour

log gets filled only after restart

**Comment by obany** [comment]
This should be fixed in the next release, please re-open if it is still an issue
