### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by wedvjin** [iotaledger/firefly#5376]
### Platform

Desktop

### Version

2.0.1

### Description

When 7th profile is created, after going through all the creation steps: the app opens one of the existing profiles and newly created disappears. It also bypasses pin protection when opens.

Essentially, it is impossible to crate more than 6 profiles.

### Expected behaviour

The profile is created as normal and displayed next to other 6.

### Actual behaviour

At the end of the creation process, the profile is not created but one of the existing ones opens without asking for a pin.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Create 6 profiles
2. Create 7th profile
3. Observe

### Operating System

Mac

### Diagnostics

```shell
Version 
Language: en
Platform: macOS
Platform Version: 10.15.7
Platform Architecture: x64
CPU Count: 4
Total Memory: 16384.0 MB
Free Memory: 186.9 MB
```

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeeanribeiro** [comment]
We were not able to reproduce it, might already be fixed
