### ISSUE TITLE
[Task]: fix max button on send when glow is selected

### ISSUE THREAD

**Issue by paul-boegelsack** [iotaledger/firefly#5382]
### Task description

When using the max button on send with glow selected as subunit, the glow amount is added, but the unit changes to shimmer.

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
Its correct to switch the max amount to the base unit
