### ISSUE TITLE
changing the file name of the stronghold backup during saving makes the file unusable

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#539]
## Issue description

i created 3 backup file:
1.) during profile setup, 2.) after account creation and funds received, another one to test this.
All those file i changed the filename (so i can remember to what they belong) during the normal firefly "file saving" process (not afterwards)

Now i tried to import those and see they are not accepted.
File type is changed from STRONGHOLD file to "file" and its not possible to import in the wallet.
Only leaving the name unchanged as prepared from firefly in the explorer dialogue creates a "Stronghold" file type

## Wallet version

- wallet version (version number, commit, or branch):

Platform: win32
Platform Version: 10.0.19041
Platform Architecture: x64
CPU Count: 4

## Is it a repeatable issue?

yes

## Steps To reproduce the issue

click 'backup stronghold', change one character in the preset filename

Those backups i did today, only one is usable: 
<img width="554" alt="file backups" src="https://user-images.githubusercontent.com/77154511/111865468-1e3db580-89a2-11eb-982d-0392306b420e.png">

**Comment by cvarley100** [comment]
Did you remove the file extension when you changed the name?

**Comment by Phyloiota** [comment]
> Did you remove the file extension when you changed the name?

No charlie - windows explorer soes autiomaticaly just give "all files" in dropdown menu. If you dont touch the filename it saves as Stronghold, as soon as you change anything in the filename, even without touchging the "filetype" dropdown menu it daves it as "newname.file"
<img width="683" alt="backup file type" src="https://user-images.githubusercontent.com/77154511/112701761-76a61300-8ecc-11eb-8b9a-f8c886def6b4.png">
<img width="508" alt="backupfiletest" src="https://user-images.githubusercontent.com/77154511/112701771-7c9bf400-8ecc-11eb-9ba8-91e6e8b6d799.png">
<img width="563" alt="explorertest" src="https://user-images.githubusercontent.com/77154511/112701778-8160a800-8ecc-11eb-942f-cf95d51d749b.png">

This "file" is not possible to use as stronghold backup.

**Comment by obany** [comment]
This should be fixed on the next release, the extension is enforced on save.

**Comment by Phyloiota** [comment]
can confirm that it is fixed now. In the save file dialogue windows has now automatically the file type "stronghold - file" and you can rename to any name you like as long as you keep the file type
