### ISSUE TITLE
Proof of work is missing in settings

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#541]
## Issue description

The option in advanced settings "proof of work" is a point in the menu and a clickable link, but is not visible in the actual advanced settings page

0.2.0
Platform: win32
Platform Version: 10.0.19041
Platform Architecture: x64

## Is it a repeatable issue?

yes

no errors
<img width="780" alt="proof of work" src="https://user-images.githubusercontent.com/77154511/111869998-10e1f480-89bd-11eb-9b94-302509c1fe5a.png">

**Comment by obany** [comment]
This is implemented in the next version.
