### ISSUE TITLE
Password strength is GOOD, but still too weak

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/firefly#543]
## Issue description

Password strength is shown as `GOOD`, but it doesn't let me save it because it says `Your password is too weak`

## Wallet version

- wallet version (version number, commit, or branch): 0.2.0

## System specification

What is your operating system?

Win

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Use `FireflyPassw` as password

## Expected behaviour

Password strength should be weak, or it should allow it

## Errors

![image](https://user-images.githubusercontent.com/46689931/111870698-82528080-8986-11eb-9ef8-1e5b7788e615.png)

**Comment by alorraine** [comment]
Same issue on Mac 0.3.0

First arose from entering a password that was too weak, and after deleting (backspace) and trying with new password which I know to be complex, the "too weak" barrier still exists.

<img width="464" alt="Screenshot 2021-03-22 at 18 18 20" src="https://user-images.githubusercontent.com/19776496/112038969-617f5c00-8b3b-11eb-867b-18a55d171e73.png">

Resolved by pressing 'back' in the app, then restarting with strong password.

**Comment by cvarley100** [comment]
@alorraine yours appears to be a different issue. Please can you open a separate issue for it?

**Comment by alorraine** [comment]
> @alorraine yours appears to be a different issue. Please can you open a separate issue for it?

I've not been able to repeat this error since the update to 0.3.1
