### ISSUE TITLE
Automatically open "Move funds" tab when deleting account with balance

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/firefly#545]
## Description

Firefly presents an alert when trying to delete an account with a positive balance. The option "Move funds" should then open the "Move funds" tab by default.

## Motivation

It is more convenient than manually switching to the "Move funds" tab in case it wasn't selected earlier.

## Are you planning to do it yourself in a pull request?

No.

**Comment by obany** [comment]
This should be fixed, please re-open if the problem persists after next release.
