### ISSUE TITLE
[Task]: Fix inconsistency in displaying proposal states

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5466]
### Task description

The proposal states are showing inconsistently in the Governance dashboard vs the proposal view vs what is visible on the node.

### Requirements

_TBD_

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
Blocked until https://github.com/iotaledger/firefly/pull/5682 is merged.
