### ISSUE TITLE
[Task]: Fix node auth required popup to show only specific, required credentials

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#5472]
### Task description

Currently, we show all three inputs for username, password, and JWT, however it's possible that the node requires...
- Username and password
- JWT
- Username, password, and JWT

### Requirements

_TBD_

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
Blocked until we have more information on how wallet.rs handles authentication on their end.

**Comment by Tuditi** [comment]
Having authenticated endpoint is an edge case and will occur only for a limited set of users. Node owners will manually generate a JWT to access the protected endpoints, so we only need a JWT field for now.
