### ISSUE TITLE
[Bug report]: An error message shows up after setting up the PIN number

### ISSUE THREAD

**Issue by guhyeonjeong** [iotaledger/firefly#5486]
### Platform

Desktop

### Version

2.1.0-alpha-1

### Description

An error message shows up after setting up the PIN number

### Expected behaviour

No error message displayed and proceed to the next step

### Actual behaviour

An error message shows up

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Create a new profile
2. Proceed to the PIN number setting stage
3. Moving to the next stage shows up the error message

### Operating System

Mac

### Diagnostics

```shell
App Version: 2.1.0-alpha-1

platform: macOS
platformVersion: 13.0.1
platformArchitecture: x64
cpuCount: 36
totalMem: 131072.0 MB
freeMem: 84278.9 MB

Error Type: [Main Context] Unhandled Rejection

Error: No application in the Launch Services database matches the input criteria.
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

App Version: 2.1.0-alpha-1

platform: macOS
platformVersion: 13.0.1
platformArchitecture: x64
cpuCount: 36
totalMem: 131072.0 MB
freeMem: 84278.9 MB

Error Type: [Main Context] Unhandled Rejection

Error: No application in the Launch Services database matches the input criteria.

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rajivshah3** [comment]
I think this would only come from opening a URL 🤔  https://github.com/electron/electron/blob/644243efd61b75c22707605d9d0dbc6ade4fe458/shell/common/platform_util_mac.mm#L32

**Comment by begonaalvarezd** [comment]
Hi, is this still an issue in the latest version?

**Comment by guhyeonjeong** [comment]
I just tested for Firefly Shimmer, and didn't see any error message during the test. 

[Version info.]
    macOS : 13.5.2
    Firefly Shimmer : 2.1.6 (which already had 2 profiles)
                                  2.1.7-beta-1 (which had no profiles)

**Comment by begonaalvarezd** [comment]
Thank you, will close the issue 🙏🏼 please reopen if the issue appears again
