### ISSUE TITLE
[Task]: Add error handling for fetch response status codes

### ISSUE THREAD

**Issue by kraftjs** [iotaledger/firefly#5515]
### Task description

Errors returned from attempting to fetch NFT media is currently polluting the developer console. Add error handling for fetch response status codes. 

### Requirements

Add error handling for fetch response status codes

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by MarkNerdi** [comment]
Closed in https://github.com/iotaledger/firefly/pull/6296
