### ISSUE TITLE
[Bug report]: Does not synch the Wallet

### ISSUE THREAD

**Issue by sl00k** [iotaledger/firefly#5520]
### Platform

Desktop

### Version

1.7.0

### Description

I did try different Nodes, and three different internet provider

network status is green.

wallet history does not update and can not stake iota, because the wallet does not synch

### Expected behaviour

a wallet that can synch

### Actual behaviour

a wallet which does not synch

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. start firelfy
2. error

### Operating System

Windows

### Diagnostics

```shell
Version 1.7.0
Language: en
Currency: EUR
Node selection: Automatic
Platform: win32
Platform Version: 10.0.22623
Platform Architecture: x64
CPU Count: 16
Total Memory: 15741.3 MB
Free Memory: 4418.3 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sl00k** [comment]
![image](https://user-images.githubusercontent.com/33859801/209535602-23c66189-369a-4f3c-af35-cb8be1fcfbe8.png)
6b897d88327df6db6fa0657b11a2868641cead45b9a679ff5a53f25a710577be

seems like the staking worked. 

but this does not load 
![image](https://user-images.githubusercontent.com/33859801/209535663-bc199178-baf4-4286-afba-5761c2651f24.png)

**Comment by begonaalvarezd** [comment]
Hi, is this still an issue in the latest version?

**Comment by sl00k** [comment]
no
