### ISSUE TITLE
[Task]: Check if governance state is cleared after logging out.

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5572]
### Task description

Sometimes FF throws governance errors when a user logs out. I think it relates to polling governance events.

### Requirements

TBD

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by maxwellmattryan** [comment]
I am not getting any Governance-related errors, but once in every 20 or so logouts I'll get this:
```
internal error in Neon module: error initializing account manager: Storage("IO error: lock hold by current process, acquire time 1674172746 acquiring thread 106593: /home/maxwellmattryan/.config/Electron/__storage__/383e73c23c51597d12f02e6cf79650f3/LOCK: No locks available")
```

It's incredibly inconsistent though, and the wallet-rs logs don't look too suspicious.

**Comment by Tuditi** [comment]
I think it relates to a wallet API that has been initiated, but for which the response comes after the profile has logged out. Maybe it's a database that is still being queried while the user already logged out.
