### ISSUE TITLE
[Bug report]: Cannot chose the options of the voting - 2 UPDATES

### ISSUE THREAD

**Issue by MyMonk089** [iotaledger/firefly#5628]
### Platform

Desktop

### Version

2.1.0-alpha-3

### Description

I cannot choose the options of the voting. When clicking on one of the answers, nothing happens.

UPDATE: Tested another proposal and there it worked. Seems a single problem...

UPDATE 2: Saw that this vote isn't open yet... seems it was my fault. ;-)

<img width="347" alt="Bildschirm­foto 2023-01-21 um 09 43 16" src="https://user-images.githubusercontent.com/60474745/213859344-054a83ec-1270-4106-92cc-352d8c000e29.png">

<img width="1185" alt="Bildschirm­foto 2023-01-20 um 18 14 09" src="https://user-images.githubusercontent.com/60474745/213762417-476ef934-e870-4514-b1a5-5ca5c89f535a.png">

### Expected behaviour

The option I select should be picked and marked in a color.

### Actual behaviour

See upon.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. register a proposal
2. click on the answers to the questions.

### Operating System

Mac

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

No.

### Error Logs

```shell
No error logs available.
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Phyloiota** [comment]
This shows that it's not clearly visible that a proposal is not yet ready to vote while in the announcement. Even if it is displayed when "counting starts," the contrast on the button that says "vote starts in 5 days" is too less even to recognize that there might be any important information. 
I suggest either making it much more contrasting or even making the writing "starts in 5 days" blink or something like that.

**Comment by jeeanribeiro** [comment]
I've opened a PR that fixes the expected cursor behavior, it should look like the answer is not selectable when it is really not

**Comment by jeeanribeiro** [comment]
@MyMonk089 do you think that changing the cursor would prevent your expectation to select the answer?

**Comment by MyMonk089** [comment]
Hey. Think the problem was (see Updates), that this proposal was not live, yet, at the time I wanted to vote. So there is no problem, but, as mentioned by Phylo, maybe you can highlight when a proposal will be live in X days!?
