### ISSUE TITLE
[Bug report]: Firefly freezes after submitting a vote

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#5629]
### Platform

Desktop

### Version

Alpha 3

### Description

Casting a vote for a proposal and confirming it with a password. 
A message appears "Your vote was successfully cast." 
After this, the wallet does not react to any actions anymore, I can click the "Vote" and "Cancel" Buttons, but they are not responsive. Buttons in the sidebar are not clickable anymore.
Only the main burger menu is reachable, and the wallet can be closed by clicking on exit.

EDIT: This also happened once i just entered the detail view of a proposal. I casted a vote on this proposal, went back to the dashboard view, went back into the detail view of the proposal on then it frezzed same as described before, see second video of the behavior

https://user-images.githubusercontent.com/77154511/213840600-0b17f332-a167-46f9-994e-27e759efa934.mp4

https://user-images.githubusercontent.com/77154511/213860726-f5ee8864-3a76-4f61-a236-a26f919626d7.mp4

### Expected behaviour

see above

### Actual behaviour

wallet gets unresponsive

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

see above

### Operating System

Windows

### Diagnostics

```shell
Version 
Language: en
Currency: undefined
Node list: https://api.testnet.shimmer.network
Platform: win32
Platform Version: 10.0.22621
Platform Architecture: x64
CPU Count: 16
Total Memory: 16236.1 MB
Free Memory: 8685.7 MB
```

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

Non-responsive

### Error Messages

none

### Error Logs

```shell
none
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeeanribeiro** [comment]
It looks like it is related to the proposal milestones info, I could not reproduce the error but my "Counting ends on" shows a different date than yours @Phyloiota 
Probably related to #5466 

I'm still investigating how this can be fixed
