### ISSUE TITLE
[Bug report]:  Incorrect display of Proposal timing information for "announced" proposals

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#5630]
### Platform

Desktop

### Version

Alpha 3

### Description

For a Proposal that is in the "announcement phase" Firefly displays only the information when the "counting" phase of the proposal begins, but not when a voter actually can start to vote (Commencing) 

![image](https://user-images.githubusercontent.com/77154511/213860104-fe72193e-c604-4d62-b3b5-5b57062f68b8.png)

### Expected behaviour

I would except to always dis[lay when the next Phase begins. For a user that is most likely the most important information.

Edit, i see now that the button displays "Voting starts in 5 days" - i did not see this while trying to vote on the proposal, this should be highlighted much better to make this information visible.

### Actual behaviour

dispalys only when a proposal counting starts

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

open an proposal that is in "announcement"

### Operating System

Windows

### Diagnostics

```shell
--
```

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

--

### Error Logs

```shell
--
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tuditi** [comment]
May be related to: https://github.com/orgs/iotaledger/projects/35/views/1?pane=issue&itemId=16778891

**Comment by jeeanribeiro** [comment]
I created a subtask in #5663 that can address this issue, we should have different relevant data in the proposal information box for each phase
