### ISSUE TITLE
[Bug report]: Submitting the same vote multiple times is not deactivated

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#5634]
### Platform

Desktop

### Version

Alpha 3

### Description

Firefly lets me vote again on a proposal for the same option that i have already voted on before.

### Expected behaviour

I should only have the possibility to vote for another option (change opinion) or stop/cancel the vote, but allowing me to vote the same thing again is confusing.
Though this action does not have any effect and will not show up in the tx history, i would like to disable the possibility of doing this. EDIT: after a minute, those actions show up in the tx overview as "voting power decreased - 0 SMR" that's also not really a helpful message

![image](https://user-images.githubusercontent.com/77154511/213895416-5d3c2c66-33dc-43a3-8ff3-092e3a0f7c8e.png)

Either clicking on the option that i had voted for already should not be possible, or, in the confirmation dialogue, there should be a warning, "you have already voted for this option with your voting power."

### Actual behaviour

https://user-images.githubusercontent.com/77154511/213895530-efe22f79-c52c-477f-b618-0f95dcd85921.mp4

see video

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

vote on a proposal
leave the proposal detail view
enter the proposal again
vote for the same option again

### Operating System

Windows

### Diagnostics

```shell
Version 
Language: en
Platform: win32
Platform Version: 10.0.22621
Platform Architecture: x64
CPU Count: 16
Total Memory: 16236.1 MB
Free Memory: 7866.5 MB
```

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

--

### Error Logs

```shell
--
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeeanribeiro** [comment]
Created a subtask for it in #5663 

"Don't allow voting for the same question with the same answers selected and the same voting power"
