### ISSUE TITLE
[Bug report]: "About Firefly Shimmer - Alpha" screen does not go away

### ISSUE THREAD

**Issue by BenRoyce-Society2-com** [iotaledger/firefly#5654]
### Platform

Desktop

### Version

2.1.0-alpha-3

### Description

about screen persists and cannot be dismissed via any action (besides closing the main application). it does not block other actions. it also can be minimized and does not steal screen real estate

(so minor bug and should be easy to fix)

### Expected behaviour

tapping the about screen or shifting focus from it should dismiss the screen

### Actual behaviour

about screen displayed and now undismissable

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. from main menu select "Firefly Shimmer - Alpha" 
2. ...submenu: "About Firefly Shimmer - Alpha"

### Operating System

Windows

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tuditi** [comment]
I can close it using the 'X' button on the latest beta release. Does the problem persist for you? If not, I'll close this issue.
