### ISSUE TITLE
[Task]: Rename register proposal to add proposal

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5660]
### Task description

Register proposal might confuse the users, so let's change the wording to add proposal.

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Phyloiota** [comment]
Maybe we call it "upload" proposal? Dont know, Add is also fine, definitely better than "register"

**Comment by jeeanribeiro** [comment]
Included in #5546
