### ISSUE TITLE
[Bug report]: Selecting and deselecting vote leaves "Vote" button active while it shouldn't

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/firefly#5685]
### Platform

Desktop

### Version

2.1.0-alpha3

### Description

When we select and deselect certain vote, the Vote button stay active while it shouldn't and we getting error as a result (everything captured on the video)

https://user-images.githubusercontent.com/35224101/215120232-e73e7872-68f4-40c4-baff-3fada06fd361.mp4

### Expected behaviour

"Vote" button should constantly check if all votes are properly selected, not only once

### Actual behaviour

(on the video above)

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Try to vote
2. Select all options (Vote button gets active)
3. Deselect one vote (Vote button stays active while it should get desactivated)
4. Click "Vote" and you will get an error **invalid type: null, expected u8 at line 1 column 188**

### Operating System

Windows

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

invalid type: null, expected u8 at line 1 column 188

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeeanribeiro** [comment]
Tracked in https://github.com/iotaledger/firefly/issues/6184
