### ISSUE TITLE
[Task]: Fix switching wallets when on the proposals details page

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#5749]
### Task description

When switching wallets on the proposals details page the governance dashboard correctly resets but it stays in an infinite loading state.

### Requirements

- Find and fix the issue so that the governance dashboard correctly loads

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
May be related to this issue: https://discord.com/channels/397872799483428865/988073611287994418/1072062437597126718

**Comment by Tuditi** [comment]
Closed, since it doesn't occur on dev branch anymore.
