### ISSUE TITLE
"You must transfer your balance before deleting this account" when trying to delete account, even when it's empty

### ISSUE THREAD

**Issue by t00k** [iotaledger/firefly#576]
## Issue description

I am not able to delete an account and gets the error "You must transfer your balance before deleting this account" even though it is empty.

## Wallet version

FF 0.2.1
Win 19

## Steps To reproduce the issue

1. Add 6 different accounts. Send funds between them.
2. Consolidate all funds into Account 1.
3. Try and delete the profile.

## Expected behaviour

The profile should be removed, since it doesnt hold any funds.

## Actual behaviour

Gets the error "You must transfer your balance before deleting this account" and not being able to delete the account.

## Errors

Error Log - Sun, 21 Mar 2021 13:52:52 GMT
AccountNotEmpty: can't delete account: account has history or balance

Developer Tools

> message: "can't delete account: account has history or balance"
> time: 1616334884703
> type: "AccountNotEmpty"
> __proto__:
> constructor: ƒ Object()
> hasOwnProperty: ƒ hasOwnProperty()
> isPrototypeOf: ƒ isPrototypeOf()
> propertyIsEnumerable: ƒ propertyIsEnumerable()
> toLocaleString: ƒ toLocaleString()
> toString: ƒ toString()
> valueOf: ƒ valueOf()
> __defineGetter__: ƒ __defineGetter__()
> __defineSetter__: ƒ __defineSetter__()
> __lookupGetter__: ƒ __lookupGetter__()
> __lookupSetter__: ƒ __lookupSetter__()
> get __proto__: ƒ __proto__()
> set __proto__: ƒ __proto__()
in 
> debugger:///VM69 C:\Users\t00k\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js
[error.zip](https://github.com/iotaledger/firefly/files/6177543/error.zip)

Adding the preload.js error file in a zip.

**Comment by cvarley100** [comment]
Fixed in 0.3.1.
