### ISSUE TITLE
[Bug report]: Error while triying to open settings from the developer section

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#5770]
### Platform

Desktop

### Version

Alpha 4

### Description

I visited the developer section to create an NFT, but wanted to check on something in the settings. Opened the ICON to access the general settings, but nothing happened. SIte became unresponsive and error occurred

![image](https://user-images.githubusercontent.com/77154511/216900597-84d98b98-3d6f-4e77-bc34-9eb605a28ead.png)

### Expected behaviour

Opening the settings page

### Actual behaviour

Wallet frozen

### Can the issue reliably be reproduced?

No

### Steps to reproduce the issue

Go to developer section
Click on the profile icon
Click on "settings"

### Operating System

Windows

### Diagnostics

```shell
platform: win32
platformVersion: 10.0.22621
platformArchitecture: x64
cpuCount: 16
totalMem: 16236.1 MB
freeMem: 6026.5 MB
```

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

Non-responsive

### Error Messages

App Version: 2.1.0-alpha-4

platform: win32
platformVersion: 10.0.22621
platformArchitecture: x64
cpuCount: 16
totalMem: 16236.1 MB
freeMem: 6026.5 MB

Error Type: [Render Context] Error

TypeError: Cannot read properties of undefined (reading 'lockScreenTimeoutInMinutes')
    at file:///C:/Program%20Files/Firefly%20Shimmer%20-%20Alpha/resources/app.asar/public/build/index.js:2:2423944
    at file:///C:/Program%20Files/Firefly%20Shimmer%20-%20Alpha/resources/app.asar/public/build/index.js:2:2163440

### Error Logs

```shell
empty
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MarkNerdi** [comment]
@Phyloiota Can you constistently reproduce that on your profile? So will it always occur if you go to "Dev" -> "Settings"?

**Comment by Phyloiota** [comment]
Hey Mark, sadly not, it only appeared the first time i did this and i have not been able to reproduce it since then...
