### ISSUE TITLE
[Bug report]: Error when selecting maximum voting power

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#5771]
### Platform

Desktop

### Version

Alpha 4

### Description

After adding proposals, I wanted to start voting, i added all available balance as voting power via the slider, while pushing confirm, and error appears 
![image](https://user-images.githubusercontent.com/77154511/216905409-f01ec788-722a-49db-a013-42af6fdae2e4.png)

Strangely, maybe 1 minute later i pushed confirm again in the same window (hadn't closed or changed anything) and it worked, though, i did not get a confirmation on the action to establish my voting power. The "wheel kept turning and turning.

After around 5 minutes i closed the wallet, Opened and entered the profile again. The voting power was not established and no voting tx can be found in the activities.

I had maybe 3 minutes before the attempt to establish voting power received tokens back that i did send with an expiration period, maybe that's the reason for the 20 missing tokens in the screenshot.

This was the tx, you see the expiration time was 4 minutes before the error, so the tokens should have been already back in the Wallet
![image](https://user-images.githubusercontent.com/77154511/216906359-41732607-a120-4df8-b349-2e8f6fe040ea.png)
This is the tx with the expiration time https://explorer.shimmer.network/testnet/transaction/0x11e08241d5f592ac74c36952fff0f6a5920ff3302620bdd7dddb24b384df4364

ADD ON:
I wanted to reproduce, i did send 5 SMR with short expiration. In the expiration time i tried to start managing my voting power. Clicking confirm gives me the same error, still 20 SMR are missing - see recording 

https://user-images.githubusercontent.com/77154511/216908246-7c7f3f8a-2648-43ff-bc96-022309b12896.mp4

This is my address in the explorer. Here i have spendable balance 374 SMR, while Firefly shows 394 SMR
rms1qrr5l6ka6fnjtfcqw3sgfwvssevwkm43l45ycdckjzspzd3pg4pecw6letc
![image](https://user-images.githubusercontent.com/77154511/216908893-84afc49b-ba90-4407-b743-d26759a87259.png)

### Expected behaviour

shown available voting power should be able to set as max

### Actual behaviour

error

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Diagnostics

```shell
--
```

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

Infinite loading symbol

### Error Messages

Mon, 06 Feb 2023 07:01:22 GMT
client: insufficient amount: found 378892800, required 399343200

Mon, 06 Feb 2023 07:01:11 GMT
client: insufficient amount: found 378892800, required 399343200

### Error Logs

```shell
Mon, 06 Feb 2023 07:01:22 GMT
client: insufficient amount: found 378892800, required 399343200

Mon, 06 Feb 2023 07:01:11 GMT
client: insufficient amount: found 378892800, required 399343200
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tuditi** [comment]
Fixed by this: https://github.com/iotaledger/iota.rs/pull/1582
