### ISSUE TITLE
[Bug report]: Incorrect Proposal overview

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#5772]
### Platform

Desktop

### Version

Alpha 4

### Description

2 Issues here.

Issue 1:

I voted on proposals. TX are confirmed and show up in explorer and history

Opening the Wallet, logging in and looking in Governance does not show me that i vote on proposals:

Those are my votes
![image](https://user-images.githubusercontent.com/77154511/216915133-2f4cd2db-ea0f-425f-b88e-31192d01914c.png)

This is the governance overview:
![image](https://user-images.githubusercontent.com/77154511/216915254-e69c9e26-0a00-41be-aad3-2e79c8b010d7.png)

It takes around 2 - 3 minutes until this view changes and shows the actual participation
![image](https://user-images.githubusercontent.com/77154511/216915549-4c13df32-f499-4823-b4d4-eab8d562c25b.png)

Issues 2:

The Proposal count is wrong:
Here it says Total proposals 8, while i have only uploaded 7 to this Wallet, i have uploaded 8 to the other wallet. If Wallets are really separated it should be enforced also in this overview
![image](https://user-images.githubusercontent.com/77154511/216915834-61ef1721-d5bc-4e98-8592-58bc7a6527fe.png)

### Expected behaviour

faster loading, correct display of the count

### Actual behaviour

--

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Diagnostics

```shell
--
```

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

--

### Error Logs

```shell
--
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tuditi** [comment]
May be fixed by https://github.com/iotaledger/firefly/issues/5784

**Comment by Tuditi** [comment]
Should be fixed with the new wallet.rs release, we'll keep it open just in case it resurfaces.

**Comment by Tuditi** [comment]
Due to the latest refactors, I'll close this, since we fixed the correct display of the counts and optimized loading speeds.
