### ISSUE TITLE
[Bug report]: Transaction report not complete

### ISSUE THREAD

**Issue by Knopfbock** [iotaledger/firefly#5807]
### Platform

Desktop

### Version

1.7.0

### Description

Ther are Errors in the documentation of my trades. On Firefly the are signed as 0 Mi . On the sonnaverse side its ok an the transaktion correkt noticed. Pleas fix it , my Taxreport have to be save.
![firefly 1](https://user-images.githubusercontent.com/121851717/217515023-f0107e31-f611-415c-b875-b8b969077fc0.JPG)
![soonlabs 1](https://user-images.githubusercontent.com/121851717/217515332-d44ce73e-e8c6-49a8-9c94-a071730fd9ad.JPG)

Here are the Fireflytransaction and the soonlabs Transaction to check.

### Expected behaviour

fix the transactionprotokoll

### Actual behaviour

Error on Transactionreport. 

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

open export transaction
check transaction

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

NO everything is fine

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
Hi, is this still an issue in the latest version?

**Comment by begonaalvarezd** [comment]
The network was recently upgraded, please download the latest firefly iota version 2.0.2. The new version does not have the CSV export feature added, will close the issue because this is tracked in a different task
