### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by javitechjkd** [iotaledger/firefly#5810]
### Platform

Desktop

### Version

1.7.1

### Description

5:43:35.631 › Update for version 1.7.1 is not available (latest version: 1.7.1, downgrade is disallowed).
Error occurred in handler for 'keychain-set': [Error: The name org.freedesktop.secrets was not provided by any .service files]

### Expected behaviour

Open wallet

### Actual behaviour

error and freeze

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1.Execute Firefly
2.Try to restore a ledger wallet
3.Write NEW PIN twice.
2.Freeze

### Operating System

Linux

### Diagnostics

```shell
5:43:35.631 › Update for version 1.7.1 is not available (latest version: 1.7.1, downgrade is disallowed).
Error occurred in handler for 'keychain-set': [Error: The name org.freedesktop.secrets was not provided by any .service files]
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Previously staked

### Crash Status

None of the above

### Error Messages

5:43:35.631 › Update for version 1.7.1 is not available (latest version: 1.7.1, downgrade is disallowed).
Error occurred in handler for 'keychain-set': [Error: The name org.freedesktop.secrets was not provided by any .service files]

### Error Logs

```shell
5:43:35.631 › Update for version 1.7.1 is not available (latest version: 1.7.1, downgrade is disallowed).
Error occurred in handler for 'keychain-set': [Error: The name org.freedesktop.secrets was not provided by any .service files]
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
Hi, is this still an issue in the latest version?

**Comment by javitechjkd** [comment]
No answers

**Comment by Dimfred** [comment]
For me yes
