### ISSUE TITLE
[Bug report]: Merging or staking with wrong Ledger gives unclear error

### ISSUE THREAD

**Issue by antonionardella** [iotaledger/firefly#5817]
### Platform

Desktop

### Version

1.7.1

### Description

If the IOTA app is open on the Ledger with a different mnemonic than the one managing the private key of the profile a non-specific error message is given and the user is stuck

### Expected behaviour

Receive a message that tells that the Ledger app is open, but non with the correct mnemonic/seed for this profile

### Actual behaviour

Non-specific error is given  "Something went wrong" with no additional information to solve the issue.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Merge stake of recently received tokens
2. IOTA app open on Ledger with different mnemonic as the one managing the private key of that profile
3. Clic the _Confirm_ button to start signing the transaction
4. Non-specific error appears

### Operating System

Linux

### Diagnostics

```shell
Version 1.7.1
Language: en
Currency: USD
Node selection: Automatic
Platform: linux
Platform Version: 5.15.89-1-MANJARO
Platform Architecture: x64
CPU Count: 24
Total Memory: 64231.6 MB
Free Memory: 19387.0 MB
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Actively staking

### Crash Status

None of the above

### Error Messages

![image](https://user-images.githubusercontent.com/7383572/217657862-49d71bdf-c8bd-4fab-8e7c-70e5b159a006.png)

### Error Logs

```shell
The error log is empty.
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marc2332** [comment]
Hi, is this still an issue in the latest version?

**Comment by begonaalvarezd** [comment]
Closing issue because staking is not in the latest version
