### ISSUE TITLE
[Bug report]: Download firefly 1.7.1

### ISSUE THREAD

**Issue by ulflipinski** [iotaledger/firefly#5843]
### Platform

Desktop

### Version

1.7.0

### Description

Hallo,
ich habe das prestaking 5 von Assembly knapp verpasst.
nun möchte ich am Staking teilnehmen und wollte Firefly auf 1.7.1. upgraden, aber es wird immer nur 1.7.0 angeboten
was kann ich tun ?
vielen Dank

### Expected behaviour

ich möchte firefly 1.7.1 downladen

### Actual behaviour

ich kann firefly 1.7.1 nicht downladen, es wird mir nicht angeboten

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JannemanDev** [comment]
You can find it here https://firefly.iota.org/
Also mentioned in the annoucment https://blog.iota.org/iota-staking-for-assembly-round-5/

**Comment by ulflipinski** [comment]
Hallo, Yesterday afternoon it doesnt work at firefly.iota.org, but 2 hours before i could load firefly1.7.1Thank you--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 12.02.23, 18:19 schrieb JannemanDev ***@***.***>:

   
  You can find it here https://firefly.iota.org/ Also mentioned in the annoucment https://blog.iota.org/iota-staking-for-assembly-round-5/
