### ISSUE TITLE
[Bug report]: Removal of closed proposals impossible

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#5867]
### Platform

Desktop

### Version

Alpha 6

### Description

I wanted  to start removing the many closed proposals from the dashboard

A popup appears that wants me to "You must stop voting on a proposal to remove it"

But i am not voting on this proposal anymore (It was closed a long time ago.

![image](https://user-images.githubusercontent.com/77154511/218992169-aa6bc02e-4205-4c00-896e-1f712faa80b0.png)

I wanted to check if its possible to remove it once i have stopped voting on the active proposals, so i reduced voting power to 0.
Confirming this action did lead to endless loading and not confirming the action, so i aborted it and logged out of the profile. 
I tried to log in again, now the "Initializing Account manager" got stuck and after a couple of seconds, i am back at the login screen with the message "something went wrong."

![image](https://user-images.githubusercontent.com/77154511/218993483-7ef2ac83-eec2-4004-aa38-36be38918ea8.png)

https://user-images.githubusercontent.com/77154511/218993885-5c76ebd5-283e-49a5-ae62-668ce8be3af2.mp4

### Expected behaviour

remove the proposal no matter if i am voting on active proposal

### Actual behaviour

Not possible, error and not able to access the account anymore

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Diagnostics

```shell
--
```

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

something went wrong

### Error Logs

```shell
Wed, 15 Feb 2023 09:51:42 GMT
Generic: undefined

Wed, 15 Feb 2023 09:47:57 GMT
Generic: undefined

Wed, 15 Feb 2023 09:34:01 GMT
voting: No unspent voting output found

Tue, 14 Feb 2023 12:19:42 GMT
client: no password has been supplied, or the key has been cleared from the memory

Tue, 14 Feb 2023 11:36:58 GMT
client: no password has been supplied, or the key has been cleared from the memory

Tue, 14 Feb 2023 11:35:24 GMT
Generic: undefined

Tue, 14 Feb 2023 11:34:52 GMT
Generic: undefined

Tue, 14 Feb 2023 11:34:28 GMT
Generic: undefined
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Phyloiota** [comment]
Update, also once i have stopped voting on all active proposals i cannot remove old closed proposals, same tooltip message shows up

**Comment by Tuditi** [comment]
Did you do this on a profile that has been restored previously?

**Comment by begonaalvarezd** [comment]
Hi, is this still an issue in the latest version?
