### ISSUE TITLE
[Task]: Improve fetching governance events after profile recovery

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5870]
### Task description

After recovery, it's possible that FF doesn't have the necessary information to display a proposal. So if an event has been fetched from an output for which FF doesn't know the node URL, we query the user to add the node URL again or remove it from their output.

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by MarkNerdi** [comment]
Probably fixed in this PR https://github.com/iotaledger/wallet.rs/pull/1867/
