### ISSUE TITLE
Permanently syncing and logout doesn't work

### ISSUE THREAD

**Issue by jkl2e** [iotaledger/firefly#589]
## Issue description

After sending some Funds from Account 1 to Account 2, the balance of Account 1 was negativ.
Try to logout to check the other account... Logout Button does not work.

## Wallet version

0.2.1

## System specification

macOS 11.2.2

## Is it a repeatable issue?

not sure

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. install firefly
2. finish init process
3. request tokens from faucet
4. Logut (button is working fine)
5. create secound account
6. Copy RX-Adress from second account
7. Logout from 2. account
8. Login into firs account
9. send some funds to copied address from account 1 

## Expected behaviour

Balance ist correct
when Logout button is pressed, the user loged out

## Actual behaviour

Balance is -2 Mi
Logout button doesn't work

## Errors
<img width="1280" alt="Bildschirmfoto 2021-03-21 um 23 43 32" src="https://user-images.githubusercontent.com/71429780/111923544-1401e100-8aa0-11eb-8fa8-35944645f9c5.png">

<img width="1279" alt="Bildschirmfoto 2021-03-21 um 23 50 36" src="https://user-images.githubusercontent.com/71429780/111923612-4dd2e780-8aa0-11eb-8c23-ae02607a0b4e.png">

**Comment by cvarley100** [comment]
Fixed in 0.3.0
