### ISSUE TITLE
[Task]: Fix revote doesn't show if stronghold was originally locked when initiating manage vote

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#5894]
### Task description

If you login to a profile that is already voting and stronghold is locked, if you go to manage vote - after the voting power increase or decrease transaction the revote popup does not open. However, if you start the flow with stronghold unlocked the revote popup correctly opens.

### Requirements

Fix the issue

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
I couldn't reproduce the issue anymore.
