### ISSUE TITLE
[Task]: Fix managing voting power twice in a row while voting, does not open the revote popup the second time

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#5896]
### Task description

If you successfully manage your voting power once and then revote, if you go to manage it again in the same session then the second time you go through the flow the revote popup does not open which is incorrect.

### Requirements

Revote should correctly open if you manage voting power and are already voting on a proposal no matter what.

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
I couldn't reproduce this issue anymore.
