### ISSUE TITLE
[Task]: Implement an export function for the TX data

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#5906]
### Task description

Implement the same function we have in IOTA Firefly so users are able to export their tx data from the Wallet (mainly to do their taxes, etc)

### Requirements

see IOTA Wallet

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
We believe the ideal place to export tx data is the explorer, we are teaming up with the explorer team to improve this whole reporting, but we believe the wallet is not the place as firefly is not connected to permanodes plus the tx history reporting should be public information accesible from the explorer
