### ISSUE TITLE
[Task]: Debug get_participation_overview occassionally returning an empty array

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#5913]
### Task description

Some users reported being unable to vote. This might happen when wallet.rs returns an empty array.

Wallet.rs logs
[wallet-2023-02-17-10-28.log](https://github.com/iotaledger/firefly/files/10767590/wallet-2023-02-17-10-28.log)
[wallet-2023-02-17-10-21.log](https://github.com/iotaledger/firefly/files/10767591/wallet-2023-02-17-10-21.log)
[wallet-2023-02-17-10-25.log](https://github.com/iotaledger/firefly/files/10767592/wallet-2023-02-17-10-25.log)

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by MarkNerdi** [comment]
Probably fixed with this PR https://github.com/iotaledger/wallet.rs/pull/1867
