### ISSUE TITLE
[Task]: Update svelte-picker + use correct locale

### ISSUE THREAD

**Issue by MarkNerdi996** [iotaledger/firefly#5915]
## Description
Depending on the users language we want to display the datepicker in their corresponding language.
Currently we use `svelty-picker v1.3`. With this version, only english is supported. Therefore we need to update this

## Requirements
 - [x] Update svelty-picker
 - [x] Use correct locale

**Comment by MarkNerdi** [comment]
Wait for this PR to be merged into svelty picker https://github.com/mskocik/svelty-picker/pull/85

**Comment by Tuditi** [comment]
Added a couple of locales in this PR: https://github.com/mskocik/svelty-picker/pull/86

Will open a new one with all the remaining locales we support in FF if this one gets merged.
