### ISSUE TITLE
[Bug report]: ASMB not showing on Firefly, not able to stake IOTA

### ISSUE THREAD

**Issue by Ciprian9229** [iotaledger/firefly#5920]
### Platform

Desktop

### Version

1.7.1

### Description

I am not able to see my ASMB balance and not able to stake my IOTA for ASMB.

When I open Firefly an error pops on the right low corner that say : Something went wrong

### Expected behaviour

To see my ASMB balance and be able to stake my IOTA for ASMB as I am losing ASMB due to this issue

### Actual behaviour

I am not able to see my ASMB balance and not able to stake my IOTA for ASMB.

When I open Firefly an error pops on the right low corner that say : Something went wrong

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Open Firefly
An error pops out Stating: "Something went wrong"

### Operating System

Windows

### Diagnostics

```shell
Version 1.7.1
Language: en
Currency: USD
Node selection: Automatic
Platform: win32
Platform Version: 10.0.19044
Platform Architecture: x64
CPU Count: 8
Total Memory: 14269.3 MB
Free Memory: 5079.8 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Error Messages

![Firefly Error](https://user-images.githubusercontent.com/120144772/219954218-b694035d-bf8f-4793-a088-2da7252b6565.JPG)

This issue pops out and I cannot see any balance of my previous staked ASMB and I am not able to stake now IOTA for ASMB.

![image](https://user-images.githubusercontent.com/120144772/219954275-f1c44a90-c5e8-4ee4-bb1b-fffa1a0b80b5.png)
![image](https://user-images.githubusercontent.com/120144772/219954293-4a0bae5c-dc21-45f2-9a5a-db0e0a2da4fc.png)

### Error Logs

```shell
The error log is empty.
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ciprian9229** [comment]
Please solve this ASAP as I am losing ASMB due to this issue!

**Comment by Ciprian9229** [comment]
Please solve this ASAP as I am losing ASMB due to this issue!

**Comment by begonaalvarezd** [comment]
Hi, I hope your issue solved in the recent updates we did 🙏🏼 
Staking events have finished so I'll close the issue for now
