### ISSUE TITLE
[Task]: Fix surplus amount not showing when following a deep link

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#5941]
### Task description

Soonaverse raised a bug in the latest beta, where the surplus is not showing on the send confirmation page when the user follows a deep link with native tokens and a surplus.

### Requirements

- Fix issue so that the surplus amount is displayed in the send confirmation form

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by adamunchained** [comment]
@nicole-obrien - FYI this seems to work correctly in Firefly Shimmer 2.0.1 and it shows but got broken in alpha.
