### ISSUE TITLE
Operation timed out errors during fund transfer

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#599]
## Issue description

during the internal transfer between accounts i had 4 times (2 times on fresh created profile, 2 times on imported profile) an error message "something went wrong" and the transfer was not initiated. First try - error, second try - error, third try - success normal tx process.
This happened both times in the "first session" of the profile, so after creation, faucet fund receiving, sending back and forth a couple of times, but before the profile was logged out / App was closed. Until now not happened on a profile after a first log out and relog in.

## Wallet version

Firefly v0.2.1 (0.2.2 actually)
Platform: win32
Platform Version: 10.0.19041
Platform Architecture: x64
CPU Count: 4
Total Memory: 6082.5 MB
Free Memory: 1838.0 MB

## Is it a repeatable issue?

not really, happened in 35 tx 4 times now - obviously connection problem to the nodes

## Errors

[operation timed out.txt](https://github.com/iotaledger/firefly/files/6180157/operation.timed.out.txt)

**Comment by cvarley100** [comment]
@laumair is this due to too restrictive timeouts?

**Comment by Phyloiota** [comment]
> @cvarley100 No I cannot say for certain that it happened because of timeouts. Is there an error log @Phyloiota ?

sorry no error log, just the one i posted above, 
[operation.timed.out (1).txt](https://github.com/iotaledger/firefly/files/6265778/operation.timed.out.1.txt)
closing this now as i never had that issue showing up again...
