### ISSUE TITLE
[Task]: 4. Add warning hint to pin entry page when stronghold is out of date

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#6008]
### Task description

When a user selects a profile that is not using the latest stronghold version, we should add a warning hint to the enter pin view

### Requirements

- Add warning hint
- Add locales

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jeeanribeiro** [comment]
🚫 blocked 
PR with mocked data is opened as a draft, waiting for #6006 to get done and then the working condition can be added to #6085
