### ISSUE TITLE
[Task]: 6. Add update stronghold view and UI to update stronghold router

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#6048]
### Task description

After the user has entered the pin from a profile not using the latest stonghold, they will get routed to the stronghold migration process which starts with the view “update stronghold”. 

### Requirements

- Create view with all necessary UI components
- Add view into the stronghold router

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jeeanribeiro** [comment]
🚫 blocked
PR with mocked data is opened as a draft, waiting for #6006 and #6010 to get done and then the working conditions can be added to https://github.com/iotaledger/firefly/pull/6087
