### ISSUE TITLE
[Task]: 15. Add update stronghold router to import stronghold onboarding claim flow

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#6057]
### Task description

By this point we should have already created the update stronghold flows and router, so we can just add this into the claim flow where the user is importing a stronghold

### Requirements

Add stronghold update router into the onboarding claim flow and adjust necessary logic

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by MarkNerdi** [comment]
closed in https://github.com/iotaledger/firefly/pull/6115
