### ISSUE TITLE
[Task]: 7. Add logic to update stronghold view

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#6074]
### Task description

Now that we have the UI for updating a stronghold we need to add the logic to perform this action. Involving a call to the wallet.rs to to migrate the stronghold snapshots.

### Requirements

- Add logic to migrate stronghold with wallet.rs
- Add logic to update profile data to state the new version of stronghold for the profile

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by amadeu2** [comment]
This logic on desktop is copying / deleting the file with Electron at import flow.
Currently, on mobile, we use the Filesystem Capacitor plugin to copy the file to the app's internal folder. We'll also need to make sure to delete the temporary file once it's used, as currently this file is deleted on the next import.
