### ISSUE TITLE
[Bug report]: Currency Conversion

### ISSUE THREAD

**Issue by Buddh1n1** [iotaledger/firefly#6083]
### Platform

Desktop

### Version

1.7.1 and earlier

### Description

Hi,
setting the currency in firefly settings to something else than USD (confirmed with EUR) will show wrong token price (in that currency) and balance.
Most likely it is pulling IOTA/EUR from coingecko, assuming it just pulled IOTA/USD and convert again according to USD/EUR rate.

### Expected behaviour

Show correct price in different currencies.
![correct](https://user-images.githubusercontent.com/126293269/223241325-0e29f3bc-fdcf-462c-8e28-d433f2fc2730.png)

### Actual behaviour

Shows wrong price in different currencies.
![wrong](https://user-images.githubusercontent.com/126293269/223241379-de34e163-3fab-4de6-8343-f8cb83440def.png)

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Set Firefly currency in settings to USD (and restart Firefly if it was set to a different currency before)
2. Check token price in EUR in wallet (top right)
3. Set Firefly currency in settings to EUR.
4. Check token price in EUR in wallet (top right)

### Operating System

Mac

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Actively staking

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
A new version with an improved fiat implementation will be released soon
