### ISSUE TITLE
[Bug report]: Insufficient funds when claiming 2+ transactions

### ISSUE THREAD

**Issue by antonionardella** [iotaledger/firefly#6096]
### Platform

Desktop

### Version

2.1.0-beta-1

### Description

For testing a number of NFTs are sent to an address without expiration.
Trying to claim 2 transactions work, as soon as the third or fourth claim is tried the error `Generic: Insufficient funds to cover the storage deposit` is shown

It is possible to normally claim the other transactions after the previous transactions are claimed

### Expected behaviour

Either the claim button is greyed out until the previous 2 are claimed or a different error message

### Actual behaviour

`Generic: Insufficient funds to cover the storage deposit` is shown. Which is technically incorrect since the wallet has sufficient funds.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Send a number >3 NFT transactions to a wallet
2. Try to claim all 3 or more at the same time
3. Error message is displayed

### Operating System

Linux

### Diagnostics

```shell
Version 
Language: en
Currency: undefined
Node list: https://api.testnet.shimmer.network
Platform: linux
Platform Version: 5.15.94-1-MANJARO
Platform Architecture: x64
CPU Count: 24
Total Memory: 64231.6 MB
Free Memory: 49003.4 MB
```

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

![image](https://user-images.githubusercontent.com/7383572/223474132-7d702166-d8ea-474c-aaa9-68fd63d25315.png)

### Error Logs

```shell
Tue, 07 Mar 2023 15:34:10 GMT
Generic: Insufficient funds to cover the storage deposit

Tue, 07 Mar 2023 15:34:09 GMT
Generic: Insufficient funds to cover the storage deposit

Tue, 07 Mar 2023 15:34:08 GMT
Generic: Insufficient funds to cover the storage deposit

Tue, 07 Mar 2023 15:33:45 GMT
Generic: Insufficient funds to cover the storage deposit
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeeanribeiro** [comment]
@antonionardella does this keeps happening in the latest versions?

**Comment by Tuditi** [comment]
This is a limitation of the protocol. Let's imagine the following scenario:

1. You create a brand new profile that owns one output with 1000 SMR.
2. This profile receives 2 NFT outputs that have to be claimed both.
3. When you claim the first NFT you spend your output that leaves you with 0 outputs for the moment.
4. If you then immediately claim your second NFT then you would receive the error message you experienced.

IIUC, you're in a similar situation I described above. To educate the user better, we changed the error message to:

`Insufficient funds to cover the storage deposit. If you have ongoing transactions, please wait for their confirmation.`

What do you think about this approach?
