### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by Lyraua** [iotaledger/firefly#6122]
### Platform

Desktop

### Version

1.7.1

### Description

Firefly Wallet - Click Receive Funds Button, Error Message " Something Went Wrong"

Wallet is Connected and IOTA app opened
![Screenshot 2023-03-09 151238](https://user-images.githubusercontent.com/127444653/224144043-f65548dd-79af-40dd-866c-adca768c8102.png)

### Expected behaviour

A wallet address to be generated so I could deposit funds.  I tried on both a staked wallet and unstaked walllet. 

### Actual behaviour

ERROR MESSAGE - SOMETHING WENT WRONT

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Click Wallet
Click Receive Button
Click Generate Address Button
Open IOTA app on Ledger Device
Error message - Something went wrong

### Operating System

Windows

### Diagnostics

```shell
Version 1.7.1
Language: en
Currency: USD
Node selection: Automatic
Platform: win32
Platform Version: 10.0.22621
Platform Architecture: x64
CPU Count: 12
Total Memory: 16095.1 MB
Free Memory: 8104.8 MB
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Actively staking

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
Hi, is this still an issue in the latest version?

**Comment by begonaalvarezd** [comment]
We recently upgraded the network to stardust, please download the new compatible firefly app 2.0.2

**Comment by Lyraua** [comment]
Hi, well Assembly staking is completed so I would not be able to test.

Is there something specific you want me to test or verify?

Also on a side note am very confused with the announcement of Bloom. Firefly is such a great interface. Is Bloom replacing it? There are already 20 apps named Bloom so that is also confusing.

**Comment by begonaalvarezd** [comment]
I'll close the issue since the staking events have finalized for now. Thank you very much for replying so fast

> Also on a side note am very confused with the announcement of Bloom. Firefly is such a great interface. Is Bloom replacing it? There are already 20 apps named Bloom so that is also confusing.

Bloom is not replacing Firefly, Bloom is a new wallet forked from Firefly, its a spinoff, developed by part of the original Firefly team. In the IOTA Foundation we will continue developing Firefly.
You can ask Bloom more questions in their discord, you can find their discord and more information in the official announcement post https://blog.iota.org/introducing-bloom-former-firefly-team-to-launch-new-wallet/.
