### ISSUE TITLE
[Task]: 1. Update wallet.rs to latest version

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#6135]
### Task description

Update the [wallet.rs](http://wallet.rs/) version to the latest version that includes the updated stronghold version and APIs to perform the stronghold snapshot migration.

### Requirements

- Update [wallet.rs](http://wallet.rs/)
- Update interfaces that have changed

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
In chrysalis, the wallet-rs version is pointed by a github commit id/hash or a branch. So as soon as the code is added to the repository, we could trigger this issue
