### ISSUE TITLE
error "this is greater than your available balance"

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#620]
## Issue description

fresh setup installation, first profile created, receiving funds from faucet on acc1 (20Mi) and acc2 (10Mi)
- attempt to sent from acc2 to the receiving address of acc1 
- try to send 5  Mi from a 10 Mi balance 
- error appears "This is greater than your available balance"
before i initiated the transaction the only things i did was:
 - deaktivating notifications
 - activating deep links
 

## Wallet version

Firefly v0.2.1
Language: en
Currency: USD
Node settings: Automatic node selection
Platform: win32
Platform Version: 10.0.19041
Platform Architecture: x64
CPU Count: 4

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

Describe what actually happens.

## Errors
This are the errors in Wallet error log after resterting the wallet:
Mon, 22 Mar 2021 15:35:54 GMT
ClientError: `No synced node available`

Mon, 22 Mar 2021 15:18:55 GMT
InsufficientFunds: insufficient funds

Mon, 22 Mar 2021 15:15:04 GMT
InsufficientFunds: insufficient funds

Mon, 22 Mar 2021 15:12:36 GMT
InsufficientFunds: insufficient funds

Mon, 22 Mar 2021 15:12:08 GMT
InsufficientFunds: insufficient funds
Mon, 22 Mar 2021 15:35:54 GMT
ClientError: `No synced node available`

Mon, 22 Mar 2021 15:18:55 GMT
InsufficientFunds: insufficient funds

Mon, 22 Mar 2021 15:15:04 GMT
InsufficientFunds: insufficient funds

Mon, 22 Mar 2021 15:12:36 GMT
InsufficientFunds: insufficient funds

Mon, 22 Mar 2021 15:12:08 GMT
InsufficientFunds: insufficient funds

[console available balance errors.txt](https://github.com/iotaledger/firefly/files/6183383/console.available.balance.errors.txt)

<img width="958" alt="greater than available" src="https://user-images.githubusercontent.com/77154511/112015200-90f78e00-8b66-11eb-9c0d-d520a05ee35b.png">

https://user-images.githubusercontent.com/77154511/112015561-e3d14580-8b66-11eb-95a0-44fcb935e312.mp4

**Comment by JM0unir** [comment]
Hi, encountered same issue while trying to send funds internally. Error logs attached :)

I managed to do an internal transfer by setting up a new profile.

Firefly v1.3.2
Language: en
Currency: USD
Node selection: Manual
Platform: win32
Platform Version: 10.0.19043
Platform Architecture: x64
CPU Count: 12
Total Memory: 32718.7 MB
Free Memory: 22599.3 MB

[issue_620_error logs_20210104.txt](https://github.com/iotaledger/firefly/files/7810065/issue_620_error.logs_20210104.txt)
