### ISSUE TITLE
[Task]: Enable in-app updates for Windows

### ISSUE THREAD

**Issue by nicole-obrien** [iotaledger/firefly#6213]
### Task description

Currently we have in-app updates turned off for windows, this is because on windows the electron updater dependency does not walk the certificate chain correctly to know if the update is authenticated. @rajivshah3 has been creating a package to do this on ourside.

### Requirements

TBD

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
Blocked by https://github.com/iotaledger/firefly/issues/7655, once we upgrade and patch we can enable
