### ISSUE TITLE
Total balance doesnt prefill when trying to delete an account, if you already are in the send view

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#627]
## Issue description

When you try deleting an accounts with balance, you are asked to move your funds. The normal behavior is that the total balance of your account gets pre-filled in the "Amount" input, but if you already are in the send view, this doesnt happen.  

## Wallet version

Which version of wallet are you using?

0.3.0

## System specification

Ubuntu 18.04

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Have an account with balance
2. Click on the account
3. Click on Send funds
4. Click on the dotdotdot > remove account
5. Amount doesnt change

## Expected behaviour

Step 5: the amount should be pre-filled with the total balance, as it happens in any other circumstance. 

## Actual behaviour

Amount doesnt change

**Comment by obany** [comment]
Fixed
