### ISSUE TITLE
[Task]: Fixes on shared folder to allow a clean mobile compilation

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#6275]
Currently when webpack is compiling the mobile folder, desktop components are also compiled in the same step, showing unexpected desktop warnings and causing the desktop components to be included in the mobile compiled code, bloating the final js/css files, and also making the compilation slower.

- The file `login-router.ts` on shared folder is importing desktop features file. Add `features` to Platform.

- Here's imported a desktop component:  https://github.com/iotaledger/firefly/blob/develop/packages/shared/components/molecules/AssetList.svelte#L4

By making just these two changes we can avoid building desktop components on mobile devices.

**Comment by amadeu2** [comment]
Let me check it, I remember there was something realed to this issue

**Comment by begonaalvarezd** [comment]
Mobile also has its own in `packages/mobile/components/AssetList.svelte` and it will also refactored (you will see this happens for almost all the componentes we have in mobile, there is a duplicate in shared that is for desktop), there are lots of components that will be refactored and moved to the specific folder, you can see the list [here](https://github.com/iotaledger/firefly/issues/5934), the list is not 100% complete yet though.
There are lots of components and files inside shared lib that are are desktop only, we need to refactor all of them little by little. The tasks are being moved to https://github.com/iotaledger/firefly/milestone/1
