### ISSUE TITLE
Potential issue with glibc on Linux

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/firefly#628]
## Issue description

Users using Ubuntu 18.04 may see a white screen upon launching. The DevTools will show `version 'GLIBC_2.29' not found`

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch): 0.3.0

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible) Ubuntu 18.04

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Launch the app

## Expected behaviour

App launches

## Actual behaviour

White screen

## Errors

`version 'GLIBC_2.29' not found`

**Comment by miili** [comment]
Same here, Debian 10 Buster.

![image](https://user-images.githubusercontent.com/4992805/112048446-b37dad00-8b4e-11eb-9825-993c8e2794f3.png)

**Comment by miili** [comment]
Please build the AppImage against an old version of glibc.

https://unix.stackexchange.com/a/149627

**Comment by Edupredon** [comment]
The last version of trinity worked on debian 10, I believe it is possible to adjust firefly. Thanks.
