### ISSUE TITLE
Missing error message when invalid token value is being transferred. 

### ISSUE THREAD

**Issue by adamkundrat** [iotaledger/firefly#632]
## Issue description
LOW priority although important to increase usability.

Missing error message when invalid token value is being transferred. User just unable to proceed but might get confused why he is unable.

## Wallet version
0.3.0

## System specification
Mac Big Sur

## Is it a repeatable issue?
Yes

## Steps To reproduce the issue

1. Go in to the wallet
2. Click send tokens
3. Enter 0.0001 Kiota

## Expected behaviour
User get warned that less than 1 IOTA can not be transferred. 

## Actual behaviour
No error, user unable to click send.

**Comment by obany** [comment]
This should be fixed in the next version, please re-open if you still have issues
