### ISSUE TITLE
[Task]: Update Mobile Readme for iOS

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#6328]
### Task description

Add missing requiements for iOS development to Readme:
- `CocoaPods` https://guides.cocoapods.org/using/getting-started.html#installation
- Add Xcode instructions https://discordapp.com/channels/397872799483428865/930250781649690634/1092506363168563250
- Update `packages/mobile/public/index.html` with `connect-src 'self' https://* ws://*;`
- if using iOS > 16, you need to add a patch to be able to use the safari inspector dev tools https://github.com/ionic-team/capacitor/issues/6441#issuecomment-1491092025
- Running the iOS simulator on a M1/M2 chip, needs Rosetta mode to work

### Requirements

Update readme 

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by amadeu2** [comment]
Here's a complete list of requirements:
https://capacitorjs.com/docs/getting-started/environment-setup#ios-requirements

Also on Android we're not mentioning the Android SDK
