### ISSUE TITLE
[Bug report]: Can not stake Soon

### ISSUE THREAD

**Issue by Spartacus94** [iotaledger/firefly#6340]
### Platform

Desktop

### Version

2.0.0

### Description

I tried several times with every single possibility in the settings to send Soon to Soonaverse to stake. It never worked. 2 times, I never got back my Soon I sent. It was just 20 Soon in total, so lets not consentrate on that. I just want to stake.
I want to send 10 Soon
I got on my wallet 11 Soon, and 2.850,5908 Shimmer

### Expected behaviour

Get the process of sending Soon from Shimmer done

### Actual behaviour

get an error

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

I can reproduce yes. 
1.Go to soonaverse, stake your token
2.Hit the linked Firefly, or copy paste the adress, tried both
3.Send soon, with every single possibility with the deposit and expirering date and so on

### Operating System

Windows

### Diagnostics

```shell
Version 
Sprache: de
Währung: EUR
Node-Liste: https://api.shimmer.network
Plattform: win32
Plattformversion: 10.0.19045
Plattform-Architektur: x64
CPU-Anzahl: 8
Gesamtspeicher: 16060.7 MB
Freier Speicher: 2373.4 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

The wallet account doesent have enough native tokens, missing: NativeTokens(BoxedSlicePrefix([NativeToken { token_id:TokenID(0x0884298fe9b82504d26ddb873dbd234a344c120da3a4317d8063dbcf96d356aa9d0100000000),amount: 4000000 }]))`

### Error Logs

```shell
none
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marc2332** [comment]
This doesn't seem like a Firefly issue, is it still happening? Maybe try updating :smile: :v:

**Comment by begonaalvarezd** [comment]
Hi @Spartacus94 , i believe in order to send native tokens to soonaverse you need to gift the storage deposit because they will not cover it, if you have any question about the requirements of soonaverse i would ask directly in their discord app 🙏🏼 
Will close the issue because this is not a problem in the firefly app
