### ISSUE TITLE
[Task]: Implement CSS safe-areas for Android

### ISSUE THREAD

**Issue by amadeu2** [iotaledger/firefly#6345]
There was a known issue with Chrome for Android returning 0 for CSS env safe-area-inset-* variables.
Currently from version 111 seems it's solved https://caniuse.com/mdn-css_properties_custom-property_env_safe-area-inset-bottom

We need to change Android theme to beign able to use the safe areas.

**Comment by kraftjs** [comment]
Waiting for #6342 for improved workflow with safe areas in Android
