### ISSUE TITLE
Translation German <>  English is not possible

### ISSUE THREAD

**Issue by MiKeF05** [iotaledger/firefly#635]
Some of the translations from English to German are not shown. I have chosen the language German but in the settings there are some English sentences. I have attached 2 examples to show.

![Screenshot 1](https://user-images.githubusercontent.com/71659397/112039296-2fbec300-8b44-11eb-9e61-34aada717308.PNG)

![Screenshot 2](https://user-images.githubusercontent.com/71659397/112039299-30575980-8b44-11eb-8b34-f561c4456415.PNG)

**Comment by David-Sat** [comment]
Yes, some titles and descriptions in the settings stay in English when switching languages. I also encountered this with French.

**Comment by MiKeF05** [comment]
Translations from English to German are now available in v0.3.1
