### ISSUE TITLE
[Task]: Show correct EVM address for Ledger profiles

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6366]
### Task description

The user will need to use the Ledger device for generating EVM addresses (at least initially) to display in the network cards.

:no_entry_sign: We need **1)** additional UX since this will require interacting with the Ethereum Ledger app and **2)** to figure out how to connect with the Ethereum Ledger app. 

### Requirements

_TBD_

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
Close as handled in #6600
