### ISSUE TITLE
[Task]: Implement logic to edit a chain

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6370]
### Task description

A user should be able to edit a chain that they've manually added.

### Requirements

_TBD_

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
Blocked until https://github.com/iotaledger/firefly/issues/6377 is closed.
