### ISSUE TITLE
[Task]: Modify destination network dropdown to use manually added networks

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6374]
### Task description

With being able to add networks / chains, a user should be able to select them in the "Destination network" dropdown in the send form. We should also avoid hard-coding alias addresses.

### Requirements

_TBD_

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by nicole-obrien** [comment]
This will be part of the send flow changes so I would close this task as not planned
