### ISSUE TITLE
Unable to use a comma as decimal separator

### ISSUE THREAD

**Issue by d4ytn** [iotaledger/firefly#639]
## Issue description

Firefly will ignore any "," you're typing into the transaction value input field.
To support all countries with different decimal separator standards, you should translate the comma into the dot when typing.

## Wallet version

v0.3.0

## System specification

What is your operating system?

macOS Big Sur 11.2.3

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Simulate a transfer of 0,1 KIOTA to a random address
2. You will be stuck with no separator

## Expected behaviour

I would expect to get my comma input translated into a dot by Firefly seamlessly.

## Actual behaviour

I am left with no decimal separator when using ","

## Errors

-/-

**Comment by 94jaku** [comment]
This should be default behaviour. Vote up.

**Comment by JanOonk** [comment]
Firefly should respect regional settings set by user in the OS.

**Comment by obany** [comment]
This is fixed for the next release, please re-open if you still have issues.

**Comment by Travetown** [comment]
The issue is still there. If I set "German" and "EUR", then the correct comma is displayed as a point. You cannot enter a comma when sending.
