### ISSUE TITLE
[Task]: Fix build scripts for Windows

### ISSUE THREAD

**Issue by jeeanribeiro** [iotaledger/firefly#6394]
## assetgen.sh
- Windows has a native `convert` command so the ImageMagick command is not executed, the `convert` commands need to be changed to `magick convert`
- Windows needs the directories to be have backslash instead of slash
- Windows is not replacing the interpolated string variables with the positional parameters

**Comment by amadeu2** [comment]
I think for windows should be needed to install mingw64 + bash, or WSL. Or maybe make it with nodejs, wdyt?

**Comment by jeeanribeiro** [comment]
> I think for windows should be needed to install mingw64 + bash, or WSL. Or maybe make it with nodejs, wdyt?

I think it would be better to use NodeJS, because it is the tech that most of the team is familiarized with
