### ISSUE TITLE
[Task]: Document deep links for FF iota

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#6409]
### Task description

There is no place to find the deep links for FF v1. Users have been requesting this information lately.

A deep link for FFv1 looks like this:

iota://wallet/send/iota1qrla2afrc6xy2p52ep20rle4cag42mmpe6wqc49xf3yankp7xfy4w9an36l/?amount=1000&unit=Gi

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by marc2332** [comment]
Closing this as we already have [docs](https://github.com/iotaledger/firefly/blob/develop/docs/specifications/deep-links.md) for Firefly v2 deeplinks and FF v1 is no longer maintained
