### ISSUE TITLE
[Task]: Investigate Windows Log Issue

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#6427]
### Task description

Thoralf reported that logs are not shown on Windows. We should investigate this issue and fix it if it turns out to be true.

It's possible that logs are just saved on a different location and then we should update the handbook:
https://iotaledger.github.io/firefly/guides/developer-tips/#backend-1

Unblocks: #6100 

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by brancoder** [comment]
On Windows the log files are located in C:\Users\<user>\AppData\Roaming\Electron\logs :

Os info:
```
Edition	Windows 11 Pro
Version	22H2
Installed on	‎4/‎23/‎2023
OS build	22621.1848
Experience	Windows Feature Experience Pack 1000.22642.1000.0
```

**Comment by begonaalvarezd** [comment]
> On Windows the log files are located in C:\Users<user>\AppData\Roaming\Electron\logs :
> 
> Os info:
> 
> ```
> Edition	Windows 11 Pro
> Version	22H2
> Installed on	‎4/‎23/‎2023
> OS build	22621.1848
> Experience	Windows Feature Experience Pack 1000.22642.1000.0
> ```

@brancoder could you update the handbook with the location https://iotaledger.github.io/firefly/guides/developer-tips/#backend-1 🙏🏼 and open a PR that closes this issue
