### ISSUE TITLE
[Task]: Implement `removeProfileFolder` in `capacitorApi.ts`

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#6428]
### Task description

`removeProfileFolder` is missing from `capacitorApi.ts` and its needed as it is used in multiple places in the core libraries 

### Requirements

Implement `removeProfileFolder`

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
Blocked by the filesystem capacitor plugin

**Comment by amadeu2** [comment]
add also renameProfileFolder and listProfileFolder
