### ISSUE TITLE
German Translation is using DU and SIE - change all SIE to Du

### ISSUE THREAD

**Issue by Badabooo** [iotaledger/firefly#643]
## Issue description

Briefly describe the issue.

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by rajivshah3** [comment]
Hi, this can be changed on [Crowdin](https://crowdin.com/project/iota-firefly)
