### ISSUE TITLE
[Task]: Issue with 24 word passphrase confirmation

### ISSUE THREAD

**Issue by multifolio** [iotaledger/firefly#6445]
### Platform

Desktop

### Version

1.7.1

### Description

Currently, in the Firefly Wallet, when confirming the 24 word passphrase backup, users are presented with a screen where they need to click on the correct words. However, the current implementation allows users to randomly click on any of the three suggested words per slot, making it fairly easy to confirm the 24-word backup phrase without actually knowing the correct words.

I suggest implementing a solution that would make it more difficult for users to confirm their 24 word passphrase backup by random clicking. For example, the user could be required to enter the words manually(type validation) or more options per word are presented. This would greatly improve the account setup process.

### Expected behaviour

Make it harder or impossible to pass the 24 words passphrase confirmation without knowing the passphrase.

### Actual behaviour

The wallet allows users to confirm the backup by randomly clicking on the suggested words. This is fairly easy and can be done in 15-20 seconds without knowing the 24 words backup phrase as there are only three options per word.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Do the wallet setup
2. Show 24 words passphrase
3. Proceed to 24 words passphrase confirmation
4. Randomly click any of 3 words per slot to find the right one
5. Repeat for the remaining words

### Operating System

Mac

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dangenendt** [comment]
Where exactly is the problem? 
When the user just clicks through those words it's the users problem when after the process he does not know how to recover his acc 😁

Imagine I register for some service and I need to provide my email address (twice). I just press some random buttons and be able to provide the same email two times, without knowing the email i typed in. That's the users problem, not the problem of the service imho 🤷🏻‍♂️

**Comment by marc2332** [comment]
This isn't really an issue. :+1:
