### ISSUE TITLE
[Task]: Make Tag field a selectable text field

### ISSUE THREAD

**Issue by multifolio** [iotaledger/firefly#6446]
### Task description

The tag field is used to transmit info or data along the transaction. Making it selectable enables a lot of usecases like receiving payments that include information. Making it selectable enables easier interaction with the tag data.

### Requirements

Make tag field selective

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
The tag field is already included in both shimmer and iota apps and it can be added to any transaction on demand by the user
