### ISSUE TITLE
Make Ingoing and Outgoing Transactions Easier to Distinguish

### ISSUE THREAD

**Issue by Oskar-F** [iotaledger/firefly#645]
## Description

Make ingoing and outgoing transactions easier to distinguish.

## Motivation

It's rather difficult to differentiate incoming and outgoing transactions.

## Requirements

I propose to go with the rest of the world on this, and make outgoing transactions red.

## Are you planning to do it yourself in a pull request?

No.

**Comment by maxwellmattryan** [comment]
Hey @Oskar-F, thanks for the suggestion. I've moved this issue to a discussion [here](https://github.com/iotaledger/firefly/discussions/1511) 👍
