### ISSUE TITLE
MAC - Stronghold Backup 'Something Went Wrong'

### ISSUE THREAD

**Issue by alorraine** [iotaledger/firefly#646]
## Issue description

In setup, at 'Back up to a Stronghold File', after correctly entering the password, selecting 'Save Stronghold backup' gives the save file dialog, and saving causes 'Something went wrong' error.

'Skip this step' also produces ' Something went wrong' error.

This is after renaming the saved file name. Going back to confirm the 24 word phrase and reaching Stronghold backup stage does not solve the problem.

## Wallet version

Mac 0.3.0 Beta Release

## System specification

What is your operating system?

Mac 10.15.7 Catalina
 
## Is it a repeatable issue?

N - Tried new wallet, and didn't re-produce error.

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

I'd hope to rename files so I can identify them myself.

## Actual behaviour

'Something Went Wrong' error, and unable to skip

Having seen the error below, I can confirm that the correct password was entered in the 'Stronghold Backup' section. 100%.

## Errors

Mon, 22 Mar 2021 18:41:27 GMT
StrongholdError: `snapshot password not set`

Mon, 22 Mar 2021 18:35:36 GMT
StrongholdError: `snapshot password not set`

Mon, 22 Mar 2021 18:34:44 GMT
StrongholdError: `snapshot password not set`

Mon, 22 Mar 2021 18:34:43 GMT
StrongholdError: `snapshot password not set`

Mon, 22 Mar 2021 18:34:42 GMT
StrongholdError: `snapshot password not set`

Mon, 22 Mar 2021 18:34:38 GMT
StrongholdError: `snapshot password not set`

Mon, 22 Mar 2021 18:34:32 GMT
StrongholdError: `snapshot password not set`

Mon, 22 Mar 2021 18:33:33 GMT
StrongholdError: `snapshot password not set`

Mon, 22 Mar 2021 18:33:31 GMT
StrongholdError: `snapshot password not set`

Mon, 22 Mar 2021 18:33:29 GMT
StrongholdError: `snapshot password not set`

Mon, 22 Mar 2021 18:32:08 GMT
StrongholdError: `snapshot password not set`

Mon, 22 Mar 2021 18:31:54 GMT
StrongholdError: `snapshot password not set`

Mon, 22 Mar 2021 18:31:51 GMT
StrongholdError: `snapshot password not set`

Mon, 22 Mar 2021 18:31:39 GMT
StrongholdError: `snapshot password not set`

**Comment by vasiauvi** [comment]
The same issue is also for me, but for Ubuntu 20.10. The "Something went wrong" appears indifferently if I change or not the file name. Past this step the setup will not continue.

**Comment by mixim-mixim** [comment]
One quickfix: i reset the App by deleting ~/.config/FireFlyBeta ... started from scratch and saved the Stronghold backup file to the ~./Applications directory (where the FireFly-Beta-AppImage is located) ... that works ...

**Comment by HomoEfficio** [comment]
The same issue in Windows 10.
![firefly-error-stronghold-01](https://user-images.githubusercontent.com/17228983/112073585-c5e00100-8bb7-11eb-9ffb-1ab0748ba608.png)

**Comment by Phyloiota** [comment]
> The same issue in Windows 10.
> ![firefly-error-stronghold-01](https://user-images.githubusercontent.com/17228983/112073585-c5e00100-8bb7-11eb-9ffb-1ab0748ba608.png)

did you update already to 0.3.1?

**Comment by HomoEfficio** [comment]
I was on 0.3.0 and, when I visited https://blog.iota.org/firefly-beta-release/, the link was 0.3.0.

Now I see 0.3.1 in https://blog.iota.org/firefly-beta-release/ and the Firefly 0.3.1 works OK!!

Thanks for the quick fix!!

**Comment by vasiauvi** [comment]
Confirmed that with 0.3.1 the issue is resolved. This means that the Stronghold backup is removed from the setup and possible to be done after in Settings -> Security -> Export Backup.

**Comment by obany** [comment]
The should now be fixed, please re-open after the next release if you still have issues.
