### ISSUE TITLE
Settings Scroll Bar click-box not appropriately sized

### ISSUE THREAD

**Issue by Wisper7** [iotaledger/firefly#647]
## Issue description

In the settings menu (may be in other scroll related instances as well), the right side of the scroll bar does not respond to click-drags. There seem to be a few pixels that should be part of the bar, but are not considered part of it when I click and drag the far side of the bar.

## Wallet version

0.3.0

## System specification

Mac Mojave 10.14.6

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Increase hit detection box of scroll bar
2. Increase width of scroll bar in general (very skinny)
3. Compare to Discord's scroll bar, which actually has an enlarged hitbox greater than the actual scroll bar image, to make it easier to click and drag.

## Expected behaviour

Respond to mouse no matter what part of bar I click.

## Actual behaviour

Ignores far right side clicks.

**Comment by obany** [comment]
The scroll bars will be larger in the next release, please re-open this issue if the problem persists.
