### ISSUE TITLE
18446.74 Pi balance

### ISSUE THREAD

**Issue by VolkerLudwikowski** [iotaledger/firefly#648]
## Issue description

I had 12Mi in my wallet when I send a transaction of 1.23456 Mi to my own wallet adresse.
When the transaction was confirmed, my balance updated to 18446.74Pi.

## Wallet version

v0.3.0

## System specification

What is your operating system?

Firefly v0.3.0
Plattform: win32
Plattformversion: 10.0.19041
Plattform-Architektur: x64

## Is it a repeatable issue?
N

## Expected behaviour

The balance should still be 12Mi

## Actual behaviour

The balance changed to the amount of 18446.74Pi.
![grafik](https://user-images.githubusercontent.com/81188567/112046553-7d3f2e00-8b4c-11eb-93f0-52f5adf056e3.png)

**Comment by dbforma** [comment]
I also had a few times the wrong balance displayed but then it updated correctly.

**Comment by TheAnimatrix** [comment]
#Devs, Looks like a number overflow since i had the same event occur with the same constant balance.
