### ISSUE TITLE
Account Name overflow

### ISSUE THREAD

**Issue by howsitcohendevelopment** [iotaledger/firefly#650]
## Issue description

Account name overflows in UI

![image](https://user-images.githubusercontent.com/26185003/112047290-63eab180-8b4d-11eb-807a-5fe5f0a37c4d.png)

## Wallet version
0.3.0

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.
make alot of accounts, make them have long names

## Expected behaviour

account name not to overflow or be truncated with ellipsis 

## Actual behaviour
account name overflows

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by norbus161** [comment]
![bug](https://user-images.githubusercontent.com/42058970/112145852-2896c400-8bdb-11eb-806c-a9cda7267153.JPG)

In addition there is a overflow of the account layout in the top region, if too many accounts are available.
Here it should still show the full string of the account name, which is in this case: "this is a test"

**Comment by obany** [comment]
Both these issues should be fixed in the next release, please re-open if you still have issues.
