### ISSUE TITLE
[Task]: Fix export backup in settings gives success with any password if stronghold is unlocked

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#6517]
### Task description

In settings > export backup, you can enter any password and that will give a succesful export, if stronghold is unlocked. We should always check the password before to avoid this as stronghold will fail after choosing the destination file

### Requirements

Only allowed to export if the password is correct

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
Cant reproduce this anymore 🤔

**Comment by jeeanribeiro** [comment]
This needs to be fixed in iota-sdk as this is related to the "sendMessage" function error handling

**Comment by jeeanribeiro** [comment]
Being fixed in https://github.com/iotaledger/iota-sdk/tree/fix/capacitor-reject-promise-on-error

**Comment by jeeanribeiro** [comment]
https://github.com/iotaledger/iota-sdk/pull/298 merged
