### ISSUE TITLE
Balance is not showing correctly even after login/logout

### ISSUE THREAD

**Issue by MiKeF05** [iotaledger/firefly#652]
## Issue description

I received 2 Mi in one of my receive addresses. The transaction was confirmed (shown at explorer.iota.org) but was not shown in Firefly. After I logged out and logged in the transaction was shown. But the balance didn´t increase with 2 Mi.

## Wallet version

0.3.0

## System specification

What is your operating system?

Windows 10 Pro

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

**Comment by prashant-labh** [comment]
Same issue.
Balance gets changed to 18446.74Pi
<img width="1266" alt="Screen Shot 2021-03-22 at 21 57 03" src="https://user-images.githubusercontent.com/30258454/112052154-7966d800-8b5b-11eb-92d4-f57f85ae679c.png">

**Comment by tccflash** [comment]
I sent a amount and the Balance was shown incorrectly after sending. The Balance showed me -1Mi. The real Balance was 9Mi. The correct Balance was shown after log out and logging in again.
![Bildschirmfoto_2021-03-22_um_21 04 17](https://user-images.githubusercontent.com/46502426/112052274-39035c00-8b53-11eb-95aa-fbc7f2451d99.png)
![Bildschirmfoto_2021-03-22_um_21 05 20](https://user-images.githubusercontent.com/46502426/112052290-3dc81000-8b53-11eb-82fa-9518bf567f2b.png)

**Comment by prashant-labh** [comment]
![Uploading Screen Shot 2021-03-22 at 22.22.44.png…]()

**Comment by prashant-labh** [comment]
More+
<img width="1280" alt="Screen Shot 2021-03-22 at 22 22 44" src="https://user-images.githubusercontent.com/30258454/112055242-44f51b00-8b5f-11eb-9afe-9a0ea0f3ed1f.png">

**Comment by prashant-labh** [comment]
More+
<img width="1280" alt="Screen Shot 2021-03-22 at 22 22 44" src="https://user-images.githubusercontent.com/30258454/112056409-a36ec900-8b60-11eb-8211-34b0b22e19b5.png">

**Comment by klemp** [comment]
My latest transaction -5MI is not calculated in Account Balance

![IOTA1](https://user-images.githubusercontent.com/38591540/112466560-4ba1af00-8d66-11eb-99db-0139d50ddf96.png)
![IOTA2](https://user-images.githubusercontent.com/38591540/112466564-4c3a4580-8d66-11eb-92e7-0505c83549d3.png)

**Comment by cvarley100** [comment]
@MiKeF05 are you on Discord? If so, can you change your wallet password, export a backup and DM me the Stronghold?

**Comment by MiKeF05** [comment]
@cvarley100 Yes I´m on Discord. Okay will do the steps and send you the stronghold file.

**Comment by cvarley100** [comment]
Should be fixed in the next version. Please open a new issue if you face a similar issue.
