### ISSUE TITLE
"Snapshot password not set" on Stronghold export in setup

### ISSUE THREAD

**Issue by mixim-mixim** [iotaledger/firefly#653]
## Issue description

Can't save the Stronghold backup at initialization, can't skip backup creation

## Wallet version

Firefly 0.3.0 (beta)

- wallet version (version number, commit, or branch): Firefly 0.3.0 (beta)

## System specification

Linux / Ubuntu 20.04 / KDE Neon

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Initialize the wallet and fill all steps until 'Backup to Stronghold-Datei
2. Give ur wallet password
3. Try to create/save the Stronghold file

## Expected behaviour

The Stronghold file has been created/saved

## Actual behaviour

Only a notification box (An error occured)

## Errors

Firefly log seems to be empty, the access right to write files to disc are present (home dir)

**Comment by mixim-mixim** [comment]
Firefly v0.3.0
Sprache: de
Währung: USD
Node-Einstellungen: Automatische Node-Verwaltung
Plattform: linux
Plattformversion: 5.4.0-67-generic
Plattform-Architektur: x64
CPU-Anzahl: 12
Gesamtspeicher: 31749.8 MB
Freier Speicher: 9078.7 MB
Benutzerpfad: /home/mixim/.config/Firefly Beta

**Comment by mixim-mixim** [comment]
![image](https://user-images.githubusercontent.com/24353892/112053329-846a3a00-8b54-11eb-8903-f43cc7aa7d30.png)

**Comment by mixim-mixim** [comment]
This issue is probably a duplicate of #646

**Comment by mixim-mixim** [comment]
One quickfix: i reset the App by deleting ~/.config/FireFlyBeta ... started from scratch and saved the Stronghold backup file to the ~./Applications directory (where the FireFly-Beta-AppImage is located) ... that works ...

**Comment by Gerry4888** [comment]
same problem on Mac, impossible
 to save Stronghold backup at initialization.

**Comment by stuar7** [comment]
I was able to pass this screen by running the program as administrator on Windows (Firefly v0.3.1).

**Comment by cvarley100** [comment]
@mixim-mixim did you do anything odd during setup like go backwards and fowards or wait for a while?

**Comment by mixim-mixim** [comment]
@cvarley100 sry i don't remember exactly, but at the first try i don't tried to save to my home dir, after delete of the .config/FireflyBeta dir and fresh setup i tried to save to my home dir, that works, and i did no more extra try. ..

**Comment by obany** [comment]
Is this still an issue, or can it be closed ?

**Comment by mixim-mixim** [comment]
can be closed, works now, thx
