### ISSUE TITLE
Account with same name possible

### ISSUE THREAD

**Issue by MiKeF05** [iotaledger/firefly#657]
## Issue description

There are many accounts with the same name possible. Wouldn´t it make sense to refuse this? Because I think this will lead to problems.

## Wallet version

0.3.0

- wallet version (version number, commit, or branch):

![Screenshot](https://user-images.githubusercontent.com/71659397/112058833-5c320980-8b5b-11eb-8792-3bb33befb81c.jpg)

**Comment by obany** [comment]
Could you document how you produced this, unable to reproduce

**Comment by MiKeF05** [comment]
I tried it with v0.3.1 but it seems to be good. So it is not possible to create accounts with the same name.
