### ISSUE TITLE
[Task]: Add `AddEvmChainForm` validation logic 

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6580]
### Task description

With the form to add an EVM chain stubbed out, the next step is adding form validation logic.

### Requirements

_TBD_

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
Blocked by #6581
