### ISSUE TITLE
Sorry new to Github ... I have requested the test tokens to be sent to my wallet, everything looks set up fine with the wallet but getting an error message from faucet

### ISSUE THREAD

**Issue by Mace467** [iotaledger/firefly#662]
## Issue description

Briefly describe the issue.

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by tryoutpackage** [comment]
F5 the page / keep requesting, it will work eventually.

**Comment by Mace467** [comment]
Thanks 
just trying to log into faucet and getting bad gateway message!!

**Comment by tryoutpackage** [comment]
They are currently fixing / improving it as we speak (based on Discord messages)

**Comment by Mace467** [comment]
Thanks again, problem solved and tokens have arrived, can we try and send each other some?

**Comment by tryoutpackage** [comment]
atoi1qp9wrcqjr6qw270adt3x9mdzrd5xlqc7swwvn3srsgg4kt68ppyqz7540zy

**Comment by Mace467** [comment]
atoi1qz7gp4yak8wm9kk6r6uhmphxcp75fm7saj7vr7umfn7gdcvmaejj5hu488f

Much appreciated, seemed that transaction was very fast

**Comment by Mace467** [comment]
assume it arrived OK

**Comment by rajivshah3** [comment]
Hi, the faucet should be working now
