### ISSUE TITLE
Portfolio shows currency different to profile setting

### ISSUE THREAD

**Issue by tryoutpackage** [iotaledger/firefly#663]
## Issue description

I've set EUR as default currency in my profile, but in the main screen it always defaults back to USD when restarting Firefly.

## Wallet version

0.3.0. / Developer Version

## System specification

Win 10, Version 10.0.19042 Build 19042

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

1. Set Profile Default Currency to EUR
2. Go to main window, top right box "Portfolio"
3. Set to EUR
4. Restart Wallet
5. It is back to USD

## Expected behaviour

If I select EUR, all should be EUR.

## Actual behaviour

Defaults back to USD.

## Errors

No errors

**Comment by cvarley100** [comment]
Fixed in #776
