### ISSUE TITLE
[Bug report]: Metadata field displaying hexadecimal code instead of text for long strings

### ISSUE THREAD

**Issue by multifolio** [iotaledger/firefly#6636]
### Platform

Desktop

### Version

2.1.0

### Description

Metadata field shows hex code instead of text for long strings for incoming transactions:

Screenshot: [https://imgur.com/a/lW4MuI0](https://imgur.com/a/lW4MuI0)

### Expected behaviour

Show human readable text like it's working for shorter strings

### Actual behaviour

Show unreadable hex code

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Send 0.4 SMR to smr1qztz2z8cj3ygtnv984pq9ldq3jssppkv94nhlkvvfr994qp26ye7g5h4ezd adding a prompt that generates 200 words in the metadata field e.g. "Write 200 words about a topic of your choice."
2. Wait for the prompt response.

### Operating System

Mac

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

I can't paste the hexcode since you haven't made the metadata field a selective-text yet(https://github.com/iotaledger/firefly/issues/6446) 

Here is a screenshot: [https://imgur.com/a/lW4MuI0](https://imgur.com/a/lW4MuI0)

Tx: [https://explorer.shimmer.network/shimmer/transaction/0x4758a3ca2b8829dfceda6063d3d602b2069d83479336fa73e58f42fa45fef88d](https://explorer.shimmer.network/shimmer/transaction/0x4758a3ca2b8829dfceda6063d3d602b2069d83479336fa73e58f42fa45fef88d)

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwellmattryan** [comment]
Hey @multifolio, this is a slightly more complicated fix to do because when we have bytes within an output's metadata field, we don't know how to de-serialize those bytes. It could be UTF-8/text like in your case, it could be metadata encoded in hex format for a smart contract, or something else. We're drafting a TIP to make this field adhere to some standard, so once that is in then it will be significantly easier to de-serialize those bytes properly to display the data correctly.

**Comment by Tuditi** [comment]
We cannot reproduce it. When sending the transaction you described, it prompts me to send 8 SMR. What approach do you follow to encode your response? FF expects a hex string and it works with text of 400 words inside the transaction. 

E.g.: This transaction shows correctly in the incoming wallet:  https://explorer.shimmer.network/testnet/transaction/0x21985eb9240d0e8d762c636f52913ab09bb0d5a93617065ab442e425f8d94291

**Comment by marc2332** [comment]
Closing due inactivity
