### ISSUE TITLE
[Bug report]: whitescreen when deleting profile

### ISSUE THREAD

**Issue by sl00k** [iotaledger/firefly#6638]
### Platform

Desktop

### Version

1.7.1

### Description

Firefly whitescreen after deleting one profile.
I have more than one profile. dont know if this happens if the deleted profile was the only profile in firefly.

I am not sure about the staking part right know. 

### Expected behaviour

no whitescreen

### Actual behaviour

whitescreen

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

log in profile and delete it

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

White screen

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marc2332** [comment]
Hey @sl00k, we have recently launched the new Firefly IOTA (latest version is v2.0.2 at the moment of writing this). Do you mind giving it a try and letting us know if this issue still happens? :smile: 

Thank you :v:

**Comment by sl00k** [comment]
I did a simple test
create new profile and delete it.
seems to be fixed
