### ISSUE TITLE
Make color of arrows for transactions more distinguishable

### ISSUE THREAD

**Issue by tryoutpackage** [iotaledger/firefly#664]
## Description

In the transaction overview, both arrows for incoming and outgoing transactions seem to have nearly the same coloring. It is hard to distinguish them quickly.

## Motivation

Colors quickly help to get an understanding if an incoming or outgoing transaction happend, especially when scrolling quickly through history.

## Requirements

1. The color of the arrows should be more distinguishable from each other.
2. Right now it is light green and slightly less light green

![Screenshot 2021-03-22 231315](https://user-images.githubusercontent.com/70478858/112065005-365d3280-8b64-11eb-8623-7d28a1711e73.png)

**Comment by TrustedKiller** [comment]
Definitely needs to be more distinguishable.  Would prefer Green for incoming and Red for outgoing transactions.

**Comment by tryoutpackage** [comment]
It seems to be based on wallet-color. Create 2-3 colors and then orange
appears, which also colors the arrows. Still some are not readable enough.

TrustedKiller ***@***.***> schrieb am Di., 23. März 2021,
00:02:

**Comment by jkhabbaz11** [comment]
needs to have the entire block likes a darkish/lightish red and darkish/lightish green for sending and receiving, respectively.

**Comment by dev0pa** [comment]
![1](https://user-images.githubusercontent.com/81360970/112461989-d7184180-8d60-11eb-887e-8cfb76856f8e.jpg)

**Comment by cvarley100** [comment]
Closing this one. Let's use #698 to track this issue.
