### ISSUE TITLE
'Total in' and 'total out' are cluttering the wallet

### ISSUE THREAD

**Issue by petewinson** [iotaledger/firefly#666]
## Hi guys, I think the 'Total in' and 'total out' info is unnecessary and rather confusing. It also clutters up the wallet with additional numbers. Wouldn't it be better to leave this out and make it an optional feature for number geeks?

Also, even if it would be optional, the font size is too big in my opinion. It makes it seem too important.

Briefly describe the issue.

## Wallet version: Firefly Beta

Which version of wallet are you using?

- wallet version (version number, commit, or branch): Firefly Beta

## System specification

What is your operating system? OS

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue? Y

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen. The info should not be there.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by rafaeldjpbrochado** [comment]
Tagging duplicates here: https://github.com/iotaledger/firefly/issues/581 and https://github.com/iotaledger/firefly/issues/353.

**Comment by frnfa** [comment]
or at least, show total out and total in specific for your account, not all accounts together

**Comment by cvarley100** [comment]
Total In/Out were removed in #815
