### ISSUE TITLE
Confirmation before sending our MAX balance

### ISSUE THREAD

**Issue by IcecolD120** [iotaledger/firefly#667]
Hi Team,

It could be great if you can add a confirmation request before sending our MAX balance. A missclick could happen and will cost you all your balance. What do you guys think ?

**Comment by tryoutpackage** [comment]
That would really be good. Why not make it optional in the settings, if you want to have confirmation of sending in general (on by default). Especially with the iota:// deeplinks a send can happen in 2 clicks (!).

**Comment by cvarley100** [comment]
There is a confirmation screen before every transaction added in #816
