### ISSUE TITLE
Can't send "Need to leave 1 Mi"-Error, even though 1 Mi is still in wallet

### ISSUE THREAD

**Issue by tryoutpackage** [iotaledger/firefly#668]
## Issue description

I'm transferring 1 Mi from one wallet to another ("move amounts / Guthaben verschieben"). The sending wallet has 2 Mi. Still I can't send 1 Mi, as an error claims "I need to at least have 1 Mi left". 

## Wallet version

0.3.0 Developer Version (latest)

## System specification

Win 10, Version 10.0.19042 Build 19042

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

1. Have internal wallet with 2 Mi
2. Create second wallet inside it
3. Send 1 Mi over, error appears ("need to have at least 1 Mi left in old wallet)

## Expected behaviour

That I can send over 1 Mi, as 1 Mi will still be left.

## Actual behaviour

It claims I have less than 1 Mi in old wallet left, which is not true based on what I see in the wallet.

## Errors

No error logs. 

![less_1_mi](https://user-images.githubusercontent.com/70478858/112068012-54796180-8b69-11eb-9b5c-13c34a0c2415.png)

**Comment by TheAnimatrix** [comment]
you might have a value really close to 2Mi, could be rounded. Try selecting "MAXIMAL" and try sending

**Comment by tryoutpackage** [comment]
Seems to be solved with update? Now I can send below <, but it is on a 2nd wallet, not the "main" / first one.

Also I cannot see if there is some smaller amount on it and it just rounds to 2 Mi, is that setting I'm missing?

**Comment by tryoutpackage** [comment]
Ok, can be closed, it is indeed some still there when clicking Max.

![image](https://user-images.githubusercontent.com/70478858/112136597-75749d80-8bcf-11eb-9905-2af5857c668d.png)
