### ISSUE TITLE
Different Profiles same seed displaying different Balances. 

### ISSUE THREAD

**Issue by Basha0** [iotaledger/firefly#669]
## Issue description
I created a a Profile from a backup file and sent some tokens with it.
looked into the old Profile and the Balances were different

My latest transaction with my **old** Profile
![image](https://user-images.githubusercontent.com/12910214/112068317-f600b300-8b69-11eb-8c85-7128e3dae30e.png)

My latest transaction with my **new** Profile from my backup file
![image](https://user-images.githubusercontent.com/12910214/112068362-087aec80-8b6a-11eb-9172-ec014cc06631.png)

## Wallet version

Version 0.3.0
also in 0.3.1
## System specification

Win 10

![image](https://user-images.githubusercontent.com/12910214/112068004-517e7100-8b69-11eb-9f90-c40f01cd9218.png)

![image](https://user-images.githubusercontent.com/12910214/112067945-37449300-8b69-11eb-99cc-bf642b81f8a8.png)

## Is it a repeatable issue?

yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

this is what i did.
1.create Profile receive faucet tokens.
2.send/receive some tokens
3. Create a backup
4.create a new Profile with the backup.
5.send/receive some transactions
(Sometimes you have to switch between the profiles and issue transactions, I could reproduce the issue on the third switch)
6.log out and login into "old" account
balances are different from each other.

## Expected behaviour

Both Profile should have the same balance as it is the same seed.

## Actual behaviour

Different balances in firefly. Also the explorer is displaying different Token Amount.

**Comment by obany** [comment]
There are some known issues with balances, also in future versions you will not be able to import the same stronghold more than once.
