### ISSUE TITLE
It is possible to paste text in the "amount" field when sending a transaction.

### ISSUE THREAD

**Issue by lluisin** [iotaledger/firefly#670]
## Issue description

It is possible to paste text in the "amount" field when sending a transaction.
The "amount" field should only accept digits in it.

## Wallet version

0.3.0

## System specification

Win 10

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

1. Copy text from somewhere (for example: Discord)
2. Paste it in "Amount" field when sending a transaction

## Expected behaviour

Red text : "The amount appears to be an invalid number"

## Actual behaviour

Text is pasted in "Amount" field

**Comment by obany** [comment]
This should be fixed in the next release, please re-open if you still have issues.
