### ISSUE TITLE
[Task]: Implement search functionality for `SelectAssetPopup`

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6702]
### Task description

The user will need to be able to search for an asset among potentially large list.

### Requirements

_TBD_

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Tuditi** [comment]
https://github.com/iotaledger/firefly/pull/6705
