### ISSUE TITLE
Unable to save Stronghold backup

### ISSUE THREAD

**Issue by itsmontoya** [iotaledger/firefly#671]
## Issue description

When attempting to save Stronghold backup, the error "something went wrong" is returned. 

## Wallet version

Which version of wallet are you using?

- v0.3.0

## System specification

What is your operating system?

OSX 10.15.7

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Attempt to save Stronghold backup with default settings

## Expected behaviour

Stronghold backup should save and user should goto next page

## Actual behaviour

Error or "something went wrong" appears. 

## Errors

<img width="455" alt="Screen Shot 2021-03-22 at 4 42 24 PM" src="https://user-images.githubusercontent.com/928954/112071905-fbd8a300-8b2d-11eb-9703-cf7001a0e1dc.png">

<img width="495" alt="Screen Shot 2021-03-22 at 4 45 47 PM" src="https://user-images.githubusercontent.com/928954/112071955-1448bd80-8b2e-11eb-9bd0-ea362ea0d01c.png">

**Comment by cvarley100** [comment]
This is fixed in 0.3.1. Please update to the new version.
