### ISSUE TITLE
Keep "restart app" prompt open after in-app updating

### ISSUE THREAD

**Issue by cyclux** [iotaledger/firefly#672]
## Description

Keep "restart app" prompt open after in-app updating, let the user close it manually.

## Motivation

The "restart app" prompt closes itself very quickly after in-app updating. If you are not quick enough or you don't follow the downloading you miss the message entirely.

## Are you planning to do it yourself in a pull request?
No.

**Comment by obany** [comment]
This should be fixed with the next release, please re-open if you still have issues.
