### ISSUE TITLE
Firefly does not check for updates if the app is open

### ISSUE THREAD

**Issue by rafaeldjpbrochado** [iotaledger/firefly#673]
## Issue description

When a new version of Firefly is available, if the user has Firefly already open, they won't be able to see that there is a new version available (even if they press the `Firefly Version` UI element under the `Security` module - it just says that "Firefly is up to date").

## Wallet version

v0.3.0

## System specification

Windows 10

## Is it a repeatable issue?

Yes

## Expected behaviour

The app should probably check for updates every once in a while, or perhaps when the user interacts with the `Firefly Version` UI element under the `Security` module. Or perhaps there should be a "Check for updates" button inside that module.

**Comment by Oskar-F** [comment]
Same on macOS.

**Comment by obany** [comment]
Fixed in the next version.
