### ISSUE TITLE
Mystery account appears after unlocking the wallet.

### ISSUE THREAD

**Issue by metableorg** [iotaledger/firefly#674]
## Issue description
I created a second account and deleted it. After deleting the second account, it reappears with the name "Account 2" and a balance of 0.

## Wallet version

Firefly v0.3.1

## System specification

Windows

## Is it a repeatable issue?

Yes, I think so.

## Steps To reproduce the issue

1. Create a second account.
2. Add tokens to it.
3. Delete the account.
4. Let the wallet be inactive long enough to go into its lock screen.
5. Unlock the wallet and look for a second account with a zero balance.

## Expected behaviour

For no mystery accounts to appear.

## Actual behaviour
![screen_shot](https://user-images.githubusercontent.com/3117023/112074926-63e6b380-8b45-11eb-88ad-09f938b5028c.png)

A mystery account appears.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by Phyloiota** [comment]
is it still there after app restart?

**Comment by metableorg** [comment]
Yes

**Comment by gjeee** [comment]
i can confirm this weird account behaviour:

1) i had 2 accounts "bla" and "bla2", then i deleted "bla2" and added a new one called "ia" -> i ended up with "bla2" and "Account 2"
2) after adding a new second account, the "My Accounts" pane shows two accounts with both the name of the one i just created (both also show same balance)

**Comment by Phyloiota** [comment]
> Yes

you said you first added some tokens to the second account - did you see this message when you tried to delete it? As normally the wallet will not allow to delete accounts that have still value:
![image](https://user-images.githubusercontent.com/77154511/112256416-b38cc280-8c9e-11eb-8bfc-0f07b672d727.png)

**Comment by metableorg** [comment]
Yes, I did an internal transfer to zero out the balance and then I deleted the account. I can confirm that I had only one account after the deletion. It was shortly after the deletion that the new mystery account appeared.

**Comment by cvarley100** [comment]
This will be fixed in the next version. Please open an issue if you face anything similar.
