### ISSUE TITLE
Not able to proceed further "Verify your pin" whle setting up new wallet

### ISSUE THREAD

**Issue by aayush** [iotaledger/firefly#676]
## Issue description
it ask fro verify your pin, even if i type correct pin, it dont go to next step
Briefly describe the issue.

## Wallet version
0.3.1
Which version of wallet are you using?

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac/Win/Linux (+Version and or Distro if possible)
linux ubuntu 18.04

## Is it a repeatable issue?
yes

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

just start setting up wallet

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by cvarley100** [comment]
Please can you enable dev tools and paste any errors you see in the console?

**Comment by obany** [comment]
Can you retest this with the latest release https://github.com/iotaledger/firefly/releases/tag/desktop-0.4.0 and see if this is still an issue
