### ISSUE TITLE
Add help icon with description

### ISSUE THREAD

**Issue by simpletranslation** [iotaledger/firefly#678]
Add help icon with proper description next to option in settings. For example Deep Links Automatically fill Transaction in Firefly .......... people won't understand what is it for.

**Comment by cvarley100** [comment]
Can you expand a little more on what you mean? I don't understand.

**Comment by rafaeldjpbrochado** [comment]
I think the problem @simpletranslation is describing is that some settings aren't clear enough about what they do and what they're useful for (for non-DLT-savvy folks). I think @simpletranslation then suggests a traditional "help icon" that you can hover on to get more in-depth information, sort of like this (next to Deep Links):

![help icon](https://user-images.githubusercontent.com/39466455/115026325-5d233600-9e90-11eb-8647-0b7f19b2d9e3.png)

However, I don't think we necessarily need this help icon functionality. We can probably just expand the existing descriptions to give more insight into each setting.

**Comment by maxwellmattryan** [comment]
I agree with @rafaeldjpbrochado - the setting ideally should be concise but descriptive enough to know what that setting is.

**Comment by maxwellmattryan** [comment]
Thanks for your suggestion @simpletranslation. You can reach out to us on #firefly-discussion or #firefly-translations on [Discord](https://discord.iota.org) to talk about some clarifications or thoughts you have about the text in Firefly. I am going to close this issue in the meantime 👍
