### ISSUE TITLE
Whole Wallet Freeze after trying to change account value from USD to something else

### ISSUE THREAD

**Issue by simpletranslation** [iotaledger/firefly#681]
Whole Wallet Freeze after trying to change account value from USD to something else. Dropdown will show up and after that you can select anything or get out of it. Tried it multiple times only thing which is working is close red button.

<img width="1280" alt="Screen Shot 2021-03-23 at 1 28 09 pm" src="https://user-images.githubusercontent.com/4455434/112083831-df933f80-8bdb-11eb-9694-d763f11ea25f.png">

**Comment by Phyloiota** [comment]
could you add infos of your operating system? Did you see any errors in error log or see now errors in the log? Could you open "developer tools" and switch to the console tab? Copy all errors from there please and paste it in your issue

**Comment by simpletranslation** [comment]
operating system macOS Catalina version 10.15.7
No errors in log
I did few more testing and it happens if you select under General Setting your currency for example AUD then you get option AUD in dropdown and when you click on it it will freeze. With the BTC, ETH, EUR, USD it works fine so it's only when you add another one through general settings.

**Comment by chris-ayala** [comment]
I'm running the wallet under Windows 10, and one of the first things I did was to change it to from USD to JPY through the general settings. No problems here. I also tried setting it to AUD too, and no issues here. Could be a macOS issue.

**Comment by Tulipsmasher** [comment]
Hi Guys

I have this issue also - However I only experience this when I specifically select GBP as per my screenshot. All other currencies are fine. When I log in the wallet functions perfectly but as soon as I select the GBP currency it freezes everything.

* I am a Windows 10 user - Version 20H2 (OS Build 19042.867)
* I have updated the wallet version
* The wallet doesn't respond at all once I select GBP currency - I have to hit X to exit

![image](https://user-images.githubusercontent.com/81441691/112684661-3d898680-8e6b-11eb-916a-0e9a7a16b9a4.png)

**Comment by chris-ayala** [comment]
I previously mentioned that I did not see this problem under Windows 10 but after further testing, I actually do.

Working case:
- Open wallet
- Go to general settings and set currency to JPY
- Return to either account screen (account graph) or main screen (portfolio graph)
- Try to change the currency from USD to JPY (why didn't the new settings propagate to these graphs?)
- Works, graphs display in JPY and UI still works

Freezing case:
- Open wallet
- Go to general settings and just **confirm** that the currency is set to JPY
- Return to either account screen (account graph) or main screen (portfolio graph). Note that even after relaunching the wallet from the working case where I set the currency to JPY, the account graph and portfolio graph still revert to USD, although other parts of the UI do correctly show JPY when appropriate
- Try to change the currency of the account graph or portfolio graph from USD to JPY
- UI freezes without any error. It's not a hard freeze as I can hover over parts of the UI and interact with it, but clicking on anything no longer works.

**Comment by obany** [comment]
This should be fixed in the next release, please re-open if the issue persists.
