### ISSUE TITLE
[Task]: Add error handling for the different ledger signals

### ISSUE THREAD

**Issue by Tuditi** [iotaledger/firefly#6812]
### Task description

At the moment, we don't handle any ledger issues. 

We should be able to handle the following errors:

- Device locked
- Device disconnected
- Wrong app open
- Log if error is not one of those

### Requirements

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by maxwellmattryan** [comment]
There's a task already created for this - #6799
