### ISSUE TITLE
"Your password is incorrect"

### ISSUE THREAD

**Issue by iota-atoi** [iotaledger/firefly#682]
## Issue description

Using "Import Wallet" > "I have a text backup" > Enter 24 word seed > "Continue" > "You have successfully recovered your backup" > Continue > Continue > Create a password.

Entered "STRONG" > Save password > repeatedly got "Your password is incorrect"
I have retyped correct password, have copy & paste same password. Always got "Your password is incorrect"
Have also tried using original & new password, all same error.

## Wallet version

0.3.1

## System specification

MacOS Catalina Version 10.15.7

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Create a new wallet
2. Perform transactions and stronghold backup
3. Delete portfolio
4. Import existing wallet using 24 words

## Expected behaviour
Successful > Enter new password > original wallet restored

## Actual behaviour

Stuck at entering password. Always giving error "Your password is incorrect"
![Screen Shot 2021-03-23 at 3 47 52 PM](https://user-images.githubusercontent.com/81204217/112086638-73bbd180-8bf1-11eb-8469-1945d3600d69.png)
![Screen Shot 2021-03-23 at 3 47 52 PM](https://user-images.githubusercontent.com/81204217/112086679-87ffce80-8bf1-11eb-989b-1d97863514f8.png)
![Screen Shot 2021-03-23 at 3 47 52 PM](https://user-images.githubusercontent.com/81204217/112086739-a82f8d80-8bf1-11eb-8f74-850768df5d0d.png)

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by cvarley100** [comment]
This should be fixed in the next version. Please reopen this issue if you face it after the update.
