### ISSUE TITLE
Giving more details during PIN and password creation

### ISSUE THREAD

**Issue by IcecolD120** [iotaledger/firefly#684]
Hi Team,

That would be great if we can have more information when creating the PIN Code and the password.
For example:
- The password will be used to lock/unlock stronghold + what is stronghold.
- The pin code will be used to open the wallet 

Thank you,
Ice colD

**Comment by maxwellmattryan** [comment]
Hey @IcecolD120, thank you for the suggestion. I'm going to close this issue and move it to a discussion [here](https://github.com/iotaledger/firefly/discussions/1508) 👍
