### ISSUE TITLE
[Bug report]: Unable to manage voting power

### ISSUE THREAD

**Issue by Cool-Dr-T** [iotaledger/firefly#6848]
### Platform

Desktop

### Version

2.1.2

### Description

Firefly becomes unresponsive and blank after trying to open wallet - progress bar appears to finish loading.

Using ledger with all firmware and latest app. 

Cannot print error logs or look at diagnostics because app becomes unresponsive.

Ubuntu desktop version.

Other wallets that are not linked to ledger work fine.

![Screenshot from 2023-05-18 16-37-03](https://github.com/iotaledger/firefly/assets/30495398/9dc5d94d-7d37-404a-a4d6-c0f08d5f4bc3)

### Expected behaviour

wallet should load and should be able to see balances. Worked fine on last version.

### Actual behaviour

plug in ledger, wake ledger with pin, select shimmer app, Open firefly, select wallet, enter pin to log in - watch progress bars load and then see blank screen (attached image)

### Can the issue reliably be reproduced?

Yes

### Operating System

Linux

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

None

### Crash Status

White screen

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicole-obrien** [comment]
Thanks for the report, working on a fix

**Comment by nicole-obrien** [comment]
Fix released: https://github.com/iotaledger/firefly/releases/tag/desktop-2.1.3

**Comment by Cool-Dr-T** [comment]
not fixed!
