### ISSUE TITLE
Spelling mistakes on French version

### ISSUE THREAD

**Issue by chrishamer** [iotaledger/firefly#685]
## Issue description

**Two spelling mistakes on french version**

**

- From the upleft menu > Firefly Beta > Diagnostiques (correct spelling : Diagnostic -add an "S" if you mean plural, but not with "que" at the end)

- From the upleft menu > Firefly Beta > Developer Tools (even if everybody understands it, in french version, it should be "Outils de développement " or "Outils pour développeurs"**

## Wallet version

**V. 0.3.1 (updated)**

## System specification

**WINDOWS**

## Is it a repeatable issue?

**Y**

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.
![wallet french version](https://user-images.githubusercontent.com/49960379/112107998-f754ce80-8baf-11eb-95d2-99fac8ff4ef9.png)

**Comment by rajivshah3** [comment]
Hi, these can be updated on [Crowdin](https://crowdin.com/project/iota-firefly)
