### ISSUE TITLE
[Bug report]: broken .CSV format for "transactions export" on certain sys languages due to unescaped commas

### ISSUE THREAD

**Issue by janviehweger** [iotaledger/firefly#6854]
### Platform

Desktop

### Version

1.7.2

### Description

One assumes, that the _"export transactions"_ feature was intended to further processing of transactions in tax tools or common spread sheet applications.

Each of these tools requires proper format of a ._CSV_-file to be able to process. Tools like _MS Excel_ or _Libre Office Calc_ are more flexible and capable to handle various _CSV_ formats since one can define delimiters and rule sets to detect the _CSV_ structure. But this requires at least a consistent and identifiable structure which is not the case on the current state of the exported transactions file on certain sys language settings. 

All provided sys languages are affected, **BESIDES the following**:
- _Arabic_
- _English_
- _Chinese (simplified)_
- _Chinese (traditional)_
- _Hebrew_
- _Hindi_
- _Japanese_
- _Korean_
- _Persian_

The current export format on the affected sys languages uses a comma (`,`) in the cells belonging to the columns of _"Formatted Value"_. Since the comma is also used as the delimiter in the _header_ (first row), the number of columns can't be matched for an CSV interpreter. In this case the _header_ has 5 commas whereas the data rows each have 6. This issue leads to a column shift and misinterpretation of the CSV data.

**Solution:**
Implement spec [RFC 4180](https://datatracker.ietf.org/doc/html/rfc4180) for CSV format, which suggests

> _Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes._

**Intermediate workaround for users:**
Choose an unaffected sys language like _English_ 

### Expected behaviour

One expects a valid CSV output format like so:

```
Message ID,Intern,Rohwert,Formatierter Wert,Datum,Uhrzeit
0000000000000000000000000000000000000000000000000000000000000000,true,9979999,"9,979999 Mi",16. Nov. 2021,21:09 MEZ
0000000000000000000000000000000000000000000000000000000000000000,true,-8529999,"-8,529999 Mi",26. Nov. 2021,12:50 MEZ
```

... which correctly gets interpreted like so:

![Bildschirmfoto 2023-05-18 um 19 41 44](https://github.com/iotaledger/firefly/assets/376219/800a3c0d-23d7-41f0-af1f-c7e79b722826)

### Actual behaviour

Current broken CSV output _(Message ID obfuscated for demo):_

```
Message ID,Intern,Rohwert,Formatierter Wert,Datum,Uhrzeit
0000000000000000000000000000000000000000000000000000000000000000,true,9979999,9,979999 Mi,16. Nov. 2021,21:09 MEZ
0000000000000000000000000000000000000000000000000000000000000000,true,-8529999,-8,529999 Mi,26. Nov. 2021,12:50 MEZ
```

... results in this misinterpretation:

![Bildschirmfoto 2023-05-18 um 19 35 35](https://github.com/iotaledger/firefly/assets/376219/704fcc3e-2bd0-435c-b54a-4df36b2af8ef)

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. From the _"All Settings" > "General" > "Language" menu _ select any language **NOT** listed in the description above. Choose "German" for example.
2. From the "..."-Menu in the current wallet choose _"Transaktionsverlauf exportieren" (Export transaction history)_
3. Export and save the file locally.
4. Try open the file in a spreadsheet app like MS Excel or Libre Office Calc

### Operating System

Mac

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Previously staked

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marc2332** [comment]
Hey! Firefly IOTA 1.7.2 has been deprecated, a new release has been made (2.0.2 at time of writing this) but it no longer supports exporting your transaction history.
