### ISSUE TITLE
[Bug report]: Governance management popup freezes

### ISSUE THREAD

**Issue by LaKabra** [iotaledger/firefly#6855]
### Platform

Desktop

### Version

2.1.2

### Description

Governance tab freezes when trying to modify voting weight

### Expected behaviour

Change voting weight

### Actual behaviour

The whole tab freezes

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Open Firefly 2.1.2
2. Go to Governance
3. Try changing the weight of the vote (currently staked)

![_1](https://github.com/iotaledger/firefly/assets/119283939/20d211d4-24f5-448b-a6b5-2e5647008639)

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

Non-responsive

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicole-obrien** [comment]
https://github.com/iotaledger/firefly/releases/tag/desktop-2.1.3
