### ISSUE TITLE
[Bug report]: Firefly 2.1.1 and 2.1.2 Tokens cannot be removed from governance (manage voting power) LEDGER nanoX

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#6865]
### Platform

Desktop

### Version

2.1.1, 2.1.2

### Description

Didn't touch my Ledger Account since the vote.

After updating to 2.1.2 i want to send dome tokens. Available balance shows 0.
I check in Governance and see all tokens are still locked as voting power.
I enter "Manage Voting Power" but am unable to set it to 0 because the slider is already on the left side and amount voting power is displayed as "undefined"
![image](https://github.com/iotaledger/firefly/assets/77154511/62de8b92-0573-46b0-a0e6-4db3ebe7c1e9)

I also cannot close the popup anymore or leave the governance tab, only closing the wallet shuts it down.
I downgrade to 2.1.1 - same behavior
I downgrade to 2.1.0 - cannot even access my ledger Profile - it just shows and ebless loading bluescreen
Update to 2.1.2 again, try again, same behavior

I create a new Ledger Profile and attempted to restore the profile from Ledger, i can access the profile, but the behavior stays the same, i cannot access my balance because it is locked in voting power.

Also after creating the second Ledger restore profile, i cannot enter my original Ledger Profile anymore - i get Neon errors
![image](https://github.com/iotaledger/firefly/assets/77154511/8d9023d2-bcfa-4c7c-a51d-5f657a8aad65)

### Expected behaviour

it should work

### Actual behaviour

nope

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

See above described

### Operating System

Windows

### Diagnostics

```shell
Version 2.1.2
Language: en
Platform: win32
Platform Version: 10.0.22621
Platform Architecture: x64
CPU Count: 16
Total Memory: 16236.1 MB
Free Memory: 7566.6 MB
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

None

### Crash Status

Non-responsive

### Error Logs

```shell
Sat, 20 May 2023 06:04:50 GMT
Generic: internal error in Neon module: error initializing account manager: Json(Error("missing field `outputId`", line: 1, column: 904))

Sat, 20 May 2023 05:13:40 GMT
Generic: internal error in Neon module: error initializing account manager: Json(Error("missing field `outputId`", line: 1, column: 904))

Sat, 20 May 2023 05:13:21 GMT
Generic: internal error in Neon module: error initializing account manager: Json(Error("missing field `outputId`", line: 1, column: 904))

Sat, 20 May 2023 05:13:00 GMT
Generic: internal error in Neon module: error initializing account manager: Json(Error("missing field `outputId`", line: 1, column: 904))

Sat, 20 May 2023 05:12:50 GMT
Generic: internal error in Neon module: error initializing account manager: Json(Error("missing field `outputId`", line: 1, column: 904))

Sat, 20 May 2023 05:12:40 GMT
Generic: internal error in Neon module: error initializing account manager: Json(Error("missing field `outputId`", line: 1, column: 904))

Sat, 20 May 2023 05:12:31 GMT
Generic: internal error in Neon module: error initializing account manager: Json(Error("missing field `outputId`", line: 1, column: 904))

Sat, 20 May 2023 05:12:11 GMT
Generic: internal error in Neon module: error initializing account manager: Json(Error("missing field `outputId`", line: 1, column: 904))

Sat, 20 May 2023 05:11:47 GMT
Generic: internal error in Neon module: error initializing account manager: Json(Error("missing field `outputId`", line: 1, column: 904))

Sat, 20 May 2023 05:11:31 GMT
Generic: internal error in Neon module: error initializing account manager: Json(Error("missing field `outputId`", line: 1, column: 904))

Sat, 20 May 2023 05:04:24 GMT
Generic: internal error in Neon module: error initializing account manager: Json(Error("missing field `outputId`", line: 1, column: 904))
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nicole-obrien** [comment]
https://github.com/iotaledger/firefly/releases/tag/desktop-2.1.3
