### ISSUE TITLE
Add public memos to transactions

### ISSUE THREAD

**Issue by ForrestPamp** [iotaledger/firefly#688]
## Description

I would like to see smilies and comments on transactions like on paypal

## Motivation

Comments for transactions are needed to know why money is sent back and forth. Smilies are there to give it a modern feeling and user experience

## Requirements

Write a list of what you want this feature to do.

1. Comments for transactions like in usual banking apps
2.smilies

**Comment by cvarley100** [comment]
Duplicate of #471
