### ISSUE TITLE
Latest transactions spinner spinning forever

### ISSUE THREAD

**Issue by milancheck** [iotaledger/firefly#689]
## Issue description

Latest transactions stuck in infinite loop. Recent transactions not being displayed in the overview.

## Wallet version

0.3.1 

## System specification

Win 10x64
Version 20H2
Build 19042.867

## Is it a repeatable issue?

N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. User is about to receive a transaction to his address
2. User starts the firefly wallet
3. Firefly is up and running. Latest transactions overview stuck in infinite loop (transaction/s received while Firefly being off)

Test: https://youtu.be/RenAaHGaPOU (didn't reproduce the issue)

## Expected behaviour

Latest transactions loading icon won't stuck and transactions are up-to date

## Actual behaviour

Latest transactions loading icon **will get stuck** and transactions are **not up-to date**

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by cvarley100** [comment]
Do you mean the transaction loading spinner span forever?

**Comment by milancheck** [comment]
yes. exactly

**Comment by cvarley100** [comment]
Should not be present in 0.4.0. Please reopen if you experience this again.
