### ISSUE TITLE
Add sent from/to account titling to transaction items

### ISSUE THREAD

**Issue by ForrestPamp** [iotaledger/firefly#690]
## Description

When you send tokens from WalletA to WalletB (both belong to the same account)
firefly should recognize the name of your wallet and posting the name in the transaction history.
Now in the transaction history the adress is posted.

E.g.: **atoi1qrd5f6zjlj64tj8hxj4nt5keayuezzwetlmyzt0hz7pjt2qq7uahc3as4ms** sent 10 MIOTA to **atoi1qqjvpyuv2xyqgusezg04p9ydund39gxfdjyg9sw5ac5qmqk9d6kzswpakex**
But its a better user experience if the firefly wallet would write the name of the wallet instead of the adress like:
Sparemoney sent 10 MIOTA to Holidaywallet

## Motivation

Better user experience and easier to understand the transaction history

**Comment by maxwellmattryan** [comment]
Hey @ForrestPamp, iiuc this change has been made, so I am going to close this issue. Thank you for the suggestion! 👍
