### ISSUE TITLE
The wallet settings are not translated, it would look more professional if these were also translated to the respective language. =)

### ISSUE THREAD

**Issue by xbfSiiedler** [iotaledger/firefly#694]
## Description

Briefly describe the feature that you are requesting.

## Motivation

Explain why this feature is needed.

## Requirements

Write a list of what you want this feature to do.

1.
2.
3.

## Open questions (optional)

Use this section to ask any questions that are related to the feature.

## Are you planning to do it yourself in a pull request?

Yes/No.

**Comment by rajivshah3** [comment]
Hi, the translations can be done on [Crowdin](https://crowdin.com/project/iota-firefly)
