### ISSUE TITLE
Wallet window not resizable/stretchable in certain areas

### ISSUE THREAD

**Issue by chris-ayala** [iotaledger/firefly#695]
## Issue description
I cannot stretch the wallet window if I try to resize along the areas in red (see screenshot below).
![2021-03-23-17-25-47 991 CxS](https://user-images.githubusercontent.com/764773/112117888-2d6d6f00-8bff-11eb-842c-6a566a0fee06.png)

## Wallet version
Which version of wallet are you using?
- v0.3.1

## System specification
#What is your operating system?
Windows 10 Pro

## Is it a repeatable issue?
Yes

## Steps To reproduce the issue
Explain how the maintainer can reproduce the issue.

1. Open the wallet.
2. Try resizing the windows in the red areas annotated in the image.
3. You'll notice that you cannot stretch the window from the red areas, but you can from the green areas.

## Expected behaviour
Wallet window should be stretchable all around the entire window borders and corners.

## Actual behaviour
Wallet window is not stretchable in the areas designated in red.

## Errors
No error message is shown.

**Comment by obany** [comment]
This should be fixed in the next release, please re-open if the problem persists.
