### ISSUE TITLE
[Task]: Fix build failure with Firefly Shimmer Desktop

### ISSUE THREAD

**Issue by maxwellmattryan** [iotaledger/firefly#6950]
### Task description

The automated builds are failing on the compilation step.

Build: https://github.com/iotaledger/firefly/actions/runs/5300788057/jobs/9594534192

### Requirements

_TBD_

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by maxwellmattryan** [comment]
I think this is related to the `@ethereumjs` libraries that we've added to support signing transactions with the Ledger - probably would be good to start here.

**Comment by Tuditi** [comment]
I think one of the culprits is the @ledgerhq/hw-transport-node-hid package: https://github.com/LedgerHQ/ledger-live/issues/3416

**Comment by Tuditi** [comment]
The 1st issue is that we're depending on @ledgerhq/domain-service, which depends on an outdated eip55 (`2.1.0`) package that relies on keccak version 1.x. Firefly builds if you specify eip55 to `2.1.1` in the `overrides` section of package.json
