### ISSUE TITLE
German translation of "Eingehende Adresse" -> "Sendeadresse"

### ISSUE THREAD

**Issue by kmueller** [iotaledger/firefly#699]
## Description

The sending address could be clearer:

Sending address should be "Sendeadresse" instead of "Eingehende Adresse".
Receiving address is translated as "Empfangsadresse".

## Motivation

"Eingehende Adresse" is confusing, it could also be understood as receiving address.

## Are you planning to do it yourself in a pull request?

No.

**Comment by r-c-k** [comment]
Translation related suggestions are taking place at [https://crowdin.com/project/iota-firefly](https://crowdin.com/project/iota-firefly). I suggested a change to "Absendeadresse" [here](https://crowdin.com/translate/iota-firefly/32/en-de#4784).
