### ISSUE TITLE
deeplinks format not compatible with ARPANET rules

### ISSUE THREAD

**Issue by HBMY289** [iotaledger/firefly#700]
## Issue description

I tried posting a iota deeplink on Discord, but the final link was changed automatically by Discord and was invalidated.
Any link with more than 63 characters will be cut and a slash is automatically introduced.
This link
http://1234567890123456789012345678901234567890123456789012345678901234
will be changed to this:
http://123456789012345678901234567890123456789012345678901234567890123/4

Other services might also behave similar making FireFly deeplinks in their current form unusable.

## Wallet version

0.3

## System specification

Not OS specific

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Post any iota Firefly deeplink on Discord and check the final link.

## Expected behaviour

Posted link matches the link I have entered. Clicking the link will open Firefly and show the transaction to send.

## Actual behaviour

Discord changes the link. Clicking it will open Firefly, but it will not open any transaction to send, because the link is invalid.

## Proposed solution
User TOBY MZ analyzed the issue. This is his summary: 

Because of ARPANET rules for host names, discord and maybe other communication platforms and services will have problems interpreting firefly deeplinks. In a discord chat, the address in the current deeplink format is interpreted as DNS Label, which has a maximum length of 63. To prevent platforms from misinterpreting iota deeplinks, the format should followed the internationally applied specification and implementation of domain Names postulated in rfc1035 (1987) [https://www.ietf.org/rfc/rfc1035.txt]
A possible solution to the problem in discord would be to change the format from 
iota://address/?amount=x 
to iota://send/address/?amount=x

Other web services might also restrict the second or the third field and we might even need to divide the address.  Which is not elegant but probably the safest solution.

**Comment by obany** [comment]
This will be updated in the next release with the new format

`iota://wallet/atoi1qzwderym4mesvs7835l52vk7jl7tz264j5yphny8kmeg6xn3vz2w5h67dwl?amt=1000`

**Comment by JanOonk** [comment]
> 
> 
> This will be updated in the next release with the new format
> 
> `iota://wallet/atoi1qzwderym4mesvs7835l52vk7jl7tz264j5yphny8kmeg6xn3vz2w5h67dwl?amt=1000`

That format didn't work for me in v0.4 beta.
This worked: iota://atoi1qqzvmh85v36z054guuscakrxvqhnpu0hwf4989g9hjg529sqyaw9z3fhml0/?amount=1000

**Comment by obany** [comment]
This PR has not been merged yet

**Comment by JanOonk** [comment]
Ah ok thanks... really confusing when a ticket is closed but it is not fixed.
