### ISSUE TITLE
Send amount precision not limited based on chosen denomination

### ISSUE THREAD

**Issue by janvanhoef** [iotaledger/firefly#701]
## Issue description

When entering an amount to send, there is a limit to the precision of the number. Unfortunately it is possible to input numbers with a higher precision than the theoretical limit of 1 iota. See screenshot below for example. There is only 0.999999 MI, 0.999999999999999 MI shoud not be possible. Subsequently, you don't receive an error when pressing the send button.

## Wallet version

Version 0.3.1

## System specification

Windows 10

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Create a transaction
2. Input the amount 0.999999999999999 MI
3. Press send

## Expected behaviour

Input field precision should be limited to denomination. Conversion should occur when switching denominations from a field with a lower precision to a field with a higher precision. Field should be made empty or error should occur when moving from a denomination with more precision to a denomination with less precision.

Trying to send an impossible amount should result in an error.

## Actual behaviour

Actual precision limit in field is unclear

## Errors

![image](https://user-images.githubusercontent.com/1385666/112129021-42c6a700-8bc7-11eb-8432-c9dbb490c398.png)

**Comment by adamkundrat** [comment]
duplicates/similar to #632

**Comment by obany** [comment]
This should be fixed in the next version, please re-open if you still have issues
