### ISSUE TITLE
Being able to copy the password

### ISSUE THREAD

**Issue by Hagi09** [iotaledger/firefly#702]
## Issue description

In the process of creating a new wallet, its possible to copy the password of the first line and pasting it in "confirm password" in the next step. Just wondering if this is some desirable option or a security issue

## Wallet version

0.3.1 Beta

What is your operating system?

Win

Is it a repeatable issue?

Y

**Comment by obany** [comment]
This should be fixed in the next release, please re-open if its still an issue
