### ISSUE TITLE
Profile is missing from general settings

### ISSUE THREAD

**Issue by JanOonk** [iotaledger/firefly#703]
When you go bottom left > All settings > Profile you will notice it's not there:
![image](https://user-images.githubusercontent.com/13236774/112132598-14e36180-8bcb-11eb-8cb9-d8fe6e95408f.png)

**Comment by myhrmans** [comment]
The settings page for profile is currently under [development](https://github.com/iotaledger/firefly/blob/f6d0504f551d222ed69f21d3f92269f512f3cc45/packages/shared/routes/dashboard/settings/views/General.svelte#L33).

**Comment by myhrmans** [comment]
The settings page for profile is currently under [development](https://github.com/iotaledger/firefly/blob/f6d0504f551d222ed69f21d3f92269f512f3cc45/packages/shared/routes/dashboard/settings/views/General.svelte#L33) and therefore currently disabled

**Comment by obany** [comment]
Its in our backlog to do before release, so closing for now as known
