### ISSUE TITLE
Send --> Amount field is not overridable only deletable

### ISSUE THREAD

**Issue by Ephaltes** [iotaledger/firefly#704]
## Issue description

When you want to send iota and paste the address in the wrong field in my example in the amount field
you can not mark the address and override it, you have to mark it ,delete it by pressing backspace 
or deleting single characters by pressing backspace but you cant for example
mark it and then press 3 to override it with the amount of 3 MIOTA

## Wallet version

0.3.1

## System specification

Win 10

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Copy a iota address into the amount field
2. mark the content of amount field
3. try to override it by pressing e.g. 5
4. the address in the amount field doesn't get overridden

## Expected behaviour

that the address gets overridden with e.g. 5

## Actual behaviour

Nothing, address is not getting overridden it just stays marked.
only way to delete from that field is by pressing backspace

## Errors

![1](https://user-images.githubusercontent.com/13035924/112135672-532e5000-8bce-11eb-846b-e3b04c023bca.png)

**Comment by obany** [comment]
This should be fixed in the next release, please re-open if it still has issues.
