### ISSUE TITLE
[UI] Setup process - success circle cut off 

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/firefly#705]
## Issue description

The "success circles" in the setup process seem to be cut off on the sides.

## Wallet version

v0.3.1

## System specification

macOS 11.3 Beta

## Errors

<img width="465" alt="Bildschirmfoto 2021-03-23 um 11 27 17" src="https://user-images.githubusercontent.com/17240275/112136261-0139fa00-8bcf-11eb-8ce9-4630aef5dfc1.png">

**Comment by obany** [comment]
This is as designed.
