### ISSUE TITLE
German translation: "password" instead of "passwort"

### ISSUE THREAD

**Issue by emha** [iotaledger/firefly#706]
## Issue description
On the `Passwort erstellen` screen with the **German** language you can find 

> ...empfohlen, dass Passwor**d**...

insted of

> ...empfohlen, dass Passwor**t**...

## Wallet version
0.3.1

## System specification
Linux - popOS

## Is it a repeatable issue?
Y

## Steps To reproduce the issue
1. Start a fresh run of Firefly
2. Create a new wallet

**Comment by JanOonk** [comment]
You can update it yourself at https://crowdin.com/project/iota-firefly

**Comment by emha** [comment]
> You can update it yourself at https://crowdin.com/project/iota-firefly

Nice, didn't know that. Thank you!
