### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by SOLatGit** [iotaledger/firefly#7060]
### Platform

Desktop

### Version

1.7.2

### Description

after updating wallet version using update feature of wallet, restart throws an error

### Expected behaviour

that wallet opens up and works..

### Actual behaviour

see error description

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. open wallet with older version
2. click left lower corner
3. click notification of "update available" (or similar)
4. wait for installation/update done
5. restart

### Operating System

Linux

### Diagnostics

```shell
App Version: 1.7.2

platform: linux
platformVersion: 4.15.0-212-generic
platformArchitecture: x64
cpuCount: 4
totalMem: 3823.2 MB
freeMem: 810.6 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.vWL7Hm)
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
Hi, which exact distro of Linux do you have? From the last update we had to start building the artifacts using ubuntu 20.04 because github stopped providing machines for ubuntu 18.
If you are using Ubuntu 18 or less, please try updating your version.

**Comment by marc2332** [comment]
Closing due inactivity
