### ISSUE TITLE
[Task]: Fix displayed surplus in send confirmation 

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#7061]
### Task description

Currently the surplus is not correctly displayed in the confirmation popup

Repro: `firefly-alpha://wallet/sendConfirmation?address=<address_here>&disableToggleGift=true&disableChangeExpiration=true&amount=1&giftStorageDeposit=false&surplus=1000&assetId=<native-token-id-here>`

In this example I am sending 1000 glow as surplus and the surplus is not showing at all in the confirmation 
![image](https://github.com/iotaledger/firefly/assets/3624944/fad9a4d1-eb66-449d-95eb-03c9b58d6538)

The confirmation should say: 
- storage deposit: the calculated minimum storage deposit
- surplus: 1000 glow

The surplus should always be added on top of the storage deposit, as you can decide later on to gift the storage deposit or not, but the surplus is an amount attached to the utxo

### Requirements

Above mentioned fixed

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by brancoder** [comment]
Not needed as the displaying surplus in send confirmation is fixed in this PR https://github.com/iotaledger/firefly/pull/7057
