### ISSUE TITLE
[Bug Report]: ASMB funds don't show up in Firefly

### ISSUE THREAD

**Issue by Mosehyah** [iotaledger/firefly#7069]
### Task description

Problem with staking, does not show ASMB funds. MY SERVER has "PARTICIPATION" function 
URL address: https://iota-node.tanglebay.com
Software: HORNET 1.2.4
Network ID: chrysalis-mainnet
Bech32 HRP: iota
Features: Participation, POI
Confirmed milestone index: 6850304
Pruning index: 0
News per second: 6.50
Network confirmations: 81.54

### Requirements

Problem with staking, does not show ASMB funds. MY SERVER has "PARTICIPATION" function URL address: https://iota-node.tanglebay.com
Software: HORNET 1.2.4
Network ID: chrysalis-mainnet
Bech32 HRP: iota
Features: Participation, POI
Confirmed milestone index: 6850304
Pruning index: 0
News per second: 6.50
Network confirmations: 81.54

### Creation checklist

- [x] I have assigned this task to the correct people
- [x] I have added the most appropriate labels
- [x] I have linked the correct milestone and/or project

**Comment by marc2332** [comment]
Hey, chrysalis has been deprecated, do you mind giving the newest release (v2.0.2 at time of writing this) a try and let us know if it works? Thank you :v: :smile: !

**Comment by begonaalvarezd** [comment]
Closing issue because the staking events have finalized
