### ISSUE TITLE
Transactions are not visible in the Tangle Explorer for the Chrysalis Testnet

### ISSUE THREAD

**Issue by EKO-IOTA** [iotaledger/firefly#709]
## Issue description

I have received some Miotas (through several transactions) to my address (atoi1qzg0c2vlcf8dkuyq90xq6mcfhth2qxurvnr8rsy4dvnapwj49ffvxenhm9u) that are not visible in the Tangle Explorer for the Chrysalis Testnet (https://explorer.iota.org/chrysalis/addr/atoi1qzg0c2vlcf8dkuyq90xq6mcfhth2qxurvnr8rsy4dvnapwj49ffvxenhm9u). The transactions are not displayed in the Explorer as inputs and outputs. 

<img width="1020" alt="Bildschirmfoto 2021-03-23 um 13 10 46" src="https://user-images.githubusercontent.com/81235754/112144229-35b2b380-8bd9-11eb-97f3-9f8e7abe62d5.png">

## Wallet version

- wallet version 0.3.0

## System specification

What is your operating system?

Mac - Version 11.2

**Comment by Phyloiota** [comment]
can you confirm that this is the correct message id of the transcation you did:

7de902c874d5d93d6ebeece41ddfb1d037e057cacd2055d39935dd16bb5088c9

?

**Comment by EKO-IOTA** [comment]
yes it is! But for control here once again copied from the firefly wallet:

7de902c874d5d93d6ebeece41ddfb1d037e057cacd2055d39935dd16bb5088c9

**Comment by MiKeF05** [comment]
This transaction ID can be seen in the tanglebay explorer see:
https://explorer.tanglebay.com/testnet/message/7de902c874d5d93d6ebeece41ddfb1d037e057cacd2055d39935dd16bb5088c9
