### ISSUE TITLE
[Task]: Fix expiration modal showing time even when none is selected

### ISSUE THREAD

**Issue by marc2332** [iotaledger/firefly#7106]
Enabling the `Gift storage deposit` makes the expiration show "none" but `In 1 today` is shown in the dropdown  
![image](https://github.com/iotaledger/firefly/assets/38158676/05b272d5-4eaf-4c44-b696-00d367295cea)

**Comment by begonaalvarezd** [comment]
Duplicate https://github.com/iotaledger/firefly/issues/7096
