### ISSUE TITLE
Password too short error message incorrect

### ISSUE THREAD

**Issue by Wisper7** [iotaledger/firefly#711]
## Issue description

Error message given when password is too short is inadequate.

## Wallet version

0.3.1

## System specification

Mac Mojave 14.6

Mac/Win/Linux (+Version and or Distro if possible)

Y

## Steps To reproduce the issue

Put in a very short password on account creation.

## Expected behaviour

A message telling me the the password is short should be shown.

## Actual behaviour

A coding error message 'error.password.short'. Or something along those lines.

**Comment by JanOonk** [comment]
They will probably add it to https://crowdin.com/project/iota-firefly in next version where the community can translate for their language.

**Comment by cvarley100** [comment]
@Wisper7 please can you share a screenshot?

**Comment by Wisper7** [comment]
![Screen Shot 2021-03-31 at 2 43 03 PM](https://user-images.githubusercontent.com/43035966/113194791-7e98e680-922f-11eb-8477-5efe8c918229.png)

I'm on 0.3.1 still.

**Comment by obany** [comment]
This is fixed in the next release, please re-open if the problem persists.
