### ISSUE TITLE
UI improvement - swap the 'amount' and the 'send to address'

### ISSUE THREAD

**Issue by Roy-export** [iotaledger/firefly#712]
## UI improvement -

When using the wallet I am copying and pasting an address - because the wallet defaults to the amount - I end up pasting it on the amount instead of the 'send to address'. 

## Wallet version
0.3.1
- wallet version (version number, commit, or branch):

## Is it a repeatable issue? Yes
![fireflysuggestion](https://user-images.githubusercontent.com/77155712/112159523-3886c600-8c24-11eb-89ec-18edcec91851.PNG)

**Comment by dev0pa** [comment]
![2](https://user-images.githubusercontent.com/81360970/112462647-953bcb00-8d61-11eb-9701-2be5a6ec6bb1.jpg)

**Comment by cvarley100** [comment]
This was fixed in #836
