### ISSUE TITLE
Error "Addresses start with prefix atoi" when there is a typo in the address behind "atoi"

### ISSUE THREAD

**Issue by github-i286** [iotaledger/firefly#715]
## Issue description
Error "Addresses start with prefix atoi" when there is a typo in the address behind "atoi"
There is sometimes alos the the error pop-up "Somthing went wrong" with a mistyped address.

We should have different message for non-network prefix addresses and typos after the network prefix.

## Wallet version
0.3.1

## System specification
Win 10

## Is it a repeatable issue?
Y

## Steps To reproduce the issue
Try to send for exmaple to the invalid address "atoi1asdl7uasduz7asdjhasd7asdhasjdkasdhbbnasdasdad23nnnasdsadas3"

## Expected behaviour

Expected error: "Invalid address: checksum failed"

## Actual behaviour
Error "Addresses start with prefix atoi" (a user would be confused, as his address does start with the network prefix.
Or "Something went wrong", even when we know it's the address that is corrupted.

## Errors
There are no errors logged.

**Comment by dinangeri** [comment]
hello, i have the same prefix address ( atoi ), when i try to send a transaction it is not possible ( invalide address ) what i have to do to solve the issue ? thanks

**Comment by github-i286** [comment]
> hello, i have the same prefix address ( atoi ), when i try to send a transaction it is not possible ( invalide address ) what i have to do to solve the issue ? thanks
Not every number starts with atoi is a valid address, a checksum validates addresses to avoid copy&paste and typo errors. IOTAs sent to an invalid address can never be recovered anymore, no one will ever find the private key.
The but greport here is that the error shoudl not say "Addresses start with <network-prefix>...", as sometimes they really do, but are stil invalid. I suggest in case they really do start with atoi... but is still invalid, to report "invalid address, please check again".

The atoi... prefix is just here to avoid a copy&paste error of an valid address i.e. from testnet to be used in mainnet (starts with iota...).

**Comment by dinangeri** [comment]
thanks for the information and clarification

**Comment by Phyloiota** [comment]
user "dinangery" experienced the following:
directly after the first profile setup he wanted to request funds from the community, so he clicked on "receiving" and coied the shown address to the clipboard, pasted the address to discord. 
I tried to send there and got following error:
<img width="283" alt="atoi" src="https://user-images.githubusercontent.com/77154511/112296370-cf5c8c80-8ccf-11eb-80d3-f93528ff843d.png">
 logout and relogg didnt change his address, he also clicked the address refresh button, but address stayed the same
closing and restarting the wallet - still same receive address in this first account so he only could generate a new profile.

here his screenshots and errors:
https://cdn.discordapp.com/attachments/824207474470158346/824221744310779925/20210324_093710.jpg
https://cdn.discordapp.com/attachments/824207474470158346/824222955583832064/20210324_110705.jpg
https://cdn.discordapp.com/attachments/824207474470158346/824222956023840809/20210324_110654.jpg
https://cdn.discordapp.com/attachments/824207474470158346/824223927538155530/20210324_111108.jpg

**Comment by obany** [comment]
I have improved the errors around the address validation.

But I think in `dinangery` case this was manually copied incorrectly, it should be `atoi1lqqfgyr8fvakxpkfm5lej0k4fldwr2l4ena3nydc6vwyj7vlk5uywuwttztt`

You can clearly see from the screen grab that there is a `l` after the `atoi1` which matches the other characters that were transposed from "l" to "1"

**Comment by xiaoru99** [comment]
I have the same issue , should I close this account and generate a new account?
