### ISSUE TITLE
[Bug report]: i cant get smr from iota staking. 

### ISSUE THREAD

**Issue by loveyousmr** [iotaledger/firefly#7151]
### Platform

Desktop

### Version

2.1.3

### Description

please help me to fit this error
![Ảnh chụp màn hình (3)](https://github.com/iotaledger/firefly/assets/139227635/ea8268b3-bdfd-452c-bf27-25c7e0262c0f)

### Expected behaviour

fit error for firefly

### Actual behaviour

fit for firefly

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

![image](https://github.com/iotaledger/firefly/assets/139227635/2945af42-e2b1-4072-9969-3d3c4fa5aacf)
![Ảnh chụp màn hình (2)](https://github.com/iotaledger/firefly/assets/139227635/10676c9e-91a8-4cab-8657-d2be39b4a0d5)

### Operating System

Windows

### Diagnostics

```shell
a
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

i cant enter my walet

### Error Logs

```shell
a
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
We are preparing a new release which will include a fix for this issue. Apologize for the troubles 🙏🏼

**Comment by begonaalvarezd** [comment]
Fixed by https://github.com/iotaledger/firefly/pull/7568
