### ISSUE TITLE
[Task]: Fix mismatched tx history

### ISSUE THREAD

**Issue by cpl121** [iotaledger/firefly#7155]
### Platform

Desktop

### Version

2.1.4

### Description

The activity history of a profile does not match. I create a profile, make a profile backup and then restore the profile.
I make some transactions from the restored profile and the activity history of the profiles shows differently

Restored profile
![image](https://github.com/iotaledger/firefly/assets/100352899/27df1035-b959-4541-8a68-233d74e4c298)

Original profile
![image](https://github.com/iotaledger/firefly/assets/100352899/6d53547d-9ca2-4e1d-bdee-fb894c6ec79e)

For example, the last nft sent is not shown, and the native tokens, on restored profile is shown as `sent` and on original profile as `burned`

### Expected behaviour

Same activity history in both profiles

### Actual behaviour

Different activity history in both profiles

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Create a profile
2. Make a stronghold backup of the profile
3. Restore a profile from stronghold backup
4. Make transactions from this profile
5. Check that the activity histories of the profiles are different

### Operating System

Linux

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
Importing from sttonghold I believe should have the exact same tx history on all profiles, as stronghold serves as tx tracker too. We should investigate if this is an issue on our end or the sdk
