### ISSUE TITLE
[UI] Contrast for pre-set receiving account too low

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/firefly#716]
## Issue description

If you have exactly two accounts, firefly fills out the receiving account if you open the "Internal Transfer" tab. The contrast of the pre-filled account is too low and therefore hardly visible.

## Wallet version

v0.3.1

## System specification

macOS 11.3 Beta

## Steps To reproduce the issue

1. Make sure you have exactly two accounts
2. Open the "Internal Transfer" tab

## Errors

<img width="376" alt="Bildschirmfoto 2021-03-23 um 16 55 47" src="https://user-images.githubusercontent.com/17240275/112178479-0fe9d680-8bfa-11eb-957d-29c5ff86b3c5.png">

**Comment by JanOonk** [comment]
When you have more than 2 accounts the contrast is better:
![1](https://user-images.githubusercontent.com/13236774/112295576-5429b500-8c94-11eb-9aab-c42af199e2fc.jpg)

**Comment by obany** [comment]
This should be fixed with the next release, please re-open if there are still issues.
