### ISSUE TITLE
Portfolio timeline display in currency MIOTA

### ISSUE THREAD

**Issue by github-i286** [iotaledger/firefly#718]
## Description
The portfolio can be displaed in a timeline for USD, BTC, etc. It woudl be usefull to display history in MIOTA "currency", how much net deposit and withdraws has been done in view of MIOTAs.

## Motivation
View net add and spends over time in MIOTAs

## Requirements

Add MIOTA to the list of currences.

## Open questions (optional)
N/A

## Are you planning to do it yourself in a pull request?
No.

**Comment by rafaeldjpbrochado** [comment]
I'd like this as well!
