### ISSUE TITLE
adding acccount, starts sending transaction from an old account to itself.

### ISSUE THREAD

**Issue by wonkytonky2** [iotaledger/firefly#721]
## Issue description

after messing around sending money internally alot and after deleten and adding accounts 

for some reason  now when i add account it takes a lot of time.  and it is doing an tx in background sending existing wallet money in another  acount to itself making a real tx on tangle. 
![image](https://user-images.githubusercontent.com/48189056/112226333-548f6500-8c2e-11eb-95b4-035a95f5c2e7.png)
![image](https://user-images.githubusercontent.com/48189056/112226497-81dc1300-8c2e-11eb-8925-b2d6b26e7cd6.png)
it pretents to send money to this new acount 5 i created but it didnt do it in reality

![image](https://user-images.githubusercontent.com/48189056/112226618-a932e000-8c2e-11eb-9a46-56f67f8ef848.png)
when trying to send money internaly it shows the same acount  3 times although there are more acounts then "account6"

## Wallet version
3.1 beta

## System specification

What is your operating system?

win 10

## Is it a repeatable issue?

in my wallet yes, i dont know how i got there
it keeps happening 

## Steps To reproduce the issue
try to import my backup

pin is 555555
http://www.filedropper.com/firefly-backup-2021-03-23t22-07-00

password : give me a name in discord i should contact

lets hope you can reproduce it this way.
## Expected behaviour

just add acount don't do wierd stuff like sending tx to itself in other wallets

**Comment by cvarley100** [comment]
Hey please contact me (Charlie) on Discord with the Stronghold and password.

**Comment by wonkytonky2** [comment]
update : so i created a new profile and could  reproduce it manually :   create few accounts
acount 1
acount 2 
etc..
 send money  trough them .. from 1 to  last one you created

 then remove the first account 
  then add new acount again and then the problems seem to start

**Comment by obany** [comment]
This should be fixed with the next release, please re-open if the problem persists
