### ISSUE TITLE
Stronghold backup date is not recognized correctly

### ISSUE THREAD

**Issue by Travetown** [iotaledger/firefly#723]
## Issue description

Today is March 24th and this will appear on my wallet. The last backup was yesterday.

Perhaps the calculation is not based on the date, but on the basis of 24 hours. However, this would then have to be represented differently.

## Wallet version

0.3.1

-- MacOS 11.2.3
<img width="827" alt="Bildschirmfoto 2021-03-24 um 07 16 22" src="https://user-images.githubusercontent.com/66588710/112264452-36972400-8c71-11eb-8c98-e06940658dd9.png">

**Comment by myhrmans** [comment]
The calculation is actually checked to see if [your backup is older than one month](https://github.com/iotaledger/firefly/blob/f6d0504f551d222ed69f21d3f92269f512f3cc45/packages/shared/routes/dashboard/wallet/views/Security.svelte#L24). And from what I can see and test the [calculations are correct](https://github.com/iotaledger/firefly/blob/f6d0504f551d222ed69f21d3f92269f512f3cc45/packages/shared/lib/helpers.ts#L110). So you should not actually get that window until a month has passed from the original backup. Something must have gone wrong somewhere else.

**Comment by Travetown** [comment]
Now the display is correct again. So it's up to the 24 hours.

<img width="482" alt="Bildschirmfoto 2021-03-24 um 08 34 52" src="https://user-images.githubusercontent.com/66588710/112272015-eb364300-8c7b-11eb-881b-640097bf6442.png">

**Comment by obany** [comment]
This should be fixed in the next release, please re-open if it persists.
