### ISSUE TITLE
Error: "This ist greater than your available balance"

### ISSUE THREAD

**Issue by Travetown** [iotaledger/firefly#724]
I tried to send the maximum amount and got the error (see screenshot). Then I tried to send 200 MI and got the same error. Sending 100 MI worked.
I assume that this is due to the fact that the balance was on several addresses.

<img width="1261" alt="Bildschirmfoto 2021-03-24 um 10 19 38" src="https://user-images.githubusercontent.com/66588710/112286981-2cceea00-8c8c-11eb-9544-f9a75882ff0d.png">

**Comment by Phyloiota** [comment]
simmilar to #620

**Comment by Travetown** [comment]
Ups

**Comment by Travetown** [comment]
see #620
