### ISSUE TITLE
[Bug report]: Balance not fully operational

### ISSUE THREAD

**Issue by Xirdas999** [iotaledger/firefly#7255]
### Platform

Desktop

### Version

1.7.2

### Description

It seems that a part of my IOTA coins in my firefly wallet is not operational; Firefly shows the correct balance; but I cannot stake or tansfer all of my coins. In the background a part of my coins seems to be missing. In the tangle explorer I find it on another wallet name; maybe I was using another wallet (Wallet 2) which was not transferred correctly after an update, but I am not sure and the total balance displayed in my firefly is correct. However this issue occurs after an transaction with conflicts (see below).

### Expected behaviour

All of my coins should be able to be staked or transfered. 

### Actual behaviour

A part of my IOTA balance is not operational.

### Can the issue reliably be reproduced?

No

### Operating System

Windows

### Diagnostics

```shell
Version 1.7.2
Sprache: de
Währung: EUR
Node-Auswahl: Automatisch
Plattform: win32
Plattformversion: 10.0.19045
Plattform-Architektur: x64
CPU-Anzahl: 4
Gesamtspeicher: 8115.3 MB
Freier Speicher: 3363.4 MB
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Actively staking

### Crash Status

None of the above

### Error Messages

The error occured after conflicts in an ttransaction: Message ID:
62b9580bcef1c05dcb18a1675b39a74765f6414e8cbcdd4974bbe0b8efab0bc3

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Xirdas999** [comment]
one additional info, the missing funds are displayed under the following address:

https://explorer.iota.org/mainnet/message/427cc4609b564c77be6a45fe90de849ece3f7a38b2a980a43fe0b06447fd6444

**Comment by marc2332** [comment]
Hey @Xirdas999 , IOTA chrysalis has been deprecated. Do you mind giving the latest release (v2.0.2 at the time of writing this) a try and letting us know if you have any other issues?

Please read https://blog.iota.org/stardust-upgrade-iota-tokenomics/. The assembly project does not exist anymore, but your rewards got airdropped to you in form of IOTAs. They will appear in the new version 2.0.2 in the vesting tab. If you are missing balances you can run the balance finder from settings > advanced > balance finder, or if you are missing rewards you can also run the rewards finder from the vesting tab, the '....' menu, search vesting rewards

**Comment by Xirdas999** [comment]
Hi Marc, thx for your help. I checked and atm all is working fine again. The bug semmes to be fixed with the update :)
