### ISSUE TITLE
[Bug report]: Cannot claim SMR Staking rewards

### ISSUE THREAD

**Issue by cruuxoxo** [iotaledger/firefly#7283]
### Platform

Desktop

### Version

2.1.4

### Description

When claiming SMR rewards in latest firefly shimmer release via Recovery Phrase, the process gets stuck in claiming rewards screen. No error message shown. Followed the guide multiple times, tried from different systems and networks.

![image](https://github.com/iotaledger/firefly/assets/122932378/5b507c74-6889-4378-bacd-3b0d7db262ce)

### Expected behaviour

successful claiming of tokens

### Actual behaviour

claiming process is stuck forever

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

Infinite loading symbol

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
We apologize for the trouble, this is a known bug. We already have the fix merged https://github.com/iotaledger/firefly/pull/7279 and will be integrated in our next release

**Comment by Ahib** [comment]
you need more acc to reproduced? I have the same bug. Can't clame my shimmer reward too. Waitig for the nex´t release.

**Comment by cruux13** [comment]
you may want to try the beta 2.1.5, worked for me

**Comment by Ahib** [comment]
yes 2.1.5. worked for mee too
