### ISSUE TITLE
Negative balance on an account

### ISSUE THREAD

**Issue by Travetown** [iotaledger/firefly#729]
I have made many transactions in quick succession. Now I have a negative balance on an account.

I haven't changed anything since then and could also make the Stronghold file available if the individual transactions need to be traced.

<img width="375" alt="Bildschirmfoto 2021-03-24 um 17 48 58" src="https://user-images.githubusercontent.com/66588710/112351086-ded8d700-8cc9-11eb-9d40-a097c1c5a203.png">
<img width="355" alt="Bildschirmfoto 2021-03-24 um 17 48 04" src="https://user-images.githubusercontent.com/66588710/112351099-e1d3c780-8cc9-11eb-81e6-d3ee5ec22e1c.png">

**Comment by dcher44** [comment]
I managed to reproduced quite easily the issue by processing several sending , without waiting for the update on the account.
Nevertheless after some time, when you got a timeout on firefly and you need to connect again with pin code, the balance is correctly set to 0.

**Comment by Travetown** [comment]
Yes, after restarting the wallet, everything is fine again.
Nevertheless, the wrong display should be prevented.

**Comment by cvarley100** [comment]
This should be fixed in the next version. If you experience balance problems in the next version, please reopen this issue.
