### ISSUE TITLE
[Fix]: Enable blind signing when sending transactions with tag in ledger

### ISSUE THREAD

**Issue by cpl121** [iotaledger/firefly#7301]
### Task description

When making a base token transaction, it is not necessary to have blind signing enabled, but when adding a `tag` and/or a `metadata` firefly show a popup to enable it and it does not let the transaction be done if it is not enabled

### Requirements

The popup to enable blind signing should not appear when performing a transaction with tag and/or metadata

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
Ive asked about this and its necessary because the information doesnt fit in ledger so it needs blind signing with a hash only
