### ISSUE TITLE
[Bug report]: Cant claim my Shimmer using Stronghold File

### ISSUE THREAD

**Issue by 1245986** [iotaledger/firefly#7316]
### Platform

Desktop

### Version

2.1.4

### Description

I have a MIOTA Firefly, where i was staking back in 2021. Now I wanted to claim my Shimmer.
So I installed the newest Version of Fierfly & Firefly Shimmer. When installing the Firefly Shimmer I tried to import my stronghold file that I had created before. Now im getting an error code that says that they are unable to initialize an Shimmer claiming Account.
What am I supposed to do to get the rewards into the firefly shimmer wallet?
And I am trying via stronghold, cause I don't have the seed anymore.

Thanks for your help guys
![Shimmer](https://github.com/iotaledger/firefly/assets/142113079/9078a8a0-7b58-4cb1-8cae-cd1386302407)

### Expected behaviour

I hope someone can help out

### Actual behaviour

Cant find a way to get my shimmer, even it's listed on Firefly, I cant claim or send it to the Firefly Shimmer

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Diagnostics

```shell
Version 2.1.4
Language: en
Platform: win32
Platform Version: 10.0.19045
Platform Architecture: x64
CPU Count: 16
Total Memory: 32713.5 MB
Free Memory: 23164.8 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

Unable to Inizialize Shimmer claiming Account

### Error Logs

```shell
Sat, 12 Aug 2023 17:49:59 GMT
BaseError: Error: Unable to initialize Shimmer claiming account

Sat, 12 Aug 2023 17:49:59 GMT
BaseError: undefined
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
We apologize for the trouble, we have a known bug around shimmer rewards claiming. We released a beta version which should fix your problem https://github.com/iotaledger/firefly/releases/tag/desktop-2.1.5-beta-1 you can either try that or wait for the production version to be out, which will be soon.
Please reopen the issue if necessary
