### ISSUE TITLE
Firefly won't start "Cannot read property 'data' of null"

### ISSUE THREAD

**Issue by TGro89** [iotaledger/firefly#732]
## Issue description

Sent atoi to my own second profile, sending process never ended. Closed Firefly for restart but won't enter wallet after restarting, only logo appears but nothing happens for hours... can click on burgermenu, but doesn't appear to help the process

## Wallet version
Firefly
0.3.1

## System specification

win10
build19042

## Is it a repeatable issue?

N

## Expected behaviour

Restart Firefly > choose profile > enter pw > send and receive

## Actual behaviour

just Firefly logo and burgermenu appears

## Errors

clicking "Fehlerprotokoll" or any other won't cause any action
![firefly_fail](https://user-images.githubusercontent.com/81326274/112370338-8b708400-8cdd-11eb-90e5-f72fbd3ffb6b.jpg)

**Comment by TGro89** [comment]
This is what the console says:
C:\Users\xyz\…\build\preload.js:1 Uncaught Error: Uncaught TypeError: Cannot read property 'data' of null
    at C:\Users\xyz\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:1:17674
    at C:\Users\xyz\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:1:24580
    at Array.forEach (<anonymous>)
    at destroy (C:\Users\xyz\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:1:24568)
    at C:\Users\xyz\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:1:19467

**Comment by obany** [comment]
Did you have a custom currency selected ?

**Comment by TGro89** [comment]
> 
> 
> Did you have a custom currency selected ?

Can you specify?

**Comment by obany** [comment]
Did you go into the settings and change your currency from the default USD.

**Comment by obany** [comment]
ok thanks, there is a problem with custom currencies in the current version, the changes in the next build should fix the issue you were seeing.

**Comment by TGro89** [comment]
ok, is it capable of updating automatically or do I have to reinstall?

**Comment by TGro89** [comment]
never mind, I can update before clicking my profile. Thanks for your support!

**Comment by obany** [comment]
The new build is not yet released, you will have to reinstall when it is released

You can completely reset your current version by removing the contents of

`C:\Users\xyz\AppData\Roaming\Firefly Beta`

**Comment by TGro89** [comment]
Removed content as described above, recovered from backup, now able to enter but shows wrong balance. Closed Firefly while being in an infinite transaction process in the first case ... anything to do with that maybe? (Total received 40Mi>total send 1 Mi>Total Balance 27 Mi)

**Comment by obany** [comment]
There are a few known issue with balances, I would ignore them for now
