### ISSUE TITLE
shown view flips from settings or account detail back to main if a tx is proccessing.

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#734]
## Issue description

User Tobi MZ reported the issue first, i tested and can confirm...
If an tx is issued and you switch the screen to setting or account detail or any setting detail page, after a few seconds, the screen flips back to the main view (before the ongoing tx seems finished / maybe during pow)

## Wallet version
Firefly v0.3.1
Platform: win32
Platform Version: 10.0.19041
Platform Architecture: x64
CPU Count: 4

## Is it a repeatable issue?

yes

## Steps To reproduce the issue

issue a tx (internal transfer)
click directly after starting the tx on "settings" and wait there 
after 5 - 10 seconds the view flips back to the Main wallet view

## Expected behaviour

screen should stay where i wanted it to be

## Actual behaviour

screen flips tp main view without user command

## Errors
here the console, but thats i think all old - during the issue no new errors show up in console
[console.txt](https://github.com/iotaledger/firefly/files/6204124/console.txt)

and the wallet error log, also mostly old...

[error log.txt](https://github.com/iotaledger/firefly/files/6204144/error.log.txt)

two recordings of the behaviour:

https://user-images.githubusercontent.com/77154511/112463328-0ea4df00-8d9d-11eb-9d3b-b104e802a0ea.mp4

https://user-images.githubusercontent.com/77154511/112463521-51ff4d80-8d9d-11eb-94da-6597752e0bba.mp4

**Comment by obany** [comment]
This is fixed in the next release, please re-open if it persists.
