### ISSUE TITLE
[Bug report]: Firefly no response from btn after wrong string entry in nft tab

### ISSUE THREAD

**Issue by sl00k** [iotaledger/firefly#7340]
### Platform

Desktop

### Version

2.1.5

### Description

Wallet crashes when inserting wrong string in nft send tab

### Expected behaviour

no crash

### Actual behaviour

crash

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Log in the account
click send asset
switch to nft sending
insert receiver address in the nft tag field
go back to send token (because I thought the nft field would be blank again - faster than deleting the string)
go back to nft tab
FF "crashes" can not click on any btn

### Operating System

Windows

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

Non-responsive

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
Hi, thanks for reporting! Is the version you are using really `1.7.1`? For Shimmer it should be 2.x.y. If you could please correct that it would help us debugging

**Comment by MarkusGolser** [comment]
App Version: 1.7.3

platform: macOS
platformVersion: 11.7.8
platformArchitecture: x64
cpuCount: 4
totalMem: 8192.0 MB
freeMem: 641.2 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: dlopen(/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node, 1): Symbol not found: __ZNSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE7seekoffExNS_8ios_base7seekdirEj
  Referenced from: /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node

**Comment by MarkusGolser** [comment]
Hallo! Was soll ich machen?

**Comment by begonaalvarezd** [comment]
> App Version: 1.7.3
> 
> platform: macOS platformVersion: 11.7.8 platformArchitecture: x64 cpuCount: 4 totalMem: 8192.0 MB freeMem: 641.2 MB
> 
> Error Type: [Preload Context] Error
> 
> Error: node-loader: Error: dlopen(/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node, 1): Symbol not found: __ZNSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE7seekoffExNS_8ios_base7seekdirEj Referenced from: /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node (which was built for Mac OS X 13.0) Expected in: /usr/lib/libc++.1.dylib in /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node

Hi, this is a different issue that we already found and will release a new version soon https://github.com/iotaledger/firefly/issues/7324
