### ISSUE TITLE
Text in privacy policy & terms of use

### ISSUE THREAD

**Issue by Pyretex** [iotaledger/firefly#743]
Hey!

When installing the finnish version of firefly the text in terms of use and privacy policy is in latin. Everything els is in finnish. Is there a translation done for finnish?

![termsofuse](https://user-images.githubusercontent.com/81362902/112503682-ce8d2e80-8d93-11eb-9c36-064121b18816.jpg)

**Comment by obany** [comment]
These translations are not yet done
