### ISSUE TITLE
[Task]: Fix network id mismatch error

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#7437]
### Task description

Reported on Firefly Shimmer 2.1.7-beta-1
Seems like when we can get the information from the node, firefly throws a network id mismatch error, we should improve this error management, and if the node doesnt return a network id, it might be because the node is unreachable
https://discord.com/channels/397872799483428865/1148183829866106880/1152324925026218025

### Requirements

Fix network id mismatch error

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by msarcev** [comment]
Couldn't reproduce the issue. Probably caused by stale profile state.
