### ISSUE TITLE
Total Balance is temporarily incorrect

### ISSUE THREAD

**Issue by antalm** [iotaledger/firefly#745]
## Issue description

Total Balance is temporarily incorrect: individual account balances don't add up to the Total Balance and Total Balance shows more than my actual total balance (80.05 Mi instead of the correct 65.05 Mi).

![firefly_total_balance_two_way_transactions_in_progress](https://user-images.githubusercontent.com/29548853/112517343-7f95c800-8d98-11eb-8a08-faef4e8d51e7.png)

## Wallet version

v0.3.1

## System specification

Arch Linux

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

1. Have at least 2 accounts in your profile. In this test I used Test1 and Test2 accounts.
2. Send 15 Mi from Test1 to Test2 then immediately send 10 Mi from Test2 to Test1 before the first transaction finished.
3. When two-way transactions are in progress the Total Balance is too much, also the manual sum of account balances are too much:
![firefly_total_balance_two_way_transactions_in_progress](https://user-images.githubusercontent.com/29548853/112517343-7f95c800-8d98-11eb-8a08-faef4e8d51e7.png)

## Expected behaviour

1. I would expect that at least Total Balance and manual sum of account balances match up at any given time. Update the Total Balance and the account balances in an atomic way so that they are in sync at any given time.
2. Total Balance should never be more than it actually is. Do not update the Total Balance before the transaction gets confirmed.

## Actual behaviour

1. Firefly temporarily shows 85.05 Mi in the Total Balance, the manually calculated sum of account balances is 75.05 Mi.
2. Total Balance is temporarily 85.05 Mi even though I have only 65.05 Mi in total.

After waiting a few seconds for the two-way transactions to finish both Total Balance and the manual sum of account balances corrects to 65.05 Mi:
![firefly_total_balance_two_way_transactions_finished](https://user-images.githubusercontent.com/29548853/112517357-845a7c00-8d98-11eb-88d6-852ac0add563.png)

**Comment by delarosan1** [comment]
A mi me ha pasado igual 

https://prnt.sc/10wab2x

**Comment by cvarley100** [comment]
This is fixed in the next version. If you see something similar please open another issue.
