### ISSUE TITLE
[Bug report]:

### ISSUE THREAD

**Issue by hpk2504** [iotaledger/firefly#7451]
### Platform

Desktop

### Version

1.7.5

### Description

App Version: 1.7.5

platform: macOS
platformVersion: 10.12.6
platformArchitecture: x64
cpuCount: 4
totalMem: 8192.0 MB
freeMem: 2049.4 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: dlopen(/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node, 1): Symbol not found: __ZdlPvSt11align_val_t
  Referenced from: /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node
  Expected in: /usr/lib/libc++.1.dylib
 in /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node

### Expected behaviour

open firefly

### Actual behaviour

cannot open firefly

### Can the issue reliably be reproduced?

Yes

### Operating System

Mac

### Diagnostics

```shell
App Version: 1.7.5

platform: macOS
platformVersion: 10.12.6
platformArchitecture: x64
cpuCount: 4
totalMem: 8192.0 MB
freeMem: 2049.4 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: dlopen(/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node, 1): Symbol not found: __ZdlPvSt11align_val_t
  Referenced from: /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node
  Expected in: /usr/lib/libc++.1.dylib
 in /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
Hi, in the latests releases we dropped support in Firefly IOTA for versions of mac < 10.14, we recommend upgrading your machine so you can get security updates for your macOS

**Comment by hpk2504** [comment]
Hello! thx a lot for help. I have already bought a new mac and installed a firefly wallet there. 
Is it possible to transfer the tokens from the old mac to the new mac? 
to be honest, i dont know how to upgrade the old one :) 
... i am really gratefull for your help!!!

**Comment by begonaalvarezd** [comment]
> Hello! thx a lot for help. I have already bought a new mac and installed a firefly wallet there. Is it possible to transfer the tokens from the old mac to the new mac? to be honest, i dont know how to upgrade the old one :) ... i am really gratefull for your help!!!

Sure, you can restore a profile in your new machine by using your last stronghold backup or your 24 words mnemonic

**Comment by hpk2504** [comment]
Thx a lot!!!

Am 01.10.2023 um 08:48 schrieb Begoña Álvarez de la Cruz ***@***.***>:

﻿

Hello! thx a lot for help. I have already bought a new mac and installed a firefly wallet there. Is it possible to transfer the tokens from the old mac to the new mac? to be honest, i dont know how to upgrade the old one :) ... i am really gratefull for your help!!!

Sure, you can restore a profile in your new machine by using your last stronghold backup or your 24 words mnemonic
