### ISSUE TITLE
Incorrect Balance after using the same seed over 2 Firefly wallets (2 different computers)

### ISSUE THREAD

**Issue by EKO-IOTA** [iotaledger/firefly#746]
## Issue description

I created a wallet with a seed on my MBP and created two internal accounts in it for testing (total balance: 102Mi). Then I also created a wallet with the same seed on my iMac and all the Miotas were there and then I just wanted to split the Miotas equally between both accounts with 51Mi (Message ID: 786a0057789241fd5bdd960fab29021b48d8842370e055e8c3f0dc058aa94c2b) each and this was also transferred and displayed correctly on my iMac. Then I logged back on my MBP and there was only on one account 51Mi but on the 2nd account were 0Mi. Btw the total income amount should be 102Mi and not 153Mi as shown in the picture.
<img width="1392" alt="Bildschirmfoto 2021-03-25 um 19 22 34" src="https://user-images.githubusercontent.com/81235754/112523849-7a884700-8d9f-11eb-9f9d-625820930c77.png">

## Wallet version

Which version of wallet are you using?

Both wallet versions are 0.3.1 

## System specification

What is your operating system?

MBP: macOS Big Sur - Version 11.2
iMac: macOS High Sierra - Version 10.13.6

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Creating a new seed and wallet on the first Mac(MBP).
2. Getting some tokens from the faucet.
3. Creating an "internal" second account on the first wallet. ("Account 1" and "TEST" as shown in the pic)
4. Transferring all Tokens to the new (second) account "TEST".
5. Creating a new wallet with the same seed as above on the second Mac (iMac).
6. Logging out and closing from the wallet on the MBP.
7. Transferring 51Mi from the "TEST" account to "Account 1" on the iMac.
8. On the iMac it total balance and each account balance shows up correctly.
9. Opening and logging in on the wallet on the MBP.
10. Incorrect showing of the balances on the MBP.

## Expected behaviour

The balances should be displayed correctly on the wallet regardless of which computer I log in to.

## Actual behaviour

As described above.

**Comment by cvarley100** [comment]
This should be fixed in the next version (by pressing sync). Please reopen if not.
