### ISSUE TITLE
[Task]: Improve error message when sending all funds to L2

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#7468]
### Task description

Because gas fees are added on top of the amount, the tx cant proceed but the error message is confusing, we should explain the user that because of the gas fees they cant send all, we could display them how much they could send max
![image](https://github.com/iotaledger/firefly/assets/3624944/32e9211c-0a89-4fac-8ef1-791e324db7ce)

### Requirements

improve l1-l2 max funds error message

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by JannemanDev** [comment]
Even better and simpler would be for the user is to add a button or something which adapts the send amount (old - fee) and proceed with the flow. Else the user needs the remember the new amount or even worse the fee amount and do the subtraction himself.

**Comment by begonaalvarezd** [comment]
Lets first do the refactor https://github.com/iotaledger/firefly/issues/7508 and then improve the UX
