### ISSUE TITLE
[Task]: Update references/links of Shimmer to IOTA

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#7483]
Change links/references that mention Shimmer to IOTA (e.g docs, readme, etc)

Example from the readme:
![image](https://github.com/iotaledger/firefly-private/assets/38158676/5ef73afd-79b9-49ad-8210-e95aaed3dbc6)

**Comment by Joseadames2323** [comment]
hola mw podrian ayudar con la nueva descarga de shimmer firefly, la descargo en mi mac pero al abrirme me sale solo el logo de firefly y al instante se quita quedando la wallet en blanco sin poder acceder o hacer algo en ella !

**Comment by begonaalvarezd** [comment]
> hola mw podrian ayudar con la nueva descarga de shimmer firefly, la descargo en mi mac pero al abrirme me sale solo el logo de firefly y al instante se quita quedando la wallet en blanco sin poder acceder o hacer algo en ella !

Hola, por favor abre un issue https://github.com/iotaledger/firefly/issues/new?assignees=&labels=bug+report&template=bug_report.yml&title=%5BBug+report%5D%3A o escribemos en los canales help o firefly support en discord e intentaremos ayudarte https://discord.iota.org/
