### ISSUE TITLE
Incorrect Send payment section - Amount window words entering values.

### ISSUE THREAD

**Issue by NOUNero** [iotaledger/firefly#750]
![Firefly wallet bug1](https://user-images.githubusercontent.com/34715285/112601139-c0cebc00-8e1a-11eb-922d-e3eec5d20ccf.PNG)

**Comment by obany** [comment]
I am not sure what the error is here, could you explain more ?

**Comment by cvarley100** [comment]
@obany perhaps he means the error message should change depending on the selected unit?
