### ISSUE TITLE
[Bug report]: Updating to Alpha 2 fails with error

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#7511]
### Platform

Desktop

### Version

2.0.0. Alpha2

### Description

Wallet shows new version is avalible.

When you are logged in a profile and download the update, then logout of the profile, an error occurs.
After this every update attempt fails with the same erroro

### Expected behaviour

no errors

### Actual behaviour

App Version: 2.0.0-alpha-2

platform: macOS
platformVersion: 14.0
platformArchitecture: x64
cpuCount: 8
totalMem: 8192.0 MB
freeMem: 24.7 MB

Error Type: [Main Context] Unhandled Rejection

Error: Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. See https://github.com/Squirrel/Squirrel.Mac/issues/182 for more information.

### Can the issue reliably be reproduced?

Yes

### Operating System

Mac

### Diagnostics

```shell
Version 2.0.0-alpha-2
Language: en
Platform: macOS
Platform Version: 14.0
Platform Architecture: x64
CPU Count: 8
Total Memory: 8192.0 MB
Free Memory: 17.9 MB
```

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

App Version: 2.0.0-alpha-2

platform: macOS
platformVersion: 14.0
platformArchitecture: x64
cpuCount: 8
totalMem: 8192.0 MB
freeMem: 24.7 MB

Error Type: [Main Context] Unhandled Rejection

Error: Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. See https://github.com/Squirrel/Squirrel.Mac/issues/182 for more information.

### Error Logs

```shell
-
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
Thanks for reporting 🙏🏼 We would have a look but to me this looks like an electron issue, we should upgrade to newer versions 🤞🏼

**Comment by begonaalvarezd** [comment]
@Phyloiota Did you experience this issue upgrading to the production version 2.0.2?

**Comment by Phyloiota** [comment]
Hey Begona. Nope no more errors while updating to the next version. Thanks
