### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by pfms1** [iotaledger/firefly#7516]
### Platform

Desktop

### Version

1.7.3

### Description

App Version: 1.7.3

platform: macOS
platformVersion: 10.13.6
platformArchitecture: x64
cpuCount: 4
totalMem: 4096.0 MB
freeMem: 834.7 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: dlopen(/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node, 1): Symbol not found: __ZNSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE7seekoffExNS_8ios_base7seekdirEj
  Referenced from: /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node

### Expected behaviour

App up and running

### Actual behaviour

App Version: 1.7.3

platform: macOS
platformVersion: 10.13.6
platformArchitecture: x64
cpuCount: 4
totalMem: 4096.0 MB
freeMem: 834.7 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: dlopen(/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node, 1): Symbol not found: __ZNSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE7seekoffExNS_8ios_base7seekdirEj
  Referenced from: /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node

### Can the issue reliably be reproduced?

Yes

### Operating System

Mac

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

App Version: 1.7.3

platform: macOS
platformVersion: 10.13.6
platformArchitecture: x64
cpuCount: 4
totalMem: 4096.0 MB
freeMem: 834.7 MB

Error Type: [Preload Context] Error

Error: node-loader:
Error: dlopen(/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node, 1): Symbol not found: __ZNSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE7seekoffExNS_8ios_base7seekdirEj
  Referenced from: /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
We have mitigated this issue recent version, please upgrade to V1.7.5, you can download it from the official website https://firefly.iota.org/. We do not support macOS version < 10.14 though, since those versions have reached the official end of life some time ago. We recommend you upgrade your macOS version so you can receive official security updates
