### ISSUE TITLE
Export funtionality does not work properly for non english versions

### ISSUE THREAD

**Issue by plessmann** [iotaledger/firefly#7529]
### Platform

Desktop

### Version

1.7.5

### Description

Export funtionality does not work properly for non english versions of firefly
The export format is broken if language/I18N settings are set to de_DE e.g. (depends on the configured decimal seperator). In some situations the formatted value breaks the CSV field separator in the output file!

In my mind the full export format needs rework. Its absolutely not helpful what Firefly outputs. Neither an operation type is included, nor the currency symbol is included since there are subtokens available (SVM and ASM). 
Please also consider to put an ISO Datetime as one single column instead of 2 separate fields as other exchanges or wallets do to be more compatible!

### Expected behaviour

As minimal solution to fix the issue: if a coma separated value is excpected in the output, you need to escape the value by double quotes!

E.g.:
```
Message ID,Intern,Rohwert,Formatierter Wert,Datum,Uhrzeit
1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef,false,555555555,"555,555555 Mi","11. Sept. 2021","10:04 MESZ"
```

If a complete export rework is possible, the follwing format would be fine and help the consumers of Firefly:

1. There is no need to translate the coumn names in specific languages. Keep it just english, to make the export file more compatible all over the world
2. Just use an export format based on LedgerLive, which helps to process the output automatically and procesable for tax applications e.g.:

```
Date,"Sent Amount","Sent Currency","Received Amount","Received Currency","Net Worth Amount","Net Worth Currency",Label,Description,Message ID
"2022-01-31 23:59:59",,,688240999,IOTA,860.3,EUR,Deposit,,1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
```

As label there are options like: Deposit, Withdrawal, Staking, Reward, Cost, Gift ....

### Actual behaviour

```
Message ID,Intern,Rohwert,Formatierter Wert,Datum,Uhrzeit
1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef,false,555555555,555,555555 Mi,11. Sept. 2021,10:04 MESZ
```
555,555555 Mi will break the CSV format because its detected as 2 columns: 555 and 555555 Mi.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Open Firefy latest version
2. Open a wallet with some transactions
3. Export the Transaction history to a file (CSV)
4. Try to import with MS Excel or LibreOffice Calc

### Operating System

Windows

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Previously staked

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marc2332** [comment]
Hey @plessmann, Chrysalis (Firefly v1.X.X) has been deprecated. We do no longer have this feature in the latest releases (v2.X.X) either. So, I am gonna close this.

**Comment by janviehweger** [comment]
hey @plessmann, i've reported the same issue allready here [#6854](https://github.com/iotaledger/firefly/issues/6854). Unfortunately it has also been closed. My workaround is/was to switch firefly to 'English', where the errors do not appear. Cheers
