### ISSUE TITLE
Long transaction time

### ISSUE THREAD

**Issue by klemp** [iotaledger/firefly#753]
## Issue description

I am trying out the new firefly wallet and I'm sending funds from one wallet account to another. The transaction takes quite a while (more than a minute) which is a lot more than 10 s that are being advertised by IF.
 Also when I sign in it takes a minute for transactions to sync.

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch):
0.3.1
## System specification

What is your operating system?

Win 10 Enterprise

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

I am not doing anything special, only ordinary use of wallet
1.
2.
3.

## Expected behaviour

Quick transaction

## Actual behaviour

Slow transaction

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by Travetown** [comment]
It is not the transaction itself that takes so long, but the preparation of the transaction. Once the transaction is in the Tangle, it is also confirmed very quickly. The number of UTXOs also determines how much time it takes to prepare the transaction.

At the moment there seems to be a (known) bug in the Chrysalis node, which causes a high CPU load when updating the data.

https://discord.com/channels/397872799483428865/786955911595687946/824178704291856386
