### ISSUE TITLE
[Bug report]: Failed To Update To Firefly 2.0

### ISSUE THREAD

**Issue by Sayvai** [iotaledger/firefly#7534]
### Platform

Desktop

### Version

1.7.5

### Description

After successfully logging in, I receive a toast notification that `Something went wrong`.

<img width="1392" alt="Firefly-Error-After-Login" src="https://github.com/iotaledger/firefly/assets/7581546/9595b8a9-07d0-4281-bf36-1c2525915b6f">

And then on the main dashboard, there is a notification to update the app. I clicked to update from within the menu and received an error that the update failed; `An error occurred during the update. Please try again`.

![Firefly-Update-To-2 0-Failure](https://github.com/iotaledger/firefly/assets/7581546/45d8f73e-ac6c-4682-babd-2c672ab18e2d)

### Expected behaviour

Firefly to have successfully updated to version `2.0`

### Actual behaviour

Firefly failed to update to version `2.0` from `1.7.5`

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

- Login
- See initial error message; `Something went wrong`
- Click to update version from menu
- During the download process, received message `An error occurred during the update. Please try again`

### Operating System

Mac

### Diagnostics

```shell
Nothing new reported in the Error log.

Diagnostics:

Version 1.7.5
Language: en
Currency: GBP
Node selection: Manual
Platform: macOS
Platform Version: 13.4
Platform Architecture: x64
CPU Count: 8
Total Memory: 16384.0 MB
Free Memory: 286.4 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

See description

### Error Logs

```shell
None generated for when the error occurred. Last error output was in 2022.
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
We are investigating, please update from the official website https://firefly.iota.org/

**Comment by begonaalvarezd** [comment]
The issue has been fixed, we had a wrong appId which made the auto update fail. Please download the latest version 2.0.2, and the issue should be solved from now on 🙏🏼 apologies for the troubles
