### ISSUE TITLE
[Bug report]:

### ISSUE THREAD

**Issue by sdellava** [iotaledger/firefly#7535]
### Platform

Desktop

### Version

2.0.0

### Description

After the successful first access to the wallet, now after inserting my profile pin, FF stuck on white screen.

### Expected behaviour

I'd like to see my IOTA :)

### Actual behaviour

after inserting my profile pin, FF stuck on white screen.

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Diagnostics

```shell
white screen
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

none

### Error Logs

```shell
none
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheNec** [comment]
Had the same problem: Empty dark blue (dark mode) background after installing and starting

The problem is that the old versions were installed to the user profile folder but the new one is installed to %programfiles%\firefly

Just start the correct software ;)

**Comment by begonaalvarezd** [comment]
We had a wrong appId so:
- Firefly 1.7.X had appId A
- Firefly 2.0.0 had appId B
- Firefly 2.0.1 has appId A
Which means that 2.0.1 will replace firefly 1.7.x but not 2.0.0. Please remove 2.0.0 from your systems if you still have it 🙏

**Comment by sdellava** [comment]
issue resolved.
