### ISSUE TITLE
[Bug report]: Only Assembly Airdrop funds are visible after stardust upgrade and not previous funds

### ISSUE THREAD

**Issue by emha** [iotaledger/firefly#7539]
### Platform

Desktop

### Version

2.0.1

### Description

In the firefly app I only see my received Assembly Airdrops. All my "normal" funds are not visible anymore.

### Expected behaviour

All my funds including Assembly Airdrop should be visible.

### Actual behaviour

None assembly airdrop funds are not visible.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Upgrade from 1.7.5 to 2.0.0 (or 2.0.1) by downloading the dmg from github

### Operating System

Mac

### Diagnostics

```shell
App Name: Firefly
Version 2.0.1
Sprache: de
Währung: usd
Node-Liste: https://api.stardust-mainnet.iotaledger.net
Plattform: macOS
Plattformversion: 13.6
Plattform-Architektur: x64
CPU-Anzahl: 12
Gesamtspeicher: 16384.0 MB
Freier Speicher: 137.8 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

Wed, 04 Oct 2023 10:33:06 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 09:51:41 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 09:51:09 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 09:51:09 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 09:51:09 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 09:50:44 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 09:50:44 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
Please run the balance finder in settings > advanced > balance finder. You might have funds sitting on high indexes

**Comment by emha** [comment]
That's it, thank you very much! :)
