### ISSUE TITLE
[Bug report]: "Chrysalis database migration failed" Error message

### ISSUE THREAD

**Issue by CrashOverride-lab** [iotaledger/firefly#7543]
### Platform

Desktop

### Version

2.0.1

### Description

After Upgrading from 1.7.5 to 2.0.1 when i try to open a Profile it says:

Wed, 04 Oct 2023 16:36:36 GMT
wallet: Chrysalis database migration failed: migration failed CipherError { alg: "XCHACHA20-POLY1305" }

I recovered for a test my old Ledger Firefly Folder from an old Backup. Uninstalled Firefly 2.0.1 and installed Firefly 1.7.5 --> Profile works like a charm. Upgrading it again to 2.0.1 --> Same Error see above.

In my Firefly are two profiles --> one based on Ledger and one from Stronghold. --> No one is accessible and after PIN-Entry the Error appears on both Profiles.

### Expected behaviour

A Clean Migration including all Transactions where in the Profile.

### Actual behaviour

See description

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

See Description

### Operating System

Windows

### Diagnostics

```shell
App Name: Firefly
Version 2.0.1
Sprache: de
Plattform: win32
Plattformversion: 10.0.22621
Plattform-Architektur: x64
CPU-Anzahl: 24
Gesamtspeicher: 32488.7 MB
Freier Speicher: 17552.8 MB
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

None

### Crash Status

None of the above

### Error Messages

wallet: Chrysalis database migration failed: migration failed CipherError { alg: "XCHACHA20-POLY1305" }

### Error Logs

```shell
wallet: Chrysalis database migration failed: migration failed CipherError { alg: "XCHACHA20-POLY1305" }
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marc2332** [comment]
Hey @CrashOverride-lab we have released a new version `2.0.2`, can you give it a try and let us know if this is fixed for you? :smile: 

Thank you!

**Comment by CrashOverride-lab** [comment]
Hi Marc,

unfortunatelly Version 2.0.2 only helps with the Problem on Stronghold Profile.

The Ledger Profile displays now:

![image](https://github.com/iotaledger/firefly/assets/85289600/082c3afd-0286-41bd-8685-75df5ead00b3)


But i was in Contact with Thoralf about this and he means, that in the Next Release this should be fixed. Can you estimate when the next Version will be available?

**Comment by begonaalvarezd** [comment]
> Hi Marc,
> 
> unfortunatelly Version 2.0.2 only helps with the Problem on Stronghold Profile.
> 
> The Ledger Profile displays now:
> 
> ![image](https://user-images.githubusercontent.com/85289600/274653878-082c3afd-0286-41bd-8685-75df5ead00b3.png)
> 
> But i was in Contact with Thoralf about this and he means, that in the Next Release this should be fixed. Can you estimate when the next Version will be available?

We found and fixed the issue you describe in this message too, we will release a new version as soon as possible

**Comment by begonaalvarezd** [comment]
Fixed by https://github.com/iotaledger/firefly/pull/7600 & https://github.com/iotaledger/firefly/pull/7572, we will release a new production version very soon
