### ISSUE TITLE
[Bug report]: Firefly Software wallet

### ISSUE THREAD

**Issue by fzwmyh** [iotaledger/firefly#7547]
### Platform

Desktop

### Version

2.0.1

### Description

Just downloaded the latest version (2.0.1) and when I try to open it all I get is a blank Firefly window with no way to put in my passcode.

<img width="1545" alt="Screenshot 2023-10-05 at 15 05 55" src="https://github.com/iotaledger/firefly/assets/31075302/341ea434-cc9e-4f3e-85ac-00d4d17de6d4">

### Expected behaviour

I expected that i would be taken to the passcode screen and then logged in once I had out in the code

### Actual behaviour

Blank screen

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Just by trying to login to the app

### Operating System

Mac

### Diagnostics

```shell
When I click on Diagnostics nothing happens.
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

None

### Error Logs

```shell
None
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CapnGerry** [comment]
I'm getting the same issue

**Comment by CapnGerry** [comment]
When I uninstall and reload older version I get as far as inputting my PIN No then get the white screen lock.

**Comment by JacKpoT-91** [comment]
I'm getting the same issue

**Comment by Narrenkappe** [comment]
Me too, Version 2.0.1 , MAC OS

**Comment by begonaalvarezd** [comment]
We are working on a fix, will release a new version asap

**Comment by fzwmyh** [comment]
Thank you very much.RegardsSteveSent from my iPadOn 8 Oct 2023, at 18:15, Begoña Álvarez de la Cruz ***@***.***> wrote:﻿
We are working on a fix, will release a new version asap

**Comment by Narrenkappe** [comment]
Thanks u so much for your support!! The new Version is working :)

**Comment by fzwmyh** [comment]
Thanks very much for this.  I shall try it later this evening.Kind regardsSteveSent from my iPadOn 9 Oct 2023, at 17:30, Begoña Álvarez de la Cruz ***@***.***> wrote:﻿
Closed #7547 as completed.
