### ISSUE TITLE
[Bug report]: wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

### ISSUE THREAD

**Issue by mcid21x** [iotaledger/firefly#7551]
### Platform

Desktop

### Version

2.0.1

### Description

Thu, 05 Oct 2023 17:51:59 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Thu, 05 Oct 2023 16:34:15 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Thu, 05 Oct 2023 16:32:09 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Thu, 05 Oct 2023 16:31:35 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Thu, 05 Oct 2023 16:31:12 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Thu, 05 Oct 2023 16:31:01 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Thu, 05 Oct 2023 16:30:54 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Thu, 05 Oct 2023 16:30:07 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Thu, 05 Oct 2023 16:24:30 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Thu, 05 Oct 2023 16:24:22 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Thu, 05 Oct 2023 16:24:10 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Thu, 05 Oct 2023 16:23:57 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Thu, 05 Oct 2023 16:23:41 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Thu, 05 Oct 2023 16:23:25 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 20:36:32 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 20:30:37 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 20:21:31 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 20:18:51 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 20:15:43 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 20:13:23 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 20:12:52 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 20:08:48 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 20:03:44 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 20:01:51 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 20:01:31 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 19:57:51 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 19:57:40 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 19:56:08 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 19:55:54 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 19:55:38 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 19:55:30 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 19:54:58 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 19:54:43 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 19:54:28 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 19:54:13 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 19:52:39 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 19:52:30 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 19:51:32 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 19:46:30 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 19:35:50 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 19:35:38 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 19:35:28 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 19:35:21 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 19:35:14 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 19:34:57 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 19:34:51 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 19:34:41 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 18:22:54 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 18:20:43 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 18:18:21 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 18:17:52 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 18:17:02 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 18:16:50 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 18:07:54 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 18:06:00 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 18:05:54 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 18:05:48 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 18:05:42 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 18:05:36 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 18:05:30 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 18:05:19 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 18:05:13 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 18:05:07 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 18:04:55 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:59:38 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:59:32 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:59:27 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:59:09 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:59:05 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:58:59 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:58:51 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:58:43 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:58:31 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:58:04 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:56:07 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:56:00 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:55:52 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:55:44 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:51:54 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:50:48 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:50:38 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:50:16 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:50:08 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:50:00 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:49:03 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:47:50 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:47:33 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:47:10 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:46:57 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:46:22 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 04 Oct 2023 17:46:17 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

### Expected behaviour

...

### Actual behaviour

...

### Can the issue reliably be reproduced?

Yes

### Operating System

Mac

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

Non-responsive

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
This is normal if you dont have enough outputs that can be consolidated you cant consolidate, you need at least 2 outputs and you have 1. You can wait until having more rewards unlocked or getting more funds to your account somehow. If you want to claim and you are getting this error, the claimable rewards are always yours to use as soon as they are unlocked, so dont worry about claiming, claiming will only consolidate them but the funds are your and available to use as soon as they are unlocked

**Comment by mcid21x** [comment]
Many thanks for your message. Since I have other accounts with more IOTa, if I transfer the low balance accounts to the larger ones, do you think I can claim the full rewards this way without disadvantages?Sincerely,Marcos Cid+41 78 733 47 ***@***.*** 9 oct. 2023 à 13:14, Begoña Álvarez de la Cruz ***@***.***> a écrit :﻿
This is normal if you dont have enough outputs that can be consolidated you cant consolidate, you need at least 2 outputs and you have 1. You can wait until having more rewards unlocked or getting more funds to your account somehow. If you want to claim and you are getting this error, the claimable rewards are always yours to use as soon as they are unlocked, so dont worry about claiming, claiming will only consolidate them but the funds are your and available to use as soon as they are unlocked

**Comment by begonaalvarezd** [comment]
Claiming is just a consolidation so the ledger cleans up from all these small outputs that the vesting rewards created, the unlocked payouts are ready to use at any time, we just need a way to guide the user to "claim" the rewards which puts all these outputs in a single one, hence reducing the whole size of the ledger. Long story short, you dont really need to claim anything, every output that is unlocked is ready to be used from the moment is unlocked.
