### ISSUE TITLE
[Bug Report]: `Chrysalis database migration failed: migration failed CipherError { alg: "XCHACHA20-POLY1305" }`

### ISSUE THREAD

**Issue by Ahframogxr** [iotaledger/firefly#7559]
### Platform

Desktop

### Version

2.0.1

### Description

Ich kann mich nach dem neuesten Update mit meinem PW in FF nicht mehr einloggen. Es kommt die Fehlermeldung:
wallet: Chrysalis database migration failed: migration failed CipherError { alg: "XCHACHA20-POLY1305" }

### Expected behaviour

Wallet müsste sich nach der Eingabe des PW öffnen.

### Actual behaviour

Ich komme nicht in die Wallet

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Diagnostics

```shell
App Name: Firefly
Version 2.0.1
Sprache: de
Plattform: win32
Plattformversion: 10.0.19045
Plattform-Architektur: x64
CPU-Anzahl: 4
Gesamtspeicher: 7918.8 MB
Freier Speicher: 2780.6 MB
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

None

### Crash Status

None of the above

### Error Messages

wallet: Chrysalis database migration failed: migration failed CipherError { alg: "XCHACHA20-POLY1305" }

Fehlermeldung nach dem neuesten FF Update. Ich komme mit meinem PW nicht mehr in FF. Die Meldung tritt auf. (4.10. und 7.10.2023)

### Error Logs

```shell
Sat, 07 Oct 2023 18:35:13 GMT
wallet: Chrysalis database migration failed: migration failed CipherError { alg: "XCHACHA20-POLY1305" }
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
We are working on a fix for this 🙏🏼 will try to provide a new version asap

**Comment by begonaalvarezd** [comment]
Duplicate https://github.com/iotaledger/firefly/issues/7559
