### ISSUE TITLE
[Task]: Fix `no password has been supplied or the key has been cleared from memory`

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#7574]
### Task description

https://discord.com/channels/397872799483428865/1159365054395850832/1159365054395850832
We cant reproduce the issue yet, need to keep investigating

### Requirements

Fix `no password has been supplied or the key has been cleared from memory`

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by begonaalvarezd** [comment]
Fixed by https://github.com/iotaledger/firefly/pull/7623

**Comment by fergzie** [comment]
Has this fix been released? I ask because I get this error i Firefly 2.0.2 and I now can't log in.

**Comment by begonaalvarezd** [comment]
Not yet, will be released very very soon 🙏🏼

**Comment by fergzie** [comment]
Awesome. Thanks for the quick reply. Looking forward to the release.
