### ISSUE TITLE
[Bug report]: Firefly forwards to incorrect URL from md link in participatrion

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#7586]
### Version

2.02, 2.18

### Description

The description of the participation event (additional Info text of the event) contains a md link to the governance forum. 
Forefly alters the URL and leads the user to a non existing page of the governance froum

### Expected behaviour

Link to the defined UrL specified in the Participation event

### Actual behaviour

It adscharacters to the url, in this case 

It opens this URL:
https://govern.iota.org/t/sgp-0006-igp-0001-tangle-community-treasury-grant-committee-framework-revision/1675%5D

While displayed in the Frontend and specified in the event is this URL:
https://govern.iota.org/t/sgp-0006-igp-0001-tangle-community-treasury-grant-committee-framework-revision/1675

The participation event that produces the link is this:

{
    "name": "[IGP - 0001] - Shimmer Community Grant Committee Revision Proposal",
    "milestoneIndexCommence": 7805764,
    "milestoneIndexStart": 7926724,
    "milestoneIndexEnd": 8047684,
    "payload": {
        "type": 0,
        "questions": [
            {
                "text": "Do you support the revision of the Shimmer Community Treasury Grant Committee Framework according to the changes proposed in this Governance proposal?",
                "answers": [
                    {
                        "value": 1,
                        "text": "Yes",
                        "additionalInfo": "I approve the proposed framework revision"
                    },
                    {
                        "value": 2,
                        "text": "No",
                        "additionalInfo": "I don't want to implement the proposed changes."
                    }
                ],
                "additionalInfo": ""
            }
        ]
    },
    "additionalInfo": "The IOTA voters agree to allocate 10 million IOTA Tokens through a donation from the IOTA Community Treasury to the Tangle Community Treasury Grant Committee and accept the operation specification outlined in the following proposal. Read the full proposal here: [https://govern.iota.org/t/sgp-0006-igp-0001-tangle-community-treasury-grant-committee-framework-revision/1675]"
}

And this:

{
    "name": "[SGP - 0006] - Shimmer Community Grant Committee Revision Proposal",
    "milestoneIndexCommence": 6342981,
    "milestoneIndexStart": 6463941,
    "milestoneIndexEnd": 6584901,
    "payload": {
        "type": 0,
        "questions": [
            {
                "text": "Do you support the revision of the Shimmer Community Treasury Grant Committee Framework according to the changes proposed in this Governance proposal?",
                "answers": [
                    {
                        "value": 1,
                        "text": "Yes",
                        "additionalInfo": "I approve the proposed framework revision"
                    },
                    {
                        "value": 2,
                        "text": "No",
                        "additionalInfo": "I don't want to implement the proposed changes."
                    }
                ],
                "additionalInfo": ""
            }
        ]
    },
    "additionalInfo": "Read the full proposal here: [https://govern.iota.org/t/sgp-0006-igp-0001-tangle-community-treasury-grant-committee-framework-revision/1675]"
}

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

open the governance tab and click on the displayed link under the event name.

Happens in IOTA and Shimmer version

### Operating System

Mac

### Diagnostics

```shell
Version 2.1.8
Language: en
Platform: macOS
Platform Version: 14.0
Platform Architecture: x64
CPU Count: 8
Total Memory: 8192.0 MB
Free Memory: 29.9 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

non

### Error Logs

```shell
non
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
Closing issue because its a problem on the markdown of the event, it will be fixed with a redirection
