### ISSUE TITLE
[Bug report]: Interpretation of URLs in an event

### ISSUE THREAD

**Issue by shufps** [iotaledger/firefly#7587]
### Version

latest

### Description

It happened that an event contained:

```
"additionalInfo": "The IOTA voters agree to allocate 10 million IOTA Tokens through a donation from the IOTA Community
Treasury to the Tangle Community Treasury Grant Committee and accept the operation specification outlined in the following
proposal. Read the full proposal here: [https://govern.iota.org/t/sgp-0006-igp-0001-tangle-community-treasury-grant-committee-
framework-revision/1675]"
}
```

Firefly interpretated the last `]` as part of the URL:

![image](https://github.com/iotaledger/firefly/assets/3079832/a9d8a36a-e32c-44cb-962f-07e0d1aaa12f)

Probably it's not really a bug ... 

Does it make sense to clip the URL when unusual characters appear? :man_shrugging: 

### Expected behaviour

Should show the link as `https://govern.iota.org/t/sgp-0006-igp-0001-tangle-community-treasury-grant-committee-framework-revision/1675`

### Actual behaviour

Shows the links as `https://govern.iota.org/t/sgp-0006-igp-0001-tangle-community-treasury-grant-committee-framework-revision/1675]`

### Can the issue reliably be reproduced?

Yes

### Operating System

Linux

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
the markdown of the event is wrong:
- link in the json for this event (its missing the last parenthesis with the link):
```
"additionalInfo": "Read the full proposal here: [https://govern.iota.org/t/sgp-0006-igp-0001-tangle-community-treasury-grant-committee-framework-revision/1675]"
```
- ex. Link for a Lead Committee Event:
```
"additionalInfo":"You can only choose one candidate. Read the applications for the Committee Lead Positions here: [https://govern.iota.org/c/shimmer-governance-proposals/shimmer-community-treasury-coommittee-lead-appli/59](https://govern.iota.org/c/shimmer-governance-proposals/shimmer-community-treasury-coommittee-lead-appli/59)"
```
Will close the issue as it doesnt seem to be a problem in firefly
