### ISSUE TITLE
[Bug report]: Unabale to claim Shimmer rewards

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#7588]
### Version

all Shimmer versions (2.1.5 till newest)

### Description

User aims to claim Shimmer rewards with STronghold and 24 words 
Fails with Error.

We uninstalled and deleted Appdata from the newest release down until 2.1.5, but it stays the same behavior and error

### Expected behaviour

Shimmer should be claimable

### Actual behaviour

Fails with error 

Sat, 14 Oct 2023 23:50:43 GMT
BaseError: Error: Unable to get bound account

Sat, 14 Oct 2023 23:50:43 GMT
BaseError: undefined

Sat, 14 Oct 2023 23:50:11 GMT
BaseError: Error: Unable to get bound account

Sat, 14 Oct 2023 23:50:11 GMT
BaseError: undefined

Sat, 14 Oct 2023 23:49:51 GMT
BaseError: Error: Unable to initialize Shimmer claiming account

Sat, 14 Oct 2023 23:49:51 GMT
BaseError: undefined

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Claim SMR

### Operating System

Windows

### Diagnostics

```shell
Version 2.1.5
Language: en
Platform: win32
Platform Version: 10.0.22621
Platform Architecture: x64
CPU Count: 8
Total Memory: 7879.7 MB
Free Memory: 2583.9 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

Sat, 14 Oct 2023 23:50:43 GMT
BaseError: Error: Unable to get bound account

Sat, 14 Oct 2023 23:50:43 GMT
BaseError: undefined

Sat, 14 Oct 2023 23:50:11 GMT
BaseError: Error: Unable to get bound account

Sat, 14 Oct 2023 23:50:11 GMT
BaseError: undefined

Sat, 14 Oct 2023 23:49:51 GMT
BaseError: Error: Unable to initialize Shimmer claiming account

Sat, 14 Oct 2023 23:49:51 GMT
BaseError: undefined

### Error Logs

```shell
Sat, 14 Oct 2023 23:50:43 GMT
BaseError: Error: Unable to get bound account

Sat, 14 Oct 2023 23:50:43 GMT
BaseError: undefined

Sat, 14 Oct 2023 23:50:11 GMT
BaseError: Error: Unable to get bound account

Sat, 14 Oct 2023 23:50:11 GMT
BaseError: undefined

Sat, 14 Oct 2023 23:49:51 GMT
BaseError: Error: Unable to initialize Shimmer claiming account

Sat, 14 Oct 2023 23:49:51 GMT
BaseError: undefined
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
This is a known bug that will be fixed in the next release
Closed by https://github.com/iotaledger/firefly/pull/7568
