### ISSUE TITLE
[Bug report]: Update 2.0.1 --> 2.0.2 Failed on Mac

### ISSUE THREAD

**Issue by jkl2e** [iotaledger/firefly#7591]
### Version

2.0.1

### Description

![Bildschirmfoto 2023-10-16 um 09 15 58](https://github.com/iotaledger/firefly/assets/71429780/65d94530-d054-497b-a274-c4d4faa8140b)

When Updating from 2.0.1 to 2.0.2 to update fails.

Hardware:
Mac Book Air M2 mit MacOS 14.0

### Expected behaviour

Update will install without error

### Actual behaviour

Update failed, Error Log emtpy

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Restart Firefly
2. Click Update
3. Download Upate
4. Installl failed

### Operating System

Mac

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Error Messages

see screenshot

### Error Logs

```shell
emtpy
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marc2332** [comment]
Hey :v: Auto update got broken in 2.0.1, you will need to install v2.0.2 manually by downloading the app again, let me know if it helps :pray:

**Comment by jkl2e** [comment]
downloaded the app und moved into the application folder.
V 2.0.2 running fine. Thanks.
