### ISSUE TITLE
NFC integration on Mobile

### ISSUE THREAD

**Issue by R15h4B** [iotaledger/firefly#760]
##willit possible contact less payment feature in iphone app.
Like we can use normal bank cards to make payments similar we can send tokens to one phone to another contactless feature 

Briefly describe the feature that you are requesting.

## Ease of use 

Explain why this feature is needed.

## IPhone 

Write a list of what you want this feature to do.

1.
2.
3.

## Open questions (optional)

Use this section to ask any questions that are related to the feature.

## Are you planning to do it yourself in a pull request?

No.

**Comment by cvarley100** [comment]
We do have this planned for the mobile version, yes.

**Comment by maxwellmattryan** [comment]
Hey @R15h4B, thank you for the request. I'm closing this issue as mentioned earlier, we've got this in the plans for mobile 👍
