### ISSUE TITLE
Stronghold recovery "incorrect password" bug

### ISSUE THREAD

**Issue by Diskad** [iotaledger/firefly#7629]
### Version

1.0.7

### Description

I can't recover stronghold from the mobile app(android) it says password is incorrect, while on my desktop it was working normally.

### Expected behaviour

Should have accepted my password.

### Actual behaviour

On mobile it says that my password is incorrect.

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
The mobile app is deprecated and no longer maintained by the IOTA Foundation. Please use the desktop version, you can find it on the official website https://firefly.iota.org/
