### ISSUE TITLE
Sending Fiat value instead of token amount

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#763]
## Description

User BernvonBrot suggested this feature. I think it can be a nice addition for the wallet.

Instead of only let the user decide if he wants to send Gi, Mi, Ki etc
it should be a possibility to send a fixed fiat value USD or EUR.
So the wallet would need to grab the latest ticker value and the user can decide to send 100USD worth of tokens to an selected address...

## Motivation

Ease of use

## Requirements
make it possible to input fiat values in the send routine...

## Open questions (optional)

Use this section to ask any questions that are related to the feature.

## Are you planning to do it yourself in a pull request?

Yes/No.

**Comment by Travetown** [comment]
analogous to Trinity


![image](https://user-images.githubusercontent.com/66588710/112754186-41d4b180-8fdb-11eb-8614-f24cabf279a1.jpeg)

**Comment by maxwellmattryan** [comment]
New feature has been merged into `develop` 👍 thank you for the request!
