### ISSUE TITLE
[Bug report]: Reduced IOTA Balance

### ISSUE THREAD

**Issue by jiangh77** [iotaledger/firefly#7639]
### Version

firefly-iota-desktop-2.0.2

### Description

After I updated my desktop wallet from 1.7.5 to 2.0.2.  My IOTA balance has been reduced.  I had over 500 MIOTA before the update, the wallet balance has been reduced to just 4 IOTA after the update.  There is no sent activity or staking activity.  There are 31 IOTA to be release from Locked supply

I understand there is a change from MIOTA to IOTA, but the balance should not change

### Expected behaviour

I expect the wallet to contain 500 IOTA

### Actual behaviour

The wallet balance is only 4 IOTA

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Update desktop wallet to version 2.0.2

### Operating System

Windows

### Diagnostics

```shell
There are no Diagnostic popup
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Previously staked

### Crash Status

None of the above

### Error Messages

There are no Error Messages

### Error Logs

```shell
There is Error Log
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jiangh77** [comment]
Screenshot of the wallet balance

![image](https://github.com/iotaledger/firefly/assets/40775325/5e714f03-9336-4e8d-94f0-cc18134c8911)

**Comment by begonaalvarezd** [comment]
Please run the balance finder from settings > advanced. If your funds sit in high index addresses your will need to run it multiple times, just run "search again" untill all your funds appear

**Comment by jiangh77** [comment]
Thank you so much, it worked, all my funds are there

I only have to run it once

You really helped me out

I appreciate that very much
