### ISSUE TITLE
[Task]: Fix undefined default theme

### ISSUE THREAD

**Issue by cpl121** [iotaledger/firefly#7658]
### Task description

When creating the first profile with ledger, the theme value was not set correctly
![Captura de pantalla de 2023-10-24 16-59-40](https://github.com/iotaledger/firefly/assets/100352899/34fe95a8-fdc9-484f-a366-c27626cccc04)

### Requirements

When creating the first profile with ledger, the theme value was not set correctly

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by evavirseda** [comment]
closed because the issue couldn't be reproduced again
