### ISSUE TITLE
Fehler beim einsammeln in FireFlay

### ISSUE THREAD

**Issue by FelixGare** [iotaledger/firefly#7708]
### Version

2.0.3

### Description

Sehr geehrte Damen und Herren,

Leider kann ich trotz anschließen meines Ledger meine Auszahlung der "iota Belohnung" nicht einsammeln. Anbei ein foto von der Fehlermeldung. 

Was kann ich machen damit ich diese einsammeln kann? 

![20231112_124020](https://github.com/iotaledger/firefly/assets/150685497/c887013f-95d3-4b44-94aa-d7a1d0bb4983)

### Expected behaviour

Einsammeln meiner iotas 

### Actual behaviour

Fehlermeldung siehe anhang

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
You dont really need to collect your rewards, once they are unlocked they compute as part of your available balance. What happens behind the scenes is what we call "output consolidation" which needs at leads 2, and it seems like you only have 1, so until the next payout you wont be able to press "collect", but that doesnt mean that you cant spend those funds, you can. We improved the user experience in https://github.com/iotaledger/firefly/pull/7609 the improvement will be included in the next release
