### ISSUE TITLE
Non-integers accepted as PIN by copy-paste

### ISSUE THREAD

**Issue by Foffex** [iotaledger/firefly#772]
## Issue description

PIN can be set to all kind of characters if pasted. Only keypress is blocked.

## Wallet version

v0.3.1

## System specification

Win10 Pro, 20H2.

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

https://user-images.githubusercontent.com/40924386/112902155-083c9d00-90e6-11eb-83f2-c0e55fc08296.mp4

## Expected behaviour

1. Check on leave if field contains non-accepted characters.
2. Set field to blank or PIN change not possible if non-accepted exist.

## Actual behaviour

Allows the PIN to be changed.

## Errors

None.

**Comment by obany** [comment]
This will be fixed in the next build, the settings page uses the PIN input control, see https://github.com/iotaledger/firefly/pull/609
