### ISSUE TITLE
[Task]: Support `set_stronghold_password` in NodeJS `SecretManager` bindings for IOTA 2.0 in sdk

### ISSUE THREAD

**Issue by marc2332** [iotaledger/firefly#7724]
Before, we were able to update the stronghold password because we already had the multi-accounts wallet from the begining (profile manager), but now, the single-account wallets are created a bit later, so we only have the secret manager from the begining.
But, turns out we cannot update the stronghold password through the nodejs secret manager, cuz it's not implemented.

**Comment by begonaalvarezd** [comment]
Superseeded by https://github.com/iotaledger/firefly/issues/7801
