### ISSUE TITLE
[Task]: Split `ProfileManager` into a SecretManager store and selectedWallet store

### ISSUE THREAD

**Issue by marc2332** [iotaledger/firefly#7729]
Use https://github.com/iotaledger/firefly/pull/7726 as base 

- Remove IProfileManger interface
- Split Profile manager into a `SecretManager` store and `selectedWallet` (previously `selectedAccount`)

**Comment by begonaalvarezd** [comment]
Refactors needed:
- getAccounts
- recoverAccounts
