### ISSUE TITLE
[Bug Report]: My Password Doesn't Work

### ISSUE THREAD

**Issue by WakeUpJudah** [iotaledger/firefly#7741]
### Task description

I just updated my Firefly wallet today 11/21/23. My password which has always worked no longer works.
Is there a service I can have access to fix this issue. 

I have used my wallet many times taking IOTA in and out. Never had a problem with my password until now. 

I have my seed phrase but am concerned that if my password isn't working that it won't as well. 

Note:
The PIN code I have set works no issues.

Please get back to me as soon as possible. Thank you

WakeUpJudah

**Comment by begonaalvarezd** [comment]
Hi, are you talking about the pin or the stronghold password? 
In any case, you can always restore your profile from your mnemonic, that will always work

**Comment by WakeUpJudah** [comment]
I'm speaking about the stronghold password.
I've had firefly since the 1st Assembly staking event.

Is the Stronghold password different? (I have a password written down but
it doesn't take.)

And thanks for your reply. Much appreciated!

**Comment by WakeUpJudah** [comment]
Ok, thanks for the clarification.
I will reply with how things are going. I appreciate your responding! Says
a lot about the project!

**Comment by WakeUpJudah** [comment]
Hi
I have an update.
I went to another computer an chose to migrate wallet using 24 seed phrase.
I was able to reset my password.
Here's the issue:

My coins are gone on my newly migrated account. Currently, I can open the
same account on two different devices. My 1st wallet still holds my IOTA.
The second, new wallet doesn't hold my full IOTA balance.
Now
Both wallets have the same receive address, and my vesting rewards for
staking when Assembly was discontinued. What could be the issue?

Is there a password recovery service that can be used?

Thanks for your help

**Comment by begonaalvarezd** [comment]
@WakeUpJudah 

About missing balances: If you are missing balances you can run the balance finder from settings > advanced, if you search for a while and your funds still dont appear you can check "search only in current wallet" to run an optimized search which is much faster and run in on every wallet

About staking rewards, just in case, here I share a bit of info about it: please read https://blog.iota.org/stardust-upgrade-iota-tokenomics/. The assembly project does not exist anymore, but your rewards got airdropped to you in form of IOTAs. They will appear in the new version 2.0.3 in the vesting tab. If you are missing rewards you can also run the rewards finder from the vesting tab, the '....' menu, search vesting rewards

**Comment by WakeUpJudah** [comment]
You are the best!

All is well now! I wish you well and I am sending a prayer for you now!

Thanks again
