### ISSUE TITLE
Profile deleting possible without entering the password

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#775]
## Issue description

A proflie can be deleted without the need to use the stronghold unlock password. Pin code to login to the profile is enough

## Wallet version

Firefly v0.3.1
Platform: win32
Platform Version: 10.0.19041
Platform Architecture: x64
CPU Count: 4
Total Memory: 6082.5 MB
Free Memory: 2023.1 MB

## Steps To reproduce the issue

login to a profile with PIN, go to settings and delete profile

## Expected behaviour

would expect to be asked for the password also. Even if those warnings popup, i would suggest the same security level (Pin and password) to make such a dramatic operation. If ever i would maybe give my kids access to the wallet to use the maessaging function or play around with NFT's or whatever comes in the future i could tell them the pin, but they could not do tx. But they could delete the whole wallet. I think thats not how it should be...

https://user-images.githubusercontent.com/77154511/112973583-18a35500-9184-11eb-87f2-c1baf1403716.mp4

## Actual behavior

deleting without password

**Comment by obany** [comment]
Fixed in next version.
