### ISSUE TITLE
[Bug report]: Balance missing after update Firefly

### ISSUE THREAD

**Issue by domste7** [iotaledger/firefly#7757]
### Version

2.0.3

### Description

after update Firefly my previous balance disappear and there is only balance added from vesting

### Expected behaviour

there must be vesting balance added to previous balance

### Actual behaviour

the upgrade most likely ran over the previous state

### Can the issue reliably be reproduced?

Yes

### Operating System

Mac

### Diagnostics

```shell
App Name: Firefly
Version 2.0.3
Language: en
Currency: eur
Node list: https://api.stardust-mainnet.iotaledger.net,https://iota-node.tanglebay.com
Platform: macOS
Platform Version: 12.7.1
Platform Architecture: x64
CPU Count: 4
Total Memory: 8192.0 MB
Free Memory: 18.6 MB
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Messages

No

### Error Logs

```shell
Sun, 03 Dec 2023 18:57:26 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Sun, 03 Dec 2023 16:52:34 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Sun, 23 Jan 2022 18:42:01 GMT
ClientError: `Response error with status code 404: {"error":{"code":"404","message":"Not Found, error: event not found: f6dbdad416e0470042d3fe429eb0e91683ba171279bce01be6d1d35a9909a981: code=404, message=Not Found"}}
`
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
You can run the balance finder from settings > advanced > balance finder, run it until all your balances appear. If you know in which wallet specially you are missing balances, tick the checkbox "search only un current wallet" to speed up the searching process

**Comment by Geppetox** [comment]
Hi, I have the same problem when trying to claim my biweekly tokens. Same error as above...
