### ISSUE TITLE
Entering password while importing a stronghold backup does not accept "return button" as confirmation

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#785]
## Issue description

In all areas where the user has to enter the password a simple push on the return button confirms the entered password.
This is not possible in the backup import section. 
Here a push on return does nothing and the user has to use the mouse to click on "continue"

## Wallet version

0.3.1

Windows 10

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Create profile => import existing wallet => choose file to upload => upload file => enter password to confirm => try to confirm with "return"

## Expected behaviour

a push on the return button should execute the entered password

## Actual behaviour

Only mouse click is possible

![image](https://user-images.githubusercontent.com/77154511/113144675-17475a80-9260-11eb-9652-d8fd52ac195c.png)

**Comment by obany** [comment]
Fixed in next version.
