### ISSUE TITLE
[Task]: Check that `mainAccountId` is still an owned account

### ISSUE THREAD

**Issue by evavirseda** [iotaledger/firefly#7939]
[Reference](https://github.com/iotaledger/firefly/pull/7923/files#diff-c7eeae96d1ba9e82889acefd84ba880255b813e26cae8a4f3e7fa5361c324851R50)

**Comment by cpl121** [comment]
Solved [here](https://github.com/iotaledger/firefly/pull/7923/files#diff-c7eeae96d1ba9e82889acefd84ba880255b813e26cae8a4f3e7fa5361c324851R45)
