### ISSUE TITLE
New Wallet Setup - Create Password error message

### ISSUE THREAD

**Issue by beeetrooot** [iotaledger/firefly#799]
## Issue description

When creating a new wallet, I am receiving an error code 'error.password.undefined' instead of an error message when setting the password.  This occurs when I use 'test' as the password.

Also, a small variation of the above issue.  When creating a new wallet, I am receiving an error code 'error.password.word' instead of an error message when setting the password.  This occurs when I use 'tes' as the password.    

## Wallet version

0.3.1

## System specification

What is your operating system?  

Windows 10

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.  Create a new wallet.
2.  Set password to 'test' or 'tes'.
3.  Select Continue.

## Expected behaviour

I expect a descriptive error message is displayed.

## Actual behaviour

An error code is displayed.

**Comment by cvarley100** [comment]
This will be fixed in the next version. Please reopen if you see it again.
