### ISSUE TITLE
trying to send with more than 0.000001 zeroes, there is no error, the send button just does nothing

### ISSUE THREAD

**Issue by admljhnsn** [iotaledger/firefly#801]
## Issue description

When attempting to send a value with more than 0.000001 zeroes, there should be an error. You only get an error about sending 0.000001 iota, not 0.0000001. I know it won't let you send less than 1 Mi right now anyway.

## Wallet version

0.3.1

- wallet version (version number, commit, or branch):

## System specification

MacOS Big Sur 11.2.3

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Go to send, enter address.
2. Enter 0.0000001
3. Try to send -> no error

## Expected behaviour

Some error like the one that says you can't send less than 1 Mi.
<img width="1392" alt="Screen Shot 2021-04-03 at 11 44 25 AM" src="https://user-images.githubusercontent.com/33967917/113483536-f5252680-9471-11eb-9a05-36741f6d6b0e.png">

## Actual behaviour

Send button has no reaction.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by cvarley100** [comment]
This will be fixed in the next version. Please reopen if you face it still.
