### ISSUE TITLE
Firefly update 2.0.6 & SMR 2.1.12 scammed[Bug report]: 

### ISSUE THREAD

**Issue by baz59** [iotaledger/firefly#8028]
### Version

2.0.6

### Description

I just updated Fire Fly 2.0.6 & SMR 2.1.12 - my tokens in both wallets have dissappeared - exported out of both wallets. Addresses on File explorer are shown where sent to - how to recover these  - have I been scammed - the new wallets had a lottery claim attachment in them as well - is ths the scam? how does it get added / embedded into the newest wallet update.

### Expected behaviour

I expected the new wallet updates to install as previous updates the same. Then I thought the tokens are stuck in the Tangle - but there is a transaction record out of the new wallets when updating.

### Actual behaviour

Wallet updated to latest versions. Firefly 2.0.6   Shimmer 2.1.12 Then new totals shown are 0 SMR & .02 iota - 
https://explorer.iota.org/mainnet/transaction/0x52c300241d2655614b109644ca5514a2fbb4139e819c5258a830af06a5ed8ba9Fie

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

I dont know if it can be reproduced as the transaction out of wallet is there only .

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
Duplicate https://github.com/iotaledger/firefly/discussions/8029#discussioncomment-8439131
