### ISSUE TITLE
[Bug report]: Error after iota wallet upgrade [ I Use Window 8.1 K ]

### ISSUE THREAD

**Issue by Linkedlee** [iotaledger/firefly#8042]
### Version

i cannot check

### Description

I use Windows 8.1 K and I accidentally upgraded my Iota wallet, and now I get this error.
[the procedure entry point discard virtual memory could not be located in the DLL C:Program/Files/Firefly/Firefly.exe]

*I can't check the current version of Iota

### Expected behaviour

I thought it would be upgraded the same as before

### Actual behaviour

An error occurs when the program is running, and the program does not start

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Now, I use Windows 8.1 K
2. The upgrade has been disabled due to operating system issues, but I accidentally upgraded it
3. This will result in an error window and the program will not run

[the procedure entry point discard virtual memory could not be located in the DLL C:Program/Files/Firefly/Firefly.exe]

### Operating System

Windows

### Diagnostics

```shell
Unable to run Firefly :(
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

Application closed

### Error Messages

![캡처](https://github.com/iotaledger/firefly/assets/160032904/0b13a454-07cb-4c3d-9ddd-cdceba160845)

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rajivshah3** [comment]
Hi, this is because Windows 7, 8, and 8.1 are no longer supported. Please upgrade to Windows 10 if possible. Alternatively, you can try installing Ubuntu (or another major Linux distro) on your computer and using Firefly on there
