### ISSUE TITLE
cannot restore my old  back up

### ISSUE THREAD

**Issue by javaherian1** [iotaledger/firefly#8083]
### Task description

i have  .kdbx file , but i cannot drag/drop into new iota wallet   anyone can help ?

**Comment by begonaalvarezd** [comment]
🔈 **We just released the new legacy migration tool** 🔈

Read about it here: https://blog.iota.org/iota-legacy-migration-tool/ 

If you face any issues please contact us over discord https://discord.iota.org/ or open an issue directly in the legacy tool repo https://github.com/iotaledger/legacy-migration-tool

Happy migration 🌷
