### ISSUE TITLE
IOTA 

### ISSUE THREAD

**Issue by zzmm18** [iotaledger/firefly#8088]
### Task description

Hello , i have one problem today i logt in to my firefly account and there i had 5k iota and after few mins they was not on firefly 
can you please tell me did the migrated to another account or whats wrong here ?

**Comment by begonaalvarezd** [comment]
What do you mean? They suddenly disappeared or was there an outgoing transaction? Did you update Firefly when you saw your balance disappear?

**Comment by zzmm18** [comment]
yes i updated Firefly and i checked there is no transfer and i have no idea , can you help me please to finde out whats wrong

**Comment by begonaalvarezd** [comment]
It can be that you need to run the balance finder, just go to the settings > advanced > balance finder and search until your funds appear. You can make an optimized search by checking the checkbox "search only in current wallet" to speed up the process

**Comment by begonaalvarezd** [comment]
It can take couple of searches until your funds appear, if you are 100% your funds are there, just keep searching until they appear. 

In any case, there is always the option to restore and create a new profile from your ledger, 24 words mnemonic or latest stronghold backup in case you think there is something wrong with the firefly profile

**Comment by zzmm18** [comment]
yes i am trying to search but nothing , it was this lottery inside firefly and is that possible i migrated to iota-fly .com ?

**Comment by begonaalvarezd** [comment]
Ahh wait, that is a scam 

Scam Alert!

Currently, scammers are sending NFTs to IOTA addresses that aim to trick users into visiting an "IOTA Lottery" website where it is promised they could claim their "Win".

There is no IOTA Lottery, and visiting this website can lead to losing all Funds in your IOTA Wallet.

It is not possible to block receiving these NFT so either ignore them or "burn" them by following these steps:
1) In your wallet go to: Collectibles
2) Choose the scammer NFT
3) Click on the three dots on the top right
4) Burn NFT

NEVER enter your seed, 24 words Phrase or backup file in ANY website or online application.

Stay safe.

If you fell victim to this scam please report it to your local authorities.

![image](https://github.com/iotaledger/firefly/assets/3624944/283ea051-5e7d-49c3-88a6-d8969c009ed7)

**Comment by begonaalvarezd** [comment]
If you entered your private keys to that website, im afraid you are a victim of that scam

**Comment by zzmm18** [comment]
wow
how is possible firefly alow that to be inside

**Comment by zzmm18** [comment]
is there any possible to do something pleas or why i can se nothing where they transfered

**Comment by begonaalvarezd** [comment]
We cant prevent someone from gifting you an NFT. The ecosystem is full of "do not enter your seed in random places, do not share your seed with anybody"... Firefly is a self custody wallet, you need to take good care of your seed because you are the only one that holds it.

If firefly is not displaying the transaction you can visit your address/addresses in the explorer to see if there was indeed a transaction or not https://explorer.iota.org/ you can find all your address in the option next to your balance "..." menu > address history

If you didnt share your seed with the scammers your funds will still be there in your addresses, you just need to search for them using the balance finder. But if you did enter your seed there, im afraid there isnt much you can do at this point. As mentioned in the message above, if you are a victim, we recommend you report it to your local authorities

**Comment by zzmm18** [comment]
I checked my address and i had 2 wallets and yes they was transfered in another address but its strange can i di something or can i block transfer ?

Sent from my iPhone

On 23 Feb 2024, at 4:36 PM, Begoña Álvarez de la Cruz ***@***.***> wrote:

﻿

Did you check all your addresses in the explorer?

**Comment by zzmm18** [comment]
Please do something on this its not okey to allow scammers to go inside you should block this part or trying to have more security i checked now in same account which was transferred for few hours was 30k iota , i know this was my fold but i never expect someone to come in my home and steel people in my house if that happen this is my fold and i paid 11k for this iota, please protect others because for me looks like too late

**Comment by begonaalvarezd** [comment]
Im a very sorry you are a victim 🙏🏼 stay safe
