### ISSUE TITLE
[Task]: Prepare release process for canary iota 2.0 testnet version

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/firefly#8111]
### Task description

We need to prepare the CI so that we can make canary 3.0.0-x releases for the testnet
Lets discuss what version number we will give to this canary, the idea is that 
- Testnet: Firefly Canary 3.0.0
- Shimmer/Mainnet: Firefly 3.0.0

**Comment by cpl121** [comment]
Blocked until there is a stable release of the iota/sdk
