### ISSUE TITLE
Installed the updated IOTA Firefly, which is linked to my Ledger Plus device, The Iota update app will not generate my account from the old app, I can't log into my account.  

### ISSUE THREAD

**Issue by vmillervm** [iotaledger/firefly#8116]
### Task description

Installed the new updated IOTA Firefly, which is linked to my Ledger Plus device, The Iota update app will not generate my account from the old app, I can't log into my account.  App Name: Firefly
Please NOTE diagnostics Version 2.0.8
**Language: en
Platform: win32
Platform Version: 10.0.22621
Platform Architecture: x64
CPU Count: 16
Total Memory: 15711.3 MB
Free Memory: 10978.5 MB**

**Comment by begonaalvarezd** [comment]
Did you update your iota ledger app? It has to be on the latest version 0.8.6 to work, if you cant see that version in ledger live you must update your ledger firmware first

**Comment by MarWar69** [comment]
I am also having the same issue, Ledger nano S , already have the latest firmware 2.1.
Both Firefly IOTA and Firelfy shimmer are showing the same error codes:
`Fri, 08 Mar 2024 16:42:44 GMT
wallet: `local time 1709916164 doesn't match the time of the latest milestone timestamp: 1709915210`

Fri, 08 Mar 2024 16:42:28 GMT
wallet: `local time 1709916148 doesn't match the time of the latest milestone timestamp: 1709915210`

Fri, 08 Mar 2024 16:42:10 GMT
wallet: `local time 1709916130 doesn't match the time of the latest milestone timestamp: 1709915148`

Fri, 08 Mar 2024 16:42:01 GMT
wallet: `local time 1709916120 doesn't match the time of the latest milestone timestamp: 1709915148`

Fri, 08 Mar 2024 16:40:25 GMT
Generic: `local time 1709916025 doesn't match the time of the latest milestone timestamp: 1709915054`

Fri, 08 Mar 2024 16:40:03 GMT
Generic: `local time 1709916003 doesn't match the time of the latest milestone timestamp: 1709915054`

Fri, 08 Mar 2024 16:39:34 GMT
Generic: `local time 1709915974 doesn't match the time of the latest milestone timestamp: 1709915054`
`
This was not an issue in the previous updates. tried going back a version (were IOTA NFTs were still visible), still could not access my account.


right after the log in password is correctly written, the wallet starts loading and right before the end of the loading, this error pops up  

> **local time (numbers) doesn't match the time of the latest milestone timestamp: (numbers)**

Please help!

**Comment by begonaalvarezd** [comment]
The error is suggesting that your machine's clock is not in sync, just sync your clock or set it to automatic and it should work

**Comment by MarWar69** [comment]
Hello Begona,
Thank you for your reply. 
It seems that this Error happens when the Ledger is connected before logging in Firefly account.

I can now access my account. 
Thank you once again!
