### ISSUE TITLE
Error while creating a new wallet

### ISSUE THREAD

**Issue by Solipsos** [iotaledger/firefly#8117]
### Version

2.0.8

### Description

Hello,

when I try to setup a new account, always get the same mistake at the end. The new account exist, but when I try to log in, I get the same mistake.

Regards

### Expected behaviour

Logging in into the setup account

### Actual behaviour

Thu, 29 Feb 2024 19:12:23 GMT
wallet: `local time 1709233943 doesn't match the time of the latest milestone timestamp: 1709237541`

Thu, 29 Feb 2024 19:12:01 GMT
wallet: `local time 1709233919 doesn't match the time of the latest milestone timestamp: 1709237494`

Thu, 29 Feb 2024 19:10:22 GMT
wallet: `local time 1709233822 doesn't match the time of the latest milestone timestamp: 1709237410`

Thu, 29 Feb 2024 19:09:57 GMT
wallet: `local time 1709233797 doesn't match the time of the latest milestone timestamp: 1709237347`

Thu, 29 Feb 2024 19:09:50 GMT
wallet: `local time 1709233788 doesn't match the time of the latest milestone timestamp: 1709237347`

Thu, 29 Feb 2024 19:07:24 GMT
wallet: `local time 1709233644 doesn't match the time of the latest milestone timestamp: 1709237238`

Thu, 29 Feb 2024 19:07:06 GMT
wallet: `local time 1709233626 doesn't match the time of the latest milestone timestamp: 1709237190`

Thu, 29 Feb 2024 19:07:01 GMT
wallet: `local time 1709233620 doesn't match the time of the latest milestone timestamp: 1709237190`

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

None

### Crash Status

None of the above

### Error Messages

Thu, 29 Feb 2024 19:12:23 GMT
wallet: `local time 1709233943 doesn't match the time of the latest milestone timestamp: 1709237541`

Thu, 29 Feb 2024 19:12:01 GMT
wallet: `local time 1709233919 doesn't match the time of the latest milestone timestamp: 1709237494`

Thu, 29 Feb 2024 19:10:22 GMT
wallet: `local time 1709233822 doesn't match the time of the latest milestone timestamp: 1709237410`

Thu, 29 Feb 2024 19:09:57 GMT
wallet: `local time 1709233797 doesn't match the time of the latest milestone timestamp: 1709237347`

Thu, 29 Feb 2024 19:09:50 GMT
wallet: `local time 1709233788 doesn't match the time of the latest milestone timestamp: 1709237347`

Thu, 29 Feb 2024 19:07:24 GMT
wallet: `local time 1709233644 doesn't match the time of the latest milestone timestamp: 1709237238`

Thu, 29 Feb 2024 19:07:06 GMT
wallet: `local time 1709233626 doesn't match the time of the latest milestone timestamp: 1709237190`

Thu, 29 Feb 2024 19:07:01 GMT
wallet: `local time 1709233620 doesn't match the time of the latest milestone timestamp: 1709237190`

### Error Logs

```shell
Thu, 29 Feb 2024 19:12:23 GMT
wallet: `local time 1709233943 doesn't match the time of the latest milestone timestamp: 1709237541`

Thu, 29 Feb 2024 19:12:01 GMT
wallet: `local time 1709233919 doesn't match the time of the latest milestone timestamp: 1709237494`

Thu, 29 Feb 2024 19:10:22 GMT
wallet: `local time 1709233822 doesn't match the time of the latest milestone timestamp: 1709237410`

Thu, 29 Feb 2024 19:09:57 GMT
wallet: `local time 1709233797 doesn't match the time of the latest milestone timestamp: 1709237347`

Thu, 29 Feb 2024 19:09:50 GMT
wallet: `local time 1709233788 doesn't match the time of the latest milestone timestamp: 1709237347`

Thu, 29 Feb 2024 19:07:24 GMT
wallet: `local time 1709233644 doesn't match the time of the latest milestone timestamp: 1709237238`

Thu, 29 Feb 2024 19:07:06 GMT
wallet: `local time 1709233626 doesn't match the time of the latest milestone timestamp: 1709237190`

Thu, 29 Feb 2024 19:07:01 GMT
wallet: `local time 1709233620 doesn't match the time of the latest milestone timestamp: 1709237190`
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
You have to sync the clock of your machine, its not accurate. Sync it or set it to automatic to fix the error `local time 1709233943 doesn't match the time of the latest milestone timestamp: 1709237541`
