### ISSUE TITLE
[Task]: Update the new output event logic when the delegation output is received

### ISSUE THREAD

**Issue by cpl121** [iotaledger/firefly#8187]
### Task description

Update the new output event logic when the delegation output is received
[Reference](https://github.com/iotaledger/firefly/pull/8154/files#diff-5790b75f3a351fa8556f6c427a234a781582ce1342b29dd6914d80c2da3fba84R54)

**Comment by marc2332** [comment]
I think this could be fixed by tweaking the sync options passed to the background syncing
