### ISSUE TITLE
Account address history wont update until restart of wallet

### ISSUE THREAD

**Issue by t00k** [iotaledger/firefly#828]
## Issue description

Looking at the account address history after sending a transfer shows the old status of the addresses.

## Wallet version

FF 0.4.0
Windows 10

## Steps To reproduce the issue

1. Go into account -> show address history
2. Send any amount to another address
3. Go into account -> show address history

## Expected behaviour

The address value should update to represent the value after sending.

## Actual behaviour

The view is the same as before sending. Shows the incorrect value on address X. Have to restart Firefly and go back into "show address history" to see an update view with the new, unused address highest up, and with the correct values representing.

**Comment by obany** [comment]
This will be fixed in the next release
