### ISSUE TITLE
MIS IOTA HAN DESAPARECIDO

### ISSUE THREAD

**Issue by 19801980David** [iotaledger/firefly#8288]
### Version

2.09 ACTUALIZADA

### Description

HOLA, hoy me he metido en mi cartera de Firdfly y me aparecían correctamente mis 2028 IOTA (equivalente a 750 dólares), después he realizado de prueba el Voto sobre la elección de IOTA o MIOTA y minutos después mi saldo ha pasado a 0,23975. Pueden informarme de lo sucedido? 
Tiene que ver en algo el uso de Luciernaga?
No puedo ver cuales han sido los últimos movimientos, pueden ayudarme a recuperar mis 2028 IOTA. 
Muchas gracias

### Expected behaviour

Que siguiesen los 2028 IOTA.

### Actual behaviour

Han desaparecido de repente mis 2028 IOTA

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Developer Profile

Yes

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
Hola, a qué voto te refieres con "después he realizado de prueba el Voto sobre la elección de IOTA o MIOTA"? No conozco de ninguna votacion activa al respecto

**Comment by ramin8361** [comment]
Hello
The same thing happened to me. After voting, my IOTA decreased

**Comment by begonaalvarezd** [comment]
Voting locks your funds in voting power, go to your balance breakdown, next to your balance there is a "..." menu and access the balance breakdown from there, you can see how your balance is spread. You can just remove or decrease your voting to unlock those funds again

**Comment by ramin8361** [comment]
Is it possible to stack and lock our iotas in firefly but still get stolen?

**Comment by begonaalvarezd** [comment]
With "lock" I meant from a firefly perspective the funds are locked, but they are really not locked, the outputs are free to be spent from a protocol perspective, its just very bad UX if we allow users to move their funds while they are voting because they will stop voting. 
If your keys were compromised you funds could be sent somewhere else unless they are time locked (they have a special timelock)
