### ISSUE TITLE
Amount disappear when pasting address during send

### ISSUE THREAD

**Issue by t00k** [iotaledger/firefly#829]
## Issue description

When sending a transaction and filling in the amount first, that amount then disappear when pasting in the receiving address.

## Wallet version

FF 0.4.0
Windows 10

## Steps To reproduce the issue

1. Send funds
2. Fill in amount
3. Paste receieve address (or any text)

## Expected behaviour

The transaction should continue as usual.

## Actual behaviour

When pasting the receiving address (or anything) the amount disappear.

**Comment by begonaalvarezd** [comment]
fixed by #836
