### ISSUE TITLE
[Task]: Fix BIC negative when transition many accounts

### ISSUE THREAD

**Issue by evavirseda** [iotaledger/firefly#8313]

**Comment by begonaalvarezd** [comment]
I think this can be because we are not estimating the mana cost with enough buffer and if the mana cost changes, then the bic can go negative. We can try adding 1 extra slot (instead of the 3 we had originally) and see if it still happens, I feel like it hsouldntshouldnt 🤞🏼

**Comment by begonaalvarezd** [comment]
Fixed by the SDK
