### ISSUE TITLE
Crash after deleting and recreating profile with the same name

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/firefly#833]
## Issue description

After setting up a profile for the first time and immediately deleting it, firefly throws you back to the setup process. If you then attempt to create a new profile with the same name (P1 in my case), you'll get an error message first which says "Something went wrong". If you however press enter or click "Create new wallet" for a second time, the application window turns white.

## Wallet version

v0.4.0

## System specification

macOS 11.3 Beta

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Create a profile
2. Delete it
3. Go trough setup process again and chose the same profile name
4. Click "Create new wallet" & ignore error message
5. Click "Create new wallet" again

## Expected behaviour

Should create the profile/continue setup process

## Actual behaviour

App crashes

## Errors

<img width="1392" alt="Bildschirmfoto 2021-04-10 um 14 46 20" src="https://user-images.githubusercontent.com/17240275/114270520-23c07580-9a0d-11eb-859d-c877f812f3bc.png">
<img width="554" alt="Bildschirmfoto 2021-04-10 um 14 44 35" src="https://user-images.githubusercontent.com/17240275/114270522-2753fc80-9a0d-11eb-8b56-087fd27029ff.png">
<img width="1392" alt="Bildschirmfoto 2021-04-10 um 14 46 45" src="https://user-images.githubusercontent.com/17240275/114270526-29b65680-9a0d-11eb-87f9-8c089ad20984.png">

**Comment by obany** [comment]
This should be fixed in the next release
