### ISSUE TITLE
[Task]: Fix displayed mana in tx details

### ISSUE THREAD

**Issue by evavirseda** [iotaledger/firefly#8334]
mana is not displayed correctly in tx details after claiming rewards 

![Image](https://github.com/iotaledger/firefly/assets/72078237/09124912-2bc8-4558-bde8-eb5f29a904cd)

**Comment by begonaalvarezd** [comment]
To display correctly the mana we should do it this way:
- Calculate the wallet "available" mana in the input section of the tx
  - match all outputs that you own by address unlock condition
  - match all outputs that you own by the address return if the output has an expired expiration time unlock condition at the time of the tx
  - available mana = potential + stored + genered rewards of all your owned outputs by the tx of the tx
- Calculate the stored mana of all your owned outputs in the output section of the tx
  - match all outputs that you own only by address unlock condition
- Mana = Outputs Mana - Inputs Mana
