### ISSUE TITLE
 "Crash" after consecutively deleting two profiles

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/firefly#834]
## Issue description

After consecutive deletion of two (newly) created profiles, the application "crashes". While it still lets you open the wallets main view, buttons thereafter don't respond anymore.

## Wallet version

v0.4.0

## System specification

macOS 11.3 Beta

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

1. Consecutively create two profiles (P1 & P2 in my case)
2. Delete the newly created profile (P2)
3. Attempt to delete the other profile (P1)

## Expected behaviour

Setup process should begin after deleting the last remaining profile

## Actual behaviour

Application "crashes"

## Errors

<img width="1935" alt="Bildschirmfoto 2021-04-10 um 15 19 01" src="https://user-images.githubusercontent.com/17240275/114271338-2624ce80-9a11-11eb-9bb2-b86e18d72059.png">

**Comment by obany** [comment]
This should be fixed in the next release
