### ISSUE TITLE
"Crash" after starting with a single whitespace in account creation process

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/firefly#835]
## Issue description

When starting with a single whitespace in the account creation process, the application "crashes" and buttons don't respond anymore.

## Wallet version

v0.4.0

## System specification

macOS 11.3 Beta

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

1. Click "Create" to create a new account
2. Type in a single whitespace

## Errors

<img width="1775" alt="Bildschirmfoto 2021-04-10 um 15 41 23" src="https://user-images.githubusercontent.com/17240275/114271966-4d30cf80-9a14-11eb-90e3-0c2f57765e14.png">

**Comment by obany** [comment]
Fix included in the next release.
