### ISSUE TITLE
[Bug report]: Device not connected

### ISSUE THREAD

**Issue by AmericanNDN** [iotaledger/firefly#8351]
### Version

2.0.9

### Description

When I try to move MIOTA from one Firefly account to another, I get a message that says "connect to ledger" .  So when I do that I get a green colored message that says "Ledger connected".  Then it tells me to go to open IOTA account on Ledger. I do but when I
Click enter I get a little red message that says" cannot connect to device". Can you lease tell be what is causing this?

Ledger support tells me everything is working fine on the Ledger end.
Candie

### Expected behaviour

I expected to send my iota to the other firefly wallet I have.

### Actual behaviour

Message that says " cannot connect to device"

![Error Connection to Ledger Device](https://github.com/iotaledger/firefly/assets/157909154/377ba1c4-517a-404e-a767-c4270a623e20)

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Select iota to send
input address
Firefly tells me to connect to Ledger
Firefly tells me to open IOTA on Ledger
Green Firefly message says connected
Click enter to send transaction 
Firefly sends red message "cannot connect to device"

### Operating System

Windows

### Diagnostics

```shell
App Name: Firefly
Version 2.0.9
Language: en
Currency: usd
Node list: https://api.stardust-mainnet.iotaledger.net,https://iota-node.tanglebay.com
Platform: win32
Platform Version: 10.0.22631
Platform Architecture: x64
CPU Count: 16
Total Memory: 16059.7 MB
Free Memory: 7552.8 MB
```

### Developer Profile

Yes

### Profile Type

Hardware (Ledger)

### Staking

None

### Crash Status

None of the above

### Error Messages

cannot connect to device

### Error Logs

```shell
Thu, 14 Mar 2024 16:50:40 GMT
wallet: nothing to consolidate: available outputs: 0, consolidation threshold: 2

Fri, 06 May 2022 14:52:55 GMT
LedgerDeviceNotFound: ledger device not found

Thu, 13 Jan 2022 15:53:14 GMT
LedgerDeviceNotFound: ledger device not found

Thu, 13 Jan 2022 15:34:31 GMT
RecordNotFound: account not found

Thu, 13 Jan 2022 14:27:05 GMT
RecordNotFound: account not found

Thu, 13 Jan 2022 13:34:08 GMT
RecordNotFound: account not found

Wed, 22 Dec 2021 19:03:31 GMT
RecordNotFound: account not found

Wed, 22 Dec 2021 19:02:24 GMT
RecordNotFound: account not found

Wed, 22 Dec 2021 18:59:20 GMT
RecordNotFound: account not found

Wed, 22 Dec 2021 18:56:56 GMT
RecordNotFound: account not found

Wed, 10 Nov 2021 15:14:34 GMT
ClientError: {}
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rajivshah3** [comment]
Hi, can you double check if the Ledger Live app (or another app that uses the Ledger) is open? Sometimes it can interfere with Firefly. If that's not the case, using a USB hub or a cable that isn't the originally supplied by Ledger can sometimes cause problems.

**Comment by AmericanNDN** [comment]
yes, I did that.  Still says device not connected.
Candie

**Comment by begonaalvarezd** [comment]
Are you on the latest ledger app version? The network was upgraded and you need the iota ledger app version 0.8.6 otherwise it will not work. If you cant see that version in ledger live that means that you first need to update the firmware of your ledger. 
Additionally, just to insist on what was mentioned above, ledger does not behave well with non official cables, so please make sure you are using an original ledger cable
