### ISSUE TITLE
[Bug report]: wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

### ISSUE THREAD

**Issue by Geppetox** [iotaledger/firefly#8388]
### Version

2.0.9

### Description

App Name: Firefly
Version 2.0.9
Language: en
Currency: usd
Node list: https://api.stardust-mainnet.iotaledger.net,https://iota-node.tanglebay.com,https://mainnet-node.tanglebay.com
Platform: win32
Platform Version: 10.0.19045
Platform Architecture: x64
CPU Count: 8
Total Memory: 16206.4 MB
Free Memory: 11411.9 MB

I cannot claim the biweekly tokens. Error: 

Wed, 17 Apr 2024 17:22:08 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 17 Apr 2024 17:20:00 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 17 Apr 2024 17:19:46 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 17 Apr 2024 17:17:05 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 17 Apr 2024 17:14:40 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 17 Apr 2024 17:14:25 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 17 Apr 2024 17:13:51 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 17 Apr 2024 17:13:39 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 17 Apr 2024 17:13:13 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

Wed, 17 Apr 2024 17:13:05 GMT
wallet: nothing to consolidate: available outputs: 1, consolidation threshold: 2

### Expected behaviour

Claim tokens

### Actual behaviour

Get the error

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

I click on collect in the vesting tab and the error is shown in the bottom right corner. 

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
Hi, let me first explain a bit what collect actually does: As soon as the outputs are unlocked the balance is free to use so it gets added to the balance before collecting, "collect" basically consolidates the outputs (combines multiple into one) and puts them into your deposit address, cleaning up spread balances between multiple addresses and helping the tangle by reducing the number of tiny unspent outputs out there. What this means, is that the user doesnt really need to collect anything, your funds are usable and are added to your balance as soon as they unlock. Not the best UX I agree, but we need a shiny button to help cleaning up rotating addresses and the tangle snapshot size increase

Then, about your error, consolidation only works if you have at least more than 1 output, which seems like you dont. You can use your funds anyway, you can send them wherever your want.
