### ISSUE TITLE
[Task]: Display `Generated Mana` message when insufficient mana on create delegation

### ISSUE THREAD

**Issue by evavirseda** [iotaledger/firefly#8431]
when we try to delegate without enough mana, they see a disabled `Confirm` button but get no info on when we'll have enough mana... We need to make it clearer by showing a message about mana generation progress

![Image](https://github.com/iotaledger/firefly/assets/72078237/8eada00a-71f9-4d73-a6e7-89152bfa0cbe)

**Comment by Thoralf-M** [comment]
Looks the same if the account address is not from a validator, @cpl121 does your PR also show some address error in this case?
