### ISSUE TITLE
correcting a typo while changing password leads to error

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#846]
## Issue description

wanted to change the password in settings
1.) Entered the original password
2.) entered the new password
3.) entered the new password but with a typo
passwords do not match occurs
4.) corrected the typo and pressed enter
- message something went wrong occurs
<img width="955" alt="misstype correct" src="https://user-images.githubusercontent.com/77154511/114294854-e541be00-9ad3-11eb-9609-007a2a5c2667.png">

## Wallet version

Firefly v0.4.0
Language: en
Currency: USD
Node settings: Automatic node selection
Platform: win32
Platform Version: 10.0.19041
Platform Architecture: x64

## Is it a repeatable issue?

Not yet, tried it on several profiles afterwards, but did not happen again yet, reporting it anyway...

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.
errors from firefly error log:

Sun, 11 Apr 2021 06:36:41 GMT
Panic: Internal error: Error at C:\Users\runneradmin\.cargo\git\checkouts\stronghold.rs-fe28308a6634692d\65ec786\client\src\interface.rs:470

   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: BaseThreadInitThunk
  21: RtlUserThreadStart

Sun, 11 Apr 2021 06:32:18 GMT
Panic: Internal error: Error at C:\Users\runneradmin\.cargo\git\checkouts\stronghold.rs-fe28308a6634692d\65ec786\client\src\interface.rs:470

   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: BaseThreadInitThunk
  21: RtlUserThreadStart

Sun, 11 Apr 2021 06:26:46 GMT
ClientError: {}

Sun, 11 Apr 2021 06:26:31 GMT
ClientError: {}

Sun, 11 Apr 2021 06:12:32 GMT
ClientError: {}

Sun, 11 Apr 2021 06:10:02 GMT
ClientError: {}

errors from console:
Uncaught (in promise) Error: EBUSY: resource busy or locked, unlink '\\?\C:\Users\Amedw\AppData\Roaming\Firefly Beta\__storage__\import words phylo1\db\LOCK'
    at unlinkSync (VM39 fs.js:1035)
    at rimrafSync (VM54 rimraf.js:182)
    at VM54 rimraf.js:211
    at Array.forEach (<anonymous>)
    at _rmdirSync (VM54 rimraf.js:210)
    at rimrafSync (VM54 rimraf.js:180)
    at VM54 rimraf.js:211
    at Array.forEach (<anonymous>)
    at _rmdirSync (VM54 rimraf.js:210)
    at rimrafSync (VM54 rimraf.js:180)
index.js:2 Initialise called when another actor already initialised
pr @ index.js:2
VM69 C:\Users\Amedw\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:1 Objectmessage: "{}"time: 1618122391490type: "ClientError"__proto__: Object
o @ VM69 C:\Users\Amedw\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:1
index.js:2 Initialise called when another actor already initialised
pr @ index.js:2
VM69 C:\Users\Amedw\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:1 Object
o @ VM69 C:\Users\Amedw\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:1
index.js:2 Initialise called when another actor already initialised
pr @ index.js:2
VM69 C:\Users\Amedw\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:1 Object
o @ VM69 C:\Users\Amedw\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:1

This one showed up after a second click on enter to try to confirm the change again:

VM69 C:\Users\Amedw\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:1 {type: "Panic", message: "Internal error: Error at C:\Users\runneradmin\.car…20: BaseThreadInitThunk↵  21: RtlUserThreadStart↵", time: 1618123001406}
o @ VM69 C:\Users\Amedw\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:1
F @ VM69 C:\Users\Amedw\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:1
(anonymous) @ VM69 C:\Users\Amedw\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:1
(anonymous) @ VM69 C:\Users\Amedw\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:1
destroy @ VM69 C:\Users\Amedw\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:1
(anonymous) @ VM69 C:\Users\Amedw\AppData\Local\Programs\desktop\resources\app.asar\public\build\preload.js:1

**Comment by obany** [comment]
At any point before this had you deleted a profile ?

**Comment by Phyloiota** [comment]
> At any point before this had you deleted a profile ?

I cannot say 100%, but i think not - i id delete a profile to test if it works flawless, but am pretty sure i did this a few hours after that issue...
Can you tell me why you ask this? Is there a specific error that leads you to this guessing? Maybe this helps me remembering...

**Comment by obany** [comment]
There was a bug in the delete profile which leads to the "Initialize called when actor was already initialized" console error, after that the wallet becomes unstable

**Comment by Phyloiota** [comment]
okay... maybe ... ill try to reproduce this ... so first deleting a profile and then triying to get that error again...

**Comment by Phyloiota** [comment]
sorry - no luck with that - dont find a way to repeat that...
