### ISSUE TITLE
buttons "change pin" and "change password" do only accept mouseclick

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/firefly#847]
## Issue description

The buttons to "enter" a change in Pin or Password dont get triggered with the "enter" key, only clicking on them with the mouse activates them

## Wallet version

0.4.0
Win 10

## Is it a repeatable issue?

yes
## Steps To reproduce the issue

try change pin or password, after filling out the new values press enter - nothing happens

## Expected behaviour

enter button should confirm the task

<img width="450" alt="change pin" src="https://user-images.githubusercontent.com/77154511/114295147-ebd13500-9ad5-11eb-9cd7-e3d20d4d45a9.png">

**Comment by obany** [comment]
Fixed in next relelease
