### ISSUE TITLE
[Task]: Fix delegation claimed activity

### ISSUE THREAD

**Issue by evavirseda** [iotaledger/firefly#8470]
![Image](https://github.com/iotaledger/firefly/assets/72078237/bd25dc8e-b644-49a1-bf92-9db713ee9bbf)

- [ ] the pill is showing `mint` instead of `claimed`
- [ ] fix `View on explorer` in the tx details links to the tx that created the delegation output, not the x in which it was claimed.

**Comment by marc2332** [comment]
>  fix View on explorer in the tx details links to the tx that created the delegation output, not the x in which it was claimed.

Instead of changing the transactionId in the "View on explorer" we should be using the "claimed in" field
