### ISSUE TITLE
[Linux] Stuck at Confirm PIN code

### ISSUE THREAD

**Issue by monospacedmagic** [iotaledger/firefly#850]
## Issue description

During initial setup, Firefly does nothing when I click on the Confirm PIN code button.

## Wallet version

- desktop-0.3.1

## System specification

What is your operating system?

Manjaro 21.0.1 (Kernel: Linux 5.10.26-1-MANJARO)

## Is it a repeatable issue?

Yes.

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Go through initial setup on Manjaro
2. Try to confirm your PIN code as part of the initial setup

## Expected behaviour

The software continues with the initial setup after pressing Confirm PIN code.

## Actual behaviour

Nothing happens, the button press is visible as the background color of the button element changes, however the software doesn't seem to respond.

## Errors

The error log is empty.

## Additional Notes

It might be worth noting that Firefly does save the theme preference between attempts to go through the initial setup.

**Comment by monospacedmagic** [comment]
I just ran Firefly via the terminal and it gave me a slightly more useful error message that appeard every time I would click the Confirm PIN code button:

    Error occurred in handler for 'keychain-set': [Error: The name org.freedesktop.secrets was not provided by any .service files]

Hope this helps!

**Comment by monospacedmagic** [comment]
Turns out this can be fixed simply by installing a PGP keyring that supports the Free Desktop Secret Service standard and provides an `org.freedesktop.secrets` service. I see one issue that caused this issue, however, that I would like to at least mention as it led me to creating this issue:

CLI logs should be accessible somewhere to make debugging easier from a tester's perspective, or the error log should be able to catch those errors as well.

**Comment by Prunkton** [comment]
`sudo apt install gnome-keyring` fixed it for me on KDE (KDE Wallet is not using the service)
