### ISSUE TITLE
[Bug report]: Not working, profile not showing

### ISSUE THREAD

**Issue by KryptoniteAli** [iotaledger/firefly#8536]
### Version

3.0.0

### Description

The app didn't display anything like the wallet I have created and also the option to add profile

### Expected behaviour

Should display the profile to open

### Actual behaviour

No display

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

![Screenshot from 2024-05-19 12-20-06](https://github.com/iotaledger/firefly/assets/121098441/87c3e9d1-f679-40a4-ad2f-26b5836726bf)

### Operating System

Linux

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Actively staking

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
Could you try purging the data and reinstalling? You can purge by removing `~/.config/Firefly\ Canary\ -\ Alpha/__storage__`
