### ISSUE TITLE
stronghold problem

### ISSUE THREAD

**Issue by GENCAY43** [iotaledger/firefly#8543]
### Version

latest

### Description

Hello, I have been keeping the firefly wallet in this wallet for about 2-3 years to save my iotas and collect shimmer and assembly. I LIVE IN ISTANBUL AND I AM A PROFESSIONAL MUSICIAN. So I'm not a bot, I'm a real person, you can check all my social media accounts and see if I'm real.
I have been having withdrawal problems with my iota firefly wallet for a while now. I'm experiencing a stronghold error. And I sent e-mails about this many times. I request you to please reply to me urgently.

### Expected behaviour

Hello, I have been keeping the firefly wallet in this wallet for about 2-3 years to save my iotas and collect shimmer and assembly. I LIVE IN ISTANBUL AND I AM A PROFESSIONAL MUSICIAN. So I'm not a bot, I'm a real person, you can check all my social media accounts and see if I'm real.
I have been having withdrawal problems with my iota firefly wallet for a while now. I'm experiencing a stronghold error. And I sent e-mails about this many times. I request you to please reply to me urgently.

### Actual behaviour

Hello, I have been keeping the firefly wallet in this wallet for about 2-3 years to save my iotas and collect shimmer and assembly. I LIVE IN ISTANBUL AND I AM A PROFESSIONAL MUSICIAN. So I'm not a bot, I'm a real person, you can check all my social media accounts and see if I'm real.
I have been having withdrawal problems with my iota firefly wallet for a while now. I'm experiencing a stronghold error. And I sent e-mails about this many times. I request you to please reply to me urgently.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Hello, I have been keeping the firefly wallet in this wallet for about 2-3 years to save my iotas and collect shimmer and assembly. I LIVE IN ISTANBUL AND I AM A PROFESSIONAL MUSICIAN. So I'm not a bot, I'm a real person, you can check all my social media accounts and see if I'm real.
I have been having withdrawal problems with my iota firefly wallet for a while now. I'm experiencing a stronghold error. And I sent e-mails about this many times. I request you to please reply to me urgently.

### Operating System

Mac

### Diagnostics

```shell
stronghold reported a procedure error: engine : fatal engine error: record error: RecordNoot Found(Chain(xYLh_agC_RULFuxyTİaLyajvXhGhrPct))
```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

Non-responsive

### Error Messages

stronghold reported a procedure error: engine : fatal engine error: record error: RecordNoot Found(Chain(xYLh_agC_RULFuxyTİaLyajvXhGhrPct))

### Error Logs

```shell
stronghold reported a procedure error: engine : fatal engine error: record error: RecordNoot Found(Chain(xYLh_agC_RULFuxyTİaLyajvXhGhrPct))
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
Hi, we dont provide email support. 
It might be that your wallet got corrupted, you can just re-import your profile using your 24 words or your latest working stronghold backup.
