### ISSUE TITLE
instal failed

### ISSUE THREAD

**Issue by juanmita28** [iotaledger/firefly#8559]
### Version

2.0.11

### Description

Sun, 23 Jun 2024 11:31:18 GMT
Generic: {"type":"error","payload":{"type":"wallet","error":"error accessing storage: Corruption: Corruption: IO error: No such file or directory: NewRandomAccessFile failed to Create/Open: C:\\Users\\cioma\\AppData\\Roaming\\Firefly/__storage__/51fc273d203f0623c454240c54584ac8/000110.ldb: El sistema no puede encontrar el archivo especificado.\r\n in file C:\\Users\\cioma\\AppData\\Roaming\\Firefly/__storage__/51fc273d203f0623c454240c54584ac8/MANIFEST-000107"}}

### Expected behaviour

i dont open program

### Actual behaviour

not open

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

None

### Crash Status

Non-responsive

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
Your installation and or profile might have corrupted, can you restore your wallet again from your 24 words or ledger?
If so, i suggest you clean up the persisted data too, it is under `C:\Users\[username]\AppData\Roaming\Firefly/__storage__` Please delete that `__storage__` folder, restart the app, and restore your wallet
