### ISSUE TITLE
[Bug report]: total balance excludes locked tokens

### ISSUE THREAD

**Issue by Buddh1n1** [iotaledger/firefly#8575]
### Version

2.0.11

### Description

Firefly displays a wrong "iota mainnet balance" excluding vested / time-locked tokens.

### Expected behaviour

The total balance should include time-locked/vested tokens.
They should remain excluded from the "available balance" just below.

### Actual behaviour

Total balance excludes vested tokens.

### Can the issue reliably be reproduced?

Yes

### Operating System

Mac

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
This information is displayed in the balance breakdown
