### ISSUE TITLE
[Bug report]: "the semantic validation of a transaction failed with conflict reason: 5 - InvalidSignature"

### ISSUE THREAD

**Issue by xrpmschrenko** [iotaledger/firefly#8576]
### Version

2.0.11

### Description

Firefly is connecting but when I try to transfer anything I get "wallet: the semantic validation of a transaction failed with conflict reason: 5 - InvalidSignature"
![Screen Shot 2024-07-12 at 5 34 54 PM](https://github.com/user-attachments/assets/71f5b6ac-7b5d-4d9b-93d5-3b401c46203d)
![Screen Shot 2024-07-12 at 12 17 32 PM](https://github.com/user-attachments/assets/e6e3a528-9789-480a-93a7-429f82cdb1d7)
![Screen Shot 2024-07-12 at 12 17 37 PM](https://github.com/user-attachments/assets/3001dd8c-ab47-42ea-a0d2-7b947ca44e15)

### Expected behaviour

I cant transfer anything because of this error: "wallet: the semantic validation of a transaction failed with conflict reason: 5 - InvalidSignature"

### Actual behaviour

I cant transfer anything because of this error: "wallet: the semantic validation of a transaction failed with conflict reason: 5 - InvalidSignature"

### Can the issue reliably be reproduced?

Yes

### Operating System

Mac

### Diagnostics

```shell
App Name: Firefly
Version 2.0.11
Language: en
Currency: usd
Node list: https://api.stardust-mainnet.iotaledger.net,https://iota-node.tanglebay.com
Platform: macOS
Platform Version: 12.6.3
Platform Architecture: x64
CPU Count: 16
Total Memory: 65536.0 MB
Free Memory: 44916.5 MB
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Never staked

### Crash Status

None of the above

### Error Messages

"wallet: the semantic validation of a transaction failed with conflict reason: 5 - InvalidSignature"

### Error Logs

```shell
Fri, 12 Jul 2024 18:26:40 GMT
wallet: `the semantic validation of a transaction failed with conflict reason: 5 - InvalidSignature`

Fri, 12 Jul 2024 18:25:18 GMT
wallet: `the semantic validation of a transaction failed with conflict reason: 5 - InvalidSignature`

Fri, 14 Jun 2024 19:02:21 GMT
wallet: `the semantic validation of a transaction failed with conflict reason: 5 - InvalidSignature`

Fri, 14 Jun 2024 19:00:57 GMT
wallet: `the semantic validation of a transaction failed with conflict reason: 5 - InvalidSignature`

Thu, 26 Oct 2023 22:23:04 GMT
wallet: `the semantic validation of a transaction failed with conflict reason: 5 - InvalidSignature`
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
That means that the ledger you are connecting is incorrect, that can happen if you have multiple ledgers or changed the mnemonic of your ledger. Please make sure you connect the same ledger with the same mnemonic you used to create the profile

**Comment by xrpmschrenko** [comment]
That must be it!!!After you sent this to me I remembered that around that time my seed phrase was compromised and I had to reset my ledger with a new one! I’m sure that Firefly was created with the original seed phrase and now the new one is the problem!!Should I buy a new ledger and load the original seed into it in order to authenticate my firefly app?Best,- Mark Schrenko On Jul 14, 2024, at 2:36 AM, Begoña Álvarez de la Cruz ***@***.***> wrote:﻿
That means that the ledger you are connecting is incorrect, that can happen if you have multiple ledgers or changed the mnemonic of your ledger. Please make sure you connect the same ledger with the same mnemonic you used to create the profile

**Comment by begonaalvarezd** [comment]
Hi, im glad the mystery is solved.
It is up to you to decide what to do with your ledger devices, get a new one, enter manually a seed phrase in an existing ledger you have, use a software profile directly, ...

I'll close this ticket because there is no issue in the code of Firefly, if you need further support you can visit our discord https://discord.iota.org/
