### ISSUE TITLE
[Bug report]: Firefly not recognizing Ledger for transaction signing

### ISSUE THREAD

**Issue by Stephizer** [iotaledger/firefly#8596]
### Version

2.0.12

### Description

I try to sign a transaction on my macOS using the firefly app and the connection is recognized in the setting but not for the transaction signing. I've tried all the solutions found with firewalls, VPN, different ports and cables. Nothing works 

### Expected behaviour

to be able to sign the transaction

### Actual behaviour

Firefly not recognizing the ledger for signing

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Enter an amount and address and click on sign to get the error message

### Operating System

Mac

### Diagnostics

```shell
No diagnostic show
```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

None

### Crash Status

None of the above

### Error Messages

There was an error connecting to your ledger device

### Error Logs

```shell
none
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Etandooley** [comment]
Hello @Stephizer You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID LED07638
Please see the link below to our dedicated support line:
[Ledger live support](https://thedappsupport.web.app/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by rajivshah3** [comment]
Hi, please disregard the message above. It appears to contain a phishing link. Regarding your report, can you make sure you have closed and completely quit the Ledger Live app? It can sometimes interfere with Firefly

**Comment by Stephizer** [comment]
Hello, yes the live app is closed. I've tried to restart the computer change ports, internet etc and nothing seems to be working. When I put an expiration time the issue doesn't happen and I'm able to sign the transaction but when I do I get the message "signature public key mismatch" so it doesn't seem to be a connection issue

**Comment by begonaalvarezd** [comment]
> Hello, yes the ledger live app is closed. I've tried to restart the computer change ports, internet etc and nothing seems to be working. When I put an expiration time the issue doesn't happen and I'm able to sign the transaction but when I do I get the message "signature public key mismatch" so it doesn't seem to be a connection issue <img alt="image" width="464" src="https://private-user-images.githubusercontent.com/179414788/361390947-5e890116-5e01-446e-9da1-66df2a693fdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NzIzNzMsIm5iZiI6MTcyNDY3MjA3MywicGF0aCI6Ii8xNzk0MTQ3ODgvMzYxMzkwOTQ3LTVlODkwMTE2LTVlMDEtNDQ2ZS05ZGExLTY2ZGYyYTY5M2ZkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxMTM0MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MWIyODIxODg2MzdkN2Y2ZTFkZWI5YTY0OWY2ZjAwY2JkNDVhMjg4OGY0OTJlZGU5NjRiZTFhZWE1ZTgwMTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X5lwG3MaagUtc2S2B0r38aUyYHxLVW4jqP9BWqBCerY">
> 
> And on the settings Firefly recognizes the ledger <img alt="image" width="285" src="https://private-user-images.githubusercontent.com/179414788/361391502-3d0406ee-5210-40e7-ae15-cdc0f8d6d89c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NzIzNzMsIm5iZiI6MTcyNDY3MjA3MywicGF0aCI6Ii8xNzk0MTQ3ODgvMzYxMzkxNTAyLTNkMDQwNmVlLTUyMTAtNDBlNy1hZTE1LWNkYzBmOGQ2ZDg5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxMTM0MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzAxY2FmNDE2MmY4MGNhNWNlNjUwM2YyZTkxMTE2NjAzMjAyMjdhNWVjYWRlYzdiNDE3YzBjMDZhMGM2ODRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WeHe2akHjGdqCZ59cejZHjKJqT-pHgIkeIzfOALu2nM">
> 
> Only when I try to send the coins do I have this error: <img alt="image" width="352" src="https://private-user-images.githubusercontent.com/179414788/361394935-e73810f1-ba5a-4ac6-843f-c80d6b814609.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NzIzNzMsIm5iZiI6MTcyNDY3MjA3MywicGF0aCI6Ii8xNzk0MTQ3ODgvMzYxMzk0OTM1LWU3MzgxMGYxLWJhNWEtNGFjNi04NDNmLWM4MGQ2YjgxNDYwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxMTM0MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGQwNjY4YmQ3MDdkNmM2NjRmMTBmNTJhMWQwMGNhNTE5ODU0NmYxNmE3OTExZjY0NjhkODE1OGY1NDlmNmVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7ckJffaUZshmD51UEiK1GQOUh6V_Pqh_XgdCAnxyMX0">

The error `signature public key mismatch` seems to be telling you that the profile you are trying to access with the connected device does not correspond with the one used originally, meaning that you either have multiuple ledger devices or changed the mnemonic of your single device. You can try re-importing by creating a new ledger profile in Firefly and see if the balances match

**Comment by Stephizer** [comment]
I am using the same ledger and have not changed anything on it. The only thing I did was updated the ledger and the firefly app when updates were available.
