### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by MI999M** [iotaledger/firefly#8602]
### Version

2.0.12

### Description

![2024-06-13_231001](https://github.com/user-attachments/assets/1f7781d5-c68d-40db-bb43-97cb87e8eaf7)

### Expected behaviour

![2024-06-13_231001](https://github.com/user-attachments/assets/07aeffb8-4c59-49b3-abba-165a5b0cab2b)

### Actual behaviour

не могу войти в приложение. ввожу пинкод . и дальше выдает как на картинке внизу  справа.
![2024-09-02_174343](https://github.com/user-attachments/assets/f70266b0-b63a-4356-8e38-5a79469e740e)

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by laalauren1** [comment]
> ### Version
> 2.0.12
> 
> ### Description
> ![2024-06-13_231001](https://private-user-images.githubusercontent.com/123558320/363691953-1f7781d5-c68d-40db-bb43-97cb87e8eaf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzIzMTEsIm5iZiI6MTcyNTM3MjAxMSwicGF0aCI6Ii8xMjM1NTgzMjAvMzYzNjkxOTUzLTFmNzc4MWQ1LWM2OGQtNDBkYi1iYjQzLTk3Y2I4N2U4ZWFmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxNDAwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjY5NWY0MWFkMzJlNGEwODkyZTE4Y2VmMTIzYTk3NGY0ZTU3Zjk1ODM3Y2ZjOTM3NWJlMzU4Yjk2YzlmZDcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1usWhVbwxz4QRV3EYbSBkSsYW3FRgadQZYesHi9rYmQ)
> 
> ### Expected behaviour
> ![2024-06-13_231001](https://private-user-images.githubusercontent.com/123558320/363692324-07aeffb8-4c59-49b3-abba-165a5b0cab2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzIzMTEsIm5iZiI6MTcyNTM3MjAxMSwicGF0aCI6Ii8xMjM1NTgzMjAvMzYzNjkyMzI0LTA3YWVmZmI4LTRjNTktNDliMy1hYmJhLTE2NWE1YjBjYWIyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxNDAwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2NhM2QzMzMzZmIwNjExYTkwMTYwMWJiNWZkYWU4ZGI2NDZiZjc2YzU4YzU5ZWVkMzkwYWRkZmUyMjE4ZjM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YaOEo-FjPzOf1ndtqkxe99cdtFir2aya4g9gl5ZToMg)
> 
> ### Actual behaviour
> не могу войти в приложение. ввожу пинкод . и дальше выдает как на картинке внизу справа. ![2024-09-02_174343](https://private-user-images.githubusercontent.com/123558320/363693380-f70266b0-b63a-4356-8e38-5a79469e740e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzIzMTEsIm5iZiI6MTcyNTM3MjAxMSwicGF0aCI6Ii8xMjM1NTgzMjAvMzYzNjkzMzgwLWY3MDI2NmIwLWI2M2EtNDM1Ni04ZTM4LTVhNzk0NjllNzQwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxNDAwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWM5NDMyY2Y1NTNhYWY2NTIzNzUyNjU1ZmZlMmM3ZWY1MmVmNDdmNWE0OGVhOGI4MDcyN2Y2MjNhZDg2MmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MWKuLg5Hi-Uu7tIXg-H0hk5Sn_McQlaGW0MZx4uE_zM)
> 
> ### Can the issue reliably be reproduced?
> Yes
> 
> ### Steps to reproduce the issue
> _No response_
> 
> ### Operating System
> Windows
> 
> ### Diagnostics
> _No response_
> 
> ### Developer Profile
> No
> 
> ### Profile Type
> Software (Stronghold)
> 
> ### Staking
> None
> 
> ### Crash Status
> None of the above
> 
> ### Error Messages
> _No response_
> 
> ### Error Logs
> _No response_
> 
> ### Duplicate declaration
> * [x]  I have searched the issues tracker this issue and there is none
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

@MI999M thank you for opening this bug You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID STE07638
Please see the link below to our dedicated support line:
[Stellar live support](https://thedappsupport.web.app)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by begonaalvarezd** [comment]
⚠️ ⚠️ ⚠️ ⚠️  Please do not follow any links from the previous message, it was a scam message ⚠️ ⚠️ ⚠️ ⚠️

**Comment by begonaalvarezd** [comment]
The error means that your system does not have the right time, please sync your machine and try again, the issue should be gone when the time is correct
