### ISSUE TITLE
[Bug report]: 

### ISSUE THREAD

**Issue by Mirco28021980** [iotaledger/firefly#8603]
### Version

2.0.12

### Description

![image](https://github.com/user-attachments/assets/6613622d-1016-43c0-b14e-fa4f8a4a1bbc)

### Expected behaviour

bug timestamp wrong

### Actual behaviour

Anmeldung scheitert

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

Previously staked

### Crash Status

None of the above

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
The error means that your system does not have the right time, please sync your machine and try again, the issue should be gone when the time is correct
