### ISSUE TITLE
[Task]: Migrate to new 2.0.12 firefly wallet 

### ISSUE THREAD

**Issue by Simonsiota** [iotaledger/firefly#8604]
### Task description

I am unable to migrate to new software. Please see screenshot.

Where can I find page to access wallet with 24 word secret seed.
![Screenshot 2024-09-03 124609](https://github.com/user-attachments/assets/7f75c8f6-5e64-469a-9c93-13894f5377e3)

**Comment by Hansi-cross** [comment]
you get this page with 24 phrases, when you registered the first time. you have to save it. if not, you have no access.

BR
Hansi

**Comment by begonaalvarezd** [comment]
In order top be able to migrate you have to decrypt the stronghold/backup file wih thte password you originally set. If you dont remember it, you can simply create a new profile with your 24 words
