### ISSUE TITLE
[Task]: Update on #8604

### ISSUE THREAD

**Issue by Simonsiota** [iotaledger/firefly#8605]
### Task description

I have the new software but it does not like my password. How do I access wallet with my 24 word secret seed.
![Screenshot 2024-09-03 124609](https://github.com/user-attachments/assets/118560d6-7d1e-4cdd-be6d-97f098fa1f69)

**Comment by begonaalvarezd** [comment]
If you dont remember your password your can re-import your 24 words as a new profile
