### ISSUE TITLE
[Bug report]:

### ISSUE THREAD

**Issue by Jo6j9** [iotaledger/firefly#8622]
### Version

2.0.8 y 2.0.12

### Description

buenas noches, el problema que tengo es que no puedo abrir la aplicación de firefly con mi Ledger cuando pongo el pin correcto me sale un mensaje que dice; 
Local time 1729110427 Doesn't match The time of latest milestone timestamp 1729110115
 la numeración cambia con cada intento que hago para poder acceder a la aplicación de Firefly. 
El pin es correcto y no puedo abrir la aplicación de monedero Firefly iota
les pido por favor si me pueden ayudar a solucionar este problema. Gracias

### Expected behaviour

no se nunca me ha ocurrido

### Actual behaviour

no funciona no puedo acceder a la aplicacion

### Can the issue reliably be reproduced?

No

### Operating System

Windows

### Diagnostics

Nombre de la Aplicacion: Firefly
Versión 2.0.12
Idioma: es-ES
Plataforma: win32
Versión de la plataforma: 10.0.22631
Arquitectura de la plataforma: x64
Número de CPU: 16
Memoria Total: 16052.0 MB
Memoria Libre: 10636.3 MB

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

Actively staking

### Crash Status

Non-responsive

### Error Messages

Thu, 17 Oct 2024 20:19:54 GMT
wallet: `local time 1729196394 doesn't match the time of the latest milestone timestamp: 1729196077`

Thu, 17 Oct 2024 17:40:29 GMT
wallet: `local time 1729186829 doesn't match the time of the latest milestone timestamp: 1729186512`

Thu, 17 Oct 2024 17:40:06 GMT
wallet: `local time 1729186806 doesn't match the time of the latest milestone timestamp: 1729186490`

Thu, 17 Oct 2024 17:38:13 GMT
wallet: `local time 1729186693 doesn't match the time of the latest milestone timestamp: 1729186376`

Thu, 17 Oct 2024 17:36:54 GMT
wallet: `local time 1729186614 doesn't match the time of the latest milestone timestamp: 1729186300`

Thu, 17 Oct 2024 10:18:11 GMT
wallet: `local time 1729160291 doesn't match the time of the latest milestone timestamp: 1729159976`

Thu, 17 Oct 2024 10:05:08 GMT
wallet: `local time 1729159508 doesn't match the time of the latest milestone timestamp: 1729159191`

Thu, 17 Oct 2024 09:50:24 GMT
wallet: `local time 1729158624 doesn't match the time of the latest milestone timestamp: 1729158309`

Thu, 17 Oct 2024 09:45:49 GMT
wallet: `local time 1729158349 doesn't match the time of the latest milestone timestamp: 1729158036`

Thu, 17 Oct 2024 09:40:51 GMT
wallet: `local time 1729158051 doesn't match the time of the latest milestone timestamp: 1729157739`

Thu, 17 Oct 2024 09:40:30 GMT
wallet: `local time 1729158030 doesn't match the time of the latest milestone timestamp: 1729157713`

Thu, 17 Oct 2024 09:37:27 GMT
wallet: `local time 1729157846 doesn't match the time of the latest milestone timestamp: 1729157534`

Thu, 17 Oct 2024 09:22:08 GMT
wallet: `local time 1729156928 doesn't match the time of the latest milestone timestamp: 1729156611`

Thu, 17 Oct 2024 09:21:54 GMT
wallet: `local time 1729156914 doesn't match the time of the latest milestone timestamp: 1729156600`

### Error Logs

Thu, 17 Oct 2024 20:19:54 GMT
wallet: `local time 1729196394 doesn't match the time of the latest milestone timestamp: 1729196077`

Thu, 17 Oct 2024 17:40:29 GMT
wallet: `local time 1729186829 doesn't match the time of the latest milestone timestamp: 1729186512`

Thu, 17 Oct 2024 17:40:06 GMT
wallet: `local time 1729186806 doesn't match the time of the latest milestone timestamp: 1729186490`

Thu, 17 Oct 2024 17:38:13 GMT
wallet: `local time 1729186693 doesn't match the time of the latest milestone timestamp: 1729186376`

Thu, 17 Oct 2024 17:36:54 GMT
wallet: `local time 1729186614 doesn't match the time of the latest milestone timestamp: 1729186300`

Thu, 17 Oct 2024 10:18:11 GMT
wallet: `local time 1729160291 doesn't match the time of the latest milestone timestamp: 1729159976`

Thu, 17 Oct 2024 10:05:08 GMT
wallet: `local time 1729159508 doesn't match the time of the latest milestone timestamp: 1729159191`

Thu, 17 Oct 2024 09:50:24 GMT
wallet: `local time 1729158624 doesn't match the time of the latest milestone timestamp: 1729158309`

Thu, 17 Oct 2024 09:45:49 GMT
wallet: `local time 1729158349 doesn't match the time of the latest milestone timestamp: 1729158036`

Thu, 17 Oct 2024 09:40:51 GMT
wallet: `local time 1729158051 doesn't match the time of the latest milestone timestamp: 1729157739`

Thu, 17 Oct 2024 09:40:30 GMT
wallet: `local time 1729158030 doesn't match the time of the latest milestone timestamp: 1729157713`

Thu, 17 Oct 2024 09:37:27 GMT
wallet: `local time 1729157846 doesn't match the time of the latest milestone timestamp: 1729157534`

Thu, 17 Oct 2024 09:22:08 GMT
wallet: `local time 1729156928 doesn't match the time of the latest milestone timestamp: 1729156611`

Thu, 17 Oct 2024 09:21:54 GMT
wallet: `local time 1729156914 doesn't match the time of the latest milestone timestamp: 1729156600`

### Duplicate declaration

- [x] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
El error que estas experimento es a causa de tener la hora de tu ordenador mal, sincroniza el reloj de manera automática o con sincronización manual y ya deberías poder entrar
Si sigues teniendo problemas puedes volver a abrir el issue

**Comment by MACCON591** [comment]
Buenas ! No se si alguien me puede ayudar.Hacia tiempo que entraba en firefly con iota puesto que las estaba holdeando en la wallet y cual a sido mi sorpresa que no me deja entrar como habitualmente lo venia haciendo que hera con usuario y contraseña.Me redirecciona a poder emigrar en mi caso a la nueva wallet de IOTA pero me pide las palabras de recuperacion.Cuando cree la wallet estas semillas no recuerdo haberla obtenido ( soy metodico para eso ).El problema es que no puedo acceder a la wallet y no se como gestionarlo para poder acceder.¿Alguien me puede ayudar o darme una direccion de correo se soporte ?

Gracias
