### ISSUE TITLE
[Task]: Code doesnt work but i have my security phrase

### ISSUE THREAD

**Issue by RAYban40** [iotaledger/firefly#8628]
### Task description

please help me input my security phrase rather than code. code does not give me access

**Comment by begonaalvarezd** [comment]
Hi, i am not sure I am understanding your issue. If you want to access your funds you can use your mnemonic (security phrase) to import an existing profile.

**Comment by Hansi-cross** [comment]
![Image](https://github.com/user-attachments/assets/f47d360c-c8d0-4321-b9d0-bdf1fc514719)
this appears, when i use my PIN. After importing the backup/stronghold.

BR
Hansi

**Comment by begonaalvarezd** [comment]
You have your machine clock not in sync, hence the error. Just syncronize it or set it to automatic to fix the problem
