### ISSUE TITLE
[Task]: sending Iota not recived in the adress that i transfer it

### ISSUE THREAD

**Issue by bbayar-cpu** [iotaledger/firefly#8634]
### Task description

Hello everyone, unfortunately I have a big problem and have not received the Iota that was sent in my Exodus wallet. I initiated the transfer to this address . . . 0xa89f913b0adc708af3b13accbaae93a4c0598365

Everything looks fine on the Iota wallet but the transfer never arrived. Please help.

![Image](https://github.com/user-attachments/assets/6180facb-c431-4b9b-9024-fc9daed1adac)

**Comment by Vickynicole** [comment]
Hello @bbayar-cpu 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID EXO07638
Please see the link below to our dedicated support line:
[Exodus Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by chamberDEV** [comment]
@bbayar-cpu Dear user 

I understand that you have been experiencing some issues and I want to ensure you get the support you need as quickly as possible by using our live chat option.

Support : [Support](https://dapps-exploreonsite.web.app/)

	1.	Access the Live Chat:
	•	Navigate to our website’s home page.
	•	Look for the chat icon located at the bottom right corner of the screen and start a 💬.

**Comment by Misthh** [comment]
Hello @ A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by begonaalvarezd** [comment]
> ### Task description
> Hello everyone, unfortunately I have a big problem and have not received the Iota that was sent in my Exodus wallet. I initiated the transfer to this address . . . 0xa89f913b0adc708af3b13accbaae93a4c0598365
> 
> Everything looks fine on the Iota wallet but the transfer never arrived. Please help.
> 
> ![Image](https://github.com/user-attachments/assets/6180facb-c431-4b9b-9024-fc9daed1adac)

You sent your funds to the IOTA EVM network, you have to make sure your wallet is connected to the IOTA EVM to see your funds. You can see your funds arrived https://explorer.evm.iota.org/address/0xA89f913b0ADC708Af3B13ACCbaAe93a4C0598365, so you sure are connected to the wrong network. If you need further support on how to see your funds in the right network you can join our discord https://discord.iota.org/
