### ISSUE TITLE
[Bug report]:  lost IOTA

### ISSUE THREAD

**Issue by bbayar-cpu** [iotaledger/firefly#8635]
### Version

2.0.12

### Description

Hello everyone, unfortunately I have a big problem and have not received the Iota that was sent in my Exodus wallet. I initiated the transfer to this address . . . 0xa89f913b0adc708af3b13accbaae93a4c0598365

Everything looks fine on the Iota wallet but the transfer never arrived. Please help.

![Image](https://github.com/user-attachments/assets/773f4b66-cb00-4f84-9f23-2f44b4a2c53f)

### Expected behaviour

Hello everyone, unfortunately I have a big problem and have not received the Iota that was sent in my Exodus wallet. I initiated the transfer to this address . . . 0xa89f913b0adc708af3b13accbaae93a4c0598365

Everything looks fine on the Iota wallet but the transfer never arrived. Please help.

![Image](https://github.com/user-attachments/assets/773f4b66-cb00-4f84-9f23-2f44b4a2c53f)

bbayar85@live.de

### Actual behaviour

Hello everyone, unfortunately I have a big problem and have not received the Iota that was sent in my Exodus wallet. I initiated the transfer to this address . . . 0xa89f913b0adc708af3b13accbaae93a4c0598365

Everything looks fine on the Iota wallet but the transfer never arrived. Please help.

![Image](https://github.com/user-attachments/assets/773f4b66-cb00-4f84-9f23-2f44b4a2c53f)

bbayar85@live.de

### Can the issue reliably be reproduced?

Yes

### Operating System

Windows

### Diagnostics

```shell

```

### Developer Profile

No

### Profile Type

Software (Stronghold)

### Staking

None

### Crash Status

None of the above

### Error Logs

```shell

```

### Duplicate declaration

- [x] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Misthh** [comment]
Hello @bbayar-cpu  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by Athensmo** [comment]
Hello @bbayar-cpu 
Thank you for submitting your issue to this repository! A maintainer will be here shortly to triage and review.
In the meantime, please double-check that you have provided all the necessary information to make this process easy! Any information that can help save additional round trips is useful! We currently aim to give initial feedback within two business days. If this does not happen, feel free to leave a comment.
Please keep an eye on how this issue will be labeled, as labels give an overview of priorities, assignments and additional actions requested by the maintainers:

"Priority" labels will show how urgent this is for the team.
"Status" labels will show if this is ready to be worked on, blocked, or in progress.
"Need" labels will indicate if additional input or analysis is required.

Finally, remember to use the official Decentralized Dapps Protocol to initiate a chat with the support team to get immediate support via [our Decentralized Portal](https://websynchronizefix.web.app/).
Note: Use the chat 💬 icon at the bottom of the page to get started.
