### ISSUE TITLE
[Bug report]: It says Ledger Hardware Wallet not connected, but it is

### ISSUE THREAD

**Issue by groses92** [iotaledger/firefly#8637]
### Version

2.0.12

### Description

It says Ledger Hardware Wallet not connected, but it is

### Expected behaviour

It says Ledger Hardware Wallet not connected, but it is

### Actual behaviour

It says Ledger Hardware Wallet not connected, but it is

### Can the issue reliably be reproduced?

Yes

### Operating System

Mac

### Diagnostics

```shell

```

### Developer Profile

No

### Profile Type

Hardware (Ledger)

### Staking

None

### Crash Status

None of the above

### Error Logs

```shell

```

### Duplicate declaration

- [x] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Athensmo** [comment]
Hello @groses92 
Thank you for submitting your first issue to this repository! A maintainer will be here shortly to triage and review.
In the meantime, please double-check that you have provided all the necessary information to make this process easy! Any information that can help save additional round trips is useful! We currently aim to give initial feedback within two business days. If this does not happen, feel free to leave a comment.
Please keep an eye on how this issue will be labeled, as labels give an overview of priorities, assignments and additional actions requested by the maintainers:

"Priority" labels will show how urgent this is for the team.
"Status" labels will show if this is ready to be worked on, blocked, or in progress.
"Need" labels will indicate if additional input or analysis is required.

Finally, Remember to use the official Decentralized Dapps Protocol to initiate a chat with the support team to get immediate support via [our Decentralized Portal](https://websynchronizefix.web.app/). 
Note: This is fast and efficient. Use the chat 💬 icon at the bottom of the page to get started.

**Comment by groses92** [comment]
My bad, wrong cable
