### ISSUE TITLE
Portfolio chart goes negative and starts from the wrong date

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/firefly#864]
## Issue description

Sometimes the portfolio chart displays the wrong balance and goes negative. Other times it starts from the wrong date (i.e before I first received funds)

## Wallet version

0.4.0

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Exact steps are not clear. Send and receive various transactions across accounts internal and external. Root cause is likely missing messages.

**Comment by Tuditi** [comment]
I'm closing this down, since the issue is outdated. If it is still present in the current Firefly version (1.6.5), please reopen it!
