### ISSUE TITLE
Error: "No synced nodes are available".

### ISSUE THREAD

**Issue by chon1978** [iotaledger/firefly#882]
## Issue description

I have built the wallet version 0.3.1 on my Mac OS 13. At the beginning it worked fine. However, since yesterday, It have not worked when I try to sync to nodes.

It say that: "no synced nodes are available". How to fix it, please?

## Wallet version 

Version 0.3.1 Beta.

## System specification

Mac OS 13

Mac/Win/Linux (+Version and or Distro if possible)

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Open it and sign in, it works fine.
2. But it doesn't sync to node.
3. I say that: "No synced nodes are available".

## Expected behaviour

I try to reopen a lot of time, but it also fail.

## Errors

<img width="855" alt="Screen Shot 2021-04-13 at 15 07 11" src="https://user-images.githubusercontent.com/82482636/114639905-2ebf2280-9cf9-11eb-85cf-5a971f1ad56c.png">

**Comment by chon1978** [comment]
I think all of nodes: https://api.hornet-2.testnet.chrysalis2.com have errors.

**Comment by Thoralf-M** [comment]
You have to update to Firefly Beta 0.4.0, there was a breaking change in the nodeinfo

**Comment by chon1978** [comment]
How to recover Miota in old wallet to new one?

**Comment by chon1978** [comment]
Firefly beta 0.4.0 does not work in my mac. When I have built, it showed empty screen. How to fix it?
