### ISSUE TITLE
FireFly 0.4.0 does not allow decimal point entry of Mi (German, Swiss German system settings)

### ISSUE THREAD

**Issue by github-i286** [iotaledger/firefly#883]
## Issue description

Entering a decimal point for a Mi transfer is not possible.
It only allows a comma ",".
![image](https://user-images.githubusercontent.com/24428771/114662963-da687280-9cf9-11eb-8d65-633ab70dc03a.png)

However when proceeding, the comma is removed and only integer Mi are transferred.
![image](https://user-images.githubusercontent.com/24428771/114663238-45b24480-9cfa-11eb-80f3-997e4eef56ee.png)

The only way to send fractions is to switch to Ki or i units.

## Wallet version

FireFly 0.4.0, German Language
Possibly is not work also with other language settings.

## System specification

Windows 10, Swiss German Settings:
![image](https://user-images.githubusercontent.com/24428771/114663150-25828580-9cfa-11eb-9369-360a2e7ea720.png)
Possibly is not work also with other language settings.

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Set Windows to Swiss German (decimal point '.')
2. Install FireFly 0.4.0 Wallet, set German
3. Try to transfer fractions of Mi. Entering decimal point is not possible. Entering a comma is possibly, but fractions are ignored.

## Expected behaviour

Allow fractions if Mis to be seind.

## Actual behaviour

You need to switch to Ki o i to send fractions of Mi

## Errors

No error is displayed, fractions are silently ignored.

**Comment by Travetown** [comment]
In my setting / German / EUR I have set the normal standard for Germany (comma for decimal places). In this case, however, I cannot enter a comma.

<img width="357" alt="Bildschirmfoto 2021-04-14 um 09 03 20" src="https://user-images.githubusercontent.com/66588710/114667833-43eb7f80-9d00-11eb-904c-5a4480941e23.png">

**Comment by obany** [comment]
I acknowledge there is a bug here with formatting, parsing.
The currency format is actually picked up from the browser/electron language (would normally match the OS) and is not affected by any of the settings in Firefly itself.

**Comment by github-i286** [comment]
It would be very confusing for a end user when not to use the OS system settings.
I don't even know where I would be able to change the settings of the electron browser? I habe Egde, IE, Chrom and Firefox installed on my computer.
It's also very dangerous to just ignore certain characters, like '.' or ','. For example you type 1.25 (Mi), but FireFly ignores the dot and sends 125 Mi instead. That 100x the intended value. Of course you have to confirm the transaction, but errors will total wrong values are very easily made this way.
It would be better to accept all characters and finally make a paring with error message, or error while typing.

**Comment by obany** [comment]
I have already stated that is a bug not accepting the decimal separator under certain language settings. The electron setting are picked up from the OS by default, but we also have language and currency setting within Firefly. The question is which ones takes priority.

**Comment by obany** [comment]
My local build with the fixes now appears like this
![image](https://user-images.githubusercontent.com/5030334/114678055-c70dd500-9d02-11eb-8889-27b7f62130f3.png)

**Comment by github-i286** [comment]
But your screenshot is now a wild mix of commas and dots:
![image](https://user-images.githubusercontent.com/24428771/114678715-cfb6d900-9d0b-11eb-86b2-1d513e25fdee.png)
For entry and to display I recommend only using the system settings. I may use English language, but still keep my Swiss German number and date format settings. Language selection has nothing to do with locals settings.

**Comment by obany** [comment]
I am still formatting the MIOTA stuff, its was more to highlight the EUR input and amount sending is correct

**Comment by github-i286** [comment]
I do think its false to localize the number format according to the **currency**. The displayed and entered number format should only depend localizing settings. For example, me as Swiss like to see number like CHF 1'234.56 and even Euros as EUR 1'234.56. A German may likes to see and enter all numbers as 1.234,56, regardless of the chosen currency. A Hindi may likes to see all numbers very differently. You may make your job easier and just use only Intl.NumberFormat, not adding any currency "localisation" on top.
You may use this https://phrase.com/blog/posts/number-localization/ as a reference.
my 2 cents...
