### ISSUE TITLE
Clicking deeplink when Firefly is closed doesn't work properly

### ISSUE THREAD

**Issue by JanOonk** [iotaledger/firefly#884]
## Issue description

Clicking a deeplink when Firefly is closed does not work. It will start FF, but after you click a profile and pin only startscreen appears.
Clicking a deeplink when Firefly is open does work: it will bring you to transaction screen which is prefilled with address and optionally amount when given

## Wallet version

v0.4

## System specification

Windows 10

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Make a deeplink on a webpage for example: `iota://atoi1qqzvmh85v36z054guuscakrxvqhnpu0hwf4989g9hjg529sqyaw9z3fhml0/?amount=1000`
2. Be sure Firefly is not started
3. Click deeplink
4. Firefly will start and after clicking profile and pin you will see the startscreen not the (prefilled) transaction screen

## Expected behaviour

Firefly should start and after selecting profile and typing pin you should see a prefilled transaction screen.

## Actual behaviour

Firefly is started, and after clicking profile and typing pin, you see the startscreen not the (prefilled) transaction screen

## Errors

No actual errors

**Comment by obany** [comment]
This PR has not been merged yet, will appear in a future build https://github.com/iotaledger/firefly/pull/773

**Comment by cvarley100** [comment]
Deep linking has been disabled until a later version.
