### ISSUE TITLE
No synced nodes available

### ISSUE THREAD

**Issue by Renegade0815** [iotaledger/firefly#885]
After installing and setting up Firefly v0.3.1. (Windows 10 Pro) I get the error message "No synced nodes available". 
"Manual node selection" does not work either.

**Comment by Thoralf-M** [comment]
Same as here, you need to update to v0.4 https://github.com/iotaledger/firefly/issues/882#issuecomment-819290833

**Comment by Renegade0815** [comment]
Ok, ich habe es auch gerade gesehen. ThanX.

**Comment by Renegade0815** [comment]
Ok, I just saw it too. ThanX.
