### ISSUE TITLE
[UI/UX] Make account setting directly available with right click

### ISSUE THREAD

**Issue by dev0pa** [iotaledger/firefly#894]
These account settings
![1](https://user-images.githubusercontent.com/81360970/114761892-62ce2e00-9d61-11eb-8816-229d23608345.jpg)

make available also here with each individual account me right-click
![2](https://user-images.githubusercontent.com/81360970/114762064-9b6e0780-9d61-11eb-88c9-23942e327763.jpg)

**Comment by maxwellmattryan** [comment]
Hey @dev0pa, thanks again for the suggestion! I've also moved this one to a discussion [here](https://github.com/iotaledger/firefly/discussions/1512) 👍
