### ISSUE TITLE
Invalid send address error is not descriptive 

### ISSUE THREAD

**Issue by beeetrooot** [iotaledger/firefly#899]
## Issue description

When sending from the iota wallet, if a character in the address after 'atoi' is incorrect, then the error notification 'Something went wrong' is displayed.  A more descriptive error message should be displayed.  e.g. Invalid address.

**Note:  This is related to issue 715 that has been closed.**

## Wallet version

0.4.0

## System specification

Windows 10

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Select send button.
2. Paste a valid address to send to.  
3. Change the last character of the address so that the address is now invalid.
4. Send the transaction.
5. Error notification 'Something went wrong' is displayed.

## Expected behaviour

Error message 'Invalid address' is displayed.

## Actual behaviour

Error notification 'Something went wrong' is displayed.

## Errors

Error log:
InvalidType: Invalid type of action received.

**Comment by obany** [comment]
Fixed with https://github.com/iotaledger/firefly/pull/886
