### ISSUE TITLE
[UI] Hover 'Create' next 'Accounts' is working wrong.

### ISSUE THREAD

**Issue by gtgalone** [iotaledger/firefly#902]
## Issue description

When I hover 'create' button next Accounts on main screen with Korean Language,

it is working wrong. With English Language works right way.

Maybe string length problem.

## Wallet version

Which version of wallet are you using?

- wallet version (version number, commit, or branch): 0.4.0

## System specification

What is your operating system?

Mac Big Sur 11.2.3

## Is it a repeatable issue?

Y

![Kapture 2021-04-15 at 22 16 54](https://user-images.githubusercontent.com/23162037/114975553-4bfb0a80-9e39-11eb-899f-74bf7b97f611.gif)

**Comment by obany** [comment]
Fixed with https://github.com/iotaledger/firefly/pull/903
