### ISSUE TITLE
FireFly 0.4.0 wont display anything (white screen on ubuntu 20.04)

### ISSUE THREAD

**Issue by alaakaazaam** [iotaledger/firefly#904]
## Issue description

On linux 'Ubuntu 20.04.2 LTS ', the cmdLine './firefly-desktop-0.4.0.AppImage &' starts the wallet with a blank screen and nothing else happens

## Wallet version

firefly-desktop-0.4.0 from here : https://github.com/iotaledger/firefly/releases/tag/desktop-0.4.0

## System specification

$ cat /etc/issue
Ubuntu 20.04.2 LTS \n \l
$ uname -a
Linux ste64 5.4.0-47-lowlatency #51-Ubuntu SMP PREEMPT Fri Sep 4 20:46:20 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

## Is it a repeatable issue?

Y

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. give execution right : chmod 775 ./firefly-desktop-0.4.0.AppImage
2. run it with simple cmdline : ./firefly-desktop-0.4.0.AppImage &

## Expected behaviour

One would expect the wallet screen to show a wizard for creating the account

## Actual behaviour

Wallet only displays a blank white screen

## Errors

My console shows only this : 
 15:13:22.931 › Checking for update
15:13:28.514 › Update for version 0.4.0 is not available (latest version: 0.3.1, downgrade is disallowed).

**Comment by rajivshah3** [comment]
Does version 0.3.1 work for you?

**Comment by alaakaazaam** [comment]
Yes it works (still) but i had to retrieve the ~/.config/Firefly Beta folder (renamed in order to test the 0.4.0 version)
<br>
![testFirefFly_0 3 1_ok](https://user-images.githubusercontent.com/6622814/115107165-7350f500-9f69-11eb-837f-24bab86cc283.png)

**Comment by cvarley100** [comment]
Closing due to the release of 1.0.0. Please reopen with the version difference if it happens there.
