### ISSUE TITLE
local API and message channels

### ISSUE THREAD

**Issue by michalisioak** [iotaledger/firefly#915]
## Description

a local interface for installed apps (and websites) to get user info, establish a connection etc.
In addition, an app could request for a separate channel to send messages to other users on behalf of the user after granting the app access.

## Motivation

I think these features are essentials for fully decentralised apps.
I would personally use them.
Moreover, messaging channels would upgrade user privacy by not giving access to a conversation to other apps and adding functionality to the wallet.

## Requirements

1. a local (rest) api to get info, send messages, handle payments etc
2. password protected messaging channels (password would be (preferably) randomly generated from the first app accessing the channel) 
3. request for override password for channel endpoint (something like android's special permission request).If granted by the user the new app sets the new password.
4. reserved channel for direct user messages

## Are you planning to do it yourself in a pull request?

probable no

**Comment by maxwellmattryan** [comment]
Hey @michalisioak, I've closed this issue and moved it into a discussion [here](https://github.com/iotaledger/firefly/discussions/1501).
