### ISSUE TITLE
Refreshing latest tx after test-migration leads to error

### ISSUE THREAD

**Issue by RubensGitHub** [iotaledger/firefly#924]
## Issue description

After successfully going through a test-migration, refreshing the "latest transaction" field leads to a "Something went wrong"-Error. I have not added any additional nodes to the wallet.   
Log error message: 

`Mon, 19 Apr 2021 09:11:53 GMT
ClientError: error sending request for url (https://api.lb-0.migration4.iotatestmigration4.net/api/v1/addresses/atoi1qzt5sn2jud0hehr35tnzaampc586lwfhem24nhkdax6d0m8p64vxypcmer3/outputs?include-spent=true): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

## Wallet version

v0.4.0: https://github.com/iotaledger/firefly/actions/runs/762130940

## System specification

What is your operating system?

Windows 10

## Is it a repeatable issue?

Yes

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1. Go through a migration process
2. Refresh latest tx 

## Expected behaviour

Simple refreshing the latest transactions

## Actual behaviour

On the bottom right, a basic error message shows.

## Errors

UI: "Error: Something went wrong."

Detailed error from log file: 
`Mon, 19 Apr 2021 09:11:53 GMT
ClientError: error sending request for url (https://api.lb-0.migration4.iotatestmigration4.net/api/v1/addresses/atoi1qzt5sn2jud0hehr35tnzaampc586lwfhem24nhkdax6d0m8p64vxypcmer3/outputs?include-spent=true): error trying to connect: dns error: Der angegebene Host ist unbekannt. (os error 11001)`

![Screenshot_15](https://user-images.githubusercontent.com/44226748/115213040-6f57db00-a101-11eb-9473-d845b43bec89.png)

**Comment by cvarley100** [comment]
Fixed with 1.0.0.
