### ISSUE TITLE
Clicking on "Learn about spent addresses" does not work

### ISSUE THREAD

**Issue by NaitsabesMue** [iotaledger/firefly#927]
## Issue description

Clicking on "Learn about spent addresses" does not work

## Wallet version

v. 0.4.0 Mac

- wallet version (version number, commit, or branch):

## System specification

What is your operating system?

Mac/

## Expected behaviour

Infos on spent addresses should appear

## Actual behaviour

Nothing

**Comment by obany** [comment]
This is fixed in the release version
