### ISSUE TITLE
FireFly  Token Migration

### ISSUE THREAD

**Issue by Iota2021** [iotaledger/firefly#963]
## Issue description

Briefly describe the issue.

## Wallet version

Which version of wallet are you using?FireFly

- wallet version (version number, commit, or branch):0.4.0

## System specification

What is your operating system?Win

Mac/Win/Linux (+Version and or Distro if possible)Win

## Is it a repeatable issue?Y

Y/N

## Steps To reproduce the issue

Explain how the maintainer can reproduce the issue.

1.
2.
3.

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.Hi,

Just have a query trying to migrate my tokens from old Trinity Wallet to Firefly having issues with error 81 word Seed not supported?

## Errors

Paste any errors that you see from the Error Log in the Firefly menu or share screenshots of the issue.

**Comment by Thoralf-M** [comment]
Wait for the new release

**Comment by cvarley100** [comment]
This is possible only in version 1.0.0 onwards.
