### ISSUE TITLE
"Legacy Network" not translate-able on transaction window window 

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/firefly#975]
## Expected behaviour
When transaction comes from migration, Send Address is "Legacy Network" and it's non-translateable, there is no string on crowdin. Please add the string to translate to the crowdin.

![Bez tytułu](https://user-images.githubusercontent.com/35224101/115542087-2ee29380-a2a0-11eb-846c-1e7f37608d8d.png)

**Comment by obany** [comment]
This is in the crowdin translations now.
