### ISSUE TITLE
Firefly desktop wallet v1.0.0 not loading (empty background)

### ISSUE THREAD

**Issue by macway** [iotaledger/firefly#989]
## Issue description

Firefly desktop wallet v1.0.0 is not loading, it only stays in an empty background
edit: firefly beta worked fine before updating, I have tried both updating the beta app and downloading the new app, also tried after deleting all associated files fom application support

## Wallet version

desktop wallet 1.0.0

## System specification

What is your operating system?

macos 10.13.6

## Is it a repeatable issue?

Y

## Errors

from the console Firefly Helper (Renderer) .crash file:

Process:               Firefly Helper (Renderer) [1644]
Path:                  /Applications/Firefly.app/Contents/Frameworks/Firefly Helper (Renderer).app/Contents/MacOS/Firefly Helper (Renderer)
Identifier:            Firefly Helper (Renderer)
Version:               1.0.0
Code Type:             X86-64 (Native)
Parent Process:        Firefly [1640]
Responsible:           Firefly Helper (Renderer) [1644]
User ID:               501

Date/Time:             2021-04-21 20:38:22.510 +0300
OS Version:            Mac OS X 10.13.6 (17G14042)
Report Version:        12
Anonymous UUID:        16584815-B655-B826-FF8B-9B85682C1A59

Sleep/Wake UUID:       00FF6A4E-D086-4969-BF1D-0D96A8B3D4A9

Time Awake Since Boot: 12000 seconds
Time Since Wake:       1800 seconds

System Integrity Protection: disabled

Crashed Thread:        0  CrRendererMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Application Specific Information:
/Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node

Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Firefly.app/Contents/Resources/app.asar.unpacked/public/build/index.node
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by rajivshah3** [comment]
I'll close this so we can merge it with #897
