### ISSUE TITLE
App does not launch on Windows for ARM

### ISSUE THREAD

**Issue by willbaa** [iotaledger/firefly#997]
## Issue description

I keep getting this message when I try run Firefly.
"This App can’t run on your PC. To find a version for your PC, check with the software publisher"

## System specification

Edition: Windows 10
Version: 2004
System Type: 64-bit operating system, ARM-based processing

Reached out to Microsoft and they said it was not a Windows issue but a problem on the publishers side.

**Comment by chon1978** [comment]
I'm too. It does not work on my PC with MacOS 10.13. 
Please help me!

**Comment by Phyloiota** [comment]
> ## Issue description
> 
> I keep getting this message when I try run Firefly.
> "This App can’t run on your PC. To find a version for your PC, check with the software publisher"
> ## System specification
> 
> Edition: Windows 10
> Version: 2004
> System Type: 64-bit operating system, ARM-based processing
> 
> Reached out to Microsoft and they said it was not a Windows issue but a problem on the publishers side.

could you please specify the windows system build? 
    Select the Start button > Settings > System > About . Open About settings.
    Under Device specifications > System type, see if you're running a 32-bit or 64-bit version of Windows.
    Under Windows specifications, check which edition and version of Windows your device is running.

**Comment by willbaa** [comment]
Edition: Windows 10
Version: 2004
OS Build: 19041.928
System Type: 64-bit operating system, ARM-based processing

**Comment by willbaa** [comment]
Hi Rajiv,

I was wondering if you had an estimate on when the Firefly wallet would work on Windows on ARM?

Thanks
